### ISSUE TITLE
Custom translations not working when forcing language

### ISSUE THREAD

**Issue by ligne13** [AmauriC/tarteaucitron.js#1000]
Hi,
I have entered a few custom translations for the english language. It works.

But it does not work when I force the language to english, using :

`var tarteaucitronForceLanguage = 'en';`

It displays the default english translations.

**Comment by AmauriC** [comment]
Hi

This is odd. Can I see the complete installation (or website url)?

**Comment by ligne13** [comment]
Bonjour Amauri,

je continue en français.

Le site est sur une URL de test, confidentielle :-) :
https://fieldbox.treizedev.com/
username : private
password : fieldbox2022!

J'ai finalement retiré la variable qui permet de forcer la langue.
Mais j'ai un autre souci : j'ai beau supprimer manuellement le cookie
tarteaucitron, il réapparaît automatiquement lors d'un refresh de la page.
Le script semble l'ajouter automatiquement... et donc impossible de revoir
la barre de consentement.
Cette vidéo montre le problème :
https://www.loom.com/share/da2b093caf394746bfb486b6c9c7268a

Est-ce normal ?

Merci

*Maxime Freschard*
ligne13.com
mailroseplace.io
06 71 20 31 23


Le sam. 8 oct. 2022 à 13:15, Amauri CHAMPEAUX ***@***.***> a
écrit :

**Comment by AmauriC** [comment]
You use the pro version, to force a locale, it's not with the js variable but with an url parameter on the script tag:

```
<script type="text/javascript" src="https://tarteaucitron.io/load.js?locale=en&domain=xx&uuid=xx"></script>
```
