### ISSUE TITLE
GTM & GA4 événements personnalisés

### ISSUE THREAD

**Issue by francoisriant** [AmauriC/tarteaucitron.js#1005]
Bonjour,

Merci pour TAC, ça aide beaucoup!

Je rencontre pour la première fois un soucis avec TAC:

Sur un site Wordpress, j'ai installé TAC en mode manuel et j'y mis deux services : GTM & GA4

      //GA4
      tarteaucitron.user.gtagUa = '{{ google_analytics_id }}';
      (tarteaucitron.job = tarteaucitron.job || []).push('gtag');
      
      //TagManager
      tarteaucitron.user.googletagmanagerId = '{{google_tag_manager}}';
      (tarteaucitron.job = tarteaucitron.job || []).push('googletagmanager');

Dans la configuration de mon GTM, il y a des événements personnalisés qui vont vers GA4.

Quand j'utilise TAC, les événements personnalisés ne remontent pas dans GA4 mais quand TAC est absent, cela fonctionne.

Je me demandais si vous aviez déjà vu un soucis similaire?

Auriez-vous une piste que je pourrai creuser ?

Merci !

**Comment by AmauriC** [comment]
Les 2 services sont autorisés par l'utilisateur?

Possible d'avoir un exemple d'event?

**Comment by francoisriant** [comment]
Bonjour,

Merci pour la réponse. Oui les deux services sont bien acceptés par l'utilisateur.
dans mes projet j'utilise une petit class pour envoyer des events à GTM

`export default class TagManagerUtils {
  static sendEvent(eventName, eventParams) {
    window.dataLayer = window.dataLayer || [];
    window.dataLayer.push({
      event: eventName,
      ...eventParams,
    });
  }
}
`
Puis j'import ma class et je l'utilise comme ceci
`      TagManagerUtils.sendEvent('sound_player', {
        language_code: lalang,
      });`
