### ISSUE TITLE
Google core web vitals accessibility score getting impacted by non unique IDs on focusable elements

### ISSUE THREAD

**Issue by coatpont** [AmauriC/tarteaucitron.js#1010]
See here as an example via Page Speed Insights: https://pagespeed.web.dev/report?url=https%3A%2F%2Fnominis.cef.fr%2F&form_factor=desktop - decreasing the accessibility score by 2 points.

Two elements (one button, one span) with the same element ID of "Eng88145edrecaptcha" with the same page/DOM.

Thanks for your attention!

**Comment by AmauriC** [comment]
Fixed, thanks ;)

**Comment by coatpont** [comment]
Nice. Thank you!
