### ISSUE TITLE
Google core web vitals performance score getting impacted due to non-minified versions of .js and .css resources

### ISSUE THREAD

**Issue by coatpont** [AmauriC/tarteaucitron.js#1011]
please see here as an example: https://pagespeed.web.dev/report?url=https%3A%2F%2Fnominis.cef.fr%2F&form_factor=desktop

is there a way to load a minified version of the .js and .css resources? I've seen some closed issues on this topic but cannot find the documentation on how to do so.

thanks for your attention

**Comment by AmauriC** [comment]
With pro version there still no min version, it's planned to add it.

**Comment by coatpont** [comment]
thanks - looking forward to it - sounds like a "pro" feature indeed ;-)

**Comment by Skoua** [comment]
Well any decent one would do, Vite uses esbuild which looks to have good perfs and saving.
Thanks for your quick answer!

**Comment by AmauriC** [comment]
It's available 🙂

For the pro version it's live.

For manual version, add this javascript var before loading tarteaucitron: `tarteaucitronUseMin = true;`
