### ISSUE TITLE
Ajout option more pour matomo

### ISSUE THREAD

**Issue by Sylry** [AmauriC/tarteaucitron.js#1015]
Je voudrais ajouter une fonction similaire à celle pour google analytics permettant d'ajouter des options custom à matomo
Quelque chose comme tarteaucitron.user.matomoMore qui serait une fonction appelée si définie

si ça vous intéresse, j'ouvre une PR

**Comment by AmauriC** [comment]
Oui bien sûr, je valide le PR rapidement.

Même si il faudrait trouver un système pour inclure ce genre d'event pour tous les services, le système de "more" fonctionne ;)
