### ISSUE TITLE
tarteaucitron.user.mapscallback n'est pas executé

### ISSUE THREAD

**Issue by Labyala** [AmauriC/tarteaucitron.js#1035]
Bonjour,

j'utilise le plugin WordPress de tarteaucitron.js et j'ai un cas particulier que je n'arrive pas à résoudre: sur un formulaire Gravity Form j'ai ajouté un plugin pour l'autocompletion d'adresse postale ( https://wordpress.org/plugins/gf-google-address-autocomplete/ )

quand tout est activé, j'obtiens une erreur "Google is not defined" car le script google est ajouté par tarteaucitron après le chargement des scripts du plugin donc je comprend que c'est normal mais je n'arrive pas à faire exécuter la fonction du plugin après tarteaucitron.
J'ai essayé avec le code : `<script>tarteaucitron.user.mapscallback = 'initialize';</script>` mais la fonction n'est jamais appelée, je pense que c'est parce que je n'ai pas de map qui s'affiche, l'api google map est uniquement utilisée pour la recherche d'adresse avec places API. J'ai déjà utilisé ce callback avec une google map et cela a très bien marché.

Site de test pour constater l'erreur : https://test.bluemarketing.fr/

Merci pour votre aide.
Sébastien

**Comment by AmauriC** [comment]
Bonjour Sébastien : )

En ajoutant ce code JS ça réactivera le plugin quand tarteaucitron autorise Google Maps:

```
document.addEventListener('googlemaps_loaded', function() {
   setTimeout(function() {
      gform.initializeOnLoaded( function() { jQuery(document).trigger('gform_post_render', [4, 1]) } );
   }, 800);
});
```

**Comment by Labyala** [comment]
super @AmauriC, ça fonctionne parfaitement !
un grand merci
