### ISSUE TITLE
Rename Matomo tracking files

### ISSUE THREAD

**Issue by maze13** [AmauriC/tarteaucitron.js#1036]
In tarteaucitron.js the (deprecated) Matomo tracking files are called. Rename piwik.php to matomo.php and piwik.js to matomo.js.

**Comment by maze13** [comment]
https://github.com/AmauriC/tarteaucitron.js/pull/1037/

**Comment by AmauriC** [comment]
Thanks but is it safe to change it for everyone or some old installations dont have the matomo* files?

**Comment by maze13** [comment]
The renaming process of Matomo seems to be still in progress https://github.com/matomo-org/matomo/issues/12420 but is on the agenda. The renamed files are introduced in Matomo 4 in the end of 2020. Matomo 3 LTS is unsupported and expired on December 1st 2021.

**Comment by maze13** [comment]
Alternatively there could be two services. The one for Piwik and the other for Matomo.

**Comment by AmauriC** [comment]
There is the "Matomo cloud" service.
I think I just wrongly renamed Piwik to Matomo.

**Comment by maze13** [comment]
It's a bit confusing. :) There are four Piwik / Matomo services. Two for tracking with a cloud service:
- tarteaucitron.services.matomocloud
- tarteaucitron.services.piwikpro

The other two
- tarteaucitron.services.matomo
- tarteaucitron.services.matomohightrack
are similar, but use in one service the piwik.php tracker in the other matomo.php. But both are called matomo*. And they differ in other parameter, e.g. the setDoNotTrack option.
