### ISSUE TITLE
Flickr

### ISSUE THREAD

**Issue by Canarithy** [AmauriC/tarteaucitron.js#104]
Bonjour,
Serait-il possible d'ajouter Flickr dans tarteaucitron.js ?
Merci d'avance.

**Comment by pierretux** [comment]
Bonjour,

J'ai aussi le besoin, comment le rajouté ?

Cdt

**Comment by AmauriC** [comment]
Bonjour,

Il me faut le marqueur HTML actuel du service pour que je vois s'il est possible de l'ajouter ; )

**Comment by pierretux** [comment]
Ah comment je te trouve ça ?
Le code ajouté dans l'article est par exemple :
`<a data-flickr-embed="true" href="https://www.flickr.com/photos/affairessocialessante/47651512342/" title="Stratégie pauvreté : conférence régionale en Martinique"><img src="https://live.staticflickr.com/65535/47651512342_00325e58b1_k.jpg" width="2048" height="1362" alt="Stratégie pauvreté : conférence régionale en Martinique"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>`

**Comment by AmauriC** [comment]
Sur le site flickr j'imagine, je ne sais pas comment vous intégrez ce service sur votre site actuellement.

**Comment by pierretux** [comment]
Alors c'est le code mon exemple que j'utilise.
