### ISSUE TITLE
Est-ce qu'il y a du support pour Tarte au Citron ? Problème d'association des conversions avec linkedin ads

### ISSUE THREAD

**Issue by Startouf** [AmauriC/tarteaucitron.js#1045]
Bonjour, j'ai un problème pour faire fonctionner correctement certains services de pub, j'ai l'impression que cela vient de tarte au citron mais je n'en suis pas certain et j'aurais aimé pouvoir discuter rapidement avec la communauté.

Il n'y a aucune information dans le readme concernant le support : un potentiel slack, forum, etc. où je pourrais soumettre des problématiques... si ça existe ?

Faute d'avoir trouvé, je me permet d'indiquer rapidment ma problématique ici : 
J'ai installé linkedin ads via GTM 
```
<script type="text/javascript">
        tarteaucitron.user.linkedininsighttag = 'xxxx';
        (tarteaucitron.job = tarteaucitron.job || []).push('linkedininsighttag');
</script>
```
Et avec des triggers event-specifics de ce type
```
<script type="application/javascript">
  window.lintrk("track", { "conversion_id": xxxx });
</script>
```
Quand nos utilisateurs cliquent sur une pub linkedin, il sont bien redirigé sur notre site avec un paramètre ?li_fat_id=xxx qui est sauvegardé dans un cookie du même nom (j'ose croire que c'est cet ID très mal documenté qui est important pour les conversions), et les tags GTM appropriés sont fired, mais pour autant je vois que tarte au citron que "linkedin n'a installé aucun cookie" et dans l'interface linkedin ads, je vois bien remonter des évènements de conversion individuels, mais ils ne se rattachent pas à mes campagnes.

![Screenshot 2023-01-11 at 14 43 19](https://user-images.githubusercontent.com/7388889/211821754-2272afc4-0a20-4a4f-9e9b-d5379ca23473.png)
![Screenshot 2023-01-11 at 14 24 32](https://user-images.githubusercontent.com/7388889/211821825-78f1d0b5-781f-457f-a2b0-cec26c6f0669.png)
![Screenshot 2023-01-11 at 14 24 20](https://user-images.githubusercontent.com/7388889/211821830-2a0ebda3-fbf2-4afa-bcf5-da84a4b09776.png)

Any idea ? Notre site : https://www.myjobglasses.com

**Comment by AmauriC** [comment]
Bonjour,

Première chose, GTM doit normalement être chargé après avoir eu le consentement de l'internaute, comme pour tous les produits Google ;) 

Sur Linkedin et le suivi des conversions je ne l'utilise pas donc difficile d'aider sur ce point mais peut-être que quelqu'un ici aura la solution.

Pour le cookie `li_fat_id` il est posé sur le site ou sur le domaine linkedin?
L'important est de bloquer Linkedin tant que l'utilisateur ne l'accepte pas.

**Comment by Startouf** [comment]
Lorsque nous générons une publicité linkedin et que nous ajoutons un lien qui ramène sur notre site, Linkedin semble ajouter un paramètre `&li_fat_id=xxx` sur le lien quand un utilisateur clique sur la pub.

Si j'ai bien compris (à prendre avec des grosses pincettes car je n'ai pas trouvé de doc technique), le tag Linkedin insight exécute un morceau de JS qui récupère ce paramètre de l'URL courante, et l'enregistre dans un cookie ayant le même nom. Je me doute que ce cookie est ensuite transmis lors d'évènements de conversion (quand on effectue par la suite une action de conversion sur notre site, le cookie li_fat_id est envoyé avec pour associer l'évènement de conversion à la publicité qui a amené l'utilisateur sur le site)

Donc le cookie `li_fat_id` semble être déposé par le tag linkedin insight sur notre site

**Comment by AmauriC** [comment]
Je viens d'ajouter ce cookie à la liste de ceux utilisés par Linkedin Insight ;)
