### ISSUE TITLE
Fermeture automatique quand on accepte/refuse tout

### ISSUE THREAD

**Issue by Philalawst** [AmauriC/tarteaucitron.js#1049]
Est-ce qu'il est possible de fermer automatiquement la fenêtre tarteaucitron lorsqu'on clique sur le bouton "Accepter tout" ou "Refuser tout" ?

**Comment by AmauriC** [comment]
Une solution avec jQuery:

```
window.addEventListener('tac.root_available', function() {
    jQuery('#tarteaucitronAllAllowed').html('Tout accepter et fermer');
    jQuery('#tarteaucitronAllDenied').html('Tout refuser et fermer');
    jQuery('#tarteaucitronAllAllowed, #tarteaucitronAllDenied').on('click', function(){setTimeout(tarteaucitron.userInterface.closePanel, 500);});
});
```

**Comment by Philalawst** [comment]
Thanks a lot for the quick answer !!!

in pure javascript

window.addEventListener('tac.root_available', function() {
      document.querySelector('#tarteaucitronAllAllowed').innerHTML = ('Tout accepter et fermer');
      document.querySelector('#tarteaucitronAllDenied').innerHTML = ('Tout refuser et fermer');

      let cbox = document.querySelectorAll("#tarteaucitronAllAllowed, #tarteaucitronAllDenied");
      cbox.forEach(box => {
        box.addEventListener('click', () =>  setTimeout(tarteaucitron.userInterface.closePanel, 500) );
      });
});

**Comment by marcaureleg** [comment]
Très utile ce petit bout de code !

Cette option de fermeture automatique de la fenêtre lors de l'acceptation ou du refus global des services ne devrait-elle pas être une option proposée par défaut ?
