### ISSUE TITLE
Affichage video youtube avec react

### ISSUE THREAD

**Issue by Lucas-allard** [AmauriC/tarteaucitron.js#1051]
Bonjour à tous.

J'utilise cet lib magnifique pour la gestion de mes cookies, cependant je suis confronté a un problème, j'ai une vidéo youtube de présentation sur la homepage de mon site web, jusqu'a la tout va bien j'ai réussi a initialiser les cookies pour youtubes, cependant je ne parviens pas gerer l'affichage, j'ai pourtant suivi le guide d'installation à la lettre.

Voici comment je m'y suis pris :  
```
import "./video.scss";
import React from "react";

function Video({ videoId }) {


  return (

      <div className="youtube_player" videoid={videoId} width="560" height="315" theme="light" rel="0" controls="1"
           showinfo="1" autoPlay="0"></div>
  );
}

export default Video;
```

Ma div s'affiche bien mais je n'ai rien dedans...

Merci pour votre aide !

**Comment by AmauriC** [comment]
Je ne suis pas spécialiste react mais le `className` au lieu de `class` c'est normal?

Le paramètre pour le video id prend une majuscule sur le id: `videoID`

**Comment by Lucas-allard** [comment]
Merci d'avoir pris le temps de me répondre, effectivement le className est
tout a fait Normal c'est comme ça que l'ont défini une classe sur React,
malheureusement je ne peux pas laisser le VideoID comme sur la doc car
react ne le comprends pas...



Le mar. 17 janv. 2023, 14:11, Amauri CHAMPEAUX ***@***.***> a
écrit :

**Comment by AmauriC** [comment]
C'est sûrement le problème.
https://github.com/AmauriC/tarteaucitron.js/blob/ef8c443041d48a4ba05c76f3a90b3831bb4868d7/tarteaucitron.services.js#L4165

Dans l'immédiat je ne vois pas comment modifier ça :/

**Comment by GeekCornerGH** [comment]
Essaie [cette réponse](https://stackoverflow.com/questions/54869777/react-typescript-adding-custom-attribute)

**Comment by Lucas-allard** [comment]
> Essaie [cette réponse](https://stackoverflow.com/questions/54869777/react-typescript-adding-custom-attribute)

J'ai essayé mais ca ne change rien au problème, j'ai contourner le problème en récupérant les cookies directement et faire mon traitement en fonction du cookie
