### ISSUE TITLE
Eulerian

### ISSUE THREAD

**Issue by pierretux** [AmauriC/tarteaucitron.js#1054]
Amauri,

On va passer les ministères sur Eulerian mais il sont pas ok avec ton code : https://eulerian.wiki/doku.php?id=fr:setup:cmp:tarteaucitron&s[]=tarteaucitron
Tu penses l'amélioré ou ce n'est pas prévu ?

Merci pour ton boulot

**Comment by AmauriC** [comment]
Salut,

On en avait déjà discuté, de ce que je comprend, l'intégration Eulerian ne fait rien de plus qu'afficher le service dans le panel? Tout le système d'autorisation est ailleurs?
Si oui ce n'est pas le fonctionnement de tarteaucitron, le consentement doit être donné au niveau de tarteaucitron et si c'est refusé, il n'y a tout simplement aucun chargement et non un transfert vers un autre CMP qui va lui décider de la suite :/

**Comment by AmauriC** [comment]
https://github.com/AmauriC/tarteaucitron.js/issues/1022

**Comment by guillaumef** [comment]
Bonjour @pierretux ,
J'ai explicité de manière exhaustive dans cette [issue](https://github.com/AmauriC/tarteaucitron.js/issues/1022) et surtout dans notre documentation que vous avez lié plus haut pour quelles raisons il faut utiliser la version de notre doc.
Nous ne sommes à priori pas les seuls bloqués ([matomo](https://github.com/AmauriC/tarteaucitron.js/issues/1028)).
Je vous invite à passer via le support Eulerian pour vous donner explications/solutions et que nous ayons la trace de ces échanges liés à l'entité que vous représentez.
Merci à vous.

**Comment by AmauriC** [comment]
@guillaumef La problématique concernant Matomo est différente.
Le service Eulerian sur tarteaucitron est comme tous les autres et permet de charger, si l'utilisateur l'autorise, le marqueur de base de votre service (https://eulerian.wiki/doku.php?id=fr:setup:onsite_setup:tag_installation_guide#partie_1decouverte_du_tag_standard).

Je ne peux pas ajouter ce que vous proposez, tarteaucitron est le tiers de confiance qui charge ou non le service, ce n'est pas un pont pour faire la configuration de votre côté.

**Comment by pierretux** [comment]
@guillaumef Pourquoi ça fonctionne avec ATinternet sans problème ?
- j'accepte => tout fonctionne
- je refuse => cela limite les infos
- je bloque avec un optin-optout => rien sera envoyer voir le bouton en bas de cette page https://sante.gouv.fr/ministere/article/donnees-personnelles-et-cookies pour exemple

Pourquoi donc ne fonctionnez vous pas comme ça ?
Merci

**Comment by guillaumef** [comment]
Voici plus explicitement ce qu'il se produit avec l'implémentation classique TAC... donc l'implémentation que vous spécifiez de ATinternet (il s'agit de Piano Analytics - société de droit américain - cloud américain):

1. En cas de non-recueil de consentement - c'est à dire presque toutes les visites à une page et autres si la personne ne prend pas la peine de répondre au consentement - il n'y a aucun appel libéré par TAC (car c'est manichéen: soit nécessitant l'autorisation, soit sans autorisation). Donc les plateformes exemptées de recueil, validées par la CNIL, ne peuvent pas fonctionner correctement. C'est un problème majeur inacceptable pour l'exhaustivité des données et représenter 30% des volumes de visite.
2. TAC ne nous permet pas de respecter la RGPD. Eulerian est plus qu'un système d'analytics simple et dispose de modules d'activation, nous avons l'obligation de pouvoir rétrocéder et appliquer les refus/accords recueillis par la CMP à tous les tiers qui seraient succeptibles d'être configurés en appel sur notre plateforme (TagManagement, Server2Server, ...). Structurellement, TAC ne rétrocéde au service que sa propre autorisation.

L'implémentation du service eulerian dans TAC que **nous fournissons** sera supportée et estimons compléte, mais nous ne souhaitons pas dégrader nos systèmes à cause d'une limitation CMP alors que des dizaines d'autres CMP professionnelles existent et remplissent les fonctionnalités de base exigées.
Je vous invite à passer sur le support Eulerian au besoin.
Bon week-end.
