### ISSUE TITLE
Service Lead Forensics

### ISSUE THREAD

**Issue by schullergraphic** [AmauriC/tarteaucitron.js#1056]
Bonjour,
Le service Lead Forensics demande la mise en place de ce code pour un compte de test:

&lt;script type="text/javascript" src="https://secure.visionarybusinessacumen.com/js/{$ID}.js" >
&lt;/script>

&lt;noscript>
&lt;img alt="" src="https://secure.visionary-enterprise-wisdom.com/{$ID}.png" style="display:none;" />
&lt;/noscript>

Cdlt,

**Comment by AmauriC** [comment]
Bonjour,

Le tag actuellement sur tarteaucitron utilise l'url `https://secure.team8save.com/js/sc/ID.js`

Comme vous avez un contact avec le support vous pouvez leur demander si il y a une différence avec `https://secure.visionarybusinessacumen.com/js/ID.js` ?

Merci

**Comment by schullergraphic** [comment]
C'est en cours...

**Comment by schullergraphic** [comment]
Bonjour Amauri,
Voici la réponse de leadforensic.com:

**"These URLs are synonyms and point to the same backend servers."**

Cdlt,

**Comment by schullergraphic** [comment]
Bonjour Amauri,
Le service est bien activé, le cookie bien accepté mais je ne vois pas l'appel au serveur secure.team8save.com dans l'inspecteur réseau (alors que je vois bien les appels Google).
Est-ce normal ?

**Comment by AmauriC** [comment]
Avec le service tarteaucitron c'est `secure.visionarybusinessacumen.com` mais c'est la même chose d'après la réponse de leur support.

**Comment by schullergraphic** [comment]
Oui, mais je ne vois aucun appel, ni à "secure.team8save.com", ni à "secure.visionarybusinessacumen.com" depuis l'inspecteur du navigateur
Le site: https://corlet.fr/
Le cookie tarteaucitron est ok: 
![image](https://user-images.githubusercontent.com/15612623/216312786-9e2cede0-deb2-45e5-97fe-9fc12388c8ab.png)

**Comment by AmauriC** [comment]
En effet il y a un souci, ce sera corrigé demain.

**Comment by AmauriC** [comment]
C'est corrigé, ce sera dispo sur le v pro dans quelques heures 👍

**Comment by schullergraphic** [comment]
Bonjour Amauri,
Je vois bien l'appel. Je check avec LeadForensic si c'est bon de leur coté
Merci
Cdlt,
