### ISSUE TITLE
Tag ?

### ISSUE THREAD

**Issue by pierretux** [AmauriC/tarteaucitron.js#1058]
@AmauriC

coucou, tu penses mettre un tag en place d'ici combien de temps ?

Merci

**Comment by AmauriC** [comment]
Dès que j'ai ajouté les services en attente d'ajout, si pas d'imprévu je m'en occupe ce w-e :)

**Comment by AmauriC** [comment]
C'est dispo https://github.com/AmauriC/tarteaucitron.js/releases/tag/v1.10.0 👍
