### ISSUE TITLE
Balise gtag en double avec TAC comme gestionnaire de consentement

### ISSUE THREAD

**Issue by Facyla** [AmauriC/tarteaucitron.js#1059]
Bonjour, 

J'utilise TAC (version à jour à cette date) pour gérer le consentement de services qui sont ensuite injectés par Google Tag Manager (GTM). Pour cela le principe est d'interdire à GTM d'injecter des balises tant que le cookie tarteaucitron ne contient pas les autorisation explicites, ce qui se fait côté GTM avec une variable qui lit les données du cookie défini par TAC et utilise un regex pour lire les autorisations données. 

TAC est configuré de manière classique par ailleurs, les seules différences étant que GTM (qui ne dépose pas de cookie pour son propre usage) ne fait pas partie de la liste des services, et que les services utilisés sont configurés sans injecter le code de suivi : la config des services ressemble à : 
`// Google Analytics GA4
(tarteaucitron.job = tarteaucitron.job || []).push('analytics');
// Google Ads
(tarteaucitron.job = tarteaucitron.job || []).push('googleads');`

L'ensemble fonctionne bien : aucune balise n'est injectée par défaut, et elles se chargent comme attendu en fonction des consentements donnés. 

Cependant la balise de Google Analytics est chargée en double : 1 fois correctement par GTM, et une autre fois par TAC, d'une manière non  fonctionnelle (normal : le code du service n'est pas fourni dans la config JS de TAC). 

Je ne comprends pas ce qui se passe car il me semblait que ".push('analytics')" se contente d'ajouter ce service à la liste des consentements demandés, mais ne charge pas le code de suivi. 

=> Est-ce la bonne manière de demander le consentement sans injecter les balises ? et sinon comment peut-on faire pour que TAC ne serve que à gérer les consentements mais pas les balises ?

**Comment by AmauriC** [comment]
Bonjour,

C'est le problème, tac n'est pas pensé pour être un simple relai du consentement. C'est un tag manager qui charge ou non le contenu, ce n'est pas pensé pour déléguer ce chargement à GTM ;)

**Comment by Facyla** [comment]
Merci du retour rapide ! 
Bien compris, c'est pas l'usage habituel ;)

Je pense que dans le cas qui m'intéresse ici une bonne manière de faire serait soit de définir un service personnalisé avec une clef "js" vide, soit encore mieux de surcharger le service concerné pour remplacer cette clef ; ça ne devrait pas poser de difficulté particulière je suppose, avec quelque chose du type : `tarteaucitron.services.analytics.js = function () {}`

Je regarderai ça en début de semaine prochaine, bon weekend ! 
(je ferai un retour sur le ticket)

**Comment by Facyla** [comment]
Bonjour, 

J'ai réussi à obtenir le résultat souhaité en surchargeant les services correspondants `(tarteaucitron.services.googleads.js = function () {};`)
de sorte que les balises ne soient plus injectées. 

Au passage, l'utilisation de useExternalJS (true) a permis d'alléger considérablement le poids des scripts chargés, en ne gardant que les services souhaités dans la liste de définition. 

Merci pour l'aiguillage, et surtout pour cette délicieuse bibliothèque !-)
