### ISSUE TITLE
Définir la langue

### ISSUE THREAD

**Issue by DavidHorizon** [AmauriC/tarteaucitron.js#106]
Bonjour,

Je n'ai vu aucune option pour définir la langue utilisée, est-ce possible ?
Et si je comprend bien la langue est définie en fonction des réglages navigateur de l'utilisateur ?

**Comment by GuillaumeKadolis** [comment]
Est-ce ce que tu cherches ? (cf la doc)

Vous pouvez forcer la langue du bandeau et du panneau de contrôle via une variable Javascript à placer au tout début de la balise <head>, AVANT le bloc principal.
Si vous spécifiez une langue non supportée, la langue du navigateur sera sélectionnée, ou par défaut, l'anglais.

`<script type="text/javascript">
var tarteaucitronForceLanguage = 'fr'; /* supported: fr, en, de, es, it, pt, pl, ru */
</script>
`

**Comment by DavidHorizon** [comment]
Tout à fait, c'est ce que je cherchais. Merci.

PS :  Il ne me semble pas que ce soit écrit dans la doc.
