### ISSUE TITLE
Possibilité d'avoir une url de politique de confidentialité par locale en pro + automatique

### ISSUE THREAD

**Issue by laura14424** [AmauriC/tarteaucitron.js#1060]
Hello, 

Sur la version PRO et sur un site en mode automatique, il m'a été impossible de trouver un moyen d'avoir une URL de politique de confidentialité différente par langue.
Pour l'instant, j'ai bypasser le soucis en ayant une configuration pour le domain .fr et une pour le domaine .en sachant qu'à part cette URL, tout le reste de la configuration est identique. 
Est-ce que c'est la seule solution pour mon cas ? Si ça l'est, est-ce qu'il est prévu que ça soit géré dans les futures versions sans avoir à faire deux configurations différentes ?

Merci beaucoup

**Comment by AmauriC** [comment]
Hello
En effet ce n'est pas encore prévu. 
La solution est de mettre un lien vers une page qui va gérer la redirection en fonction de la langue.
Il est prévu de l'ajouter pour une prochaine version ;)
