### ISSUE TITLE
Inconsistent behavior of  `matomo` service compared with `matomocloud`

### ISSUE THREAD

**Issue by Dynnammo** [AmauriC/tarteaucitron.js#1064]
:warning: Newbie on this repository, please excuse the description that may seem obscure, I can provide as much detail as possible in order to get this issue solved.

**Context**
The Matomo service seems to have changed recently : #1028 . As we use it in many of our websites, we are currently struggling with its behavior: normally, 2 cookies are created when Matomo is used (`_pk_ses` and `_pk_id`). What is stricking is that when using the former `matomo` service, the cookie banner removes the `_pk_ses` but not the `_pk_id`.

As we tried to use to install the new `matomocloud` service, neither of these cookies are created.

It may finally require another issue, but the former `matomo` service that went created for previous website seems to be not modifiable anymore
![image](https://user-images.githubusercontent.com/33259633/217226671-9d046a4b-9071-4d62-a22b-85dfd91ee368.png)

**Comment by AmauriC** [comment]
Hey

Old Matomo and Matomo cloud share the same script but the configuration need one more argument for the cloud version.

Can you share your Matomo cloud settings?

**Comment by AmauriC** [comment]
Précision: le service est "deprecated" parce qu'il n'est plus utile de le maintenir et fait doublon avec le service Matomo Cloud.
Ce n'est modifiable sur l'interface tarteaucitron.io mais **c'est totalement fonctionnel et rien ne change sur les sites qui utilisent toujours l'ancien service Matomo**.

Clarification: the service is "deprecated" because it is no longer useful to maintain it and doubles up with the Matomo Cloud service.
It cannot be modified on the tarteaucitron.io interface but **it is fully functional and nothing changes on sites that are still using the old Matomo service**.

**Comment by Thomasfds** [comment]
Bonjour,

Si nous utilisons notre propre installation matomo, nous devons mettre le code Matomo Cloud sur nos sites ? Car cela ne s'affiche pas dans la personnalisation des cookies.

![image](https://user-images.githubusercontent.com/48243771/218118977-4df364e2-816a-4104-9ef3-61b2ce40c0b3.png)

**Comment by AmauriC** [comment]
Vous avez ajouté le tag tarteaucitron pour charger le service? Possible d'avoir l'url de la page?

**Comment by Thomasfds** [comment]
> Vous avez ajouté le tag tarteaucitron pour charger le service? Possible d'avoir l'url de la page?

Oui, j'ai bien tous ajouté, https://playgame-tracker.com/

Le lien du fichier de config de tarte au citron :
https://playgame-tracker.com/assets/js/tarteaucitrons.js

**Comment by AmauriC** [comment]
La version est trop ancienne, passez à la 1.10.0:
```
https://cdn.jsdelivr.net/gh/AmauriC/tarteaucitron.js@1.10.0/tarteaucitron.js
```

**Comment by Thomasfds** [comment]
> https://cdn.jsdelivr.net/gh/AmauriC/tarteaucitron.js@1.10.0/tarteaucitron.js

En effet cela fonctionne mieux merci !!

**Comment by Thomasfds** [comment]
> La version est trop ancienne, passez à la 1.10.0:
> 
> ```
> https://cdn.jsdelivr.net/gh/AmauriC/tarteaucitron.js@1.10.0/tarteaucitron.js
> ```

J'ai mis à jour mais je ne reçoit toujours pas les données depuis mon administration :/

**Comment by AmauriC** [comment]
Il y a bien un envoi vers https://analytics.thomasfds.fr/matomo.php pourtant. Peut-être un délai de prise en compte?
