### ISSUE TITLE
Adding custom service -> new cookie

### ISSUE THREAD

**Issue by fvsadem** [AmauriC/tarteaucitron.js#1065]
Hi,

It's seems that when i add a new custom service, a new cookie is generated in the browser.
The problem is that it demands the consent all the time on all pages... what matter i choose to answer (accept or deni).

The old cookie still exists but there is another one (with the same name) for the new.
I only can see the cookie domain name is different (.exemple.com and www.exemple.com).
The old cookie is on www.exemple.com contains all the service except the new one.
The new cookie is on .example.com and contains only the new service.

My custom service has been register like so :
```
(tarteaucitron.job = tarteaucitron.job || []).push('test_service');

tarteaucitron.services.test_service = {
    "key": "test_service",
    "type": "analytic",
    "name": "Test Service",
    "uri": "",
    "needConsent": true,
    "readmoreLink": "",
    "cookies": [],
    "js": function () {
        dataLayer.push({'event': 'test_service'});
    },
};

```

I have to clear cookies to stop to show the consent popup.
After that "clear" process, everything is working great. cookie is on www.example.com (with my new custom service).

Sorry, i can't reproduce the bug anymore... (due to cookie clearing)
I will add some captures on the issue if my customers has this bug.

Thanks 

Version: 1.9.3

**Comment by fvsadem** [comment]
I don't know why but github don't want me to write correctly my code :
tarteaucitron.services.test_service = {
    "key": "test_service",
    "type": "analytic",
    "name": "Test Service",
    "uri": "",
    "needConsent": true,
    "readmoreLink": "",
    "cookies": [],
    "js": function () {
        dataLayer.push({'event': 'test_service'});
    },
};

**Comment by AmauriC** [comment]
Hi

The new service is not the problem, it's probably because on the main configuration you changed the `cookieDomain` and it conflict with the old cookie.

Clearing the cookies is the solution to fix this issue ;)

**Comment by fvsadem** [comment]
@AmauriC 

My customer start calling me about that... 

Is there any other solution I can apply, other than deleting cookies?

I never add cookieDomain parameter on the init function.
Maybe if i force my domain ?

**Comment by AmauriC** [comment]
Set the cookie domain + change the cookie name it will start with a fresh cookie:

```
"cookieDomain": ".example.com",
"cookieName": "rgpd_cookie",
```

**Comment by fvsadem** [comment]
Thanks @AmauriC 

it works !
