### ISSUE TITLE
Erreurs Sonar Cloud et CodeQL

### ISSUE THREAD

**Issue by AlaricRG** [AmauriC/tarteaucitron.js#1067]
Mon équipe et moi utilisions [Sonar Cloud](https://www.sonarsource.com/products/sonarcloud/) (service d'analyse de code) pour travailler sur [ce projet](https://github.com/DroitPluriel-appli/justicie/), et lorsque nous avons ajouté les scripts de TarteAuCitron il nous a remonté plusieurs erreurs, dont 2 considérées comme "Bug majeur".

Tous les détails sont accessibles [ici](https://sonarcloud.io/project/issues?resolved=false&types=BUG&pullRequest=66&id=DroitPluriel-appli_justice-plurielle).

Directement dans Github, CodeQL nous a également remonté 6 erreurs et nous avons constaté que la version de CodeQL n'était pas à jour (TarteAuCitron est encore en [v1 qui est dépréciée](https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/)).

Dans la pratique nous n'avons constaté aucun bug, mais nous préférons quand même remonter l'info 🙂

**Comment by AmauriC** [comment]
Merci pour le retour, je vais corriger mais ce n'est pas majeur comme problème.

Ca change l'opacité d'un element 2x de suite et il y a un appel qui n'est pas nécessaire mais ça ne provoque aucune erreur., c'est par contre inesthétique niveau code je l'accorde 🙃
