### ISSUE TITLE
Google Maps - Position "Google Maps est désactivé" 

### ISSUE THREAD

**Issue by sylbal** [AmauriC/tarteaucitron.js#1068]
Bonjour,

Lorsque les cookies ne sont pas acceptés, le panneau d'information indiquant que Google Maps n'a pas été accepté semble systématiquement se positionner tout en bas à gauche et non dans l'espace dédié à l'affichage de la carte (version pro - mode auto).
Ce qui peut être déroutant pour l'utilisateur avec une zone blanche parfois conséquente et aucun message visible dans l'écran.

Existe-t-il un moyen d'indiquer l'élément qui affiche la carte et ainsi afficher le message dans cet espace ?

Exemple avec un affichage sous le pieds de page

<img width="393" alt="image" src="https://user-images.githubusercontent.com/621070/220336991-e673e69b-3fbb-46e2-a0bf-ef18f443b5ad.png">

**Comment by sylbal** [comment]
Nous avons contourné le comportement via une positionnement CSS sur la classe `tarteaucitron-magic-block-googlemaps` mais peut être qu'une solution plus élégante est possible.

**Comment by AmauriC** [comment]
La div `tarteaucitron-magic-block-googlemaps` est ajouté par le mode auto à la place du tag javascript de google maps.

En mettant le tag javascript à l'endroit où la carte s'affiche, le call to action sera bien placé ;)
