### ISSUE TITLE
tarteaucitronRoot is not injected into document when setup via Tag Manager Consent initialization

### ISSUE THREAD

**Issue by ambroisemaupate** [AmauriC/tarteaucitron.js#1072]
I need to setup tarteaucitron within Google Tag Manager to inject cookie consent banner on a website I manage and on ticketing shop  (which I don't manage) sharing to same root domain. The same cookie-banner must show on `myrootdomain.com` and `billetterie.myrootdomain.com`. That's why I inject tarteaucitron with GTM and GTM is always loaded but with no services unless consented.

I created a special GTM tag on `Consent initialization` step:

![image](https://user-images.githubusercontent.com/380026/222743445-c8c2bc00-52f0-4ed3-94df-8e49a2ad5a66.png)

```html
<script id="inject-tarteaucitron">
var tarteaucitronForceCDN = "https://cdn.jsdelivr.net/npm/tarteaucitronjs@1.10.0/"
var s = document.createElement('script');
var r = false;
s.type = 'text/javascript';
s.src = 'https://cdn.jsdelivr.net/npm/tarteaucitronjs@1.10.0/tarteaucitron.min.js';
s.onerror = function(err) {
    reject(err, s);
};
s.onload = s.onreadystatechange = function() {
    if (!r && tarteaucitron) {
        r = true;

        console.log('[tarteaucitron] init');
        tarteaucitron.init({
            "privacyUrl": "https://www.myrootdomain.com/protection-des-donnees", /* Privacy policy url */
            "hashtag": "#cookie_consent", /* Open the panel with this hashtag */
            "cookieName": "onl_cookie_consent", /* Cookie name */
            "orientation": "bottom", /* Banner position (top - bottom) */
            "groupServices": false, /* Group services by category */
            "showAlertSmall": false, /* Show the small banner on bottom right */
            "cookieslist": false, /* Show the cookie list */
            "closePopup": false, /* Show a close X on the banner */
            "showIcon": false, /* Show cookie icon to manage cookies */
            //"iconSrc": "", /* Optional: URL or base64 encoded image */
            "iconPosition": "BottomLeft", /* BottomRight, BottomLeft, TopRight and TopLeft */
            "adblocker": false, /* Show a Warning if an adblocker is detected */
            "DenyAllCta" : true, /* Show the deny all button */
            "AcceptAllCta" : true, /* Show the accept all button when highPrivacy on */
            "highPrivacy": true, /* HIGHLY RECOMMENDED Disable auto consent */
            "handleBrowserDNTRequest": false, /* If Do Not Track == 1, disallow all */
            "removeCredit": true, /* Remove credit link */
            "moreInfoLink": false, /* Show more info link */
            "useExternalCss": false, /* If false, the tarteaucitron.css file will be loaded */
            "useExternalJs": false, /* If false, the tarteaucitron.js file will be loaded */
            "cookieDomain": "myrootdomain.com", /* Shared cookie for multisite */
            "readmoreLink": "", /* Change the default read-more link */
            "mandatory": true, /* Show a message about mandatory cookies */
        });

        console.log('[tarteaucitron] services config');
        // Facebook px
        tarteaucitron.user.facebookpixelId = 'xxxxxxxxxxxxxxxxxx';
        tarteaucitron.user.facebookpixelMore = function () {
            console.log('[tarteaucitron] facebookpixel injected', fbq);
        };
        (tarteaucitron.job = tarteaucitron.job || []).push('facebookpixel');

        document.addEventListener('facebookpixel_loaded', function () {
            console.log('[tarteaucitron] facebookpixel_loaded');
            if (dataLayer) {
                dataLayer.push({'event':'facebookpixel_loaded'});
            }
        });
        document.addEventListener('tac.root_available', function () {
            console.log('[tarteaucitron] root_available');
        });

        if (dataLayer) {
            dataLayer.push({'event':'tarteaucitronReady'});
        }
    }
};
var t = document.getElementsByTagName('script')[0];
t.parentElement.insertBefore(s, t);
</script>
```

GTM is well loaded and my *tag* is triggered on `Consent initialization` step, then I see *tarteaucitron* script been loaded by GTM:

![image](https://user-images.githubusercontent.com/380026/222744705-e7806059-6338-4a25-b221-3c36d7efbc0b.png)

When I preview GTM I see tarteaucitron scripts and services configuration executed (console logs):
![image](https://user-images.githubusercontent.com/380026/222743727-9623a7bd-8d1c-4495-bfd6-fd5a4b45618a.png)

But `#tarteaucitronRoot` element is never injected into document. `tac.root_available` event is never triggered. 
My `facebookpixel` service is not triggered as well (`fbq` is undefined).

**Comment by AmauriC** [comment]
The use of GTM to load tac is a bad practice.

What is the website url?

**Comment by ambroisemaupate** [comment]
Why is it a bad practice ? A bad code practice or bad GPDR practice ?

If every tags are injected by TAC after GTM consent initialization, no tracker and cookie may be stored in session for current user. Even if GTM is loaded without consent.

I cannot share website URL publicly.

But after reading TAC source code, I found that TAC is executed after a `load` event from document.
As TAC is init by GTM, main window `load` has already been triggered and TAC's `loadEvent` method is never called.

If  I add:

```js
// Force load AFTER init to avoid losing custom configuration
console.log('[tarteaucitron] force trigger load event');
tarteaucitron.initEvents.loadEvent(false);
```

After `tarteaucitron.init` everything works now.

![image](https://user-images.githubusercontent.com/380026/222755614-4956d02f-6417-448e-aa7d-b7cc60a8e6ec.png)

**Comment by AmauriC** [comment]
Bad practice about GDPR, GTM is not compliant to be loaded without consent, just for your information.
Nice if you fixed the problem ;)

**Comment by ambroisemaupate** [comment]
Do you have any sources about that @AmauriC? I'm curious and I can't find any article saying that GTM *without any tag* is not GDPR compliant.

In fact, proprietary consent managers such as *Axeptio* or *CookieBot* are using GTM to trigger user consent management, so GTM is loaded on website **before** any consent.

I don't see any interest into using GTM if it is not GDPR-compliant. Because it would require to setup TAC and services directly on your website code. Or worse if you only setup GTM service with TAC on website, once you consented to GTM, user wouldn't consent for any additional tags injected by GTM.

**Comment by AmauriC** [comment]
Free GTM is not free for the user, google use datas.

I know a lot of good CMP like axeptio use GTM, I'm not ok with that, they know my position.

Maybe it's too much from my side but it's accepted by the tarteaucitron community.
