### ISSUE TITLE
Ajouter des options à la config GA4

### ISSUE THREAD

**Issue by OlivierTortel** [AmauriC/tarteaucitron.js#1074]
Bonjour, nous souhaiterions ajouter des options à la configuration de GA4 dans tarteaucitron
Notamment l'ajout de l'option "send_page_view: false"
A cet endroit là : https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.services.js#L2637
Merci par avance de votre retour

**Comment by AmauriC** [comment]
Bonjour,
J'essaierai de m'en occuper mais si vous pouvez proposer un PR ça irait plus vite ;)
