### ISSUE TITLE
Le service Adobe analytics ne fonctionne pas

### ISSUE THREAD

**Issue by elodiegrondin** [AmauriC/tarteaucitron.js#1075]
Bonjour,

J'ai un souci avec le service _adobe analytics_, le src n'est pas correct. Il semblerait qu'il manque deux parties dans l'URL.

Voici ce que j'obtiens :
`<script id="" async="" src="//assets.adobedtm.com/launch-zzzzzzzzzzzz.min.js"></script>`

Alors que je devrais recevoir ceci :
`<script src="https://assets.adobedtm.com/xxxxxxxxxxxx/yyyyyyyyyyyy/launch-zzzzzzzzzzzz.min.js" async></script>`

Dans mon template, j'ai une variable qui contient uniquement zzzzzzzzzzzz (adobeanalyticskey) :

```
  {% if seo.adobeAnalytics|length and getenv('CRAFT_ENVIRONMENT') == 'production' %}
    tarteaucitron.user.adobeanalyticskey = '{{seo.adobeAnalytics}}';
    (tarteaucitron.job = tarteaucitron.job || []).push('adobeanalytics');
  {% endif %}
```
J'ai pourtant l'impression d'avoir suivi la doc. Quelqu'un a-t-il le même souci ?
Merci d'avance !

**Comment by AmauriC** [comment]
Bonjour,

C'est sûrement une nouvelle version du script, quand je l'avais ajouté en 2020 le tag était:
`<script src="//assets.adobedtm.com/launch-ZZZ.min.js" async></script>`

Ca s'appelle toujours "Adobe Analytics" ?

L'idéal serait de créer un nouveau service pour ne pas rendre inutilisable les installations qui utilisent l'ancienne version.

**Comment by elodiegrondin** [comment]
Merci pour ta réponse rapide !

Effectivement, il vaut mieux ne pas casser l'ancienne version.
Ça s'appelle toujours Adobe Analytics.
Ce sont des clés de 12 chiffres à chaque fois et elles sont nécessaires, car elles font partie du path vers le script.

J'avoue que je n'ai pas beaucoup plus d'informations parce que c'est mon client qui a créé les deux Adobe Analytics et il m'a juste envoyé les balises script...

J'ai l'impression que ce sont des ids liés au compte adobe:
`https://assets.adobedtm.com/{user_id?}/{id_property_1?}/launch-{adobe_analytics_key_1}.min.js`
`https://assets.adobedtm.com/{user_id?}/{id_property_2?}/launch-{adobe_analytics_key_2}.min.js`
Le premier est pareil, j'imagine que c'est un genre de user_id. Les autres sont différents.

Mais effectivement, si ce n'est pas commun à tous les scripts, c'est peut-être plus simple de faire un service custom.

**Comment by elodiegrondin** [comment]
Je vais essayer de me renseigner auprès du client.
En attendant, j'ai créé un custom service :)

**Comment by elodiegrondin** [comment]
Bonjour,

Je pense qu'on peut partir sur Adobe - Analysis Workspace.
Voici la réponse du client :

> L’espace « Reports » sera totalement abandonné par Adobe Analytics au 31/12/2023. Il vaut mieux donc se baser sur le « Workspace ».
> « Adobe Analytics - analysis workspace » me paraît bien.

En attendant l'implémentation de la nouvelle version, je clôture ce ticket comme j'ai de toute façon crée un custom service.

Merci beaucoup pour ton aide rapide et cette super librairie ! :)

**Comment by AmauriC** [comment]
Super, merci. Je réouvre pour que je n'oubli pas de m'en occuper ;)
