### ISSUE TITLE
Matomo pour wp intégration cookie non déposé

### ISSUE THREAD

**Issue by thierrydeve** [AmauriC/tarteaucitron.js#1081]
Salut, je me suis mis à Matomo pour un site WordPress.

J'ai bien intégré Tarteaucitron.js dans le site WordPress et j'ai mis le script tarteaucitron.js dans le functions.php comme plus bas…

Sur le site, il apparait bien le petit logo pour le consentement avec le pop-up qui reconnait Matomo. 
Sauf qu'il me signale qu'aucun cookie n'est déposé. (même si je refuse et j'accepte).

Je voudrais savoir également s'il faut réellement supprimer ce script dans le header pour que Matomo puisse analyse le trafique :

`` <script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="YOUR_MATOMO_URL";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', SITE_ID]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src='JS_PATH'; s.parentNode.insertBefore(g,s);
  })();
</script>``

**Functions.php**

``function cookie(){
	?>
        <script src="/wp-content/themes/montheme/tarteaucitron/tarteaucitron.js"></script>

        <script type="text/javascript">
        tarteaucitron.init({
    	  "privacyUrl": "", /* Privacy policy url */
          "bodyPosition": "bottom", /* or top to bring it as first element for accessibility */
          ..........
        });
        </script>
    <?php
}
add_action('wp_head', 'cookie');

function cookie_deux(){
	?>

	
	<script>
		tarteaucitron.user.matomoHost = 'https://ex-verif-statique.com';
		tarteaucitron.user.matomoCustomJSPath = 'https://ex-verif-statique.com/matomo.js';
	</script>

	<script type="text/javascript">
                tarteaucitron.user.matomoId = 2;
                (tarteaucitron.job = tarteaucitron.job || []).push('matomocloud');
    </script>

	<?php
}
add_action('wp_footer', 'cookie_deux');``

**Comment by AmauriC** [comment]
Salut,

Il manque un slash de fin sur le `matomoHost` et il faut retirer du header le code Matomo, c'est tarteaucitron qui se charge de l'ajouter.

Matomo ne dépose pas systématiquement des cookies, ce n'est pas un souci, ce qui est important c'est d'empêcher le chargement du marqueur si l'utilisateur le refuse.

**Comment by AmauriC** [comment]
1- Il ne reste plus de cookie une fois Matomo désactivé?

2- Si il n'y a que Matomo et comme il est ok pour être accepté par défaut, le bandeau ne s'affiche pas comme le consentement est déjà implicitement donné. Si vous ajoutez un autre service qui requiert le consentement, le bandeau s'affichera.
