### ISSUE TITLE
Le service matomocloud continue de track après refus

### ISSUE THREAD

**Issue by trpharove** [AmauriC/tarteaucitron.js#1085]
Maintenant que le service TAC matomo est déprécié et que la page associé à sauté, nous sommes obligés d'utiliser autre chose que la service matomo, donc matomocloud.
Les cookies sont bien déposés si l'utilisateur les accepte et le tracking est visible depuis l'outil Matomo (je vois bien les pages qu'il consulte).
Les cookies déposés sont tels que :
![image](https://user-images.githubusercontent.com/99823823/231222325-aea1bac8-0e13-4b92-9780-d1cfa8b250d3.png)

Si l'uilisateur refuse depuis l'interface
![image](https://user-images.githubusercontent.com/99823823/231223105-1d95fc76-0c88-4ad0-91a0-2e97a2b99cd3.png)

Alors les cookies sont supprimés mais pas le MATOMO_SESSID
![image](https://user-images.githubusercontent.com/99823823/231224023-5b9512c4-d37f-4714-80d1-4fbaf27ffb09.png)

Je ne sais pas si c'est lié a ça mais après refus de l'utilisateur, même s'il rafraichit la page ses actions sont toujours affichés dans Matomo comme s'il avait accepté.
Nous n'avions pas ce soucis avec le service TAC matomo mais mes tests dataient d'il y a maintenant quelques mois.

Est-ce que vous avez une idée du soucis ou un cas similaire qui aurait été corrigé ?

**Comment by AmauriC** [comment]
Le nouveau service Matomo inclu maintenant le chargement de stats anonyme quand l'utilisateur refuse.
https://github.com/AmauriC/tarteaucitron.js/issues/1028
