### ISSUE TITLE
synchronous xmlhttprequest is deprecated

### ISSUE THREAD

**Issue by alexandrebrubeyonds** [AmauriC/tarteaucitron.js#1086]
Hello,

Google Page speed said 

> The synchronous `XMLHttpRequest` request on the main thread is deprecated due to its negative impact on the end-user experience. If you need help, check out https://xhr.spec.whatwg.org/.

How can we fix that ?

**Comment by alexandrebrubeyonds** [comment]
Nobody else ?

**Comment by AmauriC** [comment]
Hi

This is about this part https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.js#L79 ?

A suggestion about how we can make this better?

**Comment by alexandrebrubeyonds** [comment]
Hello @AmauriC, yes it's from this part, but sorry I don't have a suggestion, just report it :)

**Comment by alexandrebrubeyonds** [comment]
Anyone have a suggestion ?

**Comment by AmauriC** [comment]
Since I dont have a solution right now I closed this but no worries, it's only used to load the `tarteaucitronProLoadServices();` if the function exist and it's almost never used ;)
