### ISSUE TITLE
handling third party cookies

### ISSUE THREAD

**Issue by NguyenTheo-dev** [AmauriC/tarteaucitron.js#1088]
Hello,

Is there a way to handle third party cookies built-in ? 

The use case is that editors on my website tend to include iframes from other website with their own cookies and cookie policies, and i have no idea how i would block all these

**Comment by AmauriC** [comment]
Hi

This is possible but not automatic, you have to rewrite the iframe to something like:

```
<div class="tac_iframe" width="930" height="500" data-url="https://example.com/"> </div>
```
