### ISSUE TITLE
Head or Tail?

### ISSUE THREAD

**Issue by coatpont** [AmauriC/tarteaucitron.js#1091]
The installation script recommends to place the .js include within the <head> section of the page, making it a blocking resource for the page. Any reason why putting it at the bottom of the DOM is not an option?

**Comment by AmauriC** [comment]
If you dont use the "automatic mode" from the pro version, you can put it at the bottom ;)

**Comment by coatpont** [comment]
Ah, I'm using the pro version - see https://nominis.cef.fr - is that a dealbreaker?

**Comment by AmauriC** [comment]
Pro version and automatic mode, you have to let the script before all tags or tac will not be able to detect and block.

**Comment by coatpont** [comment]
ok - performance wise, given that the configuration is unlikely to change often, is there a way to get a client-side TTL on this .js resource?

**Comment by AmauriC** [comment]
Yes, I'm sure. Click on the line and check the "expire" header.

**Comment by coatpont** [comment]
ah yes i can see it, I was expecting a cache-control header similar to the ones we get for the resources served out of cdn.tarteaucitron.io - all good (although cache-control would be a bit better for http1.1+ compatibility)
