### ISSUE TITLE
How to use tarteaucitron with content editor like tinymce?

### ISSUE THREAD

**Issue by ldecoker** [AmauriC/tarteaucitron.js#1094]
Hello!

I would like to use tarteaucitron on website where users can add videos (like vimeo video) via tinymce.
The code added in the page via tinymce is as follows:

<iframe style="display: block; margin-left: auto; margin-right: auto;" title="{title}" src="{url}" width="{width}" height="{height}" frameborder="0" allowfullscreen="allowfullscreen"></iframe>

When looking the documentation, the only way to use cookie consent with tinymce would be to change this iframe code by :

<div class="vimeo_player" videoID="video_id" width="width" height="height"></div>

Any idea on how to do that?
Thx for any suggestion.

**Comment by AmauriC** [comment]
Hi

I dont know how tinymce work but I think you can edit the iframe template to something similar to https://github.com/AmauriC/tarteaucitron.js/issues/1088#issuecomment-1537093946
