### ISSUE TITLE
Bandeau de cookies réapparait à chaque requête

### ISSUE THREAD

**Issue by eliegaboriau** [AmauriC/tarteaucitron.js#1095]
Bonjour,
Sur une plateforme où des cookies sont installés depuis la plateforme pro de tarteaucitron, le bandeau réapparait à chaque requète.
Après investigation, le bug n'apparait que sur chrome, et on trouve 2 cookies "cookieconsentement", l'un relatif à matomo et l'autre relatif à matomo et matomo cloud.
En supprimant les cookies du navigateur, nous retrouvons un fonctionnement normal.
Le problème est donc probablement lié au passage de matomo à matomocloud.
Merci à vous

**Comment by AmauriC** [comment]
Bonjour,
Il n'y a pas eu d'autres changement, surtout sur la valeur du nom du cookie ou du "cookieDomain" ?
Si 2 cookies coexistent c'est en effet un problème, une fois purgé, ça ne devrait plus réapparaitre.

**Comment by eliegaboriau** [comment]
Le cookie domain n'est pas précisé, j'imagine qu'il est généré depuis le champ "nom de domain" de la plateforme pro. 
Il n'a donc pas changé
