### ISSUE TITLE
Compatibility with partytown

### ISSUE THREAD

**Issue by ThibaultAndreis** [AmauriC/tarteaucitron.js#1097]
I plan to add compatibility with [partytown](https://github.com/BuilderIO/partytown) on a project
It seems that for most of the scripts (if not all), it only requires to set the script tag as ` 'text/partytown' ` and call the function
`window.dispatchEvent(new CustomEvent('ptupdate'));`
Do you think it would be better to add a global configuration for all of tarte au citron, or manage it per service?
Is it something you might be interested  in upstreaming?

**Comment by AmauriC** [comment]
Maybe I dont understand well the way Partytown work but there is no need to change something on the tarteaucitron side to make it work?

**Comment by ThibaultAndreis** [comment]
Yes, in case someone is checking for how to do it, you can't use the baked in support, you have to rewrite it, to add the type and start dispatch the event after the script is added

For instance google tag manager in tarte au citron services :

`tarteaucitron.services.googletagmanager = {
    "key": "googletagmanager",
    "type": "api",
    "name": "Google Tag Manager",
    "uri": "https://policies.google.com/privacy",
    "needConsent": true,
    "cookies": ['_ga', '_gat', '__utma', '__utmb', '__utmc', '__utmt', '__utmz', '__gads', '_drt_', 'FLC', 'exchange_uid', 'id', 'fc', 'rrs', 'rds', 'rv', 'uid', 'UIDR', 'UID', 'clid', 'ipinfo', 'acs'],
    "js": function () {
        "use strict";
        if (tarteaucitron.user.googletagmanagerId === undefined) {
            return;
        }
        window.dataLayer = window.dataLayer || [];
        window.dataLayer.push({
            'gtm.start': new Date().getTime(),
            event: 'gtm.js'
        });
        tarteaucitron.addScript('https://www.googletagmanager.com/gtm.js?id=' + tarteaucitron.user.googletagmanagerId);
    }
};`

become 
`tarteaucitron.services.googletagmanager = {
		key: 'googletagmanager',
		type: 'api',
		name: 'Google Tag Manager',
		uri: 'https://policies.google.com/privacy',
		needConsent: !0,
		cookies: [
			'_ga',
			'_gat',
			'__utma',
			'__utmb',
			'__utmc',
			'__utmt',
			'__utmz',
			'__gads',
			'_drt_',
			'FLC',
			'exchange_uid',
			'id',
			'fc',
			'rrs',
			'rds',
			'rv',
			'uid',
			'UIDR',
			'UID',
			'clid',
			'ipinfo',
			'acs'
		],
		js: function () {
			'use strict';
			void 0 !== tarteaucitron.user.googletagmanagerId &&
				((window.dataLayer = window.dataLayer || []),
				window.dataLayer.push({
					'gtm.start': new Date().getTime(),
					event: 'gtm.js'
				}),
				tarteaucitron.addScript(
					'https://www.googletagmanager.com/gtm.js?id=' + tarteaucitron.user.googletagmanagerId,
					null,
					null,
					null,
					'type',
					'text/partytown'
				));
			window.dispatchEvent(new CustomEvent('ptupdate'));
		}
	},`

**Comment by AmauriC** [comment]
Thanks for the details 👌
