### ISSUE TITLE
RespondAll deny is broken

### ISSUE THREAD

**Issue by NguyenTheo-dev** [AmauriC/tarteaucitron.js#1101]
Hello,

I am using tac on my website, latest version (20230203) and i noticed that the denyall button doesn't work as expected: clicking it doesn't iterate over all the registered services to set them to false, so the tac cookie isn't correctly setup in the end. Manually clicking on allow/deny does set it correctly, and then reloads the page

Is it just my installation ?

Thanks

EDIT:

I realize this is similar to #718

I do have a custom service indeed, but it's copy/pasted from the generic iframe one:

```
// INA
// Kinda made for one and only one website, but we never use it otherwise
tarteaucitron.services.ina = {
    "key": "ina",
    "type": "video",
    "name": "INA",
    "uri": "https://sites.ina.fr/cnil/charte-vie-privee-blank",
    "needConsent": true,
    "cookies": ['didomi_token', 'euconsent-v2', '_ga', '_gid', '_gat', 'AMP_TOKEN', '1P_JAR', 'CONSENT', 'hit.xiti', 'atid', 'xtvrn', 'xtan', 'Xtan+numsite', 'Xtant', 'Xtant+numsite'],
    "js": function (){
        "use strict";
        tarteaucitron.fallback(['ina_player'], function (x) {
            var frame_title = tarteaucitron.fixSelfXSS(tarteaucitron.getElemAttr(x, "title") || 'INA iframe'),
                frame_height = tarteaucitron.getElemAttr(x, "height"),
                frame_width = tarteaucitron.getElemAttr(x, "width");
            
            return '<iframe title="' + frame_title + '" type="text/html" ' + 'width="' + frame_width + '" height="' + frame_height + '" src="//sites.ina.fr/"' + ' frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen' + ' ></iframe>';
        });
	},
    "fallback": function () {
        "use strict";
        var id = 'ina';
        tarteaucitron.fallback(['ina_player'], function (elem) {
            elem.style.width = tarteaucitron.getElemAttr(elem,'width') + 'px';
            elem.style.height = tarteaucitron.getElemAttr(elem,'height') + 'px';
            return tarteaucitron.engage(id);
        });
    }
};
```

My tac is setup like this:

```
<!--Tartocitron-->
        <script src="https://m3c.universita.corsica/tarteaucitron/tarteaucitron.js"></script>

        <script type="text/javascript">
        tarteaucitron.init({
    	  "privacyUrl": "https://m3c.universita.corsica/s/fr/page/politique-de-confidentialite", /* Privacy policy url */

    	  "hashtag": "#tarteaucitron", /* Open the panel with this hashtag */
    	  "cookieName": "tarteaucitron", /* Cookie name */
    
    	  "orientation": "middle", /* Banner position (top - bottom) */
       
          "groupServices": false, /* Group services by category */
                           
    	  "showAlertSmall": false, /* Show the small banner on bottom right */
    	  "cookieslist": false, /* Show the cookie list */
                           
          "closePopup": true, /* Show a close X on the banner */

          "showIcon": false, /* Show cookie icon to manage cookies */
          //"iconSrc": "", /* Optionnal: URL or base64 encoded image */
          "iconPosition": "BottomRight", /* BottomRight, BottomLeft, TopRight and TopLeft */

    	  "adblocker": false, /* Show a Warning if an adblocker is detected */
                           
          "DenyAllCta" : true, /* Show the deny all button */
          "AcceptAllCta" : true, /* Show the accept all button when highPrivacy on */
          "highPrivacy": true, /* HIGHLY RECOMMANDED Disable auto consent */
                           
    	  "handleBrowserDNTRequest": true, /* If Do Not Track == 1, disallow all */

    	  "removeCredit": false, /* Remove credit link */
    	  "moreInfoLink": true, /* Show more info link */

          "useExternalCss": false, /* If false, the tarteaucitron.css file will be loaded */
          "useExternalJs": false, /* If false, the tarteaucitron.js file will be loaded */

    	  //"cookieDomain": ".my-multisite-domaine.fr", /* Shared cookie for multisite */
                          
          "readmoreLink": "", /* Change the default readmore link */

          "mandatory": true, /* Show a message about mandatory cookies */
        });
</script>
        <script type="text/javascript">
        tarteaucitron.user.matomoId = 1;
        (tarteaucitron.job = tarteaucitron.job || []).push('matomocloud');
(tarteaucitron.job = tarteaucitron.job || []).push('youtube');
(tarteaucitron.job = tarteaucitron.job || []).push('vimeo');
(tarteaucitron.job = tarteaucitron.job || []).push('ina');
(tarteaucitron.job = tarteaucitron.job || []).push('maps_noapi');
        </script>
<script>tarteaucitron.user.matomoHost = 'https://m3c.universita.corsica/matomo/';tarteaucitron.user.matomoCustomJSPath = 'https://m3c.universita.corsica/matomo/matomo.js';</script>
<!--Tartocitron-->
```

**Comment by AmauriC** [comment]
Hi

Tested and from my side it works as intended, the deny all button revoke all the consent and refresh the page.

The only thing that can be an issue on some browser is the `+` on 2 cookie names `Xtant+numsite` and `Xtan+numsite`

**Comment by NguyenTheo-dev** [comment]
AHHHH

I deleted the cookies with the `+` in their names and it works. I saw nothing on the console i wondered what the hell was wrong

Thanks!

**Comment by NguyenTheo-dev** [comment]
Excuse me to reopen this, but i think my INA service is broken and i can't understand why. Here's what it looks like with the modification on the cookies witha plus:

`// INA
// Kinda made for one and only one website, but we never use it otherwise
tarteaucitron.services.ina = {
    "key": "ina",
    "type": "video",
    "name": "INA",
    "uri": "https://sites.ina.fr/cnil/charte-vie-privee-blank",
    "needConsent": true,
    "defaultState": false,
    "cookies": ['didomi_token', 'euconsent-v2', '_ga', '_gid', '_gat', 'AMP_TOKEN', '1P_JAR', 'CONSENT', 'xiti', 'atid', 'xtvrn', 'xtan', 'Xtant'],
    "js": function (){
        "use strict";
        tarteaucitron.fallback(['ina_player'], function (x) {
            var frame_title = tarteaucitron.fixSelfXSS(tarteaucitron.getElemAttr(x, "title") || 'INA iframe'),
                frame_height = tarteaucitron.getElemAttr(x, "height"),
                frame_width = tarteaucitron.getElemAttr(x, "width");
            
            return '<iframe title="' + frame_title + '" type="text/html" ' + 'width="' + frame_width + '" height="' + frame_height + '" src="//sites.ina.fr/mobilisations-en-corse/tempo/"' + ' frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen' + ' ></iframe>';
        });
	},
    "fallback": function () {
        "use strict";
        var id = 'ina';
        tarteaucitron.fallback(['ina_player'], function (elem) {
            elem.style.width = tarteaucitron.getElemAttr(elem,'width') + 'px';
            elem.style.height = tarteaucitron.getElemAttr(elem,'height') + 'px';
            return tarteaucitron.engage(id);
        });
    }
};`

I tried setting the default state to disabled to try to have the cookie initialized without a problem, but when i add this to my services.js the dney all seems to break again...

I don't quite get why, since this is almost 1:1 the generic iframe one. Do have an idea why ?

Thanks

**Comment by AmauriC** [comment]
There is an another plugin that use some tarteaucitron function:
https://m3c.universita.corsica/modules/EUCookieBarTarteAuCitron/asset/vendor/jquery.cookiebar/jquery.cookiebar.js

It can be the problem, can you try to remove it?

**Comment by NguyenTheo-dev** [comment]
I tried withand without it to no avail; in the end i elected to set my services as disabled by default. Sorry, thanks for your time
