### ISSUE TITLE
Ajustements visuels sur le bandeau cookie

### ISSUE THREAD

**Issue by SW-Vincent** [AmauriC/tarteaucitron.js#1102]
Bonjour,

Nous utilisons actuellement la version payante de TAC.
Suite à une mise en production sur plusieurs sites nous aimerions savoir s'il est possible : 
 - de rajouter une image à gauche du "titre" (par défaut sur la version centrée, les caractères ☝ 🍪 remplissent ce rôle, nous aimerions utiliser une image spécifique + du texte à la place)
 - avoir la main sur quelques éléments de mise en forme (aligner à gauche, etc), à priori disponible via Thème > custom CSS rules
 - pouvoir ajouter des niveaux de granularité dans le texte (par exemple remplacer "Ce site utilise des cookies et vous donne le contrôle sur ceux que vous souhaitez activer" par deux éléments de taille distincte

Merci pour votre aide !

**Comment by AmauriC** [comment]
Bonjour,

1- Image + texte ça va être difficile mais pour remplacer les emojis par une image, il faut ajouter cette règle CSS:
```
div#tarteaucitronAlertBig:before {
    background:url(https://tarteaucitron.io/img/logo.png) center center no-repeat;
    background-size: contain;
    content:"";
    height:40px!important;
    display:block;
}
```

2- Le CSS custom est là pour ça

3- Vous pouvez depuis le panel https://tarteaucitron.io/fr/pro/ modifier le texte et utiliser les balises `<br><b><i><em><a>`
Avec du CSS vous pouvez ensuite changer la taille de la police/couleurs/...
