### ISSUE TITLE
[Services] Bug iframe Instagram ?

### ISSUE THREAD

**Issue by lucmuller** [AmauriC/tarteaucitron.js#1104]
D'après ce que je constate ce matin, l'iframe d'embed d'instagram semble avoir besoin d'un segment /p/ avant le postId.

J'ai du corriger sur mon instance locale.
Je vais faire un pull request, mais je pense que c'est à vérifier.

**Comment by AmauriC** [comment]
Merci Luc 💪

C'est rétro compatible?

Je n'ai pas d'installation sous la main pour tester.

**Comment by lucmuller** [comment]
> C'est rétro compatible?
A priori oui, je n'ai que modifié l'url de l'iframe, contenant l'embed, générée.

Par contre instagram propose à présent une option "inclure la légende" qui ajoute une autre clée d'url. Ce paramètre n'est pas pris en compte par le service actuellement.
