### ISSUE TITLE
[BUG] Event JS envoyé avant changement d'état

### ISSUE THREAD

**Issue by Mintoo200** [AmauriC/tarteaucitron.js#1106]
Bonjour,

## Context

Nous utilisons tarteaucitron notamment pour gérer le consentement aux cookies de tracking via Eulerian.
Comme discuté dans l'issue #1022, l'implémentation du service proposée par Eulerian envoie les requêtes de tracking même lorsque le service a été refusé (ou pas encore accepté) par l'utilisateur. Nous nous sommes donc retrouvés à ré-implémenter la vérification du consentement avant d'effectuer ces requêtes à la main, dans notre code.

L'implémentation est simple, elle ressemble à ça : 
```ts
function sendAnalytics() {
  if (window.tarteaucitron.state['eulerian'] === true) {
    // do stuff
  }
}

document.addEventListener('eulerian_allowed', sendAnalytics);
```

## Problème observé

Il semblerait que lorsque l'event `'eulerian_allowed'` est envoyé, le state de tarteaucitron n'est pas encore mis à jour pour refléter ce changement : 

```ts
document.addEventListener('eulerian_allowed', () => {
	console.group('eulerian_allowed');
	console.log('from tarteaucitron:', window.tarteaucitron.state.eulerian);
	console.log('from document.cookie:', document.cookie);
	console.groupEnd();

	setTimeout(() => {
		console.group('eulerian_allowed 1 second ago');
		console.log('from tarteaucitron:', window.tarteaucitron.state.eulerian);
		console.log('from document.cookie:', document.cookie);
		console.groupEnd();
	}, 1000);
}
```
Nous donne le résultat suivant : 
<img width="635" alt="image" src="https://github.com/AmauriC/tarteaucitron.js/assets/25901730/dc132f31-f1b4-4cc6-bcbf-818b40fff4af">

## Solution envisagée

Déplacer l'envoi d'event JS **après** la mise à jour du state.
Ces events ne semblent pas utilisés par le script tarteaucitron lui-même mais simplement exposés à l'extérieur.

Le changement semble simple : déplacer les lignes 1026 à 1032 et 1074 à 1080 **après** les lignes 1035 et 1083.
Ce changement a résolu le problème chez nous, serait-il pertinent de refléter ce changement sur ce repo ?

Merci

**Comment by AmauriC** [comment]
En effet ce serait plus logique d'envoyer l'event quand tout est bien défini, je ne vois pas d'objection à faire le changement : )

Vous pouvez envoyer un PR ou je m'en occupe en début de semaine prochaine.

**Comment by Mintoo200** [comment]
PR ouverte (#1108)
