### ISSUE TITLE
Eulerian : double hit

### ISSUE THREAD

**Issue by pierretux** [AmauriC/tarteaucitron.js#1112]
Bonjour @AmauriC et @guillaumef,

Nous remarquons que le service remonte du double hit, cela vient de la ligne avec le EA_push(); qu'il faudrait supprimé.
Peut on faire cela ?

Cdt
Pierre

**Comment by pierretux** [comment]
Bonjour,

Amauric tu peux faire cela ? 

Merci

**Comment by AmauriC** [comment]
D'où viens l'autre EA_push ?

Je peux ajouter une option côté tarteaucitron pour choisir d'appeler ou non cette fonction.

**Comment by pierretux** [comment]
C'est le push de https://eulerian.wiki/doku.php?id=fr:modules:collect:gdpr:tarteaucitron qui prends le second hit du coup

**Comment by AmauriC** [comment]
Il ne peux pas y avoir les 2 services chargés en même temps, ils ont le même id 🧐
Possible d'avoir l'url du page pour reproduire le problème?

**Comment by pierretux** [comment]
sur https://sante.gouv.fr/ par exemple

**Comment by AmauriC** [comment]
C'est la version tarteaucitron qui est utilisé, le code eulerian n'écrase pas celui de tarteaucitron.

Une petite modification pour avoir un identifiant propre à la version eulerian custom devrait régler le problème:

```
tarteaucitron.services.euleriancustom = {
	'key': 'euleriancustom',
	'type': 'analytic',
	'name': 'Eulerian Analytics',
	'needConsent': true,
	'cookies': ['etuix'],
	'uri' : 'https://eulerian.com/vie-privee',
	'js': function () {
		'use strict';
		(function(x,w){ if (!x._ld){ x._ld = 1;
			let ff = function() { if(x._f){x._f('tac',tarteaucitron,1)} };
			w.__eaGenericCmpApi = function(f) { x._f = f; ff(); };
			w.addEventListener('tac.close_alert', ff);
			w.addEventListener('tac.close_panel', ff);
		}})(this,window);
	},
	'fallback': function () { this.js(); }
};
(tarteaucitron.job = tarteaucitron.job || []).push('euleriancustom');
```

**Comment by guillaumef** [comment]
Le code 'eulerian' servit dans le services.js est déficient et inutile. Nous l'avons signalé à de nombreuses reprises ici et nous avions demandé son retrait. L'implémentation est fausse et elle ne sert à rien.

Tous les problèmes générés dans l'utilisation de TAC sur lesquels nous avons du intervenir viennent du fait que cette implémentation persiste dans ce fichier.

Nous avons déjà détaillé la mitigation dans notre documentation.
**Ce que vous proposez ici a déjà été fourni:**
https://eulerian.wiki/doku.php?id=fr:quickonboarding:installation:cmp
Notamment pour utiliser une clé alternative, que nous avons nommé 'eulerian-analytics'.

**Comment by pierretux** [comment]
ok la doc a été amélioré, je ferme la demande du coup

**Comment by AmauriC** [comment]
J'ai supprimé Eulerian de la liste des services supportés dans la doc et pour la v pro comme vous ne souhaitez pas y être.

Votre utilisation de tarteaucitron est également inutile, le tag sera toujours chargé que j'accepte ou refuse, ce n'est pas comme ça que tarteaucitron fonctionne, si un utilisateur refuse Eulerian, rien ne doit être chargé.

Dommage que vous n'ayez jamais voulu trouver une solution, seul service sur 198 ;)

**Comment by AmauriC** [comment]
Dernière précision, la clé 'eulerian' reste pour des raisons de rétro comptabilité, il ne fallait pas utiliser la même dans votre doc initiale..
