### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by Olwyne** [AmauriC/tarteaucitron.js#1118]
Bonjour,

J'ai installé le plugin tarte au citron sur un WordPress 6.2.2, PHP 8.2 et dernière version du plugin. J'ai ce warning qui s'affiche sur le site. Je n'ai pas encore renseigné d'identifiant dans le plugin.

`Deprecated: ctype_alnum(): Argument of type bool will be interpreted as string in the future in /var/www/html/wp-content/plugins/tarteaucitronjs/tarteaucitron.php on line 30`

Avez-vous une idée de résolution ?

Merci
Bonne journée

**Comment by AmauriC** [comment]
Merci pour le retour, je corrige quand j'ai un moment.

Ce n'est pas un problème, juste une information sur un futur changement qui n'aura pas d'impact sur le plugin ; )
