### ISSUE TITLE
La popup de choix des cookies ne s'ouvre pas automatiquement au démarrage

### ISSUE THREAD

**Issue by jeromevilliseck** [AmauriC/tarteaucitron.js#1126]
Bonjour,

Après mise en place de la librairie dans un projet. Il faut malheureusement placer en fin d'url le tag #tarteaucitron en bout d'url pour ouvrir le panneau de choix par defaut à l'arrivée sur le site.

Il y a t'il une solution pour faire s'ouvrir le panneau par defaut à l'arrivée sur le site

**Comment by AmauriC** [comment]
Bonjour,

Il n'y a pas d'options pour ouvrir automatiquement le panel, seul le bandeau est affiché et ensuite l'utilisateur peu ouvrir pour gérer les détails.
