### ISSUE TITLE
Paramétrage cookieDomain avec et sans sous-domaine

### ISSUE THREAD

**Issue by zoltanru44** [AmauriC/tarteaucitron.js#1127]
Bonjour, lorsque je paramètre l'option cookieDomain avec ".monsite.org", est-ce que cela prend en compte à la fois le site d'origine en https://monsite.org et les sous domaines en https://test.monsite.org ?
Car je suis en phase de mise en place pour avoir un cookie commun mais je n'arrive pas à avoir une gestion unique de TAC, je retrouve pourtant bien mon cookie en .monsite.org sur le domaine principal (après avoir consulté le sous domaine) mais sur le domaine principal j'ai le cookie en monsite.org sans le point. 

Merci d'avance !

**Comment by AmauriC** [comment]
La configuration est bien la même sur les 2 sites?
Cookies supprimés après le changement de configuration ? Il est probable que le cookie par défaut sans . soit toujours existant et prenne le dessus.

**Comment by zoltanru44** [comment]
Oui j'ai supprimé plusieurs fois les cookies. 

Le problème c'est que je n'ai la main que sur un des deux sites. Mais c'était pour être sur que niveau configuration j'étais bon avec ' "cookieDomain": ".monsite.org",'. Et que cela était normalement bien compatible.

Merci pour la rapidité de ta réponse (et pour TarteauCitron aussi :-) )
