### ISSUE TITLE
Google Ads Event

### ISSUE THREAD

**Issue by vcol** [AmauriC/tarteaucitron.js#1128]
Bonjour à tous,

Sur ma page de remerciement après dépôt d'un formulaire, je souhaite pousser une conversion Google Ads. J'ai mis le code suivant mais aucune conversion ne remonte :

```
<script type="text/javascript">
    tarteaucitron.user.googleadsId = 'AW-XXXXXXXX';
    (tarteaucitron.job = tarteaucitron.job || []).push('googleads');
</script>

<!-- Event snippet for Leads conversion page -->
<script>
    gtag('event', 'conversion', {'send_to': 'AW-XXXXXXXX/zzzzzzzzzzzzzzz'});
</script>
```

Au final dans ma console on m'indique que la fonction "gtag is not defined".
Ai-je fait quelque chose d'incorrect ?
Merci bcp pour votre aide.
Vincent

**Comment by AmauriC** [comment]
Bonjour Vincent,

Si `gtag` n'est pas défini, c'est probablement que tarteaucitron n'a pas encore chargé Google Ads.

Essayez:

```
<script>
document.addEventListener("googleads_loaded", function() {
   gtag('event', 'conversion', {'send_to': 'AW-XXXXXXXX/zzzzzzzzzzzzzzz'});
});
</script>
```

**Comment by vcol** [comment]
Merci beaucoup Amaury. Hélas, cela ne semble pas fonctionner. Voici l'url de la page : https://www.touslesbts.fr/merci

**Comment by AmauriC** [comment]
Testons avec un petit délai supplémentaire:

```
<script>
document.addEventListener("googleads_loaded", function() {
   setTimeout(function() {gtag('event', 'conversion', {'send_to': 'AW-XXXXXXXX/zzzzzzzzzzzzzzz'});}, 800);
});
</script>
```

**Comment by vcol** [comment]
Pareil hélas... mais avec une petit délai supplémentaire :)

**Comment by AmauriC** [comment]
Pas d'adblocker ou de VPN qui pourraient bloquer la requête ?

**Comment by vcol** [comment]
Non aucun.

**Comment by AmauriC** [comment]
Ca fonctionne de mon côté maintenant 🧐

**Comment by vcol** [comment]
De notre côté nous ne voyons pas les conversions Google Ads (alors que nous en générons). Je vais donc passer par GTM.
Merci de votre aide.

**Comment by AmauriC** [comment]
Ok, merci pour le retour ; )
