### ISSUE TITLE
[WORDPRESS] - Abonnement affiché expiré alors que celui-ci est actif

### ISSUE THREAD

**Issue by Eliophot** [AmauriC/tarteaucitron.js#1131]
Bonjour,

Sur WordPress, l'abonnement s'affiche expiré, alors que ce n'est pas le cas : 
![image](https://github.com/AmauriC/tarteaucitron.js/assets/81296123/b1723485-0bf9-4e02-932a-23506007f058)
![image](https://github.com/AmauriC/tarteaucitron.js/assets/81296123/62964fcf-24ff-4bc3-ace5-166dd2258c71)
Les clés sont peut-être régénérées tous les ans ? Le plugin semble toutefois encore fonctionner, est-ce le cas ?

**Comment by AmauriC** [comment]
Il est en effet possible qu'un ancien token soit expiré.

Déconnectez vous et reconnectez avec les identifiants dispo dans l'espace "Mon compte" https://tarteaucitron.io/fr/pro/

**Comment by Eliophot** [comment]
Oui c'est ce que l'on fait. Il n'y a pas de système de refresh ?
Le problème c'est que l'on a plus de 180 sites sous WordPress, effectuer cette opération tous les ans est quelque peu chronophage...

**Comment by AmauriC** [comment]
Si, normalement c'est refresh mais il faut ouvrir la page "tarteaucitron" du plugin pour que ce soit fait, c'est peut-être le problème.

Si vous n'utilisez pas les options dispo dans le plugin WP, vous pouvez vous en passer, il suffit juste d'ajouter le tag js dans le header du site ; )

**Comment by Eliophot** [comment]
ok merci on va peut-être prendre cette solution effectivement.
