### ISSUE TITLE
Responsible disclosure policy

### ISSUE THREAD

**Issue by psmoros** [AmauriC/tarteaucitron.js#1132]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@rudloff) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by AmauriC** [comment]
Hi :)

I've created the SECURITY.md, you can reach me at amauri@tarteaucitron.io

Thanks!

**Comment by Rudloff** [comment]
@AmauriC You should have received an e-mail containing a link allowing you to access the private report.

**Comment by AmauriC** [comment]
Yes @Rudloff , I've answered few hours after and no response : (

**Comment by Rudloff** [comment]
Did you answer via e-mail or on the huntr.dev issue?

@psmoros Did you get the answer?

**Comment by AmauriC** [comment]
I have answered the mail.
I dont get the url to huntr because my client (outlook) dont load all the mail, it's cut on the ``` but from the source I get the link to huntr, I'll answer here, thanks ; )
