### ISSUE TITLE
Piwik Pro avec TauC Pro

### ISSUE THREAD

**Issue by eficiens-eric** [AmauriC/tarteaucitron.js#1134]
Bonjour,

J'ai installé Piwik Pro via l'interface de de Tarte au Citron Pro. Jusqu'ici tout marchait bien, et là je vois que les données Piwik ne remontent plus. J'ai l'impression que c'est lié au paramètre 'container' qu'il faut renseigner, mais quand je fais valider le champ repasse à zero et TauC ne conserve pas l'info que j'avais donnée. Résultat, au moment du chargement de TauC puis de Piwik, rien ne se passe.

<img width="957" alt="image" src="https://github.com/AmauriC/tarteaucitron.js/assets/81694039/54d4582a-b0a6-4028-afad-7ba3de03114f">

Le site est le suivant : https://www.medecinsexpertscovea.fr/
Merci d'avance

**Comment by AmauriC** [comment]
Bonjour,

Essayez de supprimer et de recréer le service Piwik Pro.

Avant le container était un container générique d'exemple (par erreur), si vous aviez des stats piwik pro c'est probablement que vous n'aviez pas retiré du site le marqueur piwik.

**Comment by eficiens-eric** [comment]
Merci Amauri,
Maintenant ça fonctionne
De manière étrange, j'avais bien des stats jusqu'au 31 mai, et a priori sans code résiduel piwik. Etrange…
Merci en tout cas pour votre réactivité
