### ISSUE TITLE
Release note plus verbeuses

### ISSUE THREAD

**Issue by lucmuller** [AmauriC/tarteaucitron.js#1140]
Salut Amauri.

C'est chouette que tu publie régulièrement de nouvelle version, ça me permet de maintenir efficacement mon plugin pour TYPO3 que j'utilise dans tous mes projets.
Voir : https://extensions.typo3.org/extension/ameos_tarteaucitron

Serait-il possible que tu mettes un peu plus d'information dans les release note des versions de tarteaucitron ? Cela aiderai a identifier rapidement quelles modifications ont été faites et quels ont été les services ajoutés et/ou modifiés et pour quelle raison.

Voilà l'état actuel des notes de version, il faut reconnaitre que c'est assez sommaire ^^
![image](https://github.com/AmauriC/tarteaucitron.js/assets/1927963/d19b4fdd-7b5d-447a-bb55-5f3ceb6b3a84)

Merci encore pour ton travail sur ce plugin vraiment formidable :)

**Comment by AmauriC** [comment]
Salut Luc!

J'essai de m'y tenir à le faire une fois par mois 😀

Les releases notes sont inexistantes mais l'outil "compare" de Github règle le problème comme sur tous les commits il y a une explication:
https://github.com/AmauriC/tarteaucitron.js/compare/v1.13.1...v1.14.0

**Comment by lucmuller** [comment]
Ha oui ok, ça semble adéquat.
J'utilise assez peu cette vue.
