### ISSUE TITLE
Google Tag bloqué

### ISSUE THREAD

**Issue by EstebanQui** [AmauriC/tarteaucitron.js#1141]
Bonjour , 

Lorsque j'installe Tarteaucitron sur mon site Wordpress, les boutons dans le Panneau de gestion des cookies sont non cliquable.   
![screen panneau de gestion](https://github.com/AmauriC/tarteaucitron.js/assets/74357764/1d7b9e03-3dff-4390-bfc8-d4e389fd35fc)

De plus le widget bloque tag GTM, je me demande pourquoi. 

Je voudrais savoir également si je peux ajouter un suivi sur des solutions tierces comme outgrow et tradingview qui génère leur propre clef google tag. 

Merci

**Comment by AmauriC** [comment]
Bonjour,

Il est normal que GTM soit bloqué, c'est un service soumis à consentement.
Par contre il devrait être dispo dans le panel tarteaucitron.

Possible d'avoir l'url du site?

**Comment by EstebanQui** [comment]
Bien sur le voici [https://www.lesmetauxprecieux.com/](url)

**Comment by AmauriC** [comment]
Merci. En effet il y a quelque chose qui entre en conflit avec le mode auto de tarteaucitron.
La détection ne fonctionne pas, GTM est chargé sans blocage.

Possible que ce soit dût au plugin de cache, possible de tester après désactivation?

**Comment by EstebanQui** [comment]
J'utilise WP faste cache je peux le désactiver afin de faire un test

**Comment by AmauriC** [comment]
Merci, du coup c'est pas ça.
Il y a aussi le plugin svg-support qui a du js jouant sur le chargement des elements, possible que ce soit lui le conflit.

**Comment by EstebanQui** [comment]
e l'ai également désactivé, mais aucun changement. Mes doutes portent sur Outgrow ou tradingview, mais je ne peux enlever aucun des deux ...

**Comment by AmauriC** [comment]
Dommage alors, tarteaucitron n'est pas compatible avec votre site 🙁

**Comment by AmauriC** [comment]
Avec WordPress il y a tellement de plugins et de configurations possibles que oui, c'est déjà arrivé et pour trouver la source du problème il faut passer par la désactivation de plugin jusqu'à trouver celui qui pose problème.

Une fois que c'est identifier, il est souvent possible de trouver une solution.

**Comment by EstebanQui** [comment]
Je vais donc voir en désactivant tous les plugins, en espérant que ça fonctionne.
Merci
