### ISSUE TITLE
Amélioration de l'accessibilité

### ISSUE THREAD

**Issue by spryah** [AmauriC/tarteaucitron.js#1142]
Bonjour Amauri,

Je vous transmets quelques retours sur l'accessibilité de la modale de configuration des choix, qui remonteraient dans le contexte d'un audit RGAA :

### 9.1. Dans chaque page web, l’information est-elle structurée par l’utilisation appropriée de titres ?
Il manque une sémantique de titre sur les éléments suivants :  "Cookies obligatoires", "Mesure d'audience", "Réseaux sociaux", etc. Ces éléments devraient être des titres de niveau 2, avec dans le cas de "Mesure d'audience" et "Réseaux sociaux" un bouton "Plus d'information" (en plus du titre) pour afficher l'infobulle associée.

### 7.1. Chaque script est-il, si nécessaire, compatible avec les technologies d’assistance ?
* "Cookies obligatoires" est annoncé comme un bouton alors que ça n'en est pas un.
* L'intitulé des boutons "Mesure d'audience" et "Réseaux sociaux" (et des titres suivants de même niveau) sont non explicites (cf. 9.1).

Pouvez-vous svp vérifier cela ?

Merci :relaxed:

**Comment by AmauriC** [comment]
Bonjour :)

Il des options pour je pense corriger ces points: 
- activer le regroupement des services par catégorie, ça ajoute un titre de niveau 2 et la description sans popup
- désactiver la nouvelle option "Cliquer pour ouvrir les détails du fonctionnement des cookies" pour aussi supprimer le popup d'explications

Le bouton pour les cookies obligatoires qui est inutile a été supprimé ;)

**Comment by spryah** [comment]
Merci beaucoup,

Nous avons donc ajouté les options suivantes pour obtenir le résultat désiré : 
```js
'groupServices': true,
'mandatoryCta': false,
```
