### ISSUE TITLE
Problem with youtube video service

### ISSUE THREAD

**Issue by pierrelevy** [AmauriC/tarteaucitron.js#1146]
While allowed, the YouTube video integration displays an empty frame with 'srcdoc' label.
using 1.14.0 release.

Here is the source code generated :
<div class="youtube_player" videoid="2ze1XJlNfEk" width="560" height="315" theme="dark" rel="0" controls="0" showinfo="1" autoplay="0" mute="0" srcdoc="srcdoc" loop="1" loading="0" start="0" end="0" style="width: 560px; height: 315px;">
    <iframe title="Youtube iframe" type="text/html" width="560" height="315" src="[//www.youtube-nocookie.com/embed/2ze1XJlNfEk?theme=dark&amp;rel=0&amp;controls=0&amp;showinfo=1&amp;autoplay=0&amp;mute=0&amp;start=0&amp;end=0&amp;loop=1&amp;enablejsapi=&amp;playlist=2ze1XJlNfEk](view-source:file:///embed/2ze1XJlNfEk?theme=dark&rel=0&controls=0&showinfo=1&autoplay=0&mute=0&start=0&end=0&loop=1&enablejsapi=&playlist=2ze1XJlNfEk)" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen="" srcdoc="srcdoc" loading=""></iframe>             
</div>

Thanks for help

Pierre

**Comment by pierrelevy** [comment]
A better souce code capture

<div class="youtube_player" videoid="2ze1XJlNfEk" width="560" height="315" theme="dark" rel="0" controls="0" showinfo="1" autoplay="0" mute="0" srcdoc="srcdoc" loop="1" loading="0" start="0" end="0" style="width: 560px; height: 315px;">
<iframe title="Youtube iframe" type="text/html" width="560" height="315" src="//www.youtube-nocookie.com/embed/2ze1XJlNfEk?theme=dark&amp;rel=0&amp;controls=0&amp;showinfo=1&amp;autoplay=0&amp;mute=0&amp;start=0&amp;end=0&amp;loop=1&amp;enablejsapi=&amp;playlist=2ze1XJlNfEk" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen="" srcdoc="srcdoc" loading=""></iframe>
</div>

**Comment by AmauriC** [comment]
What is the tarteaucitron code?
Srcdoc is added only if he's defined: https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.services.js#L4533

**Comment by pierrelevy** [comment]
Here is the written code :
<div class="youtube_player" videoID="2ze1XJlNfEk" width="560" height="315" theme="dark" rel="0" controls="0" showinfo="1" autoplay="0" mute="0" srcdoc="srcdoc" loop="1" loading="0" start="0" end="0"></div>

**Comment by pierrelevy** [comment]
<div class="youtube_player" videoID="2ze1XJlNfEk" width="560" height="315" theme="dark" rel="0" controls="0" showinfo="1" autoplay="0" mute="0" srcdoc="srcdoc" loop="1" loading="0" start="0" end="0"></div>

**Comment by pierrelevy** [comment]
div class="youtube_player" videoID="2ze1XJlNfEk" width="560" height="315" theme="dark" rel="0" controls="0" showinfo="1" autoplay="0" mute="0" srcdoc="srcdoc" loop="1" loading="0" start="0" end="0"></div>

**Comment by AmauriC** [comment]
Remove `srcdoc="srcdoc"`

**Comment by AmauriC** [comment]
Possible d'avoir l'url de la page? Première fois que j'ai ce retour 🧐

**Comment by pierrelevy** [comment]
Cela ne fonctionne pas en local, mais cela fonctionne desormais via un serveur http.
Merci beaucoup.:)
