### ISSUE TITLE
Error in reCaptcha

### ISSUE THREAD

**Issue by claytonedk** [AmauriC/tarteaucitron.js#1150]
Hi AmauriC,

I have a joomla extension called "Convert Forms" that allows me to create forms quickly using drag and drop input fields. One of the inputs available is the google recaptcha v2. The problem is that it generates an error when I add recaptcha in tarteaucitron services.

**tarteaucitron.js:1918     GET https://www.google.com/recaptcha/api.js?onload=tacRecaptchaOnLoad&render=6LcWHHsnAAAAAErKvBuHVTICOxlfX8XZMDH1knVb net::ERR_ABORTED 400

addScript @ tarteaucitron.js:1918
js @ tarteaucitron.services.js?v=20230203:3332
addService @ tarteaucitron.js:892
(anonymous) @ tarteaucitron.js:574
addScript @ tarteaucitron.js:1891
addInternalScript @ tarteaucitron.js:1923
(anonymous) @ tarteaucitron.js:526
script.onreadystatechange.script.onload @ tarteaucitron.js:1909
load (async)
addScript @ tarteaucitron.js:1905
addInternalScript @ tarteaucitron.js:1923
(anonymous) @ tarteaucitron.js:271
script.onreadystatechange.script.onload @ tarteaucitron.js:1909
load (async)
addScript @ tarteaucitron.js:1905
addInternalScript @ tarteaucitron.js:1923
load @ tarteaucitron.js:266
loadEvent @ tarteaucitron.js:114
(anonymous) @ tarteaucitron.js:45
load (async)
init @ tarteaucitron.js:44
(anonymous) @ infolettre-bnq.html:141**

The problem maybe is that Convert Forms initializes the recaptcha, it creates the div and the iframe.
```
<div class="cf-control-group " data-key="5" data-name="recaptchaaio_5" data-label="reCAPTCHA" data-type="recaptchaaio" data-required>
--
   <div class="cf-control-input">
    
   <div class="nr-recaptcha g-recaptcha"
   data-sitekey="6LcWHHsnAAAAAErKvBuHVTICOxlfX8XZMDH1knVb"
   data-theme="light"
   data-size="normal">
   </div>
   </div>
   </div>
```

Do you have an idea how to solve this problem ?

**Comment by AmauriC** [comment]
Hi

Thats an issue on the API key, this url shouldn't return a 400 error:
https://www.google.com/recaptcha/api.js?onload=tacRecaptchaOnLoad&render=6LcWHHsnAAAAAErKvBuHVTICOxlfX8XZMDH1knVb

**Comment by AmauriC** [comment]
Tarteaucitron support recaptcha v3

**Comment by claytonedk** [comment]
Hi, I tried with recaptcha v3 and it blocked the submit button until authorize, as expected.

The problem is that when I authorize it, the button submit action seems changed, it does not do what the button normally do. It is like tarteaucitron has changed the onSubmit event of the button. Do you have an idea ?

**Comment by AmauriC** [comment]
Tarteaucitron didn't change anything on the form or event.

It just load the script when authorized.

**Comment by claytonedk** [comment]
Yes, the problem seems to be the plugin that I use, it does not use the button with "g-recaptcha" and "data-site-key" classes, it uses the programatically approach. I tried to add "g-recaptcha" class and "data-site-key" to the button, it shows blocked as expected but when I authorize it, it does not work. I suppose that it is tarteaucitron that needs to call and initialize recaptcha, if it is initialized before by a plugin its is problematic. That is my case, I do not have control over it.

**Comment by AmauriC** [comment]
Thats probably because your form initialize the captcha on page load but recaptcha is not yet loaded.

There is this Javascript event to refresh the form when tarteaucitron load recaptcha:

```
document.addEventListener("recaptcha_loaded", function(){

   setTimeout(function() {
       // recaptcha fully loaded, refresh the form
   }, 500);

});
```

**Comment by claytonedk** [comment]
Is recaptcha v2 supported by TAC ?

**Comment by claytonedk** [comment]
You can close this issue.
