### ISSUE TITLE
Error in mootools.js

### ISSUE THREAD

**Issue by claytonedk** [AmauriC/tarteaucitron.js#1151]
Hi,

I am trying to add TaC to a old website developped using Joomla 2.5.

I add tarteaucitron.js in the head of our template and I called the code to initialize TaC. I have an error with a library called mootools-core.js.

mootools-core.js:125  Uncaught TypeError: Cannot read properties of undefined (reading 'indexOf')
    at new <anonymous> (mootools-core.js:125:73)
    at tarteaucitron.js:562:53
    at Object.addScript (tarteaucitron.js:1891:17)
    at Object.addInternalScript (tarteaucitron.js:1923:23)
    at tarteaucitron.js:526:31
    at script.onreadystatechange.script.onload [as onreadystatechange] (tarteaucitron.js:1909:29)

![image](https://github.com/AmauriC/tarteaucitron.js/assets/20322725/60349677-8cba-4592-80b1-e02f8eabe3a2)

It seems in the "tac.root_available" event.

Do you have an idea ?

**Comment by AmauriC** [comment]
Hi,

Looks like mootools is trying to read an id on an undefined element 🙄

I dont use this tool but the last update was on 2016 (https://mootools.net/blog/2016/01/14/mootools-1-6-0-release) so.. It's time to switch to something else 🙃

**Comment by claytonedk** [comment]
Yes I can't argue with you :D you can close the issue
