### ISSUE TITLE
TAC script adding eventListener after browser's event dispatch on Safari 

### ISSUE THREAD

**Issue by gmoocto** [AmauriC/tarteaucitron.js#1153]
Hello,

We noticed on our project that, when using Safari, the TAC script's line that adds an event listener on the browser "load" is often called _after_ the event is dispatched by the browser.
Therefore the TAC modal / button is not loaded 

We added this fix on our project, which works well : 
https://github.com/DNUM-SocialGouv/1j1s-front/pull/1441/commits/29bab3c6c6bac07cd9fe18f8986f19f3277ac486

**Comment by AmauriC** [comment]
Hi,
Did you load tarteaucitron with `async` or `defer` attribute?

**Comment by gmoocto** [comment]
We are using NextJS's `Script` component with `strategy="beforeInteractive"` which "loads the script before any Next.js code and before any page hydration occurs"

It does render a `script` tag with `defer`
