### ISSUE TITLE
adfrom : nombre de cookie

### ISSUE THREAD

**Issue by pierretux** [AmauriC/tarteaucitron.js#1154]
Bonjour,

Sur le site https://travail-emploi.gouv.fr/ on ne voit pas le nombre de cookie que Adform veut déposer
Comment définir cela ?

Cordialement

**Comment by AmauriC** [comment]
Bonjour,

La liste des cookies du service Adform est vide (https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.services.js#L5188).

Si le service en dépose sur le site, donnez moi la liste et je mettrai à jour ;)

**Comment by pierretux** [comment]
Sur la page ou j'ai mis adform j'ai un lien de cookie comme ceci ; https://track.adform.net/serving/container/?pm=...&lid=...&ctype=0&media=0&PageName=...&rnd=...&cpref=...

Est ce que c'est la liste de cookie ?

**Comment by AmauriC** [comment]
Actuellement adform ne se charge pas sur ce site, il manque le paramètre `tarteaucitron.user.adformpagename`

Je viens de tester, avec le paramètre Adform se charge correctement et ne dépose pas de cookie sur le site, donc l'affichage "pas de cookie" est correct.

**Comment by pierretux** [comment]
Le cookie est sur la page https://travail-emploi.gouv.fr/sante-au-travail/stop-aux-accidents-du-travail-graves-et-mortels/

`<script>tarteaucitron.user.adformpagename = '2023-09-securiteautravail.gouv-PageAccueil-AccueilSite';</script>`

**Comment by AmauriC** [comment]
Idem par de cookie déposé directement sur le site.
Il n'empeche que le consentement est requis pour charger Adform, même si il n'y a pas de cookie déposé sur le site.

**Comment by pierretux** [comment]
J'ai bien un dépôt de cookie pour adform
![image](https://github.com/AmauriC/tarteaucitron.js/assets/4512774/02458f7b-a182-496d-818c-0270c5ef93e5)

**Comment by AmauriC** [comment]
Oui mais en provenance d'un autre site. 

Impossible de modifier des cookies qui sont sur un autre site, adform ici.

Par contre quand adform est désactivé, le tag adform n'est pas chargé sur le site et les cookies deviennent inaccessibles.

**Comment by pierretux** [comment]
Dans ce cas, on peut modifié le texte pour indiquer que le cookie est déposé sur le site adform et non le site visité ?

**Comment by AmauriC** [comment]
Je ne suis pas sûr que ce soit très pertinent. Ce qui compte c'est que si l'utilisateur refuse, il n'y ai pas de dépôt/lecture.

Je reste ouvert à tout PR  ;)

**Comment by pierretux** [comment]
@AmauriC en fait le souhait est de faire comme ici https://www.1jeune1solution.gouv.fr/
Je vois des surcharge perso https://www.1jeune1solution.gouv.fr/scripts/tarteaucitron.js?v=3.159.8
Est ce que tu penses que je peux te le faire dans une PR ou c'est pas top / y'a mieux ?

**Comment by AmauriC** [comment]
C'est propre comme option mais il faudrait créer une nouvelle classe CSS plutôt que de reprendre l'ancienne et surtout créer les chaines génériques dans les 33 langues 🫣

Une autre solution pour un usage ponctuel :
```
window.addEventListener('tac.root_available', function() {
   jQuery('#googletagmanagerLine .tarteaucitronH3').after('<span>Why we use Google Tag Manager</span>');
});
```

**Comment by pierretux** [comment]
la chaine de lanque pourrait être le nom du tag justement googletagmanagerLineTexte par exemple ?

**Comment by AmauriC** [comment]
Le souci c'est qu'il faudrait inclure un texte de base pour chaque service.

**Comment by pierretux** [comment]
Bonjour @AmauriC 

Je me relance sur cette possibilité mais pour le moment cela ne rajoute rien dans le panneau de cookie.
Il faut placer le code a quel niveau dans le site ?

Merci

**Comment by AmauriC** [comment]
Salut,
Il manque un petit timeout:

```
<script>
window.addEventListener('tac.root_available', function() {
   setTimeout(function() {
      jQuery('#googletagmanagerLine .tarteaucitronH3').after('<span>Why we use Google Tag Manager</span><br/>');
   }, 200);
});
</script>
```
