### ISSUE TITLE
Support TCF 2.2

### ISSUE THREAD

**Issue by eficiens-eric** [AmauriC/tarteaucitron.js#1155]
iab a annoncé la v2.2 du TCF, avec une liste de 78 services conformes, dont des CMP comme Commanders Act, Cookiebot, Didomi, iubenda, OneTrust et Sirdata. 

Quelle est la position pour Tarteaucitron ?

Merci d'avance

**Comment by AmauriC** [comment]
Pas de TCF (ou autre tiers à qui déléguer le consentement) dans tarteaucitron.

**Comment by eficiens-eric** [comment]
Merci pour la réponse rapide. Comme ça c'est clair

**Comment by AmauriC** [comment]
Merci d'avoir posé la question 🙂
