### ISSUE TITLE
Problème avec l'installation des cookies

### ISSUE THREAD

**Issue by Dongwa1** [AmauriC/tarteaucitron.js#1159]
Bonjour, nous faisons face à des difficultés sur notre site, boutique.ffjudo.com, en ce qui concerne l'affichage récurrent des cookies à chaque actualisation de la page ou lors du changement de page. Même après avoir déjà accepté ou refusé les cookies, l'affichage persiste lorsque nous actualisons la page.
Ce problème se produit uniquement sur la version desktop du site, car sur la version mobile, les cookies ne sont même pas visibles.

Dans l'attente de votre retour, 

Adresse mail du compte tarte au citron : communication@ffjudo.com
Site web en question: boutique.ffjudo.com

**Comment by AmauriC** [comment]
Bonjour,

Je viens de tester sur différentes configuration et impossible de reproduire le problème.
La configuration est ok. Aucune autre remonté pour ce type de problème.
 
Chrome Mac ok
Safari Mac ok
Chrome iPhone ok
Safari iPhone ok
Edge Windows ok
Firefox Windows ok
 
 
Est-ce que vous utilisez un adblocker sur vos navigateurs ?
Il y a de mémoire certains plugins de navigateur qui interfèrent avec tarteaucitron et peuvent causer ce genre de comportement.
