### ISSUE TITLE
Plugin Joomla GMAPFP et tarteaucitron

### ISSUE THREAD

**Issue by Stepomp** [AmauriC/tarteaucitron.js#1160]
Bonjour,

Est-ce que quelqu'un utilise le plugin Joomla "GMAPFP" et a réussi à faire fonctionner tarteaucitron dessus ?

Je n'arrive pas à voir où ajouter : <div class="googlemaps-canvas" zoom="zoom" latitude="latitude" longitude="longitude" style="width: widthpx; height: heightpx;"></div><script>tarteaucitron.user.mapscallback = 'callback_function';tarteaucitron.user.googlemapsLibraries = 'LIBRARIES';</script>

Et où supprimer : <script src="https://maps.googleapis.com/maps/api/js?key=API KEY" type="text/javascript"></script>
<script type="text/javascript">
function initialize() {
    var mapOptions = {
        center: { lat: latitude, lng: longitude},
        zoom: zoom
    };
    var map = new google.maps.Map(document.getElementById('map-canvas'),
        mapOptions);
}
google.maps.event.addDomListener(window, 'load', initialize);
</script>

En vous remerciant

**Comment by AmauriC** [comment]
Bonjour,

Il faudrait voir ça avec les développeur du plugin pour inclure une compatibilité avec tarteaucitron.

Une autre solution serait le "mode auto" qui évite de devoir à modifier les intégrations mais c'est dans l'offre commerciale de tac.

**Comment by Stepomp** [comment]
Bonjour,

Merci pour ton retour,

Je l'ai contacté également, j'attends de voir sa réponse

Sinon, ça peut être l'occasion effectivement de passer à la version payante.

Je vous tiens au courant,
