### ISSUE TITLE
Cannot read properties of null (reading 'setAttribute')

### ISSUE THREAD

**Issue by vasilvestre** [AmauriC/tarteaucitron.js#1161]
With bad connection, this error appears and can be reproduced. A workaround would be to use .ready on the dom element ?

https://github.com/AmauriC/tarteaucitron.js/blob/594b0f6276c52173dceb5b3049d3f11f4d50434b/tarteaucitron.js#L1114

**Comment by AmauriC** [comment]
I'm not sure to understand the problem. Can you share a way to reproduce?

**Comment by vasilvestre** [comment]
Use the script in any app and enable throttling in developer setting with a really slow network and this happen

**Comment by ConiDev** [comment]
Hi,
I've made a simple repository to reproduce the error here: [click me](https://github.com/ConiDev/reproduce-lemonPie-issue)

It seems like the issue is caused by passing the adblocker option to true.
I also noticed another error by having the adblocker option set to true and not providing any job service

**Comment by AmauriC** [comment]
It make sense if the adblock check file is not loaded, services are not initialized.

I suggest you to disable this feature, not really useful.

**Comment by AmauriC** [comment]
Just spotted that you load `mycustomservice` on the tarteaucitron jobs.

Where is it defined?

**Comment by ConiDev** [comment]
I've added it at the beginning of the file in `public/tarteaucitron/tarteaucitron.services.js`
This was actually just to avoid an error and be able to reproduce the setAttribute one

**Comment by AmauriC** [comment]
Ok. Can you add a console.log on the key var in https://github.com/AmauriC/tarteaucitron.js/blob/594b0f6276c52173dceb5b3049d3f11f4d50434b/tarteaucitron.js#L1114
And also the rendered html at this point?

**Comment by ConiDev** [comment]
I've added some console.log, let me now if you need anything else !

**Comment by AmauriC** [comment]
Yes run the test and give me the output of the console log + the rendered html please ; )

**Comment by ConiDev** [comment]
Here's the output I get from running with a slow connection:

![image](https://github.com/AmauriC/tarteaucitron.js/assets/73347247/90dd59ed-1589-44ee-b5f3-eba0a4eb99f3)

and the output with a good connection:

![image](https://github.com/AmauriC/tarteaucitron.js/assets/73347247/444ffc58-140d-4df1-93d6-dee93c775e5f)

**Comment by AmauriC** [comment]
Thanks. The tarteaucitron.services.js file is loaded? Maybe your server close the connection before he's fully loaded?

**Comment by ConiDev** [comment]
It looks like the tarteaucitron.service.js file is loaded.
I don't know what is actually causing that problem, but keeping the adblock option to false does solve the issue.

Here's a screenshot from my network tab if it can be of any help

![image](https://github.com/AmauriC/tarteaucitron.js/assets/73347247/8d0bb197-03cc-4c22-8122-519eff03b5f3)
