### ISSUE TITLE
Soumettre à consentement le conversion linker de Google 

### ISSUE THREAD

**Issue by SW-Vincent** [AmauriC/tarteaucitron.js#1162]
Bonjour,

Je souhaite dans une intégration GTM de tarteaucitron soumettre la balise "conversion linker" à consentement.
Si on se fie au consent mode de google, cette balise correspond aux objectifs "ads" et "analytics" de tarteaucitron.
Pour information, cette balise a pour but la transmission du clic ID aux outils google d'une page à l'autre (ou d'un domaine à l'autre) sous la forme de l'ajout de paramètres d'url.

Si on veut une vue "objectif" je pense pouvoir sur la base du cookie tarteaucitron (tarteaucitron.cookie.read) et de l'élément "type"  (tarteaucitron.services.mon-service.type).

Si on veut une vue plutôt par "outil", il faudrait que le consentement associé soit dépendant du consentement associé à l'ensemble des outils Google, mais je ne pense pas qu'il y aie une variable permettant de faire le pont de manière dynamique.

**Comment by AmauriC** [comment]
Bonjour,

Intégrer tarteaucitron via GTM n'est pas une bonne pratique, GTM ne doit pas être chargé sans consentement ;)

Il n'y a pas de service Google Consent Mode sur tarteaucitron mais ça peux se faire via un service custom: https://github.com/AmauriC/tarteaucitron.js#create-custom-service
