### ISSUE TITLE
Blocage d'un cookie nécessaire au fonctionnement du site

### ISSUE THREAD

**Issue by tabularasadev** [AmauriC/tarteaucitron.js#1167]
Bonjour,
Nous avons un souci sur nos sites utilisant le CMS Contao, tournants sous Symfony.
Ce dernier sécurise les formulaires en réclamant systématiquement un token de sécurité. Ce token est stocké dans un cookie dénommé "csrf_https-contao_csrf_token".
Il semblerait que Tarteaucitron nous le bloque, ce qui empêche le bon fonctionnement de tous nos formulaires.
J'ai essayé de l'ajouter dans les services, mais cela ne résout pas le souci visiblement.
Ne serait-il pas possible d'avoir une variable de configuration pour lister les cookies nécessaires au fonctionnement du site ?
Merci.

**Comment by AmauriC** [comment]
Bonjour,
Ce cookie n'est pas dans la liste de ceux qui peuvent être supprimé par tarteaucitron.
Il pourrait le bloquer si il est dépendant d'un service tiers pour le poser.
Possible d'avoir l'url de la page?

**Comment by tabularasadev** [comment]
Bonjour,

Le problème est visible ici : https://www.icocc.fr/jeton.html
Ce qui est le plus étrange, c'est que ce dernier se reproduit uniquement lors de la première visite sur le site, il faut utiliser une nouvelle session en navigation privée à chaque fois. 
On en déduit que c'est tarteaucitron car lorsqu'on le retire des scripts, le souci ne se reproduit plus.
Merci.

**Comment by AmauriC** [comment]
Vous avez ajouté un service `contao` qui supprime ce cookie : https://www.icocc.fr/files/tabularasa/js/tarteaucitron/tarteaucitron.services.js

**Comment by tabularasadev** [comment]
Oui, c'était un test, que je n'ai pas retiré pour voir si cela changeait quelque chose. Je pensais pouvoir mettre un type "mandatory" ou quelque chose du genre.

**Comment by AmauriC** [comment]
J'arrive à reproduire, en navigation privée, au premier chargement de la page le cookie de session est absent.

Mais ça n'a aucun rapport avec tarteaucitron, vérifiez le script qui dépose ce cookie.

**Comment by tabularasadev** [comment]
Ok, je vais creuser dans d'autres directions du coup.

Merci pour votre aide.
