### ISSUE TITLE
Apple macOS Safari - the script is not loading every time

### ISSUE THREAD

**Issue by craoul10** [AmauriC/tarteaucitron.js#1169]
Hello,

I have a problem on Safari macOS, also on iPhone devices, the script is not running every time. When the user refresh the page, the sometimes is running and sometimes no.

I use this package in a ReactJS application.

I observed that the init function is called every time, but the function "loadEvent" is not called.

I entered on the end of the file the followed code:

function addLoadEvent() {
  tarteaucitron.initEvents.loadEvent(false);
}

function callUntilLoadFunctionExecuted() {
  if (!loadFunctionWasExecuted) {
    setTimeout(() => {
    addLoadEvent();
    }, 500);
  } else {
    clearInterval(interval);
  }
}

const interval = setInterval(callUntilLoadFunctionExecuted, 1000);

In this way the Tarteaucitron element is added every time, but still I think the parameters which I gave to him are not loaded correctly.

Does everyone has this problem? Do you have a solution ?

Thanks!

**Comment by cdricnj** [comment]
Hello, I am facing the same issue. Has anyone found a solution?
