### ISSUE TITLE
Tarteaucitron non autorisé par Google dès le début 2024

### ISSUE THREAD

**Issue by SW-Vincent** [AmauriC/tarteaucitron.js#1175]
Bonjour,

Google a récemment annoncé que les annonceurs n'utilisant pas les outils conformes à la norme TCF seraient pénalisés dans leurs annonces, applicable dès janvier 2024.
Tarteaucitron ne fait pas partie des solutions listées, ce qui va rapidement gêner la diffusion d'annonces et forcer plusieurs de nos clients à changer de CMP.

Est-il prévu que tarteaucitron cherche à se conformer à ces éléments ?

Article : https://support.google.com/adsense/answer/13554116

**Comment by AmauriC** [comment]
Bonjour,

Pour être certifié par Google il faut d'abord être approuvé par l'iab, payer une souscription, être audité par Google et par la suite suivre leurs consignes.

Ce n'est pas du tout le fonctionnement de tarteaucitron qui depuis le début est indépendant et open source.

**Comment by lucmuller** [comment]
Ce ticket est sommes toute intéressant par la question qu'il soulève.

Comment est-ce que Tarte Au Citron s'inscrit dans le cadre du TCF ?
Est-ce que le TCF en lui-même est reconnu et utilisé dans le cadre du RGPD ?

Je m'excuse si les questions sont simpliste, je viens de découvrir cette "norme".

**Comment by AmauriC** [comment]
Le TCF c'est en simplifiant à l'extreme la CNIL version marketing/publicitaire avec des normes pour partager le consentement avec des centaines d'acteurs pub.

Ca a évolué mais c'était au début les panneaux de contrôle avec une liste interminable de "partenaires" à cocher/décocher.

Un exemple qui n'inspire pas confiance dans leur process, pour s'enregistrer comme cmp approuvé par l'iab, il faut passer par https://register.consensu.org/CMP avec un joli widget recaptcha chargé sans consentement.. Alors que les conditions d'utilisations de recaptcha stipule que:

> En vertu de la section 3(d) des conditions d'utilisation des API Google, si vous utilisez les API, vous acceptez qu'il vous incombe d'en informer les utilisateurs et de leur demander leur autorisation pour la collecte et le partage de ces données avec Google. Dans l'Union européenne, le ou les clients d'API, et vous-même, devez vous conformer aux Règles relatives au consentement de l'utilisateur dans l'UE.

Je ne suis pas allé plus loin.


tarteaucitron n'existe pas au niveau de l'iab/tcf comme ce n'est pas un CMP approuvé.
Je n'ai d'ailleurs jamais été contacté pour l'être 😗

**Comment by lucmuller** [comment]
>tarteaucitron n'existe pas au niveau de l'iab/tcf comme ce n'est pas un CMP approuvé.
>Je n'ai d'ailleurs jamais été contacté pour l'être 😗

La question que je me pose, c'est comment serait-il possible de certifier un système opensource qui peut être modifié par n'importe qui.
Et donc, si Google va permettre de diffuser des annonces uniquement pour les éditeurs de sites qui utilisent un CMP approuvé, alors ça signe (encore plus) la mort des solutions libres.

J'ai un client qui fait des campagne adwords pour lequel j'ai installé TAC, je crains qu'il vienne un matin en me disant qu'il ne peut plus diffuser d'annonces car TAC n'est pas approuvé.

Le truc se mort la queue, car les seuls systèmes approuvables, seraient des systèmes centralisés via un service tiers... ou quelque chose m'échappe encore ?

**Comment by AmauriC** [comment]
Bonne question, est-ce que tarteaucitron en version open source (sans une société derrière) pourrait être accepté?
La première question du formulaire d'adhésion est "Billing entity name" pour la cotisation annuel de 1575e à régler pour rester dans le programme. Ca pourrait être via le sponsoring github et j'y participerai.
Je ne suis pas contre l'idée, à voir si c'est faisable.

Il est toujours possible d'utiliser tac et adsense mais via les réglages adsense il faut activer l'option pour afficher, après activation via tac, le cmp de google. Exemple https://www.wikimix.info/fr (très vieille version de tac mais ça montre le fonctionnement du second popup).

Bonne année à tous! ☺️

**Comment by eldk** [comment]
Bonjour,

Il est possible d'utiliser tarteaucitron et le système "Google consent management" d'adsense ou d'Ad manager conjointement.

C'est en test depuis 2 semaines.

Comment ?

1a - J'ai sorti les service Adsense et GPT (Ad manager) de la gestion par tarteaucitron.
1b - pour régler le soucis d'affichage des bannières de consentement lors de la première visite du site, j'ai forcé le DNT dans le script tarteaucitron.js : seule la bannière de consentement "Google consent management" s'affiche. Tous les services gérés par tarteaucitron sont donc à "false/désactivé", mais sont réactivables lorsque le visiteur clique sur "Autoriser"  des bannieres masquées.

Il y a donc : 
- Un popup activable pour la gestion des services par tarteaucitron
-  Un second popup activable pour les consentements liés à l'utilisation d'Adsense ou Ad Manager.

Je n'ai pas encore trouvé comment mixer les 2 : Google donne une solution simple pour l'utilisation d'Ad Manager seul, mais pas pour l'utilisation conjointe avec Adsense : https://support.google.com/admanager/answer/10114217?hl=en&ref_topic=10075594&sjid=18433075203474153689-EU#zippy=%2Ccode-sample.

On a donc :  

1 - Google Consent Management pour gérer tout ce qui est lié à la pub ...
2 - Tarteaucitron pour tout le reste

Cordialement,

Eric
