### ISSUE TITLE
Symfony 6.3 : Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by euroR67** [AmauriC/tarteaucitron.js#1176]
Bonjour, j'essaie d'installer et de configurer tarteaucitron dans mon projet en Symfony 6.3, mais j'ai l'erreur suivante
### Failed to load resource: the server responded with a status of 404 (Not Found)
, pourtant les chemins sont correcte :

j'ai mon fichier tarteaucitron.js dans le chemin suivant :

[C:\laragon\www\talentblend\templates\tarteaucitron\tarteaucitron.js](url)

`<script src="tarteaucitron/tarteaucitron.js"></script>`

et je souhaite utiliser ceci dans mon base.html.twig qui est dans la route suivante :

[C:\laragon\www\talentblend\templates\base.html.twig](url)

Lorsque je fait (ctrl + clic) sur le chemin du script j'ai bien le fichier js qui s'ouvre

**Comment by AmauriC** [comment]
Bonjour,
Dans la console du navigateur, quel est le fichier en 404?
Il y a le principal tarteaucitron.js mais aussi le fichier service et lang + le css.

**Comment by euroR67** [comment]
![Capture d'écran 2023-12-29 145321](https://github.com/AmauriC/tarteaucitron.js/assets/122833486/70005dbf-eabf-470d-a23e-ad6292fc755a)
![Capture d'écran 2023-12-29 145519](https://github.com/AmauriC/tarteaucitron.js/assets/122833486/bb3ee303-72d0-46d3-bb08-2187926bce88)
![Capture d'écran 2023-12-29 145636](https://github.com/AmauriC/tarteaucitron.js/assets/122833486/80a62aa2-f0be-4138-93f7-2d5131a54b6a)

**Comment by euroR67** [comment]
> Bonjour, Dans la console du navigateur, quel est le fichier en 404? Il y a le principal tarteaucitron.js mais aussi le fichier service et lang + le css.

![Capture d'écran 2023-12-29 145321](https://github.com/AmauriC/tarteaucitron.js/assets/122833486/4890b017-932d-487d-8dda-f77681b46a4b)
![Capture d'écran 2023-12-29 145636](https://github.com/AmauriC/tarteaucitron.js/assets/122833486/58f757d0-1a1c-4089-bdd2-707a7e0b3b70)
![Capture d'écran 2023-12-29 145519](https://github.com/AmauriC/tarteaucitron.js/assets/122833486/1d191aac-b10e-4882-8229-a9f9de047cec)

**Comment by AmauriC** [comment]
Un slash / devant tarteaucitron/ pour être sûr de le charger à la racine ?

**Comment by euroR67** [comment]
> Un slash / devant tarteaucitron/ pour être sûr de le charger à la racine ?

Si je met le slash devant , c'est pire, est quand je fait (ctrl + clic) il trouve pas du tout le fichier

mais l'erreur est un peu différent :
![Capture d'écran 2023-12-29 145321](https://github.com/AmauriC/tarteaucitron.js/assets/122833486/cba0db5b-9713-4db8-89d0-1a460ffa85e4)

**Comment by AmauriC** [comment]
Du coup c'est bien que le fichier n'est pas sur localhost/tarteaucitron 😕

**Comment by euroR67** [comment]
ok problème résolu j'ai fait :

`<script src="http://localhost/talentblend/tarteaucitron/tarteaucitron.js"></script>`

J'ai du renseigner le chemin complet...
