### ISSUE TITLE
Mailchimp popup

### ISSUE THREAD

**Issue by mosne** [AmauriC/tarteaucitron.js#118]
je viens de faire le service pour les popup de Mailchimp

`// mailchimp popup
tarteaucitron.services.mailchimp  = {
    "key": "mailchimp",
    "type": "api",
    "name": "Mailchimp Popup",
    "uri": "https://mailchimp.com/legal/privacy/",
    "needConsent": true,
    "cookies": [],
    "js": function () {
        "use strict";
        tarteaucitron.addScript('//downloads.mailchimp.com/js/signup-forms/popup/embed.js', '', function () {
            
            if (typeof tarteaucitron.user.mailchimpMore === 'function') {
                tarteaucitron.user.mailchimpMore();
            }
            
        });
     }
};`

utilisation
`tarteaucitron.user.mailchimpMore = function () { require(["mojo/signup-forms/Loader"], function(L) { L.start({"baseUrl":"mc.us10.list-manage.com","uuid":"XXXXXXXXXXXXXXXXXXXXXXXXX","lid":"XXXXXXXXXXXXXXXX"});});};
(tarteaucitron.job = tarteaucitron.job || []).push('mailchimp');`

**Comment by holzee** [comment]
would be cool to see it added to the services list
