### ISSUE TITLE
Erreur sur la fonction CSS calc()

### ISSUE THREAD

**Issue by nicozerr** [AmauriC/tarteaucitron.js#1182]
Dans les fichiers tarteaucitron[.min].css, le sélecteur [`#tarteaucitron #tarteaucitronServices .tarteaucitronTitle + [id^="tarteaucitronDetails"]`](https://github.com/AmauriC/tarteaucitron.js/blob/8a1735e42e0d49c1ceef16a217622a0c28593706/css/tarteaucitron.css#L562C12-L562C16) utilise la propriété `width` avec la valeur `Calc(100% - 40px)`. La majuscule de la fonction `Calc()` pose problème lors de l'utilisation d'un preprocesseur type node-sass, qui refuse de finir la tâche de génération du CSS final.

De plus, [la doc de cette fonction `calc()`](https://developer.mozilla.org/fr/docs/Web/CSS/calc) n'indique pas de majuscule.

Merci de remplacer `Calc` par `calc` (sans majuscule).

**Comment by tg-cbnmc** [comment]
Même souci observé, 

```bash
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Incompatible units: 'px' and '%'.
        on line 561 of node_modules/tarteaucitronjs/css/tarteaucitron.css
        from line 8 of assets/css/vendors.scss
>>     width: Calc(100% - 40px);
```

Ca serait top d'avoir cette correction pour éviter d'avoir à versionner le fichier CSS corrigé. 🙏

**Comment by tg-cbnmc** [comment]
Merci @AmauriC !
