### ISSUE TITLE
Still a risk of XSS with getElemWidth and getElemHeight methods

### ISSUE THREAD

**Issue by mably** [AmauriC/tarteaucitron.js#1184]
I think there is still a risk of XSS attack left with theses two methods:

<img width="774" alt="image" src="https://github.com/AmauriC/tarteaucitron.js/assets/385653/e8eebe50-38fc-4b62-8ca1-f5390dfe404d">

I think they should both use the getElemAttr utility method to avoid any risk.

Such usage as below of those methods could put users at risk:

<img width="962" alt="image" src="https://github.com/AmauriC/tarteaucitron.js/assets/385653/169b8978-97ae-4393-92be-107940dc6f51">

**Comment by mably** [comment]
I think it's an important fix to have.

**Comment by Rudloff** [comment]
@AmauriC would it be possible to publish a security advisory for this fix? (See [this documentation](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/publishing-a-repository-security-advisory).)
This allows users to know they should update to a secure version.
