### ISSUE TITLE
Tarte au citron, Google Maps & Divi

### ISSUE THREAD

**Issue by Nuyonuyonoina** [AmauriC/tarteaucitron.js#1187]
Bonjour. J'ai un problème avec les sites utilisant le plugin WordPress de Tarte au citron, Divi et Google Maps. Que l'on accepte ou non les cookies, seul un grand blanc s'affiche à la place de la carte Google Maps créée avec Divi. Je retrouve le problème sur tous mes sites utilisant Divi. Le message d'erreur dans la console est "Google Maps JavaScript API has been loaded directly without a callback. This is not supported and can lead to race conditions and suboptimal performance. For supported loading patterns please see https://goo.gle/js-api-loading". Lorsque je désactive Tarte au citron, la carte s'affiche normalement.
Par contre, avec Elementor, pas de souci. 
Une idée pour pouvoir de nouveau utiliser Tarte au citron avec Divi ? D'avance, merci.

**Comment by AmauriC** [comment]
Bonsoir,
C'est parce que Divi initialise la carte au chargement de la page mais tarteaucitron bloque et différe le chargement de la librairie Google Maps.
Je n'ai jamais réussi à avoir un retour de Divi pour recharger la creation de la carte quand tarteaucitron charge la librairie gmaps 😕
