### ISSUE TITLE
[Enhancement] Prévenir l'appel multiple de tarteaucitron lors de l'appel manuel à tarteaucitron.initEvents.loadEvent

### ISSUE THREAD

**Issue by SW-Vincent** [AmauriC/tarteaucitron.js#1190]
Bonjour Amauri,

J'ai rencontré un problème similaire au topic suivant : https://github.com/AmauriC/tarteaucitron.js/issues/1072#issuecomment-1453674482
La résolution n'a pas été tout à fait la même car l'ordre de chargement entre tarteaucitron et le dom n'était pas toujours le même. Cela m'a permis de constater que tarteaucitron pouvait se charger plusieurs fois ce qui générait des problèmes d'affichage.
Voici ce qui a marché pour moi : 
```
  if (document.readyState === "complete") {
    // L'événement "load" s'est déjà produit
        tarteaucitron.initEvents.loadEvent(false);
  } else {
    // L'événement "load" ne s'est pas encore produit, le code de base affiche TAC
  }   
```
Pour autant je considère ça comme un workaround. **Serait-il possible de modifier le code de manière à prévenir l'appel multiple de tarteaucitron ?**
Cela rendrait l'usage de TAC via n'importe quel TMS plus simple.

Note : je connais ta position sur l'usage de Google Tag Manager, mais l'usage d'un Tag Manager en général (hors Google) ne me semble pas une mauvaise pratique du point de vue RGPD.

**Comment by AmauriC** [comment]
Il y a maintenant un boolean `tarteaucitronIsLoaded` dans la fonction `load`. 
Ca devrait régler le souci. Je ferme mais si besoin, n'hésites pas à réouvrir ; )
