### ISSUE TITLE
[Enhancement/UX] Ajouter un bouton "Enregistrer" dans le menu de personalisation

### ISSUE THREAD

**Issue by SW-Vincent** [AmauriC/tarteaucitron.js#1191]
Bonjour Amauri,

A ce jour, lorsque l'utilisateur accède à la partie "Personnaliser" du bandeau cookie, il n'y a pas de bouton "Enregistrer" pour valider ses choix. 
L'utilisateur doit alors faire ses choix et fermer la fenêtre. Cela pose deux problème : 
 - valider ses choix via le bouton fermer n'est pas intuitif ;
 - si il reste au moins un service sur lequel l'utilisateur s'est prononcé explicitement, le bandeau cookie se réaffiche ;

Il faudrait donc : 
 - ajouter un bouton "Enregistrer ses choix" dans la modale de personnalisation ;
 - que fermer la ou enregistrer ses choix suite à au moins un choix explicite refuse tous les autres cookies pour prévenir le réaffichage du bandeau ;

![image](https://github.com/AmauriC/tarteaucitron.js/assets/118832007/b6c2fc1e-3b09-4875-b36d-a60ff676cd31)

**Comment by AmauriC** [comment]
C'est dispo :)
https://github.com/AmauriC/tarteaucitron.js/commit/c963fa88271d4890e13b6e5473475ac6fc16e6f6

**Comment by AmauriC** [comment]
-

**Comment by SW-Vincent** [comment]
> Quel serait l'intérêt de le différer?
Le point que j'avais en tête était de limiter le nombre de déclenchements de l'événement de mise à jour du consentement. Cela permettrait par exemple de limiter les coûts liés à du server-side tracking (en réduisant le nombre de requêtes entrantes), puisque c'est un sujet d'actualité avec la fin des cookies tiers.

Au delà de ça je n'ai pas particulièrement d'arguments en tête.
A noter qu'il serait pertinent si l'option est activée de désactiver la fermeture du bandeau sans validation (ex : lorsque l'on clique en dehors du bandeau).

**Comment by AmauriC** [comment]
Ok, merci, je note ; )
