### ISSUE TITLE
URL Google Fonts API

### ISSUE THREAD

**Issue by SeptimusVII** [AmauriC/tarteaucitron.js#1194]
Bonjour,
En intégrant une Google Font sur un site, j'ai remarqué qu'il manquait une large sélection de font weight. 
Après vérification, il semble que Google distribue maintenant ses fonts via une url légèrement différente

Tarteaucitron:
https://fonts.googleapis.com/css?family=Exo+2:ital,wght@0,100..900;1,100..900&display=swap
(ne fournit que les font weight 100 et 400)

Google: 
https://fonts.googleapis.com/css2?family=Exo+2:ital,wght@0,100..900;1,100..900&display=swap
(fournit les font weight de 100 à 900)

**Comment by AmauriC** [comment]
tac utilise le [WebFontLoader de typekit](https://github.com/typekit/webfontloader) mais ça n'a en effet pas été mis à jour depuis très longtemps.

Même en forçant dans le nom de la font le weight ça ne règle pas le souci?
https://github.com/typekit/webfontloader?tab=readme-ov-file#google

**Comment by SeptimusVII** [comment]
En effet, ça fonctionne avec cette syntaxe : `Exo+2:ital,100,200,300,400,500,600,700,800,900`

**Comment by AmauriC** [comment]
Je ferme mais je note d'améliorer ce service pour passer par l'ajout de balise CSS sans utiliser cette ancienne librairie.
