### ISSUE TITLE
Cannot read properties of null (reading 'insertAdjacentHTML')

### ISSUE THREAD

**Issue by informalys** [AmauriC/tarteaucitron.js#1195]
Bonjour,

Depuis la mise à jour Wordpress 6.4.3, l'ensemble des sites gérés par mon abonnement premium Tarteaucitron présentent le problème suivant : 

Les boutons du bandeau ne répondent pas. Impossible de cliquer dessus.

Il y a une erreur en console : 

Uncaught TypeError: Cannot read properties of null (reading 'insertAdjacentHTML') 

Cette erreur renvoie à la ligne : 

`tacSaveButtonParent.insertAdjacentHTML("beforeend", '<div id="tarteaucitronSave"><button class="tarteaucitronAllow" id="tarteaucitronSaveButton">' + tarteaucitron.lang.save + "</button></div>");
`
J'emploie l'extension Wordpress
Vous pouvez me contacter pour que je fournisse un URL et un accès pour analyse.

Je ne suis malheureusement pas dev et ne peux donc par résoudre ce problème par moi-même.
Bien cordialement

**Comment by AmauriC** [comment]
Bonsoir,

Je viens de publier un correctif, recharger la page rechargera le script tarteaucitron et le problème devrait être réglé.

Je veux bien l'URL d'un site pour plus d'investigation amauri@champeaux.fr

Merci pour le retour 👍

**Comment by AmauriC** [comment]
Merci pour le retour par mail, c'est définitivement réglé ; )
