### ISSUE TITLE
Add optional Nonce to addScript

### ISSUE THREAD

**Issue by vdeville** [AmauriC/tarteaucitron.js#1198]
Hello,

Is possible to add generated server nonce to all addScript make by TAC ?
For example for GTM.js, refuse to load external google scripts because CSP not allowed when CSP is enabled.
By default if GTM.js is load with nonce="xx" GTM propagate this nonce to all sub scripts load

Thanks

**Comment by AmauriC** [comment]
Hey

How tarteaucitron will be able to get the nonce?

**Comment by vdeville** [comment]
Hello,
If you use template engine like Twig by example you can add the nonce to the TAC constructor init()
Thanks
