### ISSUE TITLE
gajs service "gray area"

### ISSUE THREAD

**Issue by devyg** [AmauriC/tarteaucitron.js#12]
Would this work and be CNIL-compliant in a new grayJs function added to gajs service ?

`_gaq.push(['_gat._anonymizeIp']);`

**Comment by AmauriC** [comment]
Gray JS is no longer supported. It's not a good idea to leave a not CNIL compliant alternative in this script.

**Comment by devyg** [comment]
I agree. It would be strange to leave it (and hidden) while you claim your tool complies with the law.
