### ISSUE TITLE
Google reCAPTCHA v3

### ISSUE THREAD

**Issue by caro43** [AmauriC/tarteaucitron.js#1202]
Bonjour,

Je ne trouve pas le code pour Google reCAPTCHA v3 dans le paramétrage, car si j'intègre le code existant cela supprime le nom de mon bouton étant donné que la key est sur le bouton.

`<button class="g-recaptcha" 
        data-sitekey="reCAPTCHA_site_key" 
        data-callback='onSubmit' 
        data-action='submit'>Submit</button>`

Merci d'avance

**Comment by AmauriC** [comment]
Bonjour,

Le code recaptcha v2 v3 est le même sauf erreur, c'est une configuration côté Google pour choisir le niveau d'API.

Pas sûr de comprendre le problème de suppression de nom, possible d'avoir une url pour reproduire de mon côté?

**Comment by caro43** [comment]
En fait cela supprime l'intitulé du button, normalement entre les balises button j'ai "ENVOYER" et quand on accepte les cookies cela le supprime
![image](https://github.com/AmauriC/tarteaucitron.js/assets/47216082/c897c684-90d7-4ced-9f02-c8152f1a1e62)

**Comment by caro43** [comment]
![image](https://github.com/AmauriC/tarteaucitron.js/assets/47216082/dce41d95-7683-471a-afad-5313522df5fc)

**Comment by caro43** [comment]
j'ai trouvé où le corriger mais je ne sais pas ce que ça implique de ne pas mettre vide (ligne en gras)
`    "fallback": function (matchClass, content, noInner) {
        "use strict";
        var elems = document.getElementsByTagName('*'),
            i,
            index = 0;

        for (i in elems) {
            if (elems[i] !== undefined) {
                for (index = 0; index < matchClass.length; index += 1) {
                    if ((' ' + elems[i].className + ' ')
                            .indexOf(' ' + matchClass[index] + ' ') > -1) {

                        if (typeof content === 'function') {
                            if (noInner === true) {
                                content(elems[i]);
                            } else {
                                elems[i].innerHTML = content(elems[i]);
                            }
                        } else {
                            **elems[i].innerHTML = content(elems[i]);**
                        }
                    }
                }
            }
        }
    },`

**Comment by AmauriC** [comment]
Avec l'url de la page ce serait plus simple, en privé si vous voulez (amauri@tarteaucitron.io).

**Comment by caro43** [comment]
Bonjour,
Je vous l'ai envoyé par mail. merci

**Comment by AmauriC** [comment]
Merci.

Ajoutez ce code js, ça remettra le libellé du bouton:

```
document.addEventListener('recaptcha_loaded', function() {
   jQuery('button.g-recaptcha').html('ENVOYER');
});
```

**Comment by caro43** [comment]
Merci beaucoup !

Bonne journée


Restant à votre entière disposition au besoin,



Caroline ANJARRY
Développeuse web, logiciel & mobile



[cid:5f4c1e42-03a7-415f-94df-649f8c6d81e7]Solutions informatiques pour les professionnels
Réseau d’entreprise | Matériel | Site web & Android | ERP Métiers | Audit | Infogérance | Caisse enregistreuse

Solution Micro - 144, rue Léon Mathieu - ZA de Taulhac - 43000 Le Puy en Velay
04 71 04 17 55 - www.solution-micro.com<http://www.solution-micro.com/>

[cid:f10a45e0-60ac-4706-b9bd-ed1269757482]<https://www.facebook.com/SolutionMicro43/>  [cid:fd70e8be-60e9-485f-be83-9319eb9856f5] <https://www.instagram.com/solution_micro/>   [cid:0989d4f3-1bc2-4cf1-a285-b5d08b171176] <https://www.linkedin.com/in/caroline-anjarry/>    [cid:a93cb808-5ef9-48db-ad17-46878100727b] <https://www.solution-micro.com/services-informatiques-haute-loire/codial-erp-logiciel-devis-facture-haute-loire/>     [cid:b0ae9298-aa60-4d08-af6f-0e13503a5ba9] <https://www.eurabis.com/>




________________________________
De : Amauri CHAMPEAUX ***@***.***>
Envoyé : jeudi 14 mars 2024 09:27
À : AmauriC/tarteaucitron.js ***@***.***>
Cc : Caroline Anjarry Solution Micro ***@***.***>; Author ***@***.***>
Objet : Re: [AmauriC/tarteaucitron.js] Google reCAPTCHA v3 (Issue #1202)


Merci.

Ajoutez ce code js, ça remettra le libellé du bouton:

document.addEventListener('recaptcha_loaded', function() {
   jQuery('button.g-recaptcha').html('ENVOYER');
});
