### ISSUE TITLE
Consent mode default push by default

### ISSUE THREAD

**Issue by csonrel** [AmauriC/tarteaucitron.js#1203]
Bonjour, 

Je me rends compte que vous poussez nativement un consent mode default sur l'ensemble des sites ?

J'ai un exemple de sites où personne n'est intervenu dessus et vous poussez dans la configuration 
googleConsentMode: true, ce qui pousse un default dans le consent mode
![image](https://github.com/AmauriC/tarteaucitron.js/assets/45960995/1bb47657-3107-4858-8a36-6b25518c35e8)
Mais cela ne peut pas aller si par exemple le site ne possède que le service GTM......ou bien si on utilise les services personnalisés et cela altère les données sur l'ensemble de GA4 et google ADS car nous n'avons aucune mise à jour de l'update.

Avez vous fait une activation par défaut de ce parmètre sur l'ensemble de vos versions de TAC ?

A

**Comment by csonrel** [comment]
Bon, je crois que j'ai un peu ma réponse, vous avez activé le consent mode default par défault sur les sites.....Il vous faut absolument décocher cette option nativement
![image](https://github.com/AmauriC/tarteaucitron.js/assets/45960995/c2ed526a-4815-4eef-8306-978b89ea103b)

**Comment by AmauriC** [comment]
En effet le consent mode a été activé par défaut, c'était beaucoup plus simple pour la grande majorité des utilisateurs.

Si il n'y a pas GA4 / Google Ads dans le panneau, il est possible d'ajouter manuellement tous les signaux GCM via les services tac.

**Comment by csonrel** [comment]
Oui j'imagine,

Mais je pense que vous avez aussi beaucoup de personnes qui ne sont pas au courant de cette MAJ et ou de la procédure de mise en place et qui vont se retrouver avec des stats à 0 dans GA4 soit parce que le default est à denied et donc que les données ne vont pas rentrer dans l'interface
Soit que le volume pour modéliser les données n'est pas suffisant et se rajoute aussi le fait que vous devez avoir des comptes pros "gratuits" et donc limité à 3 services.

Et finalement, il y a aussi des comptes pro avec des customs services.


Cédric SONREL
[Responsable Pôle Analytics]
Ligne directe : +33 4 78 41 03 33

Ligne Portable : +33 6 64 82 02 14
***@***.***

[https://redir.cybercite.fr/email/logo.png?s=bnFubFdUS2paV01YbmVXL1k0N0lSc3R3NjMyaHVWUEFiUnpJTmRyTUVucz0%3D]<https://redir.cybercite.fr/email/logo?s=bnFubFdUS2paV01YbmVXL1k0N0lSc3R3NjMyaHVWUEFiUnpJTmRyTUVucz0%3D>

LYON • CHAMBERY • PARIS • NANTES • NICE • RENNES
www.cybercite.fr<https://www.cybercite.fr/>

<https://redir.cybercite.fr/email/bandeau?s=bnFubFdUS2paV01YbmVXL1k0N0lSc3R3NjMyaHVWUEFiUnpJTmRyTUVucz0%3D>
[Page LinkedIn de CyberCité]<https://redir.cybercite.fr/email/linkedin?s=bnFubFdUS2paV01YbmVXL1k0N0lSc3R3NjMyaHVWUEFiUnpJTmRyTUVucz0%3D>[Page Instagram de CyberCité]<https://redir.cybercite.fr/email/instagram?s=bnFubFdUS2paV01YbmVXL1k0N0lSc3R3NjMyaHVWUEFiUnpJTmRyTUVucz0%3D>[Page Facebook de CyberCité]<https://redir.cybercite.fr/email/facebook?s=bnFubFdUS2paV01YbmVXL1k0N0lSc3R3NjMyaHVWUEFiUnpJTmRyTUVucz0%3D>[Flux X (Twitter) de CyberCité]<https://redir.cybercite.fr/email/x?s=bnFubFdUS2paV01YbmVXL1k0N0lSc3R3NjMyaHVWUEFiUnpJTmRyTUVucz0%3D>[Chaîne YouTube de CyberCité]<https://redir.cybercite.fr/email/youtube?s=bnFubFdUS2paV01YbmVXL1k0N0lSc3R3NjMyaHVWUEFiUnpJTmRyTUVucz0%3D>[Page TikTok de CyberCité]<https://redir.cybercite.fr/email/tiktok?s=bnFubFdUS2paV01YbmVXL1k0N0lSc3R3NjMyaHVWUEFiUnpJTmRyTUVucz0%3D>[Avis clients sur CyberCité]<https://redir.cybercite.fr/email/customer-reviews?s=bnFubFdUS2paV01YbmVXL1k0N0lSc3R3NjMyaHVWUEFiUnpJTmRyTUVucz0%3D>

Bâtiment Iroko - e.Golf-Park - 950, avenue Roumanille - F-06410 Biot - Tél : +33 (0)4 22 13 04 32 - Fax : +33 (0)4 26 68 24 17

________________________________
De : Amauri CHAMPEAUX ***@***.***>
Envoyé : mercredi 13 mars 2024 17:38
À : AmauriC/tarteaucitron.js ***@***.***>
Cc : SONREL Cédric ***@***.***>; Author ***@***.***>
Objet : Re: [AmauriC/tarteaucitron.js] Consent mode default push by default (Issue #1203)


En effet le consent mode a été activé par défaut, c'était beaucoup plus simple pour la grande majorité des utilisateurs.

Si il n'y a pas GA4 / Google Ads dans le panneau, il est possible d'ajouter manuellement tous les signaux GCM via les services tac.

**Comment by AmauriC** [comment]
Le consent mode est de toute façon obligatoire maintenant? Donc avec ou sans le denied par defaut, sans l'instruction rien ne remonte?

Sur les comptes pro gratuits ça va bientôt être terminé mais je ne comprend pas le rapport avec GCM.

**Comment by csonrel** [comment]
Oui, il est obligatoire effectivement,  mais tout le monde n'est pas au courant de sa mise en place, de ses effets ou n'a pas encore décidé de le mettre en place ou bien est en retard sur sa mise en place.

Et en mettant en place un default à denied sur l'ensemble des 4 paramètres, vous n'avez plus rien dans GA4.


Cédric SONREL
[Responsable Pôle Analytics]
Ligne directe : +33 4 78 41 03 33

Ligne Portable : +33 6 64 82 02 14
***@***.***

[https://redir.cybercite.fr/email/logo.png?s=bnFubFdUS2paV01YbmVXL1k0N0lSc3R3NjMyaHVWUEFiUnpJTmRyTUVucz0%3D]<https://redir.cybercite.fr/email/logo?s=bnFubFdUS2paV01YbmVXL1k0N0lSc3R3NjMyaHVWUEFiUnpJTmRyTUVucz0%3D>

LYON • CHAMBERY • PARIS • NANTES • NICE • RENNES
www.cybercite.fr<https://www.cybercite.fr/>

<https://redir.cybercite.fr/email/bandeau?s=bnFubFdUS2paV01YbmVXL1k0N0lSc3R3NjMyaHVWUEFiUnpJTmRyTUVucz0%3D>
[Page LinkedIn de CyberCité]<https://redir.cybercite.fr/email/linkedin?s=bnFubFdUS2paV01YbmVXL1k0N0lSc3R3NjMyaHVWUEFiUnpJTmRyTUVucz0%3D>[Page Instagram de CyberCité]<https://redir.cybercite.fr/email/instagram?s=bnFubFdUS2paV01YbmVXL1k0N0lSc3R3NjMyaHVWUEFiUnpJTmRyTUVucz0%3D>[Page Facebook de CyberCité]<https://redir.cybercite.fr/email/facebook?s=bnFubFdUS2paV01YbmVXL1k0N0lSc3R3NjMyaHVWUEFiUnpJTmRyTUVucz0%3D>[Flux X (Twitter) de CyberCité]<https://redir.cybercite.fr/email/x?s=bnFubFdUS2paV01YbmVXL1k0N0lSc3R3NjMyaHVWUEFiUnpJTmRyTUVucz0%3D>[Chaîne YouTube de CyberCité]<https://redir.cybercite.fr/email/youtube?s=bnFubFdUS2paV01YbmVXL1k0N0lSc3R3NjMyaHVWUEFiUnpJTmRyTUVucz0%3D>[Page TikTok de CyberCité]<https://redir.cybercite.fr/email/tiktok?s=bnFubFdUS2paV01YbmVXL1k0N0lSc3R3NjMyaHVWUEFiUnpJTmRyTUVucz0%3D>[Avis clients sur CyberCité]<https://redir.cybercite.fr/email/customer-reviews?s=bnFubFdUS2paV01YbmVXL1k0N0lSc3R3NjMyaHVWUEFiUnpJTmRyTUVucz0%3D>

Bâtiment Iroko - e.Golf-Park - 950, avenue Roumanille - F-06410 Biot - Tél : +33 (0)4 22 13 04 32 - Fax : +33 (0)4 26 68 24 17

________________________________
De : Amauri CHAMPEAUX ***@***.***>
Envoyé : mercredi 13 mars 2024 17:50
À : AmauriC/tarteaucitron.js ***@***.***>
Cc : SONREL Cédric ***@***.***>; Author ***@***.***>
Objet : Re: [AmauriC/tarteaucitron.js] Consent mode default push by default (Issue #1203)


Le consent mode est de toute façon obligatoire maintenant? Donc avec ou sans le denied par defaut, sans l'instruction rien ne remonte?

Sur les comptes pro gratuits ça va bientôt être terminé mais je ne comprend pas le rapport avec GCM.

**Comment by AmauriC** [comment]
Si tarteaucitron est correctement configuré et gère GA4, c'est transparent pour l'utilisateur, les signaux sont passés en granted quand GA4 est autorisé.

Si par contre tarteaucitron n'a été configuré que pour activer/désactiver GTM, en effet il faudra une étape en plus (ajouter manuellement les services GCM) mais ça n'a jamais été une bonne pratique de faire comme ça.

Si il n'y a pas les signaux denied, GA4 continue à collecter des données comme avant?
Ce serait surprenant, je pensai qu'il ne le faisait que quand le signal est granted depuis le 6 mars.

**Comment by csonrel** [comment]
Bonjour Amaury, 

Merci pour vos réponses avant toute chose.
Oui GA4 va continuer à collecter surtout sur GA4. La mise en place du consent mode est avant tout pour les produits GADS et sera; c'est certain déployer ensuite sur GA4. IL y a déjà des informations sur la prise en compte des paramètres des comptes GA4 à ce sujet, mais si vous ne mettez pas encore le consent mode, des données sont collectées.

Je vous laisse éventuellement regarder dans vos bases combien de vos clients pro on juste activer GTM dans la plate forme et vous pourrez vous donner une idée des implications de la mise en place du paramètre default par défault

Nous sensibilisons toujours nos clients à cette mise en place et nous reprenons en général les configurations en mettant en place des services personnalisées sous cette forme

**Comment by AmauriC** [comment]
Merci pour les explications. Je comprend mieux votre fonctionnement.

L'option restera en "activé par défaut", c'est le comportement voulu par la très large majorité des utilisateurs mais vous pouvez toujours le désactiver depuis la console tarteaucitron.

**Comment by VincentColombeau** [comment]
Bonjour @AmauriC ,
Le consent mode ne fonctionne pas si on a mis en place le tracking Google Ads via GTM.
Si je rajoute le code ci-dessous, le consent mode fonctionne mais mon tracking Google Ads est comptabilisé deux fois...
  <script type="text/javascript">
        tarteaucitron.user.googleadsId = 'AW-XXXXXXXXX';
        (tarteaucitron.job = tarteaucitron.job || []).push('googleads');
        </script>
Comment faire ?
Merci d'avance pour votre aide.

**Comment by AmauriC** [comment]
@VincentColombeau Il ne faut pas ajouter le service Google Ads car il est déjà chargé par GTM.
La bonne pratique est de retirer GAds de GTM et l'intégrer via tarteaucitron, si ce n'est pas possible, vous pouvez ajouter les services Consent Mode :

```
<script type="text/javascript">
(tarteaucitron.job = tarteaucitron.job || []).push('gcmanalyticsstorage');
(tarteaucitron.job = tarteaucitron.job || []).push('gcmadsuserdata');
(tarteaucitron.job = tarteaucitron.job || []).push('gcmadstorage');
</script>
```

**Comment by SW-Vincent** [comment]
Bonjour @AmauriC,

Je suis ravi de savoir que cette option existe !
Serait-il possible de savoir à partir de quelle version le consent mode v2 est pris en compte ?

**Comment by VincentColombeau** [comment]
> @VincentColombeau Il ne faut pas ajouter le service Google Ads car il est déjà chargé par GTM. La bonne pratique est de retirer GAds de GTM et l'intégrer via tarteaucitron, si ce n'est pas possible, vous pouvez ajouter les services Consent Mode :
> 
> ```
> <script type="text/javascript">
> (tarteaucitron.job = tarteaucitron.job || []).push('gcmanalyticsstorage');
> (tarteaucitron.job = tarteaucitron.job || []).push('gcmadsuserdata');
> (tarteaucitron.job = tarteaucitron.job || []).push('gcmadstorage');
> </script>
> ```

Merci beaucoup @AmauriC . Cela semble fonctionner !
