### ISSUE TITLE
Paramètre enablejsapi pour Youtube

### ISSUE THREAD

**Issue by SW-Vincent** [AmauriC/tarteaucitron.js#1206]
Bonjour,

Je souhaite effectuer le suivi statistiques des vidéos Youtube sur mon site.
Actuellement, celles-ci sont soumises à consentement via tarteaucitron.

Pour ce faire, j'aurais besoin de deux choses : 
 - la présence du paramètre "enablejsapi" dans l'url finale de l'IFrame ;
 - l'envoi d'une ligne de code (pour ré-évaluer la présence de la vidéo) une fois la vidéo chargée ;

Pour le premier point, j'imagine que cela nécessite d'être implémenté dans l'outil pour que renseigner l'attribut fonctionne.
Est-ce possible d'avoir cette fonctionnalité ou y a-t-il une prise de position sur le sujet ?

Pour le second point, dans la mesure où j'ai besoin que la ligne de code soit exécutée après que l'IFrame soit chargé, sais-tu s'il est possible de paramétrer un callback ou un event listener ?
Je pense qu'utiliser "onClick" seul déclencherait mon instruction trop tôt.

------------------------------

Additionnellement, je me permet une petite proposition sur les options de mise en forme : 
Avoir des options de mise en forme règlerait le souci des vidéos peu attirantes (qui est un point bloquant pour certains clients).

Par exemple : 
 - l'ajout d'une image de fond personnalisée ou de la vignette https://i.ytimg.com/vi/{{VIDEO-ID}}/hqdefault.jpg
 - l'ajout d'un effet de flou, de transparence ou "plus foncé" au centre pour que le CTA "Activer" reste lisible

**Comment by AmauriC** [comment]
Bonjour Vincent,

Le paramètre jsapi est supporté par tarteaucitron, il faut ajouter l'attribut `data-enablejsapi`.

Il y a un event après le chargement de Youtube par tarteaucitron:

```
document.addEventListener('youtube_loaded', function() {
    setTimeout(function() {
       […]
    }, 600);
});
```
