### ISSUE TITLE
Le service gtag se déclenche indépendamment du consentement

### ISSUE THREAD

**Issue by SW-Vincent** [AmauriC/tarteaucitron.js#1208]
Bonjour @AmauriC,

Il semblerait que le service gtag (que ce soit le service de base ou les instructions gtagMore) se déclenche indépendamment du consentement depuis peu.
Pour information : 
 - nous utilisons la version premium de tarteaucitron
 - la clé "needConsent" du service gtag a toujours TRUE pour valeur
 - les autres services semblent toujours fonctionner normalement
 - l'exécution de la fonction gtag ne déclenche pas l'événement gtag_loaded, mais si j'accepte le cookie rien de plus ne se passe alors que mon event listener gtag_loaded se déclenche

Dans la mesure où nous n'avons pas fait de changement récent dans notre code ou notre configuration, nous envisageons que cela puisse être lié à une mise à jour récente de l'outil.

Voici deux versions de l'extrait de code utilisé, qui donne le même résultat (déclenchement du console.log ET du tag GA4) : 

```
<script type="text/javascript"> 
  tarteaucitron.user.gtagUa = 'G-MY-ID'; 
  tarteaucitron.user.gtagMore = function () {
    console.log("requiert consentement")
  };
  (tarteaucitron.job = tarteaucitron.job || []).push('gtag');
</script>
```

```
<script type="text/javascript">
  tarteaucitron.user.gtagMore = function () {
    gtag('config','G-MY-ID',{
      'cookie_domain': {{domain-var}},
      'send_page_view': true
    });
    console.log("requiert consentement")
  };*/
  (tarteaucitron.job = tarteaucitron.job || []).push('gtag');
</script>
```

-------------------------

Edit : ce phénomène semble lié à l'implémentation du consent mode v2 : 

Je pense qu'il y a tout de même une question à se poser dans le sens où nous ne savons toujours pas si l'utilisation du consent mode sans consentement additionnel est conforme RGPD (en effet, des informations sont tout de même envoyées en cas de refus de consentement même dans la v2, et seul Google a statué sur la conformité du processus).

De notre côté, nous soumettons généralement les tags à consentement en addition de l'utilisation du consent mode. Pensez-vous qu'il est possible de prévoir une option de cet ordre là ?

**Comment by AmauriC** [comment]
C'est bien le consent mode depuis la v1.17 qui autorise le chargement par défaut de GA4 et Google Ads en envoyant un signal "denied" par défaut.

Pour revenir au précédent comportement (pas de consent mode, chargement quand accepté) il faut désactiver l'option "Consent Mode" depuis la console tarteaucitron.

**Comment by SW-Vincent** [comment]
J'envisage de "soumettre le consent mode à consentement".
Autrement dit, ne déclencher le tag que lorsque le consentement est donné mais à ce moment là envoyer "granted".

**Comment by AmauriC** [comment]
Possible en désactiver l'option Consent mode de tac et en ajoutant la fonction ci-dessous en utilisant l'event de chargement de GA4:

```
document.addEventListener("gtag_loaded", function() {
    window.dataLayer = window.dataLayer || [];
    window.tac_gtag = function tac_gtag() {
        dataLayer.push(arguments);
    };
    window.tac_gtag('consent', 'update', {
        analytics_storage: 'granted'
    });
});
```
