### ISSUE TITLE
question: reload et autorisation implicite - nombre de cookie déposés

### ISSUE THREAD

**Issue by jipexu** [AmauriC/tarteaucitron.js#121]
Bonjour
Tout d'abord Bô boulot !!
Je suis entrain de tester dans tous les sens pour intégration dans le CMS NPDS ...

Question :
1- Quand on reload une page et que le cookie de tarteaucitron n'existe pas encore (donc avec le bandeau d'acceptation) la page rechargée ne présente plus le bandeau (donc le cookie est écrit)...
est ce un comportement désiré (normal)  ?
cela me semble étrange ...
alors d'accord le message du bandeau est .... en poursuivant la navigation ... 
mais quand on reload une page de ce type on devrait la trouver dans son état initial ... c'est à dire sans l'écriture du cookie donc avec le bandeau d'acceptation
donc vous considérez que le reload fait partie de la poursuite de la navigation ? 

2- Dans le gestionnaire de services pour vimeo, dailymotion, youtube
le dialogue propose 3 possibilités pour le dépot des cookies en fonction de l'état

Ce service peut déposer xxx cookies.
Ce service a déposé xx cookies.
Ce service n'a déposé aucun cookie.

Quand ce(s) service est autorisé je devrai avoir :
Ce service a déposé xx cookies.
au moins pour vimeo et dailymotion ?? (car le nocookies de youtube dépose autre chose ..)
et j'obtiens toujours
Ce service n'a déposé aucun cookie. (alors qu'ils ont été déposés et visible dans ma console de dev...)

est ce un comportement normal ? ou j'ai manqué quelque chose ?

Merci pour vos lumières ...

**Comment by AmauriC** [comment]
Oui, si l'utilisateur recharge une page il navigue sur le site, que ce soit avec f5 ou un clic.

Dans quel cas un rechargement ne devrait pas valoir consentement ?

-

Les cookies ne sont pas obligatoirement déposés (il faudrait d'ailleurs prévoir des vérifications).

tarteaucitron n'a accès qu'aux cookies sur le domaine du site, pas ceux sur les domaines des contenus embarqués.

**Comment by jipexu** [comment]
Merci pour la réponse 
1_ Pour moi  le reload ne devrait pas valoir consentement quand le cookie (tarteaucitron) n'existe pas (pour une raison ou une autre) c'est à dire par exemple  lors de la toute première visite d'une page ... mais ce n'est qu'un détail...
2_ ah merci pour la confirmation .. c'est ce que je pensai ...

**Comment by jipexu** [comment]
pour le point 2
quand le service est activé et que des cookies sont susceptibles d'etre déposé hors domaine ne pourrait on pas envisager une autre alternative que cette  phrase
Ce service n'a déposé aucun cookie. (ce qui est inexact ou incomplet)
par
Ce service peut déposer xxx cookies.
