### ISSUE TITLE
cookieDomain pour tous les sous-domaines 

### ISSUE THREAD

**Issue by Vendredi3** [AmauriC/tarteaucitron.js#1211]
Bonjour,

Nous avons installé ce (très bon) script sur un site en prod, sans spécifier de cookieDomain. 
Après réflexion nous avons ajouté l'option paramétrée comme dans la doc pour partager le cookie sur le domaine et ses sous domaines : 

`"cookieDomain": ".domain.tld"`

Après livraison, les modifications de consentement ne sont plus prise en compte.

On se retrouve avec deux cookies tarteaucitron.

![image](https://github.com/AmauriC/tarteaucitron.js/assets/7081907/6861280e-9eb0-401e-9112-0762b746a305)

Après suppression des cookies, cela revient à la normale

**Comment by AmauriC** [comment]
Merci :)

Il y a un cookie avec www. et l'autre sans.

La valeur du cookieDomain doit être la même sur tous les sous domaines.

**Comment by Vendredi3** [comment]
De rien ;)

En fait le premier cookie a la valeur commençant avec un point + nom de domaine. 
Je pensais que ça allais du coup prendre en compte le domaine et ses sous domaines (www inclus). 

Pas de soucis fondamental, c'était juste pour noter que si la config initiale n'inclus pas l'option cookieDomain, et qu'on rajoute ensuite l'option, il peut y avoir un doublon de cookies qui empêche la modif des consentements jusqu'à la suppression des cookies

**Comment by AmauriC** [comment]
Une bonne pratique quand il y a un changement sur le `cookieDomain` c'est de modifier en même temps le `cookieName` pour éviter un double cookie et ce problème.

**Comment by Vendredi3** [comment]
Merci @AmauriC j'aurai dû y penser !
