### ISSUE TITLE
Charger le consentement Google au plus tôt

### ISSUE THREAD

**Issue by yannicka** [AmauriC/tarteaucitron.js#1220]
J'ai l'impression que le consentement Google (Consent Mode V2) n'est pas chargé au plus tôt.

![image](https://github.com/AmauriC/tarteaucitron.js/assets/22885898/3845ba94-cdae-45d4-804d-e77d3ed4a3dc)

J'ai des évènements de modules externes (`view_item` par exemple) qui s'exécutent avant que le consentement ne se mette.

Actuellement la page charge, des évènements `gtag` sont envoyés, le consentement par défaut est mis, puis finalement le consentement final est mis.

À cause de cela, les évènements ne remontent pas à ma connaissance.

Il faudrait que le consentement final se charge au plus tôt, de sorte à être avant les évènements `gtag`.

D'ailleurs, Google indique ceci :
https://developers.google.com/tag-platform/security/guides/consent-debugging?hl=fr#default-consent-not-set
> Ne définissez pas les états de consentement par défaut de manière asynchrone.

Aussi, comme on le voit dans la capture, j'ai ce message qui s'affiche :
https://developers.google.com/tag-platform/security/guides/consent-debugging?hl=fr#default-consent
> A tag read consent state before a default was set

Étant donné que je n'ai pas la main sur les modules installés, il faudrait que soient eux s'éxecutent après Tarte au citron, soit que Tarte au citron s'exécute avant eux (au plus tôt donc). Il me semble alors plus simple (si c'est possible) de faire évoluer seulement Tarte au citron plutôt que tous les modules externes.

Est-ce que c'est faisable ? ou ai-je des méconnaissances à ces sujets ?

**Comment by AmauriC** [comment]
tarteaucitron ne peux pas définir le consent mode plus tôt s'il est chargé après un event gtag.

Par contre il est possible de le définir plus tôt en direct (sans passer par tarteaucitron) en ajoutant avant tous les autres scripts:

```
<script>
window.dataLayer = window.dataLayer || [];
window.force_gcm = function force_gcm() {
            dataLayer.push(arguments)
};
window.force_gcm("consent", "default", {
            ad_storage: "denied",
            analytics_storage: "denied",
            ad_user_data: "denied",
            ad_personalization: "denied",
            wait_for_update: 800
});
</script>
```
