### ISSUE TITLE
Video Vimeo non reconnu par TarteauCitron dans une collapse

### ISSUE THREAD

**Issue by lisandru1208** [AmauriC/tarteaucitron.js#1221]
Bonjour, 

On a voulu effectuer une mise à jour de votre librairie, cependant on rencontre une anomalie lorsque on insère la balise <div class='vimeo_player' videoID='xxx'></div> en ajax dans une collapse. 

Une fois qu'on récupère la balise depuis php en "echo" et qu'on l'insérer sur notre page, tarteAuCitron ne transforme pas cette balise en vidéo Vimeo. 

Pourtant ça fonctionné sur la version 2021. 

Voici le code ajax : 
```
$('.aFicheAjax').on('show.bs.collapse', function () {
var that = $(this).find(".card-body");
var id_fiche = $(this).data('fiche');
	$.ajax({
		url: "ajax_fiche_docs.php",
		type: "GET",
		data: "cmd=EDITfiche&id_fiche=" + id_fiche,
		success: function (data, status) {
			var contenuHtml = JSON.parse(atob(data));
			that.html(htmlDecode(contenuHtml));
			tarteaucitron.triggerJobsAfterAjaxCall();
	}
    });
});
```
voici le résultat à la fin de la requête ajax : 

![image](https://github.com/AmauriC/tarteaucitron.js/assets/101753826/fee8e9f4-8bb4-40eb-ab09-bff17ef3f265)

![image](https://github.com/AmauriC/tarteaucitron.js/assets/101753826/e24d76f7-4fba-4dc7-a1dc-24258d5275d6)

Existe t'il une fonction qui permet de relancer une analyse de la page pour réagir sur cette balise ? 

Si vous avez une question ou une idée merci de votre retour. 

>

**Comment by lisandru1208** [comment]
MAJ : Je n'ai pas ce problème en récupérant la librairie sur github, uniquement sur la version payante.

**Comment by AmauriC** [comment]
Vous n'êtes pas en "mode auto" avec la v pro?
Possible d'avoir l'url du site pour tester?

**Comment by lisandru1208** [comment]
Oui, on était en mode auto sur la version pro. 
Par contre, on a remis la version locale sur notre site de prod, l'anomalie se produisait sur cette page : [https://docs-dev.index-education.com/docs_fr/fr-support-edt-personnel-client.php](https://docs-dev.index-education.com/docs_fr/fr-support-edt-personnel-client.php ) dans la catégorie vidéo. 
Finalement, on est resté sur la version locale, la version pro nous intéressé car la librairie ce mettait à jour automatiquement.

**Comment by lisandru1208** [comment]
Avez-vous une newsletter pour informer des mises à jour de votre librairie ?
