### ISSUE TITLE
Statistiques et première page visitée

### ISSUE THREAD

**Issue by Linkinou** [AmauriC/tarteaucitron.js#1227]
Bonjour,

Ayant l'offre PRO et donc la page des statistiques, j'avais une question à propos du taux d'activation.

Sachant qu'il y a forcément la visite d'une première page avant d'accepter ou refuser les cookies, est-ce que cette page est comptabilisée dans les stats ? Autrement dit, est-ce que les pages visitées sans avoir accepté/refusé les cookies sont comptabilisés comme des visites de pages désactivées ?

Cordialement,

**Comment by AmauriC** [comment]
Bonjour,
Un service non autorisé/non refusé est compté comme refusé.
Par contre si l'utilisateur accepte/refuse, le statut est mis à jour.
