### ISSUE TITLE
[Enhancement] Ajouter une "file" pour l'appel des services

### ISSUE THREAD

**Issue by SW-Vincent** [AmauriC/tarteaucitron.js#1228]
Tarteaucitron est aujourd'hui massivement utilisé via des gestionnaires de balises (pas forcément son intégration, mais parfois simplement l'appel des tags). Je précise que je parle du fonctionnement gestionnaire de balises en général et pas forcément Google (j'utilise beaucoup Matomo Tag Manager par exemple).

Cela pose un certain nombre de problèmes car l'appel des tags est asynchrone, et il arrive notamment que le tag soit appelé avant l'événement tarteaucitronRootAvailable. Bien sûr, ce n'est pas forcément consistant (le déclenchement se fait parfois après aussi) donc on ne peut pas conditionner nos tags à cet événement.

Le fonctionnement idéal serait d'utiliser un dataLayer pour appeler les tags plutôt qu'un objet, de cette manière l'ordre de déclenchement importerait peu.
Par exemple au lieu de : 

```
<script>
    tarteaucitron.user.gtagUa = 'G-XXXXX';
    tarteaucitron.user.gtagMore = function () {
        //Enter additionnal instructions here
    }
    (tarteaucitron.job = tarteaucitron.job || []).push('gtag');
</script>
```

On aurait quelque chose comme : 
```
<script>
    var _tacDataLayer = _tacDataLayer || []
    _tacDataLayer.push({
        "service":"gtag",
        "gtagUa":"G-XXXXX",
        "gtagMore": function () {
            //Enter additionnal instructions here
        },
    })
</script>
```

**Comment by AmauriC** [comment]
Merci, je note cette bonne idée. 

Je ferme l'issue parce que ça demande beaucoup de travail et que je n'ai vraiment pas le temps en ce moment mais c'est dans la todo list ;)
