### ISSUE TITLE
Activation fallback services par défaut

### ISSUE THREAD

**Issue by shaffe-fr** [AmauriC/tarteaucitron.js#1229]
Bonjour,

En analysant un site utilisant Tarteaucitron avec l'outil officiel d'analyse de l'Union Européenne ([https://www.edpb.europa.eu/news/news/2024/edpb-launches-website-auditing-tool_en](https://www.edpb.europa.eu/news/news/2024/edpb-launches-website-auditing-tool_en)), je me suis aperçu qu'un premier appel à Google Analytics et Google Tag Manager est fait avant même d'avoir statué sur l'acceptation du service (statut = wait).

Je trouve ce fonctionnement étonnant et contraire à la philosophie de l'opt-in.

Quelle est la motivation de ce comportement ?

Merci,
Karel

**Comment by AmauriC** [comment]
Bonjour Karel,

Possible d'avoir l'URL du site?

Surement un problème d'installation.

**Comment by AmauriC** [comment]
Merci. Le Google Consent Mode est actif sur ce site, donc la librairie Google est en effet chargée mais via le consent mode Google ne collecte/n'utilise aucune donnée avant le consentement.

**Comment by shaffe-fr** [comment]
OK.
Je vois tout de même un appel à https://region1.google-analytics.com/g/collect. 
Le Google Consent Mode étant maintenant obligatoire, il ne semble pas viable de désactiver l'option.

**Comment by AmauriC** [comment]
C'est le principe du consent mode, de pouvoir avoir des stats anonyme pour les utilisateurs qui refusent.

Dans l'appel à region1, il faut regarder le paramètre `gcd=`
Par exemple en refusant :

```
Dernier Payload
gcd | 13p3p3p2p5

Explication du code GCD
ad_storage:Refusé par défaut
analytics_storage:Refusé par défaut
ad_user_data:Refusé par défaut
ad_personalization:Refusé par défaut
```
