### ISSUE TITLE
Multilangue sur Wordpress WPML

### ISSUE THREAD

**Issue by AgenceWebSpinat** [AmauriC/tarteaucitron.js#123]
Bonjour,
Pouvez-vous me dire comment traduire le module lorsque le site n'est pas en francais.
J'arrive à le traduire sur un sur-mesure mais pas avec le module Wordpress. 
Merci d'avance

**Comment by superdaikon** [comment]
Bonjour Florent
Il me semble que les fichiers de lang js se chargent automatiquement en fonction de la langue native du navigateur. Vous pouvez les trouver dans le répertoire lang. À mon sens il est nullement nécessaire de les traduire finalement. Certes quand vous, vous faites l'essai sur votre site vous voyez sans doute toujours le français mais des visiteurs allemand, espagnols eux le verront dans leur langue.

**Comment by fadupla** [comment]
Bonjour @florent06000 
Si tu veux tester les différentes langues tu peux ajouter : 

    tarteaucitronForceLanguage = 'fr'; // la langue que tu veux parmi : en,cs,en,fr,es,it,de,pt,pl,ru 

Après le init de tarte au citron en javascript.
