### ISSUE TITLE
Paramètre enablejsapi pour l'API Youtube

### ISSUE THREAD

**Issue by SW-Vincent** [AmauriC/tarteaucitron.js#1230]
Je cherche à ajouter le paramètre enablejsapi=1 à l'URL de mes IFrames youtube pour assurer le suivi des vidéos dans Matomo. Est-ce possible ou cela demanderait il de modifier le service ?

Pour la même raison, j'aimerais exécuter la fonction permettant à Matomo d'évaluer la présence de vidéos une fois la façade convertie en IFrame (une fois l'opération terminée, sinon cela ne fonctionnera pas).

**Comment by AmauriC** [comment]
https://github.com/AmauriC/tarteaucitron.js/issues/1206
