### ISSUE TITLE
Cookie asks twice 

### ISSUE THREAD

**Issue by huyhoang8398** [AmauriC/tarteaucitron.js#1231]
Hi,

Im using tarteaucitron as cookies plugin for wordpress. 
My issue is tarteaucitron asks me two time ( first when i visit page then when i visit the page which has contact form plugin, it asks me again ).

How can I debug this

**Comment by AmauriC** [comment]
Hi

There is probably one more service on the contact page.

If this for example recaptcha, add this JS tag on each page to ask the consent on every page:

```
<script type="text/javascript">
(tarteaucitron.job = tarteaucitron.job || []).push('recaptcha');
</script>
```

**Comment by huyhoang8398** [comment]
Hi, We are using `Invisible Recaptchar` plugin base on this recommendation #873. do you know how can i find the correct string to put, i tried to use 'recaptchar' as you mentioned but it doesnt work, i suppose it need a correct name

**Comment by AmauriC** [comment]
What is the service not denied/agreed on the tarteaucitron panel when you go on the contact page?

**Comment by huyhoang8398** [comment]
i found these two 
![image](https://github.com/AmauriC/tarteaucitron.js/assets/25379882/1e361f80-cc96-4a7b-aa9e-671fdd333aa9)

**Comment by AmauriC** [comment]
Add the code below on every pages, it should fix the issue.

```
<script type="text/javascript">
(tarteaucitron.job = tarteaucitron.job || []).push('recaptcha');
(tarteaucitron.job = tarteaucitron.job || []).push('googlemapssearch');
</script>
```

**Comment by huyhoang8398** [comment]
Thanks, it works well now
