### ISSUE TITLE
Popup not showing

### ISSUE THREAD

**Issue by oprichnik** [AmauriC/tarteaucitron.js#1237]
At first load, no popup is opening, neither in Forefpx nor in Chrome. 
Except that, script is working as expected and i get the bottom icon with popup opening on click.
Any idea ?

**Comment by AmauriC** [comment]
Can you share the url?

**Comment by oprichnik** [comment]
https://www.luxoutdoor.lu/

**Comment by AmauriC** [comment]
There is just "Matomo" which is Privacy by design and allowed by default, so no need to show the banner.

**Comment by newpen** [comment]
Is there any way to still display the banner even when that cookie is allowed by default? I still want users to have a chance to disable it if they want to. Thanks!

**Comment by AmauriC** [comment]
No because when there is no choice to make, the banner is hidden.

If it was possible, the banner will be always displayed ; )
