### ISSUE TITLE
Can't remove Google Analytics cookies after validation

### ISSUE THREAD

**Issue by jlemale** [AmauriC/tarteaucitron.js#124]
So if the first time I accept Google Analytics cookies (__utma, ...b, ..c..) they are added under [Google Analytics (ga.js)] and then change my mind and deny the service. The cookie is now denied (it's red) but the cookies are not remove, they are present under my main domain instead of [Google Analytics (ga.js)] and I cannot manually remove them with tarteaucitron panel.
I need to manually do it in my browser.

What could it be ? Thank you in advance

**Comment by jlemale** [comment]
On a domain without subdomain it works, I don't know exactly why yet

**Comment by quentin-michinot** [comment]
https://github.com/AmauriC/tarteaucitron.js/issues/359
