### ISSUE TITLE
Matomo confusing option

### ISSUE THREAD

**Issue by jcerdan** [AmauriC/tarteaucitron.js#1242]
Hello,

I find this config too much confusing.

`tarteaucitron.user.matomoDontTrackPageView`

in services js file comparison is like this

`if (tarteaucitron.user.matomoDontTrackPageView !== true) {`

which is really confusing.

Wouldn't it be easier to get rid of all that negations with a 

`tarteaucitron.user.matomoTrackPageView`

option?

**Comment by AmauriC** [comment]
I agree, I really don't like double negative but the point of this option is to be able to "don't track" for a specific use but if the option is not set it should continue as before and trigger the page view.

If I change to `tarteaucitron.user.matomoTrackPageView`, all users will have to change the integration to add this option. 

I'm open to all suggestion 🙃
