### ISSUE TITLE
minor issue in tar.gz and .zip

### ISSUE THREAD

**Issue by jcerdan** [AmauriC/tarteaucitron.js#1243]
Hi,

when downloading files from github, both tar.gz or zip, you can see in tarteaucitron.js

`"version": 1.17,`

It should be 1.18

It's not a problem are files are identical but just got me confused as I thought I were using an old version.

Regards

**Comment by AmauriC** [comment]
🙈 Released too fast..

Should I tag a new 1.18.1 ?

**Comment by jcerdan** [comment]
I don't think so. Just to let people know if they met my situation and get confused. 
They'll find the issue... hopefully.

;-)

**Comment by nicozerr** [comment]
Personally, I use to check the version directly in the code among all my websites, especially when I need to update TAC.
As v1.18.0 was released last week, it's not too late to set "1.18.1" in the code, and release version 1.18.1 ;)

**Comment by AmauriC** [comment]
v1.19.0 available ;)
