### ISSUE TITLE
readmoreLink

### ISSUE THREAD

**Issue by maxime-carbonneau** [AmauriC/tarteaucitron.js#1246]
Je remarque que l'attribut readmoreLink de la config écrase le celui des services. Est-ce que c'est voulu?
J'aurais cru que ce soit l'inverse : que tarteaucitron.parameters.readmoreLink soit le défaut, mais que l'attribut dans un service soit prioritaire.

**Comment by AmauriC** [comment]
C'est bien le comportement voulu, pouvoir le modifier globalement pour tous les services.
