### ISSUE TITLE
google consent mode and "multiple*"-services

### ISSUE THREAD

**Issue by sir-gawain** [AmauriC/tarteaucitron.js#1247]
Hi there, thanks for integrating the gcm into tac!

Today i noticed, that the services "googletagmanager", "multiplegoogletagmanager" and "multiplegtag" do not include the fallback option and are not loaded in case gcm is activated. It this on purpose?

**Comment by AmauriC** [comment]
Thanks, I've added the fallback for the multiplegtag service. 

For GTM, it's better to just don't add it to tarteaucitron and directly load it.

**Comment by lucmuller** [comment]
@sir-gawain : In case you need the fix for TYPO3 the latest release of my extension is already available in the repositories !

**Comment by sir-gawain** [comment]
@AmauriC so you recommend adding the tag manager directly into the site and then use the gcm* services of TAC to ask the user for permission? I'm currenty not sure, which modules i need in which use case.

@lucmuller thanks for your work!

**Comment by AmauriC** [comment]
Yes, directly load and add the consent services. 

Search "consent mode" from https://tarteaucitron.io/en/install/
