### ISSUE TITLE
Popup ne s'affiche pas sur Firefox

### ISSUE THREAD

**Issue by DominicDesbiens** [AmauriC/tarteaucitron.js#125]
Je pensais avoir un problème avec mon installation de tarteaucitron.js, la popup n'apparaît pas sur la dernière version de Firefox. Mais il y a le même problème sur le site de la CNIL. Sur Chrome et Microsoft Edge c'est fonctionnel...

**Comment by eldk** [comment]
Bonsoir,

Pour ma part, pas de soucis avec [Firefox 60.0.1](https://www.mozilla.org/en-US/firefox/releases/), la fenêtre de réglage des paramètres apparait correctement : testé sur site de la CNIL et un autre.

Cordialement,
Eric
