### ISSUE TITLE
Add Dialog Insight

### ISSUE THREAD

**Issue by AmauriC** [AmauriC/tarteaucitron.js#1250]
## Marqueur HTML
```
<script type="text/javascript" src=https://t.ofsys.com/js/Journey/1/{{DialogInsightId}}/DI.Journey-min.js></script>
```
## Liste des cookies
?

### Site web
?
### Politique de confidentialité
?

**Comment by 13mira** [comment]
> ## Marqueur HTML
> ```
> <script type="text/javascript" src=https://t.ofsys.com/js/Journey/1/{{DialogInsightId}}/DI.Journey-min.js></script>
> ```
> 
> ## Liste des cookies
> ?
> 
> ## Права застави
> ### Веб-сайт
> ?
> 
> ### Політика конфіденційності
> ?

Браво
