### ISSUE TITLE
Url de la politique de confidentialité multilingues

### ISSUE THREAD

**Issue by onlyweb-be** [AmauriC/tarteaucitron.js#1253]
Bonjour,

Dans le cadre d'un site multilingues, comment paramétrer une URL pour le lien vers la page vie-privée qui serait différente en fonction la langue en cours ?
Actuellement il n'est possible de ne renseigner qu'une URL unique dans les options du site via l'admin tarteaucitron :)

Merci d'avance

**Comment by AmauriC** [comment]
Bonjour,

Dans l'espace "Modifier le texte" il y a une chaîne "Privacy policy url" qui sert à traduire l'url ; )

**Comment by onlyweb-be** [comment]
Bonjour,

Super merci !
Désolé je n'avais donc pas assez bien fouillé :)

Bonne journée
