### ISSUE TITLE
[Service]: Firebase.js obsolète

### ISSUE THREAD

**Issue by fred-scal** [AmauriC/tarteaucitron.js#1256]
Bonjour

Suite à un audit sécurité, j'ai une alerte mineure sur la librairie "firebase.js" qui utilise la version 8.6.2.

Dans une prochaine version, pourriez-vous mettre à jour ce service ?

Merci

**Comment by AmauriC** [comment]
Bien sûr. Quel est la version actuelle? Pas de changement sur la structure du code?

```
<script src="https://www.gstatic.com/firebasejs/8.6.2/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.6.2/firebase-analytics.js"></script>
<script>
    var firebaseConfig = {
      apiKey: "APIKEY",
      authDomain: "AUTHDOMAIN",
      databaseURL: "DATABASEURL",
      projectId: "PROJECTID",
      storageBucket: "STORAGEBUCKET",
      appId: "APPID",
      measurementId: "MEASUREMENTID",
    };
    firebase.initializeApp(firebaseConfig);
    firebase.analytics();
</script>
```

**Comment by fred-scal** [comment]
Merci pour ce retour rapide.

Je suis embêté pour te fournir la réponse.

Nous n'utilisons pas cette librairie (firebase-app.js) sur notre site. Mais l'auditeur a trouvé cette référence dans les fichiers remontés sur le poste Client.
Bien que la librairie firebase ne soit pas chargée sur le poste client, il a mentionné ce point dans son audit (en mineur).

La dernière version de la librairie semble être la version : 9.8.1 (Je ne sais pas si la configuration a évoluée depuis la 8.6.2)
Mais j'aimerais qu'un développeur utilisant cette librairie nous confirme ces points.

Désolé de ne pas avoir d'éléments plus précis.

**Comment by AmauriC** [comment]
Pas de problème, je comprend.

Je vais investiguer si pas de retour rapide d'un utilisateur ; )
