### ISSUE TITLE
Ajout des options de cross-domain pour gtag

### ISSUE THREAD

**Issue by cmoiccool** [AmauriC/tarteaucitron.js#126]
Je suis en train de tester tarte au citron et j'utilise gtag et je vois qu'il manque l'option de cross-domain pour gtag qui est configuré lors de l'appel à`gtag('config', 'UA-XXXXXXXX')` en ajoutant un paramètre `linker` comme indiqué sur la [documentation de gtag](https://developers.google.com/analytics/devguides/collection/gtagjs/cross-domain):
```
gtag('config', 'GA_TRACKING_ID', {
  'linker': {
    'domains': ['example.com']
  }
});
```
et
```
gtag('config', 'GA_TRACKING_ID', {
  'linker': {
    'accept_incoming': true
  }
});
```

Il serait bien de pouvoir ajouter une variable à configurer comme `tarteaucitron.user.gtagLinker` pour permettre la configuration du cross-domain.

**Comment by Resasol** [comment]
Bonjour à tous,

Je rencontre le meme soucis que @cmoiccool concernant le cross domain. Et c'est le meme soucis que rencontre les gens qui souhaitent anonymiser les ip (#140 #128 ...) , et plus généralement passer des paramètres à la commande config de gtag. 

D'aprés la doc tout cela se fait via le passage d'un obj paramètres à la commande config.

En plus de gtagUa et de gtagMore est-il possible d'avoir une 3ème variable gatgParams dans lequel on renseignerait l'objet paramètre par ex:
`{
     'linker': { 'domains': ['example-1.com', 'example-2.com']},
     'anonymize_ip': true,
     'autre_param': valeur_param
}`
si gtagParams est définie on ajoute l'obj parametres à la commande config.
gtag('config', tarteaucitron.user.gtagUa, tarteaucitron.user.gtagParams);

C'est ajout est-il possible, envisageable ?
