### ISSUE TITLE
Cookie count i18n

### ISSUE THREAD

**Issue by MacGyer** [AmauriC/tarteaucitron.js#1261]
Hey @AmauriC,

Traduit avec DeepL.com (version gratuite):
Tout d'abord, merci pour votre excellent travail !

Comme nous utilisons TaC en Allemagne, j'ai une petite amélioration à suggérer.
Dans https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.js#L1918 et https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.js#L1924, vous ajoutez le mot "cookie" (+ "s" si nécessaire). En allemand, les noms s'écrivent avec une majuscule, ce qui oblige à écrire "Cookie/s".

Pourriez-vous ajouter le mot "cookie" à l'objet langue et aux fichiers langues correspondants ? Ainsi, il serait possible d'écraser le mot si nécessaire ou d'utiliser le mot par défaut.

Je vous remercie.

English original:
first of all: thanks for your great work!

As we use TaC in Germany, I have a little improvement to suggest.
In https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.js#L1918 and https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.js#L1924 you are appending the word "cookie" (+"s" if needed). In German nouns are written with a capital letter which makes it necessary to write "Cookie/s".

Could you please add the word "cookie" to the language object and corresponding language files? So one can overwrite if needed or just use the default word.

Thanks.

**Comment by AmauriC** [comment]
Thanks for the feedback! I'll review this quickly.
