### ISSUE TITLE
Erreur sur la JS si pas de paramètre de locale dans la version PRO

### ISSUE THREAD

**Issue by laura14424** [AmauriC/tarteaucitron.js#1262]
Hello @AmauriC,

Sur la version Pro, en automatique, le script JS TAC est retourné en erreur si on ne précise pas de paramètre de locale. Sans locale, le fichier récupéré est `tarteaucitron..min.js`, en mettant `locale=fr` dans l'appel du script, le fichier recherché est `tarteaucitron.fr.min.js` et cela fonctionne.
Est-ce que le paramètre locale est devenu obligatoire ?

<img width="851" alt="Capture d’écran 2024-07-04 à 12 39 48" src="https://github.com/AmauriC/tarteaucitron.js/assets/109741466/8102c393-deba-425f-8e76-d749551ed15d">

**Comment by AmauriC** [comment]
Hey

Quelle est l'url du site?

Le paramètre locale n'est pas obligatoire.
