### ISSUE TITLE
Syntax Issue with GTM (multiple) service

### ISSUE THREAD

**Issue by agencewebcom** [AmauriC/tarteaucitron.js#1265]
Hello,

I don't know if I'm doing it wrong, but I wanted to use the Google Tag Manager (multiple) service. In the value field, I put: GTM-XXXX, GTM-WWWW.

However, once on the site, I get a JS error. In the JS, I have: ['GTM-XXXX, GTM-WWWW'].

But if I put in the GTM value: GTM-XXXX', 'GTM-WWWW

then it works, I no longer have a JS error and both GTMs are present.

Am I doing something wrong?

**Comment by AmauriC** [comment]
If it work, it's ok.

Can you try also this syntax:

```
['GTM-XXXX','GTM-YYYY']
```

**Comment by agencewebcom** [comment]
Yes, it does work - thank you very much
