### ISSUE TITLE
TikTok video cookies doesn't work

### ISSUE THREAD

**Issue by LucaP994** [AmauriC/tarteaucitron.js#1267]
Hi, i'm trying to add a tiktok video cookies to display tik tok's post on a website, but following the guide on your website, it doesn't works... 
I've added this:
    **<script type="text/javascript">
        (tarteaucitron.job = tarteaucitron.job || []).push('tiktokvideo');
    </script>**
but nothing is displayed and no cookies is detected, neither in the cookies list popup.
I've also added YouTube and Instagram cookies but this two work correctly.

**Comment by AmauriC** [comment]
You also have to add this part to initialize the widget:

ˋ <blockquote class="tiktok-embed" data-video-id="videoId" style="max-width: 605px;min-width: 325px;" ><section></section></blockquote>ˋ

**Comment by LucaP994** [comment]
Hi @AmauriC, yes i've also added this part but nothing is displayed

**Comment by AmauriC** [comment]
Possible to have the url?

**Comment by LucaP994** [comment]
Sure!
            <blockquote class="tiktok-embed" data-video-id="7393650231943892257" style="max-width: 605px;min-width: 325px;">
                <section></section>
            </blockquote>

**Comment by LucaP994** [comment]
Sure!
           `<blockquote class="tiktok-embed" data-video-id="7393650231943892257" style="width: 325px;">
                <section></section>
            </blockquote>`

**Comment by AmauriC** [comment]
I mean the url of the page where you have made the installation. 

I'll check what is wrong.

**Comment by LucaP994** [comment]
Right... the page for now is running in local. But i can give you more info about it.
I'm trying to add cookies in an Angular webapp using cdn:

  <script src="https://cdn.jsdelivr.net/npm/tarteaucitronjs@1.9.5/tarteaucitron.min.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tarteaucitronjs@1.9.5/tarteaucitron.css">

I've created a service like this:

import { Injectable } from '@angular/core';

declare const tarteaucitron: any;
@Injectable({
  providedIn: 'root',
})

export class TarteaucitronService {
  initTarteaucitron(): void {
    tarteaucitron.init({
      "privacyUrl": "", /* Privacy policy url */
      "bodyPosition": "bottom", 
      "hashtag": "#coockieSettings", 
      "cookieName": "noroykeysCookies", 
      "orientation": "popup", 
      "groupServices": false,
      "showDetailsOnClick": true, 
      "serviceDefaultState": "wait",
      "showAlertSmall": false,
      "cookieslist": true, 
      "showIcon": true, 
      "iconPosition": "BottomRight",
      "adblocker": false, 
      "DenyAllCta": true, 
      "AcceptAllCta": true, 
      "highPrivacy": true, 
      "alwaysNeedConsent": false, 
      "handleBrowserDNTRequest": false, 
      "removeCredit": false, 
      "moreInfoLink": true, 
      "useExternalCss": false, 
      "useExternalJs": false,/
      "mandatory": true,
      "mandatoryCta": true,
      "googleConsentMode": true,
      "partnersList": false
    });
    (tarteaucitron.job = tarteaucitron.job || []).push('youtube');
    (tarteaucitron.job = tarteaucitron.job || []).push('instagram');
    (tarteaucitron.job = tarteaucitron.job || []).push('tiktokvideo');
  }
};

and initialize the service in the app.component.ts like this:

  constructor(private tarteaucitronService: TarteaucitronService) { }
  ngOnInit(){
    this.tarteaucitronService.initTarteaucitron();
  }

and everything works fine except for tiktok... i'don't even have errors in console...
I've also tried to download the code and using it, but in this case tiktok works but not instragram

**Comment by AmauriC** [comment]
Without being able to reproduce the problem on a browser hard to help you :(

**Comment by LucaP994** [comment]
I've made a sample test on StackBliz, here's the url:
https://stackblitz.com/edit/stackblitz-starters-ve2upc?file=src%2Ftest.html

**Comment by LucaP994** [comment]
Just an update... i've upgraded to v1.19.0 and now tiktok is showing, but instagram don't do the same...
i've updated the test case at https://stackblitz.com/edit/stackblitz-starters-ve2upc?file=src%2Ftest.html

**Comment by AmauriC** [comment]
The instagram code is supposed to be similar to :

```
<iframe src="//www.instagram.com/postID/embed" width="width" height="height" frameborder="0"></iframe>
```

Are you sure of the reel/ id?

**Comment by LucaP994** [comment]
In the guide on the website the example is <div class="instagram_post" postID="postID" width="width" height="height"></div>,
and with the older versions works perfectly.
in some versions ig need te reel/ prefix, but in other don't.
By the way i've found that with v 1.17.0 both tiktok and ig works fine. Thanks
