### ISSUE TITLE
Nouveau service Skaze

### ISSUE THREAD

**Issue by AmauriC** [AmauriC/tarteaucitron.js#1268]
## Marqueur HTML
```
<script async="async"
src="//events.sk.ht/XXX/lib.js"></script>
<script>
 var skaze = skaze || {};
 skaze.cmd = skaze.cmd || [];
 skaze.cmd.push(function() {
  skaze.init({ siteIdentifier : "XXX" });
  skaze.pushEvent({
   name : "YYY",
   properties : {
    xxx: "yyy", 
} });
 });
</script>
```
## Liste des cookies
?

### Site web
https://www.skaze.com/fr/
### Politique de confidentialité
https://www.skaze.com/fr/politique/politique-de-confidentialite/

**Comment by theo-agorane** [comment]
Bonjour @AmauriC 

Je me permets de revenir vers toi suite à ma collaboration avec @paulinekali sur ce point

J'ai décelé un problème sur le tag Skaze, dont je te mets la correction ci-dessous :

Il faut remplacer
```
var skaze = skaze || {};
```
par
```
window.skaze = window.skaze || {};
```
dans `tarteaucitron.services.js` dans le service Skaze (ligne 56 actuellement)

Il y a un problème de scope sinon, l'event n'est jamais lancé correctement !

Merci encore pour ton travail,
et en espérant avoir été utile.

**Comment by AmauriC** [comment]
Bien vu, merci @theo-agorane , c'est corrigé :)
