### ISSUE TITLE
Possible de laisser la bannière si on actualise la page ?

### ISSUE THREAD

**Issue by DominicDesbiens** [AmauriC/tarteaucitron.js#127]
Par défaut, Tarte au citron enlève la bannière initiale qui s'affiche quand on arrive pour la première fois sur le site Web (celle avec les deux boutons permettant de tout accepter ou paramétrer) et la remplace par le petit bandeau en acceptant tout automatiquement si on actualise la page ou navigue vers une autre page.

Ce serait bien si on avait la possibilité de laisser la bannière toujours affichée tant que le visiteur n'a pas tout accepter ou paramétré les cookies.

Merci

**Comment by AmauriC** [comment]
L'option highPrivacy fait exactement ça ;)


Le 2 juin 2018 00:08, DominicDesbiens <notifications@github.com> a écrit :

Par défaut, Tarte au citron enlève la bannière initiale quand on arrive pour la première fois sur le site Web (celle avec les deux boutons permettant de tout accepter ou paramétrer) et la remplace par le petit bandeau en acceptant tout automatiquement si on actualise la page ou navigue vers une autre page.

Ce serait bien si on avait la possibilité de laisser la bannière toujours affichée tant que le visiteur n'a pas tout accepter ou paramétré les cookies.

Merci

**Comment by DominicDesbiens** [comment]
Vous avez raison, par contre il ne reste que le bouton de paramétrage et le bouton pour accepter tout disparaît...

**Comment by AmauriC** [comment]
Exact. Il faudrait donc une option pour désactiver tous les consentement implicite (navigation / Scroll) et ne pas changer le bandeau ?

Le 2 juin 2018 07:52, DominicDesbiens <notifications@github.com> a écrit :

Vous avez raison, par contre il ne reste que le bouton de paramétrage et le bouton pour accepter tout disparaît...

**Comment by DominicDesbiens** [comment]
C'est à peu près ça :-) Le bandeau (première notification avec les deux boutons) disparaîtrait alors seulement après avoir cliqué sur l'un ou l'autre des boutons (soit pour tout accepter, soit pour paramétrer les permissions).
