### ISSUE TITLE
Display banner when cookies are already allowed by default?

### ISSUE THREAD

**Issue by newpen** [AmauriC/tarteaucitron.js#1270]
Is there any way to still display the banner even when that cookie is allowed by default? I still want users to have a chance to disable it if they want to. Thanks!

_Originally posted by @newpen in https://github.com/AmauriC/tarteaucitron.js/issues/1237#issuecomment-2282346216_

**Comment by AmauriC** [comment]
No because when there is no choice to make, the banner is hidden.

If it was possible, the banner will be always displayed ; )

**Comment by newpen** [comment]
Thanks but the banner is still preferred cause I intend to banner also outside of the EU and they have different regulatory requirements. We would also like to inform users the use of the cookies and provide them a way to opt out even if it is allowed as default. Because of different requirements in different countries it is also preferable to have the needConsent of each of the services configurable as well. Thanks!

**Comment by AmauriC** [comment]
You can use the option `alwaysNeedConsent` to ask the consent for services auto enabled.
