### ISSUE TITLE
GTM - Vérifiez la configuration du mode Consentement

### ISSUE THREAD

**Issue by dcr31000** [AmauriC/tarteaucitron.js#1273]
Bonjour,

Après plusieurs recherche je suis un peu perdu quant à la configuration correcte de TarteAuCitron pour GTM + Google Consent Mode V2.

Voici ma configuration:

```
tarteaucitron.init({
		"privacyUrl": "/donnees-personnelles/", /* Privacy policy url */
		"bodyPosition": "bottom", /* or top to bring it as first element for accessibility */
		"cookieName": "xxxxxx", /* Cookie name */
		"orientation": "bottom", /* Banner position (top - bottom) */
		"showIcon": false, /* Show cookie icon to manage cookies */
		"DenyAllCta" : true, /* Show the deny all button */
		"AcceptAllCta" : true, /* Show the accept all button when highPrivacy on */
		"highPrivacy": true, /* HIGHLY RECOMMANDED Disable auto consent */
		"removeCredit": true, /* Remove credit link */
		"moreInfoLink": false, /* Show more info link */
		"useExternalCss": false, /* If false, the tarteaucitron.css file will be loaded */
		"useExternalJs": false, /* If false, the tarteaucitron.js file will be loaded */
		"googleConsentMode": true, /* Enable Google Consent Mode v2 for Google ads and GA4 */
	});
	
	tarteaucitron.user.gtagUa = 'G-XXXXXXXXX';
	// tarteaucitron.user.gtagCrossdomain = ['example.com', 'example2.com'];
	tarteaucitron.user.gtagMore = function () {};
	(tarteaucitron.job = tarteaucitron.job || []).push('gtag');
	
	tarteaucitron.user.googletagmanagerId = 'GTM-XXXXXXXX';
  (tarteaucitron.job = tarteaucitron.job || []).push('googletagmanager');
```

Je viens également d'ajouter ceci, sans certitude que cela soit nécéssaire:

`(tarteaucitron.job = tarteaucitron.job || []).push('gcmanalyticsstorage');`

Cependant, sur mon interface Tag Manager, j'ai l'alerte suivante:
> Vérifiez la configuration du mode Consentement, car un taux de consentement de 0 % a été détecté
> 100 % de vos signaux de consentement sont marqués comme refusés. Cela peut indiquer qu'ils ne correspondent pas aux choix des utilisateurs.

Pouvez-vous svp confirmer si **"googleConsentMode": true** permet de gérer entièrement Google Consent Mode V2 (valeurs par défaut + mise à jour lors de l'acceptation) ?
Est-ce que ma configuration est conforme malgré l'alerte de Google ?

Merci

**Comment by AmauriC** [comment]
Idéalement il faut charger GA4 / Google Ads directement via tarteaucitron, pas via GTM.

Dans votre configuration vous pouvez ajouter les services "consent mode" en fonction de ce que vous utilisez:
https://tarteaucitron.io/fr/install/

**Comment by dcr31000** [comment]
Merci @AmauriC 

Je met GTM car j'utilise réellement Tag Manager en plus d'Analytics.

Est-ce que l'ajout des services "consent mode" est obligatoire pour être conforme (et ne plus avoir l'alerte Google) ou bien théoriquement la gestion par défaut avec **"googleConsentMode": true** est suffisant ?
Aussi, comment savoir les services "consent mode" dont on a besoin ?

Merci

**Comment by AmauriC** [comment]
L'option `googleConsentMode` initialise les signaux à `denied`.

C'est ensuite géré automatiquement si tarteaucitron gère GA4/GAds. Comme ça passe par GTM, il faut ajouter les services "consent mode". 

A vous de voir ce dont vous avez besoin.

Advertising et Personalized Advertising si vous utilisez les options publicitaires. 
Analytics pour la mesure d'audience.
