### ISSUE TITLE
anonymize ip

### ISSUE THREAD

**Issue by superdaikon** [AmauriC/tarteaucitron.js#128]
Bonjour Amauric

Peut-être devrait-on ajouter aussi l'anonymisation des IP pour le tag Google. Ainsi on respecterait parfaitement l'anonymat des données même en intégrant les stats.

`
gtag('config', tarteaucitron.user.gtagUa, { 'anonymize_ip': true });
`

**Comment by gdurelle** [comment]
Déjà possible via l'appel a la fonction
https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#create
```

        tarteaucitron.addScript('//www.google-analytics.com/analytics.js', '', function () {
            ga('create', tarteaucitron.user.analyticsUa, {'cookieExpires': 34128000});
            ga('set', 'anonymizeIp', true);
            ga('send', 'pageview');
            if (typeof tarteaucitron.user.analyticsMore === 'function') {
                tarteaucitron.user.analyticsMore();
            }
        });
```

Mais en paramètre activé par défaut ce serait top respect des visiteurs oui ;)
