### ISSUE TITLE
Erreur connexion wp-admin depuis installation tarteaucitron via php

### ISSUE THREAD

**Issue by thotho2701** [AmauriC/tarteaucitron.js#131]
Bonjour,

J'ai installé la version gratuite tarteaucitron via php. Tout fonctionnait parfaitement au niveau des règlages mais depuis l'installation je ne peux plus me connecter à mon espace wp-admin, j'ai le message suivant qui apparaît : 

"Warning: Cannot modify header information - headers already sent by (output started at /homepages/25/d352020390/htdocs/wp-config.php:1) in /homepages/25/d352020390/htdocs/wp-includes/pluggable.php on line 1216"

Par contre, l'accès au site se fait sans problème.

Comment faire ?

Merci d'avance

**Comment by fadupla** [comment]
Bonjour @thotho2701 

Je pense que vous vous trompez d'endroit, vous n'êtes pas sur le dépôt du plugin WordPress de tarte au citron mais sur le dépôt du script tarteaucitron.js
Je vous invite à aller [sur la page du support du plugin WordPress](https://wordpress.org/support/plugin/tarteaucitronjs) pour avoir des réponses :)

Bonne journée,

**Comment by thotho2701** [comment]
Bonjour,

Je n'ai pas installé le plugin wordpress mais j'ai bien suivi le guide d'installation du script tarteaucitron.js (https://opt-out.ferank.eu/fr/install/)

Seulement depuis qu'il est installé, l'accès à mon site via monsite/wp-admin ne fonctionne plus et me renvoie au message indiqué.

**Comment by thotho2701** [comment]
J'ai résolu mon soucis tout seul en encodant mon wp-config en UTF-8 sans BOM avec Notepad et ça marche. J'espère que ça durera
