### ISSUE TITLE
Analytics : Code de suivi manquant

### ISSUE THREAD

**Issue by Addviso** [AmauriC/tarteaucitron.js#135]
Bonjour,

Après avoir installé le script TAC sur différents projets, le principe répond bien aux exigences RGPD, voire très bien puisque la collecte des données n'est effectuée que s'il y a consentement, donc à minima avoir scrollé la 1ère page visitée ou cliqué sur le bandeau. On peut constater une baisse de pages visitées dans les résultats de tracking (Analytics), qu'il nous faut expliquer aux clients.

Par contre, du fait que le tag n'est plus inséré mais injecté dans la page via TAC, ne convient pas à  google analytics. Nous avons des notifications avec l'alerte "Code de suivi manquant".

Je n'ai pas encore trouvé de solution à ce problème, doit-on passer une instruction complémentaire à GA pour prendre en compte ce type d'implémentation ?

Merci.

**Comment by AmauriC** [comment]
Problème déjà remonté mais sans solution a priori.

Est ce un problème bloquant ou juste un avertissement ?

Le 5 juin 2018 19:40, Addviso <notifications@github.com> a écrit :

Bonjour,

Après avoir installé le script TAC sur différents projets, le principe répond bien aux exigences RGPD, voire très bien puisque la collecte des données n'est effectuée que s'il y a consentement, donc à minima avoir scrollé la 1ère page visitée ou cliqué sur le bandeau. On peut constater une baisse de pages visitées dans les résultats de tracking (Analytics), qu'il nous faut expliquer aux clients.

Par contre, du fait que le tag n'est plus inséré mais injecté dans la page via TAC, ne convient pas à google analytics. Nous avons des notifications avec l'alerte "Code de suivi manquant".

Je n'ai pas encore trouvé de solution à ce problème, doit-on passer une instruction complémentaire à GA pour prendre en compte ce type d'implémentation ?

Merci.

**Comment by Addviso** [comment]
Actuellement le problème n'est pas bloquant, la récolte des data s'effectue. Néanmoins je n'ai pas de recul sur la durée, je ne sais pas comment GA peut se comporter si cette alerte persiste.
Je n'ai pas tous les éléments en main, mais il semblerait que ça pose également un problème quand à déclarer des sites dans la search console.

Lors de l'implémentation de la 1ère génération de bandeau cnil, nous avions déjà ce problème. Je pense que tout le monde avait contourné ça en intégrant le tag GA dans la page et récolte sans réel consentement. 

Mais si on veut être conforme, votre script est correct.

**Comment by eldk** [comment]
Bonsoir,

J'ai ce même message dans la console Google Analytics depuis 2 ou 3 mois (avec gtag.js).

En contrôlant avec : (Google Tag Assistant)[https://chrome.google.com/webstore/detail/tag-assistant-by-google/kejbdjndbnbjgmefkgdddjlbokphdefk] , vous verrez un message indiquant une implémenation non-standard.
![analytics_tac_alert](https://user-images.githubusercontent.com/11083657/41004040-cea81ab2-6918-11e8-973e-4496632ed388.png)

Ce n'est pas un soucis.

Cordialement,

Eric

**Comment by thomascz001** [comment]
Bonjour,

On est d'accord pour dire que rien a changé ou une mise à jour de tarteaucitron corrige cela ? Je n'ai pas fait de mises à jour.

Je ne sais pas si vous avez adwords sur vos sites mais si jamais vous avez adwords, vous aurez un décalage entre le nombre de click sur les ads/pubs et le nombre de sessions venant des pubs (la différence = ceux qui n'acceptent pas les cookies)

A partir de là, sur certains sites, j'ai un  message d'erreur Google analytics : 


> L'URL de destination de l'annonce https://www.monsite.fr/page du compte AdWords XXXXX a enregistré un nombre important de clics, mais un nombre de sessions correspondantes plus faible que prévu, car les balises de la page ne comportent pas de version compatible du code de suivi Google Analytics.

Vous avez la même chose ?
