### ISSUE TITLE
Default required cookie line

### ISSUE THREAD

**Issue by thomascz001** [AmauriC/tarteaucitron.js#137]
Hi,

Most websites have required cookies. They are just for technical purpose and don't use personal data.

It would be nice to be able to warn user about these cookies.  We could have a default line with "mandatory cookies/cookies obligatoires" to explain that required cookies are being used.

it would look like this: 
![capture2](https://user-images.githubusercontent.com/39958984/41028427-b26ad0d6-6979-11e8-868f-b4ece6ed6ba2.JPG)

example : "fonctionnalités cookies for nike.com"

![capture](https://user-images.githubusercontent.com/39958984/41028269-567706fa-6979-11e8-8b9c-9eb45507860b.JPG)

**Comment by AmauriC** [comment]
It's possible but I'm not sure if this is a good thing to add this on the script.

Now you can link a privacy policy page, it will be better to add these informations on that separated page.

**Comment by superallumette** [comment]
Bonjour Amauri,

Currently there are some cookies that are not covered by RGPD, like basket, sessions and so on.
I still want to inform my visitors about these cookies, distinguishing them from the other cookies.
And maybe in the future allow them to disable those.

I've already modified the code to enable this feature, using a required property on service and a required category that is always first.
I can commit the code if you want to.

Laurent

**Comment by alanmac** [comment]
This would be useful. Apart from required cookie, it would be useful to be able to use the tarteaucitron UI to explain first-party cookies that exist. At the moment the user can see a list of all cookies but has no transparency information available to them in context - e.g. explaining a shopping basket cookie. If we could add the cookie name and explanation in tarteaucitron configuration then the UI could inform the user further.

**Comment by AmauriC** [comment]
Ok, send the PR and I check it asap 👍

**Comment by superallumette** [comment]
What is the purpose of disabling it ?
Services are not required by default, so there is no change out of the box. 
And the required category I created only appears if you explicitly adds a service to it

By the way, I used google translate for language others than English and French. There might be a few horrors

**Comment by encreinformatique** [comment]
So it would be that ?
`(tarteaucitron.job = tarteaucitron.job || []).push('required');`

I took a look to the Spanish translation and made a suggestion for change.

**Comment by AmauriC** [comment]
How I see this feature :

- do not change anything out of the box
- added with an option (`mandatory_cookies = ['a', 'b'];`)

The @superallumette PR is a good start.

I will check this tomorrow if I have time.



Thanks all for your help :-)

**Comment by superallumette** [comment]
@encreinformatique You just need to change your service declaration.
"type": "required" makes your service appear in the first category.
"required": true prevents your service from being toggled (so it's a good idea to set needConsent to false)

tarteaucitron.services.customService = {
    "key": "custom",
    "type": "required",
    "name": "GetQuanty",
    "cookies": [],
    "required": true,
    "needConsent": false
};

**Comment by superallumette** [comment]
Hello,

Please do not merge the request for now.
Required services do not integrate really well with all the features at the moment (deny all, progress bar in small alert).
I am trying to fix everything that does not seem to work as I intended.

**Comment by AmauriC** [comment]
This is why I think this feature should be an option, not a new service.

With an option we can add the text and lists of cookies without hacking the script to disable consent and all related feature.

**Comment by superallumette** [comment]
It was an easy fix, but I do understand why you see it as a hack.
I still think it's convenient to reuse all of the service process and architecture for that, but you have a better global vision and it's your project so the choice is yours.

**Comment by lawebfabric** [comment]
Hi,
Did this have been added to the code ? If yes can you show an example ?
Best regards.

**Comment by odmaster7** [comment]
Hi, 
Yeah, it will be great!

**Comment by lawebfabric** [comment]
Maybe it's already inside the code ?
[SEE HERE](https://github.com/AmauriC/tarteaucitron.js/pull/262)

**Comment by SebMace** [comment]
the last commit occured on 15 Nov 2018 and superallumette told us that it wasn't OK. His pull request has been closed. So no it's not in the code

**Comment by lawebfabric** [comment]
So there is no possibility to set mandatory cookies?

**Comment by AmauriC** [comment]
No but I still dont get the point to add an extra information about technical stuff that the user will not understand.

Mandatory cookie for ecommerce, user management, ... do not require consent.

Maybe I miss something?

**Comment by SebMace** [comment]
@AmauriC  I agree with you the user won't probably understand this. But our business wants to display this information.

**Comment by Olivier-B-Smile** [comment]
@AmauriC Like SebMace, our RGPD policy ask for technical cookies to be listed, even if you can't disabled them. I tried to modify the code, but there is a lot of side effects like the tarteaucitron alert box color dots, the "Allow all cookies" or Disabled all cookies" buttons behaviour, etc ...

**Comment by AmauriC** [comment]
Hey

Just pushed a commit that add an option to show a message about mandatory cookies.
https://github.com/AmauriC/tarteaucitron.js/commit/e88aa287016cbcb2a8772c049c4cd12de2e1b812

There is a new "mandatory" option, false by default, if true a message is displayed above the services list. It's visible on https://tarteaucitron.io/

Need help for the translation ✋

Feedback welcomed 🙃

**Comment by Sylry** [comment]
Thanks for this new feature.

I think it would be great to list mandatory cookies and having the count display like other services

**Comment by AmauriC** [comment]
I close this because the main purpose is now live.

For additionnal feature about the "mandatory cookies", please open a new issue/PR ; )

**Comment by peter-bozovic** [comment]
When will this be released as new version and available on CDN ?
Changelog between versions would also be nice ;)
