### ISSUE TITLE
GDPR/RGPD - Are implicit consents with scroll  and navigation still allowed ?

### ISSUE THREAD

**Issue by eldk** [AmauriC/tarteaucitron.js#138]
Hello,

Default parameters in tarteaucitron.js allow implicits consent : scroll on page or navigation to a second page.

Is it still allowed or default should be now `highPrivacy": true,` ?

Thanks,

Eric

**Comment by lucmuller** [comment]
_"Is it still allowed"_
Yes : https://twitter.com/CNIL/status/1039875614268895232

**Comment by eldk** [comment]
merci
