### ISSUE TITLE
Installation ailleurs qu'a la racine

### ISSUE THREAD

**Issue by kaylegh** [AmauriC/tarteaucitron.js#139]
Bonjour,

J'utilise un CMS qui m'empêche d'installer /tarteaucitron/ à la racine de mon site. Je dois le mettre dans un dossier enfant.

En adaptant le chemin d'appel de tarteauctron.js, j'ai le message d'erreur suivant (firefox) : 
TypeError: tarteaucitron.job is undefined

Est-ce qu'il est possible d'utiliser ce plugin malgré tout ?

Merci d'avance.

**Comment by fadupla** [comment]
Bonjour @kaylegh ,

Est ce que tu peux copier ici ton _tarteaucitron.init_ et les services que tu as activé (toute ta configuration en gros :) ) ?

Merci

**Comment by jipexu** [comment]
je ne vois pas de problème potentiel (en gardant l'architecture de TAC) et en plaçant cette architecture ou tu veux  ... 
nous utilisons aussi un CMS et nous avons placé dans un dossier /lib/  ... pas de probleme

donc seul la modification de l'appel au script principal est nécessaire  ...

par exemple : 
`<script type="text/javascript" src="/lib/tarteaucitron/tarteaucitron.js"></script>
`

**Comment by DominicDesbiens** [comment]
Exact fonctionne très bien dans un sous dossier. Je l'ai mis dans le dossier de mon thème Wordpress. Suffit d'envoyer sur le serveur le dossier complet de tarteaucitron à l'endroit voulu et de faire appel au fichier tarteaucitron.js dans le header du site.

**Comment by jipexu** [comment]
cependant il est vrai que tant qu'aucun service n'est défini cette erreur js apparait
tarteaucitron.job is undefined

ce qui peut-etre devrait être corrigé ?

**Comment by kaylegh** [comment]
tarteaucitron.init({
        "highPrivacy": false, /* désactiver le consentement implicite (en naviguant) ? */
        "orientation": "top", /* le bandeau doit être en haut (top) ou en bas (bottom) ? */
        "adblocker": false, /* Afficher un message si un adblocker est détecté */
        "showAlertSmall": true, /* afficher le petit bandeau en bas à droite ? */
        "cookieslist": true, /* Afficher la liste des cookies installés ? */
        "removeCredit": false /* supprimer le lien vers la source ? */
    });

Google Chrome me remonte cette erreur :
Uncaught TypeError: Cannot set property 'push' of undefined
    at tarteaucitron.js:339
    at Object.addScript (tarteaucitron.js:1091)
    at tarteaucitron.js:325
    at HTMLScriptElement.script.onreadystatechange.script.onload [as onreadystatechange] (tarteaucitron.js:1109)

J'ai ajouté le service pour Google Analaytics (ga.js), même résultat.

**Comment by kaylegh** [comment]
My bad, une fois un service activé ça fonctionne correctement.

Merci à vous :)
