### ISSUE TITLE
Step 3: Add your services & Chrome 40.0.2214.91 (64-bit) / OS X 10.10.1

### ISSUE THREAD

**Issue by guix77** [AmauriC/tarteaucitron.js#14]
On https://opt-out.ferank.eu/install.php when you click on "I use this" nothing happens on Chrome 40.0.2214.91 (64-bit) (OS X 10.10.1). It works in other browsers on the same machine.

Thanks for this project BTW :)

**Comment by AmauriC** [comment]
Thanks :+1: 
 There was a default parameter in an function, I work with firefox so I had not yet seen the error.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters#Browser_compatibility

**Comment by guix77** [comment]
Thanks !
