### ISSUE TITLE
Anonymize IP Gtagmore

### ISSUE THREAD

**Issue by caseynash** [AmauriC/tarteaucitron.js#140]
Bonjour,

après avoir regardé tous les posts du forum je ne trouve pas de solution.

Dans le script il y a bien une ligne 

`tarteaucitron.user.gtagMore = function () { /* add here your optionnal gtag() */ };`

Mais aucun code gtag trouvé sur internet ne semble fonctionner ?

NI
`gtag('config', '<GA_TRACKING_ID>', { 'anonymize_ip': true });
`

NI
`gtag('config', tarteaucitron.user.gtagUa, { 'anonymize_ip': true });`

Sur un autre post Djullin a proposé
`function gtag(){dataLayer.push(arguments);} // Récupéré dans tarteaucitron.services.js
       		gtag('config', tarteaucitron.user.gtagUa, { 'anonymize_ip': true });`

Mais quand je regarde dans Chrome je me retrouve avec 2 collects analytics. Une avec le AIP=1 et une sans le AIP donc je pense qu'il doit y avoir un problème quelque part ?

Est-ce que quelqu'un a trouvé une solution ?

**Comment by gdurelle** [comment]
Duplicate https://github.com/AmauriC/tarteaucitron.js/issues/128 ?

J'ai pas vérifié de spécificité GTM mais l'appel a la fonction `ga('set', 'anonymizeIp', true);` fonctionne chez moi pour GAU.

**Comment by Djullin** [comment]
Salut ! Est-ce que vous avez pensé à désactiver l'ancien script analytics (le tracking code généré par Google Analytics) ?

**Comment by caseynash** [comment]
Bonjour,

oui j'avais bien enlevé l'ancien script que google donne.
