### ISSUE TITLE
Conditionner le dépôt des cookies

### ISSUE THREAD

**Issue by julienmiclo** [AmauriC/tarteaucitron.js#148]
Bonjour,

je viens de remarquer lors de l’utilisation du plugin qu'il y a une grosse erreur par rapport à la CNIL sur la gestion des cookies.

> Sauf consentement préalable de l'internaute, **le dépôt** et **la lecture** de Cookies ne doivent pas être effectués

sauf que dès l'arrivée sur le site le plugin créer un cookie avec les valeurs `wait` . Il ne devrait créer ce cookie seulement si l’utilisateur clique sur "Ok, tout accepter" ou Autoriser/Interdire un service. 

[Source](https://www.cnil.fr/fr/cookies-comment-mettre-mon-site-web-en-conformite)

voila

**Comment by AmauriC** [comment]
Il y a des exceptions, tarteaucitron en fait partie.

> les cookies persistants de personnalisation de l'interface utilisateur (choix de langue ou de présentation).


Le cookie en soit n'est pas le problème, c'est l'utilisation pour du tracking qui nécessite une régulation.

**Comment by amstramgram** [comment]
Ce n'est pas de la personnalisation de l'interface utilisateur. Bien-sur que si le problème est le cookie car il contient des choix que je n'ai pas fait.

**Comment by AmauriC** [comment]
Le script à besoin de savoir que l'internaute à vu une page pour décider si il faut charger ou non les services sur la suivante si il navigue, c'est de la personnalisation de l'interface.

Je ne comprends pas bien où est le problème ?

**Comment by AmauriC** [comment]
Si je ne mets pas de cookie je ne peux plus savoir que l'internaute a déjà vu une page.

Dans tous les cas, ce n'est pas soumis à autorisation. Heureusement que les éditeurs peuvent encore poser des cookies pour gérer leurs sites ;)

Tarteaucitron existe depuis plus de 2 ans et est utilisé par énormément de sites dont la CNIL, si ce n'était pas autorisé, il y aurait déjà eu des retours dans ce sens.

Toutefois, si vous avez une meilleure solution pour se souvenir qu'un utilisateur a déjà vu une page sans poser de cookie, je suis à l'écoute.

**Comment by amstramgram** [comment]
Je suis totalement d'accord sur le faite qu'il faut un cookie pour savoir ce que l'internaute à choisi comme paramètres pour le site. Ce le process qui me pose énormément de problème.

Il ne devrait pas y avoir de création de cookie avant que l'utilisateur est fait une action soit Accepter soit de Refuser.

**Comment by AmauriC** [comment]
Le paramètre highPrivacy attend un clic sur le bouton et désactive le consentement implicite.

Reste à verifier/modifier le script pour ne pas déposer de cookies dans ce cas.

**Comment by jipexu** [comment]
Oui le premier cookie de TAC ne pose vraiment pas de problème au yeux du texte de loi car ce cookie n'est pas recoupable et ne contient aucune information d'ordre privé recoupable ...Dans le texte de loi le paragraphe sur les cookies est de 5 lignes !!

>Les personnes physiques peuvent se voir associer, par les appareils, applications, outils et protocoles qu'elles utilisent, des identifiants en ligne tels que des adresses IP et des témoins de connexion («cookies») ou d'autres identifiants, par exemple des étiquettes d'identification par radiofréquence. Ces identifiants peuvent laisser des traces qui, notamment lorsqu'elles sont combinées aux identifiants uniques et à d'autres informations reçues par les serveurs, peuvent servir à créer des profils de personnes physiques et à identifier ces personnes.

donc vraiment le premier cookie de TAC pour moi ne rentre pas dans ce critère ....

??? 
dans le meme style de problématique quid des cookies envoyés par certain hébergeur 
par exemple le fameux cookie PHPNET-MNO
???

**Comment by amstramgram** [comment]
Cookies exemptés de consentement : les cookies de session d'équilibrage de charge, PHPNET-MNO en fait partie.
