### ISSUE TITLE
www.youtube-nocookie.com doesn't mean there is no cookie

### ISSUE THREAD

**Issue by eldk** [AmauriC/tarteaucitron.js#151]
Hello,

www.youtube-nocookie.com is widely use.

Some info of the meaning of nocookie that's not meaning that no cookies are used : https://support.google.com/youtube/answer/171780?hl=en 
but that the viewing and suggestion will be contextual and not behaviourial. 

So cookies are not used for behavioural purpose. But 'super' cookies (stored in LSO) are sent to user browser and identify its device. https://nakedsecurity.sophos.com/2014/11/05/how-to-clear-out-cookies-flash-cookies-and-local-storage/

Is there a way to count them as they are not stored in visited website domain but www.youtube-nocookie.com?

Thanks,
Eric

**Comment by jipexu** [comment]
i dont see how js can count this ....

**Comment by AmauriC** [comment]
Not possible. Only a browser extension (Adblocker) can manage cookie outside the main domain.

**Comment by siwa-pparzer** [comment]
do you mean like that?
https://github.com/AmauriC/tarteaucitron.js/pull/468
