### ISSUE TITLE
Flipbook

### ISSUE THREAD

**Issue by Stepomp** [AmauriC/tarteaucitron.js#152]
Bonjour,

Doit-on ajouter le service "Flipbook" pour être au norme de la RGPD ?

Si oui, comment l'ajouter ?

En vous remerciant,

Cdlt,

**Comment by fadupla** [comment]
Bonjour @Stepomp 

Qu'est ce que "Flipbook" ? Un service ? Vous avez un lien vers leur doc ou exemple de code pour l'embarquer ?

Merci,

**Comment by fadupla** [comment]
Il ne semble pas déposer de cookies.
Les favoris et marque ta page sont mis en localstorage

![image](https://user-images.githubusercontent.com/897717/41591309-a2efb4ba-73b9-11e8-9552-b5a746f58744.png)

Les seuls cookies présents sur votre exemple ce sont ceux de Google Analytics déposés par flipbook.3c-e.com. Mais dites moi si je me trompe :)

**Comment by Stepomp** [comment]
Je pense que vous avez raison, il ne semble pas déposer de cookies

Mais en fait je me pose la question en voyant les boutons de partage vers les RS, ne devrait-on pas laisser l'internaute le souhait de les afficher ou non ? Mais dans ce cas, ce doit être plutôt à l'éditeur de la solution d'effectuer la modif, car je ne pense pas avoir la main sur leur code....

Merci
