### ISSUE TITLE
Comment ajouter un service custom ?

### ISSUE THREAD

**Issue by Folder30** [AmauriC/tarteaucitron.js#154]
Bonjour, tout d'abord merci pour votre temps passé à lire ceci et pour l'aide apportée dans la résolution de mon incompréhension 😄 

J’essaie de rajouter un service perso en tant que test pour le faire proprement par la suite, j'ai vu les topics sur le sujet #146 #129  mais je n'arrive toujours pas à ajouter mon service.

Ma démarche est la suivante :

- J'ajoute un service dans tarteaucitron.services.js

```javascript
tarteaucitron.services.testing = {
    "key": "testing",
    "type": "other",
    "name": "Testing",
    "uri": "",
    "needConsent": true,
    "cookies": [],
    "js": function () {
        "use strict";
        tarteaucitron.fallback(['testing'], function (x) {


            return '<div class="testing_replaced"></div>';
        });
    },
    "fallback": function () {
        "use strict";
        var id = 'testing';
        tarteaucitron.fallback(['testing'], function (elem) {
            return tarteaucitron.engage(id);
        });
    }
};
```

- Je push mon service
```javascript
{literal}
<!-- tarteaucitron -->

<script type="text/javascript" src="{/literal}{$smarty.const.URL}{literal}js/tarteaucitron/tarteaucitron.js"></script>
<script type="text/javascript">

tarteaucitron.init({
  "hashtag": "#tarteaucitron", /* Ouverture automatique du panel avec le hashtag */
  "highPrivacy": true, /* désactiver le consentement implicite (en naviguant) ? */
  "orientation": "bottom", /* le bandeau doit être en haut (top) ou en bas (bottom) ? */
  "adblocker": false, /* Afficher un message si un adblocker est détecté */
  "showAlertSmall": true, /* afficher le petit bandeau en bas à droite ? */
  "cookieslist": false, /* Afficher la liste des cookies installés ? */
  "removeCredit": true /* supprimer le lien vers la source ? */

});
</script>
<script type="text/javascript">
tarteaucitron.user.gajsUa = '{/literal}{$smarty.const.ID_GOOGLE_ANALYTICS}{literal}';
tarteaucitron.user.gajsMore = function () { /* add here your optionnal _ga.push() */ };
(tarteaucitron.job = tarteaucitron.job || []).push('gajs');
(tarteaucitron.job = tarteaucitron.job || []).push('youtube');
(tarteaucitron.job = tarteaucitron.job || []).push('testing');
</script>
<!-- END tarteaucitron -->
```

- J'ajoute une div cible dans mon html
```html
<div class="testing">
TESTING
</div>
```

Voilà où j'en suis dans la compréhension du code, je ne comprends pas pourquoi mon service n'apparait pas dans la liste ni pourquoi je ne le vois pas passer en faisant des consol.log dans load et fallback coté tarteaucitron.js

Il me manque certainement quelque chose d’évident , je vais continuer mes recherches mais je ne dis pas non à un petit conseil utile. En vous remerciant à nouveau, merci 😄

**Comment by AmauriC** [comment]
Oui tout y est:
 - un service dans tarteaucitron.service.js
 - le chargement avec le push
 - la div qui réceptionne le contenu


Je n'ai pas testé mais ça devrait fonctionner : )

**Comment by Folder30** [comment]
Merci cette confirmation m'enlèves un grand doute, j'ai tout ce qu'il faut pour avancer dans la résolution de mon problème merci bien :)
