### ISSUE TITLE
Ajouter un engagement pour Recaptcha

### ISSUE THREAD

**Issue by lucmuller** [AmauriC/tarteaucitron.js#155]
Lors de l'utilisation du Service Recaptcha, si le service n'est pas autorisé il n'y a pas de captcha affiché.

Il faudrait ajouter un bouton permettant d'autorisé l'API car sans le captcha, l'envoie des formulaire n'est pas possible.

Si l'utilisateur n'a pas autorisé le placement du cookie, il ne peut pas soumettre le formulaire auquel recaptcha est associé.

**Comment by lucmuller** [comment]
J'ai fait une pull request allant dans ce sens => #156

**Comment by AmauriC** [comment]
Merci  👍

**Comment by lucmuller** [comment]
Pour information, nous sommes en train de préparer une implémentation dans une extension pour le CMS TYPO3.

Cette extension devrait être disponible dans quelques jours :)

Merci pour votre script :)
