### ISSUE TITLE
document.referrer & consentement implicite

### ISSUE THREAD

**Issue by ProjetCom** [AmauriC/tarteaucitron.js#157]
Bonjour,

sur notre serveur, le consentement implicite ne fonctionne pas alors que "highPrivacy": false, /* doit désactiver le consentement implicite (en naviguant) ? "

En effet en changeant de page sur le site le bandeau reste affiché sans que nous ne comprenions pourquoi.

Apres investigation il se trouve que document.referrer n’était pas positionné du fait d’une règle de sécurité sur Nginx :  **referrer-policy: no-referrer** .

En repositionnant le document.referrer la règle « highPrivacy » a fonctionné correctement.
Je pense que le code de tarteaucitron.js devrait pouvoir fonctionner sans cette contrainte.
Quelqu’un aurait-il une solution ?

 

Peut etre au niveau de :
hostname = document.location.hostname,
hostRef = document.referrer.split('/')[2],
 isNavigating = (hostRef === hostname) ? true : false,

**Comment by eldk** [comment]
Bonjour,

Pour ma part, j'ai ajouté une valeur au cookie tarteaucitron : userChoiceDone .

Elle est à false ou n'existe pas, tant que l'utilisateur n'a fait aucun choix : clic sur un bouton, scroll : [respond](https://github.com/AmauriC/tarteaucitron.js/blob/2991ba24bd3822bfac2d7faf2fa9a7fae6efe369/tarteaucitron.js#L547) ou [respondAll](https://github.com/AmauriC/tarteaucitron.js/blob/2991ba24bd3822bfac2d7faf2fa9a7fae6efe369/tarteaucitron.js#L523).

Si l'utilisateur change de page ou recharge une page, dans ce cas respond ou respondAll ne sont pas impliqués, il faut donc gérer cela après cela : https://github.com/AmauriC/tarteaucitron.js/blob/2991ba24bd3822bfac2d7faf2fa9a7fae6efe369/tarteaucitron.js#L460 : verifier si userchoiceDone est à false ou n'existe pas : si vrai : consentement implicite = passer userChoiceDone à true.

Tout cela est en test.

Cordialement,

Eric

**Comment by mfirmignac** [comment]
Bonjour
 je ne comprend pas bien la réponse
 si l'utilisateur change de page, cela vaut pour un consentement implicite et donc il faut faire un respondAll(true)
 quelqu'un a t'il une solution qui fonctionne pour identifier ce consentement implicite autrement que via le referrer ?
Merci d'avance pour votre aide
Marc

**Comment by eldk** [comment]
Bonjour,

>Donc la solution est de désactiver cette option sur le serveur ou se passer du consentement implicite.

Il est possible de se passer du referer pour détecter une navigation (avec une clef supplémentaire pour tracer cela dans le cookie tarteaucitron.js).

C'est en place et en test sur un de mes sites, mais cela demande quelques modifications de tarteaucitron.js.

Je ferai une PR dès que possible.

Cordialement,

Eric

**Comment by mfirmignac** [comment]
Bonjour,
 depuis la mise en place de tarteaucitron, quand bien même j'ai activé le consentement implicite
 Le tracking Analytics a chuté de 80%
 mon analyse est que les librairies analytics n'etant chargé qu'a partir de la seconde page
 on perd forcement le trafic sur ces pages
 mais cela n'explique pas une telle chute
 quelqu'un aurait il une idee sur ce phenomene ?
Merci d'avance
