### ISSUE TITLE
tarteaucitron.user.analyticsMore / displayFeatures

### ISSUE THREAD

**Issue by guix77** [AmauriC/tarteaucitron.js#16]
Hi again, I feel something is not clear in the Google Analytics explanations : how would you use tarteaucitron.user.analyticsMore to add displayFeatures for instance ?

Like this ?

    tarteaucitron.user.analyticsMore = function () {
      ga('require', 'displayfeatures');
    }

**Comment by devyg** [comment]
As the "More" function is called right after the "create" action, I'm pretty sure the answer is yes.

**Comment by AmauriC** [comment]
Yes, that's right.
Here is how the function is called:
```javascript
ga('create', tarteaucitron.user.analyticsUa, {'cookieExpires': 34128000});
ga('send', 'pageview');
if (typeof tarteaucitron.user.analyticsMore === 'function') {
    tarteaucitron.user.analyticsMore();
}
```

**Comment by guix77** [comment]
Merci !
