### ISSUE TITLE
Losing UTM source and medium

### ISSUE THREAD

**Issue by Ladylain** [AmauriC/tarteaucitron.js#160]
Bonjour, 

Nous avons installé le script tarteaucitron sur nos sites et nous rencontrons du coup un probleme de tracking vis a vis de Google Analytics. En effet, les visiteurs qui arrivent sur notre site sans avoir auparavant accepté les cookies, perdent leur tracking si il continue de naviguer. 

Par exemple: 
- Le client recherche sur Google le site www.mondomaine.com
- il clique sur le lien organic et est renvoyé sur le site avec un UTM_Source "Google" et un UTM_Medium "Organic"
- Il n'accepte pas les cookies via le bouton et continue de naviguer sur le site (cela active donc le consentement implicite), il perd donc le tracking. 

C'est un enorme probleme pour les trackings en terme de webmarketing car toute conversion se retrouve donc en tant que source Direct et est impossible à analyser.

Je comprend que le RGPD soit en place pour ne plus tracker les utilisateurs, mais nous devons quand meme etre capable de tracker les sources afin d'avoir des ROI pertinents. 

Auriez vous une solution a ce probleme ? 

Merci d'avance

**Comment by AmauriC** [comment]
Tracker les sources anonymement côté serveur. 

Conserver la source sans consentement serait contraire à l'esprit du script qui est d'attendre.

**Comment by Ladylain** [comment]
c'est une solution mais en naviguant sur plusieurs sites, je me rends comptes que :
- soit ils n'utilisent pas tarteaucitron et leur plugin de "cookie consent" charge google analytics
- soit ils n'utilisent pas google analytics et utilisent un autre logiciel de stats (piwik pour la cnil par exemple) 
- soit ils chargent les cookies sans permettre de refuser le consentement. 

J'avoue que la décision est très dure a prendre sur ce que l'on doit faire.

**Comment by AmauriC** [comment]
Dans tous les cas pour respecter la législation, il y a une perte sur les stats personnalisés.

Piwik ou FERank permettent de garder les référer car  n'utilise aucune donnee perso, juste des profils anonymes non utilisables sur plusieurs sites.

Des sites ne respectent pas la législation, c'est certain et même peut être un risque calculé amende vs CA mais ce n'est pas quelque chose que je souhaite aider ;-)

**Comment by Ladylain** [comment]
Merci cela me semble un peu plus limpide d'un coup. 

Je pense donc qu'il faudrait anonymiser les IP sur Google Analytic. Et donc charger automatiquement Analytics peu importe si le client a accepté les cookie ou non.

Y-a-t-il un moyen de charger analytics en version anonyme par defaut meme si celui ci est chargé via Google Tag Manager ?

**Comment by AmauriC** [comment]
Ça ne marchera pas, analytics permet de suivre un utilisateur sur plusieurs sites, c'est un critère necessitant un consentement.
