### ISSUE TITLE
Wordpress plugin maison tarteaucitron.js

### ISSUE THREAD

**Issue by Geekparade** [AmauriC/tarteaucitron.js#167]
Bonjour, je suis novice en php et en wordpress. Mon problème: j'arrive bien à intégrer les scripts TAC dans le header et les services dans les footer, mais je ne comprend pas pourquoi le pop-up de validation implicite ne s'affiche pas, malgrès que la valeur soit à true. I NEED HELP PLEASE.

**Comment by d4rk694** [comment]
Je suis actuellement occupé à développer un plugin wordpress. (avec l'accord d' @AmauriC )
Le plugin reprend l'ajout de tout ce qui est header et de l'activation des services, pour l'instant il est encore en développement, il me reste à intégrer les derniers services et ensuite le publier.
J'attends un feedback d'AmauriC pour savoir s'il y a d'autres fonctionnalités à ajouter, ou s'il y a des petites choses à changer avant de le rendre public.

**Comment by Geekparade** [comment]
ok merci beaucoup, mais cela ne répond pas trop à ma question.
cordialement

**Comment by d4rk694** [comment]
Sans code, c'est difficile de donner une réponse à ton problème...
J'ai eu le problème qui est apparu, parfois s'était une erreur d'initialisation des services, un oubli lors de l'ajout du code via le php, ...
Montre le code js que tu insères et comment tu l'insères. Ensuite, on saura répondre correctement à ta question.

**Comment by Geekparade** [comment]
Lol, pas faux mdr, mais j'ai entre temps résolus mon problème ( petit problème d'orthographe sur mon path). Merci quand même.

**Comment by d4rk694** [comment]
Si jamais, voile le plugin publié : https://fr.wordpress.org/plugins/wp-tarteaucitron-js-self-hosted/

Il n'y a pas les derniers services dans le panneau d'admin (il faut que la documentation soit mise à jour.) et que je fasse la mise à jour du plugin ensuite, mais il reprend déjà la majorité des services, et pour ceux non repris, il y a moyen de les activer via les codes à ajouter dans les sections autres.
