### ISSUE TITLE
Gulp builder

### ISSUE THREAD

**Issue by guix77** [AmauriC/tarteaucitron.js#17]
Not really an issue, but just to let you know I wrote a Gulp builder for a customized and minified TarteAuCitron : https://github.com/guix77/gulp-tarteaucitron

It fetches the latest TarteAuCitron with : 

    bower install tarteaucitron

Then you can customize the text, modify the CSS, delete the services you don't need, and finally get a minified build.

**Comment by AmauriC** [comment]
Thanks, I did not know gulp. It may be useful ;)
