### ISSUE TITLE
Chutte drastique de trafic sur analytics depuis la mise en ligne de tarteaucitron

### ISSUE THREAD

**Issue by mfirmignac** [AmauriC/tarteaucitron.js#176]
depuis la mise en place de tarteaucitron, quand bien même j'ai activé le consentement implicite
Le tracking Analytics a chuté de 80%
mon analyse est que les librairies analytics n'étant chargées qu'a partir de la seconde page
on perd forcement le trafic des premières pages
mais cela n'explique pas une telle chute
quelqu'un aurait il une idée sur ce phénomène ?
suis je le seul a qui cela est il arrivé?
une piste pour vérifier si lié à un défaut de paramétrage ?
Merci d'avance

**Comment by alphaspringer** [comment]
je veut même savou**A**re pourquoi. (souagne ton orthographe)

**Comment by AmauriC** [comment]
[https://tr.cloudmagic.com/h/v6/emailtag/tag/2.0/1532613260/227b47b4a0c6e0a013708c9e69f8b8da/2/8dcf5cfa76366e4e4b94702671f2401a/39ccef33faf4617ecab0d3f3d2c90c18/9efab2399c7c560b34de477b9aa0a465/newton.gif]

Tout dépend du taux de rebond avant la mise en place de tarteaucitron.


80% ne semble pas un problème.


Sur certains sites je frole les 100% tout en ayant des conversions.


Il y aura de toute façon une augmentation du taux de rebond, c'est mécanique :/


On Tue, Jul 24, 2018 at 12:04pm, mfirmignac <notifications@github.com<mailto:notifications@github.com>> wrote:


depuis la mise en place de tarteaucitron, quand bien même j'ai activé le consentement implicite
Le tracking Analytics a chuté de 80%
mon analyse est que les librairies analytics n'étant chargées qu'a partir de la seconde page
on perd forcement le trafic des premières pages
mais cela n'explique pas une telle chute
quelqu'un aurait il une idée sur ce phénomène ?
suis je le seul a qui cela est il arrivé?
une piste pour vérifier si lié à un défaut de paramétrage ?
Merci d'avance

**Comment by mfirmignac** [comment]
Bonjour,
 du coup, je me posais la question suivante :
- avez vous des statistiques sur le % de personne qui ne donne pas leur consentement ?
Est ce de l'ordre de 20% ou plutôt 1%

Merci de vos infos Amauri

Cordialement
