### ISSUE TITLE
Possibilité d'afficher la liste des cookies sans afficher AlertSmall

### ISSUE THREAD

**Issue by Corre35** [AmauriC/tarteaucitron.js#181]
Bonjour,
Je ne souhaite pas afficher en permanence le bloc 'AlertSmall' sur mon site, mais j'aurais aimé proposer à mes internautes d'accéder à la liste des cookies. Pourrait-on ajouter un bouton dans le panel principal pour afficher cette fenêtre?
Actuellement l'appel de la fonction tarteaucitron.userInterface.toggleCookiesList() ne fonctionne que si le paramètre AlertSmall est en true.

**Comment by AmauriC** [comment]
Laisser AlertSmall à true et masquer les boutons fonctionne:

```
button#tarteaucitronCookiesNumber, button#tarteaucitronManager {
    display: none!important;
}
div#tarteaucitronCookiesListContainer {
    top: 20%;
    left: 0;
    right: 0;
    margin: auto;
}
```

**Comment by julienmiclo** [comment]
"showAlertSmall": false,
https://opt-out.ferank.eu/fr/install/
et à l'endroit ou tu veux mettre le boutton.
`<a href="javascript:tarteaucitron.userInterface.openPanel();">Gestion des cookies</a>`
ou via une classe CSS :
`<div class="tarteaucitronOpenPanel">Gestion des cookies</div>`
