### ISSUE TITLE
Prior block of the not necessary cookies

### ISSUE THREAD

**Issue by matteoraggi** [AmauriC/tarteaucitron.js#183]
Hi, thi script is blocking not necessary cookies by default?

**Comment by d4rk694** [comment]
Hello, 
No the script do not block cookies for all the website, only for some services (see the [documentation](https://opt-out.ferank.eu/en/install/) or the [readme](https://github.com/AmauriC/tarteaucitron.js/#supported-services).
For each services you have to replace the HTML original HTML  with the one from the documentation and only then these cookies will be blocked until the user accept that we load the cookies.
