### ISSUE TITLE
précision Analytics

### ISSUE THREAD

**Issue by cyrilc24** [AmauriC/tarteaucitron.js#19]
Bonjour,
Concernant les marqueurs spécifiques de Analytics, je ne vois pas comment adapter le mien avec le votre, pouvez vous m'aider ?

Mon marqueur : (il contient un regroupement de contenu)
Merci

  ga('create', 'UA-XXX', 'auto');
  ga('set', 'contentGroup1', 'NAMEGROUP'); 
  ga('send', 'pageview');

</script>

**Comment by AmauriC** [comment]
Il y a une fonction prévue pour insérer d'autres ga() :
`tarteaucitron.user.analyticsMore = function () {
    ga('set', 'contentGroup1', 'NAMEGROUP'); 
}`

A tester, je ne connais pas le 'set'.

**Comment by cyrilc24** [comment]
Merci, cela a l’air de fonctionner !

 

 

De : Amauri CHAMPEAUX [mailto:notifications@github.com] 
Envoyé : vendredi 3 avril 2015 14:06
À : AmauriC/tarteaucitron.js
Cc : cyrilc24
Objet : Re: [tarteaucitron.js] précision Analytics (#19)

 

Il y a une fonction prévue pour insérer d'autres ga() :
tarteaucitron.user.analyticsMore = function () {
ga('set', 'contentGroup1', 'NAMEGROUP'); 
}

A tester, je ne connais pas le 'set'.
