### ISSUE TITLE
AddThis not working 

### ISSUE THREAD

**Issue by Flog71** [AmauriC/tarteaucitron.js#190]
Hi ! I'm trying to use tarteaucitron and addthis's service but nothing happened .. 

The service is here and the div for showing buttons but there is nothing on my page. 

![capture d ecran 2018-08-08 a 11 47 14](https://user-images.githubusercontent.com/14730789/43830227-1745bc74-9b01-11e8-974f-4f35d63ea525.png)

![capture d ecran 2018-08-08 a 11 46 48](https://user-images.githubusercontent.com/14730789/43830059-c2fd3228-9b00-11e8-8380-528cd4b054ef.png)

**Comment by NG76** [comment]
Up ?

**Comment by AmauriC** [comment]
Just tested and It's working fine. Addthis didn't change the code: https://www.addthis.com/dashboard#get-the-code/pub/ra-xxxxxxxx

No error on console? No adblocker?

**Comment by NG76** [comment]
My bad, i left to delete the addthis script inclusion : 
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5b916da380dc2c35"></script> 

Thanks you.
