### ISSUE TITLE
Remove all links

### ISSUE THREAD

**Issue by AmauriC** [AmauriC/tarteaucitron.js#196]
By default there is link to opt-out.ferank.eu (can by disable) and links to privacy policy.

Will be great to add an option to remove all links.

**Comment by mlfactory** [comment]
Just comment out the lines in tarteaucitron.js.....
Search for "opt-out.ferank.eu"

**Comment by AmauriC** [comment]
https://github.com/AmauriC/tarteaucitron.js/commit/6d6f7a77db3124068cc39a54d48c14f670a59ba9
