### ISSUE TITLE
tarteaucitronForceCDN is not defined

### ISSUE THREAD

**Issue by adegui** [AmauriC/tarteaucitron.js#197]
I tested the current version of tarteaucitron.js and I got an error:

![image](https://user-images.githubusercontent.com/23655927/44041315-6985ef82-9f15-11e8-8128-edde16481fb3.png)

I added a comment here for more details: https://github.com/AmauriC/tarteaucitron.js/commit/f86f6d0b0fde6bd8f60e25eb84cec9e93588049e#commitcomment-30056185

**Comment by javiertury** [comment]
I tested and it worked on firefox 61 and ESR. Thanks for this info, it seems that it doesn't work on chrome. I get a different error in the same line,  the error is:

```
Uncaught SyntaxError: Unexpected token ?
```

**Comment by javiertury** [comment]
Here is a new pull request that fixes the issue, now `tarteaucitronForceCDN` is always defined.

Forget about the above difference between Firefox and Chrome, Firefox was using stale cache in which `tarteaucitronForceCDN` was defined.

**Comment by adegui** [comment]
It works fine now, Many thanks to you.
