### ISSUE TITLE
google maps in iframe

### ISSUE THREAD

**Issue by menhir2015** [AmauriC/tarteaucitron.js#20]
Hallo thank you for your job, i really like it, i have seen one missing feature, what about web site that have google maps in Iframe??
I see that you find a good solution for vimeo and youtube, is it possible to have for google maps as well??
Thank you..

**Comment by AmauriC** [comment]
Hi!

What's the difference between the framed and the js method?
Through tarteaucitron, the result is the same, no? It's a real question ^^

**Comment by menhir2015** [comment]
sorry amauric you are right, i was confuse by the Service marker in the installation guide that refer to the js version, but looking better it is clear that is working in both ways..
sorry that i take your time!!!
thank you for your job
