### ISSUE TITLE
Loading services on entry page once a user signals their approval by continuing to navigate

### ISSUE THREAD

**Issue by alanmac** [AmauriC/tarteaucitron.js#201]
I'll set up a scenario to explain the issue:

A site that uses Google Analytics is configured using tarteaucitron. A visitor comes to the site and does not activate the third party services by scrolling past a certain point or clicking OK - they signal their acceptance by navigating to another page on the site.

The problems with this:

1) The visit metric for the first page is lost along with any referrer information because Google Analytics is only loaded by the time they get to their second page of browsing the site.
2) Referrer information is lost as when Google Analytics is loaded it will appear that the referrer is the first page that the user visited.

Per Recital 32 of the GDPR:
"...Consent should be given by a clear affirmative act establishing a freely given, specific, informed and unambiguous indication of the data subject’s agreement to the processing of personal data relating to him or her, such as ... conduct which clearly indicates in this context the data subject’s acceptance of the proposed processing of his or her personal data."

I would like to explore peoples thoughts around the idea of initialising the services (or at least those that you deem important for your purposes on first page load), once a user clicks a link to navigate (i.e. has given their consent), is it worth providing a configurable option that slightly delays the navigation to the next page to give the opportunity for some services to load and do their reporting (e.g. Google Analytics reporting the entry page visit and maintaining referrer information).

I'd like to hear opinions on whether this is feasible or a feature that people would like?

**Comment by AmauriC** [comment]
> once a user clicks a link to navigate
Doing the same thing than the "Accept all" button when the user click a link before the location change?

Will solve a lot of problem about lost referer and bounce rate 👍

Dunno if this is rgpd friendly, waiting more reply ; )

**Comment by d4rk694** [comment]
I asked about this to the CNIL.fr, but I'm waiting for an answer.

**Comment by alanmac** [comment]
Great, look forward to the feedback. Thanks.

**Comment by tdutreui** [comment]
Hi @doricci , did you get an answer from the CNIL?

**Comment by doricci** [comment]
No I don't have any answer from the CNIL..
