### ISSUE TITLE
Use tarteaucitron.js from jsdelivr cdn - Suggestion

### ISSUE THREAD

**Issue by eldk** [AmauriC/tarteaucitron.js#202]
Hello,

Just a few words to say that tarteaucitron.js is usable through jsdelivr cdn .

Maybe that should help those who are using standard Github AmauriC files.

@AmauriC : Adding some tag and doing some release may help to share it.

[![](https://data.jsdelivr.com/v1/package/gh/AmauriC/tarteaucitron.js/badge)](https://www.jsdelivr.com/package/gh/AmauriC/tarteaucitron.js)

Thanks,

Eric

**Comment by AmauriC** [comment]
Hey

v1.0 released and badge on the readme 👍

**Comment by eldk** [comment]
Merci
