### ISSUE TITLE
Conflit avec le reset CSS

### ISSUE THREAD

**Issue by obilabilon** [AmauriC/tarteaucitron.js#204]
Bonjour,

J'ai l'impression qu'il y a un soucis avec le reset CSS et la div **#tarteaucitronAlertSmall**, qui le rend transparent et en position haute (on ne voit plus que la barre verte ou rouge **#tarteaucitronDot**).

Si j'ai bien regardé c'est que dans le reset il y a un sélecteur de ce type : **#tarteaucitronRoot div**
Et il passe par dessus **#tarteaucitronAlertSmall** au niveau du poids des sélecteurs. Le background reste sur initial et se remet en transparent.

De mon coté je pense le corriger en mettant **div#tarteaucitronAlertSmall** pour rééquilibrer, mais a voir si il y a d'autres avis par ici. Ou une autre raison que je n'aurais pas vu sur ce problème.

**Comment by gueyendiora** [comment]
Ie pense réparer ce probleme

**Comment by VincentMarmiesse** [comment]
Je plussoie ce problème :)

**Comment by alanmac** [comment]
I'm experiencing this issue too. The selector specificity is overriding the background colour when it shouldn't
