### ISSUE TITLE
contentWrapper breaks CSS rules and videos

### ISSUE THREAD

**Issue by alterphp** [AmauriC/tarteaucitron.js#207]
Hi,

I've this strange behavior when integrating TarteAuCitron : my `<video>` on homepage is frozen and some CSS rules are broken...

I've finally found a culprit : `div#contentWrapper` that embeds all html of the body by TarteAuCitron... Is the only reason of that wrapper the `aria-hidden` attribute ?

**Comment by alterphp** [comment]
I changed the ID in tarteaucitron.js to check => same result.

It's clearly the fact to move every DOM node of the `<body>` that causes the problem. I don't know the problem for the `<video>` tags, but for CSS it's clear that every rules like `body > *` will fail with this wrapper.

**Comment by rubycon** [comment]
@AmauriC, wrapping all the body content implicitly is not great! It can breaks CSS selectors, such as `body > header` or `body > *` in stylesheets and JS selector query (I suppose it's the issue with `<video>`). You shouldn't assume how the user's gonna use his selectors. 

For now, a better way could be to make this accessibility feature an opt-in parameter.

Also `contentWrapper` is a pretty common id name, better to namespaced it (e.g. `tarteaucitronBodyWrapper`) or/and let the user set it as a parameter.

**Comment by EmmaNatales** [comment]
Bonjour et merci beaucoup pour tarte au citron ;-)
J'ai aussi un problème avec ce 'contentWrapper', j'ai des animations css sur une page (des blocs qui apparaissent en bougeant) et le fait de déplacer tout le contenu du body dans ce div rejoue l'animation.
J'ai viré le code du contentWrapper et plus de problème.

**Comment by AmauriC** [comment]
Ce contentWrapper pose beaucoup de problème.. je viens de la supprimer.

Si quelqu'un à un conseil pour garder un haut niveau d'accessibilité en ne cassant pas la structure du site, ne pas hésiter 👍

**Comment by alterphp** [comment]
Si j'ai bien compris, le contentWrapper servait à encapsuler tous les blocs sous la balise `<body>` pour leur ajouter l'attribut **aria-hidden**. Le container de tarteaucitron est ajouté ensuite en fin de `<body>`;

Puisqu'on ne doit pas changer la hiérarchie des éléments du DOM, je propose le fonctionnement suivant :

Affichage de tarteaucitron
* Pour chaque élément enfant de premier niveau de la balise `<body>` :
    * S'il n'a pas déjà l'attribut `aria-hidden` à true => on lui ajoute l'attribut `aria-hidden="true"` + une classe nous indiquant que l'attribut a été ajouté par TarteAuCitron (ex: `tac_original_content_hidden`)
* Afficher TarteAuCitron (comme actuellement)

Dissimuler TarteAuCitron
* Cacher les éléments TarteAuCitron
* Retirer l'attribut `aria-hidden` aux éléments de la classe `tac_original_content_hidden` ainsi que la classe elle-même.

**Comment by rubycon** [comment]
La solution proposée par @alterphp est simple et sans inconvénients. Par contre je pense qu'utiliser un data attribute au lieu d'une classe (`element.dataset['tarteaucitron-hidden'] = true;`) pour identifier les éléments modifiés serait moins invasif.

**Comment by stevenMouret** [comment]
The best way is to not use aria-hidden but a dialog role.

[Here the Dialog (modal) design pattern](https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal).
[And an example](https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html).
