### ISSUE TITLE
Récupération des variables dans tarteaucitron.init ?

### ISSUE THREAD

**Issue by bydox** [AmauriC/tarteaucitron.js#21]
Bonjour !

Pour des raisons d'organisation, j'aimerais savoir si il est possible de récupérer une variable du fichier lang et de la (re)définir dans le bloc "tarteaucitron.init" ?

Concrètement, j'aimerais définir le texte contenu dans "alertBig" depuis le code à insérer dans chaque page, pour ne pas modifier directement le fichier tarteaucitron.fr.js du dossier "lang".

Merci ;)

**Comment by AmauriC** [comment]
Bonjour! 

Pas possible pour le moment de modifier les variables de lang mais voilà un workaround :
```javascript
var tarteaucitronMessagePerso = 'Mon message';

function tarteaucitronChangerMessage(msg) {
	timer = setInterval(function() {
	    div = document.getElementById('tarteaucitronDisclaimerAlert');
		if (div !== null) {
			div.innerHTML = msg;
			clearInterval(timer);
		}
	}, 10);
}

tarteaucitronChangerMessage(tarteaucitronMessagePerso);
```

En attendant mieux, ça fonctionne ;)
