### ISSUE TITLE
Nombre de cookies affichés contenus embarqués

### ISSUE THREAD

**Issue by HugoHeneault** [AmauriC/tarteaucitron.js#217]
Hello, 

Bravo pour le gros boulot effectué et la simplicité d'utilisation. 
Je viens d'ajouter une iframe google maps via un nouveau service que je vais bientôt envoyer en PR. 

J'ai une liste de cookies potentiels : 
```
"cookies": ['apisid', 'hsid', 'nid', 'sapisid', 'sid', 'sidcc', 'ssid', '1p_jar'],
```

Qui sont bien déposés quand j'active le service : 
![image](https://user-images.githubusercontent.com/4112256/45542416-1b323f00-b812-11e8-91b0-5232bd66ab01.png)

Pourtant ils ne sont pas comptés dans les cookies Tarteaucitron : 
![image](https://user-images.githubusercontent.com/4112256/45542454-3735e080-b812-11e8-84f8-375bd017ffda.png)

J'ai lu sur https://github.com/AmauriC/tarteaucitron.js/issues/121 que les cookies de contenus embarqués ne pouvaient pas être comptés.

Je me demande du coup s'il ne vaudrait pas mieux conserver seulement "peut ajouter X cookies" au lieu d'afficher "n'a déposé aucun cookie" alors que dans mon cas plus de 7 cookies sont déposés...

Au besoin je peux faire une PR, à discuter !

Merci par avance.

**Comment by AmauriC** [comment]
Si les cookies sont sur google.com, impossible d'y avoir accès au niveau du site.

La majorité des services fonctionnent maintenant comme ça, il est peut-être temps de changer cette phrase  ; )
