### ISSUE TITLE
GTM ne dépose aucun cookie par lui-même

### ISSUE THREAD

**Issue by googleanalyticsresoneo** [AmauriC/tarteaucitron.js#22]
Bonjour

Il n'y a pas lieu à mon sens de proposer de bloquer GTM puisqu'il ne dépose aucun cookie, mais les tags qu'il contient peuvent être amené à le faire.

Il faudrait gérer l'activation des tags individuellement, voire proposer une façon de communiquer à GTM quelles familles de tag activer ou non d'après l'expression de l'utilisateur

**Comment by AmauriC** [comment]
Bonjour :)

Gérer les tags un-à-un revient à donner au tag manager de Google tout l'intérêt du tag manager tarteaucitron (la v. pro), donc bon... ^^ Je ne suis même pas sûr que ce soit possible techniquement.

GTM est très bien mais ce n'est pas la bonne solution pour gérer finement les cookies.

Si vous avez besoin d'aide/conseils pour le faire je suis dispo mais je ne le proposerai pas dans la version en prod.

**Comment by googleanalyticsresoneo** [comment]
Vous n'êtes pas de taille à lutter contre GTM, peut-être ne soupçonnez-vous pas ce que l'on peut faire avec ni comment l'intégrer avec votre version Pro. Là on peut vous aider.
C'est quoi votre version "en prod" ?
Un peu confus tout ça

**Comment by AmauriC** [comment]
La question n'est pas de savoir si je peux, ou non, lutter contre GTM, ce n'est pas le même service.

tarteaucitron répond à la problématique d'autorisation des "cookies" mais par cookies il faut comprendre toutes les technologies permettant de suivre un internaute (fingerprinting entre autres).

GTM est gratuit et il y a fort à parier que Google utilise les datas reçues via le tag, même sans service (je n'ai pas trouvé de politique de conf détaillée) donc sauf indications contraires, demander le consentement n'est pas aberrant (c'est de toute façon l'intérêt de tarteaucitron).

Je ne connais certainement pas toutes les possibilités et les services injectables via GTM mais ce que je sais c'est que je ne souhaite pas lier TAC à GTM, ni faire du cas par cas qui reviendrai à doublonner les services.

Pour répondre à votre question, je vois 2 solutions :

1. Ajouter les services manquants en me communiquant les codes JS ce qui permettra à tout le monde de les utiliser, avec ou sans GTM,
2. Charger tarteaucitron depuis GTM et modifier le code javascript des services de vos règles GTM par la version tarteaucitron. 

Ou (c'est là que je peux vous aider mais cette solution ne sera pas commitée sur la version "en prod", qui est maintenue et telechargeable ici sur github) :
1. Créer des services 'fictifs' dans tarteaucitron.services.js dont le but sera d'interagir avec GTM

Par exemple un service GTM Analytic, GTM retargeting, ... À vous ensuite de devenir, lors de l'activation, vos règles en fonction de vos besoins.
C'est du développement personnalisé.

J'espère ne pas avoir été trop confus.
Amauri.
