### ISSUE TITLE
Site très lent

### ISSUE THREAD

**Issue by e-lame** [AmauriC/tarteaucitron.js#222]
Bonjour, 

J'ai un énorme souci de lenteur avec l'utilisation de tarteaucitron et wordpress.

En utilisant le script à mettre dans le footer , j'ai 12 secondes  de plus qui se rajoute sur mon temps de chargement.

Quand avec le plugin, j'ai 32 secondes....
Y-a- t-il une config ou une manip en particulier pour raccourcir drastiquement le temps de chargement du script?

Merci!

**Comment by AmauriC** [comment]
C'est étonnant.. Possible d'avoir une page d'exemple ?

**Comment by e-lame** [comment]
Oui bien sur: 

un des sites: 
https://www.parentauquotidien.com/

Le rapport Gtmetrix: 
https://gtmetrix.com/reports/parentauquotidien.com/nG6gOnIK

Dans le Waterfall, il faut 46 secondes sur ce rapport pour que le .js se charge complètement.

Pour info: wp-rocket est installé sur ce site.  est-ce lié?

Merci !

**Comment by AmauriC** [comment]
Bonjour

En effet il y a eu un soucis, un ralentissement sur nos serveurs.

Tout semble rentré dans l'ordre, je surveille et je vais améliorer ça la semaine prochaine quand je rentre de congé.


Revenez vers moi si ça recommence.


Amauri



On Wed, Sep 19, 2018 at 9:31 PM +0200, "e-lame" <notifications@github.com<mailto:notifications@github.com>> wrote:


Oui bien sur:

un des sites:
https://www.parentauquotidien.com/

Le rapport Gtmetrix:
https://gtmetrix.com/reports/parentauquotidien.com/nG6gOnIK

Dans le Waterfall, il faut 46 secondes sur ce rapport pour que le .js se charge complètement.

Pour info: wp-rocket est installé sur ce site. est-ce lié?

Merci !
