### ISSUE TITLE
Langues 

### ISSUE THREAD

**Issue by mariacanae** [AmauriC/tarteaucitron.js#223]
J'ai installé le plugin Tarteaucitron sur mon site WP mais mon site est en anglais et le bandeau apparaît en français. Est ce que c'est possible d'avoir le bandeau en anglais et de le personnaliser (changer les couleurs)?

**Comment by doricci** [comment]
Bonjours, est ce que c'est le plugin "Self Hosted" ou bien le plugin tarteaucitron.js? 
Si c'est le plugin "Self Hosted" alors dans le menu "Initialisation" il y a moyen de changer la langue.

**Comment by mariacanae** [comment]
Bonjour, c'est le plugin tarteaucitron.js

**Comment by jipexu** [comment]
<script type="text/javascript"> var tarteaucitronForceLanguage = "xxxxxxxxxxxxx"; </script>

**Comment by romaricp** [comment]
Bonjour, 

Oui, passez la variable globale suivante : tarteaucitronForceLanguage = 'fr';
