### ISSUE TITLE
Crisp ?

### ISSUE THREAD

**Issue by olive75010** [AmauriC/tarteaucitron.js#224]
Bonjour,
Quelqu'un a-t-il intégré Crisp (support chat) svp ?
Merci,
Olivier

**Comment by cheuf** [comment]
Salut Olivier :) 
J'ai eu également le besoin, du coup je l'ai fais moi-même 👍 

`// crips
tarteaucitron.services.crips = {
    "key": "crips",
    "type": "support",
    "name": "Crips",
    "uri": "https://help.crisp.chat/en/article/whats-crisp-eu-gdpr-compliance-status-nhv54c/",
    "needConsent": true,
    "cookies": ['crisp-client%2Fsession%2F2', 'crisp-client%2Fsocket%2F2'],
    "js": function () {
        "use strict";
        window.$crisp = [];

        window.CRISP_WEBSITE_ID = tarteaucitron.user.cripsWebsiteId;

        tarteaucitron.addScript('https://client.crisp.chat/l.js');

        if (typeof tarteaucitron.user.cripsMore === 'function') {
            tarteaucitron.user.cripsMore();
        }
    }
};`

Pour la déclaration : 
`tarteaucitron.user.cripsWebsiteId = "YOUR_CRIPS_WEBSITE_ID";
            tarteaucitron.user.cripsMore = function () {
                        // Ajouter ici les $crisp.push()
            };
(tarteaucitron.job = tarteaucitron.job || []).push('crips');`

J'ai encore un problème au niveau du nombre de cookie car TaC a besoin des noms précis et Crips génère des noms dynamiquement, ex :  crisp-client%2Fsocket%2+CRISP_TOKEN_ID+OTHER_TOKEN

Je vais donc modifier le scripts de TaC pour ajouter la possibilité de cherche une correspondance dans le nom des cookies et non une exactitude (cf tarteaucitron,ligne 1091).

**Comment by cheuf** [comment]
J'ai fais une demande d'ajout : https://github.com/AmauriC/tarteaucitron.js/pull/281
