### ISSUE TITLE
No Google Maps Embed

### ISSUE THREAD

**Issue by makinero** [AmauriC/tarteaucitron.js#234]
Hello,

You have forgotten to give the ability to embed Google Maps like this:

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2624.9916256937554!2d2.292292615739922!3d48.85837007928754!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66e2964e34e2d%3A0x8ddca9ee380ef7e0!2sTour+Eiffel!5e0!3m2!1sfr!2sfr!4v1538492690794" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>

The other ways to use Google Maps need an API key by giving a credit card number...

Thank you

**Comment by Kaias26** [comment]
**Script :**
`(tarteaucitron.job = tarteaucitron.job || []).push('googlemapsembed');`

**html :** 
```
<div class="googlemapsembed"
	data-url="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2624.9916256937554!2d2.292292615739922!3d48.85837007928754!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66e2964e34e2d%3A0x8ddca9ee380ef7e0!2sTour+Eiffel!5e0!3m2!1sfr!2sfr!4v1538492690794" 
	width="600" height="450"
>
```

**Comment by Ludo-Boa** [comment]
Hello.
I have the same problem with Google Maps iframe.
My iframe is integrated by TinyMce, but when I replace my iframe with the div it doesn't show me anything. Do you have any idea where the problem may come from?

**Comment by florianbouvot** [comment]
@Kaias26 Solution works for me but can we activate this service using manager @AmauriC ?

**Comment by AmauriC** [comment]
If you add this script tag it will be displayed on tarteaucitron:

```
<script>
(tarteaucitron.job = tarteaucitron.job || []).push('googlemapsembed');
</script>
```

**Comment by florianbouvot** [comment]
I mean how to add Google Maps Embed using PRO interface?

**Comment by AmauriC** [comment]
If it's not auto detected or declared, the same way, by adding the js code.
