### ISSUE TITLE
Traductions

### ISSUE THREAD

**Issue by Zmove** [AmauriC/tarteaucitron.js#238]
Bonjour,

J'utilise le plugin tarteaucitron (version standalone, pas wordpress) sur un site multilangue. Je ne trouve pas d'explications dans la doc sur comment mettre le plugin en anglais sur la version anglaise du site.

D'avance merci

**Comment by AmauriC** [comment]
C'est un peu caché ^^

Sous _Etape 2 : initialiser le script_ il y a un lien _Options_.

```
<script type="text/javascript">
var tarteaucitronForceLanguage = 'fr'; /* supported: fr, en, de, es, it, pt, pl, ru */
</script>
```

**Comment by Zmove** [comment]
Ah oui tien, j'avais pourtant vu l'option pour le lien qui fait apparaitre le bandeau, mais pas les traductions.

Merci pour cette réponse rapide !
