### ISSUE TITLE
Add script to npm repo

### ISSUE THREAD

**Issue by evanre** [AmauriC/tarteaucitron.js#240]
Hi,
Is there any chance to see this cool script in npm repository? Here is small [tutorial](https://docs.npmjs.com/getting-started/creating-node-modules)
Or at least make it npm-compatible (add package.json etc.) to make possible download package directly from repo.

Thanks

**Comment by AmauriC** [comment]
Hey

Just published to npm, come back to me if something is missing/not working, I'm not a npm pro ; )
https://www.npmjs.com/package/tarteaucitronjs

**Comment by evanre** [comment]
Hi @AmauriC, thank you so much! You've saved me from headache while implementing this script into our environment.

**Comment by alanmac** [comment]
Great to see it on NPM thanks!

**Comment by encreinformatique** [comment]
Great to have it on npm.

@AmauriC , a first feedback:
The files are downloaded into the node_modules. (This is expected)
But you still need to copy all the files from the node_modules folder to make them available through the web. (copy to the _web/assets/js_ folder for example)

This means we cannot not minify all the files with gulp for example.
Why ? If we minify the files (with gulp for example) and create the file into _web/assets/js_ folder, the script still tries to load _tarteaucitron.services.js_ and the lang files from the folder, although they are minified as well.

**Comment by AmauriC** [comment]
@encreinformatique you know how to fix this? I'm not a npm user at all, I have justed followed the @evanre tutorial. Fell free to submit the needed changes ☺

**Comment by encreinformatique** [comment]
The PR https://github.com/AmauriC/tarteaucitron.js/pull/246/files resolves the css part.
If I have time, I will apply it for the Js part.

**Comment by ioweb-gr** [comment]
I'd really like to see this project work as a module. Can any experienced member suggest what we need to do in order to convert it so it works both ways?

**Comment by encreinformatique** [comment]
Is it possible to update the version of the [npm repo](https://www.npmjs.com/package/tarteaucitronjs)?
It seems to be an old version of the package.

Thanks

**Comment by AmauriC** [comment]
Done ✅

v1.2 https://www.npmjs.com/package/tarteaucitronjs

**Comment by vulkanosaure** [comment]
i'm looking at tarteaucitron for the first time,
it seems like a great tool, but i'm very surprise that something *this* popular doesn't work as a module,
i think most developer are expecting to do something like

npm install tarteaucitronjs 
import { tarteaucitron} from 'tarteaucitronjs'
//to stuff with the tarteaucitron object

i'm also not an export so i can't suggest a PR but it seems pretty straightforward to fill the gap,
from the link someone sent above, the specific part missing seem to be that one :

> In the file, add a function as a property of the exports object. This will machen the function available to other code:
> 
> ```
> exports.printMsg = function() {
>   console.log("This is a message from the demo package");
> }
> ```

so your tarteaucitron.js file is structured like this : 
`var tarteaucitron = { ... }`

i guess you would need to add the line
`exports.tarteaucitron = tarteaucitron;`

that way it might even be retro compatible (1 single file would handle both the classic js tag import + the node module scenario)

the file `tarteaucitron.services.js` might have to move into the same file as the main one though,
which i can imagine you probably don't like, 
i understand how publishing something as a module is trickier when you're not developing in a module environement (webpack / gulp)

anyway, those are just some clues in case you wanna give it a chance.
Cheers for the great script in any case !
