### ISSUE TITLE
Inversion des id des boutons "OK, tout accepter" et "Personnaliser"

### ISSUE THREAD

**Issue by gbourreau** [AmauriC/tarteaucitron.js#241]
Dans le bandeau :
- le bouton "OK, tout accepter" a pour id="tarteaucitronPersonalize"
- le bouton "Personnaliser" a pour id="tarteaucitronCloseAlert"

Mon petit doigt me dit que c'est l'inverse...

**Comment by FrancisKF** [comment]
J'ajouterai que d'origine le lien "Politique de confidentialité" à droite du bouton "Personnaliser" est en couleur #333 sur la couleur de fond du bandeau qui est également #333 ce qui rend invible ce lien et on ne soupçonne même pas sa présence. C'est en cherchant autre chose que j'ai découvert son existance dans la console de debug...
