### ISSUE TITLE
[Question] Can I declare a service that cannot be disabled?

### ISSUE THREAD

**Issue by ioweb-gr** [AmauriC/tarteaucitron.js#248]
Hi,

I would like to add a service definition for functional cookies that cannot / shouldn't be disabled but still notify the user that those cookies will be stored. 

For example I'm trying to add the magento 1x cookies to the list like this

```
tarteaucitron.services.magento = {
        "key": "magento",
        "type": "support",
        "name": "Magento functional cookies",
        "uri": "POLICY_URL",
        "needConsent": false,
        "cookies": ['CART','CATEGORY_INFO','COMPARE','CURRENCY','CUSTOMER','CUSTOMER_AUTH','CUSTOMER_INFO','C'EXTERNAL_NO_CACHE','FRONTEND','GUEST-VIEW','LAST_CATEGORY','LAST_PRODUCT','NEWMESSAGE','NO_CACHE','PERSISTENT_SHOPPING_CART','P''RECENTLYCOMPARED','STF','STORE','USER_ALLOWED_SAVE_COOKIE','VIEWED_PRODUCT_IDS','WISHLIST''WISHLIST_CNT',],
        "js": function () {
            "use strict";
            return true
        }
    };
```

What's the next step to make it so that user can't disable them?

**Comment by AmauriC** [comment]
What is the point of going through tarteaucitron if it is to disable its functionality?

**Comment by ioweb-gr** [comment]
Well, supposedly we have an eshop. It has to store session cookies and various other information like info for the shopping cart, filters, in some cases even current category in order to function. 

Without it all you'd get is a constant redirect to the homepage. Those cookies are absolutely vital for the proper functioning of the website. Still from what I understand to be GDPR Compliant it must be clear for the user,  even for those cookies, what they're being used for. 

So I'd like to inform them about them but there would be no point to deny them because they would then stop being able to use the website entirely.

**Comment by AmauriC** [comment]
Cookie aren't the problem. Tracking is the problem.

You dont have to do anything for functionnal cookie ✌

**Source: CNIL (fr)**

> Ainsi, par exemple, les traceurs suivants ne requièrent pas de consentement :
> 
> les cookies de " panier d'achat " pour un site marchand ;
> les cookies " identifiants de session ", pour la durée d'une session, ou les cookies persistants limités à quelques heures dans certains cas ;
> les cookies d'authentification ;

https://www.cnil.fr/fr/cookies-comment-mettre-mon-site-web-en-conformite

**Comment by ioweb-gr** [comment]
I see. Thank you very much for the explanation
