### ISSUE TITLE
Création d'un package "bower"

### ISSUE THREAD

**Issue by FredoVelcro** [AmauriC/tarteaucitron.js#25]
Ce serait encore plus simple pour l'installation non ?

**Comment by AmauriC** [comment]
Il existe `bower install tarteaucitron` ;)



On Tue, Sep 15, 2015 at 3:48 AM -0700, "Fred" <notifications@github.com<mailto:notifications@github.com>> wrote:


Ce serait encore plus simple pour l'installation non ?

-
Reply to this email directly or view it on GitHub<https://github.com/AmauriC/tarteaucitron.js/issues/25>.



--
Amauri CHAMPEAUX
https://www.ferank.fr/

**Comment by FredoVelcro** [comment]
Parfait merci ! ;)
