### ISSUE TITLE
Problème de chemin avec optimisation de code

### ISSUE THREAD

**Issue by yankiara** [AmauriC/tarteaucitron.js#253]
Hello,

Tout d'abord merci de fournir ce superbe script gratuitement :-)

Cependant, il semble y avoir un souci au chargement lorsqu'on utilise Autoptimize, et surement d'autres plugins du genre, cache ou opti.

Le problème se situe au niveau de la récupération du chemin du script au tout début du fichier :

var scripts = document.getElementsByTagName('script'),
    path = scripts[scripts.length - 1].src.split('?')[0],
    tarteaucitronForceCDN = (tarteaucitronForceCDN === undefined) ? '' : tarteaucitronForceCDN,
    cdn = (tarteaucitronForceCDN === '') ? path.split('/').slice(0, -1).join('/') + '/' : tarteaucitronForceCDN,

Avec cette méthode, on récupère un chemin de fichier en cache, et on utilise ce chemin par la suite pour charger le fichier de langue, qui est du coup introuvable car pas du tout au même endroit.

J'ai ajouté cette ligne avant les autres pour patcher et résoudre le problème en forçant l'utilisation du chemin racine, mais il faudrait donc surement revoir la méthode de chargement :

var tarteaucitronForceCDN = window.location.protocol + '//' + window.location.host + '/tarteaucitron/';

Bonne nuit !
Yan.

**Comment by AmauriC** [comment]
👋

C'est une bonne solution mais qui ne fonctionnera pas pour tout le monde (le script n'est pas forcement dans '/tarteaucitron/').

Utiliser jsdelivr comme cdn doit aussi fonctionner:
`var tarteaucitronForceCDN = "https://cdn.jsdelivr.net/gh/AmauriC/tarteaucitron.js@1.1/";`

Une meilleure gestion des différentes dépendances est en cours de développement, plus d'infos rapidement ; )

**Comment by yankiara** [comment]
Oui effectivement le CDN c'est plus propre ;-)
J'attends la suite avec impatience...

**Comment by yankiara** [comment]
Hello,
Je ne trouve pas la version 1.2 sur npm.
Est-elle dispo ailleurs pour un accès en CDN ?

**Comment by yankiara** [comment]
Ah OK en fait je ne la trouvais pas car pas le même chemin que la V1.1 :
https://cdn.jsdelivr.net/gh/AmauriC/tarteaucitron.js@1.1/

On peut appeler directement les scripts de npm ou c'est juste pour installer le package ?

**Comment by yankiara** [comment]
Une autre question... Je ne suis pas très familier avec les CDNs !

Faut-il absolument télécharger le dossier tarteaucitron/ à la racine du site et ajouter la ligne du CDN ?
Ne peut-on pas plutôt appeler directement le script sur le CDN ?

Par exemple :

```
<script type="text/javascript" src="https://cdn.jsdelivr.net/gh/AmauriC/tarteaucitron.js@V1.2/tarteaucitron.js"></script>
<script type="text/javascript">
    tarteaucitron.init({
        ...
    });
</script>
```

**Comment by AmauriC** [comment]
C'est le but. En utilisant le CDN, plus besoin d'ajouter le script sur son site.

**Comment by yankiara** [comment]
Du coup pourquoi la procédure d'installation ne décrit pas plutôt cette méthode ?

**Comment by yankiara** [comment]
Ah et une version minifiée serait top sur le CDN ;-)

**Comment by eldk** [comment]
Bonjour,

```
https://cdn.jsdelivr.net/gh/AmauriC/tarteaucitron.js@V1.2/tarteaucitron.min.js
```

Pour les différentes versions disponibles, mini ... : https://www.jsdelivr.com/package/gh/AmauriC/tarteaucitron.js?version=V1.2&tab=collection

Cordialement,

Eric

**Comment by eldk** [comment]
Bonsoir,

Il faudrait modifier tarteaucitron.js pour appeller tarteaucitron.services.min.js ... quand il est appelé depuis cdn.jsdelivr.net .

Je ne sais pas si combiner les js est possible avec un paramètre dans l'url (v=...) . 

Cordialement,

Eric

**Comment by yankiara** [comment]
Effectivement, combiner/minifier sur le CDN à partir des sources serait génial.

**Comment by yankiara** [comment]
Ou minifier tous les fichiers en gardant leur nom original (sans le .min), ce serait déjà ça.

**Comment by yaaax** [comment]
Bonjour,
J'ai le même problème, y a-t-il du nouveau ?
