### ISSUE TITLE
Auto accept on page change?

### ISSUE THREAD

**Issue by mlfactory** [AmauriC/tarteaucitron.js#256]
Hello,

ist there a way to disable the function that accept the cookies on page change?
If i reload the page, cookies not auto acceptet.
If i click a link or switch on the same website to a other site over the navigation then the cookies auto acceptet....

Many thank,
Michael

**Comment by winzou** [comment]
Hello,

Do you have any feedback on this? It seems that this is no GDPR-compliant (opt-out).

When I look at this line: https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.js#L568 it looks like it does not accept cookie on page change if you set `highPrivacy` to true. Am I right?

Thanks!

**Comment by mlfactory** [comment]
looks like it does not accept cookie on page change if you set `highPrivacy` to true. Am I right?

Yes! ;)
