### ISSUE TITLE
Dependency on npm to remove in package.json ?

### ISSUE THREAD

**Issue by betd-claumond** [AmauriC/tarteaucitron.js#258]
Hello,

In package.json file, there is a dependency on npm v6 :
```
"dependencies": {
    "npm": "^6.4.1"
  }
```

On Ubuntu 18.04 LTS Bionic, the official package for npm is in version 3.5
https://packages.ubuntu.com/bionic/npm
so tarteaucitron.js can't be installed on a standard Ubuntu Bionic

NPM is used for installing tarteaucitron.js, but I don't think it is an actual dependency for running the library.

Is it possible to remove this dependency please ? or decrease the version requirement for 3.5 ? 

Thanks and regards,
Christophe

**Comment by AmauriC** [comment]
Dependencie removed 👍

**Comment by betd-claumond** [comment]
Thanks !
