### ISSUE TITLE
Matomo/Piwik : erreur possible dans l'affichage du nombre de cookies déposés

### ISSUE THREAD

**Issue by AlphakDotNet** [AmauriC/tarteaucitron.js#259]
Bonjour et merci pour tout le travail effectué sur ce script.
Je remarque que chez moi le panneau de gestion des cookies affiche une info erronée concernant Matomo:
En effet il est systématiquement affiché "Ce service n'a déposé aucun cookie." alors que Matomo a bien déposé des cookies (normal puisque dans ce cas il est exempté de consentement).
En creusant un peu je me rends compte que les 2 cookies déposés ne s'appellent pas _pk_id et _pk_ses comme attendu, mais _pk_id.2.abf3 _pk_ses.2.abf3.
Le 2 est l'ID de site configuré dans Matomo chez moi, concernant le abf3, aucune idée de sa provenance, vraisemblablement un hash fixe. Je me rends compte ne pas être le seul dans ce cas, d'autres ont par exemple _pk_id.1.5c95 ou _pk_id.1.1d17 à la place du _pk_id traditionnel et officiellement documenté. Impossible de trouver dans la doc de Matomo comment est créé ce nom ni comment le changer, aucune trace en base, bref je bloque un peu.

Du coup je me demande s'il serait possible de patcher le script pour qu'il prenne en compte _pk_id.* et _pk_ses.* dans le décompte des cookies déposés.
Ou une alternative : que l'on puisse configurer manuellement le nom des cookies susceptibles d'être déposés par Matomo.

**Comment by AmauriC** [comment]
Hey,

Il est possible d'avoir un nom de cookie dynamique (comme ga https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.services.js#L1093) mais il faut la logique pour créer le nom du cookie, pas de joker.

Une alternative serait de désactiver les cookies mais je ne sais pas quel est l'impact sur les stats:
https://matomo.org/faq/general/faq_157/

--
Maybe @tsteur can help to dynamically find the cookies name 🧐

**Comment by AlphakDotNet** [comment]
J'ai ajouté mes cookies à ma liste :
`tarteaucitron.services.matomo = {
    "key": "matomo",
    "type": "analytic",
    "name": "Matomo (formerly known as Piwik)",
    "uri": "https://matomo.org/faq/general/faq_146/",
    "needConsent": false,
    "cookies": ['_pk_ref', '_pk_cvar', '_pk_id', '_pk_ses', '_pk_hsr', 'piwik_ignore', '_pk_uid', '_pk_id.2.abf3', '_pk_ses.2.abf3'],`

C'est crado mais au moins ça fonctionne. Idéalement j'aurais voulu ne pas toucher au script original et ajouter un truc du genre après le tarteaucitron.init : 
`tarteaucitron.services.matomo.cookies.push('_pk_id.2.abf3', '_pk_ses.2.abf3');`
Mais avec le chargement asynchrone l'objet n'est visiblement pas disponible à ce moment de l'exécution. Donc cette méthode plus propre à mes yeux ne fonctionne pas. Si quelqu'un a une idée je suis preneur :)

**Comment by AlphakDotNet** [comment]
Au final en cherchant un peu partout et en me creusant la tête, j'ai utilisé le code ci-dessous pour ajouter le nom de mes propres cookies Matomo sans toucher au script original.
On peut sûrement faire mieux, mais ça a l'air de fonctionner.
```
var waitForDomElement = function(selector, callback) {
  if (jQuery(selector).length > 0) {
    callback();
  } else {
    setTimeout(function() {
      waitForDomElement(selector, callback);
    }, 100);
  }
};
waitForDomElement('#tarteaucitronRoot', function() {
	tarteaucitron.services.matomo.cookies.push('_pk_id.2.abf3', '_pk_ses.2.abf3');
});
```

**Comment by HugoHeneault** [comment]
Trouvé ! La génération est ici : https://github.com/matomo-org/matomo/blob/1a76568aa7f85920e8f4b58e0aa2fd32f64de8ad/tests/PHPUnit/Fixtures/SomeVisitsCustomVariablesCampaignsNotHeuristics.php#L214

C'est un sha1 du domain + du path du cookie. 

Je teste une implémentation

**Comment by HugoHeneault** [comment]
Je n'ai pas réussi à obtenir le même sha1 que celui généré par Piwik.
Du coup je suis parti sur une méthode moins propre : vérifier dans la liste des cookies du domaine s'il y a des cookies custom déposés par Piwik. Si c'est le cas ils sont ajoutés au compte. 

N'hésitez pas à tester et à me dire si cela marche pour vous / s'il y aurait un autre moyen de corriger ce problème. :-)
