### ISSUE TITLE
Emplacement du bandeau

### ISSUE THREAD

**Issue by oneiros28** [AmauriC/tarteaucitron.js#264]
Après configuration dans Options de mon site sur https://opt-out.ferank.eu/pro/#manage,
"le bandeau doit être en haut (top) ou en bas (bottom) ?" est bien coché "En bas" 
pourtant il apparaît en haut.
J'ai d'autres sites, tous sont affichés en bas, en étant sélectionné "En bas", ce site là je ne comprends pas pourquoi ce n'est pas le cas.
Surtout que pour ajouter ce site j'ai fait "copier les paramètres" d'un précédent site ajouté....

Quelqu'un aurait une idée ?
Merci d'avance

**Comment by AmauriC** [comment]
Hello

Avec l'url du site ce sera plus simple ; )

Si privée > amauri@wpmobile.app
