### ISSUE TITLE
Xiti renvoie une image en http au lieu de https

### ISSUE THREAD

**Issue by ArnaudP21** [AmauriC/tarteaucitron.js#267]
Bonjour,

J'ai installé tarteaucitron sur mon site et inclus xiti mais malheureusement, cela me retire le https car l'image xiti est servie en http. J'ai remplacé tous les liens dans tarteaucitron.services.js mais rien n'y fait.

Auriez-vous une solution à ce problème svp ?

Site concerné: https://www.liberon.fr/

**Comment by AmauriC** [comment]
Hello,

If faut utiliser ATInternet, le service Xiti est l'ancienne intégration qui a été déprécié par atinternet ; )

**Comment by ArnaudP21** [comment]
Ok, je vais essayer ça merci beaucoup !

**Comment by AmauriC** [comment]
Il faut utiliser le service "at internet" avec tarteaucitron (rien à faire sur le site xiti).

**Comment by ArnaudP21** [comment]
Hello, Après de multiples essais et recherches, je n'ai, malheureusement, pas réussi à faire fonctionner ce service. J'ai bien trouvé ceci https://developers.atinternet-solutions.com/javascript-en/getting-started-javascript-en/tracker-initialisation-javascript-en/ mais aucun lien n'est fourni pour télécharger le smarttag. Saurais-tu où le trouver ? Est-ce que ce Smart tag fonctionne de la même manière que le tag manager de google ? Si oui, malheureusement, je ne vais pas pouvoir l'utiliser car j'utilise xiti pour une courte période afin de comparer les stats avec Analytics afin de s'assurer que tout soit OK.
