### ISSUE TITLE
Accessibilité navigation clavier

### ISSUE THREAD

**Issue by juliemoynat** [AmauriC/tarteaucitron.js#27]
Bonjour,

Pour des raisons d'accessibilité, notamment pour la navigation au clavier, il faudrait que les <div> qui sont utilisées comme des boutons (croix pour fermer, boutons autoriser / interdire, etc.) soient des vrais boutons (balise <button>) afin qu'ils puissent recevoir le focus.

Merci beaucoup !

**Comment by juliemoynat** [comment]
Je viens de voir que mon message contenait des balises que je n'avais pas mises comme code donc mon commentaire n'était peut-être pas clair. Cependant, fermer un ticket alors qu'il n'est pas corrigé me semble un peu curieux. On ne peut toujours pas utiliser ce plugin au clavier car les boutons "Autoriser" et "Interdire" sont des `<div>` au lieu de `<button>`.

**Comment by AmauriC** [comment]
J ai fermé les anciens tiquets sans activité pour se recentrer sur ce qui a vraiment besoin d'être amélioré. L'accessibilité en fait partie.

Mis à part les <a> a transformer en bouton, il y a autre chose ?

Merci pour votre aide.


-------- Message d'origine --------
De : Julie Moynat <notifications@github.com>
Date : 19/04/2018 15:27 (GMT+01:00)
À : "AmauriC/tarteaucitron.js" <tarteaucitron.js@noreply.github.com>
Cc : Amauri Champeaux <contact@ferank.fr>, State change <state_change@noreply.github.com>
Objet : Re: [AmauriC/tarteaucitron.js] Accessibilité navigation clavier (#27)


Je viens de voir que mon message contenait des balises que je n'avais pas mises comme code donc mon commentaire n'était peut-être pas clair. Cependant, fermer un ticket alors qu'il n'est pas corrigé me semble un peu curieux. On ne peut toujours pas utiliser ce plugin au clavier car les boutons "Autoriser" et "Interdire" sont des <div> au lieu de <button>.

**Comment by juliemoynat** [comment]
Ok, super nouvelle !

Ce sont bien les `<div>` à transformer en bouton si la version sur ce site est bien à jour : https://opt-out.ferank.eu/fr/ ;)
Et il y a aussi des `<span>` à transformer en bouton : ceux de la barre pour ouvrir la popin "OK tout accepter" et "Personnaliser".

J'ai repéré également que la popin présente un problème majeur : on peut naviguer au clavier sur ce qui est en-dessous d'elle et le focus n'est pas placé à l'intérieur de la popin quand elle s'ouvre. Il y a une notice d'AcceDeWeb en français pour expliquer comment devraient fonctionner les popins pour l'accessibilité : https://www.accede-web.com/notices/interface-riche/fenetres-modales-popins/ 
Ça devrait pas mal aider :)
La touche "ECHAP" ferme déjà la fenêtre, c'est cool !

Par ailleurs, afin de structurer le contenu de la popin, il serait préférable d'utiliser des balises de titres : 
* un h1 afin d'informer sur ce que représente cette fenêtre : exemple : "Gestion des cookies pour le site"
* les titres "Préférences pour tous les services", "Mesure d'audience", "Réseaux sociaux" et autres devraient être en h2
* les noms des services (FERank, Twitter...) devraient être en h3

Afin de mieux rattacher les boutons avec le contenu associé pour les utilisateurs de lecteurs d'écran, il est conseillé également d'organiser la liste des types de services en liste à puces (ul / li) et les services à l'intérieur également. Ce qui donnerait des listes imbriquées. Exemple : 
```
<ul>
  <li>Mesure d'audience
    <ul>
      <li>FERank (et tout le reste du contenu avec les boutons Autoriser / Interdire)</li>
      <li>Google Analytics (et tout le reste du contenu avec les boutons Autoriser / Interdire)</li>
    </ul>
  </li>
  <li>Réseaux sociaux
    <ul>
      <li>Twitter (et tout le reste du contenu avec les boutons Autoriser / Interdire)</li>
      <li>Facebook (et tout le reste du contenu avec les boutons Autoriser / Interdire)</li>
    </ul>
  </li>
</ul>
```

En espérant que ça vous aide ;)
Si vous avez des questions, n'hésitez pas.
