### ISSUE TITLE
Custom text

### ISSUE THREAD

**Issue by mheesters** [AmauriC/tarteaucitron.js#270]
We want change the text, e.g: tarteaucitron.lang.disclaimer = "hello world".
But we don't want to change the tarteaucitron.XX.js files.

Is this somehow possible? 

I saw the variabele tarteaucitronCustomText in the code, but i'm not sure how it's used.

**Comment by doricci** [comment]
Hello, I wrote this functionnality in the pull request #182, You have a sample on how to use it, but to change the  tarteaucitron.lang.disclaimer you can set the variable like this : 
```javascript
var tarteaucitronCustomText = {
     // Only a text : 
    "disclaimer ": "Hello world",
  };
  ...
  tarteaucitron.init({...});
```
The variable use the same structure than the language files so you can modify any text that you want (even the one inside other object in the language files) without changing the other string of the text file but is doesn't support multiple language...

**Comment by mheesters** [comment]
@doricci Thanks for creating it and the quick response.

Regarding multilanguage, you can always check what language the page is, and set the appropriate texts, like in this little example:

```
switch(jQuery("html").attr('lang')){
	case 'en-US': 
		var disclaimer = 'Disclaimer text English';
		var infoboxtitle = 'Title english';
		break;
	case 'de-DE': 
		var disclaimer = 'Disclaimer text German';
		var infoboxtitle = 'Guten tag';
		break;
	default: 
		var disclaimer = 'Disclaimer in het Nederlands';
		var infoboxtitle = 'Goedemiddag';
}

var tarteaucitronCustomText = {
  "title": infoboxtitle,
  "disclaimer": disclaimer,
};
```
