### ISSUE TITLE
Google Maps : google is not defined

### ISSUE THREAD

**Issue by dcucchietti** [AmauriC/tarteaucitron.js#271]
Bonjour,

J'ai remplacé le code suivant : 
`<script type="text/javascript" async defer src="https://maps.googleapis.com/maps/api/js?key=${googleMapAPIKey}"></script>`

par 
`<script type="text/javascript">
        tarteaucitron.user.googlemapsKey = '$google_map_api_key';
        (tarteaucitron.job = tarteaucitron.job || []).push('googlemaps');
    </script>
`

comme c'est indiqué dans la doc mais maintenant je me retrouve avec une erreur : 
`Uncaught ReferenceError: google is not defined`

Pour information je n'affiche pas de carte, j'utilise Google map pour calculer le nom d'une ville en fonction du code postal renseigné : 
`function geocodeCity(object, addressTypeKey) {
   ....
    var geocoder = new google.maps.Geocoder();
    geocoder.geocode(request, function (result, status) {
    ....
   });
})
`

Avez-vous une solution ? Ou dans la mesure où je n'affiche pas de carte il n'y a pas besoin de passer par le plugin tarteaucitron pour respecter la RGPD ?

D'avance merci pour vos retours

**Comment by ju260** [comment]
hello,
du coup ca serait le service google map search api a mettre en place

**Comment by dcucchietti** [comment]
Bonjour @ju260 ,
Merci pour ton retour, je vais faire le test.
