### ISSUE TITLE
GTM don't remove _gid

### ISSUE THREAD

**Issue by SBaudrant** [AmauriC/tarteaucitron.js#272]
Hello !

I have a problem using GTM on my site. I have add the script to set google tag manager service. When i allow this service, it creates _gid and _gat_UA_XXXXXX_X cookie which are not removed when i disallow GTM service. The _gat cookie remove itself aftre 1minute, but _gid after 1 day. I want to remove it when the user disallow the service.

Is it normal ? How can i solved that ?

Thanks !

**Comment by quentin-michinot** [comment]
https://github.com/AmauriC/tarteaucitron.js/issues/359

Same for me :/ Hotjar + _gid
