### ISSUE TITLE
Service Youtube DoubleClick ?

### ISSUE THREAD

**Issue by Eric3005** [AmauriC/tarteaucitron.js#279]
Bonjour,
J'ai installé le script sur un WordPress (mais en manuel) selon les indications données mais je n'arrive pas à retrouver le même fonctionnement pour les vidéos Youtube que sur le site de la CNIL.
J'ai pourtant activé le service Youtube mais il ne trouve aucun cookie alors que youtube.com et doubleclick.com en déposent toute une série.
Une petite aide serait appréciée :)
Pour info l'url du site est atari.com
Merci par avance !
Eric

**Comment by AmauriC** [comment]
Belle intégration 👍 

Il faut différencier les cookies sur le site et les cookies tiers qui reste sur youtube.com.

Les cookies tiers ne sont pas lisible par le site et le script tarteaucitron, c'est pour ça qu'il ne sont pas dans la liste.

**Comment by Eric3005** [comment]
Merci :)
Oui j'imaginais bien un truc dans le genre.
Donc la CNIL a utilisé un autre script en complément pour gérer les vidéos YT intégrées en iFrame ?

**Comment by AmauriC** [comment]
Oui ils ont fait quelques ajustements sur plusieurs points, ça doit venir de là ; )
