### ISSUE TITLE
Cannot read property 'title' of undefined

### ISSUE THREAD

**Issue by Dizay93** [AmauriC/tarteaucitron.js#282]

**Comment by pttsky** [comment]
I had the same error in console. 

For me the cause of the problem was `useExternalJs`.
```
tarteaucitron.init({
  "useExternalJs": true
})
```

When I set it to `false`, the error gone.

**Comment by AmauriC** [comment]
When you use `useExternalJs` you have to load the services.js and lang.js files by yourself.

If you dont load these files, you'll get this error.
