### ISSUE TITLE
Acceptation sur action de l'utilisateur

### ISSUE THREAD

**Issue by oTiMo** [AmauriC/tarteaucitron.js#29]
Pouvez vous ajouter une fonction permettant d'accepter les cookies sur une action de l'utilisateur ?

**Comment by oTiMo** [comment]
On peut le faire grace à "tarteaucitron.userInterface.respondAll(true)", mais il faut préalablement détecter "à la main" si ce n'est pas déjà le cas.

**Comment by BPagoaga** [comment]
Je profite de cette issue ouverte :
L'acceptation sur action de l'utilisateur fonctionne bien pour les cookies de mesure d'audience et de régie publicitaire, en revanche pour les APIs google tag manager et jsapi, l'acceptation ne se fait pas.
