### ISSUE TITLE
Bandeau ne s'affiche pas

### ISSUE THREAD

**Issue by FannyM971** [AmauriC/tarteaucitron.js#291]
Hello,
J'ai un souci le bandeau ne s'affiche pas... J'ai bien "Gestion des services" mais pas le bandeau ...
.tarteaucitronAlertBigBottom est avec un display; none.
Un conflit js ou un mauvais paramètrage ? 

`<script type="text/javascript">
	tarteaucitron.init({
		"privacyUrl": "/50-politique-de-confidentialite", /* Privacy policy url */
		"hashtag": "#tarteaucitron", /* Open the panel with this hashtag */
		"cookieName": "tartaucitron", /* Cookie name */
		"orientation": "bottom", /* Banner position (top - bottom) */
		"showAlertSmall": false, /* Show the small banner on bottom right */
		"cookieslist": false, /* Show the cookie list */
		"adblocker": false, /* Show a Warning if an adblocker is detected */
		"AcceptAllCta" : true, /* Show the accept all button when highPrivacy on */
		"highPrivacy": true, /* Disable auto consent */
		"handleBrowserDNTRequest": false, /* If Do Not Track == 1, disallow all */
		"removeCredit": true, /* Remove credit link */
		"moreInfoLink": true, /* Show more info link */
		"useExternalCss": false, /* If false, the tarteaucitron.css file will be loaded */
		"readmoreLink": "/50-politique-de-confidentialite" /* Change the default readmore link pointing to opt-out.ferank.eu */
	});
	</script>`

**Comment by AmauriC** [comment]
Hello

C'est le comportement quand tout est accepté.
Même chose en navigation privée ?

Il y a des services chargé?

**Comment by FannyM971** [comment]
C'était pareil en navigation privée...
Mais du coup, j'ai tout réintégré et ça fonctionne.
J'ai dû foirer quelque part.
Merci :D !

**Comment by Avelornes** [comment]
Je relance parce que j'ai le même soucis de bandeau qui ne s'affiche pas, pareil en navigation privée. J'ai refait la réinstall et toujours pareil. C'est pas la première fois que je l'intègre et je n'ai jamais eu le soucis avant. J'ai aucune erreur en console et les services intégrés répondent bien.

**Comment by mirabellette** [comment]
J'ai le même soucis que Averlornes. J'ai testé avec la 1.2 et la dernière version du master, même comportement.

Fait étonnant, 
Si j'ai le paramètre "showAlertSmall": true, la css pour alertBig reste sur display:none et un element alertSmall est généré et bien affiché.

Si j'ai le paramètre "showAlertSmall": false, la css pour alertBig reste sur display:none et l'élément alertSmall n'apparaît pas.

**Comment by AmauriC** [comment]
Si handleBrowserDNTRequest est à true (comme c'est le cas sur le privatebin), le bandeau ne s'affiche pas et les services sont désactivés par default si le navigateur envoi une entête DNT. C'est probablement la cause du problème 😉

**Comment by mirabellette** [comment]
Effectivement, c'était bien ça. Une fois que je set handleBrowserDNTRequest à false, le bandeau s'affiche bien.

Il y a quand même une incohérence car si handleBrowserDNTRequest et showAlertSmall est à true, la bannière s'affiche alors que le comportement devrait être le même que celui de la bannière grosse.

Un petit peu d'explication à côté de handleBrowserDNTRequest serait la bienvenue :) Après, comme tu vends un service premium, j'imagine que c'est pas forcément ton intérêt de tout simplifier.

Dans tous les cas, merci pour ton aide :)

**Comment by AmauriC** [comment]
Le petit bandeau sert à afficher la totalité des cookies et à revenir sur le panneau de gestion, il est affiché en permanence, sauf si je rate quelque chose, c'est le comportement voulu.

La version payante est la même que celle sur Github, j'ai tout intérêt à simplifier les choses pour tout le monde 😉
