### ISSUE TITLE
Version amp ?

### ISSUE THREAD

**Issue by Bendjii** [AmauriC/tarteaucitron.js#296]
Bonjour,

Existe-il une version amp de tarteaucitron.js ou une façon permettant de l'intégrer sur une déclinaison AMP d'un site web ?

Merci d'avance.

**Comment by Bendjii** [comment]
???

**Comment by gregdu23** [comment]
Très intéressé par le sujet. Sinon impossible d’intégrer tarteaucitron sur pages AMP. Et Ça implique d’avoir un autre module d’acceptation des cookies sur pages AMP...

**Comment by Abitbolz** [comment]
Le fait de ne pas tenir compte des contraintes AMP est la seule chose qui me retiens d'utiliser tarteaucitron sur mon projet actuellement

**Comment by e-lame** [comment]
Intéressée également par une déclinaison amp ! Est-ce prévu? Merci !!
