### ISSUE TITLE
Liens sortants en follow

### ISSUE THREAD

**Issue by eldk** [AmauriC/tarteaucitron.js#30]
Bonjour,

Certains liens sortants vers opt-out.ferank ... et vers les sites officiels ne sont pas en "nofollow" :

`<a href="https://opt-out.ferank.eu/service/xiti/" target="_blank">           En savoir plus       </a>`

Cordialement,

Eric

**Comment by eldk** [comment]
https://github.com/eldk/tarteaucitron.js/commit/830b06eb255ffe9db0b0ff91a930a9fc404b75c3

**Comment by semantiqueweb** [comment]
Bonjour
Le nofollow est inutile je crois pour ce cas car de toute façon les liens sont montés en javascript et donc non suivis par les moteurs de recherche.
https://www.natural-net.fr

**Comment by AmauriC** [comment]
Je n'ai pas vraiment d'avis, si quelqu'un veut trancher, je validerai le pull request ;)

**Comment by coliff** [comment]
I suggest to add `rel="noopener"` instead. It's potentially safer and faster - and is recommended by Google for links which open with `target="_blank"`

REF:
https://developers.google.com/web/tools/lighthouse/audits/noopener
https://jakearchibald.com/2016/performance-benefits-of-rel-noopener/
https://mathiasbynens.github.io/rel-noopener/
