### ISSUE TITLE
AddThis qui ne s'affiche pas

### ISSUE THREAD

**Issue by yebou** [AmauriC/tarteaucitron.js#305]
Bonjour,

Je viens de prendre le compte pro d'essai. Impossible de faire fonctionné AddThis.
Il me génère bien la div mais rien ne s'y ajoute.
J'ai bien retiré tout ce qui appel AddThis.

https://pastebin.com/nBEsB0F7

**Comment by yebou** [comment]
Bonjour,

Voici le code que fournis addthis : https://pastebin.com/7gdgbk2N

Merci d'avance pour votre aide.

**Comment by ezjoke** [comment]
Bonjour,

J'ai le même souci avec la version manuelle.

Si j'ai bien compris le fonctionnement de tarteaucitron, la fonction 'tarteaucitron.fallback' utilisée dans le service permet de remplacer le contenu de la/les classes(s) du premier paramètre, par le deuxième paramètre. Ici rien en l'occurence donc pas de souci. Par contre, la fonction 'tarteaucitron.addScript' est appelée ensuite, et, si j'ai bien compris, elle ajoute le script dans le head de la page html. Hors, il me semble que le script addthis_widget.js doit être inséré à l'endroit même où doit apparaître le widget.

Corrigez-moi si je me trompe, et merci pour vos retours.

**Comment by ezjoke** [comment]
Après un peu de recherche, j'ai réussi à faire fonctionner le service. Il s'avère qu'il faut en fait remplacer seulement l'appel du script par `<div class="addthis_sharing_toolbox"></div>` et non tout le code concernant addthis.
La documentation n'est peut-être pas forcément claire sur ce point :-/
