### ISSUE TITLE
Par défaut, Google Analytics (gtag.js) est installé

### ISSUE THREAD

**Issue by NRV75003** [AmauriC/tarteaucitron.js#310]

**Comment by NRV75003** [comment]
Bonjour et merci pour ce simplissime et génial appli ! 
Je suis sur WP, avec Divibuilder, j'ai installé tarte au citron et choisi le service Google Analytics (gtag.js). Lorsqu'un internaute vient pour la première fois sur mon site, le cookie Google Analytics (gtag.js) est malgré tout installé, il doit de selectionenr interdire via la boite de dialogue.
Je souhaiterais, conformément au RGPD, qu'aucun cookie ne s'installe AVANT l'accord de l'internaute

Merci beaucoup pour votre aide !

**Comment by NRV75003** [comment]
No news ?

**Comment by drobert8584** [comment]
une solution ici : https://github.com/AmauriC/tarteaucitron.js/issues/334
