### ISSUE TITLE
Twitter Timelines (Timeline not fully covered)

### ISSUE THREAD

**Issue by Tutolex** [AmauriC/tarteaucitron.js#315]
Hi and first thanks for this awesome project.

I have a problem using twitter timeline service.
When I decide to not accept cookies from twitter, something appears above the timeline asking if I want to accept cookies. What is weird is that it doesn't cover the whole timeline, as you can see on the picture below. 
![image](https://user-images.githubusercontent.com/48880317/54878530-8e0a1b80-4e2e-11e9-857b-0ac57cf21a02.png)
I would have expected the same behavior as the youtube service that covers the whole video. Is this normal behavior or is there a problem ?

Thanks

**Comment by AmauriC** [comment]
Hi

If you get the timeline + the banner, you probably still have on your website the twitter tag.

When you use tarteaucitron, you have to remove your previous integration of the twitter script.

With the website url I will be able to quickly confirm ; )

**Comment by Tutolex** [comment]
Thanks for your answer. 

Here is my url : https://gemme-france-mediation.fr

It is a wordpress website and Iam using a lot of plugins including jetpack, that I previously used to generate the timeline. But since I installed tarteaucitron, I removed the Jetpack Timeline Widget and replaced it with the tarteaucitron code using elementor page builder.

Thanks in advance.

**Comment by Tutolex** [comment]
Any idea ?

**Comment by Tutolex** [comment]
Well after it totally stopped working I went back to it and tried to change my code. It finally worked but I must say I have no idea why here are the two bits of code : (inspired from thread https://github.com/AmauriC/tarteaucitron.js/issues/98)

The one that didn't work : 
```
  <span class="tacTwitterTimelines"></span>
  <a class="twitter-timeline"
    data-lang="fr"
    data-height="255"
    data-dnt="true"
    data-theme="light"
    data-show-replies="false"
    data-chrome="noheader nofooter noborders transparent"
    href="https://twitter.com/GEMME_EUROPE">
  </a>
```

The one that worked : 
```
 <span class="tacTwitterTimelines"></span>
  <a class="twitter-timeline"
    data-lang="fr"
    data-height="255"
    data-dnt="true"
    data-theme="light"
    data-show-replies="false"
    data-chrome="noheader nofooter noborders transparent"
    href="https://twitter.com/GEMME_EUROPE?ref_src=twsrc%5Etfw">
    Tweets by GEMME_EUROPE
  </a>
```
