### ISSUE TITLE
dataLayer.push sur Google Tag Manager ne fonctionne plus avec TAC

### ISSUE THREAD

**Issue by EnTeteDuNet** [AmauriC/tarteaucitron.js#316]
Bonjour et merci pour le script :)

Lorsque je remplace le script de Google Tag Manager par celui de TAC, le code suivant ne fonctionnent plus :
<script>dataLayer.push({'BookingValue': 'value'});</script>

J'utilise le code suivant : 
tarteaucitron.user.googletagmanagerId='GTM-xxxxxxx';(tarteaucitron.job=tarteaucitron.job||[]).push('googletagmanager');

Aucun souci avec le script original de GTM. J'essaie de résoudre ce souci depuis un moment maintenant, mais je ne trouve pas de solution. Alors pour le moment je suis contraint d'implémenter la métohde GTM..

Les deux scripts génèrent bien les scripts : 
<script type="text/javascript" async="" src="https://www.google-analytics.com/analytics.js"></script>
<script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-xxxxxxx"></script>
Et j'ai comparé la réponse dans les deux cas du second script, c'est bien la même...

Si quelqu'un a une piste, je suis preneur merci !

**Comment by Adysone** [comment]
Bonjour,

J'ai le même problème...

Pourquoi ça ne fonctionne pas ? C'est simple, le script de GTM est appelé après le chargement de la page, donc après les instructions `dataLayer.push( ... )`. `dataLayer` n'existe donc pas encore.

Il est possible de "bricoler" en mettant les instructions dans un `setTimeout()` pour laisser au script le temps de se charger, mais bien entendu, selon les vitesses de connexion, ça pourrait ne pas passer.

Je suis activement en train de rechercher un événement indiquant que GTM est chargé (quelque chose qui pourrait ressembler à `GTM.ready( ... )` mais en vain pour le moment.

J'ai donc la piste, mais pas la bonne solution pour l'instant !

**Comment by drobert8584** [comment]
J'ai eu le même problème, vois #334 et https://github.com/AmauriC/tarteaucitron.js/pull/361
