### ISSUE TITLE
Utiliser un lien pour faire apparaitre le panel

### ISSUE THREAD

**Issue by le61berthier** [AmauriC/tarteaucitron.js#319]
Bonjour,

J'ai déjà lu l'issue #59 où il est indiqué qu'on peut utiliser par exemple <a href="https://www.monsite.fr/mapage_cookie/" class="tarteaucitronOpenPanel">Cookies</a> pour lancer le panel à partir d'un lien.
Cependant il ne se passe rien chez moi. Je ne dois pas savoir utiliser correctement le sélecteur "tarteaucitronOpenPanel".

J'utilise ce script JS min : https://cdn.jsdelivr.net/gh/AmauriC/tarteaucitron.js@V1.2/tarteaucitron.min.js?ver=5.1.1

Cldt,
Romain

**Comment by b1nj** [comment]
Bonjour,
Il faut utiliser un lien comme cela :
`  <a href="#tarteaucitron">Lien</a> `

Le hastag peut se modifier dans la configuration :

`    "hashtag": "#tarteaucitron", /* Open the panel with this hashtag */`

**Comment by quentin-michinot** [comment]
Bonjour,

avec ceci également :)

`<a href="#" onclick="tarteaucitron.userInterface.openPanel();">Gestion des cookies</a>`

**Comment by samsam-rolon** [comment]
Hello
Dans mon cas, seul cette solution a fonctionné (Wordpress + DIVI)
> <a href="#" onclick="tarteaucitron.userInterface.openPanel();">Gestion des cookies</a>

**Comment by AmauriC** [comment]
Avec l'interprétation des tags il y a juste un lien vers un hashtag 🙃

C'est comme https://github.com/AmauriC/tarteaucitron.js/issues/319#issuecomment-480053602 ?

**Comment by samsam-rolon** [comment]
Pardon, dans mon cas, seul `<a href="#" onclick="tarteaucitron.userInterface.openPanel();">Gestion des cookies</a>` a fonctionné !
Via `<a href="#tarteaucitron">Lien</a>` et la config `"hashtag": "#tarteaucitron", /* Open the panel with this hashtag */` cela ne fonctionne pas 😞

**Comment by AmauriC** [comment]
Ok merci pour le retour. Il y a surement sur le site un système qui gère les ancres et entre en conflit avec tac.
