### ISSUE TITLE
Uncaught TypeError: Cannot set property 'push' of undefined

### ISSUE THREAD

**Issue by ahyear** [AmauriC/tarteaucitron.js#32]
Bonjour,

J'ai cette erreur une fois le JS installé:

Uncaught TypeError: Cannot set property 'push' of undefined qui me renvoi a cette ligne : 
https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.js#L337

J'ai été jusqu'à l'étape 3 incluse.

Merci d'avance pour l'aide.

**Comment by AmauriC** [comment]
Le fichier js est bien inclus ? la toute fin du html ? De fa?on synchrone ?

Le 15 avr. 2016 ? 10:48, ahyear <notifications@github.com<mailto:notifications@github.com>> a ?crit :


Bonjour,

J'ai cette erreur une fois le JS install?:

Uncaught TypeError: Cannot set property 'push' of undefined qui me renvoi a cette ligne :
https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.js#L337

J'ai ?t? jusqu'? l'?tape 3 incluse.

Merci d'avance pour l'aide.

-

**Comment by ahyear** [comment]
le fichier tarteaucitron.js et ses params sont bien dans le head,
et le script appelé avant le \</body\> est appelé dans une variable PHP et doit donc être inclus de façon synchrone je suppose.

La particularité du projet est l’insertion dans un magento multi-store. donc les id changent en fonction de la boutique.
j'ai donc une insertion appelée via une variable php définie en backoffice.

**Comment by ahyear** [comment]
je pense que j'ai du mal placer le fichier maintenant ca fonctionne ( je ne sais plus ce que j'ai fait pour que ca fonctionne en revanche désolé... )

**Comment by dlaweb** [comment]
Adding jquery document load solved this pb for me.

    <script type="text/javascript">
        $(document).on("load", function ()
        {
            tarteaucitron.init(
                {
                "hashtag": "#tarteaucitron", /* Ouverture automatique du panel avec le hashtag */
                "highPrivacy": false, /* désactiver le consentement implicite (en naviguant) ? */
                "orientation": "top", /* le bandeau doit être en haut (top) ou en bas (bottom) ? */
                "adblocker": false, /* Afficher un message si un adblocker est détecté */
                "showAlertSmall": true, /* afficher le petit bandeau en bas à droite ? */
                "cookieslist": true, /* Afficher la liste des cookies installés ? */
                "removeCredit": false, /* supprimer le lien vers la source ? */
                "cookieDomain": ".blog.fr" /* Nom de domaine sur lequel sera posé le cookie pour les sous-domaines */
                }
            );

        });
    </script>
