### ISSUE TITLE
Youtube liste

### ISSUE THREAD

**Issue by ecedi-ld** [AmauriC/tarteaucitron.js#321]
Bonjour,

sauf erreur de ma part, je n'ai pas vu de service pour embarquer des listes Youtube via :

<iframe src="https://www.youtube.com/embed/videoseries?list=xxxxxxxxxxxxxxxxxxxxx&quot; width="100%" height="250" frameborder="0" allowfullscreen="allowfullscreen" data-rocket-lazyload="fitvidscompatible" data-lazy-src="https://www.youtube.com/embed/videoseries?list=xxxxxxxxxxxxxxxxxxxxxx&quot; class="lazyloaded" data-was-processed="true"></iframe>

Est-il possible d'ajouter ce service à votre librairie svp ?

**Comment by oTiMo** [comment]
@ecedi-ld : il existe : https://github.com/AmauriC/tarteaucitron.js/blob/dd5e77bcae2effd231a10a4cdf780813ef4a8f5d/tarteaucitron.services.js#L3507
