### ISSUE TITLE
Youtube, plusieurs vidéos sur une page 

### ISSUE THREAD

**Issue by ecedi-ld** [AmauriC/tarteaucitron.js#322]
Bonjour,

en l'état il me semble qu'il n'est pas possible d'embarquer deux vidéos youtube sur une même page étant donné qu'il faut utiliser l'attribut id="xxxx" qui doit être unique par page. 

Avez vous une solution autre que de faire autant de service qu'il y a de vidéo sur une page ?

**Comment by Ecedi-LD** [comment]
Je pense que la question peut se poser pour tous les services.

**Comment by jipexu** [comment]
Bonjour
tu veux dire inclure deux fois la même vidéo avec le même id  ?? car mettre plusieurs vidéo sur une page ne pose pas de problèmes ????

l'attribut n'est pas id (qui bien entendu doit être unique) mais videoID qui lui ne fait pas l'objet d'une contrainte d'unicité ....?

**Comment by Tutolex** [comment]
J'ai l'impression que tu parles de l'ID de la page au sens Wordpress par exemple.
Dans WP, chaque page possède un ID unique mais ce n'est pas du tout l'id dont il est question dans le code "tarte qu citron".

Par exemple sur le site que je viens de créer : 
-  Je veux mettre cette vidéo youtube sur ma page d'accueil :
https://www.youtube.com/watch?v=**ylzqhpU4WyQ**
- Je vais su ma page d'accueil avec WP. Sur l'administration je suis sur l'url suivante :
http://localhost/carte_visite/wp-admin/post.php?post=6&action=edit
Donc l'ID de la page est 6 (post=6)
- Pour ajouter ma vidéo, je cré un bloc HTML et j’introduis le code suivant :
<div class="youtube_player" videoID="**ylzqhpU4WyQ**"  controls="1" height="312" showinfo="1" autoplay="0"></div>

- Donc l'ID de ma vidéo est "ylzqhpU4WyQ" ce qui n'a rien à voir avec l'ID de la page qui est "6". On peut donc mettre autant de vidéos que l'on veut par page.

**Comment by Ecedi-LD** [comment]
Bonjour,

merci pour ces retours, je viens de tester mais sans l'attribut id="youtube" (déclaré sur https://opt-out.ferank.eu/pro/#edit=9192 où il est mentionné "Cet élément (div, p, span, ...) doit être présent sur mds.71.ecedi.fr pour que Youtube y soit injecté."), le code :

<div class="youtube_player" videoID="ogEBlhBuCuM" width="300" height="314" theme="dark" rel="1" controls="1" showinfo="1" autoplay="0"></div>

ne fonctionne pas, pas d'injection. Alors qu'avec :

<div id="youtube" class="youtube_player" videoID="ogEBlhBuCuM" width="300" height="314" theme="dark" rel="1" controls="1" showinfo="1" autoplay="0"></div>

cela fonctionne bien.

**Comment by florianbouvot** [comment]
Bonjour, je me pause la même question : comment faire quand plusieurs vidéos peuvent être ajoutées par l'utilisateur dans une même page ?

Dans la version PRO, je vois qu'il est possible de déclarer plusieurs "conteneur" vidéo côté tarteaucitron mais ça ne répond pas à ce besoin dynamique !

**Comment by David-GH** [comment]
Bonjour, je me permet également d'écrire à ce sujet.
Au vu des infos que je vois sur le net, il semblerait que l'on puisse "simplement" ajouter un code de ce type :
`<div class="youtube_player" videoID="ogEBlhBuCuM" width="300" height="314" theme="dark" rel="1" controls="1" showinfo="1" autoplay="0"></div> `

Mais avec la version pro, cela ne fonctionne pas, car on doit absolument définir un conteneur avec un id unique.
On perd finalement l'aspect dynamique de la chose. Cela aurait été beaucoup plus pertinent de permettre d'activer youtube et si les cookies sont autorisés, alors remplacer simplement les champs avec attribut videoID....

Il faudrait peut-être passer par la version auto-hébergée, mais du coup on perds l'intérêt de l'offre pro... :/

Si quelqu'un sait comment faire...

**Comment by AmauriC** [comment]
C'est faisable avec la v pro, il faut ajouter le service youtube sans spécifier d'id: https://github.com/AmauriC/tarteaucitron.js/discussions/630#discussioncomment-533434

**Comment by David-GH** [comment]
Merci pour ce retour d'information qui m'a aidé.
**Merci également pour votre travail @AmauriC !**

**Comment by GABS12386** [comment]
Because a cookie’s SameSite attribute was not set or is invalid, it defaults to SameSite=Lax, which prevents the cookie from being set in a cross-site context. This behavior protects user data from accidentally leaking to third parties and cross-site request forgery.
Resolve this issue by updating the attributes of the cookie:
Specify SameSite=None and Secure if the cookie is intended to be set in cross-site contexts. Note that only cookies sent over HTTPS may use the Secure attribute.
Specify SameSite=Strict or SameSite=Lax if the cookie should not be set by cross-site requests.(bonjour j'ai cette erreur au niveau de ma page web les cookies youtube ne sont pas bloqué quand je le demande et je ne vois pas du tout a quoi cela ai du je corrige le code d'une autre personne)

**Comment by AmauriC** [comment]
Je n'ai pas accès à votre localhost 🙃
