### ISSUE TITLE
Google analytics - Événement GA send

### ISSUE THREAD

**Issue by LucieA3web** [AmauriC/tarteaucitron.js#323]
Bonjour,

J'utilise tarte au citron sur mon site.
Je souhaite au clic sur un bouton déclencher un événement.
Avant tarte au citron, j'utilisais ceci : ga('send', 'event', 'event test 1', 'view', 'test');
J'ai tenté de mettre ce code dans tarteaucitron.user.gajsMore sans réussite.

Pouvez-vous m'aider ?

Par avance merci

**Comment by Kdxfx** [comment]
Hi, i got exactly the same issue. Do you have any solution now ? thx in advance

**Comment by vgrange** [comment]
FYI the following logic is working for us to send google events:

```
tarteaucitron.user.gtagMore = function () {
    gtag('event', 'employeur', {
    'event_category': 'repondre',
    'event_label': 'entretien'
    });
};
```
However I am still struggling to send pageviews, see https://github.com/AmauriC/tarteaucitron.js/issues/325

**Comment by drobert8584** [comment]
une solution ici : https://github.com/AmauriC/tarteaucitron.js/issues/334
