### ISSUE TITLE
Vidéo Youtube/Vimeo & lightbox

### ISSUE THREAD

**Issue by popfree** [AmauriC/tarteaucitron.js#324]
Bonsoir, tout d'abord, merci beaucoup Amauri pour cette excellente tarteaucitron qui fonctionne parfaitement et que j'ai découverte sur le site de la cnil.
Auriez-vous un piste pour exécuter ce script avec des vidéos lancées en lightbox ?
En effet, la plupart des lightbox s'exécutent avec un "href=...", cependant le 'push' tarteaucitron.js impose dans le cas d'intégration de vidéo YouTube ou Vimeo une "div  class=...  vidéo id=... " ce qui génère de nombreux problème javascript à l'éxécution de lightbox. 
Je cherche à utiliser tarteaucitron depuis plusieurs semaines avec différentes lightbox (floatbox / afterglow / Video Lightning / html5lightbox/ ...) et je n'arrive pas à trouver de solution pour que tout fonctionne parfaitement. 
Soit je lance une div dans ma lightbox mais, à ce moment là, je n'ai plus de fonction comme "autoplay" ou "autoend" même en modifiant 'tarteaucitron.services.js'.
Soit je respect la programmation js des lightox et il m'est impossible d’exécuter tarteaucitron.
Quelqu'un aurait-il une solution à ce problème ou en exemple un site qui arrive à exécuter tarteaucitron dans une lightbox ou popup?
D'avance merci pour votre aide.

**Comment by hello-motto** [comment]
Salut popfree,
J'avais à peu près la même problématique que toi et pour y répondre, j'ai commencé à développer un petit plugin du même genre que lightbox qui prend en charge tarteaucitron.
Pour l'instant seul youtube est pris en compte, mais je travaille sur la prise en charge des autres fournisseurs de contenus.
Tu peux le retrouver ici : [hello-motto/videos-modal](https://github.com/hello-motto/videos-modal)
Et si tu as des suggestions d'améliorations, elle seront les bienvenues (la prise en charge du plein écran n'est pas encore possible dans youtube sur tarteaucitron, du coup là non plus).

**Comment by popfree** [comment]
Bonjour @hello-motto,
Merci beaucoup pour ton message. J'ai regardé rapidement ton script. 
En fait, tu sembles appeler le nodal "userInterface" au lieu d'intégrer le "button tac" directement dans la lightbox. C'est une approche intéressante que je vais étudier malgré mon faible niveau js.
Pour l'instant, dans mon développement de site, j'ai jeté l'éponge (au citron). J'utilise "[floatboxjs](https://floatboxjs.com/)" un script vraiment complet et j'intègre les vidéos avec "www.youtube-nocookie.com/...". 
Je ne désespère pas aussi de trouver une solution via les Ressources API des players.

**Comment by hello-motto** [comment]
> En fait, tu sembles appeler le nodal "userInterface" au lieu d'intégrer le "button tac" directement dans la lightbox
Je n'ai pas compris ce que tu voulais dire exactement... Quoiqu'il en soit, j'ai fait quelques modifications sur l'existant qui seront disponibles bientôt.
Bon courage pour la suite.
