### ISSUE TITLE
Erreur tarteaucitron v1.2

### ISSUE THREAD

**Issue by Stepomp** [AmauriC/tarteaucitron.js#335]
Bonjour,

J'ai voulu mettre à jour la version de tarteaucitron sur mon site, mais cela ne fonctionne plus

J'ai les erreurs suivantes dans la console de développement :
TypeError: tarteaucitron.parameters is undefinedtarteaucitron.js:237:9
    load https://cdn.jsdelivr.net/gh/AmauriC/tarteaucitron.js@V1.2/tarteaucitron.js:237
    init https://cdn.jsdelivr.net/gh/AmauriC/tarteaucitron.js@V1.2/tarteaucitron.js:44

Pourriez-vous me dire d'où vient le problème ?

En vous remerciant,

Cdlt,

**Comment by Stepomp** [comment]
Pour info, j'ai les mêmes erreurs si j'indique l'adresse du script en local

**Comment by Stepomp** [comment]
Bonjour,

Il n'y a plus personne ?

Cdlt,

**Comment by AmauriC** [comment]
Je suis là 😊

Le script a correctement été initialisé ?
Quel est le code tarteaucitron complet que vous avez ajouté ?

**Comment by Stepomp** [comment]
Bonjour,

Ouf ;)

J'ai téléchargé le code source de la version 1.2 sur la page https://github.com/AmauriC/tarteaucitron.js/releases et copié-collé le script se trouvant sur la page https://opt-out.ferank.eu/fr/install/

Cdlt,

**Comment by Stepomp** [comment]
Bonjour,

J'ai ajouté dans le fichier tarteaucitron.js à la ligne 38 :
if (typeof params !== 'undefined') {
        tarteaucitron.parameters = params;
		}

Et je n'ai plus d'erreur

Ne faut-il pas que vous modifiez également votre code sur :
https://cdn.jsdelivr.net/gh/AmauriC/tarteaucitron.js@V1.2/tarteaucitron.js:

Cdlt,
