### ISSUE TITLE
Attributs added, state et launch

### ISSUE THREAD

**Issue by igniscom** [AmauriC/tarteaucitron.js#34]
Bonjour,

Les 3 attributs tarteaucitron.added, tarteaucitron.state et tarteaucitron.launch sont déclarés au départ comme des _Array_. Or vous les complétez ensuite comme s'il s'agissait d'_Objects_ (en spécifiant une clé, alors qu'en javascript on ne peut pas toucher, si je ne m'abuse, aux clés).

Ne vaudrait-il pas mieux les initialiser en tant qu'objets ?
`var launch = {};`

Ou inclure les services sous forme d'objet ?
```
var launch = [];
launch.push({
    googletagmanager: true
});
```

**Comment by AmauriC** [comment]
Bonjour,

En effet, ce n'est pas du PHP..

Je vais revoir tout ça 👍

**Comment by igniscom** [comment]
Mais de rien. :)
