### ISSUE TITLE
[AJAX] Vidéo injectées en ajax ne s'initialisent pas

### ISSUE THREAD

**Issue by Son-Isaki** [AmauriC/tarteaucitron.js#341]
Hi Amauri,

I have an initialization issue with the plugin after injecting html content in the DOM using AJAX.

On content displayed on page loaded, the init works perfectly as intended (youtube videos shows up). But, when the same content is shown using AJAX in a page, videos does not initialize at all !

I obviously tried to initialize again tarteaucitron ajax success event, but it still does not work...

Do you have a solution to this problem ?

french version :
J'ai un soucis d'initialisation du plugin après injection de contenu (récupéré via ajax) dans le DOM. 

En effet, sur du contenu affiché lorsque l'on arrive sur une page, l'initialisation du plugin fonctionne normalement (les vidéo YT s'affichent) mais lorsque ces mêmes contenu sont injectés en AJAX dans une page, les vidéos ne s’initialisent pas du tout.

J'ai bien sûr tenté tarteaucitron.init(config), mais rien n'y fait...

Avez-vous une solution à ce problème ?

Cdt,
Romain

**Comment by CIMEOS** [comment]
Hi @Son-Isaki 

We encountered the same issue not  long ago, you can use this in your AJAX sucess response:
`tarteaucitron.job.push('youtube')` this should activate your youtube video :)
You could use this function to trigger tarteaucitron to show social networks you've declared in your configuration.
`function triggerTarteaucitronJobs()
{
    tarteaucitron.job.forEach(function(e)
    {
        tarteaucitron.job.push(e)
    });
}`

**Comment by Dahkon** [comment]
code from @CIMEOS works well excepts that click on "allow" for video like youtube (when you refuse cookies at first) are not effective.

I needed to add this kind of code to initialize clicks after html was inserted with ajax :  
Code was extracted from tarteaucitron.js

         ```
           var allowBtns = document.getElementsByClassName("tarteaucitronAllow");
                    for (i = 0; i < allowBtns.length; i++) {
                        tarteaucitron.addClickEventToElement(allowBtns[i], function () {
                            tarteaucitron.userInterface.respond(this, true);
                        });
                    }
```
Hope it helps

**Comment by Son-Isaki** [comment]
Thank you, it works well as CIMEOS said ;)
