### ISSUE TITLE
How to adapt language

### ISSUE THREAD

**Issue by csonrel** [AmauriC/tarteaucitron.js#353]
Hello, 
I have a website http://www.web.com/fr/ and http://www.web.com/en/. How to switch language  in tarte au citron ?
Thx !

**Comment by crtlf** [comment]
You can use the `tarteaucitronForceLanguage` variable **before** initializing Tarteaucitron.

```js
// Example : this gets the lang attribute of the html tag
var currentLanguage = document.documentElement.lang;
window.tarteaucitronForceLanguage = currentLanguage;
```

**Comment by XaBe20** [comment]
Hello,
I use version Pro, how can you do in this case?
It's possible to use `tarteaucitronForceLanguage` variable before initializing with distant librairies ?
Thanks

**Comment by AmauriC** [comment]
With the pro version, do it with an url parameter on the script:
`https://tarteaucitron.io/load.js?locale=fr&domain=...&uuid=...`

**Comment by XaBe20** [comment]
Thanks for quick answer @AmauriC 
it's works, have a good day
