### ISSUE TITLE
Trace du consentement cookies

### ISSUE THREAD

**Issue by GaelleGu** [AmauriC/tarteaucitron.js#357]
Bonjour. Le RGPD nécessite que nous gardions une trace du consentement des personnes. Où peut-on trouver une telle liste pour l'acceptation des cookies dans votre plugin ? Associant par exemple une Adresse IP, une date d'acceptation de cookie et pourquoi pas les cookies activés/désactivés par l'utilisateur. Nous avons souscrit à l'offre payante un an mais ne trouvons pas ce type d'info. Merci d'avance

**Comment by AmauriC** [comment]
Bonjour,

La CNIL ne s'est pas encore prononcé sur la méthodologie à appliquer pour apporter la preuve du consentement mais ce ne sera pas au niveau du gestionnaire de cookie.

Stocker par un prestataire tiers (moi) les adresses ip et actions des utilisateurs est un non sens 😉

Ce n'est d'ailleurs pas une preuve d'un point de vue juridique.

Dès que j'ai plus d'informations, je l'annoncerai sur le site.

**Comment by prudloff-insite** [comment]
C'est possible depuis https://github.com/AmauriC/tarteaucitron.js/pull/363.

**Comment by micka130** [comment]
Super merci @prudloff-insite
