### ISSUE TITLE
[Bug] Cookie stay after denied all

### ISSUE THREAD

**Issue by quentin-michinot** [AmauriC/tarteaucitron.js#359]
Hi,

When I accept all and refuse after, a lot of cookie stay into my browers :/

If you have any idea :)

**Comment by webdev69420** [comment]
This seems to still be the case (at least of websites starting with www.*.tld), any updates?

**Comment by AmauriC** [comment]
Did you have a website url where I can reproduce?

**Comment by webdev69420** [comment]
[Here](https://weeeze.com/) or [here](https://www.guialto.com/?preview=on) for example.

The Google Analytics cookies when accepted and when denied are not the same, but I still don't see why there would be any Google Analytics cookies stored at all when the service is refused by the user.

Maybe there's something that I don't fully understand?

Thanks for the quick reply :)

**Comment by AmauriC** [comment]
From my side it's working good on both websites.
When GA allowed there is 2 cookies, when denied (and page reloaded), no more cookies.
![Capture d’écran 2023-03-16 à 10 23 31](https://user-images.githubusercontent.com/8764074/225572705-9c2a23dd-f9a2-48dd-95d2-85e74563acca.png)
![Capture d’écran 2023-03-16 à 10 23 21](https://user-images.githubusercontent.com/8764074/225572723-898060bc-a2eb-4447-aa4b-eaaf5f0293f5.png)

**Comment by webdev69420** [comment]
Weird, for me it's 2 cookies (with values) when accepted and 33 cookies (all empty) when denied:

- [Video recording of the issue](https://cln.sh/XRSTfmy7)

I just want to make sure the user is not tracked if he denied. So all those empty cookies don't make the user trackable, that's fine for me too. I was just wondering why there's so much of them.

**Comment by webdev69420** [comment]
Nice, then I'll just ignore those cookies, that works for me!
