### ISSUE TITLE
Apply other styles

### ISSUE THREAD

**Issue by davidmoret** [AmauriC/tarteaucitron.js#362]
Bonjour Amauri,
Merci pour ce script, il m'est fort utile. Néanmoins je rencontre des difficultés à y appliquer un theme différent.
Pensez-vous que le script sera modifié à l'avenir pour sépraer le fond de la forme ? Je pense notamment aux boutons sur lesquels le javascript applique du css en ligne.
Bien cordialement,
David

**Comment by prudloff-insite** [comment]
En fait, il y a ce commit qui retire les couleurs du JS : https://github.com/AmauriC/tarteaucitron.js/commit/7c94cf65cce8f2ff0e99ad8013ac939c6b11b3a3
Mais il est n'est pas encore inclus dans une version stable.
