### ISSUE TITLE
Matomo/Variables personnalisées

### ISSUE THREAD

**Issue by YanGarnier7** [AmauriC/tarteaucitron.js#367]
Bonjour,

J'ai regardé la doc de matomo pour utiliser les variables personnalisées, cela semble assez simple mais je n'arrive pas à les faire fonctionner avec tarteaucitron.

L'exemple de la doc est le suivant : 
`_paq.push(['setCustomVariable', 1, 'Category', 'Sports', 'page']);`
`_paq.push(['setCustomVariable', 2, 'Category', 'Europe', 'page']);`
`_paq.push(['trackPageView']);`

Voila à quoi ressemble ce que j'ai fait pour l'ajouter à mon site via tarteaucitron et y intégrer des variables personnalisées : 
`tarteaucitron.user.matomoId = 2;`
`tarteaucitron.user.matomoHost = monURL;`
`(tarteaucitron.job = tarteaucitron.job || []).push('matomo');`
`    if(login != ""){`
`        (tarteaucitron.job = tarteaucitron.job || []).push(['setUserId', login]);`
`        if(departement != ""){`
`            (tarteaucitron.job = tarteaucitron.job || []).push(['setCustomVariable', 1, 'Departement', departement, 'page']);`
`          }`
`    }else{`
`        (tarteaucitron.job = tarteaucitron.job || []).push(['resetUserId']);`
`    }`
`(tarteaucitron.job = tarteaucitron.job || []).push(['trackPageView']);`
(en sachant que login et departement n'étaient pas vides, je n'ai aucune erreur js mais rien dans mes rapports d'audience matomo)

J'ai également essayé ça, sans réussite (Cannot reat property 'setCustomVariable' of undefined)
`tarteaucitron.services.matomo.setCustomVariable(1, "VisitorType", "Member", "visit");`
`tarteaucitron.services.matomo.trackPageView();`

Afin de vérifier que mon code "fonctionnait", j'ai aussi testé d'intégrer matomo sans passer par tarteaucitron via ce code, et cela fonctionne correctement je récupère bien mes variables personnalisées : 
`var _paq = window._paq || [];`
` _paq.push(['setCustomVariable', 2, 'Test', "Bonjour", 'visit']);`
` if(login != ""){`
`    _paq.push(['setUserId', login]);`
`     if(departement != ""){`
`       _paq.push(['setCustomVariable', 1, 'Departement', departement, 'page']);`
`     }`
`   }else{`
`     _paq.push(['resetUserId']);`
`   }`
` _paq.push(['trackPageView']);`
` _paq.push(['enableLinkTracking']);`
` (function() {`
`   var u= monURL;`
`   _paq.push(['setTrackerUrl', u+'matomo.php']);`
`   _paq.push(['setSiteId', '2']);`
`   var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];`
`   g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);`
` })();`

Auriez-vous des pistes, voire même des solutions pour ce problème ?

**Comment by YanGarnier-7** [comment]
J'ai trouvé une solution qui consiste à aller écrire les variables personnalisées à l'intérieur de tarteaucitron.services.matomo directement dans le fichier tarteaucitron.services.js. Cela fonctionne mais je trouve ça dommage de devoir écrire à l'intérieur du code source pour faire ça
