### ISSUE TITLE
Adcell Conversion Tracking

### ISSUE THREAD

**Issue by hansfranz456** [AmauriC/tarteaucitron.js#371]
I need a code for Adcell Conversion tracking:

<script type="text/javascript" src="https://t.adcell.com/t/track.js?pid=XXXX&eventid=XXXX&referenz=ABC_123&betrag=123.45">
</script>
<noscript>
<img border="0" width="1" height="1" src="https://t.adcell.com/t/track?pid=XXXX&eventid=XXXX&referenz=ABC_123&betrag=123.45">
</noscript>

**Comment by yunai39** [comment]
Hello,

You could just create your own custom service.

tarteaucitron.services.Adcell = {
    "key": "Adcell",
    "type": "analytic",
    "name": "other",
    "needConsent": true,
    "cookies": [],
    "js": function () {
        "use strict";
        tarteaucitron.addScript('https://t.adcell.com/t/track.js?pid=XXXX&eventid=XXXX&referenz=ABC_123&betrag=123.45');
    }
};

(tarteaucitron.job = tarteaucitron.job || []).push('Adcell');
