### ISSUE TITLE
Need help to configure

### ISSUE THREAD

**Issue by Valaby** [AmauriC/tarteaucitron.js#375]
Hello there,

It should come from a silly thing, but I can't succeed to configure tarteaucitron.
When i'm looking for services on https://opt-out.ferank.eu/, the website seems to search for ever. Does it come from me or server?

Like I said, just before </ head> i put the famous script. I dl the file tarteaucitron that i put at my file root. I've tried to configure google analytics, with include before </ body>, but I can't figure out. I left every options by default.

This is what I've copied from the original website and put before </ head> :
<script type="text/javascript" src="/tarteaucitron/tarteaucitron.js"></script>
        <script type="text/javascript">
        tarteaucitron.init({
    	  "privacyUrl": "", /* Privacy policy url */

    	  "hashtag": "#tarteaucitron", /* Open the panel with this hashtag */
    	  "cookieName": "tarteaucitron", /* Cookie name */
    
    	  "orientation": "top", /* Banner position (top - bottom) */
    	  "showAlertSmall": true, /* Show the small banner on bottom right */
    	  "cookieslist": true, /* Show the cookie list */

    	  "adblocker": false, /* Show a Warning if an adblocker is detected */
    	  "AcceptAllCta" : true, /* Show the accept all button when highPrivacy on */
    	  "highPrivacy": false, /* Disable auto consent */
    	  "handleBrowserDNTRequest": false, /* If Do Not Track == 1, disallow all */

    	  "removeCredit": false, /* Remove credit link */
    	  "moreInfoLink": true, /* Show more info link */
    	  "useExternalCss": false, /* If false, the tarteaucitron.css file will be loaded */

    	  //"cookieDomain": ".my-multisite-domaine.fr", /* Shared cookie for multisite */
                          
    	  "readmoreLink": "/cookiespolicy" /* Change the default readmore link */
        });
        </script>

Any advices? ^^'
Thanks!

**Comment by nicohery** [comment]
Did not you forget to configure the services ?
Have a look at "Step 3": add a service -> Search a service (ex: Analytics...).

**Comment by Valaby** [comment]
Hey Nicohery,
Thanks for your answer. I already put the script with replacing UA-XXXXXXXX-X with my google analytics code
<script type="text/javascript">
		tarteaucitron.user.analyticsUa = 'UA-XXXXXXXX-X';
		tarteaucitron.user.analyticsMore = function () { /* add here your optionnal ga.push() */ };
		(tarteaucitron.job = tarteaucitron.job || []).push('analytics');
	</script>

I've just tried yours, it didn't work either :/
When i'm searching a service, the site is blocking on "Search a service..."

**Comment by AmauriC** [comment]
If nothing is displayed, the service do not exist 🙃

**Comment by Valaby** [comment]
So, what should I do? ^^'
My google accounts are activate and are working fine.

**Comment by pierreloicq** [comment]
Do you manage to see the tarteaucitron alert on your website ?
what service are you looking for ?
