### ISSUE TITLE
[PRO Version] How to define the cookies durations (expire date) ?

### ISSUE THREAD

**Issue by adrienlamotte** [AmauriC/tarteaucitron.js#378]
Hi,

We have a PRO account, an we are using the Wordpress plugin.
How can we define the duration of the cookies ? Indeed, the max duration of a cookie cannot be more than 13 months...

Thank you !

**Comment by AmauriC** [comment]
Hi,

This is not yet available but I can add this as an option.

Can you tell me why you want to change the cookie expire date? 🙃

**Comment by AmauriC** [comment]
I'm aware of the CNIL recommandations, do not worry about this.
The tarteaucitron cookie expire after 13 months and when this cookie is expired, all the others cookies are removed 🙂👌

**Comment by AmauriC** [comment]
I'm aware of the CNIL recommandations, do not worry about this.
The tarteaucitron cookie expire after 13 months and when this cookie is expired, all the others cookies are removed 🙂👌

**Comment by AmauriC** [comment]
I'm aware of the CNIL recommandations, do not worry about this.
The tarteaucitron cookie expire after 13 months and when this cookie is expired, all the others cookies are removed 🙂👌

**Comment by adrienlamotte** [comment]
@AmauriC Hi ! The GDPR says that the cookies should have expiration date of 13 months (ex with the CNIL : https://www.cnil.fr/fr/cookies-traceurs-que-dit-la-loi). But for exemple Google Analytics set the default duration to 24 months.

So some of my clients ask me to reduce the duration... ;)

If you can add this as an option it will be great ! Thank you

**Comment by adrienlamotte** [comment]
@AmauriC ok good news :-)
Maybe to be more transparent with the user you should define the expire date of all cookies (when it's possible) to 13 months too (or add the option). 

Thanks !

**Comment by adriendurepaire** [comment]
Hi @AmauriC, is there any update on this issue? 
I see in the code multiple attributes like "timeExpire" or "tarteaucitronForceExpire". Which one should I use to define the expire date of all the cookies?

**Comment by AmauriC** [comment]
you can set `var tarteaucitronForceExpire = 90;` before loading the tarteaucitron tag to force the tarteaucitron cookie to expire avec 90 days.

**Comment by AnthonyIp** [comment]
Bonjour @AmauriC, 

Désolé de rouvrir l'issue mais si je comprends bien, lorsque le cookie de tarteaucitron s'expira, les cookies de GA qui par défaut sont de 24 mois, s’expieront aussi ?

Merci

**Comment by AmauriC** [comment]
Yes, quand le cookie tarteaucitron expire, GA n'est logiquement plus autorisé et les cookies sont purgés ; )

**Comment by DinhoRyoh** [comment]
Bonjour @AmauriC, J'ai un petit souçis avec l'expiration des cookies.
Quand je paramètre la variable tarteaucitronForceExpire comme expliqué plus haut, le cookie de youtube disparait bien mais pas ceux qui concernent analytics. As-tu une idée ?

Merci d'avance

**Comment by AmauriC** [comment]
Ce ne sont pas les cookies sur le domaine google.com ? Si oui ils sont impossibles à supprimer mais comme le tag google n'est plus ajouté sur le site, il ne sont plus accessibles.

**Comment by DinhoRyoh** [comment]
J'ai deux cookies _ga et _ga_XXXXX qui sont sur mon domaine en local (je fais des tests) et qui restent malgré l'expiration du cookie tarteaucitron.

on est bien d'accord que normalement à l'expiration du cookie tarteaucitron, les cookies analytics ne devraient plus apparaître sur l'inspecteur (application/cookies) ?

Quand le cookie de tarteaucitron expire et que je retourne sur le site. Dans le gestionnaire de cookies tout est bien refusé (normal), alors que dans l'inspecteur du navigateur, on retrouve les cookies de _ga qui sont toujours la.
En revanche lorsque que je ferme le gestionnaire de cookies sans aucune modification de ma part, les cookies se suppriment.

**Comment by AmauriC** [comment]
Il faut aussi regarder le contenu et la date d'expiration.
A l'expiration du cookie, tarteaucitron créé les cookies avec un contenu vide et une date d'expiration dans le passé pour être sur qu'ils sont supprimés.
Relancer la navigateur devrait tout supprimer définitivement.
