### ISSUE TITLE
RecaptchaV2 masqué même après acceptation des cookies

### ISSUE THREAD

**Issue by GaelleGu** [AmauriC/tarteaucitron.js#379]
Bonjour, 

Depuis 3 jours, nous rencontrons un problème d'incompatibilité entre le plugin Tarte au citron et le RecaptchaV2 de Google présent dans nos formulaires. Au chargement d'un formulaire, un bandeau tarteaucitron apparaît à la place du Recaptcha
![Capture1](https://user-images.githubusercontent.com/55389721/68482574-2cba7f80-023a-11ea-871d-217557e865c3.PNG)
, et si on autorise ce cookie spécifique, le Recaptcha n'apparaît pas automatiquement.
![Capture2](https://user-images.githubusercontent.com/55389721/68482819-a488aa00-023a-11ea-9df1-0f3e0ceeb9a7.PNG)
 Il faut soumettre une 1ère fois le formulaire, puis celui-ci se recharge pour faire apparaître le recaptcha. Donc il faut 2 clics pour valider le formulaire, ce qui n'est pas idéal :/
![image](https://user-images.githubusercontent.com/55389721/68482858-b9fdd400-023a-11ea-8481-8a4f066be4e1.png)

La déconnexion de Tarteaucitron sur notre Wordpress semble résoudre le problème : le Recaptcha apparaît alors dès le 1er chargement de la page. Y a-t-il eu des récentes évolutions du plugin Tarteaucitron ? Comment résoudre ce bug ? 
Merci d'avance pour votre aide :)

**Comment by HippieStereo** [comment]
Dans mon cas dans la tag head je ne charge plus le captcha vu que le js de tarte citron le fait
