### ISSUE TITLE
Error 404 on loading js lang file - MIME type ("text/html") i.o (javascript) 

### ISSUE THREAD

**Issue by Xelaflash** [AmauriC/tarteaucitron.js#384]
Hi, 

I've got an 404 error in the console for the `lang` file(s).

Error states : `The script from “xxx.com/tarteaucitron/lang/tarteaucitron.fr.js?v=20191031” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.`

and 

`Loading failed for the <script> with source “xxx.com/tarteaucitron/lang/tarteaucitron.fr.js?v=20191031”.`

When checking the `network tab` i can see the `response headers / content-type` set to `text/html` preventing the script to load.

<img width="580" alt="Screenshot 2019-11-26 at 16 02 06" src="https://user-images.githubusercontent.com/30756484/69668473-5b23c180-1066-11ea-98ca-8417eda2000f.png">

I have this issue only on production (site deployed to netlify). 
In dev all is working well i have `Content-type: application/javascript`as `Response header`. 

Do you have any idea of where this issue lies and how to solve this out?

Thanks in advance.

**Comment by fsoabsix** [comment]
Hi, i have the same problem ...

**Comment by inwardmovement** [comment]
Same here, any insight @AmauriC?

**Comment by AmauriC** [comment]
The mime type is managed by your servers, it's not setted by the script itself 🧐

Or I miss something? Someone as a live example?

**Comment by inwardmovement** [comment]
I have an example here: https://algosphere.org/

![image](https://user-images.githubusercontent.com/9438102/83736613-2fefdf80-a652-11ea-9c3d-339384d5e3d0.png)

**Comment by AmauriC** [comment]
No adblocker on your browser? With Chrome/Mac GA is correctly loaded.

**Comment by inwardmovement** [comment]
Indeed it works when the adblocker is disabled. Can you do something to get around adblockers?

Also, I've got this message:
`Le cookie « _ga » sera bientôt rejeté car son attribut « sameSite » est défini sur « none » ou une valeur invalide, et sans attribut « secure ». Pour en savoir plus sur l’attribut « sameSite », consultez https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite`

Can you add `SameSite=Lax` to the cookie, or is it Google who has to take care of this?

**Comment by AmauriC** [comment]
No, this is not possible to bypass an adblocker but there is an option to show a message if an adblocker is detected:
`"adblocker": true,`

Open a new issue for the cookie, I'll check ; )
