### ISSUE TITLE
Probleme d'affichage Addthis et tarteaucitron.js

### ISSUE THREAD

**Issue by inaativ** [AmauriC/tarteaucitron.js#386]
Bonjour,

Un peu désespéré et après avoir essayé de trouver plusieurs solutions, je termine ici pour avoir un peu d'aide. 
J'ai installé des boutons de partage Addthis sur un blog Wordpress selon la méthode d'install fournie par Addthis.
J'ai activé le service sur tarteaucitron.js comme indiqué sur la doc.
Les boutons de partage apparaissent au premier chargement de la page, et se désactivent si je le choisi dans le panneau de gestion des cookies.
Le problème, si je choisi de les activer à nouveau, ils ne s'affiche plus. Aussi, ils s'affichent 1sec si je reload la page puis disparaissent.

Exemple ici -->  https://www.pratiques-rh-au-quotidien.com/2019/11/management-des-talents-rise-marwan-mery-laurent-combalbert/

Une idée pour m'éclairer ?
Merci beaucoup !

**Comment by davidlemaitre** [comment]
Je ne vois pas de problème ou vous l'avez résolu depuis ?
