### ISSUE TITLE
Handle single page website

### ISSUE THREAD

**Issue by yunai39** [AmauriC/tarteaucitron.js#388]
Bonjour,

Je crois que actuellement tarteaucitron (après j'ai pas trouvé de fonction toutes faite dans le code pour le faire) ne gère pas les sites qui sont en single page (on charge du contenu qu'on intègre en ajax sans recharger la page).

Du coup, je voulais savoir s'il y avait déjà quelque chose pour gérer cela ?

Actuellement j'ai eu le cas, sur un tracker gtag. Pour le relancé au chagement de page j'ai fait ça:

    if (typeof tarteaucitron.state.gtag !== 'undefined' && tarteaucitron.state.gtag && typeof tarteaucitron.services['gtag'] !== 'undefined') {
             tarteaucitron.services['gtag'].js();
     }

Il y a t'il une autre façon de faire ?
Est ce qu'il serait utile de faire un fonction pour re-déclencher les envoi des trackers en cas de single page website ? (Je peux créer une Pull Request pour àa)

======================

Hello,

If I'm not wrong, currently tarteaucitron is not able to resend tracker for single page website.

I was wondering if there was anything to handle single page website ?

I had this problem for a gtag tracker. To resend the tracker I did this
?

    if (typeof tarteaucitron.state.gtag !== 'undefined' && tarteaucitron.state.gtag && typeof tarteaucitron.services['gtag'] !== 'undefined') {
             tarteaucitron.services['gtag'].js();
     }

Is there any other way to do that ? (maybe better than what I did)

And will it be useful to create a function to resend tracker for single page website ? (I will create pull request for that)

**Comment by julien-deramond** [comment]
I'm also beginning to use Tarteaucitron in a SPA.
One page contains an embedded Youtube player.
When Angular has fully initialized the corresponding component's view, I call this function to trigger manually Tarteaucitron:
```js
function triggerTarteaucitronYoutube() {      
  if (undefined !== tarteaucitron.services.youtube) {
    if (typeof tarteaucitron.state.youtube !== 'undefined' && tarteaucitron.state.youtube && typeof tarteaucitron.services['youtube'] !== 'undefined') {
      tarteaucitron.services['youtube'].js();
    } else {
      tarteaucitron.services['youtube'].fallback();
      tarteaucitron.triggerJobsAfterAjaxCall();
    }
  }
}
```
It seems to work pretty well but I'm also wondering if this is the right way of doing this :shrug:
