### ISSUE TITLE
Masquer le bandeau "tarteaucitronAlertBig"

### ISSUE THREAD

**Issue by mathieucunin** [AmauriC/tarteaucitron.js#389]
Bonjour et tout d'abord bravo pour pour tarteaucitron. J'utilise que ça maintenant lorsque je veux intégrer un bandeau cookie. Du coup 1 étoile en plus :).

J'ai une demande particulière aujourd'hui. Sur le site que je réalise actuellement je n'ai pas l'obligation d'afficher le bandeau qui s'affiche aujourd'hui automatiquement à l'ouverture du site. 
Cependant je dois tout de même avoir un lien qui me permet de paramétrer l'autorisation/interdiction des cookies.

Est-ce possible de réaliser ça ?

Merci encore et bon réveillon !!!

**Comment by Leboubou111** [comment]
Je pense qu'un display non devrait faire l'affaire... 
Et pour l'accès aux autorisations, il faut renseigner le paramètre "hashtag": "#cookies-perso", dans l'appel à la fonction tarteaucitron.init

Ensuite soit tu mets un "showAlertSmall": false, et tu mets un lien vers ton hashtag, soit tu peux juste laisse "showAlertSmall": true, et un clic sur cette boite permet d'afficher la fenêtre d'autorisation.

**Comment by mathieucunin** [comment]
Merci leboubou111, j'ai juste galéré a trouver le bon display:block à changer mais c'est ok.
