### ISSUE TITLE
Problème WP Rocket

### ISSUE THREAD

**Issue by Bazoul54** [AmauriC/tarteaucitron.js#397]
Bonjour et merci AmauriC pour ton travail !

Je gère une centaine de sites (sur DIVI), qui jusqu'à présent utilise Cookie Notice et je n'utilise que Google Analytic Universal pour le tracking.

Je voudrais passer sur Tarte au citron, mais je rencontre quelques problèmes avec WP Rocket.

Sur certains sites, cela fonctionne, et d'autres non.

J'ai essayé toutes les méthodes possible que j'ai pu trouver sur internet, aucunes ne fonctionnent.

La seul méthode que j'ai trouvé jusqu'à maintenant, c'est de désactiver WP Rocket, mettre en place le script et réactiver WP Rocket.

Mais cela ne fonctionne pas tous le temps, j'ai souvent une erreur dans la console developpeur "Failed to load resource: the server responded with a status of 404 (Not Found)"

Quelqu'un a-t-il une solution ?

J'utilise ce script: 

<script type="text/javascript" src="https://cdn.jsdelivr.net/gh/AmauriC/tarteaucitron.js@1.3/tarteaucitron.min.js"></script>
		<script type="text/javascript">
      tarteaucitron.init({
        "privacyUrl": "", /* Privacy policy url */
        "hashtag": "#tarteaucitron", /* Open the panel with this hashtag */
        "cookieName": "tartaucitron", /* Cookie name */
        "orientation": "bottom", /* Banner position (top - bottom) */
        "showAlertSmall": true, /* Show the small banner on bottom right */
        "cookieslist": true, /* Show the cookie list */
        "adblocker": false, /* Show a Warning if an adblocker is detected */
        "AcceptAllCta" : true, /* Show the accept all button when highPrivacy on */
        "highPrivacy": false, /* Disable auto consent */
        "handleBrowserDNTRequest": false, /* If Do Not Track == 1, accept all */
        "removeCredit": false, /* Remove credit link */
        "moreInfoLink": true, /* Show more info link */
        //"cookieDomain": ".my-multisite-domaine.fr" /* Shared cookie for subdomain */
      });
    </script>

**Comment by AmauriC** [comment]
Bonjour 🙂

Il existe des options pour exclure certains scripts de la logique de wprocket.

Exclure *tarteaucitron.min.js devrait fonctionner.
