### ISSUE TITLE
Push Event on subscribe and unsubscribe

### ISSUE THREAD

**Issue by stefanKBL** [AmauriC/tarteaucitron.js#410]
I notice about #363 but how to implement this ? Inside the service ? And is the solution also available for unsubscribe ? Thanks

**Comment by nstCactus** [comment]
The `<service_name>_load` event is fired:
- when the user first gives its consent for the service
- on each page load, when the service is loaded, if the user previously gave its consent.

Here's how can listen to this event:
````js
document.addEventListener('recaptcha_loaded', function (){
    console.log('Recaptcha loaded');
});
````

Currently, I don't think there's any event dispatched when the user revokes its consent to a service. This would have little interest anyway as revoking consent triggers a page reload.
