### ISSUE TITLE
Error with reCaptcha v3

### ISSUE THREAD

**Issue by Cmbnf** [AmauriC/tarteaucitron.js#411]
Hi, 
I installed tarteaucitron following [this tutorial](https://pavenum.com/rgpd-les-cookies-dans-wordpress-divi-avec-tarteaucitron-js/) (in French), but now I have a problem with reCaptcha (v3) : when I accept the cookie, reCaptcha shows the error `ERROR for site owner: Invalid site key`.

**Comment by AmauriC** [comment]
Hi,

Recaptcha v3 is not yet supported, only V2 🥺

**Comment by Cmbnf** [comment]
OK, thanks.

**Comment by Cmbnf** [comment]
Is it planned to add support for reCaptcha v3 in the near future ?
