### ISSUE TITLE
Ne fonctionne pas et pas d'erreur

### ISSUE THREAD

**Issue by murielthoms** [AmauriC/tarteaucitron.js#414]
bonjour,
Merci pour commencer pour tarteaucitron js qui facilite la vie!! Mon problème: J'ai téléchargé tarteaucitron v1.3, tout installé correctement fichier css linké , mais absolument rien n’apparaît sur le site. Vérification dans la console et aucune erreur. Je m'arrache les cheveux car je ne trouve pas d'où ça peut venir...  Pourriez-vous m'apporté votre aide SVP?   Merci beaucoup!!
Muriel.

**Comment by yunai39** [comment]
Bonjour,

Le js est il bien inclus ? le css ? Avez vous bien appelez tarteaucitron.init ?  

Et attention, tant que aucun service n'a été ajouter a tarteaucitron, la popup de base ne sera pas affiché. Donc vous auriez le comportement que vous avez décrit.

**Comment by murielthoms** [comment]
Merci pour la réponse rapide!!! très gentil de votre part et oui, comme une andouille j'ai pas ajouté de service!!!  Je me suis arrêté à "il ne se passe rien"... Ben oui là effectivement ça va mieux!! Désolée pour le dérangement et merci de votre aide!!!!
Muriel.

**Comment by AmauriC** [comment]
Merci @yunai39 🙂👌
