### ISSUE TITLE
Tracking Google Analytics even when cookies refused

### ISSUE THREAD

**Issue by NicolasPrn** [AmauriC/tarteaucitron.js#417]
Hello,

when a user refuses cookies, GA still tracks them and when the users navigate between pages, the users data increases : it adds 1 user each time the same user loads a new page.
So my data is messed up.

I checked my installation and it seems good.
I use Google Tag Manager.

Would you have an explanation ?

**Comment by AmauriC** [comment]
Hi

If GA still track the user when the service is disable it's probably because you still have the GA tracker on your website.
