### ISSUE TITLE
Options are not taken

### ISSUE THREAD

**Issue by akyoscommunication** [AmauriC/tarteaucitron.js#428]
`tarteaucitron.init({
    "privacyUrl": "", /* Privacy policy url */

    "hashtag": "#tarteaucitron", /* Open the panel with this hashtag */
    "cookieName": "tarteaucitron", /* Cookie name */
    
    "orientation": "middle", /* Banner position (top - bottom) */
    "showAlertSmall": true, /* Show the small banner on bottom right */
    "cookieslist": true, /* Show the cookie list */

    "adblocker": false, /* Show a Warning if an adblocker is detected */
    "AcceptAllCta" : true, /* Show the accept all button when highPrivacy on */
    "highPrivacy": true, /* Disable auto consent */
    "handleBrowserDNTRequest": false, /* If Do Not Track == 1, disallow all */

    "removeCredit": false, /* Remove credit link */
    "moreInfoLink": true, /* Show more info link */
    "useExternalCss": false, /* If false, the tarteaucitron.css file will be loaded */

    //"cookieDomain": ".my-multisite-domaine.fr", /* Shared cookie for subdomain website */
                          
    "readmoreLink": "/cookiespolicy" /* Change the default readmore link pointing to opt-out.ferank.eu */
});`

Thoses options are not taken, i can't put "useExternalCss" to true, and the rest can't be changed ...

Help !

**Comment by Manoz** [comment]
Can you provide additional informations about how you're using tarteaucitron? Which version? Your complete script?

We cant help without more informations.

**Comment by akyoscommunication** [comment]
Hi! 
We use it as described on the website: link to the script and params in head tag, specifications in footer. We just add css in a separate file. Since the last commit that adds a new banner, parameters are ignored. We had to take an older version or change default options in the tarteaucitron.js script, in the load function, line 211-225 :
`defaults = {
                "adblocker": false,
                "hashtag": '#tarteaucitron',
                "cookieName": 'tarteaucitron',
                "highPrivacy": true,
                "orientation": "middle",
                "removeCredit": false,
                "showAlertSmall": false,
                "cookieslist": false,
                "handleBrowserDNTRequest": false,
                "AcceptAllCta" : true,
                "moreInfoLink": true,
                "privacyUrl": "",
                "useExternalCss": true
            },`
Thanks

**Comment by Manoz** [comment]
I'm a little busy today, I'll try to replicate your issue tonight. In the meantime can you try to load everything in your `<body>` tag? Just for testing purpose.

Like so : 

```html
<body>
    <!-- your website content -->

    <script src="/tarteaucitron/tarteaucitron.js"></script>

    <script>
      tarteaucitron.init({
        // Your options
      });

      tarteaucitron.user.YOUR_SERVICE = 'YOUR-ID';
      (tarteaucitron.job = tarteaucitron.job || []).push('your-service');
    </script>
</body>
```

**Comment by akyoscommunication** [comment]
No problem, we've fixed it and we don't update for now. Do it when you can.

Thanks


Le jeu. 16 avr. 2020 à 09:21, Kévin Legrand <notifications@github.com> a
écrit :
