### ISSUE TITLE
Prise en compte de Facebook Pixel

### ISSUE THREAD

**Issue by chaissac** [AmauriC/tarteaucitron.js#43]
Bonjour,

J'ai essayé de voir comment prendre en compte le tracker d'audience Facebook Pixel mais je m'y perds un peu.
Pour info, il y a un premier code dans le head : 
```
<!-- Facebook Pixel Code -->
<script>
	!function(f,b,e,v,n,t,s) {
		if(f.fbq) return;
		n=f.fbq=function(){
			n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments);
		};
		if(!f._fbq) f._fbq=n;
		n.push=n;
		n.loaded=!0;
		n.version='2.0';
		n.queue=[];
		t=b.createElement(e);
		t.async=!0;
		t.src=v;
		s=b.getElementsByTagName(e)[0];
		s.parentNode.insertBefore(t,s);
	} (window, document,'script', 'https://connect.facebook.net/en_US/fbevents.js');
	fbq('init', '##############');
	fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
  src="https://www.facebook.com/tr?id=##############&ev=PageView&noscript=1"
/></noscript>
<!-- End Facebook Pixel Code -->
```
Puis des marqueurs de ci delà genre : 
`	<script> fbq('track', 'Search'); </script>`
ou
`	<script> fbq('track', 'ViewContent'); </script>`
...

Merci pour ce fabuleux travail !

Philippe

**Comment by 3615Yeye** [comment]
Bonjour Philippe,

J'ai ajouté la gestion du Pixel Facebook à tarteaucitron puisqu'on se met également à l'utiliser au boulot.

J'ai fait une pull request pour que cela soit intégré à tarteaucitron, mais vous pouvez l'utiliser dès maintenant si vous voulez en mettant à jour votre fichier tarteaucitron.services.js avec le code de cette page : https://github.com/AmauriC/tarteaucitron.js/pull/46/files (ajouter uniquement les lignes vertes et sans les plus de début de ligne).

Ensuite facebook pixel ce configure comme ceci :  
` 
<script type="text/javascript">
tarteaucitron.user.facebookpixelId` = 'YOUR-ID';
tarteaucitron.user.facebookpixelMore = function () { /* add here your optionnal facebook pixel function */ };
(tarteaucitron.job = tarteaucitron.job || []).push('facebookpixel');
</script> 
`

De base seul le marqueur 	fbq('track', 'PageView'); est activé mais il est possible d'en rajouter d'autres à la place du commentaire "add here your optionnal..."

**Comment by chaissac** [comment]
Bonjour,
Merci pour ce code propre, j'avais fini par bricoler un truc à peu près semblable d'ailleurs (mais moins propre :) !).
Bonne journée

**Comment by sophiejarlier** [comment]
Bonjour,
Merci pour ces explications. Petite question: si on installe d'habitude le Pixel Facebook depuis Google Tag Manager est-ce que cela veut dire que l'on ne doit plus utiliser de balise Pixel Facebook et uniquement utiliser ce code que vous nous avez donné ci-dessous:

Ensuite facebook pixel ce configure comme ceci :
<script type="text/javascript"> tarteaucitron.user.facebookpixelId = 'YOUR-ID';
tarteaucitron.user.facebookpixelMore = function () { /* add here your optionnal facebook pixel function */ };
(tarteaucitron.job = tarteaucitron.job || []).push('facebookpixel');
</script> `

Merci

**Comment by clem983** [comment]
Bonjour,

Je ne comprends pas comment rajouter un événement facebook, par exemple "fbq('track', 'Purchase', {...})".
J'ai essayé de rajouter cette fameuse ligne dans la fonction facebookpixelMore, et d'appeler cette fonction sur ma page de confirmation. 
Mais j'ai une erreur dans la console : fbq is not defined. 
Erreur logique, mais je ne sais pas comment faire autrement. Si quelqu'un pouvait me donner l'info ... :)

Merci beaucoup :)
