### ISSUE TITLE
  scripts[i].getAttribute('src') -> indexOf('tarteaucitron') of  null

### ISSUE THREAD

**Issue by manutecon2** [AmauriC/tarteaucitron.js#432]
Hello, I've had a problem and i didn't know why tartaucitron.js was not working. It was because I had some script tags without an attribute src so the script didn't work. Could be good to check if attribute src exits:

`for (var i = 0; i <  scripts.length; ++i) {
    if(typeof scripts[i].getAttribute('src') !== 'undefined' && scripts[i].getAttribute('src') !== null){
        if ( scripts[i].getAttribute('src').indexOf('tarteaucitron') >= 0) {
            // should always find this script
            thisScript = scripts[i];
            break;
        }
    }    
    // should never happen
    throw new Error("Error: tarteaucitron.js script not found");
}`

thanks a lot for all this work. Really helpful !

**Comment by Manoz** [comment]
It's not a bad idea, but I'm not sure it's necessary. If people forget to add the src attribute to scripts it's a problem related to the user and not to the script.

Everything is explained in the "documentation", users just have to copy/paste the scripts :/
