### ISSUE TITLE
Nouvelle recommandation RGPD

### ISSUE THREAD

**Issue by umgrim** [AmauriC/tarteaucitron.js#434]
Bonjour, je travail avec mon avocate sur la conformité de mon site au RGPD, et une recommandation sur la trace des consentements utilisateurs est demandée, j'ai vu dans vos précédentes issues que vous alliez vous tenir informés par rapport à ça, mais ceci devra être appliqué sous peu.
Avez vous prévu de pouvoir les recueillir d'une manière?

Merci d'avance

**Comment by AmauriC** [comment]
Bonjour,

Non, le recueillement du consentement par le script n'est pas prévu, ça n'aurai à priori pas de valeur juridique et demanderai de stocker des informations alors que le principe du script et de limiter le stockage.

Une solution est de faire des "captures" du code source de votre site qui attestent du non chargement sans consentement de services tiers.
