### ISSUE TITLE
Tarteaucitron avec React

### ISSUE THREAD

**Issue by LilaGuill** [AmauriC/tarteaucitron.js#439]
Bonjour, je travaille sur un  projet en React, comment peut-on utiliser tarteaucitron avec React ?

**Comment by mttetc** [comment]
Je rencontre le même problème, j'ai un switcher de langue et j'essaye de tout relancer, en vain

**Comment by AmauriC** [comment]
Je ne vois comme ça pourrait être possible pour l'instant sans recharger la page : /

**Comment by kevinvuillemin** [comment]
Did you find a solution ?

I'm on nextjs.
