### ISSUE TITLE
Secure and HttpOnly Attributes

### ISSUE THREAD

**Issue by sleepinzombie** [AmauriC/tarteaucitron.js#443]
Hello,

I've been using this repository for a project, and I wanted to know if there is a way to add the `secure` and `httpOnly` attributes to cookies.

Any help would be highly appreciated.

**Comment by julienmiclo** [comment]
@sleepinzombie hello,
you can achieve this by Apache instructions.
Check if **mod_headers** is enabled and add this :
```<IfModule mod_headers.c>
# only for Apache > 2.2.4:
Header edit Set-Cookie ^(.*)$ $1;HttpOnly;Secure
# older versions :
Header set Set-Cookie HttpOnly;Secure
</IfModule>```
