### ISSUE TITLE
Update NPM repository.

### ISSUE THREAD

**Issue by devSSDA** [AmauriC/tarteaucitron.js#448]
Hi. Could you update the npm repository? Your new option "bodyPosition" is missing.

I want to change the location of the block
https://github.com/AmauriC/tarteaucitron.js/commit/b274b32bd80ddb342ce20b7316b78443313708da
but the repository was updated half a year ago
https://www.npmjs.com/package/tarteaucitronjs
`1.3.1 • Public • Published 6 months ago`

**Comment by AmauriC** [comment]
Done, 1.4.0 is ready.
