### ISSUE TITLE
Cookie vierge crée sur le domaine

### ISSUE THREAD

**Issue by PtitFils** [AmauriC/tarteaucitron.js#450]
Quand j'utilise tarteaucitron.js coté frontend et que je refuse certains services, je remarque que pour les services en questions, les cookies associés sont crées et leur contenu est vierge. 
Ces cookies vierges sont crées sur le domaine de mon site web, (ce qui peut être bien pour effacer le contenu au cas où). 
Sauf que lorsque le service est autorisé, le cookie qu'il va écrire est dans son propre domaine et non pas le mien. 
Peut être existe-il la possibilité de fournir le domaine cible du service en question ? 
Pour le moment, j'ai retiré le nom des cookies utilisés pour chaque service car je trouve ça gênant, mais cela affiche dans la liste des services à activer (panneau frontend) que le service utilise 0 cookie. Ce qui n'est pas le cas. 

Peut être que je fait quelque chose de mal ? 

Merci pour votre travail et pour votre aide.

**Comment by AmauriC** [comment]
Les cookies sont créés avec une date d'expiration au 01 Jan 2000 sur le domaine pour être sûr qu'ils n'existent plus au moment de la désactivation.

C'est le comportement voulu ;)
