### ISSUE TITLE
Rapport GTMetrix

### ISSUE THREAD

**Issue by csonrel** [AmauriC/tarteaucitron.js#451]
Bonjour, je me permets de vous écrire pour savoir si il est possible d'avoir une explication sur le chargement d'un tag qui ralentit beaucoup un de mes sites
En testant le chargement des pages avec GT metrix, je constate que TAC tente de charger des versions de langues sur le site....Avec des temps de chargement très important. 
Avez vous une explication ?
Merci
![image_2020_05_12T12_35_18_695Z](https://user-images.githubusercontent.com/45960995/81692937-71300d80-945f-11ea-95c6-d0977d2b830c.png)

**Comment by AmauriC** [comment]
Bonjour,

Le fichier langue est nécessaire au bon fonctionnement du script.

Il est hébergé sur votre serveur donc le ralentissement viens du serveur.

En refaisant un test gtmetrix même problème?
