### ISSUE TITLE
tarteaucitron.events.load

### ISSUE THREAD

**Issue by gaspardwilliam** [AmauriC/tarteaucitron.js#456]
J'essaie d'utiliser tarteaucitron.events.load pour étendre certaines fonctionnalités spécifique à mon cas, mais je n'arrive pas à accéder à tarteaucitron.lang depuis tarteaucitron.events.load , Est-ce un bug ?

**Comment by O2Graphics** [comment]
À l'étape 2 : https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.js#L259 le chargement du fichier de langue est démarré, mais cela peut prendre quelques millisecondes (voire plus si le réseau est lent), et, pendant ce temps, l'exécution du code se poursuit : on arrive donc à l'appel de load() : https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.js#L653 avant que le fichier de langue soit chargé et que tarteaucitron.lang soit utilisable.

Si ton code c'est :
```javascript
tarteaucitron.events.load = function() {
	console.log( tarteaucitron.lang );
};
```

Tu peux ajouter un timeout (valeur à adapter) :
```javascript
tarteaucitron.events.load = function() {
	setTimeout(function() {
		console.log( tarteaucitron.lang );
	}, 100);
};
```

Mais si tu veux faire propre, je te suggère de t'inspirer de "tarteaucitron.events.init" et "tarteaucitron.events.load" et de créer "tarteaucitron.events.languageLoaded" que tu appelleras par ici : https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.js#L260
ou peut-être entre ces deux lignes : https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.js#L263-L264
