### ISSUE TITLE
Ajouter une catégorie custom 

### ISSUE THREAD

**Issue by achr3f** [AmauriC/tarteaucitron.js#457]
Bonjour !  avant tout je vous félicite pour ce projet ! ça nous facilite vraiment la vie !! 

j'aimerai savoir comment peut-on rajouter une catégorie Cutsom  qui regroupe l'ensemble des cookies techniques qui sont nécessaires pour le fonctionnement du projet et qui ne demande pas l'approbation  de l'utilisateur. 

j'ai vu dans le code que vous autorisez uniquement. 
```javascript 
cat = ['ads', 'analytic', 'api', 'comment', 'social', 'support', 'video', 'other'], 
```
ou à la limite  `cat == other ` et on peut mettre un titre custom 

Voila un exemple 
<img width="668" alt="Capture d’écran 2020-05-26 à 07 16 11" src="https://user-images.githubusercontent.com/1219738/82863172-c2d99d00-9f21-11ea-94b1-4310ad26385b.png">

j'ai essayé avec un Custom service mais c'est pas le rendu attendu 

Merci pour votre réponse

**Comment by achr3f** [comment]
pour info j'utilise la version 20191031

**Comment by Manoz** [comment]
Bonjour @achr3f , cette option a été ajoutée dans e88aa287016cbcb2a8772c049c4cd12de2e1b812 :)

**Comment by achr3f** [comment]
@Manoz  thx
