### ISSUE TITLE
Invalid call to gtag(), the Global site snippet is not installed

### ISSUE THREAD

**Issue by ioweb-gr** [AmauriC/tarteaucitron.js#459]
I'm trying to install the gtag snippet through tarteaucitron but I'm getting this error when I check the tags with the Google Tag Assistant  

`Invalid call to gtag(), the Global site snippet is not installed`

![image](https://user-images.githubusercontent.com/20220341/83410276-bfad4800-a41e-11ea-8c09-3731475b5208.png)

My tarte code is 

```
    tarteaucitron.user.gtagUa = 'UA-xxxxxxxxx-1';
    tarteaucitron.user.gtagMore = function () {};
    (tarteaucitron.job = tarteaucitron.job || []).push('gtag');
```

The original marker doesn't create this error.

**Comment by pierretux** [comment]
Bonjour,

J'ai aussi le problème.
Une idée de comment corrigé cela ?

Merci

**Comment by AmauriC** [comment]
Je ne sais pas comment fonctionne Tag Assistant mais si c’est une simple recherche du code Google dans le code source du site, c’est normal qu’il ne le détecte pas puise qu’il est logiquement absent et remplacé par le marqueur tarteaucitron.

**Comment by pierretux** [comment]
Actuellement on inclus :
`<script>
  gtag('event', 'conversion', {
    'allow_custom_scripts': true,
    'send_to': 'xxxxxxx'
  });
</script>
<noscript>
<img src="https://ad.doubleclick.net/ddm/activity/src=xxxxxxx" width="1" height="1" alt=""/>
</noscript>`

Je vois pour avoir une code compatible avec le js

**Comment by pierretux** [comment]
Le nouveau code communiquer est 
`
<script type="text/javascript">
var axel = Math.random() + "";
var a = axel * 10000000000000;
document.write('<iframe src="https://ccc.fls.doubleclick.net/activityi;src=cc;type=cc;cat=cc;dc_lat=;dc_rdid=;tag_for_child_directed_treatment=;tfua=;npa=;gdpr=${GDPR};gdpr_consent=${GDPR_CONSENT_755};ord=1;num=' + a + '?" width="1" height="1" frameborder="0" style="display:none"></iframe>');
</script>
<noscript>
<iframe src="https://ccccc.fls.doubleclick.net/activityi;src=cc;type=cccc;cat=cc;dc_lat=;dc_rdid=;tag_for_child_directed_treatment=;tfua=;npa=;gdpr=${GDPR};gdpr_consent=${GDPR_CONSENT_755};ord=1;num=1?" width="1" height="1" frameborder="0" style="display:none"></iframe>
</noscript>
`
Mais du coup il n'est pas bloquer.

Quel serait la solution ?

**Comment by pierretux** [comment]
Manifestement au chargement de la page https://www.googletagmanager.com/gtag/js?id=DC-cccc arrive en fin de chargement et comment j'ai gtag en haut de page cela bloque, on peut avancer le chargement comment du services.js ?

**Comment by pierretux** [comment]
@AmauriC comment debogu ou comprendre ce qui ne va pas ?

**Comment by AmauriC** [comment]
> Actuellement on inclus :
> `<script> gtag('event', 'conversion', { 'allow_custom_scripts': true, 'send_to': 'xxxxxxx' }); </script> <noscript> <img src="https://ad.doubleclick.net/ddm/activity/src=xxxxxxx" width="1" height="1" alt=""/> </noscript>`
> 
> Je vois pour avoir une code compatible avec le js

La version tarteaucitron c'est donc:

```
tarteaucitron.user.gtagUa = 'UA-xxxxxxxxx-1';
tarteaucitron.user.gtagMore = function () {
    window.gtag('event', 'conversion', { 'allow_custom_scripts': true, 'send_to': 'xxxxxxx' });
};
(tarteaucitron.job = tarteaucitron.job || []).push('gtag');
```

**Comment by pierretux** [comment]
Merci pour ton retour.
Mais comment faire avec 'send_to': 'xxxxxxx' qui est différents sur 2 pages ? je peux avoir plusieurs fois ça dans le site en fait

**Comment by AmauriC** [comment]
Oui, à ajouter sur les pages où il y a besoin de ce tracker.
