### ISSUE TITLE
Perte de trafic sur Google Analytics depuis l'installation de tarteaucitron

### ISSUE THREAD

**Issue by webmasterV** [AmauriC/tarteaucitron.js#461]
Bonjour Amauric

Depuis l'installation de TAC sur notre usine à sites Drupal 7, nous constatons une très forte diminution du trafic enregistré dans Google Analytics (divisé par 5). Comme nous respectons scrupuleusement les recommandations de la CNIL (pas de cookie écrit sans consentement ou refus de consentement) et bandeau de consentement très discret, les internautes sont peu nombreux à cliquer sur le bandeau.
Nous avons essayé d'anonymisé le trafic mais cela ne change rien.
Est-ce qu'il y a une solution (hormis utiliser Piwik :) ) ?

**Comment by AmauriC** [comment]
Bonjour,

Malheureusement non, pas vraiment de solution.

Le taux d'acceptation est assez faible (aux alentours de 30% sur https://tarteaucitron.io/).

Utiliser une solution sans consentement (piwik, at internet) est une alternative ; )

**Comment by webmasterV** [comment]
Merci AmauriC pour votre réponse rapide :)

Voilà qui ne va pas faire plaisir aux marketeurs mais on va quand même essayer Piwik.
