### ISSUE TITLE
tarteaucitron.js cree un cookie par défaut 

### ISSUE THREAD

**Issue by semantiqueweb** [AmauriC/tarteaucitron.js#47]
Bonjour

Sauf erreur ce très bon js créé son propre cookie mais celui ci n'est pas remonté dans la liste que l'internaute peut accepter/refuser, cela me semble étrange, non ? 

Merci en tout cas pour ce joli travail.

**Comment by AmauriC** [comment]
Bonjour,

Tous les cookies n'ont pas besoin d'autorisation, seul ceux ayant un but de tracage le sont.

Les cookies concernant les espaces membres, les préférences utilisateur (comme tarteaucitron), la sécurité, la repartition de la charge serveur, ... ne posent pas problème.
