### ISSUE TITLE
Refus des cookies en "orientation": "bottom"

### ISSUE THREAD

**Issue by PhilippeTrp** [AmauriC/tarteaucitron.js#470]
Le bouton "Tout refuser" ne s'affiche que sur la modal en mettant l'orientation à "middle", serait-il possible de pouvoir l'afficher même avec l'orientation à "top" ou "bottom" ? Cela permettrait d'être 100% RGPD friendly :)

**Comment by Sylry** [comment]
I added an option to be able to choose to display this button in #480 PR
