### ISSUE TITLE
Matomo Tag Manager integration

### ISSUE THREAD

**Issue by Chardonneaur** [AmauriC/tarteaucitron.js#471]
Hi there,
So as Google with Google Tag Manager, Matomo has also a Tag Manager.
The tracking code looks like this:

<script type="text/javascript">
var _mtm = _mtm || [];
_mtm.push({'mtm.startTime': (new Date().getTime()), 'event': 'mtm.Start'});
var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
g.type='text/javascript'; g.async=true; g.defer=true; g.src='http://your-instance.com/matomo/js/container_YourID.js'; s.parentNode.insertBefore(g,s);
</script>

It would be nice to integrate it.

**Comment by matmicro** [comment]
Hi,
Any chance to integrate this ?

How then Tarteaucitron script will display all consent button, and block javascript until the customer acknowledge it ?

Regards
