### ISSUE TITLE
Webpack issues (tarteaucitron is not defined)

### ISSUE THREAD

**Issue by geekthought** [AmauriC/tarteaucitron.js#473]
Hi there, 

i tried to add tarteaucitron.js to my webpack config but it doesn't seem to work. When compiled i get "tarteaucitron is not defined" for the build. If i manually add tarteaucitron.js to the head section it works. I added these import statements to my index.js. 

`import 'tarteaucitronjs/tarteaucitron';`
`import 'tarteaucitronjs/tarteaucitron.services';`
`import 'tarteaucitronjs/advertising';`

Any hints on this issues are greatly appreciated.

**Comment by TheMechanic** [comment]
Hi, totally normal, as these files don't export anything...

**Comment by mdevlamynck** [comment]
It seems like tarteaucitron.js is missing a `module.exports = tarteaucitron;` to be compatible with webpack (and everything else compatible with CommonJs modules).
