### ISSUE TITLE
Uncaught TypeError: tarteaucitron.user.multiplegtagUa.forEach is not a function

### ISSUE THREAD

**Issue by Dadox** [AmauriC/tarteaucitron.js#474]
Got this error with last release

Uncaught TypeError: tarteaucitron.user.multiplegtagUa.forEach is not a function
Line 2660

I temporary fix by adding 
`&& tarteaucitron.user.multiplegtagUa !== ""`
in the condition

**Comment by Cyrille37** [comment]
Same error in "google analytics multiple" in `tarteaucitron.services.multiplegtag`.

- file `/wp-content/plugins/wp-tarteaucitron-js-self-hosted/js/tarteaucitron/tarteaucitron.services.js?v=20191031`
- line 2543
