### ISSUE TITLE
Service personnalisées et Lien en Savoir Plus

### ISSUE THREAD

**Issue by csonrel** [AmauriC/tarteaucitron.js#479]
Bonjour Amauri, 
Nous avons un petit problème avec la configuration de Tarte au citron.
Nous utilisons en effet GTM pour les tags et nous avons donc utilisés la personnalisation des services pour générer des services fictifs (mais fonctionnels).
Cependant, lors de l'ouverture du panel de gestion des cookies, il y a sous chaque service un lien "en savoir plus" et -site officiel".
Site Officiel fonctionne très bien, car il récupère "URI" du service personnalisé, mais par contre le lien "en savoir plus" se construit avec la clé du service ! Et du coup, on pointe vers des pages 404 de vos services.
Comment faire pour conserver le site officiel, mais pas le "en savoir plus" ?
Le tout dans une version payante.
Merci

**Comment by f-to** [comment]
Il y a pour ça l'attribut "readmoreLink" pour indiquer une URL dans un service personnalisé.
