### ISSUE TITLE
Prise en compte Facebook Messenger Customer Chat

### ISSUE THREAD

**Issue by uman-fr** [AmauriC/tarteaucitron.js#48]
Bonjour,
Tout d'abord félicitations à Amauri pour ce superbe développement que je découvre un peu tardivement avec l'arrivée de la RGPD...

Je voulais savoir s' il était possible d'ajouter dans les services la gestion des cookies déposés par le plugin Facebook Messenger Customer Chat.

Merci d'avance pour votre collaboration.

**Comment by shirokoweb** [comment]
Salut @AmauriC 

Actuellement, nous utilisons les conteneurs Google Tag Manager (GTM) pour déployer rapidement tarteaucitron.js sur nos sites.

Aurais-tu un ETA concernant la demande d' @uman-fr pour l'ajout du service FB Chat ?

Le code est assez simple :

```
<script>
(function() {
    // Modify the variable values below
    var page_id = '{{FB - PageID}}';
    var ref = '';
    var theme_color = '{{FBChat - ThemeColor}}';
    var logged_in_greeting = 'Hello! Comment pouvons-nous vous aider ?';
    var logged_out_greeting = 'Hello! Nous répondons à vos questions :)';

    // Don't touch the code below
    var el = document.createElement('div');
    el.className = 'fb-customerchat';
    el.setAttribute('page_id', page_id);
    if (ref.length) {
        el.setAttribute('ref', ref);
    }
    el.setAttribute('theme_color', theme_color);
    el.setAttribute('logged_in_greeting', logged_in_greeting);
    el.setAttribute('logged_out_greeting', logged_out_greeting);
    document.body.appendChild(el);
})();
  
  // Load SDK
    window.fbAsyncInit = function() {
    FB.init({
      appId      : '{{FB - AppID}}',
      xfbml      : true,
      version    : 'v3.0'
    });
    FB.AppEvents.logPageView();
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "https://connect.facebook.net/fr_FR/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
```
L'avoir dans la repo tarteaucitron.js serait un grand plus vu la popularité de ce service. Cdt

**Comment by uman-fr** [comment]
Bonjour,
J'ai ajouté ceci dans tarteaucitron.services.js mais je n'ai pas l'impression que les cookies déposés sont détectés dans l'interface de gestion des cookies de tarteaucitron...
Merci de votre aide.
```
// facebookcustomerchat
tarteaucitron.services.facebookcustomerchat = {
    "key": "facebookcustomerchat",
    "type": "social",
    "name": "Facebook (Customer Chat)",
    "uri": "https://www.facebook.com/policies/cookies/",
    "needConsent": true,
    "cookies": ['act','c_user','datr','dpr','fr','locale','pl','presence','sb','wd','xs','/tr'],
    "js": function () {
        "use strict";
        tarteaucitron.fallback(['fb-customerchat'], '');
	window.fbAsyncInit=function(){FB.init({appId:"xxxxxxxxxxxxxxx",autoLogAppEvents:!0,xfbml:!0,version:"v3.0"})};
	tarteaucitron.addScript('https://connect.facebook.net/' + tarteaucitron.getLocale() + '/sdk/xfbml.customerchat.js', 'facebook-jssdk');
    },
    "fallback": function () {
        "use strict";
        var id = 'facebookcustomerchat';
        tarteaucitron.fallback(['fb-customerchat'], tarteaucitron.engage(id));
    }
};
```
`````

**Comment by Alex360hd** [comment]
+1

D'autant plus que le fait d'intégrer le customer chat (normalement, pas via tarteaucitron car pas supporté) fait planté la facebook like box (intégrée via tarteaucitron).

Le fait de supprimer le code lié au facebook chat fait refonctionner instantanément la likebox.

**Comment by thomascz001** [comment]
Bonjour,

Quelq'un a des avancées à ce sujet ? ça serait dommage de désactiver la gestion de la fonctionnalité facebook like par tarteaucitron pour pouvoir intégrer la chatbox messenger !

Quel choix avez-vous fait pour l'instant ?
