### ISSUE TITLE
Comment utiliser ce custom service de Tarte au Citron depuis Google Tag Manager

### ISSUE THREAD

**Issue by sophiejarlier** [AmauriC/tarteaucitron.js#484]
Bonjour Amauri, bonjour à tous,

J'utilise Google Tag Manager pour gérer les tags sur mon site (google analytics, pixel facebook, clics vers des liens externes et internes etc.). Je tente de comprendre si je peux utiliser Tarte au Citron pour activer ces tags ou non en fonction des cookies acceptés ou non.

S'il vous plait pourriez-vous m'indiquer si je pars dans la bonne direction: il faudrait que je fasse un custom service qui définit mes différentes sortes de cookies (audience, reseaux sociaux etc.) et ensuite pour mes tags (balises) dans GTM je rajoute une exception quand ces cookies sont refusés.. c'est bien ça?

Mais dans l'implémentation de ce service, mes différentes sortes de cookies seraient définies dans "type", "cookies" correspondrait à quoi? des noms de variables pour chaque type de cookies? Il faut remplir aussi quand un utilisateur refuse et accepte?

tarteaucitron.services.mycustomservice = {
  "key": "mycustomservice",
  "type": "ads|analytic|api|comment|other|social|support|video",
  "name": "MyCustomService",
  "needConsent": true,
  "cookies": ['cookie', 'cookie2'],
  "readmoreLink": "/custom_read_more", // If you want to change readmore link
  "js": function () {
    "use strict";
    // When user allow cookie
  },
  "fallback": function () {
    "use strict";
    // when use deny cookie
  }
};

Dans ce cas je n'ai plus besoin de faire de push?

Merci pour votre aide
Sophie

**Comment by BuyukCem** [comment]
Bonjour, 
Selon moi j'aurais appelé Google Tag Manager quoi qu'il arrive quel que soit le consentement de l'utilisateur, Ce n'est pas un problème car GTM n'inclut aucun cookie sur le site Web.
La technique consiste à utiliser Custom HTML Template pour appeler ses balises via tarteaucitron directement dans GTM.

Par exemple pour Google Analytics voici ce que j'aurais fais:
<script type="text/javascript"> 
        tarteaucitron.user.gajsUa = 'UA-XXXXXX'; 
        tarteaucitron.user.gajsMore = function () { /* add here your optionnal _ga.push() */ }; 
        (tarteaucitron.job = tarteaucitron.job || []).push('gajs'); 

</script>
