### ISSUE TITLE
Cookie tiers : SameSite attribute

### ISSUE THREAD

**Issue by benjaminumc** [AmauriC/tarteaucitron.js#486]
Bonjour,

Est-ce que quelque chose va être mis en place pour que nous puissions gérer le SameSite attribute sur les cookies ?
Notre agence web nous informe que sans ça, nous sommes bloqués.

D'avance merci

**Comment by AmauriC** [comment]
Bonjour,

Si vous avez une solution à proposer, n'hésitez pas ; )

**Comment by benjaminumc** [comment]
Celle proposée ici ne convient-elle pas ?
https://github.com/AmauriC/tarteaucitron.js/issues/460

**Comment by AmauriC** [comment]
Pour le cookie tarteaucitron oui mais pas le cookie _ga par exemple, c'est à Google de faire ce changement.

**Comment by benjaminumc** [comment]
merci. Ce lien pourra peut-être aider pour gérer GA.
https://www.simoahava.com/analytics/cookieflags-field-google-analytics/
