### ISSUE TITLE
cookie non connu (inconnu)

### ISSUE THREAD

**Issue by pierretux** [AmauriC/tarteaucitron.js#487]
Bonjour,

Comment sont géré les cookie non connu par le projet ?
Je cherche à savoir si il sont bloqué automatiquement ou si son visible sur le site. Par exemple : flickr qui pose un cookie quand on l'utilise sur notre site.

Cdt.

**Comment by AmauriC** [comment]
Les cookies non connus ne sont pas gérés.

Si il en manque sur certains services, n'hésitez pas à le signaler ; )
