### ISSUE TITLE
Firefox complains about the use of the non standard property “zoom”

### ISSUE THREAD

**Issue by sandbava** [AmauriC/tarteaucitron.js#488]
In the console Firefox says :
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.

This is due to tarteaucitron.css line 139 :
#tarteaucitron * {
    zoom: 1;
}

**Comment by Klemart3D** [comment]
PR: https://github.com/AmauriC/tarteaucitron.js/pull/517

**Comment by AmauriC** [comment]
I dont know why this was still here 🧐
Thanks!
