### ISSUE TITLE
Is tarteaucitron TCF V2 compliant ?

### ISSUE THREAD

**Issue by TakeshiDaveau** [AmauriC/tarteaucitron.js#489]
Hello,

TCF V2 has been launched, and the CNIL want it to be implemented on website.

I didn't see anything about TCF V2 here, is it compatible ? 

Thanks in advance

**Comment by AmauriC** [comment]
Hey

I dont know how work TCF but it's not supposed to handle by itself the consent?

**Comment by eldk** [comment]
Hello @TakeshiDaveau 

Should you give a link for "TCF V2 has been launched, and the CNIL want it to be implemented on website". I can't find any mention of this on cnil website : https://www.google.com/search?biw=1920&bih=988&ei=cPRHX9-0F8fQaIXcgPAG&q=TCF%20site%3Acnil.fr&oq=cnil&gs_lcp=CgZwc3ktYWIQAzIHCAAQsQMQQzICCAAyAggAMgIIADICCAAyAggAMgIIADICCAAyAggAMgIIADoECAAQQzoFCAAQsQM6CAgAELEDEIMBOgoIABCxAxCDARBDOgUILhCxAzoCCC5KBQgKEgE0UPpYWMNjYM1uaABwAHgAgAGwAYgB9wOSAQMwLjSYAQCgAQGqAQdnd3Mtd2l6wAEB&sclient=psy-ab&ved=2ahUKEwjfrN-M-7vrAhVHKBoKHQUuAG4Q2wF6BAgFEAE&uact=5

Thanks,

Eric
