### ISSUE TITLE
erreur gtagua

### ISSUE THREAD

**Issue by sylvaindollinger** [AmauriC/tarteaucitron.js#49]
bonjour il y'a une erreur si 
tarteaucitron.user.gtagUa is undefined
tarteaucitron.services.js:826:90

**Comment by AmauriC** [comment]
Bonjour,

Il faut que cette variable existe, sinon le script google ne fonctionnera pas.

Il faut la définir avant l'initialisation:

        <script type="text/javascript">
        tarteaucitron.user.gtagUa = '**UA-XXXXXXXX-X**';
        tarteaucitron.user.gtagMore = function () { /* add here your optionnal gtag() */ };
        (tarteaucitron.job = tarteaucitron.job || []).push('gtag');
        </script>

**Comment by element303** [comment]
Bonjour,

j'utilise le service 'analytics' mais j'avais quand même l'erreur de la variable 'gtagUa' non défini.

J'ai corrigé comme ça : 

tarteaucitron.user.gtagUa = '**UA-XXXXXXXX-X**';
tarteaucitron.user.analyticsUa = '**UA-XXXXXXXX-X**';
tarteaucitron.user.analyticsMore = function () { /* add here your optionnal ga.push() */ };
(tarteaucitron.job = tarteaucitron.job || []).push('analytics');

peut-être une petite erreur sur cette variable à corriger à la prochaine version...
Merci pour ce travail :)

**Comment by GRUXXKi** [comment]
Je viens d'avoir le même problème juste à l'installation alors que je n'utilise pas (encore...) google analytics pour le site en cours de création. 

Merci pour le super travail, je n'étais pas motivé pour faire ce rajout et ça m'a fait gagner beaucoup de temps !

**Comment by AmauriC** [comment]
C'est corrigé ;)

**Comment by element303** [comment]
bien joué ! merci !

**Comment by GRUXXKi** [comment]
Çà marche pour moi également !
