### ISSUE TITLE
La bannière ne ce ferme pas à l'acceptation des cookies

### ISSUE THREAD

**Issue by cyprienfiquet-proxiad** [AmauriC/tarteaucitron.js#490]
Bonjour, 

J'utilise tarteaucitron via le site internet tarteaucirton.io et j'implémente la gestion des cookies grâce à la balise script fourni dans le guide d'installation.
Cependant lorsque je clique sur "Ok, accepter tout" la bannière ne ce ferme pas alors que les "hit" sont bien présents dans l'interface de statistique.
Comment régler ce problème ?

Merci d'avance.

**Comment by AmauriC** [comment]
Bonjour,

Quel est l'adresse du site?

**Comment by cyprienfiquet-proxiad** [comment]
Le site est encore en développement, je ne peux donc pas vous fournir d'adresse...

**Comment by AmauriC** [comment]
Ca va être plus difficile de vous aider.

Pas d'erreur dans la console JS?

**Comment by cyprienfiquet-proxiad** [comment]
Aucune erreur dans la console js, les statistiques remontent correctement dans l'onglet statistique.
J'utilise tarteaucitron sur un drupal 8

**Comment by cyprienfiquet-proxiad** [comment]
J'ai réussi à vous obtenir l'adresse du site en développement, comment puis-je vous l'envoyer en message privé ?

**Comment by AmauriC** [comment]
amauri@champeaux.fr
