### ISSUE TITLE
Je n'arrive pas à bloqer les cookies avec le service custom

### ISSUE THREAD

**Issue by NicolasT18** [AmauriC/tarteaucitron.js#496]
> Bonjour,

J'ai un petit soucis avec les services custom, je ne sais juste pas comment sa fonctionne pour bloquer les cookies :/

Pour essayer j'ai d'abord juste écrit le code de base donné sur le le repo et j'ai remplacer les cookies par le nom des cookies enregistrer par l'api que j'utilise : 

`tarteaucitron.services.mycustomservice = {

  "key": "mycustomservice",
  "type": "api",
  "name": "MyCustomService",
  "needConsent": true,
  "cookies": ['src', 'ssid'],
  "readmoreLink": "/custom_read_more", // If you want to change readmore link
  "js": function () {
    "use strict";
    // When user allow cookie
  },
  "fallback": function () {
    "use strict";
    // when use deny cookie
  }
};
(tarteaucitron.job = tarteaucitron.job || []).push('mycustomservice');`

Je penser que les cookies était bloqué a partire du moment ou on les mettait dans le tableau "cookies" et que les fonction était juste la en cas de besoin mais sa n'a pas fonctionner alors j'ai retenté comme sa (même si je me doutais que sa allez pas marcher)

`tarteaucitron.services.mycustomservice = {

  "key": "mycustomservice",
  "type": "api",
  "name": "MyCustomService",
  "needConsent": true,
  "cookies": ['src', 'ssid'],
  "readmoreLink": "/custom_read_more", // If you want to change readmore link
  "js": function () {
    "use strict";
    tarteaucitron.fallback(['test'], function (x) {
        return '<script type="text/javascript" src="https://www.paypalobjects.com/api/checkout.js"></script>';
    });
  },
  "fallback": function () {
    "use strict";
    var id = 'test';
	tarteaucitron.fallback(['test'], function (elem) {
	return tarteaucitron.engage(id);
    });
  }
};
(tarteaucitron.job = tarteaucitron.job || []).push('mycustomservice');`

C'était un peut évident que le script serait jamais lu mais j'ai essayé quand même et les cookies n'apparaissent pour le coups jamais puisque l'api est jamais lu même quand c'est accepté x)
(je précise que la div 'test' est bien présente et fonctionnel, je vois le code de tarteaucitron quand je refuse le cookies)

Voilà si quelqu'un peut juste m'expliquer comment sa fonctionne pour bloquer les cookies sa me serait utile merci :)

**Comment by AmauriC** [comment]
Normal que ça ne fonctionne pas cette façon de charger le JS après acceptation, il y a une fonction prévue pour le faire à la place d'utiliser la function fallback:

```
    "js": function () {
        tarteaucitron.addScript('https://www.paypalobjects.com/api/checkout.js');
    }
```

**Comment by NicolasT18** [comment]
Merci pour la réponse rapide :)
Tu viens de répondre a la minute ou j'ai trouvé la solution ici https://github.com/AmauriC/tarteaucitron.js/issues/419
J'étais revenue dire que j'avais trouvé x)

**Comment by NicolasT18** [comment]
Enfin maintenant j'ai la réponse mais visiblement je l'utilise mal car j'ai écrit sa :

"js": function () {
	"use strict";
	tarteaucitron.addScript('https://www.paypalobjects.com/api/checkout.js');
}

et le script ne se charge pas mêms si j'accepte le cookies ^^'

**Comment by AmauriC** [comment]
Ce sera mieux comme ça pour vérifier "paypal":

```
tarteaucitron.addScript('https://www.paypalobjects.com/api/checkout.js', '', function () {

   if (typeof paypal !== 'undefined') {
   } else {
      alert('test');
   }

});
```

**Comment by NicolasT18** [comment]
OOOH, 

je l'avais écrit de la même façons que c'était écrit dans le poste ou j'ai trouvé la première réponse et la fonction n'était jamais lu mais il n'y avait pas le paramètre vide avant la fonction, et maintenant sa marche !

Merci encore pour tes réponses rapides et surtout merci pour la conception de tarteaucitron ! :)

Du coup juste deux dernière question:

1. Quand j'accepte les cookies, sa indique "Ce service n'a déposé aucun cookie.", alors que j'ai bien mit les cookies dans le tableau cookies et qu'il sont bien présent dans mon navigateur, il y a une étape en plus pour que tarteaucitron affiche les cookies inscrit ?

2. Je n'ai pas trouvé de documentation pour les servicecustom (hormis la fonction de base donné sur le repo), il n'en existe pas ou j'ai très mal chercher ?

**Comment by AmauriC** [comment]
Il faut faire la différence entre les cookies posé sur le site et qui sont visible par tarteaucitron et les cookies tiers posés sur le domaine paypal.com qui ne sont pas lisible par tarteaucitron, je pense que la confusion viens de là ;) 

Pas plus de doc pour les services custom :|

**Comment by NicolasT18** [comment]
Oui je me disait bien que c'était à cause de sa :/  j'ai bien un domaine suplémentaire appelé https://www.sandbox.paypal.com mais comme les cookies présent dessus sont également afficher sur le domaine du site je me suis dit qu'ils serait accessibles avec de la chance x)

Pour ce qui est de la doc il y a possibilité d'aider de ce cotès ? ^^
Comme tu peut le voir même si j'utilise tarteaucitron depuis un moment c'est la première fois que je crée un service custom donc je pense pas être le mieux placer pour crée une documentation complète.

En revanche si je peut au moins proposé de documenter les quelques fonctions de base que je viens d'apprendre je pense que sa pourrait aider des personnes ^^

**Comment by AmauriC** [comment]
Oui bien sûr, toute aide est la bienvenue : p

Pour la déclaration des variables, c'est la bonne façon de faire.

Exemple pour Google Analytics:

```
<script type="text/javascript">
tarteaucitron.user.gtagUa = 'UA-XXXXXXXX-X';
tarteaucitron.user.gtagMore = function () { /* add here your optionnal gtag() */ };
(tarteaucitron.job = tarteaucitron.job || []).push('gtag');
</script>
```

**Comment by NicolasT18** [comment]
Okok je pense en écrire un peut ce soir ou demain :)
Si je fait un peut de doc j'écrit sa dans la partie [wiki du repo](https://github.com/AmauriC/tarteaucitron.js/wiki) ? 

Tu as dit que je l'ai fait de la bonne façon mais dans ton exemples tu place tes variables dans tarteaucitron.user alors que moi je les avait mis directement dans tarteaucitron,  sa veut dire que user et reserver au variable gtag ou alorsj'aurais plutôt du faire comme sa :

```
<script type="text/javascript">
tarteaucitron.user.paypalEnv = '<?= $paypal->paypalEnv ?>';
tarteaucitron.user.paypalClientID = '<?= $paypal->paypalClientID ?>';
</script>
```

**Comment by AmauriC** [comment]
Dans le wiki ce sera parfait!

le .user. c'est pour que ce soit plus cohérent avec le reste des services mais si c'est juste pour ton usage, pas de différence ; )

**Comment by NicolasT18** [comment]
ok pas de souci

Je n'ai enfin plus de question je vais clore le sujet encore merci pour tes réponses et ta réactivité malgré mes nombreuses questions :)

et un gros gg pour tarteaucitron ! je pense publier un morceau de doc demain :)

**Comment by alhazred-abdoullah** [comment]
j'ai le même problème je n'arrive pas a retrouver la méthode qui bloque les cookies , les éléments visuel sont la , mais le fonctionnel qui est le blocage des  cookies ne fonctionne pas , pouvez vous svp m’aider sur ce point ?

**Comment by AmauriC** [comment]
tarteaucitron ne bloque pas les cookies, tarteaucitron s'occupe de charger le service quand l'utilisateur donne son autorisation, c'est différent ; )

Bloquer uniquement les cookies n'aurait aucun intéret, si par exemple, google analytics est chargé sur le site, que les cookies soit supprimés à chaque fois ou non, des infos sont envoyées à google.
