### ISSUE TITLE
Activer un bouton "Tout refuser" dans le bandeau 

### ISSUE THREAD

**Issue by GaelleGu** [AmauriC/tarteaucitron.js#498]
Bonjour Amauri, bonjour à tous

La CNIL a adopté les lignes directrices et recommandations relatives aux cookies dans le Journal Officiel du 2 octobre 2020. https://www.dalloz-actualite.fr/flash/cookies-et-autres-traceurs-lignes-directrices-et-recommandations-de-cnil#.X32vW2gzZPY

Parmi les nouvelles obligations des sites web : permettre de signifier son refus des cookies aussi facilement que son consentement. Il s'agit de proposer à l'internaute un bouton "Tout refuser" dans le bandeau synthétique, en complément du bouton "Tout accepter" (cf article 2.4 des recommandations sur https://www.dalloz-actualite.fr/sites/dalloz-actualite.fr/files/resources/2020/10/2020-092.pdf) 

Sur le site https://tarteaucitron.io/ ce bouton apparaît déjà dans le bandeau. Pourtant je ne le trouve pas dans les options proposées sur notre compte pour appliquer le même principe à nos sites web. Pouvez-vous me dire comment activer ce bouton "tout refuser" ? 

Merci d'avance

**Comment by AmauriC** [comment]
Bonjour : )

Ca arrive dans la semaine le temps de terminer les derniers tests pour tous les comptes pro 👍
C'est déjà dispo sur github pour la version manuelle.

**Comment by GaelleGu** [comment]
Bonjour Amauri. Merci pour votre réponse. En effet, je vois que cette évolution a été mise en production. C'est super !👍

Je vois qu'il y a 2 retours à la ligne (<br>) qui séparent la ligne contenant les boutons Acceptation / Refus de la ligne contenant les autres liens, ce qui fait que le bandeau prend plus de hauteur qu'avant. Est-il possible de n'avoir qu'un seul retour à la ligne (quitte à personnaliser ensuite l'espacement via des margin ou padding via les "Custom CSS rules") ?

Bonne journée :)

**Comment by AmauriC** [comment]
C'est corrigé, merci pour l'info! 👍
