### ISSUE TITLE
modification du consentement

### ISSUE THREAD

**Issue by julienstuder** [AmauriC/tarteaucitron.js#50]
Bonjour,

dans la nouvelle loi RGPD il est stipulé que le visiteur doit pouvoir modifier son consentement ultérieurement. 
Est-ce que tarteaucitron gère cette problématique ?

Merci !

**Comment by AmauriC** [comment]
Bonjour

Oui bien sur, l'utilisateur à la possibilité de tout modifier à tout moment.


-------- Message d'origine --------
De : julienstuder <notifications@github.com>
Date : 01/03/2018 11:53 (GMT+01:00)
À : "AmauriC/tarteaucitron.js" <tarteaucitron.js@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [AmauriC/tarteaucitron.js] modification du consentement (#50)


Bonjour,

dans la nouvelle loi RGPD il est stipulé que le visiteur doit pouvoir modifier son consentement ultérieurement.
Est-ce que tarteaucitron gère cette problématique ?

Merci !

**Comment by julienstuder** [comment]
ok merci bcp !

**Comment by AmauriC** [comment]
A vrai dire je ne sais pas, je n'ai pas encore vraiment mis le nez dans la RGPD mais pour ce qui concerne les cookies, c'est tout à fait ok, c'est ce qu'utilise la CNIL sur son propre site.


Le script étant auto hébergé, je ne vois d'où viendrait une incompatibilité ;)

________________________________
De : julienstuder <notifications@github.com>
Envoyé : jeudi 1 mars 2018 16:00:13
À : AmauriC/tarteaucitron.js
Cc : Amauri Champeaux; Comment
Objet : Re: [AmauriC/tarteaucitron.js] modification du consentement (#50)


est-ce que tarteaucitron est 100% compatible avec la RGPD en l'état actuel ?
