### ISSUE TITLE
Nouvelle documentation 😀

### ISSUE THREAD

**Issue by NicolasT18** [AmauriC/tarteaucitron.js#500]
Bonjour, 

après en avoir discuté avec AmauriC ici https://github.com/AmauriC/tarteaucitron.js/issues/496, j'ai pris la décision d'écrire une documentation pour aider les personnes qui commencent avec tarteaucitron.js 😁

Du coup voilà c'est dispo sur le wiki de [github avec ce lien ! 📔](https://github.com/AmauriC/tarteaucitron.js/wiki)
J'ai directement fait une version anglaise et française comme ça, pas de jaloux :)

Si vous avez des améliorations à proposer, n'hésitez pas, tout aide et la bienvenue.
Par contre, vous pouvez corriger mais soyez quand même indulgent avec les fautes, j'ai fait attention mais la plupart de la doc à été écrit entre 00h et 4h du matin 😅 (déjà que je ne suis pas un monstre en orthographe de base).

C'est préciser dans la documentation mais je reprécise ici :
Je n'ai pas documenté le plugin wordpress ni l'installation avec npm car je ne l'ai ais pas utilisé (cependant la partie sur npm devrait voir le jour dans un petit moment car je vais bientôt commencer un projet avec npm et j'aurais besoin de tarteaucitron).

Et elle va sûrement subire de légère modification dans la semaine pour la rendre plus "attirante".

Voilà, Voilà, c'est tout !

**Comment by AmauriC** [comment]
Super! MERCI 👍 

Au week-end je ferrai une relecture complète ; )

**Comment by NicolasT18** [comment]
Pas de souci si ça peut aider des personnes :)

J'en profite que tu réponde pour poser une petite question 😁

J'ai vu sur l'issue https://github.com/AmauriC/tarteaucitron.js/issues/240 que l'intégration à npm été pas encore tout à fait au point (sa date de 2018 mais je n'ai pas trouvé d'info plus récente concernant ce problème), voilà juste pour savoir si le souci et toujours d'actualité ?


Comme je compte m'en servir bientôt et développer la doc sur ce point sa me serait utile de savoir.

**Comment by AmauriC** [comment]
Je n'utilise pas NPM mais vu le compteur de téléchargement, je suppose que ça fonctionne plutôt bien ^^
https://www.npmjs.com/package/tarteaucitronjs

**Comment by NicolasT18** [comment]
Oui en effet c'est plutôt un bonne indiquateur !

**Comment by mttetc** [comment]
Merci !
Savez vous comment reinit la lib sans rechargement de page (pour des projets sur react, vue...) ?

**Comment by NicolasT18** [comment]
@mttetc pour reinitialiser la lib il faut supprimer le cookie tarteaucitron, tu peut le faire avec du js.

Mais tarteaucitron ne prendra en compte la reinitialisation que à l'actualisation de la page, si tu veut que sa prenne effet actualiser la page, le plus simple selon mois c'est de mettre l'implémentation de tarteaucitron dans un composant et de recharger se composant après avoir supprimé le cookie.

**Comment by mttetc** [comment]
J'ai bien tenté quelque chose du style, mais la doc étant si mince, je teste les fonctions à tatons (là l'élément se recréé bien dans le DOM mais s'affiche pas et surtout y a rien dans la popin de contrôle)

`			if (document.querySelector('#tarteaucitronRoot')) {
				window.tarteaucitron.cookie.purge(['youtubeapi, gtag']);
				document.querySelector('#tarteaucitronRoot').remove();
			}

			if (window.tarteaucitron.state.length == 0) {
				setTimeout(() => {
					window.tarteaucitron.load();
					window.tarteaucitron.init({
						"privacyUrl": "",
						"hashtag": "#rgpd",
						"cookieName": "tartaucitron",
						"orientation": "bottom",
						"showAlertSmall": false,
						"cookieslist": true,
						"adblocker": false,
						"AcceptAllCta": true,
						"highPrivacy": true,
						"handleBrowserDNTRequest": false,
						"removeCredit": true,
						"moreInfoLink": true,
						"useExternalCss": true
					});
				}, 1000)
			}
		`

**Comment by NicolasT18** [comment]
Mmmh c'est compliqué à dire mais en effet je ne pense pas que cela fonctionne comme sa ^^'

En ce qui concerne la documentation elle vient tout juste d'être écrite laisse lui le temps de se développer :)

À mon avis tu devrais carrément essayez de supprimer l'objet tarteaucitron et recharger le script à nouveau mais je suis pas sur que sa marche et comme j'ai dit plus haut je n'ai pas encore utilisé tarteaucitron avec npm donc difficile de t'aider

**Comment by hoprikoma** [comment]
Bonjour,
J'aimerais savoir l'initialisation au niveau de NPM, aux dernières nouvelles la documentation était en train d'être écrite, aujourd'hui elle n'est toujours pas complète et encore moins sur l'initialisation de NPM comme écrit plus haut.
Tout le monde se demande comment ça fonctionne mais à chaque fois personne à de réponse, même si les téléchargement sont haut sur NPM apparemment beaucoup de monde à du mal avec, ce serait bien d'expliquer ce point.
Merci

**Comment by seekode** [comment]
Bonjour @hoprikoma,

Désolé pour ce temps de réponse, j'ai été beaucoup occupé ses derniers temps...
Concernant la documentation de la librairie, malgré mes intentions initiales, je n'ai malheureusement pas trouvé le temps de faire la documentation avec npm, puis avec le temps, j'ai mis ce projet un peu de côtés...

Mais tu fais bien d'évoquer le sujet, je ne te promets pas des nouvelles avant un ou deux mois car j'ai beaucoup de travail, mais je vais essayer de mettre à jour la doc et de faire la partie sur npm 😃.

Si possible, avec l'accord du créateur de la librairie et un peu de temps libre de ma part, je ferais peut-être même un site web complet en tant que documentation afin que ce soit plus convivial et plus simple à utiliser.

Je vous tiens au courant sur ce feed quand j'aurai trouvé un peu de temps pour contacter AmauriC et avancé sur le sujet.
