### ISSUE TITLE
Intégration de fonctions personnalisées (AtInternet)

### ISSUE THREAD

**Issue by Aaarrrgggh** [AmauriC/tarteaucitron.js#501]
Bonjour,

merci pour ce plugin JS très pratique 👍 

j'aurais une petite question. J'utilise AtInternet et je souhaite faire appel à des fonctions spécifiques du Tag, mais je n'arrive pas à le mettre en place. 

Dans le code, j'ai ceci : 

```
tarteaucitron.user.atMore = function () {
            var ATTag = new ATInternet.Tracker.Tag();
            ATTag.page.set({
              name:'{{atInternet.current.url}}',
              chapter1:'{{atInternet.current.chapter}}',
              level2: '{{atInternet.current.level_2}}'
            });
}

```
J'ai comme erreur : AtInternet is undefined.

J'ai voulu utliser la variable "tag" mais elle n'est pas trouvée. 

Comment y remédier ?

Merci de votre retour

**Comment by AmauriC** [comment]
Merci : )

Le tag est déjà déclaré dans la variable “tag”:
https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.services.js#L2408

Donc supprimez la première ligne et remplacez ATTag.page.set par tag.page.set, ça devrait fonctionner ; )

**Comment by Aaarrrgggh** [comment]
Merci pour votre réponse,

j'ai une erreur : Uncaught ReferenceError: tag is not defined

**Comment by Aaarrrgggh** [comment]
Par contre, ça a l'air de marcher en passant tag en paramètre de la fonction atMore()
