### ISSUE TITLE
Bandeau cookies réapparaît après la 1ere page malgré clic sur CTA

### ISSUE THREAD

**Issue by GaelleGu** [AmauriC/tarteaucitron.js#503]
Bonjour Amauri
Ce matin nous venons de détecter un petit bug sur le bandeau de cookies. J'ai beau vérifier les options et paramétrages de nos bandeaux, vider cache et cookies, pas de changement. 

Lorsqu'on visite notre site, à la première page visitée le bandeau apparaît. Jusque là c'est normal ;)
Si l'on clique sur le bouton "tout accepter" ou "tout refuser", le bandeau disparaît... mais il réapparaît à chaque page visitée ensuite. 

Une idée d'où cela pourrait provenir ? 
Bonne journée

**Comment by AmauriC** [comment]
Bonjour,

Ca pourrait être un soucis avec le paramètre pour gérer le domaine sur lequel est posé le cookie.

Une url pour un exemple ?

**Comment by GaelleGu** [comment]
Merci pour votre réponse.
Bien sûr : www.dolist.com par exemple. Nous avons installé Tarte au citron sur 4 autres sites et je constate le même comportement

**Comment by AmauriC** [comment]
C'est bien ça, probleme sur le cookieDomain.

`"cookieDomain": "https://www.dolist.com"`

devrait être

`"cookieDomain": ".dolist.com"`


A modifier depuis https://tarteaucitron.io/pro/

**Comment by GaelleGu** [comment]
En effet, une fois qu'on indique .dolist.com, cela retrouve le fonctionnement normal du bandeau de cookies ! Merci pour votre réactivité :)
