### ISSUE TITLE
Scroll tracking and implicit acceptance

### ISSUE THREAD

**Issue by BenDz** [AmauriC/tarteaucitron.js#51]
Hi,
First of all, thanks for the great tool!

I was wondering about the scroll implicit acceptation of services, and the value of 2x screen height. Is this an arbitrary value or does it come from a spec I didn't find?
This lead to short pages not being able to implicitly accept. That's not an issue, but more a thing to know I guess.

If there is no spec about it, don't you think it could be interesting to have this value in the init settings? This could also be set with a page scroll percentage.
I can PR something if this can be something interesting to you.

Thanks!
Benjamin

**Comment by AmauriC** [comment]
Hi,


I had discussed this with a contact at the CNIL (which deals in France to enforce this law).
I can not remember the details but 2x the height of the screen was a good compromise to say "ok, the user is really navigating".

On a small page, we can not say that it is enough to authorize everything.

Relying on a percentage is a bad thing, a page making a few more pixels than the screen will be allowed immediately.



The script is designed to be strict in all cases but you can adapt it and reduce to 1.7x, 1.5x if it's better on your sites, I do not think that's a problem ;)

________________________________
De : Benjamin Diolez <notifications@github.com>
Envoyé : mercredi 14 mars 2018 10:29:56
À : AmauriC/tarteaucitron.js
Cc : Subscribed
Objet : [AmauriC/tarteaucitron.js] Scroll tracking and implicit acceptance (#51)


Hi,
First of all, thanks for the great tool!

I was wondering about the scroll implicit acceptation of services, and the value of 2x screen height. Is this an arbitrary value or does it come from a spec I didn't find?
This lead to short pages not being able to implicitly accept. That's not an issue, but more a thing to know I guess.

If there is no spec about it, don't you think it could be interesting to have this value in the init settings? This could also be set with a page scroll percentage.
I can PR something if this can be something interesting to you.

Thanks!
Benjamin

**Comment by BenDz** [comment]
Thank you for your quick reply, I can totally understand why it is done that way.

Cheers,
Benjamin
