### ISSUE TITLE
Problème avec la version 1.2.0 (erreur dans le tag ?)

### ISSUE THREAD

**Issue by klnjmm** [AmauriC/tarteaucitron.js#510]
Bonjour,

J'utilise sur un projet tarteaucitron.js en version `1.2.0` (version dans le fichier `20191031`).
Lors d'une réinstallation du projet (lancement de `npm ci` avec une version dans le fichier `package-lock.json` à `1.2.0`), nous avons un bug : une image de cookie s'affiche en gros sur tout l'écran.

En regardant le repo, je m'aperçois que le tag `v1.2` a été refait il y a 17 jours avec l'ajout d'un commit qui concerne la `v1.8.2`. Et j'ai même l'impression que le tag `v1.2` contient désormais le même code que la `v1.8.2`

![image](https://user-images.githubusercontent.com/15214050/97755326-3bf4a600-1af9-11eb-93a0-9fe63cb06646.png)

![image](https://user-images.githubusercontent.com/15214050/97755395-5b8bce80-1af9-11eb-8c0f-ce7bec310f49.png)

Je soupçonne une erreur manuelle lors de la création du tag `1.8.2` qui a mené à écraser l'ancien tag `v1.2.0` existant.

Serait-il possible de rétablir le tag `v1.2.0` a son commit d'auparavant s'il vous plaît ?

**Comment by AmauriC** [comment]
Arf oui en effet je ne sais pas comment je me suis débrouillé : /

Passer à la version au dessus est la solution que j'allais vous proposer.

Il y a un moyen pour revert le changement de tag?

**Comment by klnjmm** [comment]
Il y a toujours un moyen de re déplacer le tag (suppression du tag actuel puis tag sur le bon id de commit).
Maintenant il faut retrouver à quel id de commit correspond la `v1.2`.

Le tag `v1.3` est sur le commit https://github.com/AmauriC/tarteaucitron.js/commit/8d86ad84e48c06626f4c0abcfb8f34ad81278ed0

![image](https://user-images.githubusercontent.com/15214050/97776623-ee645180-1b69-11eb-99ea-96096534e0e9.png)

![image](https://user-images.githubusercontent.com/15214050/97776498-e5bf4b80-1b68-11eb-8058-38af65f991a5.png)

Si on regarde le contenu de ce commit, on s'aperçoit que c'est ici que vous avez modifié la version (`20191031`). 

![image](https://user-images.githubusercontent.com/15214050/97776586-af360080-1b69-11eb-9a4f-8eacee399c33.png)

J'aurais limite tendance à dire que le tag `v1.2` a été fait sur le même id de commit que le tag `v1.3`.



En tout cas, je suis passé en 1.3.1 et ça marche. Mais ce déplacement du tag risque de causer des soucis chez plusieurs personnes.

**Comment by AmauriC** [comment]
Normalement c'est bon 👍 
https://github.com/AmauriC/tarteaucitron.js/releases/tag/v1.2

**Comment by klnjmm** [comment]
Effectivement le tag a bien été ramené.
Par contre, je suis allé voir sur npmjs.com et la release 1.2.0 a été publiée il y a 2 ans.

![0C76EFF5-AE31-4E82-A2B5-18E46D27238F](https://user-images.githubusercontent.com/15214050/97780474-36dd3880-1b85-11eb-9d4a-5ed05cb8b10f.jpeg)

Donc ça me fait penser que ma première analyse était mauvaise. 

En regardant la liste des tags, je m’aperçois qu’il y a un tag `V1.2` et non `v1.2` qui date de 2 ans...

![1FFF550F-96D7-43BA-9CC3-0CC5A47003A4](https://user-images.githubusercontent.com/15214050/97780561-ad7a3600-1b85-11eb-9f27-2b3ac3fe7d47.jpeg)

Donc au final je ne sais pas, est ce que c’est ce tag le bon (et que le `v1.2` est un nouveau qui n’aurait pas du exister)...

La pour le coup, seul vous, le mainteneur du projet peut le savoir...

**Comment by AmauriC** [comment]
Les 1.2 v/V ont toujours coexistés. Ca me semble revenu à la normale même si ça fait fouillis : /
