### ISSUE TITLE
le bouton "personnaliser" dans la modale ne fonctionne pas

### ISSUE THREAD

**Issue by christiaen-francois** [AmauriC/tarteaucitron.js#515]
Le bouton n'a pas l'air de vouloir déclencher la moindre fonction quand je clique dessus. Pourtant "Accepter tout" et "Refuser tout" fonctionnent à merveille. 

Suis-je le seul à être dans le cas ? 

J'ai la dernière version publiée sur le repo (1.8.3)

**Comment by AmauriC** [comment]
Je n'ai pas eu d'autre retour pour ce soucis et après vérification tout fonctionne bien.
Une url ou je peux voir le soucis?

**Comment by christiaen-francois** [comment]
J'ai du ajouter `onclick="tarteaucitron.userInterface.openPanel();"` au bouton en ligne 422 du fichier tartaucitron.js pour que le clic fonctionne. 
Tu peux voir sur [https://www.intermills.be](https://www.intermills.be)

**Comment by AmauriC** [comment]
C'est parce qu'il y a sur la page plusieurs éléments avec id="tarteaucitronCloseAlert" ce qui casse le système de clic ; )

Ajouter un onclick est une solution mais il serait mieux de supprimer ces ids.

**Comment by christiaen-francois** [comment]
EEEEExcellent !! Mon dieu que c'était une erreur de débutant ! 👍 Merci mec !
