### ISSUE TITLE
Déclarations de bariable avec "let" -> problème avec uglify JS

### ISSUE THREAD

**Issue by bastien-effetb** [AmauriC/tarteaucitron.js#516]
Bonjour,

Depuis la version 1.6, il n'est plus possible de faire passer tarteaucitron.js dans uglify js pour le compresser, ceci à cause des déclarations ES6 avec des "let i..." 
`for (leti = 0; i < purgeBtns.length; i++) {`

Je pense que ce serait bien de les supprimer dans la mesure ou ce sont les seuls éléments ES6 dans ce projet.

Merci

**Comment by AmauriC** [comment]
Salut,

C'est faisable mais il faut juste une solution pour:
https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.js#L631

@sir-gawain did you see a way to remove the let and still trigger the toggle?

**Comment by sir-gawain** [comment]
I think, changing the line:
var toggleBtns = document.getElementsByClassName("catToggleBtn");
to
var toggleBtns = document.getElementsByClassName("catToggleBtn"), i;
and then removing the 3 "let"s from the code should do the trick.

**Comment by bastien-effetb** [comment]
There is also a "let" here : 
`var purgeBtns = document.getElementsByClassName("purgeBtn");
            for (let i = 0; i < purgeBtns.length; i++) {`

**Comment by AmauriC** [comment]
It didnt work for https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.js#L631
I guess "i" or any other variable are not available when the event is triggered : /

Not a problem to remove the 3 others let.

**Comment by bastien-effetb** [comment]
I did that : 
`var toggleBtns = document.getElementsByClassName("catToggleBtn"), i;
                    for (i = 0; i < toggleBtns.length; i++) {
                        toggleBtns[i].dataset.index = i;
                        tarteaucitron.addClickEventToElement(toggleBtns[i], function () {
                            tarteaucitron.userInterface.toggle('tarteaucitronDetails' + cat[this.dataset.index], 'tarteaucitronInfoBox');
                            return false;
                        });
                    }`

**Comment by sir-gawain** [comment]
The problem with L631 is the weird scoping of javascript. 

What should help is to change the block to 
`
var toggleBtns = document.getElementsByClassName("catToggleBtn"), i;
                    for (i = 0; i < toggleBtns.length; i++) {
                        var ii = i;
                        tarteaucitron.addClickEventToElement(toggleBtns[i], function () {
                            tarteaucitron.userInterface.toggle('tarteaucitronDetails' + cat[ii], 'tarteaucitronInfoBox');
                            return false;
                        });
                    }
`

This should capture a new value for each iteration of i in the inner function.

**Comment by bastien-effetb** [comment]
No it is not working, because ii is always equal to the last iteration...
My solution works.
You can also set the index in a data attribute if you prefer, the nyou can access it via the dataset as explained in my last response : 
` 
 html += '               <button type="button" class="catToggleBtn" data-index="' + i + '" data-cat="tarteaucitronDetails' + cat[i] + '"><span class="tarteaucitronPlus"></span> ' + tarteaucitron.lang[cat[i]].title + '</button>';
`

**Comment by sir-gawain** [comment]
If that works, i have no objection against this solution.

**Comment by AmauriC** [comment]
I've tried this @sir-gawain but as @bastien-effetb explain, it doesnt work.

I push your elegant solution @bastien-effetb , thanks 😊

**Comment by bastien-effetb** [comment]
Hi Amauri,

You added again two "let" declaration in your code, uglify-js code minification is now broken again.
Could you please remove this declarations ?
`if(tarteaucitron.parameters.closePopup === true){
                    let element = document.getElementById('tarteaucitronAlertBig');
                    let span = document.createElement('span')
                    span.textContent = 'X';
                    span.setAttribute('id', "tarteaucitronCloseCross")
                    element.insertBefore(span, element.firstElementChild)
                }
`

Thank you.
