### ISSUE TITLE
Le lien "Read more" / "En savoir plus" n'est pas assez descriptif

### ISSUE THREAD

**Issue by Klemart3D** [AmauriC/tarteaucitron.js#518]
Moi j'aime bien Gogole, le maître du "faites ce que je dis, mais ne faites pas ce que je fais" :)

Ils mettent en place un outil d'analyse des performances d'un site web : https://web.dev/measure/

En SEO je n'ai que "85/100" car le principal problème est que l'un des liens de tarteaucitron n'est pas assez descriptif.

<img width="953" alt="tarteaucitron-recaptcha-read-more-link" src="https://user-images.githubusercontent.com/7419525/98959398-874c8280-2503-11eb-9e3f-fdab2d6bcf74.png">

Sur mon site j'utilise reCaptcha, dans la modale tarteaucitron l'erreur montrée du doigt est le lien "En savoir plus" qui emmène vers https://tarteaucitron.io/fr/service/recaptcha/ :

<img width="615" alt="recaptcha-tarteaucitron-modale" src="https://user-images.githubusercontent.com/7419525/98960379-abf52a00-2504-11eb-918d-b2cf2339e516.png">

L'erreur précise que "Les liens n'ont pas de texte descriptif - Le texte du lien descriptif aide les moteurs de recherche à comprendre votre contenu." Et pour en savoir plus sur cette erreur, il faut cliquer sur un lien... "Learn more" 😆 😆 😆 

Trêve de plaisanterie, ma suggestion serait d'ajouter le nom du service de sorte à obtenir un lien "En savoir plus sur reCaptcha" plutôt que juste "En savoir plus", qu'en pensez-vous ?
https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.js#L690

For english people I paste error here :
Links do not have descriptive text - 1 link found 
Descriptive link text helps search engines understand your content. Learn more.
/service/recaptcha/(tarteaucitron.io) | Read more

**Comment by AmauriC** [comment]
Sacré Google 😅

Il n'y a pas plutôt un moyen pour lui dire d'ignorer les liens? Parce que rajouter le nom du service ça va faire plaisir à Google mais pour les humains ce n'est pas vraiment utile 🧐

**Comment by Klemart3D** [comment]
En fait j'ai pris Google car c'est une référence de poids dans le domaine du référencement et des bonnes pratiques web, mais la plupart des ergonomes web s'accordent sur le fait qu'un lien ne doit pas être générique et doit idéalement préciser la nature du lien. Cela est autant bénéfique pour la comprehension de l'utilisateur que pour le référencement de la page cible (dans le cas ici, la vôtre !).
De mon point de vue, je considère que **tarteaucitron** doit être irréprochable en terme d'ergonomie et de SEO et qu'il devrait donc prendre en considération cette demande afin de ne pas pénaliser les milliers de sites qui l'utilisent. Après j'ouvre un débat, je n'impose rien, mais je serais curieux d'avoir les avis d'autres personnes.

Quelques ressources intéressantes :

https://www.1min30.com/dictionnaire-du-web/ancre-de-lien
https://www.seoquantum.com/billet/ancre-lien
https://moz.com/learn/seo/anchor-text
https://blog.alexa.com/anchor-text-best-practices/

**Comment by AmauriC** [comment]
Je ne suis pas du tout fermé à un changement mais un titre « recaptcha » avec un lien « en savoir plus » me semble assez clair.

A voir les autres retours, merci d’ouvrir le débat, le seo ce n’est pas du tout mon domaine ;-)

**Comment by O2Graphics** [comment]
Et en ajoutant un `rel="nofollow"` sur les liens, ça passe mieux le test de Google ?
Voir leur code : https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/seo/link-text.js#L116
mais ils n'en parlent pas dans leur doc : https://web.dev/link-text/

**Comment by Klemart3D** [comment]
@O2Graphics, merci pour ta suggestion.

J'ai donc testé les 2 solutions :

- Rajouter un "nofollow" au lien 'En savoir plus" :
<img width="1055" alt="nofollow" src="https://user-images.githubusercontent.com/7419525/99235086-af82fc80-27f5-11eb-8668-c07a16f4fd8e.png">

- Compléter de manière plus descriptive le lien "En savoir plus" en "En savoir plus sur reCaptcha" (sans "nofollow"):

<img width="1124" alt="readmore" src="https://user-images.githubusercontent.com/7419525/99234962-86626c00-27f5-11eb-94a0-aa97baa2956e.png">

Et dans les 2 cas le test passe, ma note SEO passant de 85 à 93 / 100 !! 

<img width="932" alt="note" src="https://user-images.githubusercontent.com/7419525/99235542-451e8c00-27f6-11eb-92b9-fd0f9f649bad.png">

(Le cas restant étant un robots.txt qui protège mon environnement de test de l'indexation, donc "normal" que je n'ai pas 100/100).

Pensez-vous qu'il soit possible d'appliquer l'une des deux solutions de manière à ce que tarteaucitron soit conforme au test de valdiation SEO de Google ?

(Je peux éventuellement proposer une PR sur la solution envisagée)

**Comment by AmauriC** [comment]
PR pour le nofollow ce sera parfait ; )

**Comment by O2Graphics** [comment]
Ah, top que ça fonctionne ! :+1: 
J'avais un doute que le fichier JS que j'avais trouvé soit la dernière version utilisée par Google, parce qu'il n'y a pas de texte français dans leur BLOCKLIST : https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/audits/seo/link-text.js#L10-L76

**Comment by Klemart3D** [comment]
PR: #521
