### ISSUE TITLE
doubleclick ?

### ISSUE THREAD

**Issue by pierretux** [AmauriC/tarteaucitron.js#519]
Bonjour

C'est ce code dans un tete qui pose un cookie :  
`<script>
gtag('event', 'conversion', {
'allow_custom_scripts': true,
'send_to': 'xxxx'
});
</script>
<noscript>
<img src="https://ad.doubleclick.net/ddm/activity/src=xxxxx;type=xx;cat=xx;dc_lat=;dc_rdid=;tag_for_child_directed_treatment=;tfua=;npa=;gdpr=${GDPR};gdpr_consent=${GDPR_CONSENT_755};ord=1;num=1?" width="1" height="1" alt=""/>
</noscript>`

Comment je peux géré cela avec le js tarteaucitron ?

Cdt

**Comment by NicolasT18** [comment]
Bonjour @pierretux ,

Tu peut allez voir ici : https://tarteaucitron.io/fr/install/

Une fois sur le lien, 
clique sur : "Installation manuelle gratuite"
puis en bas de la page sur : "Next Step"
Dans la barre de recherche, cherche "google analytics"

et tu devrait trouver la réponse à ta question :)

**Comment by pierretux** [comment]
Bonjour NicolasT18,

Merci mais justement j'ai déjà mis en place GA mais je ne vois pas comment supprimer ou remplacer doubleclick dans mes pages.

Cdt
