### ISSUE TITLE
file advertising.js is blocked by adblock

### ISSUE THREAD

**Issue by Adam-CdW** [AmauriC/tarteaucitron.js#52]
Hello,

The AdBlock list "Liste FR+EasyList" and probably others, prevent the file 'advertising.js' from being loaded and consequently prevent tarteaucitron from working.

Maybe it would be good to rename it...

Merci,
Adam

**Comment by AmauriC** [comment]
Hello,

It's not a bug, it's a feature 👍 

If an adblocker is present, tarteaucitron is useless.

There is an option to show a message about adblocker:

```
tarteaucitron.init({
   "adblocker": false, /* Display a message if an adblocker is detected */
});
```

**Comment by Adam-CdW** [comment]
Ok I get it now.
Yeah I've seen the option, but the message is not showing up, don't know why. That's what made me think of advertising.js as an issue.

I'm going to investigate further on my implementation. If I have a true issue I'll open a new one. 
Thanks for the library and for your quick answer.
