### ISSUE TITLE
Forcer langue avec version pro

### ISSUE THREAD

**Issue by RDNSid** [AmauriC/tarteaucitron.js#522]
Bonjour, 

Comment adapter le tag de la version "pro" 

`<script type="text/javascript" src="https://tarteaucitron.io/load.js?domain=www.mysite.com&uuid=xxxxxxxxx"></script>`

pour forcer la langue d'affichage ? 

Car le paramétrage de la langue dans l'interface pro n'est pas restitué sur mon site

Forçage soit "en dur" soit en suivant la valeur de la balise langue de la page : ex. <html lang="fr">
Merci ! 
Pierre

**Comment by AmauriC** [comment]
Hey,

Il faut ajouter un paramètre `locale`dans l'appel du script:

`<script type="text/javascript" src="https://tarteaucitron.io/load.js?locale=fr&domain=www.mysite.com&uuid=xxxxxxxxx"></script>`
