### ISSUE TITLE
Présenter les boutons "Tout accepter" et "Tout refuser" au même format

### ISSUE THREAD

**Issue by Klemart3D** [AmauriC/tarteaucitron.js#525]
Sur la dernière version de tarteaucitron.js (1.8.3 à date de création de ce ticket), les boutons "OK, tout accepter" et "Interdire tous les cookies" sont présentés dans des couleurs différentes :

<img width="668" alt="tac_183" src="https://user-images.githubusercontent.com/7419525/99518441-dd507880-2990-11eb-8d76-d292b57d319f.png">

Hors d'après les recommandations de la CNIL publiées le 1er octobre 2020 :

> les utilisateurs peuvent avoir le choix entre deux boutons présentés au même niveau et sur le même format, sur lesquels sont inscrits respectivement « tout accepter » et « tout refuser »

Site : https://www.cnil.fr/fr/cookies-et-traceurs-comment-mettre-mon-site-web-en-conformite
PDF : https://www.cnil.fr/sites/default/files/atoms/files/recommandation-cookies-et-autres-traceurs.pdf

<img width="566" alt="cnil" src="https://user-images.githubusercontent.com/7419525/99521774-1c80c880-2995-11eb-9e24-4c38e23a4a2f.png">

Pour appliquer cette recommandation, il faudrait donc, à la fois modifier le wording :

- "OK, tout accepter" → "Tout accepter"
- "Interdire tous les cookies" → "Tout refuser"

Et à la fois modifier les couleurs pour que l'apparence des boutons soit identique.

Voici 2 PR qui vont en ce sens :

- Wording : https://github.com/AmauriC/tarteaucitron.js/pull/523
- Couleurs* : https://github.com/AmauriC/tarteaucitron.js/pull/524

*la modification des couleurs doit être soumise à vérification car elle impacte plusieurs composants du script.

Autres sources sur ce sujet :
https://www.lefigaro.fr/flash-eco/publicite-sur-internet-les-bandeaux-cookies-non-conformes-sanctionnes-dans-6-mois-20201001
https://www.numerama.com/politique/599438-cookies-pistage-consentement-7-conseils-de-la-cnil-que-tout-le-monde-doit-connaitre.html#caption-attachment-599487

**Comment by AmauriC** [comment]
Merci pour les PR, j'ai demandé à la CNIL quelques précisions sur ce point.

Pour le wording ce serait en effet très bien, il y aussi une incohérence entre le bouton "ok, tout accepter" sur le bandeau et ensuite "autoriser tous les cookies" dans le panel. Ce serait bien de revoir tout ça, pour le fr et toutes les autres langues.

**Comment by AmauriC** [comment]
Retour de la CNIL: le but de cette ligne est de décourager les darks patterns (bouton OK bien visible et bouton NON presque invisible/désactivé/..).

Dans le cas de tarteaucitron, il n'y a pas d'intention de tromper l'utilisateur donc c'est ok.

Mais, il serait quand même bien de revoir le wording et pourquoi pas choisir une couleur plus neutre que le rouge/vert qui laisse penser que refuser c'est 'une mauvaise réponse'.
