### ISSUE TITLE
Google Analytics 4

### ISSUE THREAD

**Issue by marsaultgaetan** [AmauriC/tarteaucitron.js#526]
Bonjour, 

Est-ce que tarteaucitron.js prend en compte Google Analytics 4 ( l'ID de suivi est désormais sous la forme "G-xxxxxx" au lieu de "UA-xxxxxx" ) ?
Quel service de tarteaucitron.js doit-on utiliser ? Est-ce que le service "Google Analytics (ga.js)" fonctionne avec cette nouvelle version d'Analytics ?

merci pour votre aide

**Comment by AmauriC** [comment]
Bonjour,

Oui, aucun changement sur le marqueur, il suffit simplement de mettre le nouvel id en G- ; )

Amauri Champeaux
https://amauri.io/
________________________________
De : marsaultgaetan <notifications@github.com>
Envoyé : Thursday, November 19, 2020 9:51:51 AM
À : AmauriC/tarteaucitron.js <tarteaucitron.js@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [AmauriC/tarteaucitron.js] Google Analytics 4 (#526)


Bonjour,

Est-ce que tarteaucitron.js prend en compte Google Analytics 4 ( l'ID de suivi est désormais sous la forme "G-xxxxxx" au lieu de "UA-xxxxxx" ) ?
Quel service de tarteaucitron.js doit-on utiliser ? Est-ce que le service "Google Analytics (ga.js)" fonctionne avec cette nouvelle version d'Analytics ?

merci pour votre aide

**Comment by emilie68** [comment]
Bonjour,

J'ai implémenté Google Analytics 4 en utilisant gtag.js aujourd'hui mais il y a un nouveau type de cookies qui est bien bloqué avant consentement, mais n'est pas supprimé si le consentement est révoqué.
Il s'agit de : _ga_<container-id>.
Par ailleurs, le cookie a une durée de vie de 2 ans, tout comme le cookie _ga, chose que je n'ai pas quand je paramètre Google Analytics 4 avec le code Google Analytics universal (ga.js).

**Comment by AmauriC** [comment]
Hello,

Comment trouver le container-id ? Il y a une logique pour trouver le nom complet ?
Sinon je peux ajouter le même principe que https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.services.js#L2925

Pour la durée d'expiration, ce n'est pas grave, après 13 mois le cookie tarteaucitron est supprimé et les cookies purgés.

**Comment by emilie68** [comment]
Malheureusement, j'ai supprimé mon Google Analytics 4 suite à ce problème mais il y avait bien il je suis quasiment certaine que le "container-id" correspondait à la deuxième partie de l'ID de suivi (ex : "383RMEWP5Q" pour un ID de suivi "G-383RMEWP5Q").
D'accord pour l'expiration, je suis rassurée sur ce point-là !

**Comment by radoibogdan** [comment]
Bonjour,
J'ai le même souci que emilie68 avec le nouveau code G-XXXXXXXXXX. J'ai que google analytics sur mon site. Si j'autorise tout j'ai deux cookies. Si ensuite je refuse tous les cookies via le bouton, il a un des deux qui réapparait (name = _ga_XXXXXXXXXX).
Par contre, si j'arrive sur le site et je click directement sur "Tout refuser" il y a rien qui apparait. 
Merci pour votre aide.
Cdt,

**Comment by AmauriC** [comment]
👋

Je pense que ce push règle le problème: https://github.com/AmauriC/tarteaucitron.js/commit/974c86d5e930e53ece6cba023d38863787b98c3f

**Comment by radoibogdan** [comment]
Merci pour votre retour rapide ! 💯 
J'ai pris le nouveau code, vidé le cache (php bin/console clear:cache pour symfony) et testé. 
Malheureusement j'ai le même résultat dans le navigateur (Chrome pour moi).
Le _ga_XXXXXXXXXX ne veut pas s'en aller.  Un cookie têtu.

**Comment by AmauriC** [comment]
hum ok 🧐

Il y a un site live où je peux tester? Par mail si privé (voir mon profil).

**Comment by AmauriC** [comment]
Correctif: https://github.com/AmauriC/tarteaucitron.js/commit/d32c8ff406640c5f7d27b038d0901b7a9293b815 😬

**Comment by sebdavid** [comment]
Bonjour,
est-ce que ce ticket est résolu?
Si oui, est-ce qu'il sera bientôt intégré dans une nouvelle release?

**Comment by AmauriC** [comment]
Oui ticket réglé, nouvelle release bientôt ;-)

**Comment by Klemart3D** [comment]
La compatibilité Google Analytics 4 est donc assurée depuis la v1.8.4 (29/01/2021) ?

**Comment by AmauriC** [comment]
Yes : )
