### ISSUE TITLE
Issuu : url non détecter

### ISSUE THREAD

**Issue by pierretux** [AmauriC/tarteaucitron.js#528]
Bonjour,

Désormais les urls que l'on utilise sont par exemple https://issuu.com/ministere-solidarite/docs/ste_20200010_0000_p000, comment peut on prendre cela en charge maintenant ? Ou alors comment trouvé les urls e.issuu.com sur leur site ?

Cordialement.

**Comment by pierretux** [comment]
Bonjour,
Un retour possible ?
Cela fonctionne avec les id numérique mais pas les nom de doc, comment faire ?

Merci

**Comment by pierretux** [comment]
La correction de code 
`
var embed;
            if (issuu_id.match(/\d+\/\d+/)) {
                embed = '#' + issuu_id;
            } else if (issuu_id.match(/d=(.*)&u=(.*)/)) {
                embed = '?' + issuu_id;
            }
            issuu_frame = '<iframe type="text/html" ' + frame_width + frame_height + ' src="//e.issuu.com/embed.html' + embed + '" frameborder="0"></iframe>';
 `

**Comment by AmauriC** [comment]
Merci 👌

**Comment by pierretux** [comment]
merci
