### ISSUE TITLE
Remove 20200910 tag ?

### ISSUE THREAD

**Issue by prudloff-insite** [AmauriC/tarteaucitron.js#529]
This tag does not follow semantic versioning and makes tools like Asset Packagist think it is the latest version: https://asset-packagist.org/package/npm-asset/tarteaucitronjs

This means that installing tarteaucitron with Composer without specifying a version automatically installs 20200910 instead of 1.8.3.

**Comment by AmauriC** [comment]
Not a good fix but I know use tag name 20210306 to make this one lower.

This tag is the mostly used on jsdelivr, if I delete him, it will break a lot of installations :(
