### ISSUE TITLE
Marqueur à supprimer et à remplacer par celui de tarteaucitron.io 

### ISSUE THREAD

**Issue by GaelleGu** [AmauriC/tarteaucitron.js#534]
Bonjour Amaury
Je découvre la fonctionnalité https://tarteaucitron.io/fr/test/ permettant de vérifier l’installation de Tarteaucitron et me rends compte que l’ensemble de mes sites apparaissent comme non conformes.
J’ai installé Tarte au citron via le plugin sur Wordpress et les marqueurs de mes scripts sont indiqués via le plugin Wordpress. Pourtant, il est indiqué «  Marqueur à supprimer et à remplacer par celui de tarteaucitron.io ». Je pensais pourtant que le seul fait de renseigner les infos via le plugin suffisait. Une récente évolution ? 
Du coup, comment procéder ? 
-	1 / Où trouver ces marqueurs ? S’agit-il des valeurs « UA-XXXXX-X » qui sont mises en vert dans le bout de code qui suit  chaque message «  Marqueur à supprimer et à remplacer par celui de tarteaucitron.io ». ?
-	2/ a quel endroit dois-je remplacer les marqueurs ? je modifie directement les scripts, dans le header.php de mes sites ? 
Avant de foncer tête baissée dans ces modif, j’aimerais avoir une confirmation de votre part 😊
Merci d’avance
Bonne journée

**Comment by AmauriC** [comment]
Bonjour,

Rien de nouveau, ça a toujours été comme ça ; )

tarteaucitron charge le script quand l'utilisateur donne son accord et il faut retirer le marqueur 'sans tarteaucitron' pour ne pas qu'il se charge sans le consentement et éviter qu'il soit ensuite chargé 2x.

Pour les supprimer il n'y a pas de réponse générique, tout dépend de comment vous avez, avant tarteaucitron, intégré les différents services sur vos sites.

Il faut retirer les balises <script> similaire à ce qui est affiché sur le test tarteaucitron, ce n'est pas forcement exactement le même code mais ça doit y ressembler.

**Comment by GaelleGu** [comment]
Merci pour votre réponse. Ok je comprends à présent. Cela n'étant pas indiqué dans le processus d'installation du plugin, je n'imaginais pas qu'il faille en parallèle enlever les scripts de mon fichier header.php. Je vais donc m'y atteler. 
Par contre, dans les résultats des tests Tarteaucitron, je constate sur mes sites un avertissement de non conformité pour un script Google Tag Manager (API) qui n'est pourtant pas présent. J'ai bien un script Google Analytics (gtag.js) mais pas de Google Tag Manager. Une idée de ce qui pourrait causer ce "faux négatif" ?

**Comment by AmauriC** [comment]
Url du site? ; )

**Comment by GaelleGu** [comment]
https://omnicanal-marketing.dolist.com :)

**Comment by AmauriC** [comment]
Il y a toujours cette balise:

```
<script async src='https://www.googletagmanager.com/gtag/js?id=UA-976288-35'></script>
<script>
window.dataLayer = window.dataLayer \|\| [];
function gtag(){dataLayer.push(arguments);}gtag('js', new Date());
gtag('config', 'UA-976288-35' , {'linker': {'domains': ['https://www.dolist.com/ https://www.engage-leblog.com']},'anonymize_ip': true,});
</script>
```

**Comment by GaelleGu** [comment]
Merci pour votre réponse. Auparavant le bandeau ne s'affichait pas de nouveau à la 2e page si on avait cliqué sur le bouton "accepter" ou "refuser" à la 1ere page, et ce même s'il restait une balise en dur dans le code. Je vois que ce comportement se déploie sur nos autres sites. Avez-vous fait évoluer le comportement de ce bandeau ?

**Comment by AmauriC** [comment]
Le domaine pour le cookie est invalide, supprimez le slashe à la fin:
`.omnicanal-marketing.dolist.com/`

**Comment by GaelleGu** [comment]
Ah génial 👍  Ca fonctionne en enlevant le / à la fin du domaine !
Merci beaucoup :)
