### ISSUE TITLE
Problème avec le style inline du wrapper pour les vidéos

### ISSUE THREAD

**Issue by JulesAlexiu** [AmauriC/tarteaucitron.js#535]
Bonsoir !

J'ai un problème avec le style appliqué à la div qui englobe les vidéos, par l'extension WordPress de tarteaucitron.
En effet, un attribut `style` est présent et ajoute `height:50vw`, ce qui est énorme et ne tient pas compte des dimensions de la vidéo de base.

```
<div class="vimeo_player" videoid="0123456789" width="100%" height="100%" style="height:50vw;">
  <iframe src="//player.vimeo.com/video/0123456789" allowfullscreen="" width="100%" height="100%" frameborder="0"></iframe>
</div>
```

Ainsi, dans un layout en colonne, la vidéo est bien positionnée, mais sa div parente est immense sans vraiment de raison (je précise que dans WordPress, les colonnes utilisent `display: flex`.

Y a-t-il une solution à ce problème ?
Merci

**Comment by AmauriC** [comment]
Hello,

Et en supprimant le `height:50vw` la vidéo à toujours la bonne taille?

Si oui je peux le supprimer facilement ;)

**Comment by JulesAlexiu** [comment]
Lien vers le forum WordPress, c'est plus adapté :)

https://wordpress.org/support/topic/probleme-avec-le-style-inline-du-wrapper-pour-les-videos/#post-13770147
