### ISSUE TITLE
Google maps with pointer

### ISSUE THREAD

**Issue by thierrymtp34** [AmauriC/tarteaucitron.js#54]
Hello everyone
Thank you for this very interesting development
I have on a site of my customers in the page of contact a map Google maps with a pointer to locate the company but I can not manage to display it.
Is there a solution?
Thank you in advance for your answer and sorry for my english which is not very good

**Comment by sebastienheyd** [comment]
Ne t'embêtes pas avec l'anglais, la moitié des issues sont rédigées en français... ;)

J'ai le même soucis sur un projet, j'ai besoin d'assigner des marqueurs sur la carte.

Pour le moment j'ai commenté `window.tac_googlemaps_callback` dans `tarteaucitron.services.js` et j'ai déclaré `window.tac_googlemaps_callback` dans ma page en ajoutant les marqueurs.

En clair, seul l'appel à l'api est géré par tarteaucitron, le callback est ensuite celui de ma page.

Attention à bien conserver la classe `googlemaps-canvas` sur la/les éléments pour conserver le fallback (message "maps est désactivé...")

Il serait peut être utile d'avoir une variable `tarteaucitron.user.mapscallback` pour définir le callback à appeler ?

**Comment by Stepomp** [comment]
Avec le code ça serait mieux ;)

![capture1](https://user-images.githubusercontent.com/38464811/39312052-ce25b690-496e-11e8-8e32-4b4040178cae.JPG)

**Comment by Stepomp** [comment]
![capture4](https://user-images.githubusercontent.com/38464811/39314946-bd87928e-4975-11e8-9d74-56828610b19a.JPG)

**Comment by Stepomp** [comment]
Merci beaucoup @sebastienheyd ça fonctionne nickel 😃

**Comment by lxxps** [comment]
> tarteaucitron.user.mapscallback = 'initialize';

À ajouter sur la documentation alors, svp :)

**Comment by jlethuau** [comment]
@sebastienheyd Bonjour, je suis dans le même cas de figure et j'ai à afficher une map avec certains pointeurs dont les données sont récupérées dynamiquement de manière asynchrone. Dans ta solution, est-ce qu'il faut utiliser le code de remplacement de tarteaucitron ?

**Comment by AmauriC** [comment]
Merci à tous, doc mise à jour :-)

**Comment by lainesonny** [comment]
Bonjour à toutes et à tous,

J'aimerais avoir un coup de main pour la mise en place de la map avec un pointer. J'espère que vous pourrez m'aider! :)

`<script>
    // Google Map - Tarteaucitron.js
    tarteaucitron.user.googlemapsKey = 'xxxxxxxxxxxxxxxxxxxxxxx';
    tarteaucitron.user.mapscallback = 'initialize';  // optionnal - for markers

    window.addEventListener('DOMContentLoaded', function() {
        window.initialize = function() {
            var center = {lat: xxxxx, lng: xxxxx};

            var map = new google.maps.Map(document.getElementById('map-contact'), {
                zoom: 12,
                center: center,
                scrollwheel: false
            });

            var marker = new google.maps.Marker({
                position: center,
                map: map,
                title: "Libelle du point"
            });
        }
    });
   (tarteaucitron.job = tarteaucitron.job || []).push('googlemaps');
</script>`

**Comment by gazouweb** [comment]
Bonjour à tous,
Je ne trouve pas la doc où a été ajoutée la mention "mapscallback", pouvez-vous le dire ou la trouver ?
Par ailleurs, as-t-on la possibilité de faire un test pour savoir si l'utilisateur à accepter ou refuser ?
Merci pour votre réponse.

**Comment by thierrymtp34** [comment]
Bonjour a tous,

Depuis mon premier post j'avais laissé coulé l'histoire de pointeur mais je reviens dessus.
Après de multiple tentative, je ne comprends pas comment afficher mon pointeur ...

- La mise à jour de TaC à été faite.
- Ma carte fonctionne bien avec la demande d'autorisation TaC
- quand je mets le script "<script>tarteaucitron.user.mapscallback = 'callback_function';tarteaucitron.user.googlemapsLibraries = 'LIBRARIES';</script>" plus rien ne s'affiche

Je ne sais pas quoi mettre à la place de "callback_function" et de "LIBRARIES"

Je cherche a afficher mon pointeur sur ses coordonnées "43.329615, 3.287088" 
Pourriez vous m'aider ?

**Comment by AmauriC** [comment]
Les librairies ne sont pas utiles, vous pouvez supprimer cette ligne.

Pour le marqueur, en dessous de la clé api:

```
tarteaucitron.user.mapscallback = 'initializeMarker';
window.addEventListener('DOMContentLoaded', function() {
     window.initializeMarker = function() {
            tarteaucitron.fallback(['googlemaps-canvas'], function (x) {
                var uniqId = '_' + Math.random().toString(36).substr(2, 9);
                uniqIds.push(uniqId);
                return '<div id="' + uniqId + '" zoom="' + x.getAttribute('zoom') + '" latitude="' + x.getAttribute('latitude') + '" longitude="' + x.getAttribute('longitude') + '" style="width:' + x.offsetWidth + 'px;height:' + x.offsetHeight + 'px"></div>';
            });

            for (i = 0; i < uniqIds.length; i += 1) {
                mapOptions = {
                    zoom: parseInt(document.getElementById(uniqIds[i]).getAttribute('zoom'), 10),
                    center: new google.maps.LatLng(parseFloat(document.getElementById(uniqIds[i]).getAttribute('latitude'), 10), parseFloat(document.getElementById(uniqIds[i]).getAttribute('longitude'), 10))
                };
                map = new google.maps.Map(document.getElementById(uniqIds[i]), mapOptions);

         var marker = new google.maps.Marker({
          position: {lat: 43.329615, lng: 3.287088},
          map: map,
          title: 'Hello World!'
        });
            }
     }
}
```

**Comment by thierrymtp34** [comment]
Tu viens de me perdre car je cherche que faire avec ton script et la je galère.

**Comment by AmauriC** [comment]
C'est bien pour Tarteaucitron.

Ajoute ça en dessous de:
tarteaucitron.user.googlemapsKey = 'API KEY';

**Comment by thierrymtp34** [comment]
Bien sur Amauri 
J'ai remis le code ci dessus que j'utilise

**Comment by thierrymtp34** [comment]
Up 
Pas d'idée pour une intégration dans le script officiel ?

**Comment by Tomate219** [comment]
Bonjour, je me permet d'up ce sujet parce que j ai un problème un peu similaire.
Grosso modo je travaille sur un site pour un food truck et j aurais donc plusieurs cartes avec plusieurs (ou un seul) marqueur en fonction des cartes. Après mainte relecture de ce thread je n'ai toujours pas trouvé ma solution.
J’aimerais bien quelques avis éclairés  sur mon code que voici:
HTML : 
```
<div id="map" class="googlemaps-canvas " zoom="11" latitude="47.00981" longitude="-1.583365" style="width:auto; height: 600px"></div>
            <script>tarteaucitron.user.mapscallback = 'tac_googlemaps_stcolomban';</script>
```

JS:
```
tarteaucitron.services.googlemaps = {
    "key": "googlemaps",
    "type": "api",
    "name": "Google Maps",
    "uri": "http://www.google.com/ads/preferences/",
    "needConsent": true,
    "cookies": [],
    "js": function () {
        "use strict";
        var mapOptions,
                map,
                uniqIds = [],
                i;        
        if (tarteaucitron.user.mapscallback === undefined) {
            tarteaucitron.user.mapscallback = 'tac_googlemaps_callback';
        }

        // Add Google Maps libraries if any (https://developers.google.com/maps/documentation/javascript/libraries)
        var googleMapsLibraries = '';
        if (tarteaucitron.user.googlemapsLibraries) {
            googleMapsLibraries = '&libraries=' + tarteaucitron.user.googlemapsLibraries;
        }

        tarteaucitron.addScript('//maps.googleapis.com/maps/api/js?v=3.exp&key=' + tarteaucitron.user.googlemapsKey + '&callback=' + tarteaucitron.user.mapscallback + googleMapsLibraries);

        window.tac_googlemaps_callback = function () {
            tarteaucitron.fallback(['googlemaps-canvas'], function (x) {
                var uniqId = '_' + Math.random().toString(36).substr(2, 9);
                uniqIds.push(uniqId);
                return '<div id="' + uniqId + '" zoom="' + x.getAttribute('zoom') + '" latitude="' + x.getAttribute('latitude') + '" longitude="' + x.getAttribute('longitude') + '" style="width:' + x.offsetWidth + 'px;height:' + x.offsetHeight + 'px"></div>';
            });

            for (i = 0; i < uniqIds.length; i += 1) {
                mapOptions = {
                    zoom: parseInt(document.getElementById(uniqIds[i]).getAttribute('zoom'), 10),
                    center: new google.maps.LatLng(parseFloat(document.getElementById(uniqIds[i]).getAttribute('latitude'), 10), parseFloat(document.getElementById(uniqIds[i]).getAttribute('longitude'), 10))
                };
                map = new google.maps.Map(document.getElementById(uniqIds[i]), mapOptions);
            }
        };
        window.tac_googlemaps_stcolomban = function () {
            tarteaucitron.fallback(['googlemaps-canvas'], function (x) {
                var uniqId = '_' + Math.random().toString(36).substr(2, 9);
                uniqIds.push(uniqId);
                return '<div id="' + uniqId + '" zoom="' + x.getAttribute('zoom') + '" latitude="' + x.getAttribute('latitude') + '" longitude="' + x.getAttribute('longitude') + '" style="width:' + x.offsetWidth + 'px;height:' + x.offsetHeight + 'px"></div>';
            });
            for (i = 0; i < uniqIds.length; i += 1) {
                mapOptions = {
                    zoom: parseInt(document.getElementById(uniqIds[i]).getAttribute('zoom'), 10),
                    center: new google.maps.LatLng(parseFloat(document.getElementById(uniqIds[i]).getAttribute('latitude'), 10), parseFloat(document.getElementById(uniqIds[i]).getAttribute('longitude'), 10))
                };
                map = new google.maps.Map(document.getElementById(uniqIds[i]), mapOptions);
                var marker = new google.maps.Marker({
                    position: {lat:47.0098098,lng:-1.5833651},
                    map: map,
                    icon:{url: '/images/marqueur.png', scaledSize: new google.maps.Size(85, 75)}
                });
            }
        };
        window.tac_googlemaps_hissezo = function () {
            tarteaucitron.fallback(['googlemaps-canvas'], function (x) {
                var uniqId = '_' + Math.random().toString(36).substr(2, 9);
                uniqIds.push(uniqId);
                return '<div id="' + uniqId + '" zoom="' + x.getAttribute('zoom') + '" latitude="' + x.getAttribute('latitude') + '" longitude="' + x.getAttribute('longitude') + '" style="width:' + x.offsetWidth + 'px;height:' + x.offsetHeight + 'px"></div>';
            });
            for (i = 0; i < uniqIds.length; i += 1) {
                mapOptions = {
                    zoom: parseInt(document.getElementById(uniqIds[i]).getAttribute('zoom'), 10),
                    center: new google.maps.LatLng(parseFloat(document.getElementById(uniqIds[i]).getAttribute('latitude'), 10), parseFloat(document.getElementById(uniqIds[i]).getAttribute('longitude'), 10))
                };
                map = new google.maps.Map(document.getElementById(uniqIds[i]), mapOptions);
               var marker1 = new google.maps.Marker({
                    position: {lat:46.78529 ,lng: -2.075464},
                    map: map,
                    icon:{url: '/images/marqueur.png', scaledSize: new google.maps.Size(85, 75)}
                });
            }
        };
    },
    "fallback": function () {
        "use strict";
        var id = 'googlemaps';
        tarteaucitron.fallback(['googlemaps-canvas'], tarteaucitron.engage(id));
    }
};
```

En gros il va y avoir le callback st colomban où il y aura plusieurs marqueurs(pour l'instant il n y en a qu'un ), et le hissezo où il n'y en aura qu'un, le soucis c'est que une fois qu'un marqueur est utilisé pour un callback je n'arrive pas a en afficher un via un autre callback

Désolé si ce n'est pas très compréhensible, j ai pas vraiment l habitude de demander de l aide sur les forums

**Comment by sebastienheyd** [comment]
@Tomate219 oui, c'est normal un seul callback est appelé par TaC.

En fait, tes initialisations et les placement des marqueurs doivent être faits dans ce seul callback , je n'ai pas testé mais je pense qu'il faut boucler sur les div qui vont contenir tes maps, un truc du genre...

```js
for (i = 0; i < uniqIds.length; i += 1) {
    mapOptions = {
        zoom: parseInt(document.getElementById(uniqIds[i]).getAttribute('zoom'), 10),
        center: new google.maps.LatLng(parseFloat(document.getElementById(uniqIds[i]).getAttribute('latitude'), 10), parseFloat(document.getElementById(uniqIds[i]).getAttribute('longitude'), 10))
    };
    // c'est ici que ça se passe... map[i] au lieu de map
    map[i] = new google.maps.Map(document.getElementById(uniqIds[i]), mapOptions);
}

var marker = new google.maps.Marker({
    position: {lat:47.0098098,lng:-1.5833651},
    map: map[1], // Affiche sur la première carte
    icon:{url: '/images/marqueur.png', scaledSize: new google.maps.Size(85, 75)}
});

var marker1 = new google.maps.Marker({
    position: {lat:46.78529 ,lng: -2.075464},
    map: map[2],  // Affiche sur la seconde carte
    icon:{url: '/images/marqueur.png', scaledSize: new google.maps.Size(85, 75)}
});
```

**Comment by Tomate219** [comment]
@sebastienheyd Merci de ta réponse!

### Après réflexion je ne vais pas avoir besoin de réponse a ma question étant donné qu'au final des screens suffiront pour la plupart des cartes

Mais il y a une erreur de définition dont j'ai pas réussi à trouver la source avec mes maigres compétences en JS
![erreur](https://user-images.githubusercontent.com/43028268/52469476-d4abfb00-2b8b-11e9-96a3-d98ac959b984.jpg)

Et au niveau algo, si on veut avoir plusieurs maps avec différents marqueurs dans un ordre différent sur plusieurs pages différentes il y a de fortes chances que ça ne fonctionne pas non? (sauf si on change l'ID des div auquel cas j aurais pas tout compris)
J'illustre:
Page 1:
Map 1 Marqueur A B
Map  Marqueur C
Page 2:
Map 1 Marqueur D

Si on boucle sur les div je vais forcément me retrouver avec a chaque fois le 1er marqueur de la 1ere map qui sera toujours le même non?

**Comment by sebastienheyd** [comment]
@Tomate219 la variable map doit être initialisée comme tableau pour ne pas avoir l'erreur : `var map = []`

Je te donnais un exemple pour une seule page, mais il est tout a fait possible de récupérer par exemple une variable data-name dans la balise div qui contiendra la map, dans ce cas dans la boucle l'index de ton tableau de carte sera la valeur de data-name. Avec des if sur le nom tu auras à chaque fois la bonne carte avec les bons marqueurs au bon endroit.

Sinon tu as la solution des static maps, moins compliquée : https://developers.google.com/maps/documentation/maps-static/intro

**Comment by Tomate219** [comment]
Merci pour les précisions, j'espère que ça pourra en aider certains
