### ISSUE TITLE
Aucun enregistrement sur Google analystic

### ISSUE THREAD

**Issue by manu8870** [AmauriC/tarteaucitron.js#541]
Bonjour à tous, j'ai suivi le tuto sur Tarte au citron , j'ai installé le script mais quand je vérifie sur mon compte Google analystic ça ne m'indique aucuns enregistrements....
Merci d'avance de votre aide.

**Comment by AmauriC** [comment]
Il faudrait un peu plus de détails : s

Une url du site? ou le details de l'intégration ?

**Comment by manu8870** [comment]
Voila comment j'ai installé le script, j'ai bien la petite icone en bas de page.

<!DOCTYPE html>
<html  lang="fr">
<head>
  
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="monsite.fr"> 
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="assets/images/1607273615328-247x121.png" type="image/x-icon">
  <meta name="description" content="">
  <meta name="keywords" content="">

  <title>Les travaux</title>
  <link rel="stylesheet" href="assets/web/assets/th-icons2/feuille.css">
  <link rel="stylesheet" href="assets/web/assets/th-icons/my-icons.css">
  <link rel="stylesheet" href="assets/tether/tether.min.css">
  <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="assets/bootstrap/css/bootstrap-grid.min.css">
  <link rel="stylesheet" href="assets/bootstrap/css/bootstrap-reboot.min.css">
  <link rel="stylesheet" href="assets/dropdown/css/style.css">
  <link rel="stylesheet" href="assets/socicon/css/styles.css">
  <link rel="stylesheet" href="assets/theme/css/style.css">
 <script src="tarteaucitron/tarteaucitron.js"></script>
    <script>
        tarteaucitron.init({
            "mentions.html": "", /* URL de la page de la politique de vie privée */

            "hashtag": "#tarteaucitron", /* Ouvrir le panneau contenant ce hashtag */
            "cookieName": "tarteaucitron", /* Nom du Cookie */

            "orientation": "bottom", /* Position de la bannière (top - bottom) */
            "showAlertSmall": false, /* Voir la bannière réduite en bas à droite */
            "cookieslist": true, /* Voir la liste des cookies */

            "adblocker": false, /* Voir une alerte si un bloqueur de publicités est détecté */
            "AcceptAllCta": true, /* Voir le bouton accepter tout (quand highPrivacy est à true) */
            "highPrivacy": true, /* Désactiver le consentement automatique */
            "handleBrowserDNTRequest": false, /* Si la protection du suivi du navigateur est activée, tout interdire */

            "removeCredit": true, /* Retirer le lien vers tarteaucitron.js */
            "moreInfoLink": true, /* Afficher le lien "voir plus d'infos" */
            "useExternalCss": false, /* Si false, tarteaucitron.css sera chargé */

            //"cookieDomain": ".my-multisite-domaine.fr", /* Cookie multisite */

            "readmoreLink": "/cookiespolicy" /* Lien vers la page "Lire plus" */
        });
	</script> 
  
  
  

</head>
<body>

   <script type="text/javascript">
        tarteaucitron.user.gtagUa = 'monidgoogle';
        tarteaucitron.user.gtagMore = function () { /* add here your optionnal gtag() */ };
        (tarteaucitron.job = tarteaucitron.job || []).push('gtag');
        </script>  
  

</body>
</html>

**Comment by AmauriC** [comment]
L'intégration semble ok. Pas d'erreur dans la console? Vous pouvez bien accepter/refuser le service?

**Comment by manu8870** [comment]
Oui j'ai bien accepté sur chaque appareils avec lesquel j'ai testé.

**Comment by manu8870** [comment]
![IMG_20201222_111140](https://user-images.githubusercontent.com/74957654/102877111-83871680-4446-11eb-87e2-a9b50016dcfe.jpg)
Après encore plusieurs essais,je n'ai aucuns enregistrements.....
J'ai essayé avec le script gtag et ga....aucun changement

**Comment by AmauriC** [comment]
"une erreur s'est produite" sur le site GA.

Vous avez essayé dans un autre navigateur?

**Comment by manu8870** [comment]
Je suis sur l'appli Google analystic,et j'ai essayé plusieurs navigateurs.

**Comment by manu8870** [comment]
J'ai supprimé mon code google, recréée une propriétée, ajouté le nouvel ID sur le script TAC....
Mais rien, aucune données enregistrées non plus!
Je ne comprends plus rien du tout.....

**Comment by manu8870** [comment]
Maintenant j'ai bien les visiteurs en temps réel,mais aucuns pays,aucunes pages visitées n'apparaît.....
Incompréhensible....

**Comment by AmauriC** [comment]
Si des infos remontent, ça n'a plus de rapport avec tarteaucitron.

Attendez un peu et vérifiez demain, il y a surement un délai pour traiter les informations, google analytics n'est pas en temps réel pour toutes les stats.

**Comment by manu8870** [comment]
Merci,je vais essayer demain.

**Comment by manu8870** [comment]
Donc ça ne m'affiche bien que les visiteurs en temps réels et aucunes autres informations....

**Comment by AmauriC** [comment]
Faites le test sans tarteaucitron.

**Comment by manu8870** [comment]
Donc j'ai essayé sans le script Tarte aux citrons et j'ai des enregistrements.....
Je ne vois pas d'erreur de placement de mon script.
