### ISSUE TITLE
Surcharger ou pouvoir configurer l'item de lang alertBigPrivacy

### ISSUE THREAD

**Issue by pierretux** [AmauriC/tarteaucitron.js#542]
Bonjour,

Comment peut on faire pour changer le texte de https://github.com/AmauriC/tarteaucitron.js/blob/master/lang/tarteaucitron.fr.js#L13 en fonction des sites ?
En effet pour certain si je souhaite un autre texte.

merci

**Comment by AmauriC** [comment]
Bonjour :)

En ajoutant cette variable JS avant le chargement du script ça devrait fonctionner:

```
<script>
var tarteaucitronCustomText = {
    "alertBigPrivacy": "Nouvelle phrase",
};
</script>
```

**Comment by pierretux** [comment]
Parfait, Merci
