### ISSUE TITLE
Dutch translation message for mandatory cookies

### ISSUE THREAD

**Issue by SanderVanKeer** [AmauriC/tarteaucitron.js#546]
Hi there! Thanks for the great package here.

I just saw that the messages for the mandatory cookies are not translated in Dutch.

 "mandatoryTitle": "Verplichte cookies",
 "mandatoryText": "Deze site maakt gebruik van cookies die nodig zijn voor de goede werking ervandie niet kunnen worden gedeactiveerd."

Thanks in advance for adding them!

**Comment by AmauriC** [comment]
Thanks, will be embeded on the next release 😉

**Comment by SanderVanKeer** [comment]
Hi @AmauriC,

I'm so sorry! I just saw I made a type in the last one! This is the correct version:

"mandatoryText": "Deze site maakt gebruik van cookies die nodig zijn voor de goede werking ervan die niet kunnen worden gedeactiveerd."

It has to be "ervan die" instead of "ervandie".

My apologies!

**Comment by SanderVanKeer** [comment]
Hi @AmauriC ,

I'm so sorry but I made a typo in the translation! This is the correct version:

"mandatoryText": "Deze site maakt gebruik van cookies die nodig zijn voor de goede werking ervan en die niet kunnen worden gedeactiveerd."

My apologies!

**Comment by AmauriC** [comment]
Fixed, no problem 😊
