### ISSUE TITLE
Language code for svenska and chinese

### ISSUE THREAD

**Issue by bastien-effetb** [AmauriC/tarteaucitron.js#548]
Hi Amauri,

The translation for svenska (sweden language) is named tarteaucitron.se.js, but the correct code for this language in ISO 639-1 is  
sv and not se : https://fr.wikipedia.org/wiki/Su%C3%A9dois
In fact se is the country code : https://www.localeplanet.com/icu/sv-SE/index.html

I see that chinese is also not using the good ISO 639-1 language code which should be zh

Can you please update file names as it can lead to problems when relying on ISO 639-1 to load automatically the translations.

Best regards

**Comment by jipexu** [comment]
Yes need update the files name but also modify one or two line of code in the core...

**Comment by AmauriC** [comment]
Thanks, I'll fix this asap ; )
