### ISSUE TITLE
integration ?

### ISSUE THREAD

**Issue by TheMechanic** [AmauriC/tarteaucitron.js#549]
Bonjour à tous,
ce module a l'air super, cependant voulant l'utiliser je suis assez perplexe : il n'est pas utilisable tel quel avec webpack (pas de système de module utilisé). Injecter le script tel quel dans le HEAD ? oui, mais il n'y a pas de version minifiée :/
Y-a-t-il en projet de le migrer vers un vrai module npm ?

**Comment by AmauriC** [comment]
Hello,

pas de projet de mon coté car je n’utilise pas du tout web pack mais si quelqu’un veut le faire, aucun soucis :-)

**Comment by encreinformatique** [comment]
Même problème pour moi.

**Comment by fvsadem** [comment]
+1 pour rendre compatible en module.
Malheureusement, il n'y a pas d'export dans le fichier tarteaucitron.js ce qui le rend inutilisable dans node.
