### ISSUE TITLE
Action sur bandeau cookies pas prise en compte

### ISSUE THREAD

**Issue by GaelleGu** [AmauriC/tarteaucitron.js#551]
Bonjour Amauri

Nous rencontrons un souci d’affichage du bandeau de cookies sur notre site https://services.dolist.com/ qui utilise Tarte au citron (version payante)

J’ai pourtant vidé les caches et cookies, essayé sur 2 navigateurs distincts (Chrome et Mozilla), le comportement se répète : 
-	A l’arrivée sur le site web, le bandeau des cookies apparaît pour la 1ere fois. 
o	Si Je clique oui et continue de scroller sur la même page, le bandeau réapparaît (vidéo du test ici https://www.powtoon.com/c/fVap5Pi9pgE/1/m) 
o	Si je clique oui et que je me rends sur une autre page du site, le bandeau réapparait également sur cette 2e page (vidéo du test ici https://www.powtoon.com/c/e2Yl3GCJ7eB/1/m)

J’ai l’impression qu’il y a un temps de latence un peu long pour que le système prenne bien en compte mon action sur le bandeau de cookies. 
A noter que ce délai de traitement n’est pas présent sur mes autres sites (https://technologies.dolist.com ou https://www.dolist.com) 

Comment résoudre cela ? 
Cordialement

**Comment by AmauriC** [comment]
Bonjour,

Pas de temps de latence, le bandeau réapparaît parce que le service add this est ajoute un peu après le chargement de la page.

![Uploading 5DB26676-6A67-4D38-B9CE-928E065A7759.png…]()

**Comment by GaelleGu** [comment]
Bizarre, car j'ai aussi Addthis + Tarteaucitron sur un autre site : www.dolist.com mais le bandeau cookies fonctionne du premier coup

**Comment by AmauriC** [comment]
Au niveau tarteaucitron, si les paramètres sont les mêmes sur la console, tout est identique. Il doit y avoir une différence entre les 2 sites.
