### ISSUE TITLE
Cookies non proposés

### ISSUE THREAD

**Issue by btran-lextenso** [AmauriC/tarteaucitron.js#552]
bonjour, 

- j'utilise gigya, mais il n'est pas proposé dans la liste des services, comment faire pour l'ajouter ?
- comment faire pour, comme chez vous ou sur elysee.fr, ajouter des cookies obligatoires/nécessaires au fonctionnement du site non désactivables : Ce site utilise des cookies nécessaires à son bon fonctionnement qui ne peuvent pas être désactivés.

Merci

**Comment by AmauriC** [comment]
Bonjour,

- Créez un autre ticket avec les détails pour intégrer gigya sans tarteaucitron et je verrai si il est possible de l'ajouter.

- Il y a l'option `"mandatory": true` pour afficher ce message (depuis la v pro c'est dans Mes sites > Options).
