### ISSUE TITLE
Problème affichage sur Edge et Chrome

### ISSUE THREAD

**Issue by coccinelly** [AmauriC/tarteaucitron.js#558]
Bonjour,
Je viens d'installer l'excellente tarteaucitron. 
Mais la barre de défilement de la fenêtre de choix des cookies n'apparait pas sur Chrome et Edge (elle apparait sans souci sur Firefox).
Comment résoudre le problème ?
Merci de votre aide !

**Comment by AmauriC** [comment]
Hello

Elle devrait pourtant y être. Peut-être un conflit CSS. Quel est l'url du site?

**Comment by coccinelly** [comment]
http://site.christophore.com

(j'en profite pour te dire merci et bravo pour ce super boulot !)

**Comment by AmauriC** [comment]
Merci :D mais je ne suis pas seul, 84 contributeurs sur ce projet 👍 

Ca fonctionne bien de mon côté : /
Ca ne scroll pas du tout ou juste la scrollbar n'est pas visible?

**Comment by coccinelly** [comment]
La scrollbar n'est pas visible, chez moi sur Edge et Chrome.

**Comment by AmauriC** [comment]
et ajoutant cette règle CSS:
`#tarteaucitronServices::-webkit-scrollbar-thumb {
    background-color: red;
}`

**Comment by coccinelly** [comment]
Impec ! Merci beaucoup !
