### ISSUE TITLE
One signal

### ISSUE THREAD

**Issue by W-prog** [AmauriC/tarteaucitron.js#559]
Bonjour, je voudrais déclarer le service OneSignal qui permet d'envoyer des notifications push.
Avez-vous prévu de l'intégrer dans tarteaucitron.js  ?

**Comment by AmauriC** [comment]
Partagez ici le marqueur html onesignal et je verrai si il est possible de l'ajouter.

**Comment by W-prog** [comment]
<script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" type="text/javascript"></script>
`
var OneSignal = window.OneSignal \|\| [];
--
  | OneSignal.push(function() {
  | OneSignal.init({
  | appId: "xxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxxxx",
  | });
  | });

`

**Comment by AmauriC** [comment]
C'est ajouté ; )
https://github.com/AmauriC/tarteaucitron.js/commit/e214a6289bbad0ddecfc83c91396741f9448dd4f

**Comment by W-prog** [comment]
Ok merci
Donc j’ai mis ce marqueur pour intégation
(tarteaucitron.job = tarteaucitron.job || []).push('onesignal');

**Comment by AmauriC** [comment]
Il faut ajouter aussi la ligne avec l'app id et retirer l'intégration actuelle:

 ```
<script type="text/javascript">
tarteaucitron.user.onesignalAppId = 'VOTRE_APP_ID';
(tarteaucitron.job = tarteaucitron.job || []).push('onesignal');
</script>
```

**Comment by W-prog** [comment]
Ok merci, j'ai dépublié le plugin Joomla de notification en question et la demande de notification arrive bien après acceptation des cookies. Tout est parfait.
