### ISSUE TITLE
Opt-out sur les cookies obligatoires

### ISSUE THREAD

**Issue by nina3am** [AmauriC/tarteaucitron.js#560]
Bonjour Amauri,

Sur l'exemple présent sur le site https://tarteaucitron.io/fr/, les cookies obligatoires ne peuvent pas être refusés.
A priori, il est nécessaire de prévoir un opt-out également sur ces cookies.
Est-il prévu d'implémenter cette fonctionnalité ? Si oui dans quel délai ?

Merci d'avance :)
Nina

**Comment by AmauriC** [comment]
Bonjour Nina,

Non, les cookies nécessaires au bon fonctionnement du site n'ont pas besoin d'autorisation (gestion de la connexion d'un membre, gestion d'un panier d'achat, cookie tarteaucitron, ...).

**Comment by nina3am** [comment]
Bonjour Amauri,

Merci pour ta réponse (très) rapide ! ;)
Je reboucle avec AT Internet qui nous a demandé de prévoir un opt-out sur les cookies qui bénéficient d'une exemption.

Bonne journée,
Nina

**Comment by cyrilmonnom** [comment]
Bonjour Amauri,

Je pense que l'opt-out est à prévoir pour gérer des outils d'audience comme ATInternet et Matomo ...

Exemples : 
- https://helpcentre.atinternet-solutions.com/hc/fr/articles/360014430060-Opt-Out
- http://www.xiti.com/fr/optout.aspx

Bonne journée,
Cyril

**Comment by AmauriC** [comment]
C'est prêt et en cours de validation par ATInternet 👍

**Comment by cyrilmonnom** [comment]
Amauri,

Super nouvelle 👍

Cyril

**Comment by fvsadem** [comment]
@AmauriC 

Quand tu dis c'est prêt... ça se présentera sous quel forme ?

Merci

**Comment by AmauriC** [comment]
De la même manière que les autres services mais avec une option en plus pour être en optout.

**Comment by AnthonyIp** [comment]
Pour les cookies dans les helpers chat sont ils obligatoires?
