### ISSUE TITLE
The type attribute is unnecessary for JavaScript resources.

### ISSUE THREAD

**Issue by Klemart3D** [AmauriC/tarteaucitron.js#561]
I'm using W3C validator : https://validator.w3.org/

I have following warnings related to tarteaucitron:

<img width="1111" alt="type-js" src="https://user-images.githubusercontent.com/7419525/106786217-96e4ee80-664e-11eb-9e05-6044dae8214a.png">

A fix can be to remove all `type=text/javascript` from code source, is it conceivable?

https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.js#L1608
https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.services.js#L778

**Comment by AmauriC** [comment]
How to you embed the script? This is not the official way to do it, maybe a CMS plugin?

**Comment by Klemart3D** [comment]
I embed script like explained here: https://github.com/AmauriC/tarteaucitron.js#how-to-use

But it's unnecessary in HTML5 for W3C to add `type="text/javascript"` as property of `<script>` tag, it's redundant.

Sample: https://developer.mozilla.org/fr/docs/Web/HTML/Element/script#exemple_simple
Spec: https://html.spec.whatwg.org/#attr-script-type
StackOverflow: https://stackoverflow.com/questions/4243577/which-is-better-script-type-text-javascript-script-or-script-scr

**Comment by AmauriC** [comment]
Ok, thanks. Can you submit a PR?

**Comment by Klemart3D** [comment]
Can you check with https://validator.w3.org/ some websites where tarteaucitron is installed to see if you get same warnings?

**Comment by AmauriC** [comment]
Same on https://tarteaucitron.io

**Comment by Klemart3D** [comment]
Here's whats I suggests: #564

I can't fix others warnings of tarteaucitron.io but It must remove at least one warning:
https://validator.w3.org/nu/?doc=https%3A%2F%2Ftarteaucitron.io
