### ISSUE TITLE
Bandeau ne s'affiche pas

### ISSUE THREAD

**Issue by watsab** [AmauriC/tarteaucitron.js#562]
Hello ! 

J'essaie d'implémenter tarte au citron pour la gestion des cookies et je ne comprends pas, le bandeau ne s'affiche pas. Pourtant, le script est bien chargé et initialisé, et je trouve bien dans le DOM le `tarteaucitronRoot` qui a aussi `tarteaucitronAlertBig` :
<img width="826" alt="Capture d’écran 2021-02-03 à 23 42 33" src="https://user-images.githubusercontent.com/15378800/106819111-a2014400-6679-11eb-8edd-8e46affedc82.png">

Mais quand j'inspecte l'élément `tarteaucitronAlertBig` je vois qu'il a la règle css : `display: none`. Est-ce que le problème vient de là ?
 Ci-dessous l'init de tarteaucitron :
```
tarteaucitron.init({
      hashtag: "#tarteaucitron",
      highPrivacy: false,
      orientation: "bottom",
      adblocker: false,
      showAlertSmall: true,
      cookieslist: true,
      removeCredit: false,
      DenyAllCta: false,
      showIcon: false,
    });
```

Est-ce que j'oublie quelque chose ? J'avoue que je sèche un peu...
Merci d'avance

**Comment by pierretux** [comment]
Bonjour,

Tu as une url que l'on voit le soucis ?

**Comment by AmauriC** [comment]
Est-ce qu'un service a été déclaré? Si le script n'a rien à faire, le bandeau ne s'affiche pas.

**Comment by watsab** [comment]
> Est-ce qu'un service a été déclaré? Si le script n'a rien à faire, le bandeau ne s'affiche pas.

Ah oui effectivement je n'ai pas déclaré de service. Mais pour le moment, il n'y a pas de service en particulier à afficher... en dehors de cookies de fonctionnement du site je n'ai rien d'autre. Est-ce qu'il y a un affichage possible pour ce cas ?
Merci d'avance

**Comment by AmauriC** [comment]
Du coup non et ce n’est pas utile d’ennuyer les visiteurs avec un bandeau qui ne sert à rien ; )

**Comment by watsab** [comment]
OK très bien ! Je pensais que le bandeau était obligatoire à partir du moment où on utilisait des cookies... je suis pas forcément à jour pour tout ce qui est RGPD 😉 
Merci en tout cas !
