### ISSUE TITLE
Questions sur les statistiques (version PRO)

### ISSUE THREAD

**Issue by RaphMo** [AmauriC/tarteaucitron.js#565]
Bonjour,

N'ayant pas trouvé d'informations à ce sujet, j'ai 2 questions concernant les statistiques offertes par la version PRO :

- Est-ce que le taux d’activation est bien fondé sur le nombre de visiteurs ayant acceptés, et pas le nombre d’affichage de page avec traceurs activés ? Par exemple si un utilisateur consent et regarde deux pages, et qu’un autre refuse et regarde une page, j’ai bien 50% de taux d’activation, pas 66,6%.
- Est-ce que l'on peut savoir le taux de personnes ayant refusé expressément les cookies ? Ainsi que ceux n’ayant fait aucune action et ceux ayant fermé directement la popin ?

Merci d'avance à ceux qui pourront m'éclairer sur le sujet. Cordialement,

**Comment by AmauriC** [comment]
Bonjour,

tarteaucitron n'utilise aucune donnée concernant l'internaute, les stats sont donc uniquement basées sur les pages vues.

Dans votre exemple le taux d'activation sera de 66%

Impossible d'avoir un chiffre plus précis que ce qui est dispo (refus, aucune action, ..).

**Comment by RaphMo** [comment]
Bonjour,

Merci pour les précisions et la réponse. Je clos le ticket !
