### ISSUE TITLE
Google Adwords (remarketing)

### ISSUE THREAD

**Issue by Dadox** [AmauriC/tarteaucitron.js#566]
Bonjour,

J'essaie d'intégrer un tracking Google Adwords (remarketing) mais le script tarteaucitron genère une erreur : 
Uncaught ReferenceError: AW is not defined

tarteaucitron.user.adwordsremarketingId = AW-XXXXX; => Erreur

tarteaucitron.user.adwordsremarketingId = 'AW-XXXXX'; => OK

Du coup dans l'admin (tarteaucitron.io) j'ai du forcer les quotes. Peut-être le préciser ou forcer les quotes

**Comment by AmauriC** [comment]
Merci! C'est corrigé ; )

**Comment by Dadox** [comment]
Super, merci
