### ISSUE TITLE
Surcharge JS : Texte

### ISSUE THREAD

**Issue by cyrilmonnom** [AmauriC/tarteaucitron.js#569]
Bonjour Amauri,

Est-il possible de faire une surcharge des textes présents dans le dossier "lang" ? Le but étant d'avoir un master et ensuite avoir la possibilité de personnaliser certains messages en fonction des sites qui utilises le script ?

Si oui comment faire l'appel ?

Merci par avance,

**Comment by AmauriC** [comment]
Hello

C'est possible, il faut définir une variable avant le chargement du script:

```
var tarteaucitronCustomText = {
  "alertBigPrivacy": "Ce site utilise des cookies et vous donne le contrôle sur ceux que vous souhaitez activer",
  "acceptAll": "Tout accepter",
};
```

**Comment by cyrilmonnom** [comment]
Merci beaucoup. Je viens de tester et cela fonctionnement parfaitement.
