### ISSUE TITLE
CSS boutons et fount.artequalswork/fount.js

### ISSUE THREAD

**Issue by Ludosane** [AmauriC/tarteaucitron.js#571]
Bonjour,

En cherchant à modifier le comportement au clic des bouton "Ok, tout accepter" et "Tout refuser" et plus précisément du filet de couleur (noir et blanc) avec un effet radius sur les boutons quand on clique dessus, j'ai découvert presque par hasard avec Chrome Dev du code que je ne trouve pas dans vos fichiers .js et plus particulièrement cet appel vers ce fichier externe qui semble avoir la main sur une partie de la css de ces boutons :
<script src="https://fount.artequalswork.com/fount.js" id="fountscript"></script>.

Si cela est possible, je souhaiterais savoir comment supprimer cet appel. 

Merci d'avance pour votre aide.

Ludovic 

PS : j'ai essayé de copier le code générer par ce fichier mais la fonction "insert code' ne me le permet pas.

**Comment by AmauriC** [comment]
🧐 Ce n’est pas intégré dans le script, il n’y a aucune dépendance ou appel externe sur tarteaucitron.

Peut être une extension de navigateur ?

**Comment by Ludosane** [comment]
Je ne sais pas trop, je suis tombé vraiment dessus par hasard et je n'arrive pas à le retrouver pour tout vous dire. Mais alors, comment faire pour supprimer ces filets quand on clique sur les boutons ?

**Comment by AmauriC** [comment]
Je ne suis pas sûr de comprendre ce qu’est ce filet. Une capture d’écran possible?

**Comment by Ludosane** [comment]
C'est un filet (avec un radius) qui apparaît sur les boutons quand on clique dessus, le voici ci-joint :
![bouton-filet](https://user-images.githubusercontent.com/79103801/107976048-40b26c80-6fb9-11eb-9a16-1f0bb77c5c39.png)

**Comment by Ludosane** [comment]
Je suis désolé de vous avoir parlé au début de ce fichier fount.js, c'est vous qui aviez raison : je viens de trouver qu'il venait d'un de mes plugins pour trouver les polices sur les sites  :-( 
En revanche l'origine de ce filet noir reste un mystère pour moi.

**Comment by AmauriC** [comment]
Ce ne serait pas le `:focus-visible` pour la navigation au clavier?

Après l'url du site je pourrai regarder plus en détail ; )

**Comment by Ludosane** [comment]
Je n'utilise que votre .css dans mon test, je n'ai donc pas de focus-visible. Grand merci à vous pour votre proposition de regarder cela plus en détail, voici l'URL de mon test : https://cutt.ly/ek0G2MQ

**Comment by AmauriC** [comment]
C'est bien le focus par default de Chrome sur les boutons.

Par exemple: `button.tarteaucitronCTAButton:focus {
    outline: 0px;
}` le supprime ; )

**Comment by Ludosane** [comment]
J'ai cherché partout et je n'ai pas pensé à Chrome et là je m'en veux :-) En tout cas merci mille fois Amauric pour votre aide si rapide et si efficace et un énorme merci aussi pour votre script !
