### ISSUE TITLE
Navigation privée et GTM

### ISSUE THREAD

**Issue by cyrilmonnom** [AmauriC/tarteaucitron.js#573]
Bonjour,

J'appelle le script et les services de tarte au citron via GTM. En navigation privé, le script ne se charge pas. Est-ce normal ? Y a t il une configuration spécifique à mettre en place ?

Quand j'appelle directement le script et les services directement via la page (sans passer par GTM), le script apparait bien même en navigation privé.

Merci par avance,

**Comment by AmauriC** [comment]
Il n'y a pas de différence technique entre navigation normal et privée mais le script n'est pas fait pour être chargé par un autre tag manager.

Vous êtes sur que ça fonctionne correctement en navigation classique?

**Comment by cyrilmonnom** [comment]
oui cela fonctionne en navigation classique. Je vais faire de nouveaux tests

**Comment by cyrilmonnom** [comment]
Je viens de faire de nouveaux tests et cela fonctionne correctement. Encore merci du support
