### ISSUE TITLE
Tarte au citron génère des erreurs js avec un bloqueur de pub 

### ISSUE THREAD

**Issue by jmoupah** [AmauriC/tarteaucitron.js#576]
Avec uBlock origin configuré pour masquer les bandeaux de cookies (filtre "Nuisances > Fanboy’s Annoyance" activé), il y a 3 erreurs js. A tester sur https://tarteaucitron.io/fr/ par exemple.

```
Uncaught ReferenceError: $ is not defined
    <anonymous> https://tarteaucitron.io/fr/:399
fr:399:1

Uncaught ReferenceError: $ is not defined
    worker https://tarteaucitron.io/fr/:428
    <anonymous> https://tarteaucitron.io/fr/:442
fr:428:2

Uncaught ReferenceError: $ is not defined
    <anonymous> https://tarteaucitron.io/fr/:668
fr:668:1

```

**Comment by AmauriC** [comment]
$ est l’alias jQuery, si ublock bloque tout sur tarteaucitron.io/* je ne peux rien y faire 🙄

**Comment by Shnoulle** [comment]
dailleurs avec Fanboy’s Annoyance : je ne peux pas commenter sur github,

**Comment by AmauriC** [comment]
J'ai testé et c'est le filtre `/tarteaucitron.` qui bloque toutes les requêtes de https://tarteaucitron.io/

![Capture d’écran 2021-02-21 à 09 06 35](https://user-images.githubusercontent.com/8764074/108619319-357d9780-7424-11eb-92fc-d25670d9d6b3.png)

Idem pour commenter issue. Je pense qu'il est juste temps de supprimer ce filtre ^^

**Comment by jmoupah** [comment]
Merci pour vos retours, effectivement Fanboy’s Annoyance semble un peu strict !

Une question : y a t'il un moyen pour que le script ne génère pas d'erreurs js même s'il est bloqué par uBlock ? Car l'erreur générée peut planter javascript et donc d'autres fonctionnalités légitimes (j'ai le cas sur un site où l’insertion d'une carte OSM est plantée).
