### ISSUE TITLE
sources de tarteaucitron.io/fr/test/ publiquement accessibles ?

### ISSUE THREAD

**Issue by Baltazardoung** [AmauriC/tarteaucitron.js#577]
Bonjour,

Au sein d'une autre demande, j'ai pu découvrir l'existence de l'outil "https://tarteaucitron.io/fr/test/ " permettant de tester l'installation de tarte au citron.

Intéressé par cet outil, je me demandais si le code associé au coeur de cette validation était publiquement accessible à travers un dépôt sur GitHub ou autres ? Avec l'idée avouée et non dissimulée de s'en inspirer pour répondre à un besoin similaire au sein d'un CMS où nous avons intégré TAC.

Merci de vos précisions et aides,

**Comment by AmauriC** [comment]
Bonjour 👋 

Le code du script n’est pas dispo mais les infos pour en faire un similaire sont dispo ici: https://tarteaucitron.io/json.php

celui sur tarteaucitron récupère le code source de la page et recherche ‘detection.tracker’ 😉

**Comment by Baltazardoung** [comment]
🤟  Parfait, merci pour ces infos et ce partage... Cela va grandement me faciliter la tâche !! :smile:

... Je clôture  !
