### ISSUE TITLE
Mise à jour tarteaucitron

### ISSUE THREAD

**Issue by coccinelly** [AmauriC/tarteaucitron.js#578]
Bonjour,
Bon, cela va être une question bête pour tous les pros... Comment mettre à jour manuellement tarteaucitron quand une nouvelle version sort ?
Merci de votre aide !

**Comment by AmauriC** [comment]
Hello

Il suffit de retélécharger les fichiers et de remplacer les anciens ; )

**Comment by coccinelly** [comment]
OK, et les petites modif que j'ai pu y faire, eh ben je les y remets, c'est ça ?

**Comment by AmauriC** [comment]
Oui, si vous avez modifié les fichiers, il faut remettre ces changements.

Si ça peux intéresser tout le monde, n'hésitez pas à proposer un PR ; )

**Comment by coccinelly** [comment]
Personne ne rigole : PR, c'est Pull request, c'est ça ?
Mes pts changements, pour l'instant c'est seulement ta ligne de css pr la scrollbar qui n'apparaissait pas sous Edge et Chrome.
Merci beaucoup en tout cas !

**Comment by AmauriC** [comment]
Yes, c'est bien ça : ) Ca permet de proposer le changement et si je l'accepte, ce sera dispo pour tout le monde.

Si c'est juste pour la scrollbar, pas utile ; )

**Comment by coccinelly** [comment]
Dernière question : la partie à placer dans le head ne change pas avec les mises à jour ?

**Comment by coccinelly** [comment]
Ok, eh bien c'est drôlement bien pensé tout ça !
Merci encore !
