### ISSUE TITLE
Uncaught TypeError sur installation WordPress

### ISSUE THREAD

**Issue by Shemzone** [AmauriC/tarteaucitron.js#58]
Bonjour à tous.
J'essaie d'installer Tarteaucitron sur un site Wordpress mais je rencontre des erreurs (voir console ci-après). J'ai testé sur une page simple PHP statique sans problème.
Le dossier Tarteaucitron est le même.
Des idées ?

Merci
> tarteaucitron.js:337 Uncaught TypeError: Cannot set property 'push' of undefined 
>     at tarteaucitron.js:337
>     at HTMLScriptElement.script.onreadystatechange.script.onload [as onreadystatechange] (tarteaucitron.js:1107)
> (anonymous) @ tarteaucitron.js:337
> script.onreadystatechange.script.onload @ tarteaucitron.js:1107
> load (async)
> addScript @ tarteaucitron.js:1103
> (anonymous) @ tarteaucitron.js:323
> script.onreadystatechange.script.onload @ tarteaucitron.js:1107
> load (async)
> addScript @ tarteaucitron.js:1103
> (anonymous) @ tarteaucitron.js:206
> script.onreadystatechange.script.onload @ tarteaucitron.js:1107
> load (async)
> addScript @ tarteaucitron.js:1103
> load @ tarteaucitron.js:205
> (anonymous) @ tarteaucitron.js:34
> load (async)
> init @ tarteaucitron.js:33
> (anonymous) @ (index):56
> tarteaucitron.js:1032 Uncaught TypeError: Cannot read property 'length' of undefined
>     at Object.number (tarteaucitron.js:1032)
>     at proPing (tarteaucitron.js:1261)

**Comment by element303** [comment]
Bonjour, 
une fois tarteaucitron initialisé, 
<script type="text/javascript" src="/tarteaucitron/tarteaucitron.js"></script>
<script type="text/javascript">
tarteaucitron.init({
   /* la config */
});
</script>

il faut ajouter un service en bas de page juste avant la balise </body>
Au hasard la gestion de google tag manager par exemple : 
<script type="text/javascript">
        tarteaucitron.user.googletagmanagerId = 'GTM-XXXX';
        (tarteaucitron.job = tarteaucitron.job || []).push('googletagmanager');
        </script>

    </body>
</html>

Est ce que tu as bien au moins un service paramétré ?

**Comment by Shemzone** [comment]
Bon... Il suffit que j'y retourne pour que ça fonctionne. 
Peut-être un problème de cache
