### ISSUE TITLE
Script du Fallback reste même après "Tout Accepter"

### ISSUE THREAD

**Issue by fvsadem** [AmauriC/tarteaucitron.js#581]
Bonjour,

J'ai créé plusieurs customs services qui fonctionnent correctement. Cependant ....
Je ne sais pas si c'est un bug mais lorsque l'on arrive sur le site pour la 1ère fois, le fallback des services custom s'activent. Alors que je pensais qu'ils ne s'activaient que lorsqu'on refusait le cookie.

Pour mon cas, les fallbacks ajoutent des scripts "refusés". La fenêtre du choix se lance.
Mais lorsque l'on clique sur "Tout Accepter", j'ai les autres scripts "acceptés" qui se rajoutent.
Par contre, cela n'a pas enlevé les scripts du fallback "refusé" car, il n'y a pas de refresh de la page.

Quelle est la meilleure solution pour ne plus avoir ces doublons ?

Perso, je pense qu'on ne devrait pas lancer les fallback tant qu'on est en statut "Wait"

Merci

**Comment by AmauriC** [comment]
Hello,

Les fallback sont utiles dès le début pour afficher un bouton permettant d'accepter sur les vidéos par exemple.

Je ne comprend pas bien ce que vous voulez faire mais ce n'est probablement pas la bonne méthode ; )

**Comment by fvsadem** [comment]
C'est juste que lors de la 1ere visite, on a les fallbacks qui s'activent. Moi j'ai des scripts spécifiques aux non consentement.
Si on clique sur "Tout Accepter", les scripts "Consentement OK" s'ajoutent à la suite des non consentement.
J'ai donc à la fois des scripts non consenti et des consenti....
Si on recharge la page, pas de souci.

C'est pas très grave mais je trouve ça bizarre.

**Comment by AmauriC** [comment]
Ce n'est pas le comportement de base de tarteaucitron.
Si vous avez des modifications sur les `fallback`, faites en aussi sur les `js` pour supprimer les fallback ou forcer un rechargement de la page.

**Comment by fvsadem** [comment]
Mouai...

Pour être plus clair, j'ai besoin d'avoir un script même si l'utilisateur refuse le cookie.
J'ai un paramêtre à passer au script *consent=1* si l'internaute autorise, sinon *consent=0*.

Du coup, j'ajoute mon script dans "js" avec *consent=1* et dans "fallback" j'ai le même script avec *consent=0*.
Le problème c'est ce double ajout lorsque l'on clique sur "Tout Accepter" sur la 1ère popup (pas la popup de personnalisation).

Peut-être y a-t-il une autre façon de faire ? 

Merci

**Comment by AmauriC** [comment]
Du coup, dans le fallback avant de charger le script vérifier si le statut est différent de wait:

```
if (tarteaucitron.cookie.read().indexOf('ID_DU_SERVICE=wait') !== -1) {
    // chargement 
}
```

**Comment by fvsadem** [comment]
Merci

C'était une bonne idée mais, il y a un nouveau problème. 

Lorsque je clique sur "Tout Refuser" sur la 1ere popup (toujours en statut Wait), ça ne repasse pas dans le fallback.
Du coup le script ne se génère pas.

Je pense que je vais chercher à supprimer les 1ers fallback plutôt...
