### ISSUE TITLE
Ajouter un bouton "Close"

### ISSUE THREAD

**Issue by fvsadem** [AmauriC/tarteaucitron.js#582]
Bonjour,

J'utilise la fenêtre modal (en plein milieu de l'écran) pour afficher la 1ere page de présentation des cookies (le statut Wait).

Nous sommes obligé de cliquer sur un des choix "Tout Accepter", "Tout Refuser" ou "Personnaliser".
Il semble que le *cookie wall* ne soit pas recommandé par la CNIL :
https://www.cnil.fr/fr/questions-reponses-sur-les-lignes-directrices-modificatives-et-la-recommandation-cookies-et-autres 
(voir section 14)

Je propose d'ajouter un bouton "Fermer" afin de fermer la fenêtre car je trouve que cela est bloquant actuellement. On ne devrait pas forcer un utilisateur à choisir dès sa première venue sur notre site la façon dont il veux gérer ses cookies. 

Quid de la gestion des cookies si on ferme...

Qu'est que vous en pensez ?

Merci

**Comment by AmauriC** [comment]
Hello,

C'est déjà possible avec l'option `"closePopup": true` 👍

**Comment by fvsadem** [comment]
Merci...
Je me disais bien qu'il manquait une info comme ça !
