### ISSUE TITLE
Changement des boutons > passer à un toggle switch

### ISSUE THREAD

**Issue by VilainPtiZombie** [AmauriC/tarteaucitron.js#583]
Bonjour et déjà merci pour votre script.

Je souhaite passer les boutons "Autoriser" / "Interdire" en toggle Switch, qui dans le cas présent pour mes sites web et mes contraintes est nécessaire.

J'ai déjà en quelques sortes commencer à modifier le script pour intégrer le toggle en html mais j'aimerais si possible avoir la méthode pour que ça ne soit pas uniquement visuel.

Ci-dessous l'intégration dans le html : 
`html += ' <div class="rf-toggle">';
            html += '     <input type="checkbox" class="rf-toggle__input" id="rf-dark-mode-toggle-switch' + service.key + '">';
            html += '     <label class="rf-toggle__label" for="rf-dark-mode-toggle-switch' + service.key + '" data-rf-checked-label="Activé" data-rf-unchecked-label="Désactivé"></label>' ;
            html += ' </div>';            `

Je suppose qu'il faudrait que je change ces lignes : 
`            tarteaucitron.addClickEventToId(service.key + 'Allowed', function () {
                tarteaucitron.userInterface.respond(this, true);
            });

            tarteaucitron.addClickEventToId(service.key + 'Denied', function () {
                tarteaucitron.userInterface.respond(this, false);
            });            `

Mais n'étant pas un pro du js je préfère demandé un avis avant de tout casser, ahah

Cordialement,

**Comment by VilainPtiZombie** [comment]
Bonjour, je me permet de vous relancer.

Si quelqu'un d'autre dispose de la solution n'hésiter pas non plus, j'ai vus que quelqu'un avait prévus la même chose sur Codepen : [https://codepen.io/helenep/pen/xNevgM](https://codepen.io/helenep/pen/xNevgM)

Cordialement,

**Comment by AmauriC** [comment]
En effet ça fonctionne bien sur le codepen! Je note et j'essai de faire en sorte que ce soit dispo rapidement 👍

**Comment by gmiannay** [comment]
Bonjour,
Avez-vous une date de planifiée pour la mise en place de cette fonctionnalité?
Cordialement,

**Comment by VilainPtiZombie** [comment]
> En effet ça fonctionne bien sur le codepen! Je note et j'essai de faire en sorte que ce soit dispo rapidement 👍

Je me permet de relancer si possible :) ?

**Comment by AmauriC** [comment]
Je n'ai pas trop de temps en ce moment mais de mon côté c'est toujours dans la todo list.
Si il y a un PR entre temps, je le validerai ; )

**Comment by VilainPtiZombie** [comment]
Bonjour,
Je comprends tout a fait, je fais toujours des de mon coté mais de réel solution pour le moment.

**Comment by xavOSEF** [comment]
Hello !
Toujours pas de toggle switches en vue sur tarteaucitron ? 😅
J'essaye de comprendre comment ça a été fait dans le codepen cité plus haut mais sans succès pour l'instant
