### ISSUE TITLE
Paramétrage "cookieDomain"

### ISSUE THREAD

**Issue by cyrilmonnom** [AmauriC/tarteaucitron.js#584]
Bonjour,

Je gère actuellement un site comportant des sous-domaines : 
- https://mondomaine.fr
- https://monsousdomaine1.mondomaine.fr
- https://monsousdomaine2.mondomaine.fr
- https://monsousdomaine3.mondomaine.fr

Le passage du domaine à un sous-domaine est transparent pour l'utilisateur dans sa navigation. Les cookies doivent être partagés.

Si je comprend bien je dois paramétrer l'option : avec "cookieDomain": ".mondomaine.fr", ?

Merci par avance,

**Comment by AmauriC** [comment]
C'est bien ça : )

**Comment by cyrilmonnom** [comment]
En grand merci
