### ISSUE TITLE
Cookies obligatoires > Intitulé spécifique du bouton d'activation

### ISSUE THREAD

**Issue by serialplayer** [AmauriC/tarteaucitron.js#585]
Utilisateurs de Tarteaucitron sur nos projets, on discutait avec des amis des cookies non désactivables, et du fait que le bouton "accepter" affiche le même intitulé que pour les cookies désactivables était confusant pour les utilisateurs.

Mettre au même niveau le fait d'accepter ou de refuser les autres types de cookies et ceux-ci peut donner l'impression qu'une action est possible, alors que non.

On se disait donc que ce serait une bonne idée de proposer de base la possibilité de personnaliser l'intitulé de ce bouton dans le fichier de langues pour pouvoir afficher par exemple "toujours actif" ou autre, comme le font des outils comme OneTrust, pour pouvoir le différencier des actions effectivement possibles sur les cookies.

Le bouton pourrait aussi être disabled, mais ca risque d'être confondu avec l'état de tous les autres boutons lorsqu'ils ne sont pas cliqués. L'intitulé du bouton me semble suffisant pour faire la différence.

Sans ça, super projet, merci beaucoup pour votre travail ! 💪

**Comment by AmauriC** [comment]
En effet c'est une bonne idée : )

Je n'ai pas trop de temps en ce moment mais je note.
Si quelqu'un peux proposer un PR, je le valide rapidement 👍
