### ISSUE TITLE
ajouter le service pingdom

### ISSUE THREAD

**Issue by brunotran** [AmauriC/tarteaucitron.js#586]
bonjour
pouvez vous ajouter le service pingdom : 

voici le script, ce qui change c'est la valeur de l'id

<script>
var _prum = [['id', '54bXXX13a'],
['mark', 'firstbyte', (new Date()).getTime()]];
(function() {
var s = document.getElementsByTagName('script')[0]
, p = document.createElement('script');
p.async = 'async';
p.src = '//rum-static.pingdom.net/prum.min.js';
s.parentNode.insertBefore(p, s);
})();
</script>

quand pensez-vous pouvoir le faire ?

merci

**Comment by AmauriC** [comment]
C'est ajouté ; )
