### ISSUE TITLE
Recaptcha V3

### ISSUE THREAD

**Issue by cyrilmonnom** [AmauriC/tarteaucitron.js#587]
Bonjour,

Le service de Google RE-CAPTCHA dans sa version 3 est-elle prise en compte par le plugin ? https://developers.google.com/recaptcha/docs/v3

Merci par avance,

Cyril

**Comment by zeperic** [comment]
Bonjour,

Je suis en train d'intégrer la prise en charge de Recaptcha V3 pour un formulaire de contact en utilisant la méthode la plus simple permettant de lier automatiquement recaptcha à un bouton. TAC prend en charge le service en ajoutant une div d'alerte à la place du libellé du bouton mais je rencontre un bug :  il efface durablement le libellé du bouton, même en autorisant le service .
Pour info, j'utilise la version CDN du script
Voir les extrait ci-dessous
![autorize](https://user-images.githubusercontent.com/20610990/109670914-e34f1b80-7b73-11eb-89b6-438056198088.png)
![deny](https://user-images.githubusercontent.com/20610990/109670918-e3e7b200-7b73-11eb-94ec-425856fd12d1.png)
![normal](https://user-images.githubusercontent.com/20610990/109670919-e4804880-7b73-11eb-986c-39bb36d6d6f5.png)

**Comment by maze13** [comment]
The bug still occurs in v1.9.7.

**Comment by AmauriC** [comment]
Not sure to understand the problem. Do you have a live example?

**Comment by maze13** [comment]
Unfortunately not live over the internet. But I can explain the error to you with code examples.

With Google reCAPTCHA v3 you add the captcha to a button:

```
<button type="submit" class="g-recaptcha" data-sitekey="xxx" data-callback="onSubmit" data-action="submit">send</button>

```

Add the service:

```
{# Google reCAPTCHA #}
<script type="text/javascript">
    tarteaucitron.user.recaptchaapi = 'xxx';
    (tarteaucitron.job = tarteaucitron.job || []).push('recaptcha');
</script>
```

After that you have to accept the service:

```
<button type="submit" class="g-recaptcha" data-sitekey="xxx" data-callback="onSubmit" data-action="submit">
   <div class="tac_activate tac_activate_recaptcha">
      <div class="tac_float">
         reCAPTCHA ist deaktiviert.
         <button type="button" class="tarteaucitronAllow" id="Eng51715edrecaptcha">
            <span class="tarteaucitronCheck" aria-hidden="true"></span> Erlauben
         </button>
      </div>
   </div>
</button>
```

After accepting the button text ist empty:

```
<div><div class="grecaptcha-badge" data-style="none" style="width: 256px; height: 60px; position: fixed; visibility: hidden;"><div class="grecaptcha-logo"><iframe title="reCAPTCHA" src="https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=xxx&amp;co=yyy&amp;hl=de&amp;v=zzz&amp;size=invisible&amp;sa=submit&amp;cb=pdpfh8sgr5f9" role="presentation" name="a-dpifupyjerbd" scrolling="no" sandbox="allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation" width="256" height="60" frameborder="0"></iframe></div><div class="grecaptcha-error"></div><textarea id="g-recaptcha-response" name="g-recaptcha-response" class="g-recaptcha-response" style="width: 250px; height: 40px; border: 1px solid rgb(193, 193, 193); margin: 10px 25px; padding: 0px; resize: none; display: none;"></textarea></div><iframe style="display: none;"></iframe></div>
<button type="submit" class="g-recaptcha" data-sitekey="xxx" data-callback="onSubmit" data-action="submit"></button>
```

Probably caused by the service in tarteaucitron.service.js:

```
// recaptcha
tarteaucitron.services.recaptcha = {
[...]
tarteaucitron.fallback(['g-recaptcha'], '');
[...]
```

**Comment by AmauriC** [comment]
Ok. You can add a text when it's loaded with:

```
document.addEventListener("recaptcha_loaded", function(){
   tarteaucitron.fallback(['g-recaptcha'], 'send');
});
```

**Comment by maze13** [comment]
Ok, thank you!
