### ISSUE TITLE
Pas un problème mais une idée pour Wordpress

### ISSUE THREAD

**Issue by Shemzone** [AmauriC/tarteaucitron.js#59]
Que se passe-t'il si un utilisateur désactive le Javascript ou si son navigateur ne permet pas le Javascript ? ça peut arriver dans des environnements contraints par certaines DSI, j'ai déjà vu ça. 
Il faudrait donc pouvoir proposer une alternative sans Js.

Voilà ce que j'ai fait.
Sur WordPress, plutôt que d'afficher le showAlertSmall (qui est plutôt gênant quand il est affiché de façon permanente), j'ai préféré utiliser un lien de menu "Gestion des cookies" en pied de page à la place.
Or, pas possible avec WordPress d'appeler une fonction JS.

J'ai créé un lien de menu vers une page du genre "Gestion des données privées" qui contient la marche à suivre pour gérer les cookies dans son navigateur. À la fin de l'URL j'ai ajouté #gestioncookies, ce qui donne https://www.monsite.fr/mapage#gestioncookies.
Dans mon fichier functions.php, j'ai ajouté la fonction suivante :
`add_filter('walker_nav_menu_start_el', 'gestioncookies_replace_hash', 999);
/**
 * Replace #gestioncookies with js
 * @param string $menu_item item HTML
 * @return string item HTML
 */
function gestioncookies_replace_hash($menu_item) {
    if (strpos($menu_item, '#gestioncookies"') !== false) {
        $menu_item = str_replace('#gestioncookies"', '" onclick="tarteaucitron.userInterface.openPanel(); return false;"', $menu_item);
    }
    return $menu_item;
}`

Si Js n'est pas activé, l'utilisateur ira vers la page du lien cité plus haut.
Sinon, la fenêtre modale s'affiche.

Bonne idée ou catastrophe ?

Fred

**Comment by AmauriC** [comment]
Bonne idée 👍 #59

Pour faciliter les choses, c'est possible en ajoutant une class à un lien :
`<a href="https://www.monsite.fr/mapage_cookie/" class="tarteaucitronOpenPanel">Cookies</a>`
