### ISSUE TITLE
Google Adwords (conversion)

### ISSUE THREAD

**Issue by fvsadem** [AmauriC/tarteaucitron.js#590]
Bonjour,

Il semble que le script générer par le job "googleadwordsconversion" ne soit plus à jour et ne remonte pas les bonnes infos.

D'après google (et vu par téléphone), il faut utiliser le nouveau script gtag :
```
<!-- Event snippet for Commandes conversion page -->
<script>
  gtag('event', 'conversion', {
      'send_to': 'XX-00000000/XXXXXXXXXXXXXXX',
      'value': 0.0,
      'currency': 'EUR'
  });
</script>
```

Comment on fait ça ?

Merci

**Comment by pierretux** [comment]
Bonjour,

Tu ne cherches pas #459 comme idée ?

**Comment by fvsadem** [comment]
@pierretux 
J'ai essayé hier et j'arrive au même résultat.

Pour être plus clair, la personne qui s'occupe de l'analyse des données chez nous a un souci avec la remontée des infos de la conversion Adwords.

Il semble que le nom de la page ne remonte pas correctement à chaque fois (déjà ça c'est bizarre car des fois c'est bon).
Il a vu avec un gars de google qui lui a dit qu'on utilisé une version obsolète. Il lui a dit qu'il fallait utiliser les scripts "générer par eux". Le Global Site Tag et le script de conversion. Il me propose de mettre ces scripts sans utiliser un CMP.... chose que je refuse.

En utilisant TAC, Il semble qu'il n'y ai pas de souci via l'extension "Tag Assistant" (de google).
J'ai quand même pu constater une légère différence avec ou sans TAC dans la génération de l'url du script "www.googleadservices.com/pagead/conversion/XXXXX?random..." alors que "www.googleadservices.com/pagead/conversion_async.js" (du service googleadwordsconversion) sont identiques avec ou sans TAC.

Je suis assez perplexe sur les dires du gars de google...
