### ISSUE TITLE
Personnalisation

### ISSUE THREAD

**Issue by AnthonyIp** [AmauriC/tarteaucitron.js#602]
Bonjour, 

Je souhaiterais savoir comment pouvons nous modifier la date d'expiration du cookie et changer les traductions ainsi que les icônes et images lorsque l'on fait une installation manuelle?

Merci

**Comment by VilainPtiZombie** [comment]
Bonjour, 

Pour changer la durée : Tarteaucitron.js ligne 13 tu cherches la valeur "timExpire" qui est set à : "31536000000" (365jours) 
Garde la valeur en milliseconde.

Pour la traduction tout se trouve dans : tarteaucitron > lang > tarteaucitron.XX.js (XX = ta langue, donc FR je suppose).

Pour les icones cela dépends de quoi tu parles mais, si c'est celle des boutons de validations ou interdire c'est : 
Tarteaucitron > CSS 
Ligne  ~ 619

`#tarteaucitronRoot .tarteaucitronCross::before {
    content: '\2717';
    display: inline-block;
    color: white;
}

#tarteaucitronRoot .tarteaucitronCheck::before {
    content: '\2713';
    display: inline-block;
    color: white;
}

#tarteaucitronRoot .tarteaucitronPlus::before {
    content: '\271b';
    display: inline-block;
    color: white;
}`

Pour les images je ne vois pas ^^'

Cordialement,

**Comment by AmauriC** [comment]
Pour la durée d'expiration il y a une option (exemple pour 90 jours):
```
 var tarteaucitronExpireInDay = true,
          tarteaucitronForceExpire = 90;
```

Pour le texte aussi:
```
var tarteaucitronCustomText = {
  "alertBigPrivacy": "Ce site utilise des cookies et vous donne le contrôle sur ceux que vous souhaitez activer",
  "acceptAll": "Tout accepter",
};
```

A placer avant le chargement de la librairie dans les 2 cas.

**Comment by AnthonyIp** [comment]
@AmauriC 

L'icone de l'option **showIcon** est il modifiable?

Merci

**Comment by AmauriC** [comment]
Ca devrait fonctionner (à placer avant le chargement de tarteaucitron):
```
document.addEventListener("tac.root_available", function(){
    document.getElementById('tarteaucitronManager').querySelectorAll('img')[0].src = "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png";
});
```

**Comment by AnthonyIp** [comment]
@AmauriC 
Non cela ne marche pas.

De plus, est-il possible de changer le "middleBarHead" par une image ? ou c'est seulement une string ou emoji ?

Merci

**Comment by AmauriC** [comment]
Une erreur visible dans la console?

Pour `middleBarHead` c'est uniquement du texte.

**Comment by AnthonyIp** [comment]
> Une erreur visible dans la console?
> 

Pas du tout, j'ai l'impression qu'il ne détecte pas l'évent.

**Comment by AmauriC** [comment]
Testé et approuvé à l'instant ; )

```
addEventListener("DOMContentLoaded", function() {
   window.addEventListener('tac.root_available', function() {
       document.getElementById('tarteaucitronManager').querySelectorAll('img')[0].src = "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png";
    });
});
```

**Comment by AnthonyIp** [comment]
> Testé et approuvé à l'instant ; )
> 
> ```
> document.addEventListener("DOMContentLoaded", function() {
>    window.addEventListener('tac.root_available', function() {
>        document.getElementById('tarteaucitronManager').querySelectorAll('img')[0].src = "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png";
>     });
> });
> ```

Merci ! 🙏
