### ISSUE TITLE
Récupération Event dans GTM

### ISSUE THREAD

**Issue by fvsadem** [AmauriC/tarteaucitron.js#603]
Bonjour,

J'ai créé un custom service et j'aimerais que l'événement qui est déclenché lors de l'acceptation du consentement soit récupéré dans GTM.

Il semble que les posts suivant parlent de la même chose mais impossible de le faire fonctionner :
#410, #363, #334

Voilà mon code pour tester :
```
(tarteaucitron.job = tarteaucitron.job || []).push('test_gtm');
tarteaucitron.services.test_gtm = {
    "key": "test_gtm",
    "type": "analytic",
    "name": "Test GTM",
    "uri": "",
    "needConsent": true,
    "readmoreLink": "",
    "cookies": [],
    "js": function () {
         //Ici il n'y a volontairement rien car c'est géré par GTM
    }
};
```
Dans GTM, j’espérais récupérer l'event de cette manière :

![image](https://user-images.githubusercontent.com/55987370/110134599-daf21d00-7dcd-11eb-8a10-af299d1923c8.png)

Merci d'avance pour votre aide.

**Comment by AmauriC** [comment]
Un évenement est déclenché quand un service est activé:

```
document.addEventListener("test_gtm_loaded", function(){
    // test gtm est actif
});
```

**Comment by fvsadem** [comment]
@AmauriC 

OK, 
Je croyais que cet event se lançait lors du clic sur le consentement...

Si je comprends bien, l'event "test_gtm_loaded" ne se lance que lors du chargement du service.
Je devrais pourtant dans ce cas avoir au moins un hit via GTM... mais c'est pas le cas.

**Comment by AmauriC** [comment]
Il se lance quand le service est autorisé.
Dans cette fonction vous devriez pouvoir envoyer quelque chose à GTM. Je ne sais pas comment les déclencheurs fonctionnent.

**Comment by fvsadem** [comment]
OK merci je vois.

Je vais créer l'event dans la fonction pour pouvoir le récupérer dans GTM
