### ISSUE TITLE
Durée de vie des cookies

### ISSUE THREAD

**Issue by cyrilmonnom** [AmauriC/tarteaucitron.js#607]
Bonjour @AmauriC ,

Nous aimerions afficher la liste des cookies. Le plugin "tarteaucitron", permet de lister le nombre de cookie par service. Connais-tu un moyen de lister l'ensemble des cookies d'un service ou d'une site avec les informations suivants : 
- Nom
- Titulaire du cookie
- Finalité du cookie (fonctionnement, audience ...)
- Intitulé
- Durée de conservation

Merci pour ton aide,

Cyril

**Comment by AmauriC** [comment]
Le reste c'est dans le panneau de controle 🧐

**Comment by cyrilmonnom** [comment]
que je sois sur le panneau de contrôle ou se le site (et par service) je ne vois pas la durée de vie des cookies. A moins que je cherche mal :)

**Comment by AmauriC** [comment]
Exact! Je note pour une éventuelle évolution ; )
Dans l'immédiat je n'ai pas de solution :x

**Comment by cyrilmonnom** [comment]
Merci, tjs aussi efficace. :)
