### ISSUE TITLE
Personnalisation bannière

### ISSUE THREAD

**Issue by cyrilmonnom** [AmauriC/tarteaucitron.js#608]
@AmauriC ,

Nous avons la possibilité de surcharger le texte présent dans le cookie banner. Le texte est englobé par un span avec l'ID : "tarteaucitronDisclaimerAlert".

Nous utilisons le script présent sur le jsdelivr. Nous aimerions personnaliser le message avec des listes par exemple. Est-il possible de remplacer la balise span par une balise div ?

Merci par avance,

**Comment by AmauriC** [comment]
Vous pouvez modifier tous les textes via une variable js:
```
var tarteaucitronCustomText = {
  "alertBigPrivacy": "Ce site utilise des cookies et vous donne le contrôle sur ceux que vous souhaitez activer",
  "acceptAll": "Tout accepter",
};
```

Quel serait la différence entre une `div` et une `span`?

**Comment by cyrilmonnom** [comment]
Sur la surcharge, tu m'avais déjà donnée la solution :)

La balise DIV est un bloc qui peut contenir plusieurs types de balises. La balise span est un conteneur est permet d'identifier un texte par exemple. Dans les bonnes pratiques, si je souhaite mettre des balises ul,ol,li, elle doivent être entourées d'un div et non d'un span.

Si je n'ai pas la possibilité de changer le span en div, je vais m'arranger :)

Merci

**Comment by AmauriC** [comment]
Ok, compris, en effet ce serait bien mais ça risque de casser des intégrations actuelles :s
A voir donc, je note 👍

**Comment by AmauriC** [comment]
Je ferme parce que en l'état cette modification casserai trop d'installations.
Il est prévu de revoir totalement tac en séparant le code et le layout mais ce n'est pas encore prêt. A suivre donc 🙃
