### ISSUE TITLE
Configuration AT Internet

### ISSUE THREAD

**Issue by cyrilmonnom** [AmauriC/tarteaucitron.js#610]
Bonjour @AmauriC ,

Je paramètre l'outils "tarteautitron" dans GTM pour gérer l'activation ou la désactivation de AT Internet (xiti).

Voici l'appel

```
<script>
        tarteaucitron.user.atLibUrl = 'https://tag.aticdn.net/{{variabledemonsite}}/smarttag.js';
        tarteaucitron.user.atMore = function () {  };
        (tarteaucitron.job = tarteaucitron.job || []).push('atinternet');
</script> 
```
Cependant j'ai des erreur dans la console et le script AT Internet ne se lance pas.

`VM4067:8 Uncaught ReferenceError: ATInternet is not defined`

Mon appel est-il bon ?

Merci de ton aide,

Cyril

**Comment by AmauriC** [comment]
D'où viens la variable `ATInternet` ?

Avec tarteaucitron ATInternet est initialisé dans la variable `tag`, c'est peut-être le soucis.

**Comment by cyrilmonnom** [comment]
@AmauriC ,

Effectivement c'est une erreur de ma part sur la configuration du tag.

Désormais c'est fonctionnel. Par contre j'ai 3 tags qui apparaissent au lieu de seulement "AT Internet (privacy by design)"

![image](https://user-images.githubusercontent.com/15236461/111044470-40d34a00-8449-11eb-99cd-4332e308ba4e.png)

Y a t il une raison particulière ?

Merci par avance,

**Comment by AmauriC** [comment]
Oui et non, vous devriez en avoir 2 (avec le nouveau service minimal) mais pas 3 : /

Changez le tarteaucitron.job par `atinternethightrack` pour n'en avoir qu'un ; )

**Comment by cyrilmonnom** [comment]
Merci, donc cela donnerai : 
(tarteaucitron.job = tarteaucitron.job || []).push('atinternet');
par 
(atinternethightrack  = atinternethightrack || []).push('atinternet');

C'est bien ça ?

Merci de ton retour,

**Comment by AmauriC** [comment]
Non, je n'ai visiblement pas été clair ^^
`(tarteaucitron.job = tarteaucitron.job || []).push('atinternethightrack');`

**Comment by cyrilmonnom** [comment]
Merci :)

Donc cela donnera cela ? 

tarteaucitron.job.push('atinternetoptin');tarteaucitron.job.push('atinternetoptout');
tarteaucitron.user.atLibUrl = '//tag.aticdn.net/xxxxxxxxxx/smarttag.js';
        tarteaucitron.user.atMore = function () {         //AT Page Tagging   
        var tag = new ATInternet.Tracker.Tag();
        tag.page.set({
            name: page,
            chapter1: chapterA,
            chapter2: chapterB,
            chapter3: chapterC,
            level2: s2
        });
   tag.dispatch(); };
  (tarteaucitron.job = tarteaucitron.job || []).push('atinternethightrack');

**Comment by cyrilmonnom** [comment]
En réalisant les informations ci-dessus j'ai cela

![image](https://user-images.githubusercontent.com/15236461/111135811-619cbc00-857d-11eb-8319-fbab6de87a19.png)

Le lancement D'AT Internet ne se fait pas par défaut lors du premier chargement

**Comment by cyrilmonnom** [comment]
@AmauriC ,

Je viens de faire de nouveaux tests.

**TEST 1 : OK**
J'appelle le fichier tarteaucitron.js dans sa version 1.8.3 hébergé sur mon serveur.
J'appelle de cette façon le script
```
tarteaucitron.job.push('atinternetoptin');
tarteaucitron.job.push('atinternetoptout');
  tarteaucitron.user.atLibUrl = '//tag.aticdn.net/ID/smarttag.js';
        tarteaucitron.user.atMore = function () {         //AT Page Tagging   
        var tag = new ATInternet.Tracker.Tag();
        tag.page.set({
            name: page,
            chapter1: chapterA,
            chapter2: chapterB,
            chapter3: chapterC,
            level2: s2
        });
        tag.dispatch(); };
(tarteaucitron.job = tarteaucitron.job || []).push('atinternet');
```
Constat : Je script est bien actif par defaut et le tag se lance correctement.

**TEST 2 : KO**
J'appelle la version 20210306 du fichier tarteaucitron.js hébergé sur cdn.jsdelivr.net
J'appelle de cette façon le script
```
tarteaucitron.job.push('atinternetoptin');
tarteaucitron.job.push('atinternetoptout');
tarteaucitron.user.atLibUrl = '//tag.aticdn.net/ID/smarttag.js';
tarteaucitron.user.atMore = function () { //AT Page Tagging
var tag = new ATInternet.Tracker.Tag();
tag.page.set({
name: page,
chapter1: chapterA,
chapter2: chapterB,
chapter3: chapterC,
level2: s2
});
tag.dispatch(); };
(tarteaucitron.job = tarteaucitron.job || []).push('atinternethightrack');
```
Constat : J'ai 3 valeurs qui apparaissent au lien de 2. Et j'ai des erreurs sur 'AT Internet [minimal]' que je constate dans ma console lié au fichier service.

D'autres éléments doivent-ils être configurées sur la cette version ? Quelle est le comportement attendu avec la dernière version du fichier ?

Merci par avance,

**Comment by AmauriC** [comment]
Et celui-ci:

```
tarteaucitron.user.atLibUrl = '//tag.aticdn.net/ID/smarttag.js';
tarteaucitron.user.atMore = function () { //AT Page Tagging
window.tag.page.set({

name: page,

chapter1: chapterA,

chapter2: chapterB,

chapter3: chapterC,

level2: s2

});

window.tag.dispatch(); };
(tarteaucitron.job = tarteaucitron.job || []).push('atinternethightrack');
```

**Comment by cyrilmonnom** [comment]
Voici ce que j'ai avec la nouvelle recommandation
![image](https://user-images.githubusercontent.com/15236461/111188091-f242be80-85b4-11eb-89bf-f3f29611744d.png)
Je dois conserver les appels suivants ?
tarteaucitron.job.push('atinternetoptin');
tarteaucitron.job.push('atinternetoptout');

**Comment by AmauriC** [comment]
Du coup ne garde que:
```
tarteaucitron.user.atLibUrl = '//tag.aticdn.net/ID/smarttag.js';
tarteaucitron.user.atMore = function () { //AT Page Tagging
var tag = new ATInternet.Tracker.Tag();
tag.page.set({
name: page,
chapter1: chapterA,
chapter2: chapterB,
chapter3: chapterC,
level2: s2
});
tag.dispatch(); };
(tarteaucitron.job = tarteaucitron.job || []).push('atinternethightrack');
```

Le nouveau est encore en développement, il y a encore quelques problèmes.

**Comment by cyrilmonnom** [comment]
J'ai encore des problèmes, peut-être car tu travailles sur la dernière version. As-tu une vision sur la date de la version finale ?

Comment cela va-t-il se présenter ? Une seule opt'in ? Deux opt'in ? Comment sera gérer l'opt'out ?

Merci pour ton retour,

**Comment by AmauriC** [comment]
Je ne peux pas dire de date mais ça va être assez rapide.
Il y aura un service global et un système d'optout général pour la mesure d'audience.

**Comment by cyrilmonnom** [comment]
Bonjour @AmauriC ,

Tout d'abord merci :)

J'attends donc ton retour sur la mise à disposition

Cordialement,
