### ISSUE TITLE
Duplication des cookies et Inversion des boutons

### ISSUE THREAD

**Issue by VilainPtiZombie** [AmauriC/tarteaucitron.js#612]
Bonjour,

Il s'avère que je j'obtiens un petit problème lors du choix des cookies, les boutons accepter et interdire semble être inversé.
Le bouton interdire dépose des cookies alors que le accepter non.

///////

De plus tout les cookies qui sont déposé en tout cas les cookies Analitycs semble être dupliqué ?
j'ai regarder si je n'avais pas un duplication du script mais il ne semble pas.

Pour information je suis sur un wordpress.

Cordialement,

**Comment by beauchette** [comment]
J'ai exactement le meme souci : duplication des cookies + "inversion" des boutons accepter et refuser. Je mets inversion entre guillemets, parce que le cookie tarteaucitron contient bien les choix de l'utilisateurs service=true/false etc.

Je suppose bien que j' ai du faire une erreur stupide quelque part, mais je n'ai pas trouvé. Avez vous résolu votre problème  et comment ?

**Comment by VilainPtiZombie** [comment]
> J'ai exactement le meme souci : duplication des cookies + "inversion" des boutons accepter et refuser. Je mets inversion entre guillemets, parce que le cookie tarteaucitron contient bien les choix de l'utilisateurs service=true/false etc.
> 
> Je suppose bien que j' ai du faire une erreur stupide quelque part, mais je n'ai pas trouvé. Avez vous résolu votre problème et comment ?
Bonjour,
Vérifie que tout tes scripts de bases sont bien désinstaller c'est le problème que j'avais j'avais des scripts fantômes qui appelait les services. Et je pense que les doublons de scripts ne sont pas bon pour le fonctionnement.

**Comment by beauchette** [comment]
Alors j'avais testé ca, sans tarteaucitron, mon site ne fait pas de GA. et j'ai recommencé plusieurs fois l'installation. J'ai toujours le meme résultat, je suis allé sur un autre site (pas à moi) il y a exactement ce meme probleme. Je vais refaire une nouvel issue
