### ISSUE TITLE
Fonction de callback googlemap

### ISSUE THREAD

**Issue by Merligo** [AmauriC/tarteaucitron.js#613]
Bonjour, 

depuis l'interface https://tarteaucitron.io/pro essaye d'enregistrer une fonction de callback dans les paramètres sur google map mais la valeur ne s'enregistre pas.

Cordialement,

**Comment by chaissac** [comment]
Je confirme, l'interface pour le service GoogleMap est un peu bugguée, il se mélange aussi les champs.

**Comment by granpam** [comment]
C'est possible d'avoir des exemples de code pour cette fonction ? je suis dans le meme cas, compte pro et je n'arrive pas à la faire fonctionner.

**Comment by AmauriC** [comment]
>  il se mélange aussi les champs
Même quand tous les champs sont renseignés?
Il est en effet possible que si un champ n'est pas rempli, il prenne la place d'un autre dans l'interface tac : /
