### ISSUE TITLE
Bannière qui réapparait après acceptation/ refus

### ISSUE THREAD

**Issue by AnthonyIp** [AmauriC/tarteaucitron.js#614]
Bonjour,

J'ai un gros souci lorsque j'accepte ou refuse les cookies.
La bannière réapparaît à chaque fois que l'on change de page ou que l'on rafraîchit la page.
Je n'ai pas d'erreur JS en console.
J'ai un peu modifié l'ordre des boutons sur la bannière, ajouter une div.container pour englober les boutons de la bannière, le CSS, le logo showIcon. 

Merci

**Comment by AnthonyIp** [comment]
Je viens de trouver la source de mon problème, il semblerait que le fait de mettre un sous-domaine dans l'option "cookieDomain" fait planter.

Comment fait-on pour ajouter un sous domaine ?

**Comment by AnthonyIp** [comment]
@AmauriC pourrait rouvrir l'issue?

**Comment by AmauriC** [comment]
Si par exemple le site est https://exemple.com/ pour activer le cookie sur un sous domaine, la valeur de cookieDomain doit être `.exemple.com`

**Comment by AnthonyIp** [comment]
Question bête, mais si on a un autre id pour GA, comment fait-on ?

**Comment by AmauriC** [comment]
Il faut changer la valeur de `tarteaucitron.user.analyticsUa = 'UA-XXXXXXXX-X';` sur le sous domaine.

**Comment by AnthonyIp** [comment]
Si je comprends sur mon site principal 
```
"cookieDomain"           : ".exemple.fr", 
```
Est-ce que le bandeau s'affiche sur le sous domaine aussi ? (celui-ci est une autre application à part)

**Comment by AmauriC** [comment]
Sur le sous domaine il faut aussi ajouter et initialiser tarteaucitron.

**Comment by AnthonyIp** [comment]
> 
> 
> Sur le sous domaine il faut aussi ajouter et initialiser tarteaucitron.

du coups, remttre ca sur le sous domaine ?
```
<script type="text/javascript" src="/assets/tarteaucitron.js-(version)/tarteaucitron.js"></script>
<script type="text/javascript">
tarteaucitron.init({
    "privacyUrl": "", /* URL de la politique de confidentialité */

    "hashtag": "#tarteaucitron", /* Ouvrez le panneau avec ce hashtag */
    "cookieName": "tarteaucitron", /* Nom du cookie */

    "orientation": "middle", /* Postion de la bannière (top - bottom) */
    "showAlertSmall": true, /* Afficher la petite bannière en bas à droite */
    "cookieslist": true, /* Afficher la liste des cookies */

    "adblocker": false, /* Afficher une alerte si un adblocker est détécté */
    "DenyAllCta" : true, /* Afficher un boutton pour refuser tous les cookies */
    "AcceptAllCta" : true, /* Afficher un boutton pour accepter tous les cookies (quand highPrivacy est true) */
    "highPrivacy": true, /* Désactiver l'auto consentement */
    "handleBrowserDNTRequest": false, /* Si l'utilisateur à activer Do Not Track, interdire tout les cookies */

    "removeCredit": false, /* Supprimer le lien de crédit - laissez le pour nous soutenir ;) */
    "moreInfoLink": true, /* Afficher le lien "plus d'info) */
    "useExternalCss": false, /* Si c'est faut, le fichier tarteaucitron.css par défaut sera charger */

    //"cookieDomain": ".my-multisite-domaine.fr", /* Cookie partagé pour le site Web du sous-domaine */

    "readmoreLink": "/cookiespolicy", /* Changer le lien par défaut "en savoir plus" pointant vers tarteaucitron.io */
    
    "mandatory": false /* Afficher un message sur les cookies obligatoires */
});
</script>
```

si tel est le cas , je vois pas l'interet de mettre l'option sous domaine car cela est comme une nouvelle bande cookie, non ?

**Comment by AmauriC** [comment]
L'intérêt de l'option cookieDomain est de partager le consentement (si YouTube est accepté sur le domaine principal, il le sera sur le sous domaine).

Pour charger tarteaucitron, il faut charger le script, sinon comment pourrait-il agir? 🙃

Donc pour ce cas il faut charger tarteaucitron partout et avoir une valeur cookieDomain cohérente sur le domaine/sous domaine.
