### ISSUE TITLE
Webpack - tarteaucitron is not defined

### ISSUE THREAD

**Issue by Grandpied33** [AmauriC/tarteaucitron.js#615]
Bonjour à tous,

J'ouvre ma première issue Github, j'ignore donc si la procédure est correcte ou pas n'hésitez pas à me le dire si ce n'est pas le cas.

Voilà je travaille sur un projet en Symfony 5 où je souhaite intégrer tarteaucitron.

J'ai donc un fichier app.js compilé par Webpack qui ressemble à cela :

```
require('tarteaucitronjs/tarteaucitron')

$(document).ready(function() {

    tarteaucitron.init({
        "privacyUrl": "", /* Privacy policy url */

        "hashtag": "#tarteaucitron", /* Open the panel with this hashtag */
        "cookieName": "tarteaucitron", /* Cookie name */

        "orientation": "middle", /* Banner position (top - bottom) */

        "showAlertSmall": false, /* Show the small banner on bottom right */
        "cookieslist": false, /* Show the cookie list */

        "closePopup": false, /* Show a close X on the banner */

        "showIcon": false, /* Show cookie icon to manage cookies */
        "iconPosition": "BottomRight", /* BottomRight, BottomLeft, TopRight and TopLeft */

        "adblocker": true, /* Show a Warning if an adblocker is detected */

        "DenyAllCta" : true, /* Show the deny all button */
        "AcceptAllCta" : true, /* Show the accept all button when highPrivacy on */
        "highPrivacy": true, /* HIGHLY RECOMMANDED Disable auto consent */

        "handleBrowserDNTRequest": false, /* If Do Not Track == 1, disallow all */

        "removeCredit": false, /* Remove credit link */
        "moreInfoLink": true, /* Show more info link */

        "useExternalCss": false, /* If false, the tarteaucitron.css file will be loaded */
        "useExternalJs": false, /* If false, the tarteaucitron.js file will be loaded */

        //"cookieDomain": ".my-multisite-domaine.fr", /* Shared cookie for multisite */

        "readmoreLink": "", /* Change the default readmore link */

        "mandatory": true, /* Show a message about mandatory cookies */
    });

    tarteaucitron.user.multiplegtagUa = ['UA-XXXX-X'];
    (tarteaucitron.job = tarteaucitron.job || []).push('multiplegtag');
    tarteaucitron.user.clarity = 'XXXXXXX';
    (tarteaucitron.job = tarteaucitron.job || []).push('clarity');
    (tarteaucitron.job = tarteaucitron.job || []).push('adsense');

    console.log('Hello Webpack Encore! Edit me in assets/js/app.js');
    console.log('')

});
```

Mais quand je charge une page la console me retourne l'erreur suivante : 

```
Uncaught ReferenceError: tarteaucitron is not defined
    at HTMLDocument.<anonymous> (app.js:14)
    at mightThrow (jquery.js:3762)
    at process (jquery.js:3830)
```

J'ignore si cela vient de mon intégration qui n'est pas bonne ou si je n'appelle pas correctement le script ?

Ce que je peux vous dire c'est que la seule façon que j'ai trouvé de faire fonctionner tarteaucitron est en ajoutant dans le head de mon HTML : 

`<script type="text/javascript" src="https://tarteaucitron.io/load.js"></script>`

Est-ce que quelqu'une en saurait plus sur cette intégration ou quelqu'un à déjà été dans le même cas ?

Merci d'avance et excellent travail pour cette librairie :)

**Comment by AxelRaboit** [comment]
J'ai exactement le meme probleme que toi, sous symfony, avec webpack j'ai aussi le "is not defined"....

**Comment by bastien-effetb** [comment]
Hello,
Sur symfony 4 je l'utilise comme ceci :
`global.tarteaucitron = require('tarteaucitronjs/tarteaucitron');
`

**Comment by mhouel** [comment]
Si vous avez cette problématique, attention à l'utilisation de `require('tarteaucitronjs/tarteaucitron')`.

Au tout début du script, le module essaye de détecter le CDN sur lequel chercher les autres fichiers du bundle.
Il part du principe qu'il est appelé comme dans l'exemple du [README](https://tarteaucitron.io/fr/install/) (balise script pointant vers le fichier).
Donc avec la technique citée plus haut, le bundle peut ne pas fonctionner.

Ma solution :

```Javascript
$(document).ready(function () {
    let tarteaucitronSource = $('#tarteaucitron-script-src').val();
    $("body").append($("<script></script>").attr("src", tarteaucitronSource));

    if (typeof tarteaucitron === 'object') {
        tarteaucitron.init({
            ...
        })

        ...
    }
});

```
