### ISSUE TITLE
Afficher TarteAuCItron même si aucun service n'est déclaré.

### ISSUE THREAD

**Issue by vptcnt** [AmauriC/tarteaucitron.js#616]
Bonjour,

Nous aimerions que TarteAuCitron s'affiche quand même - Alert + Panel - même si aucun service n'est déclaré. Car il y aurait quand même la mention "Cookies obligatoires - Ce site utilise des cookies nécessaires à son propre fonctionnement qui ne peuvent pas être désactivés"

Est-ce possible ?

Vincent

**Comment by chaissac** [comment]
Effectivement ce pourrait être intéressant que les gens soient informés quoi qu'il arrive. Utile quand on paramètre occasionnellement des services (par exemple pour une campagne donnée).

**Comment by AmauriC** [comment]
Je suis assez d'accord mais je ne sais pas comment faire : /

Le bandeau est prévu pour s'afficher quand un des services n'a pas encore été accepté/refusé.

Si il n'y en a aucun, il est logiquement masqué.

Une solution serait d'ajouter un cookie pour forcer l'affichage du bandeau si il est inexistant mais il y a surement plus élégant comme solution.

**Comment by thierrysutter** [comment]
Bonjour, nous rencontrons le même problème. Nous souhaitons que le bandeau s'affiche même si nous n'ajoutons aucun service car nous avons des cookies obligatoires et nous souhaitons donc que ceux ci apparaisse dans la partie Personnaliser comme c'est le cas s'il y a un service.

Vous etes capable de vérifier s'il y a ou non un service pour décider si le bandeau doit être visible ou non. Donc je me dis qu'il doit être possible de changer le code pour forcer l'affichage du bandeau s'il n'y a aucun service. On pourrait même avoir un paramètre true/false à positionner dans l'init.

**Comment by AmauriC** [comment]
Sur la problématique on est tous d'accord mais l'affichage du bandeau est actuellement conditionné au choix de l'utilisateur sur les services. 

Si un service n'a été ni accepté, ni refusé, le bandeau s'affiche.

Le problème avec les cookies obligatoires c'est que l'utilisateur n'a aucun choix à faire.

Comment décider si le bandeau doit s'afficher ou non?

**Comment by thierrysutter** [comment]
bonjour, le problème selon moi n'est pas si un service est activé ou désactivé. C'est kle fait de ne mettre aucun service dans l'init de votre plugin : 

![image](https://user-images.githubusercontent.com/25754630/116401917-163c2580-a82c-11eb-8a8e-46ac7d45685d.png)


Comme vous le voyez si je commente les lignes 112 et 113, il n'y a rien qui s'affiche au lancement de la page. Pas d'alert, pas de panel.

**Comment by thierrysutter** [comment]
pour moi le bandeau doit s'afficher tout le temps
et pour avoir une possibilité de ne pas l'avoir pour ceux qui le souhaite, je propose l'idée d'ajouter un paramètre dans l'init comme "showIcon"
par exemple : "alwaysVisible": true ou false

**Comment by AmauriC** [comment]
C'est bien ce que je dit, si il n'y a aucun service dans l'init, le bandeau ne s'affiche pas puise qu'il n'y a rien à faire pour tarteaucitron.

Je peux ajouter une option alwaysVisible mais du coup vous seriez ok pour imposer à vos visiteurs sur toutes les pages l'affichage d'un bandeau 'inutile' ?

Ce qu'il manque c'est la logique pour masquer quand même le bandeau ou bout d'un moment.

**Comment by thierrysutter** [comment]
Oui on serait ok. Mais je pense qu'il est aussi possible de laisser les boutons Tout accepter et Tout refuser et de garder le comportement actuel qui est d'afficher uniquement l'icone dès que l'utilisateur a cliqué sur un de ces boutons

**Comment by thierrysutter** [comment]
Ou sinon de mettre automatiquement l'affichage "réduit" de l'icone tarteaucitron s'il n'y a aucun service

**Comment by thierrysutter** [comment]
Merci nous allons tester de suite
