### ISSUE TITLE
TarteauCitron Laravel

### ISSUE THREAD

**Issue by JWK-new** [AmauriC/tarteaucitron.js#617]
Bonjour 

J'ai essayé de suivre la procédure  du site https://tarteaucitron.io/fr/install/
J'ai téléchargé les fichiers décompresser dans  un repertoire laravel (C:\wamp\www\persoprojet\)
J'ai copié collé le code dans mon head et pris en compte le Google Tagmanager
Mais je n'ai rien qui se passe coté front end... pas d'alert, ...

Est ce qu'une autre personne aurait eu ce même type de problème?
Je vous remercie

**Comment by sebastienheyd** [comment]
Si on suit la procédure d'installation, avec Laravel les fichiers doivent être placés dans `public/tarteaucitron`

Sinon il faut regarder les messages d'erreur dans la console (touche F12 dans le naigateur)
