### ISSUE TITLE
DataLayer ignored by gtag.js

### ISSUE THREAD

**Issue by Cruiser13** [AmauriC/tarteaucitron.js#618]
We have the following script in our website in the head (before loading tarteaucitron.js):
```js
<script>
window.dataLayer = window.dataLayer || [];
dataLayer.push({'ecommerce': {'detail': {"actionField":[],"products":[{"id":123456789,"name":"Productname","category":"ALL","price":123,"quantity":1}]} }});
</script>
```
But it never appears in analytics. It looks like the dataLayer is not properly pushed here:
https://github.com/AmauriC/tarteaucitron.js/blob/2379e0648188b3485f12d8ca0081eaf009033b0d/tarteaucitron.services.js#L1583

Any idea on how to fix that?

**Comment by Cruiser13** [comment]
@AmauriC do you need further information about this issue? Is there anything I can provide?

**Comment by AmauriC** [comment]
Maybe wait the initialization of tarteaucitron:

```
document.addEventListener("DOMContentLoaded", function() {
   window.addEventListener('tac.root_available', function() {
        window.dataLayer = window.dataLayer || []; 
        dataLayer.push({'ecommerce': {'detail': {"actionField":[],"products":[{"id":123456789,"name":"Productname","category":"ALL","price":123,"quantity":1}]} }});
   }
}
```

I dont use GA so it's hard to help you on this point.

**Comment by Cruiser13** [comment]
Thank you for the idea but it did not work sadly.

**Comment by AmauriC** [comment]
I made a mistake on my previous code 😣

```
document.addEventListener("DOMContentLoaded", function() {
   window.addEventListener('tac.root_available', function() {
        window.dataLayer = window.dataLayer || []; 
        window.dataLayer.push({'ecommerce': {'detail': {"actionField":[],"products":[{"id":123456789,"name":"Productname","category":"ALL","price":123,"quantity":1}]} }});
   }
}
```

**Comment by Cruiser13** [comment]
I noticed and changed that but still no success... I'll dig deeper.
