### ISSUE TITLE
Appel fichier cdn

### ISSUE THREAD

**Issue by cyrilmonnom** [AmauriC/tarteaucitron.js#621]
Bonjour @AmauriC ,

Nous rencontrons des problématiques sur l'appel du script depuis Google Tag Manager.

Lorsque nous appelons le script "https://cdn.jsdelivr.net/gh/AmauriC/tarteaucitron.js@20210306/tarteaucitron.js" depuis le code source de notre application, le CMP apparait parfaitement. Seulement quand nous appelons le même script depuis GTM nous avons des erreurs 404 (fichier css et js. Nous avons l'impression que GTM interprète les liens des fichiers en relatif par rapport au domaine de l'application appelante, au lieu de garder les liens absolus par rapport au cdn). Y a t il une configuration spécifique a mettre en place pour que cela soit fonctionnelle depuis GTM ?

Merci par avance

**Comment by AmauriC** [comment]
Bonsoir,

Ca semble être un problème lié a GTM.
Pourquoi ne pas charger directement tarteaucitron comme vous le faites pour GTM?

Intégrer un tag manager dans un tag manager n'est jamais une bonne chose 🙃
