### ISSUE TITLE
Bug sur l'affichage du nombre de cookie

### ISSUE THREAD

**Issue by AnthonyIp** [AmauriC/tarteaucitron.js#623]
Bonjour, 

Je viens de remarquer un petit bug sur le compteur du nombre de cookies.
Testé avec Google Analytics Universal.

**Étapes à reproduire:**
- Autoriser tous les cookies (Ce service a déposé 3 cookies.)
- Interdire tous les cookies (Ce service peut déposer 10 cookies.)
- Autoriser tous les cookies (Ce service n'a déposé aucun cookie.)

Il prend un certains temps avant de m'afficher la dernière mention.

**Comment by JWK-new** [comment]
Trouver ... Erreur de débutant... dossier non enregistré public

**Comment by AnthonyIp** [comment]
> Trouver ... Erreur de débutant... dossier non enregistré public

 ???

J initialise sur un template twig sur symfony.

**Comment by AnthonyIp** [comment]
@JWK-new meme en mettant sur le dossier public, cela ne change pas du tout

**Comment by JWK-new** [comment]
> @JWK-new meme en mettant sur le dossier public, cela ne change pas du tout

Je l'utilise sur ma version cloud. 
Je suis vraiment nouveau sur Github.  On peut échanger ? et ainsi on verra où vous bloquez..

**Comment by AnthonyIp** [comment]
@JWK-new Si vous avez discord, AznYouth#0139

**Comment by JWK-new** [comment]
Je pense qu'il manque un chiffre dans ton id

**Comment by AnthonyIp** [comment]
J'ai fait un copier coller, mais si tu veux #0139

**Comment by AnthonyIp** [comment]
personne ?

**Comment by AmauriC** [comment]
Il y a la liste des cookies potentiels (10) et ceux réellement posé sur la navigateur (3).
Cette indication n'est pas vraiment utile et source de problème, je pense à la supprimer.
