### ISSUE TITLE
Compatibilité mode hybride AtInternet

### ISSUE THREAD

**Issue by Aaarrrgggh** [AmauriC/tarteaucitron.js#631]
Bonjour,

je voulais savoir si TarteAuCitron prévoyait une compatibilité avec le mode hybride d'AtInternet.
En gros, autoriser par défaut le traqueur atInternet avec le mode exempt et en fonction des choix de l'utilisateur, passer en OptIn ou OptOut.

Merci

**Comment by AmauriC** [comment]
Oui, c'est déjà le cas mais pas optimal, une nouvelle version du service atinternet va être dispo très rapidement : )

**Comment by gregleveque** [comment]
Bonjour, concernant les dernières modifications sur les services AtInternet, il y a toujours un appel
`window.tag.page.send();` mais celui-ci envoie une requête sans aucun paramètres ce qui crée un doublon si on refais nous même un appel avec des paramètres de page dans la fonction `atMore`.
Ne serait-il pas plus pertinent de faire simplement un `window.tag.dispatch();` pour laisser la possibilité de passer des paramètres de page dans la fonction `atMore` ?

**Comment by AmauriC** [comment]
Oui en effet ce serait mieux mais si l'utilisateur n'ajoute rien d'autre, un window.tag.dispatch(); seul n'aura aucun effet?

**Comment by Aaarrrgggh** [comment]
J'ai également le même souci, car j'utilise un plan de marquage spécifique. Pour le moment, j'ai commenté le window.tag.page.send(); car les remontées sont erronées et doublées (l'une avec le plan de marquage correct et l'autre avec des paramètres vides)

**Comment by AmauriC** [comment]
Je viens d'envoyer un message à mon contact chez ATInternet pour voir si il y a une solution pour tout le monde sans devoir ajouter un paramètre au service tarteaucitron ; )

**Comment by Aaarrrgggh** [comment]
Bonjour,

le ticket est clos, mais la fonction window.page.send() renvoyant des éléments vides est toujours présente. Pourtannt je vois bien les différences dans les commit. Y a-t-il un souci avec la dernière version de tarteAuCitron ?

**Comment by AmauriC** [comment]
Je viens d'ajouter une nouvelle option `tarteaucitron.user.atinternetSendData = false;` pour désactiver l'envoi des datas côté tarteaucitron :)

**Comment by Aaarrrgggh** [comment]
Ok top ! merci ! ça fonctionne désormais ! :)
