### ISSUE TITLE
ExpireTime cookie

### ISSUE THREAD

**Issue by benjaminumc** [AmauriC/tarteaucitron.js#632]
Bonjour,

Existe-t-il une variable qui nos permette définir le temps du cookie ?

D'avance merci !

**Comment by AnthonyIp** [comment]
> 
> 
> Bonjour,
> 
> Existe-t-il une variable qui nos permette définir le temps du cookie ?
> 
> D'avance merci !

Oui, met ca avant l'init

```
var tarteaucitronExpireInDay = true, tarteaucitronForceExpire = 183,
```
