### ISSUE TITLE
Criteo

### ISSUE THREAD

**Issue by SamanthaDevWeb** [AmauriC/tarteaucitron.js#635]
Bonjour,

Nous utilisons Criteo sur notre site ecommerce.
Nous avons les tags de suivi suivant dans notre code source sur plusieurs pages (accueil / panier / confirmation de commande / etc.) : 
`<script type="text/javascript" src="https://static.criteo.net/js/ld/ld.js" async="true"></script>
<script type="text/javascript">
window.criteo_q = window.criteo_q || [];
window.criteo_q.push(
 { event: "setAccount", account: XXX},
 { event: "setEmail", email: "XX" },
 { event: "setSiteType", type: "XX" },
 { event: "viewHome" }
);
</script>`

Quel service TarteauCitron utiliser pour le rendre compatible ?

Merci d'avance.

**Comment by AmauriC** [comment]
Hello

Actuellement Criteo n'est en effet pas dispo.

Tous les paramètres (account, email, type, event) sont indispensables?
Si oui il me faut la liste des valeurs possibles ; )

**Comment by AmauriC** [comment]
Merci pour ces infos mais du coup ce n'est pas compatible avec tarteaucitron.
Il n'y a pas de notion de 'page' sur tarteaucitron.

Ce que je peux faire c'est ajouter un service qui chargera //dynamic.criteo.com/js/ld/ld.js?a=XXXXX mais est-ce que ça peux être utile seul?

**Comment by SamanthaDevWeb** [comment]
Bonjour,

C'est ce que j'ai fait, pour le moment, de cette façon : 

`tarteaucitron.services.criteo = {
		"key": "criteo",
		"type": "ads",
		"name": "Criteo",
		"needConsent": true,
		"cookies": [],
		"js": function () {
			"use strict";
			tarteaucitron.addScript('https://static.criteo.net/js/ld/ld.js');
		},
	};`

Le JS n'est appelé que lorsque les cookies sont acceptés.
