### ISSUE TITLE
tarteaucitron.io DOWN

### ISSUE THREAD

**Issue by chaissac** [AmauriC/tarteaucitron.js#638]
Bonjour,
Le site tarteaucitron.io est down (31/03/2021, 11h UTC+1), cela dure depuis au moins une heure), ce qui cause un non chargement des services et un lag au chargement des sites, en plus de l'impossibilité de gérer les services.
Il faudrait un système de fallback, de cache, je ne sais pas.

**Comment by chaissac** [comment]
Site de retour (https://status.tarteaucitron.io/history) mais la question d'un fallback reste entière...
Un début de réponse ici : https://stackoverflow.com/questions/1014203/best-way-to-use-googles-hosted-jquery-but-fall-back-to-my-hosted-library-on-go mais pour éviter une double configuration à chaque modification des services, il faudrait réfléchir à un rapatriement automatique des fichiers en local (évidemment côté serveur, sans doute est-ce indépendant de tarteaucitron et à mettre en oeuvre selon les technos utilisées, mais une api ou la possibilité de faire un callback vers le serveur à chaque modif serait intéressant).

**Comment by AmauriC** [comment]
Je n'avais pas vu ce message, désolé à tous pour le down qui a duré un peu plus d'une heure..

Il est prévu de revoir l'infra pour ajouter plus de redondance.

Le chargement de tarteaucitron pro repose sur un seul fichier js:
https://tarteaucitron.io/load.js?locale=fr&domain=tarteaucitron.io&uuid=d5c983ff271fee8f419e00db23d3d1a47cde2a76

Il est mis en cache 24h et à donc fonctionné pour les utilisateurs revenant sur le site pendant le down.

Une solution envisageable est de télécharger le contenu de ce fichier, le stocker en local et l'utiliser pour charger tarteaucitron.
Si tarteaucitron.io est down, seules les stats côté tarteaucitron.io seront indisponibles, le chargement des services fonctionnera correctement.

Plus d'infos à venir.
