### ISSUE TITLE
Support for Google Consent Mode on Analytics

### ISSUE THREAD

**Issue by eficiens-eric** [AmauriC/tarteaucitron.js#639]
Bonjour,

I understand Google Consent Mode affects 3 Google services : Ads, Floodlight and Analytics.
For Analytics, it seems Google needs to know whether consent was given or not, in which case they deploy another type of cookie… They create a variable called 'analytics-storage' that can be set to 'denied' or 'allowed'.
If set to 'denied', Analytics sends a "ping without cookie" for basic information.

Which means… this variable has to be handled by the CMP.
I did not see any information related to this on this forum or release notes. Or I missed it ?

More details here : https://support.google.com/analytics/answer/9976101?hl=fr and here : https://developers.google.com/gtagjs/devguide/consent

**Comment by AmauriC** [comment]
That's possible, a PR is under revision ; )

**Comment by eficiens-eric** [comment]
Merci ! à surveiller donc

**Comment by melchiorEcotree** [comment]
Bonjour @AmauriC , avez-vous une idée de la date d'ajout du Consent mode au code ?

**Comment by AmauriC** [comment]
Ça n'a pas encore été approuvé par la CNIL, aucune date de prévu 🤷‍♂️

https://github.com/AmauriC/tarteaucitron.js/pull/647#issuecomment-832469109
