### ISSUE TITLE
Trying to use multiplegtagUa to load GA3 and GA4… only loads GA4 ?

### ISSUE THREAD

**Issue by eficiens-eric** [AmauriC/tarteaucitron.js#641]
Bonjour,
As we migrate to the new Analytics, I have a website with both Universal Analytics and GA4 loaded. I was hoping to keep them out of the CMP, but it seems we have little choice.
I tried loading UA and GA4 separately, then using the multiplegtaUa call, but it seems only GA4 is loaded per Google's console.
Anybody has an idea ?
Merci

**Comment by AmauriC** [comment]
No idea : (
I dont use GA so I'm not the best to help you on this point.

**Comment by eficiens-eric** [comment]
Bonjour,
Found a simple solution by re-creating a tracker that I called gtag4 to avoid mixing calls with the UA tracker.
I simply copied/pasted your code for gtag, renamed the service to gtag4 and the variables to gatGtag4cookie and gtagUa4 to be sure.
This way it seems to be working OK !
Voila voila
