### ISSUE TITLE
Multiple cookie set value null / lors d'un refus

### ISSUE THREAD

**Issue by VilainPtiZombie** [AmauriC/tarteaucitron.js#642]
Bonjour,

Je remarque un comportement un peu bizarre : 
Lors d'un refus général "Tout refuser" dans le bandeau cookie ou dans le menu de gestion spécifique.
Je remarque lors du reload voir quand même les cookies set mais bien inactifs cependant.

![dc2f222270ad27371b250d9926e36037](https://user-images.githubusercontent.com/15928955/113274416-f6bde580-92dd-11eb-9261-87a0a34acb96.png)

Ma config : 
```

<script type="text/javascript">
      tarteaucitron.init({
       "adblocker": false,
              "hashtag": '#tarteaucitron',
              "cookieName": 'tarteaucitron',
              "highPrivacy": true,
              "orientation": "bottom",
              "bodyPosition": "top",
              "removeCredit": true,
              "showAlertSmall": false,
              "showIcon": false,
              "iconPosition": "BottomRight",
              "cookieslist": false,
              "handleBrowserDNTRequest": false,
              "DenyAllCta": true,
              "AcceptAllCta" : true,
              "moreInfoLink": true,
              "privacyUrl": "",
              "useExternalCss": false,
              "useExternalJs": false,
              "mandatory": true,
              "closePopup": false
      });
  </script>
  <?php
}    
add_action('wp_head', 'tarteaucitron_init');


/**
* Add GOOGLE TAG MANAGER and other services using tarteaucitron
*/
function add_tarteaucitron_services()
{
?>

<!--<script type="text/javascript">
tarteaucitron.user.matomoId = SITE_ID;
(tarteaucitron.job = tarteaucitron.job || []).push('matomohightrack');
</script>-->

<script type="text/javascript">
      (tarteaucitron.job = tarteaucitron.job || []).push('hotjar');
      </script>
<script type="text/javascript">tarteaucitron.user.hotjarId = xxxxxx;tarteaucitron.user.HotjarSv = x;</script>
<?
}
add_action('wp_head', 'add_tarteaucitron_services');
```

Je ne sais pas si c'est le comportement voulus mais il n'y aurait pas possibilité que le cookie ne soit même pas engagé ?
Ou s'agit il d'une mauvaise config de ma part ?

Cordialement,

**Comment by AmauriC** [comment]
ok, il manque visiblement des cookies à effacer quand hotjar est désactivé.

La liste actuelle:
`["hjClosedSurveyInvites", "_hjDonePolls", "_hjMinimizedPolls", "_hjDoneTestersWidgets", "_hjMinimizedTestersWidgets", "_hjDoneSurveys", "_hjIncludedInSample", "_hjShownFeedbackMessage", "_hjAbsoluteSessionInProgress", "_hjIncludeInPageviewSample", "_hjid"]`

Complétez avec ce qui manque et je mettrai à jour tac ; )

**Comment by VilainPtiZombie** [comment]
Bonjour et merci de la réponse,

Il semblerait que le seul cookie manquant est "_hjFirstSeen" je n'en voit pas d'autre. même après l'ajout sur le services.hotjar mon problème persiste.

![image](https://user-images.githubusercontent.com/15928955/113293202-c2562380-92f5-11eb-8fc6-ff1acb611bf3.png)

Le problème c'est que je reste quand même avec 30 cookies alors que j'ai tout refuser.

Cordialement,

**Comment by AmauriC** [comment]
Lors du refus, les cookies sont créés pour être sûr qu'ils sont sans contenu et avec une date d'expiration dans le passé.
Vous pouvez verifier via l'explorateur des cookies ; )

**Comment by VilainPtiZombie** [comment]
> Lors du refus, les cookies sont créés pour être sûr qu'ils sont sans contenu et avec une date d'expiration dans le passé.
> Vous pouvez verifier via l'explorateur des cookies ; )

Quel abrutis je fais j'avais pas vérifier la date d'expiration.

Bon bah parfait je comprends mieux. Je vous remercie :)
