### ISSUE TITLE
Dissocier les libellés des boutons "Tout refuser" sur tarteaucitron.io

### ISSUE THREAD

**Issue by chaissac** [AmauriC/tarteaucitron.js#643]
Bonjour,
La personnalisation des textes sur l'interface pro tarteaucitron.io ne permet pas de distinguer les 2 boutons "Tout refuser". Or il peut être souhaitable d'avoir un message différent dans l'AlertBig (comme "continuer sans accepter" par exemple) tout en gardant le libellé "Tout refuser" dans la fenêtre de gestion des cookies. Du reste, les deux instances du bouton "Tout accepter" sont, elles, bien différenciées.

**Comment by AmauriC** [comment]
Hello
Bonne idée, c'est faisable : )

Du coup ce serait bien de définir un texte par défaut pour le bandeau+panel pour que ce soit différent.
