### ISSUE TITLE
Bandeau ne s'affiche pas sur Internet Explorer 11 

### ISSUE THREAD

**Issue by eboufandwat** [AmauriC/tarteaucitron.js#644]
Bonjour,

Le bandeau qui contient les boutons Accepter, Refuser, Personnaliser... ne s'affiche pas sur IE 11.
Il s'affiche bien sur les autres navigateurs.
Il n'y a pas de message dans la console du navigateur.

Il y a un display none sur la classe #tarteaucitronAlertBig, mais si je force l'affichage, le bandeau s'affiche, mais les boutons ne fonctionnent pas.

Pouvez-vous nous aider sur ce qui pourrait bloquer l'affichage svp ?
Pour info nous avons un abonnement annuel.

Merci

**Comment by AmauriC** [comment]
Bonjour,

Quel est l'url du site?

**Comment by eboufandwat** [comment]
https://immobilier.mousquetaires.com/
Accueil - IMMO MOUSQUETAIRES<https://immobilier.mousquetaires.com/>
ALERTE FRAUDE EN COURS /!\ - Certaines entités du Groupement Les Mousquetaires (notamment les sociétés IMMO AMONT, ITM IMMO LOG, ITM IMMO LOG EM) font actuellement l’objet d’une usurpation d’identité à des fins frauduleuses.
immobilier.mousquetaires.com



Emmanuel BOUF
Développeur web

[WAT]
LD : +33 (0)1 47 61 58 71 - Portable : 06 13 23 66 96
6 bd des Capucines 75441 Paris Cedex 09
WAT - We Are Together acquiert l'agence All Contents et devient le 1er groupe indépendant en communication corporate et RH avec 250 collaborateurs proches de chez vous (Paris, Lille, Clermont-Ferrand, Strasbourg, Nantes, Lyon, Aix-en-Provence et Toulouse). #NoTrustNoFuture.
[wearetogether.fr]<http://wearetogether.fr> wearetogether.fr [http://www.orc.fr/piedmail/wat/separateur.gif]  [Twitter] <https://twitter.com/agence_wat>  [Facebook] <https://www.facebook.com/AgenceWAT>  [Youtube] <https://www.youtube.com/channel/UC9pSnOoUcUqtQSequUTUtAw?view_as=subscriber>  [Linkedin] <http://www.linkedin.com/company/agencewat/>  [Viadeo] <http://www.viadeo.com/fr/company/orc-communications>


________________________________
De : Amauri CHAMPEAUX ***@***.***>
Envoyé : vendredi 2 avril 2021 13:12
À : AmauriC/tarteaucitron.js ***@***.***>
Cc : Emmanuel BOUF ***@***.***>; Author ***@***.***>
Objet : Re: [AmauriC/tarteaucitron.js] Bandeau ne s'affiche pas sur Internet Explorer 11 (#644)


Bonjour,

Quel est l'url du site?

**Comment by eboufandwat** [comment]
https://immobilier.mousquetaires.com/

**Comment by AmauriC** [comment]
Le site est en maintenance donc je ne peux pas vérifier mais en fonction de la version que vous utilisez, c'est peut-être déjà corrigé:
https://github.com/AmauriC/tarteaucitron.js/commit/821fdc814c0168db27f022cb049a5f540a67a3f6

**Comment by eboufandwat** [comment]
Effectivement ce site a été mis en maintenance entre temps.
Il y aussi ce site : https://www.acta-assistance.com/
Nous utilisons la dernière version 1.5.1

**Comment by AmauriC** [comment]
J'ai appliqué le correctif: https://github.com/AmauriC/tarteaucitron.js/commit/205fdb3cc6beebbc40671a8b43459632441a9e23

Comme vous utilisez la v pro vous n'avez rien à faire, c'est appliqué directement (pensez juste à vider le cache pour vérifier).

**Comment by eboufandwat** [comment]
Je vous remercie. C'est bien corrigé.
