### ISSUE TITLE
atinternet

### ISSUE THREAD

**Issue by pierretux** [AmauriC/tarteaucitron.js#648]
Bonjour,

J'ai du supprimer tarteaucitron.job.push('atinternetoptin');tarteaucitron.job.push('atinternetoptout'); de mon code pour que le script fonctionne sinon cela me donne une erreur de JS, une idée ?

**Comment by pierretux** [comment]
Bonjour,
Du coup je n'ai pas l'exemption de la CIL, comment corrigé cela ?

Merci

**Comment by AmauriC** [comment]
Quel était l'erreur JS?

Le service atinternet va être revu très rapidement pour une meilleure compatibilité.

**Comment by pierretux** [comment]
tarteaucitron.job indefined

tu penses le revoir quand car je suis bloquer pour les ministères

**Comment by AmauriC** [comment]
tarteaucitron.job est censé être défini dès le chargement du script.

Possible d'avoir un site de démo avec ce problème?

**Comment by pierretux** [comment]
Non car si je le fais cela bloque les stats ;)
