### ISSUE TITLE
Event analytics callback

### ISSUE THREAD

**Issue by granpam** [AmauriC/tarteaucitron.js#649]
Bonjour,

comment faire fonctionner ce type de code avec tarteaucitron en mode pro ?

  gtag('event', 'signup_form_complete', {
    'event_callback': function() {
      form.submit();
    }
  });

Si le cookie n'est pas accepté du coup le form ne sera jamais transmis. Y a t il un moyen faire du conditionnel en testant l'activtion ou non du cookie en question ?

Merci

**Comment by AmauriC** [comment]
Il faudrait vérifier si gtag est dispo pour envoyer le formulaire sans passer par l'event google si non accepté.
Par exemple `if (tarteaucitron.launch["gtag"]) { /*autorisé*/ }`
