### ISSUE TITLE
AT Internet better integration

### ISSUE THREAD

**Issue by BenDz** [AmauriC/tarteaucitron.js#65]
Hi @AmauriC 
I'm Product Owner at AT Internet (Xiti) on the data collection part, and I would like to propose you to work together on a better integration of our solution in your tool.

Don't hesitate to contact me at benjamin.diolez@atinternet.com

Best,
Benjamin

**Comment by AmauriC** [comment]
Hi Ben

I am open to any suggestions for improvement!

Tell me what I can do to help ;)
