### ISSUE TITLE
Lithuanian language

### ISSUE THREAD

**Issue by Domka** [AmauriC/tarteaucitron.js#651]
Hello 
i need to have this  app in lithuanian. i can help to translate. how i can do it ?
thank you

**Comment by BuyukCem** [comment]
Hello,
If you can wait until next week I can pass the translations on to you,
in the company where I am,  we have the trad

**Comment by Domka** [comment]
thank you.  i can wait :)  until next week ;) inform me, when it done.thank you

**Comment by BuyukCem** [comment]
ok that works :ok_hand: , if i forget resend a message

**Comment by AmauriC** [comment]
Thanks @Domka :)

For you information @BuyukCem , the strings to translate are here (in english):
https://github.com/AmauriC/tarteaucitron.js/blob/master/lang/tarteaucitron.en.js

**Comment by Domka** [comment]
hello . what's news? passed  more 2 month and no lithuanian langue  :)  i need it.

**Comment by AmauriC** [comment]
Hi, I dont speak lithuanian but if you can translate this file https://github.com/AmauriC/tarteaucitron.js/blob/master/lang/tarteaucitron.en.js I'll add it.

**Comment by BuyukCem** [comment]
Hello, sorry I completely forgot I'm doing this right now

**Comment by BuyukCem** [comment]
I just made the PLL https://github.com/AmauriC/tarteaucitron.js/pull/727

**Comment by AmauriC** [comment]
Approved 👍
