### ISSUE TITLE
Tarteaucitron languages and  OpenElement.

### ISSUE THREAD

**Issue by MyDataAreMine** [AmauriC/tarteaucitron.js#656]
Je viens de terminer l'installation de la bannière de cookies tarteaucitron dans mon site web, développé avec OpenElement.

Jusqu'à présent, j'ai installé le script général dans la couche de base et les scripts pour bloquer les différents services dans la section/page correspondante du site. L'ensemble du processus a été très simple.

Le seul problème que je ne parviens pas à résoudre est de savoir comment faire fonctionner les fichiers .js de la langue tarteaucitron avec la fonctionnalité de langue OE. Puisque le site est disponible en 7 langues, comment puis-je configurer le script pour qu'il s'exécute dans chacune d'elles ? 

Tout conseil serait le bienvenu.

**Comment by AmauriC** [comment]
Il faut déclarer avant le chargement de tarteaucitron: `var tarteaucitronForceLanguage = 'fr';`

**Comment by MyDataAreMine** [comment]
Bonjour à nouveau,
Merci pour les conseils.
J'ai suivi les instructions et le changement de langue fonctionne maintenant bien.... mais les actions des cookies ne fonctionnent que dans la langue par défaut (anglais).

Le site n'a que des cookies liés aux vidéos Youtube. L'application Tarteaucitron fonctionne bien puisqu'elle vous permet d'avancer dans le site jusqu'à ce que vous arriviez aux vidéos, qui sont bloquées jusqu'à ce que vous acceptiez les cookies. Si vous refusez les cookies, les vidéos ne seront pas disponibles.

Mais cette fonction ne fonctionne qu'en anglais. Dans les autres langues, j'obtiens bien la boîte de sélection des cookies dans la langue sélectionnée, mais les vidéos ne sont pas bloquées par défaut, et elles restent debloquées meme si je refuse les cookies, au contraire de ce qui se passe en anglais/langue par défaut. (Voir mydatamygain.com)
Merci pour toute aide.

**Comment by AmauriC** [comment]
Sur le site EN vous avez bien remplacé les iframe youtube par:
`<div class="youtube_player" videoID="BD4lZwu9XMU" width="560" height="315" theme="theme (dark \| light)" rel="0" controls="controls (1 \| 0)" showinfo="showinfo (1 \| 0)" autoplay="autoplay (0 \| 1)" mute="mute (0 \| 1)"></div>`

mais pas sur le site FR, du coup logiquement la vidéo se charge sans consentement.
