### ISSUE TITLE
Boostrap 5 + tarteaucitron.js

### ISSUE THREAD

**Issue by Domka** [AmauriC/tarteaucitron.js#657]
Bonjour Amauri
je suis en train de créer  mon WP theme avec Boostrap 5. j'ai installée plugin de tarteaucitron.js. je vois que tous les styles et scriptes, mais il ne génère pas  cookie tarteaucitron et ne affiche pas le bannière d'information.  Le statut tarteaucitronAlertBig est display:none.. Comment on peux régler et pourquoi arrive ça ? Avec l'autres versions boostrap c'est fonctionne bien. 
merci par avance

**Comment by AmauriC** [comment]
Hello
La bannière ne s'affiche que si il y a des services à traiter, c'est probablement le problème ; )
