### ISSUE TITLE
Fallback method in tarteaucitron.js doesn't replace all values with correct html

### ISSUE THREAD

**Issue by jhiverKI** [AmauriC/tarteaucitron.js#658]
Hello,

I've just met a curious issue while implementing a service on my own : one share button displayed multiple times on the same page has not all of his instances activated when user accepts cookies.

Only the first share button is activated when cookies are accepted instead of each instance of the share button.

I've found that changing the Fallback method in tarteaucitron.js by reokacing : 
`        var elems = document.getElementsByTagName('*'),
            i,
            index = 0;`
by :
`        var elems = document.getElementsByClassName(matchClass),
            i,
            index = 0;`
solves this issue but it doesn't make any sense to me as results from "getElementsByClassName" are already returned by "document.getElementsByTagName('*')" as this last call returns all tags in DOM.

Apart from this issue, isn't it a better idea to pre-filter the DOM elements by the classname we want tarteaucitron to target instead of getting the whole nodeList of DOM and then loop on them ?

**Comment by AmauriC** [comment]
This function exist since the start of the script and I'm sure it was to be compatible with IE 6 - 8

Now we can switch to getElementsByClassName and start the ie support to IE9 ; )
