### ISSUE TITLE
Not working on Magento 1.9

### ISSUE THREAD

**Issue by Tirakal** [AmauriC/tarteaucitron.js#661]
I use the module with GDPR extension in our store.
All steps are done, but nothing happens on the front end.
In inspecting element I can see the DIV with id="tarteaucitronRoot" and some div's inside are display: none. 
Please help.

**Comment by AmauriC** [comment]
Did you declared a service? 
If there is nothing to do, the banner is not displayed.
If you have a public url, it will help to find the problem ; )

**Comment by Tirakal** [comment]
All js files are added in header. tarteaucitron.js and tarteaucitron.service.js and all other files too.
from this extension cookie are enabled (wich require tarteaucitron.js ) - https://github.com/PH2M/GDPR
this is in a config.phtml file 
`    tarteaucitron.init({
        "privacyUrl": "<?php echo $this->getPrivacyPageUrl() ?>", /* Privacy policy url */

        "hashtag": "#tarteaucitron", /* Open the panel with this hashtag */
        "cookieName": "tartaucitron", /* Cookie name */

        "orientation": "bottom", /* Banner position (top - bottom) */
        "showAlertSmall": true, /* Show the small banner on bottom right */
        "cookieslist": true, /* Show the cookie list */

        "adblocker": false, /* Show a Warning if an adblocker is detected */
        "AcceptAllCta" : true, /* Show the accept all button when highPrivacy on */
        "highPrivacy": true, /* Disable auto consent */
        "handleBrowserDNTRequest": true, /* If Do Not Track == 1, accept all */

        "removeCredit": false, /* Remove credit link */
        "moreInfoLink": true /* Show more info link */

    });`

Sorry the website is not public, only allowed ip's access.

Wich information exactly you need to know? And what you mean saying declare?

**Comment by AmauriC** [comment]
Check the "manual installation" guide: https://tarteaucitron.io/en/install/

If you dont add any service to tarteaucitron, the banner is not displayed.

Why a banner should be displayed if there is nothing to accept/reject? ; )

**Comment by Tirakal** [comment]
Thanks. Solved
