### ISSUE TITLE
Utilisation sur un site en nodejs

### ISSUE THREAD

**Issue by yanjaunky** [AmauriC/tarteaucitron.js#668]
Bonjour, 
J'ai installé tarteaucitron sur un site en NodeJs.
j'ai une erreur en faisant un import dans ce style:

import tarteaucitron from "tarteaucitronjs/tarteaucitron";

tarteaucitron.init({ <- est invalid

Pouvez-vous me guider sur le bon procedé à employer, svp?

A noter que je ne peux pas faire require( ou meme inclure les js par la balise <script

**Comment by AmauriC** [comment]
Personnellement aucune idée, je n'ai jamais utilisé NodeJs mais je suis sûr que quelqu'un ici pourra vous aider ; )

**Comment by yanjaunky** [comment]
Pour etre plus precis, j'utilise webpack et j'ai fait l'installation par npm

**Comment by bastien-effetb** [comment]
Bonjour,

Moi je l'utilise comme ça :
`global.tarteaucitron = require('tarteaucitronjs/tarteaucitron');`

**Comment by yanjaunky** [comment]
Bonjour, 
Je viens de le tenter mais j'ai toujours l'erreur

Uncaught ReferenceError: tarteaucitron is not defined

**Comment by paidge** [comment]
Il suffirait sûrement de faire un export dans le fichier [tarteaucitron.js](https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.js) pour pouvoir faire un [import en tant que module](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Statements/import).
