### ISSUE TITLE
Possibilité d'afficher le bandeau même pour des cookies techniques

### ISSUE THREAD

**Issue by mickaelbober** [AmauriC/tarteaucitron.js#669]
bonjour, 
j'ai retrouvé des sujets déja ouvert sur ce problème pour autant je vous explique notre point de vue
travaillant dans l'administration public on nous demande de prouver que coté RGPD nous nous interessons de pres a la gestion des cookies.
je sais qu'effectivement des cookies techniques n'ont pas besoin d'accord de principe de l'usager mais nous devons tout de meme montrer "pattes blanches" sur le sujet
aujourd'hui pour afficher la barre et le bouton "personnaliser" pour voir uniquement qu'il n'y a des cookies techniques j'utilise un bout de js qui force en display block la barre que vous cachez par défaut sans service initialisé (je garde dans le temps l'infos dans un cookie également....)

ne pourriez vous pas proposer dans la config lancer a l'init une option pour forcer l'affichage (false par défaut pour etre retro compatbile) et laisser la liberté a chacun d'activer le panneau meme sans service ????

**Comment by AmauriC** [comment]
Hello

Du coup, si une solution est prête de votre côté, vous pouvez proposer un PR?

**Comment by mickaelbober** [comment]
je vais essayer de vous proposer celà pour en discuter prochainement (sans doute courant mai...)
