### ISSUE TITLE
youtube / aitinternet

### ISSUE THREAD

**Issue by pierretux** [AmauriC/tarteaucitron.js#678]
Bonjour,

Je rencontre un problème sur le site https://guadeloupe.deets.gouv.fr/
Quand j'ai ATinternet j'ai le bandeau de cookie mais si j'active youtube bloque le bandeau
Je n'ai pas le problème sur d'autre sites comme https://centre-val-de-loire.dreets.gouv.fr/

Une idée du problème ?

Merci

**Comment by pierretux** [comment]
Sur ce site https://normandie.dreets.gouv.fr/ dans la liste des cookie on a "mesure d'audience" mais rien dedans.
Alors que https://bretagne.dreets.gouv.fr/ j'ai bien le but rechercher

**Comment by AmauriC** [comment]
Bonjour : )

Essayez en mettant à jour le fichier tarteaucitron.services.js:
https://raw.githubusercontent.com/AmauriC/tarteaucitron.js/master/tarteaucitron.services.js

**Comment by pierretux** [comment]
Re,

Merci cela corrige en local.
Tu envisage un tag prochainement ? Car je maintient à jour un plugins https://git.spip.net/spip-contrib-extensions/tarteaucitron et je up dès que tu fais des tag ;)

Merci pour le temps passé.

**Comment by AmauriC** [comment]
Ok, merci pour la confirmation. Je pousse un nouveau tag dans les 48h ; )
