### ISSUE TITLE
Fonction loop Youtube

### ISSUE THREAD

**Issue by Vanlen1er** [AmauriC/tarteaucitron.js#684]
Bonjour,

est ce qu'il existe une option lecture en boucle pour une vidéo Youtube ? J'ai un client qui me demande ça et forcément loop="1" ne fonctionne pas.

Merci

**Comment by AmauriC** [comment]
Bonjour,
Je viens de l'ajouter ; )

**Comment by Vanlen1er** [comment]
Nickel merci :)
