### ISSUE TITLE
Atinternet : double envoi ?

### ISSUE THREAD

**Issue by pierretux** [AmauriC/tarteaucitron.js#688]
Bonjour,

Sur les sites de dreets.gouv.fr j'ai le problème suivant : 
![image](https://user-images.githubusercontent.com/4512774/116871247-46147000-ac14-11eb-8de5-3c4e5b710d81.png)
Cela fait 2 fois la statistique  et je ne comprends pas d'où cela sort, une idée ?

**Comment by AmauriC** [comment]
Salut,

Il y a une nouvelle option depuis le commit https://github.com/AmauriC/tarteaucitron.js/commit/4cf393cd4084b37e2ea5c0c68e07b1d86c0411a9

**Comment by pierretux** [comment]
Salut,
En fait ça envoi même si je dit que non dans les cookie ?

**Comment by AmauriC** [comment]
ATInternet a un mode 'excempté' par la cnil qui permet d'avoir quelques infos même quand c'est refusé ; )

**Comment by pierretux** [comment]
ok donc il faut mettre false si veut 0 info et true si on en souhaite ?

**Comment by AmauriC** [comment]
Oui, comme vous utilisez atMore pour charger le tag, il faut passer l'option `tarteaucitron.user.atinternetSendData` à false.

**Comment by pierretux** [comment]
@AmauriC donc sur tout les sites ou j'ai ATinternet je peux mettre exempté ? ou y'a des règles ?

**Comment by AmauriC** [comment]
Il faut activer le mode "exempt":
https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.services.js#L3273

**Comment by pierretux** [comment]
ok mais tout les sites sont "exempt" ou bien y'a des normes ? Je trouve pas trop d'info sur cela.

**Comment by AmauriC** [comment]
C'est le système de mesure d'audience qui est exempté. Avec le petit bout de code en plus, atinternet récolte moins d'informations et c'est ok pour être chargé sans le consentement de l'utilisateur.

**Comment by pierretux** [comment]
ok donc sur le site https://solidarites-sante.gouv.fr/ ça envoi les stats vers AT sans que les cookie soit acceptés, comment je peux faire pour tout bloquer ?

**Comment by pierretux** [comment]
AmauriC, je viens de mettre à jour le site et j'ai tjs un envoi stats alors que les cookie sont pas accepter, comment faire ? Merci pour ton aide.

**Comment by AmauriC** [comment]
Il y a un mode 'cnil' chez atinternet qui permet d'avoir un envoi de donnée quand l'utilisateur n'accepte pas.
Ce ne sont que des données anonymes sans infos directe sur l'utilisateur ;)

**Comment by AmauriC** [comment]
C'est géré par tarteaucitron.

**Comment by pierretux** [comment]
ok merci
