### ISSUE TITLE
Comment fonctionne l'implementation du bandeau pour les sous domaines ?

### ISSUE THREAD

**Issue by AnthonyIp** [AmauriC/tarteaucitron.js#689]
Bonjour, 

Comment fonctionne l’implémentation du bandeau pour les sites en sous domaine?
Exemple: j'ai 2 sites **hello.com** et **bonjour.hello.com.**

Cependant que je veux que le bandeau de mes 2 sites sois totalement indépendant.

J'ai 2 ID different de GA. Je voudrais pas avoir les cookies de hello.com lorsque je suis sur bonjour.hello.com.
Comment est ce que je pourrais faire ?

Merci

**Comment by AmauriC** [comment]
`"cookieDomain": ".hello.com"` dans l'initialisation des 2 sites devrait suffire ; )
