### ISSUE TITLE
Intégration dans une application mobile développée en ionic4

### ISSUE THREAD

**Issue by thierrysutter** [AmauriC/tarteaucitron.js#693]
Bonjour, nous avons tenté d'intégrer tarteaucitron dans une de nos applications mobiles développées en ionic4. 
L'intégration fonctionne plutot bien sur android sauf pour notre page de geoloc qui utilise googlemaps. 
Si le service est autorisé, aucun soucis l'affichage de la map et des markers fonctionne. Par contre si on refuse le service, la page est blanche.
Nous avons aussi pas mal de soucis sur iOs. Le "gros" bandeau s'affiche tout le temps meme si on a fait nos choix auparavant.

Est ce que quelqu'un à rencontrer les mêmes difficultés ? Si oui, avez vous trouvé une solution ?

Merci d'avance pour vos retours

**Comment by AmauriC** [comment]
Je n'ai jamais essayé d'intégrer tac avec ionic mais quelques pistes:

- si le contenu est blanc, c'est probablement parce que quelque part dans votre app le fait que google maps soit absent provoque une erreur
- si la bandeau se réaffiche systématiquement (a l'inverse d'android avec la configuration), c'est que l'app ne gère pas correctement les cookies
