### ISSUE TITLE
Matomo needConsent false

### ISSUE THREAD

**Issue by developer-mde** [AmauriC/tarteaucitron.js#694]
Bonjour,

Je voudrais savoir pourquoi le 'needConsent' de 'matomohightrack' est passé de true à false ?
J'utilise actuellement la version pro de tarteaucitron et sur une première version de mon site (une landing page), nous avons installé une version "classique" (avec la librairie dans le projet) et je constate qu'entre les 2 version le needConsent a changé...

Pouvez-vous me dire si quelque chose a changé avec matomo sur le consentement ?

Merci d'avance

**Comment by AmauriC** [comment]
En effet Matomo est passé en 'autorisé par defaut' mais il y a une discussion à ce sujet, à suivre : /
https://github.com/AmauriC/tarteaucitron.js/pull/653
