### ISSUE TITLE
Bouton continuer sans accepter

### ISSUE THREAD

**Issue by AnthonyIp** [AmauriC/tarteaucitron.js#695]
Bonjour,

Je voudrais savoir comment faire pour ajouter un bouton permettant de cacher la bannière lorsqu'il est en tant que modal sans pour autant accepter ou refuser les cookies.

**Comment by AmauriC** [comment]
Il y a l'option `"closePopup": false` pour afficher une X de fermeture.

**Comment by AnthonyIp** [comment]
L'option closePopup permet de mettre le X dans la modale de paramétrage, mais ne ferme pas lorsque la bannière cookie est en mode ```orientation: "middle"```.

J'ai donc ajouté un bouton dans la bannière et ajouté cet événement. 
```
tarteaucitron.addClickEventToId("tarteaucitronClosePanelCookie", function () {
    tarteaucitron.userInterface.closePanel();
});
```

En mettant le cookie domaine, j'ai par contre un bug qui fait qu'après avoir accepté tous les cookies, je change de page, cela me réaffiche la bannière cookie
