### ISSUE TITLE
Options possibles

### ISSUE THREAD

**Issue by thierryler** [AmauriC/tarteaucitron.js#702]
Existe-t-il une page avec toutes les options de config possibles ? Par exemple j'ai trouvé "closePopup" en parcourant les issues mais j'imagine qu'il y en a plein d'autres...

**Comment by AmauriC** [comment]
https://tarteaucitron.io/fr/install/ > Installation manuelle ; )

**Comment by thierryler** [comment]
Ah oui il est dans le install mais pas dans le readme, merci.
