### ISSUE TITLE
Pro version seems to be using old matomo code

### ISSUE THREAD

**Issue by virgile-dev** [AmauriC/tarteaucitron.js#704]
After I integrate Matomo on my banner I get this message. 
<img width="882" alt="Capture d’écran 2021-05-12 à 08 50 20" src="https://user-images.githubusercontent.com/11473995/117931235-39bca100-b2ff-11eb-9571-eef55696940f.png">

Here is the code I'm supposed to use according to tarte au citron but it refers to piwik.php and piwik.js which is the old name of matomo.
```
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="YOUR_MATOMO_URL";
    _paq.push(['setTrackerUrl', u+'**piwik.php**']);
    _paq.push(['setSiteId', SITE_ID]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'**piwik.js**'; s.parentNode.insertBefore(g,s);
  })();
</script>
```

Here is an example of a matomo tracking code : 
```
<!-- Matomo -->
<script type="text/javascript">
  var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="YOUR_MATOMO_URL";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', 'SITE_ID']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Matomo Code -->
```

**Comment by AmauriC** [comment]
Thanks for the feedback, I'll modify this but this is not the script used to load matomo, this is an example of the code that you have to remove of your website ; )

**Comment by virgile-dev** [comment]
Thanks for your swift reply.
> this is an example of the code that you have to remove of your website ; )

Does this mean that I have to remove the matomo script I inserted myself and let tarte citron handle it for me ?

**Comment by AmauriC** [comment]
Yes.
