### ISSUE TITLE
Prefinery : Pre-launch Waiting List & Referral Marketing Software

### ISSUE THREAD

**Issue by SSylvain1989** [AmauriC/tarteaucitron.js#705]
Bonjour à tous . 

J'ai intégré sur mon site tarteaucitron merci beaucoup , après avoir écumé internet, c'est le seul qui marche , et assez facilement . 
J'ai également sur mon site internet un " bouton " qui permet l'inscription à une liste d'attente .

Sans le script ci-dessous , impossible de s'inscrire à la liste d'attente . Est-ce que ce type de cookie peut être considéré comme " necessaire au bon fonctionnement du site ? " , est-ce que tarteaucitron permet de gerer ce type de cookie ? 

Vous remerciant . 
```html
	<script>// eslint-disable-next-line
		prefinery = window.prefinery || function () { (window.prefinery.q = window.prefinery.q || []).push(arguments); };
	</script>
	<script src="https://widget.prefinery.com/widget/v2/bj9an5st.js" defer></script>
```

Je vois qu'on peut add un custom service .. du coup ça serait mon cas je pense. 

```javascript
tarteaucitron.services.mycustomservice = {
  "key": "mycustomservice",
  "type": "ads|analytic|api|comment|other|social|support|video",
  "name": "MyCustomService",
  "needConsent": true,
  "cookies": ['cookie', 'cookie2'],
  "readmoreLink": "/custom_read_more", // If you want to change readmore link
  "js": function () {
    "use strict";
    // When user allow cookie
  },
  "fallback": function () {
    "use strict";
    // when use deny cookie
  }
};
```
Qu'est-ce que je vais mettre dans "cookie","cookie2" ? 
En vous remerciant

**Comment by AmauriC** [comment]
Merci pour les infos, je m'occupe de l'ajouter rapidement à la liste des services ; )

**Comment by SSylvain1989** [comment]
Merci pour ta réactivité . Dans l'intervalle tu penses que je peux adapter ta fonction GA ou ta fonction custom service ci-dessus ? 
Je ne vois pas quoi mettre dans ' cookie / cookie2 ' .

**Comment by AmauriC** [comment]
Il faut soit tester (charger le service et voir les cookies qui s'installent), soit fouiller dans la doc mais je n'ai rien trouvé : /
https://www.prefinery.com/cookies
