### ISSUE TITLE
HTML/CSS de la version de base

### ISSUE THREAD

**Issue by Gregcop1** [AmauriC/tarteaucitron.js#707]
Bonjour et bravo pour le travail que vous accomplissez.
J'ai récemment installé la version de base de l'outil. Tout fonctionne très bien mais la version HTML et CSS est assez perfectible voire compliquée à surcharger. Est-ce qu'une PR avec du HTML nettoyé vous intéresserait ? (désolé je préfère demander avant de faire la PR au cas où ça ne vous intéresserait pas)

**Comment by Gregcop1** [comment]
Et en intégrant ça à une version majeure ? (et donc possiblement contenant des BC breaks ?)

**Comment by Gregcop1** [comment]
Pas d'avis sur le fait d'intégrer ça à une version majeure ?

**Comment by AmauriC** [comment]
Je suis d'accord que ce serait bien mais déployer une version majeur n'est pas du tout prévu.
Maintenant des milliers de sites utilisent tarteaucitron et maintenir 2 versions différentes ne sera pas faisable pour moi étant donné que je suis seul sur le projet : (
