### ISSUE TITLE
Changer nom d'un service

### ISSUE THREAD

**Issue by triclic** [AmauriC/tarteaucitron.js#71]
Bonjour,
Est il possible de changer le nom d'un service.
par exemple au lieu de  : "Addthis est désactivé" mettre "Addthis réseaux sociaux est désactivé"
Merci d'avance de votre aide

Cdt

**Comment by AmauriC** [comment]
Bonjour

Possible de modifier le nom du service en modifiant le fichier tarteaucitron.services.js:
https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.services.js#L37

Pas encore d'option pour éviter de modifier le fichier.

**Comment by Adam-CdW** [comment]
Bonjour,

Pour une problématique un peu similaire, j'ai simplement étendu l'objet `tarteaucitron.services` en ajoutant un nouveau service (dans un autre fichier, pour ne pas toucher à la librairie).

Cordialement,

**Comment by triclic** [comment]
Cool, merci les gars
j'ai tenté de modifier tarteaucitron.services.js
pour Addthis :
`// addthis
tarteaucitron.services.addthis = {
    "key": "addthis",
    "type": "social",
    "name": "AddThis réseau sociaux",<--ICI
    "uri": "http://www.addthis.com/privacy/privacy-policy#publisher-visitors",
    "needConsent": true,
    "cookies": ['__atuvc', '__atuvs'],
    "js": function () {
        "use strict";
        if (tarteaucitron.user.addthisPubId === undefined) {
            return;
        }
        if (tarteaucitron.isAjax === true) {
            window.addthis = null;
            window._adr = null;
            window._atc = null;
            window._atd = null;
            window._ate = null;
            window._atr = null;
            window._atw = null;
        }
        tarteaucitron.fallback(['addthis_sharing_toolbox'], '');
        tarteaucitron.addScript('//s7.addthis.com/js/300/addthis_widget.js#pubid=' + tarteaucitron.user.addthisPubId);
    },
    "fallback": function () {
        "use strict";
        var id = 'addthis';
        tarteaucitron.fallback(['addthis_sharing_toolbox'], tarteaucitron.engage(id));
    }
};`

Mais rien ne change dans la bannière qui s'affiche sur le site cela marque toujours  : 
AddThis est désactivé. ✓ Autoriser

**Comment by AmauriC** [comment]
Le cache du navigateur a bien été vidé ?

Même chose dans une fenêtre en navigation privée ?


-------- Message d'origine --------
De : triclic <notifications@github.com>
Date : 19/04/2018 15:39 (GMT+01:00)
À : "AmauriC/tarteaucitron.js" <tarteaucitron.js@noreply.github.com>
Cc : Amauri Champeaux <contact@ferank.fr>, Comment <comment@noreply.github.com>
Objet : Re: [AmauriC/tarteaucitron.js] Changer nom d'un service (#71)


Cool, merci les gars
j'ai tenté de modifier tarteaucitron.services.js
pour Addthis :
// addthis tarteaucitron.services.addthis = { "key": "addthis", "type": "social", "name": "AddThis réseau sociaux",<--ICI "uri": "http://www.addthis.com/privacy/privacy-policy#publisher-visitors", "needConsent": true, "cookies": ['__atuvc', '__atuvs'], "js": function () { "use strict"; if (tarteaucitron.user.addthisPubId === undefined) { return; } if (tarteaucitron.isAjax === true) { window.addthis = null; window._adr = null; window._atc = null; window._atd = null; window._ate = null; window._atr = null; window._atw = null; } tarteaucitron.fallback(['addthis_sharing_toolbox'], ''); tarteaucitron.addScript('//s7.addthis.com/js/300/addthis_widget.js#pubid=' + tarteaucitron.user.addthisPubId); }, "fallback": function () { "use strict"; var id = 'addthis'; tarteaucitron.fallback(['addthis_sharing_toolbox'], tarteaucitron.engage(id)); } };

Mais rien ne change dans la bannière qui s'affiche sur le site cela marque toujours :
AddThis est désactivé. ✓ Autoriser

**Comment by triclic** [comment]
Oh oui le boulet de base...le cache comme d'hab.
ça marche nickel merci les gars.
@+
