### ISSUE TITLE
Désactiver Mandatory ne fonctionne pas

### ISSUE THREAD

**Issue by Aaarrrgggh** [AmauriC/tarteaucitron.js#715]
Bonjour,

il semble qu'avec les dernières versions de tarteAuCitron, l'option "mandatory" ne fonctionne plus. Qu'elle soit à true ou false, le bloc des cookies obligatoires apparait.

Merci et bonne journée,

Alexandre

**Comment by AmauriC** [comment]
Je viens de tester et ça fonctionne bien.

Vous pouvez partager l'initialisation du script que vous utilisez?

**Comment by AmauriC** [comment]
Si ce n'est pas un problème au moment du copier/coller, il faut supprimer toutes les phrases entre / / 

```
tarteaucitron.init({
"privacyUrl": "", 
"hashtag": "#tarteaucitron", 
"cookieName": "tarteaucitron", 
"orientation": "bottom", 
"showAlertSmall": false, 
"cookieslist": true, 
"closePopup": false, 
"showIcon": false,
"adblocker": false,
"DenyAllCta" : true,
"AcceptAllCta" : true, 
"highPrivacy": true, 
"handleBrowserDNTRequest": false,
"removeCredit": true, 
"moreInfoLink": true, 
"useExternalCss": false, 
"readmoreLink": "/cookiespolicy",
"mandatory": false
});
```

**Comment by Aaarrrgggh** [comment]
Ok merci, effectivement j'avais pas fait gaffe à la coquille :)
