### ISSUE TITLE
Compatibilité anciennes versions iOS

### ISSUE THREAD

**Issue by SistProd** [AmauriC/tarteaucitron.js#716]
Bonjour,

Je viens d'installer manuellement tarteaucitron sur mon site wordpress (thème fait maison) tout fonctionne bien sauf sur les anciennes versions d'iOS où lorsque l'on ouvre la personnalisation des cookies on voit seulement le message "Ce site n'utilise aucun cookies nécessitant votre consentement", les services n'ont pas l'air de se charger...
J'ai testé sur un iPad iOS 9 (oui ça existe encore ;) et iPhone iOS 12, sur différents navigateurs (safari, firefox...), par contre ça fonctionne sur un iPhone récent. Ce qui m'embête c'est que tarteaucitron fonctionne bien sur d'autres sites sur ces devices, c'est donc probablement mon installation qui a un problème.
Avez vous une idée ? 

tarteaucitron version 1.9.1
https://t-hihat-drums.com/

Merci !

**Comment by AmauriC** [comment]
Hello

Il y a bien un soucis mais ça a été corrigé entre temps.
C'est le service xandr qui pose problème, en attendant une nouvelle release, vous pouvez supprimer ce service du fichier tarteaucitron.services.js

![Capture d’écran 2021-05-19 à 11 02 02](https://user-images.githubusercontent.com/8764074/118786117-c9c79100-b891-11eb-8ef8-b8a4bc8f7afc.png)

**Comment by SistProd** [comment]
Ok, c'est parfait, ça marche nickel. 
J'ai supprimé tous les services que je n'utilisais pas, ça allège le code au max :)
Merci pour cette réactivité et cette efficacité !
Petite question au passage par curiosité, tu utilises quoi comme émulateur ?

**Comment by AmauriC** [comment]
Avec plaisir : )

L'émulateur c'est https://www.browserstack.com/ , super pratique avec la console intégrée 👍

**Comment by SistProd** [comment]
Merci pour l'info ! Et merci pour tarteaucitron, c'est top !
