### ISSUE TITLE
TarteAuCitron et sous-domaines

### ISSUE THREAD

**Issue by Aaarrrgggh** [AmauriC/tarteaucitron.js#717]
(re)Bonjour,

Deux points : 

**1er point : basculer d'un domaine unique à plusieurs sous-domaines**

sur un domaine, j'ai mis en place tarteaucitron, sans tenir compte du paramètre cookieDomain. Le cookie  a donc été créé avec comme domaine par défaut mondomaine.com

J'ai effectué une mise à jour de TarteAucitron en ajoutant le paramètre cookieDomain, pour pouvoir profiter du cookie sur plusieurs domaines, avec comme valeur cookieDomain = ".mondomaine.com"

Conséquence : Deux cookies coexistent pour mondomaine.com (avec des domaines différents) et l'option "tout refuser" ne fonctionne plus. (TarteAuCitron n'accède qu'au premier cookie).

**Deuxième point : quid de la gestion des services entre sous-domaines ?**

Admettons un site A qui partage le cookie TarteAuCitron avec le site B, mais qui ne dispose pas forcément des mêmes services. Si j'accepte tout sur le site A, les services présents sur A et B seront activés sur B, mais les services présents sur B uniquement seront désactivés par défaut ?

Merci et bonne journée,

**Comment by AmauriC** [comment]
1- Il faut supprimer les cookies du navigateur pour appliquer le changement de domaine.
Quand il y a les 2 cookies ça pose en effet problème.
Autre solution, changer le nom du cookie tarteaucitron.

2- C'est bien ça, ce qui a été accepté sur le site A sera accepté sur le site B, le reste sera désactivé en attendant le choix de l'utilisateur.

**Comment by Aaarrrgggh** [comment]
Ok merci pour vos réponses.
