### ISSUE TITLE
Denied all -> Cookie wait

### ISSUE THREAD

**Issue by developer-mde** [AmauriC/tarteaucitron.js#718]
Bonjour,

Lorsque la popin s'ouvre pour la première fois, on peut choisir "Denied all". Mais cette commande mets la valeurs des services à "wait".

La page se recharge et la popin s'ouvre de nouveau... Si la personne dis non à tous, il ne faudrait pas lui reproposer la popin au chargement.

est-ce un comportement normal ?

merci d'avance

**Comment by developer-mde** [comment]
Pour info, j'utilise la méthode manuelle (Ni la version pro, ni le module Drupal TacJS)

**Comment by AmauriC** [comment]
Non, ce n'est évidemment pas le comportement voulu :x

Possible d'avoir l'url du site ou le code d'initialisation?

**Comment by developer-mde** [comment]
`

      tarteaucitron.init({
      "privacyUrl": "",
      "hashtag": "#tarteaucitron", /* Open the panel with this hashtag */
      "cookieName": "tarteaucitron", /* Cookie name */

      "orientation": "middle", /* Banner position (top - bottom) */

      "showAlertSmall": false, /* Show the small banner on bottom right */
      "cookieslist": false, /* Show the cookie list */

      "closePopup": false, /* Show a close X on the banner */

      "showIcon": false, /* Show cookie icon to manage cookies */
      "iconPosition": "BottomRight", /* BottomRight, BottomLeft, TopRight and TopLeft */

      "adblocker": false, /* Show a Warning if an adblocker is detected */

      "DenyAllCta" : true, /* Show the deny all button */
      "AcceptAllCta" : true, /* Show the accept all button when highPrivacy on */
      "highPrivacy": true, /* HIGHLY RECOMMANDED Disable auto consent */

      "handleBrowserDNTRequest": false, /* If Do Not Track == 1, disallow all */

      "removeCredit": false, /* Remove credit link */
      "moreInfoLink": true, /* Show more info link */

      "useExternalCss": true, /* If false, the tarteaucitron.css file will be loaded */
      "useExternalJs": false, /* If false, the tarteaucitron.js file will be loaded */

      //"cookieDomain": ".my-multisite-domaine.fr", /* Shared cookie for multisite */

      "readmoreLink": "", /* Change the default readmore link */

      "mandatory": true, /* Show a message about mandatory cookies */
    });`

**Comment by AmauriC** [comment]
Cette partie c'est ok. Sûrement un problème dans les services ajoutés.

**Comment by developer-mde** [comment]
J'ai un service custom (superOffice) et matomo

**Comment by AmauriC** [comment]
Je peux voir le code du service custom?

**Comment by developer-mde** [comment]
`

       tarteaucitron.services.superoffice = {
      "key": "superoffice",
      "type": "api",
      "name": "superoffice",
      "needConsent": true,
      "uri": "https://www.superoffice.com/",
      "cookies": 'superoffice',
      "readmoreLink": "https://www.superoffice.com/", // If you want to change readmore link
      "js": function () {
        "use strict";

        function insertIframes(){
          if (jQuery('.superoffice-iframe').length) {
            jQuery('[data-script-src]').each(function(index, elem) {
              var src = jQuery(elem).data('script-src');
              var script = '<script src="'+ src +'">';

              jQuery(elem).html('');
              jQuery(elem).append(script);
            })
          }
        }

        insertIframes();
      },
      "fallback": function () {
        "use strict";
      }
    };`

**Comment by AmauriC** [comment]
`cookies` doit être un tableau:

`"cookies": ['superoffice'],`

**Comment by developer-mde** [comment]
Juste les accolades... C'est bon ça fonctionne.

Bonne journée
