### ISSUE TITLE
Google Captcha

### ISSUE THREAD

**Issue by triclic** [AmauriC/tarteaucitron.js#72]
Salut à tous,
est ce que google Captcha est concerné par les cookies ?
si oui que faut il utiliser  ??

merci d’avance de vos réponses
@+

**Comment by Stepomp** [comment]
Salut,

J'ai l'impression que oui... https://actecil.fr/2017/03/20/les-donnees-personnelles-et-le-captcha-de-google/

Du coup que doit-on utiliser ?

En vous remerciant,

**Comment by triclic** [comment]
re,
 je pense que tarteaucitron n'a pas prévu google recaptcha pour l'instant. 
Je sais que cela récupère le cookie du visiteur et que cela utilise api google.
ça serai cool d'inclure google recaptcha dans les services couverts par tarteaucitron au vu du nombre de site l'utilisant...

si quelqu'un a un solution qu'il n'hésite pas :)
@+

**Comment by AmauriC** [comment]
reCAPTCHA v2 ajouté ; )
https://github.com/AmauriC/tarteaucitron.js/commit/bc451eb573407d3548a5ac865f844bd730f9a85f

**Comment by triclic** [comment]
Yesssss.... excellent 
Merci AmauriC

**Comment by emilie68** [comment]
Est-il prévu d'adapter tarteaucitron pour la v3 de ReCaptcha ?
