### ISSUE TITLE
Google Recaptcha cookie or not cookie

### ISSUE THREAD

**Issue by thierryler** [AmauriC/tarteaucitron.js#725]
Salut, je suis complètement perdu avec ReCaptcha. 

Est ce que ça compte comme cookie indispensable au fonctionnement du site ? Non, d'après ce que je comprend. 

Est ce qu'il faut le remplacer par autre chose ? On m'a parlé de Orange qui aurait fait un captcha conforme aux cookies. Vous en connaissez des biens ? 

Je ne vois pas comment gérer proprement le cas d'un utilisateur qui n'aurait pas accepté le cookie, par exemple parce qu'il aurait refusé tout par défaut.

**Comment by AmauriC** [comment]
reCaptcha ne peux pas être jugé indispensable, c'est google lui même qui le dit:
> vous acceptez qu'il vous incombe d'en informer les utilisateurs et de leur demander leur autorisation pour la collecte et le partage de ces données avec Google
https://www.google.com/recaptcha/admin/create

La cnil est du même avis et recommande https://www.phpcaptcha.org/

Ca fonctionne bien mais c'est un peu plus compliqué à mettre en place : /

**Comment by thierryler** [comment]
Génial. Merci.

Je vais essayer les deux solutions 1) TAC avec conf pour recaptcha et 2) phpcaptcha.org qui est un peu à l'ancienne.

J'ai regardé du coté de chez Orange mais c'est une solution payante snif

**Comment by thierryler** [comment]
En ce qui concerne la solution Orange, je n'ai rien réussi à trouver. Il faut contacter un commercial et prendre une solution payante...
