### ISSUE TITLE
La bannière(#tarteaucitronalertbig) ne s'affiche pas quand on charge juste le service Matomo.

### ISSUE THREAD

**Issue by Rantignac** [AmauriC/tarteaucitron.js#726]
Quand j'active seulement le service Matomo. Impossible d'avoir l'affichage de cette bannière (#tarteaucitronalertbig) : 
![image](https://user-images.githubusercontent.com/35865413/120206078-077dcf80-c22b-11eb-8967-6dadb186d298.png)

**Comment by AmauriC** [comment]
Parce que Matomo est activé par défaut, du coup il n'y a rien à accepter.

**Comment by Rantignac** [comment]
Du coup sur cette release : http://github.com/AmauriC/tarteaucitron.js/releases/tag/v1.3 j'ai bien l'affichage de la bannière et comment ça se fait que pour Matomo s'est activé par défaut et il n'y a rien accepté. Peux-tu me donner des informations complémentaires ?

**Comment by AmauriC** [comment]
Matomo est conforme pour une acceptation par défaut.
L'utilisateur à toujours la possibilité de refuser plus tard mais c'est autorisé par la cnil de la charger sans accord (comme atinternet).

dans la version 1.3 ce n'etait pas encore le cas ; )

**Comment by Rantignac** [comment]
merci pour ta réponse ;-)

**Comment by lphm** [comment]
Bonjour,
Juste une précision : la CNIL autorise le dépôt du cookie de Matomo mais à condition que le cookie soit conservé pendant une durée de 13 mois maximum. Est-ce le script généré par Tarte au Citron pour le suivi prend en charge ce point légal ?

**Comment by AmauriC** [comment]
Le cookie tarteaucitron expire maximum après 13 mois et quand il est expiré les cookies sont purgés, donc c'est tout bon : )

**Comment by lphm** [comment]
Parfait :+1:
Merci !

**Comment by Thithi32** [comment]
Bonjour, nous sommes dans ce cas d'usage: nous avons seulement Matomo comme service. Avant la dernière mise à jour nous avions forcé l'affichage de la popup en utilisant "Matomo (Privacy par défaut)" et en mettant `"highPrivacy": true,`. Mais maintenant la popup ne s'affiche plus. On me demande de la faire apparaître absolument. Je ne vois pas comment faire. Une idée?

**Comment by AmauriC** [comment]
Vous pouvez modifier dans le fichier tarteaucitron.services.js cette ligne https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.services.js#L3822 pour changer la valeur de `needConsent` à `true`
