### ISSUE TITLE
Positionnement gestion des services

### ISSUE THREAD

**Issue by triclic** [AmauriC/tarteaucitron.js#728]
Salut à tous,
y a t'il une option de positionner la "Gestion de services" en bas à gauche plutôt que à droite. 
ou faut-il le faire à la main :)

Merci pour l'info
Cdt

**Comment by yunai39** [comment]
Bonjour,

Je crois que tu à l'option **iconPosition**

    "iconPosition": "BottomRight", /* Position of the icon between BottomRight, BottomLeft, TopRight and TopLeft */

**Comment by triclic** [comment]
je crois que cela marche seulement si on utilise l'icone...
Pas avec la box "gestion des services".

A confirmer...

**Comment by AmauriC** [comment]
Cette option est en effet juste pour l'icone, pour la mini bannière, voir https://github.com/AmauriC/tarteaucitron.js/discussions/681 ; )

**Comment by triclic** [comment]
ok merci
AmauriC
