### ISSUE TITLE
[Suggestion] Ajout de services

### ISSUE THREAD

**Issue by GeekCornerGH** [AmauriC/tarteaucitron.js#733]
Bonjour @AmauriC, j'ai quelques idées de services à ajouter.
- Discord (widget, de serveur)
- hCaptcha (alternative à reCAPTCHA)
- Plausible (alternative à Google Analytics)
- Maps (embed accessible via le menu partager du site)
Est-ce possible d'ajouter cela?
Bonne journée

**Comment by AmauriC** [comment]
Salut,

Pour que je puisse ajouter des services il me faut:
- le marqueur html nécessaire au chargement du service
- le lien vers la politique de confidentialité
- les cookies utilisés

**Comment by GeekCornerGH** [comment]
> Salut,
> 
> Pour que je puisse ajouter des services il me faut:
> - le marqueur html nécessaire au chargement du service
> - le lien vers la politique de confidentialité
> - les cookies utilisés

Les cookies, je ne peux pas te les fournir, je sais pas comment on fait xD
Par contre pour le reste, ça devrait être faisable. Je te trouve le reste.

**Comment by GeekCornerGH** [comment]
Discord : [https://discord.com/privacy](Politique de confidentialité)
Embed: https://discord.com/widget?id=[id du serveur]

**Comment by GeekCornerGH** [comment]
hCaptcha: [Politique de confidentialité](https://www.hcaptcha.com/privacy)
Intégration : ```html
<script src="https://hcaptcha.com/1/api.js" async defer></script>
<div class="h-captcha" data-sitekey="your_site_key"></div>
```

**Comment by GeekCornerGH** [comment]
Plausible: [Politique de confidentialité](https://plausible.io/privacy)
Intégration:
```html
<script defer data-domain="yourdomain.com" src="https://plausible.io/js/plausible.js"></script>
```

**Comment by GeekCornerGH** [comment]
Google Maps: [https://policies.google.com/privacy](Politique de confidentialité)
Intégration :
```html
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6315.955406606513!2d7.192576!3d47.214252900000005!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66e2964e34e2d%3A0x8ddca9ee380ef7e0!2sTour%20Eiffel!5e0!3m2!1sfr!2sch!4v1623342295177!5m2!1sfr!2sch" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
``` pour celui ci, je n'ai pas compris comment fonctionne l'url... Désolé

**Comment by Aaarrrgggh** [comment]
Bonjour,

Plausible est RGPD compatible par défaut, non ?

**Comment by GeekCornerGH** [comment]
> 
> 
> Bonjour,
> 
> Plausible est RGPD compatible par défaut, non ?

Honnêtement, j'en sais rien. D'après la politique, oui mais j'ai jamais testé, je suggère pour d'autres utilisateurs.

**Comment by GeekCornerGH** [comment]
@AmauriC y a t'il du neuf?
