### ISSUE TITLE
Attribut classe dans code Iframe

### ISSUE THREAD

**Issue by Aaarrrgggh** [AmauriC/tarteaucitron.js#734]
Bonjour,

j'ai besoin d'ajouter une classe CSS dans le code iframe. (<iframe class="blabla"). Mais je ne voudrais pas modifier en dur le fichier services.js. Y a-t-il un moyen de procéder ? 

J'ai voulu exécuter un script qui les ajoute automatiquement en passant par un eventListener sur le domReady mais ça ne fonctionne pas. J'ai également utilisé l'attribut defer pour l'exécution du JS, mais item, c'est inefficace.

Y aurait-il un tip ?

Merci

**Comment by BuyukCem** [comment]
Bonjour, tu as testé un truc comme ca: 

const iframe = x.getElementsByTagName("iframe");
iframe.classList.add("blabla");

et tu ajoute ce script après le : 
<script type="text/javascript" src="/tarteaucitron/tarteaucitron.js"></script>

**Comment by AmauriC** [comment]
Ca ne fonctionnera pas parce que tac se charge quand le DOM est prêt.

Il faudrait utiliser l'event de chargement du sevice.

Exemple si c'est youtube et que jQuery est chargé:

```
document.addEventListener("youtube_loaded", function(){
   jQuery('iframe[src*="youtube"]').addClass('maclasse');
});
```

**Comment by Aaarrrgggh** [comment]
Ok merci,

pas de Jquery de mon côté :)

il faudrait utiliser cet event pour chaque service intégrant une iframe ?

**Comment by Aaarrrgggh** [comment]
Ca a l'air de marcher ! Merci !

Je me demandais si on ne pouvait pas tout loader d'un coup ?

**Comment by AmauriC** [comment]
Non parce que ça dépend si l'utilisateur accepte ou non.
Tant que ce n'est pas accepté, l'iframe n'existe pas.

**Comment by Aaarrrgggh** [comment]
Ok merci, je clos le ticket alors :)
