### ISSUE TITLE
Google Calendar service

### ISSUE THREAD

**Issue by pulse-mind** [AmauriC/tarteaucitron.js#736]
Bonjour,

Bravo pour le travail réalisé. 
Je ne vois pas le service associé à Google calendrier. Vous pouvez voir sur cette page par exemple l'utilisation d'une iframe pour afficher un calendrier google qui génère un ensemble de cookies. 
https://www.saintjuliensurgaronne.fr/fr/index.html

Bien cordialement,
Fred

**Comment by GeekCornerGH** [comment]
Je viens de finir d'intégrer ça, j'irai push bientôt :)

**Comment by pulse-mind** [comment]
Alors bravo et merci !

**Comment by GeekCornerGH** [comment]
Aucun problème
