### ISSUE TITLE
GA cookie non détecté sur mobile

### ISSUE THREAD

**Issue by Sylv40** [AmauriC/tarteaucitron.js#737]
Bonjour,
tout d'abord merci pour ce script bien utile !
Je rencontre un problème côté mobile, la bannière ne s'affiche pas par défaut comme sur desktop et si je l'ouvre en cliquant sur l’icône, j'ai les cookie obligatoires cochés "autorisé" , jusqu'ici rien d'anormal, mais pas de cookie statistiques à autorisé, c'est marqué " Ce site n'utilise aucun cookie  nécessitant votre consentement" alors que GA devrait être détecté et me demander l'autorisation...

Si une âme charitable pourrait m'aider à solutionner ce problème, ça m’enlèverait une belle épine du pied.

Merci

**Comment by AmauriC** [comment]
Bonjour Sylvain, merci : )

Je viens de tester et ça à l'air de fonctionner correctement.

C'est peut-être juste un problème de cache.

Même problème en ouvrant une fenetre en 'navigation privée' sur votre tél?

**Comment by Sylv40** [comment]
Merci  beaucoup pour votre réponse rapide,
j'ai pourtant vidé le cache et les cookies,et tenté la navigation privée
avec le même résultat...
mais d'un autre tel cela fonctionne correctement... le soucis doit être du
côté des préférences de mon navigateur du téléphone...

Merci en tout cas !
et désolé pour le dérangement.

Bonne fin de journée

Le lun. 14 juin 2021 à 17:32, Amauri CHAMPEAUX ***@***.***> a
écrit :
