### ISSUE TITLE
Integration Pardot dans le menu Personnaliser

### ISSUE THREAD

**Issue by Vanlen1er** [AmauriC/tarteaucitron.js#738]
Salut Amauri,

Il y a bien Pardot dans les scripts mais il n'apparait pas dans le menu Personnaliser. Est ce que c'est possible de l'avoir ?

Merci

**Comment by AmauriC** [comment]
Salut,

Je ne suis pas sûr de comprendre le soucis. Pardot a été ajouté mais n'est pas visible dans le panel de gestion?
Possible d'avoir l'url du site?

**Comment by Vanlen1er** [comment]
Salut,
Oui c'est exactement ça. Le site c'est 4cadgroup.com. J'ai un peu modifié
le design à la demande du client.

Le lun. 14 juin 2021 à 17:30, Amauri CHAMPEAUX ***@***.***> a
écrit :

**Comment by AmauriC** [comment]
Le fichier service est trop ancien et ne contient pas pardot ; )
Mettez à jour: https://raw.githubusercontent.com/AmauriC/tarteaucitron.js/master/tarteaucitron.services.js

**Comment by Vanlen1er** [comment]
Ah mais oui, j'ai pas pensé à ça. On l'a lancé y'a pas longtemps mais ça fait un moment qu'on travaillait dessus :) Merci de ta rapidité !
