### ISSUE TITLE
Code de Conversion Adwords en 2 parties ?

### ISSUE THREAD

**Issue by ghost** [AmauriC/tarteaucitron.js#74]
Bonjour,
A l'heure actuelle, les conversions Adwords sont en 2 parties

Dans le <HEAD> de toutes les pages

<script async src="https://www.googletagmanager.com/gtag/js?id=AW-XXXXXXX"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'AW-XXXXXXX');
</script>

SUR LA PAGE A TRACKER

<script>
  gtag('event', 'conversion', {'send_to': 'AW-XXXXXX/xxxxxxxxxxxxxxxxxxx'});
</script>

Comment faire pour gérer cela avec TarteAUCitron ?

Merci

**Comment by AmauriC** [comment]
Le premier code est identique au service "Google Analytics (gtag.js)", il suffit de passer l'identifiant AW-xx a la place de celui d'analytic.

Pour la deuxième partie c'est à intégrer en dehors de tarteaucitron, si le premier tag n'est pas autorisé, la fonction échouera.
