### ISSUE TITLE
Google Adsense : Failed to load resource

### ISSUE THREAD

**Issue by jlesergent** [AmauriC/tarteaucitron.js#740]
Bonjour,

J'ai remplacé les scripts générés par Google Adsense par celui fourni dans la procédure d'installation. Cependant si on choisis d'autoriser Google Adsense, aux emplacements des bannières, j'ai le message "Google Adsense est désactivé" avec un bouton "Autoriser" qui au clique ne semble pas provoquer un événement. 

En regardant la console du navigateur j'ai ceci qui est retourné :

googleads.g.doubleclick.net/pagead/ads?client=ca-ca_pub_4301409126823487&output=html&h=835&slotname=5104132124&adk=2840065686&adf=566923778&pi=t.ma~as.5104132124&w=243&cr_col=1&cr_row=13&fwrn=2&lmt=1623752196&rafmt=9&psa=0&format=243x835&url=https%3A%2F%2Fwww.algomtl.com%2F&flash=0&crui=image_sidebyside&fwr=0&wgl=1&uach=WyJXaW5kb3dzIiwiMTAuMCIsIng4NiIsIiIsIjkxLjAuNDQ3Mi4xMDEiLFtdXQ..&dt=1623752196400&bpp=3&bdt=24915&idt=377&shv=r20210607&cbv=%2Fr20190131&ptt=9&saldr=aa&abxe=1&prev_fmts=243x29%2C336x280%2C336x280&correlator=1289473991028&frm=20&pv=1&ga_vid=1590785532.1623752196&ga_sid=1623752196&ga_hid=531366832&ga_fc=1&u_tz=120&u_his=2&u_java=0&u_h=1080&u_w=1920&u_ah=1040&u_aw=1920&u_cd=24&u_nplug=3&u_nmime=6&adx=733&ady=2794&biw=1903&bih=969&scr_x=0&scr_y=0&eid=21066433%2C31060972%2C21066612%2C44743203&oid=3&pvsid=554733652308124&pem=510&eae=0&fc=896&brdim=0%2C0%2C0%2C0%2C1920%2C0%2C1920%2C1040%2C1920%2C969&vis=1&rsz=o%7C%7CpoeEbr%7C&abl=CS&pfx=0&fu=128&bc=31&ifi=4&uci=a!4&btvi=3&fsb=1&xpc=iuTAqz7IeE&p=https%3A//www.algomtl.com&dtd=394:1 Failed to load resource: the server responded with a status of 400 ()

J'ai remis les anciens scripts et les bannières sont de nouveau ok.

Avez-vous une idée ce qui bloque dans mon cas l'affichage des bannière si on accepte ?

merci pour votre retour.

**Comment by AmauriC** [comment]
Bonjour,
Il faut juste supprimer la balise <script>, la balise <ins> a l'endroit ou doit s'afficher l'annonce est à laisser. C'est bien ce que vous avez fait?

**Comment by jlesergent** [comment]
Merci de votre retour mais je ne vois pas ce que vous indiquez par "supprimer la balise <script>"

J'ai placé le code de "Ajoutez cette partie à l'endroit ou le service doit s'afficher" aux placement de mes bannières (en prenant soin de remplacer les informations data-ad-client, data-ad-slot, width et height) :
``
<ins class="adsbygoogle" style="display:inline-block;width:widthpx;height:heightpx" data-ad-client="ca_pub_xxxxxxxxxxxxxxx" data-ad-slot="ad_slot"></ins><script type="text/javascript">(adsbygoogle = window.adsbygoogle || []).push({});</script>``

et placé l'appel à Adsense par tarteaucitron à celui de Analytics : 
`<script` type="text/javascript">
 /*Google Analytics*/
	tarteaucitron.user.gajsUa = "UA-XXXXXX-XX";
	tarteaucitron.user.gajsMore = function () { /* add here your optionnal _ga.push() */ };
	(tarteaucitron.job = tarteaucitron.job || []).push("gajs");
 /*Google Ads*/
	(tarteaucitron.job = tarteaucitron.job || []).push("adsense");
</script>``

Il y a plus d'appel de script qui a été fournis par Google.

**Comment by AmauriC** [comment]
J'ai édité le message qui était mal formaté.

Avec le code fourni par Google vous devez avoir une partie `<ins>...</ins>`, elle est différente de celle que vous avez construit avec la doc tarteaucitron?

**Comment by jlesergent** [comment]
Oui, il y a bien à chaque fois une partie ``<ins>...</ins>`` . Mais, sauf erreur, elle me semble pas différente : 
``<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>``
``<ins class="adsbygoogle"
     style="display:inline-block;width:160px;height:600px"
     data-ad-client="ca-pub-XXXXXXXX"
     data-ad-slot="XXXXXXX"></ins>``
``<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
`</script>``

**Comment by AmauriC** [comment]
Du coup c'est étrange : /

Possible d'avoir l'url de la page?

**Comment by jlesergent** [comment]
Oui, j'ai https://www.pointsdechine.com/ que j'utilise pour tester l’implémentation

**Comment by AmauriC** [comment]
C'est peut-être parce qu'il faut:
```
(adsbygoogle = window.adsbygoogle || []).push({});
```
après chaque balise `<ins>`

**Comment by jlesergent** [comment]
Je l'avais au début effectivement inséré :
``<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>``

après chaque balise ``<ins>`` mais avec le même résultat. Là je viens de le faire pour la bannière à droite de la carte France.

**Comment by AmauriC** [comment]
Je pense qu'il en faut autant que de pub mais je suis pas tout expert Adsense, peut être que quelqu'un ici pourra apporter une meilleure aide ;-)

**Comment by jlesergent** [comment]
je clos le sujet. J'ai bien mes bannières après les ajustements effectués suite de ce sujet.
