### ISSUE TITLE
GA4 - tagManager

### ISSUE THREAD

**Issue by youpiyoup** [AmauriC/tarteaucitron.js#744]
Bonjour,

On utilise la dernière version de Google Analytics (GA4), je crois encore en version beta, et je ne trouve pas dans la liste son son support.
Le script natif du gtag.js est celui-ci :

window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-***********');

Avez-vous prévu une évolution de votre côté ? 
merci :)

**Comment by AmauriC** [comment]
Hello

Le tag est le même que le service 'gtag', il suffit juste de mettre l'id `G-***********` au lieu de `UA-***********`; )

**Comment by youpiyoup** [comment]
Merci Amauri, je viens de voir que cela fonctionne :)

**Comment by youpiyoup** [comment]
Bon apparement fausse joie, ça ne marche pas avec le GA4, une idée ? :)

          tarteaucitron.user.gtagUa = 'G-*********';
            // tarteaucitron.user.gtagCrossdomain = ['example.com', 'example2.com'];
            tarteaucitron.user.gtagMore = function () { /* add here your optionnal gtag() */ };
            (tarteaucitron.job = tarteaucitron.job || []).push('gtag');

**Comment by Startouf** [comment]
@youpiyoup as-tu trouvé une solution ?

**Comment by FlorientR** [comment]
Bonjour,

Je relance le sujet. Avec le script Google suivant les remontées se font bien :

`
<script async src="https://www.googletagmanager.com/gtag/js?id=G-XXX"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-XXX');
</script>
`

Avec le code suivant, je n'ai plus les remontées : 

`
tarteaucitron.user.gtagUa = 'G-XXXX';
tarteaucitron.user.gtagMore = function () { /* add here your optionnal gtag() */ };
(tarteaucitron.job = tarteaucitron.job || []).push('gtag');
`

Je ne retrouve pas la partie sur le `dataLayer` dans mon inspection HTML (TAC v1.9.6).

@youpiyoup @Startouf avez-vous réussi à le faire fonctionner ?

**Comment by AmauriC** [comment]
Pourtant c'est bien le même code dans le service ga:
https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.services.js#L2012

Pas d'erreur dans la console?

**Comment by FlorientR** [comment]
> 

Non et j'ai même bien l'appel au `collect` ...
Je posterais la solution une fois trouvée.
