### ISSUE TITLE
Ajout de services podcasts

### ISSUE THREAD

**Issue by ecosphere-aggelos** [AmauriC/tarteaucitron.js#746]
Bonjour Amauri,

peux-tu ajouter, s’il te plait, les blocages automatiques des cookies qui viennent quand on intègre les podcasts de :

**France Culture** : https://www.franceculture.fr/
Politique de confidentialité : https://www.radiofrance.com/politique-d-utilisation-des-cookies-sur-les-sites-internet-du-groupe-radio-france
Iframe : <iframe src="https://www.franceculture.fr/player/export-reecouter?content=**ID_PODCAST**" width="481" frameborder="0" scrolling="no" height="137"></iframe>
Installe le cookie : laravel_session
Origine du cookie : player.captivate.fm

**Acast** : https://play.acast.com/
Politique de confidentialité : https://www.acast.com/fr/privacy
Iframe : <iframe title="Embed Player" width="100%" height="188px" src="https://embed.acast.com/**ID_PODCAST**" scrolling="no" frameBorder="0" style="border:none;overflow:hidden;"></iframe>
Installe les cookies : intercom-id-**ID_SESSION**, intercom-session-**ID_SESSION**
Origine des cookies : .acast.com

**Mixcloud** : https://www.mixcloud.com 
Politique de confidentialité : https://www.mixcloud.com/privacy/
Iframe :<iframe width="100%" height="60" src="https://www.mixcloud.com/widget/iframe/?hide_cover=1&mini=1&feed=**ID_PODCAST**" frameborder="0" ></iframe>
Installe les cookies : __stripe_mid, __stripe_sid, _gat, _ga, _gid, csrftoken, c, mx_t
Origine des cookies : .www.mixcloud.com et .mixcloud.com

Merci beaucoup !

**Comment by GeekCornerGH** [comment]
Au moment où j'écris ces lignes, je suis entrain d'implémenter ces services 😉

**Comment by ecosphere-aggelos** [comment]
Bonjour Amauri,

Merci pour la mise en place de ces services.

Je me permets de réouvrir l'issue car nous rencontrons un problème avec  :
- Acast : en mode auto, il n'est pas bloqué, exemple : https://campusprotestant.com/podcast/la-cimade-80-ans-dhistoire/
- France Inter : en mode auto, il n'est pas bloqué, exemple : https://campusprotestant.com/podcast/john-mary-featherstone-lart-au-service-de-la-foi/
- Ausha est bien bloqué mais la notice TAC apparait en double : https://campusprotestant.com/podcast/mes-amis-adam-et-eve-comprendre-le-recit-culte/

Pourrais-tu checker stp ? Merci beaucoup

**Comment by ecosphere-aggelos** [comment]
Acast : en mode auto, il n'est pas bloqué, exemple : https://campusprotestant.com/podcast/la-cimade-80-ans-dhistoire/
France Inter : en mode auto, il n'est pas bloqué, exemple : https://campusprotestant.com/podcast/john-mary-featherstone-lart-au-service-de-la-foi/

**Comment by ecosphere-aggelos** [comment]
Bonjour Amauri,
Je me permets de réouvrir l'issue car nous rencontrons un problème avec :

    Acast : en mode auto, il n'est pas bloqué, exemple : https://campusprotestant.com/podcast/la-cimade-80-ans-dhistoire/
    France Inter : en mode auto, il n'est pas bloqué, exemple : https://campusprotestant.com/podcast/john-mary-featherstone-lart-au-service-de-la-foi/
    Ausha est bien bloqué mais la notice TAC apparait en double : https://campusprotestant.com/podcast/mes-amis-adam-et-eve-comprendre-le-recit-culte/

Pourrais-tu checker stp ? Merci beaucoup

**Comment by ecosphere-aggelos** [comment]
Bonjour Amauri,

Je me permets de rouvrir l'issue car nous rencontrons encore ces problèmes  :
- Acast : en mode auto, il n'est pas bloqué, exemple : https://campusprotestant.com/podcast/la-cimade-80-ans-dhistoire/
- France Inter : en mode auto, il n'est pas bloqué, exemple : https://campusprotestant.com/podcast/john-mary-featherstone-lart-au-service-de-la-foi/
- Ausha est bien bloqué mais la notice TAC apparait en double : https://campusprotestant.com/podcast/mes-amis-adam-et-eve-comprendre-le-recit-culte/

Pourrais-tu voir cela, s'il te plait ? Merci beaucoup.

**Comment by AmauriC** [comment]
Acast et France culture n'ont pas encore été ajouté, il faut faire des modifs sur le PR (https://github.com/AmauriC/tarteaucitron.js/pull/748).

Pour ausha, cette règle CSS cachera un des 2:

```
span[id*="ausha"]:first-child {
    display: none;
}
```

**Comment by marcbelletre** [comment]
Hello @AmauriC,

Pour info il y a une petite erreur dans la doc concernant l'installation du service Acast. Le premier paramètre est `id1` et non `id`. Je ne crois pas qu'on puisse faire de PR dans la doc ?

Merci ! :)

<img width="1013" alt="Capture d’écran 2022-02-28 à 12 24 38" src="https://user-images.githubusercontent.com/6853334/155975489-0ba7fdc1-7b29-4c43-8f2c-1238e9aa87bf.png">

**Comment by AmauriC** [comment]
Merci, c'est corrigé : )
