### ISSUE TITLE
Lien Continuer sans accepter

### ISSUE THREAD

**Issue by Phoennix** [AmauriC/tarteaucitron.js#747]
Bonjour Amauri,

Serait-il svp possible d'avoir un paramétrage permettant d'afficher un lien "Continuer sans accepter" en haut à droite de la popup de consentement, comme le font actuellement certains gestionnaires de cookies ?
Un clic sur ce lien aurait pour effet de refuser tous les cookies et d'enregistrer ce choix (et non uniquement fermer la popup).

J'ai vu sur le forum [WordPress](https://wordpress.org/support/topic/continuer-sans-accepter/) que vous indiquiez il y a quelques semaines que tarteaucitron.js ne le fait actuellement pas car vous ne proposez que des solutions conformes.

Or il s'avère que ce lien est bien conforme au RGPD, comme le confirme la délibération [n°2020-092 du 17 septembre 2020](https://www.cnil.fr/sites/default/files/atoms/files/recommandation-cookies-et-autres-traceurs.pdf) de la CNIL. Il y est indiqué sur la figure 5 illustrant le paragraphe 33 du PDF de la délibération (pages 9 et 10) :
> l'utilisateur peut cliquer sur « continuer sans accepter » pour exprimer son refus au dépôt et à la lecture de traceurs.

**Comment by AmauriC** [comment]
Hello,

C'est en effet possible de le faire mais le but d'afficher un petit lien en haut est d'essayer de faire en sorte que l'utilisateur ne le vois pas et qu'il clique sur Accepter qui sera beaucoup mieux mis en valeur. 

> La CNIL a également estimé que l’intégration d’un bouton « Tout refuser » sur le même niveau et sur le même format que le bouton « Tout accepter » permet d’offrir un choix clair et simple pour l’internaute.
https://www.cnil.fr/fr/nouvelles-regles-cookies-et-autres-traceurs-bilan-accompagnement-cnil-actions-a-venir

Si vraiment il y a de la demande pour cette option, c'est faisable de l'ajouter ; )

**Comment by Phoennix** [comment]
On ne va pas se le cacher, c'est clairement le but souhaité ^^

Depuis que nos clients chez qui on a installé Tarte au Citron se sont aperçu que c'était accepté par la CNIL, plusieurs nous ont demandé de remplacer le bouton "Tout accepter" du gestionnaire de cookies.

**Comment by BuyukCem** [comment]
Bonjour, 
Pour info j'avais ajouté (ligne 601)une croix activable avec le paramètre closePopup  elle ferme juste la fenêtre sans consentement

` if(tarteaucitron.parameters.closePopup === true){
                    setTimeout(function() {
                        var closeElement = document.getElementById('tarteaucitronAlertBig'),
                            closeSpan = document.createElement('span');
                        if (closeElement) {
                            closeSpan.textContent = 'X';
                            closeSpan.setAttribute('id', "tarteaucitronCloseCross");
                            closeElement.insertBefore(closeSpan, closeElement.firstElementChild);
                        }
                    }, 100);
                }
  `
  
  il faut peut être modifier le code du coup

**Comment by AmauriC** [comment]
Exact, du coup en désactivant le bouton "tout refuser" avec l'option `DenyAllCta: false` et en changeant le texte ça fait le job:

```
document.addEventListener("tac.root_available", function(){
   document.getElementById('tarteaucitronCloseCross').innerHTML = 'Continuer sans accepter';
});
```
