### ISSUE TITLE
Bing Ads conversion tracker

### ISSUE THREAD

**Issue by eficiens-eric** [AmauriC/tarteaucitron.js#749]
Bonjour,
Comment ajouter une conversion Bing pour qu'elle soit intégrée dans Tarte au citron ?
Chez Microsoft ils demandent de poser ces deux lignes de code
window.uetq = window.uetq || [];
window.uetq.push('event', 'submit_lead_form', {});

Je pourrais les charger en direct, partant du principe que si Bing n'a pas été validé par l'utilisateur, la fonction window.uetq.push partira en erreur et ne sera pas exécutée… mais il y a sûrement plus propre.

Merci d'avance

**Comment by AmauriC** [comment]
En effet ça fonctionnera mais peut-être trop en avance.

Plus propre:

```
document.addEventListener("bingads_loaded", function() {
   window.uetq.push('event', 'submit_lead_form', {});
});
```

**Comment by eficiens-eric** [comment]
Merci pour la réponse rapide Amauri !
Dans ce cas précis, comme c'est un pixel de conversion, lié à l'arrivée sur une page, je mets juste l'eventlistener sur la page concernée, et on est OK.

**Comment by chaissac** [comment]
Mieux vaut quand même s'assurer que uetq est bien défini comme dans le code d'origine, sait-on jamais... :)
``js
document.addEventListener("bingads_loaded", () => {
   window.uetq = window.uetq || [];
   window.uetq.push('event', 'submit_lead_form', {});
}, { once : true } );
``
