### ISSUE TITLE
Intégration Issuu.com - changement d'URL

### ISSUE THREAD

**Issue by ArnaudP21** [AmauriC/tarteaucitron.js#750]
Hello @AmauriC,

Tout d'abord, merci pour ton plugin et toutes les améliorations que tu apportes à celui-ci depuis la sortie.

J'ai un problème avec l'intégration du lecteur Issuu. Jusqu'à présent l'#ID décrite dans l'installation du service sur ton site fonctionnait mais Issuu a changé les URLs et ajoute maintenant les informations via des paramètres d'URL. Voici un exemple :  [https://e.issuu.com/embed.html?d=liberon_guide_2020-liens&hideIssuuLogo=true&u=groupe-v33](https://e.issuu.com/embed.html?d=liberon_guide_2020-liens&hideIssuuLogo=true&u=groupe-v33).

Quel est le processus pour l'intégrer maintenant ? Est-ce toujours possible ?

Cordialement,

**Comment by AmauriC** [comment]
Merci : )

C'est déjà pris en charge, il faut juste passer comme id `d=liberon_guide_2020-liens&hideIssuuLogo=true&u=groupe-v33`

**Comment by ArnaudP21** [comment]
Ah merci ! J'ai tout essayé sauf ça forcément ! 🥇
