### ISSUE TITLE
TarteAuCitron et GoogleTag Manager

### ISSUE THREAD

**Issue by chaissac** [AmauriC/tarteaucitron.js#751]
Bonjour,
Nous utilisons TarteAuCitron sur plusieurs sites, en version Premium.
Nous sommes amenés à y ajouter des services personnalisés (comme doubleclick par exemple).
Nos équipes marketing souhaiteraient avoir un peu plus la main et le confort d'utilisation de Google Tag Manager.
Outre la présence de services absents nativement de TarteAuCitron, cela permet la pose de tag analytics finement au niveau des pages, etc. Mais se pose alors évidemment le problème du consentement.
Je ne vois pas trop comment concilier GTag et TarteAuCitron, les 2 étant finalement des gestionnaires de tag. Bien sûr on peut autoriser GTag depuis TarteAuCitron, mais cela ne permet pas à l'utilisateur de choisir quels services il accepte ou refuse via GTag, il accepte ou refuse en bloc, sans même savoir ce que GTag va injecter. Cela ne me semble pas trop conforme aux recommandations CNIL.
Est-ce que quelqu'un utilise GTag avec TarteAuCitron ? Si oui comment ?
Cette page du support Google ne m'a pas vraiment aidé, qu'en retenez-vous ? https://support.google.com/tagmanager/answer/10718549?hl=fr

**Comment by nicozerr** [comment]
Bonjour,

Personnellement, je fais appeler Google Tag Manager par Tarteaucitron. Si un utilisateur n'autorise pas GTM, alors aucun tag ni déclencheur ni autre service passé au travers de GTM ne fonctionnera pour lui.

Par contre, en cas de consentement, tout y passe.
Et c'est là qu'il me semble que la CNIL oblige à informer les utilisateurs de ce que cela implique d'activer GTM, c.-à-d. tous les services susceptibles de déposer des cookies de tracking comme Google Analytics (GTag ou juste Universal Analytics), Hotjar, AdAdvisor, Quora...

**Comment by chaissac** [comment]
> 
> Par contre, en cas de consentement, tout y passe.
> Et c'est là qu'il me semble que la CNIL oblige à informer les utilisateurs de ce que cela implique d'activer GTM, c.-à-d. tous les services susceptibles de déposer des cookies de tracking comme Google Analytics (GTag ou juste Universal Analytics), Hotjar, AdAdvisor, Quora...

Oui voilà, c'est le coeur du problème ! L'utilisateur doit non seulement être informé mais aussi pouvoir accepter ou refuser chaque service individuellement.

**Comment by eficiens-eric** [comment]
J'utilise GTM pour charger les tags avec la nomenclature TauC. GTM est chargé systématiquement, en tant que coquille, puis chaque tag a été réécrit en HTML avec la syntaxe TauC. C'est assez fastidieux, et cela limite l'intérêt de GTM au niveau des balises, mais cela me permet de continuer à utiliser GTM pour gérer les balises. Pour celles n'existant pas encore dans TaC, je crée le code aussi dans GTM.
Et bien sûr ça fonctionne mieux pour des pixels chargés sur des pages que pour des déclencheurs liés à des actions (clics, scroll) où je ne suis pas certain qu'on arrive à envoyer l'info à TauC et déclencher la balise.

Idéalement, j'aurais bien aimé une simple variable on/off à interroger dans GTM, je crois bien que d'autres CMP le font.
