### ISSUE TITLE
Nouveau service : Effiliation (Effinity)

### ISSUE THREAD

**Issue by chaissac** [AmauriC/tarteaucitron.js#752]
Bonjour,

On m'a demandé en interne l'ajout d'un nouveau service custom, pour Effiliation (https://www.effiliation.com/), une solution d'affiliation et de gestion de partenariats du groupe Effinity.
Je vous livre ici mon implémentation, s'il peut servir à quelqu'un d'autre ou être intégré dans la liste des services gérés (ce qui m'arrangerait, pour le suivi des activations dans la version pro :) !). Il n'y a que la variable tarteaucitron.user.effiliationId à configurer :
```js
tarteaucitron.services.effiliation = {
  key: 'effiliation',
  type: 'ads',
  name: 'Effiliation (Effinity)',
  uri: 'https://www.effiliation.com/politique-de-confidentialite/',
  needConsent: true,

  cookies: function () {
      var effiCookie = (tarteaucitron.user.effiliationId || '');
      return [ 'Effi'+effiCookie, 'Date'+effiCookie, 'Affi'+effiCookie];
    }(),
    "js": function () {
        "use strict";
        if (tarteaucitron.user.effiliationId === undefined) {
            return;
        };
        (function() {
            var eff = document.createElement('script');
            eff.type = 'text/javascript';
            eff.charset = 'UTF-8';
            eff.async = true;
            eff.id = 'effiliation';
            eff.src = 'https://track.effiliation.com/ct/an'+tarteaucitron.user.effiliationId+'.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(eff, s);
        })();
    }
};
```

**Comment by AmauriC** [comment]
C'est mieux d'utiliser `tarteaucitron.addScript()` pour charger le script que le `document.createElement('script');`

Pour le reste ça me semble tout bon, si vous pouvez faire un pr c'est top 👍

**Comment by chaissac** [comment]
Du coup ma fonction deviendrait juste :
`(function() {
            tarteaucitron.addScript('https://track.effiliation.com/ct/an'+tarteaucitron.user.effiliationId+'.js','effiliation');
        })();`
Et le reste se fait tout seul (le async, le charset, etc.) ?

**Comment by AmauriC** [comment]
Oui, dans la fonction js juste:

```
        "use strict";
        if (tarteaucitron.user.effiliationId === undefined) {
            return;
        };
        tarteaucitron.addScript('https://track.effiliation.com/ct/an'+tarteaucitron.user.effiliationId+'.js','effiliation');
```
