### ISSUE TITLE
Nouveau service : Google Campaign Manager (DoubleClick Campaign Manager)

### ISSUE THREAD

**Issue by chaissac** [AmauriC/tarteaucitron.js#753]
Bonjour,
Un service demandé par mes utilisateurs : Google Campaign Manager (DoubleClick Campaign Manager).
J'ai implémenté ce service sous le code doubleclick, plus court. 
Il faut paramétrer tarteaucitron.user.doubleclickId, tarteaucitron.user.doubleclickType, tarteaucitron.user.doubleclickParam, et tarteaucitron.user.doubleclickCat, et on peut par ailleurs appeler ultérieurement la fonction window.doubleclick(cat). Pour de plus amples informations, se référer à la doc du service... Ceci est une implémentation "basique" du service, on pourrait faire plus complexe, mais c'était suffisant pour nos besoins :
```js
  tarteaucitron.services.doubleclick = {
      "key": "doubleclick",
      "type": "ads",
      "name": "Google Campaign Manager",
      "uri": "https://adssettings.google.com/",
      "needConsent": true,
      "cookies": [ '1P_JAR','APISID','CONSENT','HSID','IDE','NID','OTZ','SAPISID','SID','SIDCC','SSID','__Secure-3PAPISID','__Secure-3PSID','__Secure-3PSIDCC'],
      "js": function () {
          "use strict";
          window.doubleclick = function (cat) {
              var axel = Math.random() + "";
              var a = axel * 10000000000000;
              var iframe = document.createElement('iframe');
              iframe.style.display = "none";
              if (tarteaucitron.user.doubleclickParam === undefined) tarteaucitron.user.doubleclickParam='';
              iframe.src = 'https://'+tarteaucitron.user.doubleclickId+'.fls.doubleclick.net/activityi;src='+tarteaucitron.user.doubleclickId+';type='+tarteaucitron.user.doubleclickType+';cat='+cat+';dc_lat=;dc_rdid=;tag_for_child_directed_treatment=;'+tarteaucitron.user.doubleclickParam+'ord=1;num=' + a + '?';
              iframe.width=1;
              iframe.height=1;
              iframe.frameborder='0';
              document.body.appendChild(iframe);
          }
          if (tarteaucitron.user.doubleclickId === undefined || tarteaucitron.user.doubleclickType === undefined || tarteaucitron.user.doubleclickCat === undefined ) {
              return;
          }
          window.doubleclick(tarteaucitron.user.doubleclickCat);
      }
};
```

**Comment by pierretux** [comment]
Bonjour,

Ce service est lier à gtag je pense car sur un pojet j'ai ce besoin.
Est ce que le rajout du service sera réaliser ou il manque des informations ?

Merci

**Comment by AmauriC** [comment]
Le check pour `tarteaucitron.user.doubleclickId` est fait après son utilisation, ce n'est pas très logique.

Pour la cookie SID, SSID, NID son très commun. Ils sont vraiment déposés par ce service sur le domaine du site?
