### ISSUE TITLE
Nouveau service : MyFeelBack

### ISSUE THREAD

**Issue by chaissac** [AmauriC/tarteaucitron.js#754]
Bonjour,
Un autre service que j'ai dû ajouté : MyFeelBack, une gestion (française) des feedbacks clients (https://www.myfeelback.com/fr)
Les params sont tarteaucitron.user.myfeelbackId et optionnellement une fonction tarteaucitron.user.myfeelbackMore()
```js
// MyFeelBack
tarteaucitron.services.myfeelback = {
    "key": "myfeelback",
    "type": "social",
    "name": "MyFeelBack",
    "uri": "https://www.myfeelback.com/fr",
    "needConsent": true,
    "cookies": ['mfb.actor.beta.'],
    "js": function () {
        "use strict";
      if (tarteaucitron.user.myfeelbackId === undefined) {
              return;
          }
      window._Mfb_ud = {
        _context : {
                  lang : undefined, // You can force the language of the survey.
                  _page : {
                      url : location.pathname,
                      storageDuration : 30
                      // You can add page's properties here ie : pageProperties : { property1 : 'value', property2 : 'value'}
                  }
        }
      };
      
      (function() {
        var mfb = document.createElement('script');
        mfb.type = 'text/javascript';
        mfb.charset = 'UTF-8';
        mfb.async = true;
        mfb.id = 'MFBActor';
        mfb.src = 'https://actorssl-5637.kxcdn.com/actor/'+tarteaucitron.user.myfeelbackId+'/action';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(mfb, s);
      })();
          if (typeof tarteaucitron.user.myfeelbackMore === 'function') {
              tarteaucitron.user.myfeelbackMore();
          }
      }
  };
```

**Comment by chaissac** [comment]
Je n'arrive pas à mettre tout mon code en "code", désolé...

**Comment by AmauriC** [comment]
- cookie list is not complete: https://help.myfeelback.com/fr/quels-sont-les-cookies-d%C3%A9pos%C3%A9s-par-un-dispositif-de-collecte-myfeelback
- better to use tarteaucitron.addScript to load https://actorssl-5637.kxcdn.com/...
- _context.lang as undefined is ok?

I note that, if you can submit a pr it's perfect :)

**Comment by chaissac** [comment]
Ok je vais revoir ma cookie list, merci ^^
_context.lang as undefined is ok, language is defined in the survey, but can be overidden here (could be set by a tarteaucitron.user.myfeelback.lang for example).
Je n'ai jamais fait de pull request en revanche, pas à l'aise avec ça.

**Comment by AmauriC** [comment]
Désolé pour l'anglais, je me suis visiblement embrouillé entre plusieurs tickets ^^

Pas de soucis pour le PR, je m'en occuperai.
