### ISSUE TITLE
cookieDomain sur différentes applications ayant le même domaine

### ISSUE THREAD

**Issue by cyrilmonnom** [AmauriC/tarteaucitron.js#767]
Bonjour @AmauriC ,

Je gère actuellement plusieurs applications. Les environnements de test/recette sont sur le même domaine.

**Exemple** :

_Application 1_ 

- Test/recette :  espace1-application1.test.mondomainedetest.fr, espace2-application1.test.mondomainedetest.fr, espace-3-application1.test.mondomainedetest.fr
- Production :  espace-1.mondomaineprodapplication1.fr, espace-2.mondomaineprodapplication1.fr, espace-3.mondomaineprodapplication1.fr

_Application 2_ 

- Test/recette :  espace1-application2.test.mondomainedetest.fr, espace2-application2.test.mondomainedetest.fr, espace-3-application2.test.mondomainedetest.fr
- Production :  espace-1.mondomaineprodapplication2.fr, espace-2.mondomaineprodapplication2.fr, espace-3.mondomaineprodapplication2.fr

**Contexte**
Le cookie du CMP doit être partagé en fonction des applications.
Lorsque je veux tester le CMP sur les 2 applications de test/recette, les cookie est partagé car j'utilise la variable suivante : 
"cookieDomain": ".mondomainedetest.fr",

Le problème est que le cookie se partage entre les différentes applications

Pouvez-vous me donner vos recommandations ?

Cordialement,

**Comment by AmauriC** [comment]
Vous pouvez modifier la valeur de `"cookieName": "rgpdapp1",` pour différencier les applications.

**Comment by cyrilmonnom** [comment]
@AmauriC 

Je peux par exemple faire ? Dois-je donner un nom de cookie différent ? ou je peux garder pour tous : `"cookieName": "tarteaucitron",`

Application 1
"cookieDomain": ".mondomainedetest.fr",

Appication 2
"rgpdapp1": ".mondomainedetest.fr",

Appication 3
"rgpdapp2": ".mondomainedetest.fr",

**Comment by AmauriC** [comment]
`cookieDomain` doit toujours rester `cookieDomain`, ce n'est pas un paramètre, c'est le nom de l'option.

Il faut laisser l'option `"cookieDomain": ".mondomainedetest.fr",` partout et modifier l'option `"cookieName": "rgpdapp1",` en fonction de vos applications.

**Comment by cyrilmonnom** [comment]
merci @AmauriC
