### ISSUE TITLE
SHARETHIS

### ISSUE THREAD

**Issue by puddlec** [AmauriC/tarteaucitron.js#77]
sharethis have completly updated the share code
<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=UNIQUEID &product=sticky-share-buttons"></script>

if you use the sticky share buttons then you just have to add the above javascript

whereas if you use the inline share buttons then you have to also add <div class="sharethis-inline-share-buttons"></div>.

the code you provide only supports the legacy code, and  not the newer version

**Comment by Clad86** [comment]
I add this code to my project

// sharethis sticky
tarteaucitron.services.sharethissticky = {
        "key": "sharethissticky",
        "type": "social",
        "name": "ShareThis Sticky",
        "uri": "http://www.sharethis.com/legal/privacy/",
        "needConsent": true,
        "cookies": ['__unam'],
        "js": function () {
            "use strict";
            if (tarteaucitron.user.sharethisstickyPublisher === undefined) {
                return;
            }
            var uri = 'https://platform-api.sharethis.com/js/sharethis.js#property='+tarteaucitron.user.sharethisstickyPublisher+'&product=sticky-share-buttons';
            tarteaucitron.addScript(uri, '', function () {});
        },
    };

    tarteaucitron.user.sharethisstickyPublisher = 'your-identifier';
    (tarteaucitron.job = tarteaucitron.job || []).push('sharethissticky');

**Comment by josyan** [comment]
@Clad86 Merci ! Si le `product` était paramétrable au même titre que `property`, je pense que ça mériterait d'être mergé au code, ça fonctionne très bien.
