### ISSUE TITLE
Problème avec le service Facebook

### ISSUE THREAD

**Issue by lphm** [AmauriC/tarteaucitron.js#771]
Bonjour,
J'ai un soucis avec ce service. J'ai rajouté le code JS pour ajouter le service facebook, j'ai remplacé le code de Facebook par le code HTML donné par TAC et rien n'y fait : le bouton de partage de s'affiche pas.
En regardant dans la console développement : le code HTML est bien remplacé par le widget mais celui-ci ne s'affiche pas du tout...
Une idée ?
Merci.

**Comment by AmauriC** [comment]
Possible d'avoir une url pour voir le problème?
