### ISSUE TITLE
youtube ne passe pas le cap de la validation avec validator.w3.org

### ISSUE THREAD

**Issue by flexi2202** [AmauriC/tarteaucitron.js#772]
bonsoir 
je viens d installer la version 1.93 de tarteaucitron

et je viens de faire un essai en remplaçant videoID par data-videoID mais la vidéo ne se lance plus
l écran est noir 

j ai modifie également le service tarteaucitron.services.js avec le script 
https://github.com/AmauriC/tarteaucitron.js/pull/760/files

**Comment by gcorbelin** [comment]
Pour compléter, j'ajouterai que les markups pour les vidéos Youtube remontent des erreurs de contrôle w3c si les cookies ne sont pas encore acceptés ou si ils ont été refusés. 

Par exemple, sur la balise `<div class="youtube_player" videoID="6Ykcj98oYDE" width="560" height="315" theme="dark" rel="1" controls="1" showinfo="1" autoplay="0"></div>`, le w3c remonte en erreur : 

`Error: Attribute "videoid" not allowed on element "div" at this point.`
`Error: Attribute "width" not allowed on element "div" at this point.`
`Error: Attribute "height" not allowed on element "div" at this point.`
`Error: Attribute "theme" not allowed on element "div" at this point.`
`Error: Bad value "1" for attribute "rel" on element "div": The string "1" is not an absolute URL.`
`Error: Attribute "controls" not allowed on element "div" at this point.`
`Error: Attribute "showinfo" not allowed on element "div" at this point.`
`Error: Attribute "autoplay" not allowed on element "div" at this point.`

L'utilisation de data-attributes sur la `<div>` plutôt que des attributs directement et apporter les mêmes modifications que pour les vidéos Viméo (`video_id = x.getAttribute("data-videoID") || x.getAttribute("videoID"),`) pourrait certainement corriger le problème.

Dans le même élan, peut-être apporter les mêmes modifications pour les vidéos Daiymotion ?

**Comment by CIMEOS** [comment]
Nous avons aussi le même problème dans mon agence, je viens de proposer une correction https://github.com/AmauriC/tarteaucitron.js/pull/782
