### ISSUE TITLE
Ajout d'un bouton de confirmation après avoir sélectionné les cookies autorisés/réfusés

### ISSUE THREAD

**Issue by Piju** [AmauriC/tarteaucitron.js#777]
Bonjour,

Je pense qu'il serait judicieux et plus intuitif de mettre un bouton de confirmation dans le bas de la modal après avoir fait le choix des services acceptés/refusés comme ceci (à titre d'exemple, la couleur n'étant pas forcément idéale) :

![bouton-validation-cookies](https://user-images.githubusercontent.com/5053526/129374569-7d64b7d5-4f8a-47c2-84de-4c872fa8f884.jpg)

Qu'en pensez-vous ?

**Comment by AmauriC** [comment]
En effet c'est une bonne idée = )
