### ISSUE TITLE
Ajout de service affilae.com

### ISSUE THREAD

**Issue by matmicro** [AmauriC/tarteaucitron.js#778]
Hello,

Est ce possible d'ajouter le code correspondant au service affilae.com ?

Voici le code de tracking des clicks :
<script type="text/javascript">
    var _ae = {
        "pid":"xxxxxxxxx",
    };
    (function() {
        var element = document.createElement('script'); element.type = 'text/javascript'; element.async = true;
        element.src = '//static.affilae.com/ae-v3.5.js';
        var scr = document.getElementsByTagName('script')[0]; scr.parentNode.insertBefore(element, scr);
    })();
</script>

Thanks

**Comment by matmicro** [comment]
Any chance for someone to get a look on this new feature requirement ?

Thanks

**Comment by AmauriC** [comment]
Je l'ai ajouté hier mais oublié d'update cette issue ; )
https://github.com/AmauriC/tarteaucitron.js/commit/5e27eab8870894e83ff8d492bd452ae1254b7d4d
