### ISSUE TITLE
Mauvaise prédiction de l'URL du script tarteaucitron.js

### ISSUE THREAD

**Issue by AIMAR-S** [AmauriC/tarteaucitron.js#779]
Bonjour,

Lors du développement d'une app React j'ai rencontré un problème à cause d'une "erreur" dans le script qui essaie de récupérer l'url de laquelle `tarteaucitron.js` à été chargé.

Heureusement j'ai pu bypass cette erreur en settant la variable `tarteaucitronForceCDN` en mettant mon url locale.

Le bout de script qui pose problème est au tout début :

```
    scripts = document.getElementsByTagName('script'),
    path = scripts[scripts.length - 1].src.split('?')[0],
    tarteaucitronForceCDN = (tarteaucitronForceCDN === undefined) ? '' : tarteaucitronForceCDN,
    cdn = (tarteaucitronForceCDN === '') ? path.split('/').slice(0, -1).join('/') + '/' : tarteaucitronForceCDN,
```

La 1ère ligne récupère donc l'URL du dernier tag html `<script>` et avec les lignes suivantes s'en sers comme base pour charger les scripts suivants.

C'est à tort qu'il fait cela. Rien ne dit ( et encore plus dans une app react ) que `tarteaucitron.js` est bien le dernier script dans tout ceux présents dans le DOM.

Dans une app React je ne suis pas maitre de la position, de la temporalité du chargement du script. Ceci dit même dans une page web classique si le script met un peu de temps à charger peut-être que d'autres auront ajouté des balises `<script>` ce qui va forcément invalider ce choix. 

Et même au plus simple si je ne suis pas conscient qu'il faut impérativement que `tarteaucitron.js` soit le dernier script positionné dans le DOM cela peut poser pb. Et à voir cette étape https://tarteaucitron.io/en/install/ , rien ne le laisse présager.

Alors oui, heureusement `tarteaucitronForceCDN` permet de forcer et donc de palier à cette _erreur_. Mais je pense qu'il serait bien de trouver un meilleur moyen de récupérer le path du script.

Peut-être avec un sélecteur plus précis y inclueant la présence de `tarteaucitron.js` dans l'url ? 

Ex: 

```document.querySelector('script[src*="tarteaucitron.js"]')```

De plus quand on a les options :
```
useExternalJs
useExternalCSS
```
Toutes 2 à false, se retrouver avec un chargement "externe" à cause de `scripts[scripts.length - 1].src.split('?')[0]` est étonnant.

En espérant avoir été utile.

N'hésitez pas.

Stéphane.

**Comment by AmauriC** [comment]
Bonjour Stéphane, merci pour tes explications!

Même problème avec une extension WordPress: https://wordpress.org/support/topic/link-with-javascript-in-it/#post-14783222

La solution proposée est d'utiliser `currentScript` mais pas de support IE donc j'aime moyen :/
https://developer.mozilla.org/fr/docs/Web/API/Document/currentScript

**Comment by AIMAR-S** [comment]
Bonjour Amauri,

De rien :)

J'avoue que cela peut réduire le support de cette lib qui ce qui serait bien dommage et en plus je pense que cet issue est assez rare, ça ne vaudrait pas le coup.

Au mieux ajouter la sélection avec le nom du script comme je l'ai décrit ?
