### ISSUE TITLE
Take into account of the "Do Not Track" value sent by the browser (navigator.doNotTrack)

### ISSUE THREAD

**Issue by chaissac** [AmauriC/tarteaucitron.js#78]
Hello,

What if the navigator.doNotTrack value is set to 1 ? I think we should disable all the service by default and maybe replace the infoBox by a message like :
The "Do Not Track" option is enabled in your browser. All cookies and services are disabled according to your will.
Or something in a better english :) 
In France, it's a CNIL's recommandation (and I think it's an EU's recommandation too) to take account of DNT.

Thx !

**Comment by eldk** [comment]
https://caniuse.com/#feat=do-not-track

**Comment by bleutzinn** [comment]
Perhaps like this:
```
var doNotTrack = (navigator.doNotTrack === "1" || navigator.doNotTrack === "yes" || navigator.msDoNotTrack === "1" || window.doNotTrack === "1");
if (doNotTrack) {
    highPrivacy = true;
}
```

**Comment by eldk** [comment]
https://help.pinterest.com/fr/articles/we-support-do-not-track
