### ISSUE TITLE
Uncaught TypeError: tarteaucitron.getElemAttr is not a function

### ISSUE THREAD

**Issue by olivier-pierre** [AmauriC/tarteaucitron.js#787]
We use the PRO version on a website, by calling the folloing script : `https://tarteaucitron.io/load.js?domain=XXX&uuid=1234abcd`. The returned code have the version=20210509, same as https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.js but the content differ.  We do not have the `getElemAttr` function added by the 5515b8a8394 commit, 12 days ago.

**Comment by eficiens-eric** [comment]
Bonjour, même problème sur un de nos sites, et ça bloque le player Youtube.
Il semble qu'il y ait un décalage sur le CDN ?

**Comment by AmauriC** [comment]
Je viens de forcer la mise à jour du cdn, vider le cache côté navigateur devrait régler le problème.

**Comment by olivier-pierre** [comment]
thanks @AmauriC !  The `https://tarteaucitron.io/load.js?domain=XXX&uuid=1234abcd` is now up-to-date.

Having an automated CDN update should prevent issues like that in future :robot: , isn't it ?
