### ISSUE TITLE
IE11: Erreur dans le fichier service.js

### ISSUE THREAD

**Issue by fred-44** [AmauriC/tarteaucitron.js#802]
Bonjour,

Nous avons constaté une erreur dans le fichier "tarteaucitron.service.js" (v1.9.4) à la ligne 2545 (pour le service "intercomChat").

Il y a une virgule en trop qui bloque le chargement du fichier sous IE11.

Frédéric

**Comment by AmauriC** [comment]
Merci, c'est corrigé 👍
