### ISSUE TITLE
Ouverture du panneau tarteaucitron sur chaque page

### ISSUE THREAD

**Issue by ArnaudP21** [AmauriC/tarteaucitron.js#805]
Bonjour,

Je viens d'implémenter tarteaucitron via la version Pro sur le site liberon.fr. Jusqu'à la semaine dernière, il était implémenté en manuel et je n'avais aucun problème. Depuis la mise en ligne la semaine dernière, 2 visiteurs (1 externe à l'entreprise et 1 en interne) se sont plaints que le panneau s'affichait sur toutes les pages. Je n'ai pas réussi à reproduire le problème de mon côté.

De plus, j'ai remarqué que lorsque je switche sur une page qui contient une vidéo youtube comme celle-ci par exemple : https://www.liberon.fr/produit/la-peinture-meuble-a-base-de-caseine/, le panneau s'affiche à nouveau pour accepter les cookies Youtube. J'ai le même problème avec Issuu. N'est-il pas possible de le faire dès l'entrée sur le site pour l'ensemble des cookies ?

Autre problème, suite à l'implémentation via le plugin, j'ai intégré HOTJAR dans Gtag manager. Tout est OK avec la prévisualisation GTag mais rien ne remonte dans le BO Hotjar. Pourquoi ?

Cordialement,

**Comment by AmauriC** [comment]
Je n'arrive pas non plus à reproduire le bug de réouverture et au niveau configuration tout est ok.

Il est normal que le bandeau se réaffiche si un nouveau service demande l'attention de l'internaute.
Pour forcer le choix sur un service qui n'est pas dispo sur toutes les pages, vous pouvez ajouter ce code js (ex pour youtube):
```
jQuery(function() {tarteaucitron.job.push('youtube');});
```

Concernant hotjar je ne sais pas, ça ne passe par tarteaucitron?

**Comment by ArnaudP21** [comment]
Ok merci, c'est bien ce qu'il me semblait. C'est sûrement dû à du cache alors peut-être ?

Est-ce que je dois ajouter ce code sur le thème enfant dans le fichier fonctions.php ?

Je vais essayer de le passer via TAC plutôt que GTAG et on verra bien si ça passe, merci pour tes retours.

**Comment by AmauriC** [comment]
Ajouter dans le footer du theme enfant:

```
<script>
jQuery(function() {
   tarteaucitron.job.push('youtube');
   tarteaucitron.job.push('issuu');
});
</script>
```

Devrait régler le problème de redemande.

Possible que ce soit juste un problème de cache ;)

**Comment by ArnaudP21** [comment]
Merci beaucoup !
