### ISSUE TITLE
Incompatibilité iframe

### ISSUE THREAD

**Issue by vincenthirtz** [AmauriC/tarteaucitron.js#806]
Bonjour,

Premièrement, le module est cool merci beaucoup. Mais en iframe il pète complètement lors de l'acceptation de tous les cookies... une idée ?

Bonne journée

**Comment by AmauriC** [comment]
Non, je ne me souviens pas d'un retour allant dans ce sens et je ne vois pas bien comment tac peux agir sur une iframe.
L'erreur js c'est quel message?

**Comment by vincenthirtz** [comment]
Bug résolu, n'étant pas lié à Tarte au citron.
Par contre dans une iframe accepter les cookies ne semble pas fonctionner, la modale repop dans tous les cas. Je pense qu'il y a un truc à creuser.
