### ISSUE TITLE
description cookies dans panneau gestion

### ISSUE THREAD

**Issue by ftrouve** [AmauriC/tarteaucitron.js#808]
bonjour,
Je cherche à afficher comme cela est fait sur le site tarteaucitreon une description sur service

comment faire ?
merci d'avance
![capture_tarte](https://user-images.githubusercontent.com/6973553/136911556-e9b1f08c-431f-4d5c-a5cb-42be72a7b120.JPG)

**Comment by ftrouve** [comment]
merci pour la réponse.
J'affine encore plus, et si je veux ajouter une phrase, par ex :

Clarity 
**Permet de mesurer la fréquentation du site**
interdit - Ce service ne dépose aucun cookie.
En savoir plus - Voir le site officiel

**Comment by AmauriC** [comment]
Hum ça peux se faire en Javascript en injectant du html mais ce n'est pas le plus simple à faire : s
