### ISSUE TITLE
Service "iframe" error: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by achterbahn** [AmauriC/tarteaucitron.js#81]
Installing the service "iframe"

- `<div class="tac_iframe" width="930" height="500" data-url="https://maps.google.ch/maps?f=[...]output=embed"> </div>`

```  //Google Maps Iframe
    var tarteaucitron_interval = setInterval(function() {
        if (typeof tarteaucitron.services.iframe.name == 'undefined') {
            return;
        }
        clearInterval(tarteaucitron_interval);
        
        tarteaucitron.services.iframe.name = 'Google Maps';
        tarteaucitron.services.iframe.uri = 'https://myuri.com/disclaimer';
        tarteaucitron.services.iframe.cookies = ['APISID','CONSENT','HSID','NID','SAPISID','SID','SIDCC','SSID'];
    }, 10);
    (tarteaucitron.job = tarteaucitron.job || []).push('iframe');
``` 

Gives me the error in the console:
`TypeError: Cannot read property 'name' of undefined`

What am I missing?

BTW: nice script! Thanks for the work.

**Comment by Nabnab9** [comment]
Hi, 

this error states that the service "iframe" is not (or not correctly added) in the tarteaucitron.services.js file.

Do you have a line like 

```
tarteaucitron.services.iframe = {
    "key": "
    "type": "api",
    "name": "iframe ",
    "uri": "http://www.dummy.com",
    "needConsent": true,
    "cookies": [],
    "js": function () {
        "use strict";
        if (tarteaucitron.user.iframe === undefined) {
            return;
        }
        tarteaucitron.addScript('//use.typekit.net/' + tarteaucitron.user.typekitId + '.js', '', function () {
            //add iframe  tag here
        });
    }
};
```

in your tarteaucitron.services.js file ?

**Comment by achterbahn** [comment]
Hi,
There is a service about iframe 
```// generic iframe
tarteaucitron.services.iframe = {
    "key": "iframe",
    "type": "other",
    "name": "Web Content",
    "uri": "",
    "needConsent": true,
    "cookies": [],
    "js": function () {
        "use strict";
        tarteaucitron.fallback(['tac_iframe'], function (x) {
            var width = x.getAttribute("width"),
                height = x.getAttribute("height"),
                url = x.getAttribute("data-url");
            
            return '<iframe src="' + url + '" width="' + width + '" height="' + height + '" frameborder="0" scrolling="no" allowtransparency allowfullscreen></iframe>';
        });
    },
    "fallback": function () {
        "use strict";
        var id = 'iframe';
        tarteaucitron.fallback(['tac_iframe'], function (elem) {
            elem.style.width = elem.getAttribute('width') + 'px';
            elem.style.height = elem.getAttribute('height') + 'px';
            return tarteaucitron.engage(id);
        });
    }
};
```
I thought this should handle all iframes as explained in the install instructions.
So I do have add a specific service for every iframe?

**Comment by Nabnab9** [comment]
Thats is why `tarteaucitron.services.iframe` is undefined :) 
I think you need to wait for the script to be fully loaded, before using one of its functions or variables.

**Comment by achterbahn** [comment]
:-)
But even when we wait for it (setting the interval to 5000 in `var tarteaucitron_interval`), the same problem occurs.
I'm over my limit with this....
Thanks for your help, anyway.

**Comment by rackberg** [comment]
Thanks for the great work!

I have the same issue, the service name of an iframe service is always "Web content" and not as configured in 
`tarteaucitron.services.iframe.name`

**Comment by malvese** [comment]
I'm also looking for a way to use TaC with Google maps embeds…
Another issue I have is that the div with class `tac_iframe` isn't *replaced* by the iframe. The iframe is created inside of it.
