### ISSUE TITLE
FacebookPixel suppression cookie

### ISSUE THREAD

**Issue by tregouetkevin** [AmauriC/tarteaucitron.js#810]
Bonjour, lorsqu'on accepte le service facebookPixel, il créé un cookie du nom de : 

`_fbq`

Ce cookie ne fait pas partie des cookies du service facebookpixel dans tarteaucitron.service.js : 

`    "cookies": ['datr', 'fr', 'reg_ext_ref', 'reg_fb_gate', 'reg_fb_ref', 'sb', 'wd', 'x-src'],`

Du coup, si l'utilisateur accepte puis refuse le service, le cookie n'est pas supprimé.

L'ajout du cookie dans cette liste fixe le probleme :

`    "cookies": ['datr', 'fr', 'reg_ext_ref', 'reg_fb_gate', 'reg_fb_ref', 'sb', 'wd', 'x-src','_fbp']"

**Comment by nd-** [comment]
Il semblerait qu'il manque également `_gcl_au` dans le service `gtag` et (peut être dans `multiplegtag` ?)
