### ISSUE TITLE
Ajouter tarteaucitronjssur WordPress sans plugin

### ISSUE THREAD

**Issue by thierrydeve** [AmauriC/tarteaucitron.js#819]
J'ai ajouté Tarteaucitron en téléchargeant directement le fichier sur le git. J'ai suivi un tuto, ils disent de placer le dossier téléchargé  à la racine du site (non du theme), ça à l'air de fonctionner. J'ai quelques questions :

- Si WordPress fait une mise à jour, vais-je perdre le dossier ? 
- Est-il bien judicieux de placer le dossier à la racine (niveau sécurité etc
- Dernière question le logo de Tarteaucitron apparait bien sur le côté de l'écran, mais comment pourrais-je avoir le bandeau qui 
-  apparait toute suite lorsque ma page est chargé ?

**Comment by samsam-rolon** [comment]
Hello,
Je profite du passage ici pour vous recommander vivement de laisser tac à la racine du site afin qu'une MAJ de thème ne le supprime pas ...
Vécu il y a peu 😢

**Comment by AmauriC** [comment]
Je compatis : D

Ne JAMAIS modifier un theme ou un plugin tiers, toujours utiliser les hooks dispo (et les demander au support si il en manque 😉).
