### ISSUE TITLE
Cloudflare bloque le fichier .fr.js

### ISSUE THREAD

**Issue by pierretux** [AmauriC/tarteaucitron.js#822]
Bonjour,

Quand on passe par cloudflare cela coupe le chemin https://static.cloudflareinsights.com/lang/tarteaucitron.fr.js?v=20210509
Une idée de comment corrigé cela ?

**Comment by pierretux** [comment]
Est ce que je peux passer au js le dossier ou il se trouve autrement ?

**Comment by pierretux** [comment]
UN retour possible ? Merci

**Comment by AmauriC** [comment]
Il faut définir `var tarteaucitronForceCDN = "https://static.cloudflare..../..chemin vers tarteaucitron";`

**Comment by pierretux** [comment]
Ok j'ai mis https://static.cloudflareinsights.com/plugins/tarteaucitron/lib/tarteaucitron/lang/tarteaucitron.fr.js mais cela bloque encore.

**Comment by AmauriC** [comment]
J'ai une erreur 502 en accédant au fichier..

Jsdelivr fonctionne bien:

https://cdn.jsdelivr.net/npm/tarteaucitronjs@1.9.5/tarteaucitron.min.js
`var tarteaucitronForceCDN = "https://cdn.jsdelivr.net/npm/tarteaucitronjs@1.9.5/";`

**Comment by pierretux** [comment]
OK trouvé en passant par mon domaine

**Comment by maximegaul** [comment]
Pour information, l'activation de l'option "Rocketloader" sur Cloudflare retarde d'exécution des scripts et donc TAC ne fonctionne plus (plus de détection des services)
