### ISSUE TITLE
Cross-Site Scripting (XSS) - DOM Based

### ISSUE THREAD

**Issue by Arkango** [AmauriC/tarteaucitron.js#823]
The library `tarteaucitron.services.js` results vulnerable to several Cross-Site Scripting (XSS) - DOM Based, because it uses the vulnerable js function innerHTML. It is suggested to filter any input received and encode (if possible) before showing it.

A sample vulnerable code is:

```
 <script type="text/javascript">
        tarteaucitron.user.xitiId = '" onload=alert(document.domain) " ';
        tarteaucitron.user.xitiMore = function () { /* add here your optionnal xiti function */ };
        (tarteaucitron.job = tarteaucitron.job || []).push('xiti');
        </script>
```

An attacker able to inject some javascript code inside the `tarteaucitron.user.xitiId` variable, will be able to run several actions on the user' behalf, like read the keystrokes, execute a screenshot, exfiltrate data. 

It is suggested to filter the input strictly as possible.

**Comment by AmauriC** [comment]
Hey
Nice suggestion but how to parse the tarteaucitron.user object each time a new value is added?
It can be a simple string or a legitimate function.

**Comment by Arkango** [comment]
Could you filter it using a regex which accept only letters and numbers?

Instead of innerHTML you can use innerText or a library to filter xss
payloads.

**Comment by AmauriC** [comment]
Not possible to filter for just alnum.

On your previous example I can put the ˋalert` on the xitiMore function.

I don't see how to filter these values. Is there is a list somewhere of common XSS word to blacklist?

**Comment by Arkango** [comment]
It is always suggested to work with whitelist, because black list could be
bypassed.

Look my suggestion is to add a filter function for each of your methods
like xitiId. And my payload was onload=alert(1) so generally speaking you
at least could remove the parenthesis square and round, graph too. Remove
dots If possible and equals.

Portswigger has a cheatsheet of xss It could be find here
https://portswigger.net/web-security/cross-site-scripting/cheat-sheet.

Usually a generic recommendation is to encode the payload, could be a
solution to you?

Available for other clarifications
