### ISSUE TITLE
matomohightrack should require consent

### ISSUE THREAD

**Issue by prudloff-insite** [AmauriC/tarteaucitron.js#828]
If I understand correctly the matomohightrack service is for people that want to ask for consent for Matomo (because the matomo service does not require consent).

However, this commit contains unrelated changes and switched `needConsent` for matomohightrack to `false` : https://github.com/AmauriC/tarteaucitron.js/commit/1c6251a70673997346bf1b89bbfcd6d54672a666
So now both services require consent.

**Comment by AmauriC** [comment]
I understand and I agree that this is not the best way to handle it but now that this service is set as "no consent", revert back to consent will break a lot of installation. It will be better to create a new service.
