### ISSUE TITLE
Liste des cookies dans mentions légales

### ISSUE THREAD

**Issue by raphaelbadia** [AmauriC/tarteaucitron.js#831]
Bonjour, 

J'ai installé tarteaucitron sur mon site depuis quelques mois et ça fonctionne à merveille, mais quelque chose me tracasse.

Je vois que quand un service installe des cookies, ils sont listés sur le site de tarteaucitron par exemple ici : https://tarteaucitron.io/fr/service/gajs/ 

Il me semble qu'il faut également lister tous les cookies posés par les trackers et expliquer leur utilité dans les mentions légales de mon site. En savez-vous plus ? C'est un on-dit et je ne suis pas certain de la nécessité de cela. 

Merci d'avance !

**Comment by AmauriC** [comment]
Bonjour,

Je ne pense pas que ce soit indispensable mais si vous voulez vous pouvez le faire directement sur votre page, ce n'est pas le but de tarteaucitron de s'occuper de ça ; )
