### ISSUE TITLE
Comptes multiples Google Ads ou Facebook ?

### ISSUE THREAD

**Issue by eficiens-eric** [AmauriC/tarteaucitron.js#832]
Bonjour,
J'essaie de charger 2 comptes différents pour des pixels de reciblages Ads (et pareil sur Facebook)
Sauf qu'un seul est chargé
Je me demande si c'est lié au fait qu'on n'a qu'une seule variable adwordsremarketingId et que TauC prend la dernière ?
Pour être complet, les services sont chargés via Tag Manager, balises HTML qui reprennent le script proposé par Tarte au Citron.
![image](https://user-images.githubusercontent.com/81694039/143549072-b6d1aa90-a4cf-4a3b-bf37-2b223c43a5f6.png)

**Comment by AmauriC** [comment]
Pas de bonne nouvelle, ce n'est pas géré de pouvoir charger plusieurs fois le même service avec un id différent : /

**Comment by eficiens-eric** [comment]
Merci Amaury pour cette réponse rapide.
J'imagine qu'une solution de contournement serait de re-créer le service avec un nom différent, par ex. 'googleadwordsremarketing2' et dans ce cas je peux ajouter une 2e instance, etc…

**Comment by AmauriC** [comment]
Oui, ça fonctionnera ; )
