### ISSUE TITLE
Bouton de partage linkedin - Transmission de la configuration

### ISSUE THREAD

**Issue by lucmuller** [AmauriC/tarteaucitron.js#835]
Dans le bouton de partage de linkedin, il est est possible d'ajouter des paramètres, notamment pour configurer la langue d'affichage du bouton.

https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/plugins/share-plugin

Cela permet notamment de transmettre la clé d'API :
`api_key: XXXXXXXX
onLoad: onLinkedInLoad
authorize: false
lang: fr_FR`

Je ne crois pas trouver de méthode dans le service linkedin pour transmettre ces paramètres. Dans ma page, lorsque le script se charge après l'autorisation dans TAC, le texte du bouton s'affiche en anglais.

Y aurait-il une solution que j'aurai raté ou n'est pas implémenté actuellement ?
Est-il possible d'ajouter une variable pour transmettre du contenu dans la balise script ajoutée par la fonction addScript ?

**Comment by lucmuller** [comment]
Il semble possible de passer les paramètres à travers des paramètres GET dans au script de linkedin.

Je suis en train de modifier le services pour pouvoir passer les paramètres (dont j'ai besoin).

`var linkedInScriptUrl = '//platform.linkedin.com/in.js';
        var params = [];
        tarteaucitron.fallback(['tacLinkedin'], '');
        if(tarteaucitron.user.linkedinApiKey){
            params.push('api_key='+tarteaucitron.user.linkedinApiKey);
        }
        if(tarteaucitron.user.linkedinOnLoad){
            params.push('onLoad='+tarteaucitron.user.linkedinOnLoad);
        }
        if(tarteaucitron.user.linkedinAuthorize){
            params.push('authorize='+tarteaucitron.user.linkedinAuthorize);
        }
        if(tarteaucitron.user.linkedinLang){
            params.push('lang='+tarteaucitron.user.linkedinLang);
        }
        if(params.length > 0){
            linkedInScriptUrl = linkedInScriptUrl + '?'+params.join('&');
        }
        tarteaucitron.addScript(linkedInScriptUrl);
        if (tarteaucitron.isAjax === true) {
            if (typeof IN !== "undefined") {
                IN.parse();
            }
        }`

Je ne peux cependant pas, pour l'instant, confirmer que cela fonctionne avec la clé d'API, car je dois pousser en prod pour valider.
De plus, je ne suis pas sur de l'exhaustivité des paramètres possibles.
Je n'ai pour l'instant ajouté que :
tarteaucitron.user.linkedinApiKey = 'XXXXXXX';
tarteaucitron.user.linkedinOnLoad = 'onLinkedInLoad';
tarteaucitron.user.linkedinAuthorize = false;
tarteaucitron.user.linkedinLang = 'fr_FR';

Y aurait-il une autre manière plus efficace de passer une multitude de paramètres et de les ajouter en paramètres GET à l'url du script ajouté ?

**Comment by AmauriC** [comment]
Peut-être en reprenant le système de Youtube pour les paramètres?
https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.services.js#L3534
