### ISSUE TITLE
Service pour plugins smashballoon (twitter, intagram...)

### ISSUE THREAD

**Issue by florent-cdl** [AmauriC/tarteaucitron.js#836]
Bonjour,
Comment puis-je ajouter un service sur la version pro pour bloquer l'affichage du plugin smashballoon qui permet d'afficher un flux twitter ? 

Merci
Florent

**Comment by AmauriC** [comment]
Il me faut le marqueur HTML de smashballoon pour voir si il est possible de l'intégrer à tarteaucitron ; )

**Comment by florent-cdl** [comment]
Bonsoir,

Merci pour votre réponse.

Le plugin est utilisé sur cette page
https://www.afg.asso.fr/ <https://www.afg.asso.fr/>

L’affichage se fait en bas de page, section « suivez-nous »

Merci
Florent Jouet
-------------------------------------------------



Florent JOUET
CARRE DE LUNE
http://www.carredelune.com
Port : 06 76 69 99 48
Fixe : 09 72 28 59 75
Skype : florent-j

**Comment by AmauriC** [comment]
Merci mais il me faut juste le marqueur HTML/Javascript du service, ce que smashballon vous demande d'installer sur le site.
