### ISSUE TITLE
Alert modal refresh a chaque changement de page

### ISSUE THREAD

**Issue by Marin-Fa** [AmauriC/tarteaucitron.js#837]
Bonjour,

J'utilise cette lib sur plusieurs de mes sites.
Or sur l'un d'entre eux, la modale d'alerte pour accepter ou refuser les cookies réapparaît a chaque changement de page, même si acceptés une première fois.
Uniquement sur chrome.
Test de del le cache effectué mais non concluant.

Auriez-vous une idée ? 

Merci

**Comment by AmauriC** [comment]
Généralement c'est une erreur de configuration au niveau du `cookieDomain`.

Avec l'url du site je pourrai confirmer ; )

**Comment by Marin-Fa** [comment]
https://monespace.terreal.com/

Merci :D

**Comment by AmauriC** [comment]
Je viens de tester et tout fonctionne bien. Peut-être juste un soucis de cache?

**Comment by Marin-Fa** [comment]
Oui j'ai changé mon script par celui ci : https://tarteaucitron.io/en/service/gajs/

Lorsqu'un utilisateur est connecté et a accepté les cookies, c'est bon.
Par contre il est obligé de les revalider a chaque nouvelle connexion, une idée ?

Merci et belle journée :)

**Comment by AmauriC** [comment]
Ce ne serait pas alors une extension de navigateur qui purge les cookies à la fermeture?
Je viens de retourner sur le site et mon consentement d'hier est toujours valide.

**Comment by Marin-Fa** [comment]
C'était bien ça. 
Merci et belle fin de journée ;)
