### ISSUE TITLE
Buttons have to be in the same color

### ISSUE THREAD

**Issue by Cruiser13** [AmauriC/tarteaucitron.js#839]
The TTDSG in germany does force us to change the primary colors of the buttons to be all in the same color.
The "Allow" button has a green background in tarteaucitron.js sourcecode at the moment.

But I've seen that the website https://tarteaucitron.io has some extra css rules to color all buttons in white:
```
tarteaucitronAllow {
 background-color:#ffffff!important
}
...
```

I wonder if this is a config or if we should change the sourcecode to comply at this point?

I'm aware that I could override this in my own css but I wondered if there is a global solution planned yet.

**Comment by AmauriC** [comment]
Colors are not (yet?) managed by a setting, this is all on CSS.
I know this can be improved because there is different classes but currently the best way to make all the button identical is to use this CSS rule:
```
html body #tarteaucitronRoot #tarteaucitron .tarteaucitronAllow, html body #tarteaucitronRoot #tarteaucitron .tarteaucitronDeny,
html body #tarteaucitronRoot #tarteaucitronAlertBig .tarteaucitronAllow, html body #tarteaucitronRoot #tarteaucitronAlertBig .tarteaucitronDeny, html body #tarteaucitronRoot #tarteaucitronAlertBig #tarteaucitronCloseAlert {
    background: black!important;
    color: white!important;
}
```
