### ISSUE TITLE
Bandeau des cookies qui s'affiche 2 fois

### ISSUE THREAD

**Issue by ArnaudP21** [AmauriC/tarteaucitron.js#840]
Bonjour @AmauriC,

J'ai un souci sur mes sites (https://www.liberon.fr/ et http://liberon.be/ notamment), le bandeau cookies doit être accepté 2 fois pour ne pas apparaître.

Sachant que j'ai fais appel à toi récemment sur ce ticket : https://github.com/AmauriC/tarteaucitron.js/issues/805 où tu m'as donné un développement et que j'utilise WP Rocket dans lequel j'ai exclu le load.js

Aurais-tu une solution pour résoudre le problème stp ?

Cordialement,

**Comment by AmauriC** [comment]
Hello

Le fichier tarteaucitron est correctement chargé et, j'ai testé en autorisant/refusant tout et en naviguant sur le site, le bandeau ne réapparaît pas.

Tu arrives à reproduire le problème ?

**Comment by ArnaudP21** [comment]
Oui, généralement sur mobile. Sur desktop, c'est assez sporadique mais sur mobile c'est quasi systématique (testé à l'instant sur safari/chrome sur IOS).

**Comment by AmauriC** [comment]
C'est peut-être ce que tu as à la fin du site dans `jQuery(function(){});` pour ajouter youtube et insuu.
Essai en le retirant pour confirmer et si c'est bien ça, retirer le jQuery, ne laisse que le tarteaucitron.job.push.

**Comment by ArnaudP21** [comment]
Malheureusement cela ne change rien. J'ai retiré le script.

**Comment by AmauriC** [comment]
J'ai refait des tests mais je n'arrive toujours pas à reproduire le problème : /

**Comment by ArnaudP21** [comment]
Bonjour @AmauriC,

Meilleurs voeux pour 2022.

Est-ce qu'il est possible que cela soit lié au CDN (cloudflare) ?

Cdlt,

**Comment by AmauriC** [comment]
Bonne année! 😃

C'est peu probable. Je viens de retester et je n'arrive toujours pas à reproduire : /
En allant sur le site depuis un iphone/chrome, j'accepte tout, recharge la page, le bandeau ne réapparait pas.

**Comment by ArnaudP21** [comment]
Bonjour @AmauriC,

Je viens de tester à nouveau et je pense que c'était bien le petit développement qui avait été ajouté car aujourd'hui je n'ai plus le problème.
