### ISSUE TITLE
translation improvements - greek

### ISSUE THREAD

**Issue by robertodavico** [AmauriC/tarteaucitron.js#845]
Dear

we used this nice library and we notice that the Greek translator has made some serious spelling mistakes. Can we correct them? They are for the screenshot that you see attached.
Concretely

Replace the word "Επέτρεψε" with "Επίτρεψε"

Plus some content which is not translated...

thanks for taking care

![2021-12-23_greek1](https://user-images.githubusercontent.com/69516490/147247523-116fc2dd-a04a-4006-9043-a038b23d6489.png)

**Comment by AmauriC** [comment]
Thanks for the feedback.

If you can translate https://github.com/AmauriC/tarteaucitron.js/blob/master/lang/tarteaucitron.el.js I'll be happy to update the translation : )

**Comment by robertodavico** [comment]
Hello Amauri

I forwarded your tip to the native Greek colleague who will take care of put the correct translations as suggested.

Thanks for the quick reaction, I take advantage to wish you a Merry Christmas form the KNX Association team.

R.

**Comment by valourakos** [comment]
Hello Amauri,
I have just updated it!

Thanks for taking care!
Vassilios

Joyeux Noël! ;)
