### ISSUE TITLE
Step by step documentation for setting up an iframe that loads third party cookies

### ISSUE THREAD

**Issue by hilyin** [AmauriC/tarteaucitron.js#846]
Hi,

I am having difficulty finding documentation on how to handle an iframe with tarteaucitron that loads third party cookies.

Is there documentation for this, if so, can you please point me to the correct location?

Thank you.

**Comment by AmauriC** [comment]
Hey
This is not a service I can add as a real service for everyone?
There is no support for an iframe not associated with a service.

**Comment by lucmuller** [comment]
@hilyin : Shouldn't you simply use the _iframe_ service ?

See first service of : https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.services.js

Obviously it's not documented on tarteaucitron.io.

Once the service is activated you can load you iframe with

`<div class="tac_iframe" data-src="http://url-of-iframe" width="your-width" height="your-height"></div>`

This will encapsulate any iframe in TAC.

**Comment by hilyin** [comment]
Thank you, I appreciate the responses. I was not aware of that functionality due to lack of documentation, but this all make sense now.
