### ISSUE TITLE
Clarify cookies

### ISSUE THREAD

**Issue by loicy** [AmauriC/tarteaucitron.js#847]
Bonjour,

Nous venons de mettre en place Clarify. Lors de notre test, les cookies sont activés chez Microsoft de même que le site mais le service indique aucun cookies.

Je vois que le site de tarteaucitron a la même chose.

![Screenshot_234](https://user-images.githubusercontent.com/36493474/147605648-1da22f7a-f382-4416-b3d5-d764358c6b51.png)

**Comment by AmauriC** [comment]
C'est un cookie créé sur le domaine de clarity. C'est impossible à manipuler, c'est pour ça que l'accord est demandé à l'internaute.

Ce message à propos des cookies n'est pas clair et devrait prochainement disparaître 🙃

**Comment by loicy** [comment]
Merci du retour rapide !

Ok c'est plus clair maintenant.

Merci bcp.
