### ISSUE TITLE
Site multilingue - WPML

### ISSUE THREAD

**Issue by deborahscz** [AmauriC/tarteaucitron.js#849]
Bonjour,

J'ai un site décliné en 3 langues (français, allemand, anglais)

Lorsque j'installe en manuel à la racine de mon site, TAC fonctionne très bien mais uniquement sur le site en français qui est monsite.fr

J'aimerais qu'un bandeau apparaisse également sur monsite.fr/de/ et monsite.fr/en/

Avec le plugin cela fonctionne donc je ne comprends pas trop ce qui manque ?

Merci d'avance

Déborah

**Comment by AmauriC** [comment]
👋
Sur /de/ ke script tarteaucitron est bien présent?
Possible d'avoir l'url?
