### ISSUE TITLE
Ads personalization settings (GDPR/RGPD) in Google DFP (Doubleclick For Publisher) and Adsense Auto ads Fallback - Discussion

### ISSUE THREAD

**Issue by eldk** [AmauriC/tarteaucitron.js#85]
Bonjour,

Quelques informations importantes : 

https://support.google.com/adsense/answer/7670312

- Ajout d'une fonctionnalité pour permettre au visiteur d'activer ou pas la publicité personnalisée sur un site (DFP et Adsense)
- Dans les 2 cas, un cookie est nécessaire.

1 - Pas de cookie = pas de publicité (pour DFP : googletag.pubads().setCookieOptions(1))
2 - Cookie autorisé + publicité contextuelle (pour DFP : googletag.pubads().setRequestNonPersonalizedAds(1))
3 - Cookie autorisé + publicité personnalisée

Pour ma part, j'utilise le 1 (et DFP) depuis 1 an avec tarteaucitron. Cet aspect n'est pas mentionner dans la doc Google.

Je vais tester 1 + 2 + 3 dans les prochaines semaines.

Certains ont-ils déjà travaillé la question ?

Cordialement,

Eric

**Comment by sebastienheyd** [comment]
Avec la RGPD, d'après Google on n'a pas besoin du consentement pour appeler le script si on a bien configuré sa régie (du moins j'ai lu ça ici : https://www.arobasenet.com/2018/05/google-adsense-pour-RGPD-4681.html). Cependant il faut que l'internaute puisse choisir si ces données sont envoyées ou pas, ne sachant pas vraiment comment le faire je détourne TaC.

Je n'utilise pas GPT, mais j'ai écris un service pour dire si oui ou non les publicités sont personnalisées : 

```javascript
// google adsense
tarteaucitron.services.adsensergpd= {
    "key": "adsensergpd",
    "type": "ads",
    "name": "Google Adsense",
    "uri": "http://www.google.com/ads/preferences/",
    "needConsent": true,
    "cookies": [],
    "js": function () {
        "use strict";
        tarteaucitron.addScript('https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js', '', function() {
            (adsbygoogle=window.adsbygoogle||[]).requestNonPersonalizedAds=0
        });
    },
    "fallback": function () {
        "use strict";
        var id = 'adsensergpd';
        tarteaucitron.addScript('https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js', '', function () {
            (adsbygoogle=window.adsbygoogle||[]).requestNonPersonalizedAds=1
        });
    }
};
```

Il suffit ensuite d'appeler le job : 
```javascript
(tarteaucitron.job = tarteaucitron.job || []).push('adsensergpd');
```

Attention à bien retirer tous les appels à `https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js` dans vos pages...

Dans tous les cas `adsbygoogle.js` est appelé, si l'internaute à donné son accord google va utiliser les données personnelles pour afficher les publicités ciblées... sinon c'est des publicités "contextuelles"...

Je ne sais pas si c'est vraiment ça qui est attendu par contre... à vérifier !

**Comment by sebastienheyd** [comment]
A noter que pour le moment (avant le 25 mai) il n'y a aucun effet, toujours selon la doc Google : 

> The following functionality won't take effect until May 25, 2018. These APIs may not cause non-personalized ads to serve until May 25, 2018

**Comment by eldk** [comment]
Bonsoir,

C'est presque fait (DFP + Fallback sur Adsense Auto Ads). C'est en test sur un site.

![screenshot-engage-tarteaucitron](https://user-images.githubusercontent.com/11083657/40748710-9b44e8f0-6461-11e8-818a-062e5b560c45.png)

Plus d'info demain.

Cordialement,

Eric

**Comment by eldk** [comment]
Bonjour,

DFP et fallback sur Adsense Auto Ads : 

```
<!--DFP -->
<script async ='async' src='https://www.googletagservices.com/tag/js/gpt.js'></script>
<script>
  var googletag = googletag || {};
  googletag.cmd = googletag.cmd || [];
</script>
	<script>
        googletag.cmd.push(function () {
            var regex = new RegExp("!googlepublishertag=true", "g");
            if (!regex.test(tarteaucitron.cookie.read())) {
                googletag.pubads().setCookieOptions(1);
            } else {
                var regexAdsType = new RegExp("!requestNonPersonalizedAds=true", "g");
                if (regexAdsType.test(tarteaucitron.cookie.read())) {
                    console.log('setRequestNonPersonalizedAds :' + 'true');
                    googletag.pubads().setRequestNonPersonalizedAds(1);
				}
			}
            googletag.defineSlot('/slotnumber/d250x300', [300, 250], 'div-gpt-ad-1496605106020-0').addService(googletag.pubads());
            googletag.defineSlot('/slotnumber/b768', [728, 90], 'div-gpt-ad-1496605106020-3').addService(googletag.pubads());
            googletag.pubads().enableSingleRequest();
            googletag.enableServices();
        });
	</script>
```

**Comment by eldk** [comment]
Il reste à gérer le clic sur le bouton "tout accepter" : pour le moment, en cas de clic, seul "!googlepublishertag=true" est inséré dans le cookie tarteaucitron : "!requestNonPersonalisedAds" étant absent, c'est la publicité contextuelle qui s'affiche.

Le visiteur doit pouvoir choisir par ce biais également.

**Comment by eldk** [comment]
Bandeau avec choix entre la publicité personnalisé ou non personnalisée : 

![bandeau-alerte-tarteaucitron-tarteaucitronalertbig](https://user-images.githubusercontent.com/11083657/41111679-f8415b94-6a7c-11e8-9946-d30ddfb2b894.png)

**Comment by eldk** [comment]
Fenêtre de gestion des paramètres : 

![parametres-tarteaucitron-profilage](https://user-images.githubusercontent.com/11083657/41114700-7711e166-6a85-11e8-906d-a93186a627e2.png)

**Comment by eldk** [comment]
![parametres-tarteaucitron-profilage-jepersonnalise2](https://user-images.githubusercontent.com/11083657/41169129-484a26c2-6b48-11e8-881f-a5772acdb6ea.png)
