### ISSUE TITLE
Matomo cloud integration

### ISSUE THREAD

**Issue by tflorac** [AmauriC/tarteaucitron.js#851]
Hi,
I'm trying to include Matomo Cloud with TarteAuCitron.
The problem is that, when using `matomo` service, TarteAuCitron is referencing a `piwik.php` script, which is matching the previous name of Matomo, instead of `matomo.php`.
Should we just change `piwik.php` to `matomo.php`, or should we add a new `matomo-cloud` service?
I can create the pull request...
Best regards,
Thierry

**Comment by AmauriC** [comment]
👋
A new "Matomo Cloud" service will be perfect ; )
