### ISSUE TITLE
Personnalisation du look (CSS) de tarteaucitron

### ISSUE THREAD

**Issue by JulieJAP** [AmauriC/tarteaucitron.js#856]
Bonjour @AmauriC ,
Tout d'abord un grand merci pour ce superbe outil ! 
Je ne suis pas très technique et j'ai tout de même réussi à l'installer sur mon site, ce dont je ne reviens toujours pas 😅
Malheureusement, je n'arrive pas à personnaliser le look de tarteaucitron pour qu'il se fonde dans la charte graphique de mon site et ne sais plus trop comment progresser.
Un peu de contexte : 
Installation sur wordpress avec jsdelivr dans le <head> du site
Version tarteaucitron 1.9.5 (la dernière 😊)
J'ai fait l'installation avec "useExternalCss" à false et le look par défaut le temps de vérifier que tout se passe bien en terme de gestion des cookies.
Je suis ensuite passée à "useExternalCss" à true pour pouvoir ajuster le look à ma charte graphique.
Comment j'ai fait ? J'ai téléchargé le CSS de la version 1.9.5 sur Github, je l'ai mis "à mes couleurs" et je l'ai copié-collé dans le CSS personnalisé de mon thème. J'ai lu que certaines personnes avait procédé comme ça avec succès. Au-delà d'ajuster le look de tarteaucitron à leur thème enfant Wordpress, cela leur permet de profiter de leur plugin de cache et de la minification, ce qui est top.
Bon ben en ce qui me concerne c'est un échec total. 💥
Tous les éléments de tarteaucitron apparaissent en vrac au pied de mes pages Wordpress, sans aucune mise en forme.
C'est comme si il ne voyait pas du tout la mise en forme CSS que j'ai collée dans le thème enfant.
J'ai essayé 10 000 trucs, mais là, j'avoue, je donne ma langue au chat 🐈
Une idée ?
Un grand merci par avance pour ton aide !
Julie.

**Comment by AmauriC** [comment]
Bonjour Julie, 

Tout semble ok au niveau de la configuration 👍

Si le CSS du thème n'est pas appliqué, c'est probablement un problème de cache. Il a été vidé? 

Possible d'avoir l'URL du site?

**Comment by JulieJAP** [comment]
Dans la même ligne d'idée, j'ai vu que tu avais créé un codepen il y a quelques temps pour pousser encore plus loin les possibilités de personnalisation du look de tarteaucitron. Je trouve cette idée géniale et je me demandais si tu avais mis à jour ce codepen quelque part pour la version 1.9.5. En effet, il semble que ce codepen soit lié à une ancienne version de tarteaucitron car lorsque je compare le CSS de la 1.9.5 avec le code du codepen, je ne m'y retrouve pas du tout.

Cela serait vraiment génial de pouvoir disposer de ce codepen pour la 1.9.5. Il suffirait alors de choisir le look que l'on veut dessus et le copier-coller dans le CSS de son thème enfant avec "useExternalCss" à true pour avoir une solution visuellement au top de ce que l'on cherche. Mais ça ne marche malheureusement pas chez moi 😔

**Comment by JulieJAP** [comment]
Coucou Amauri ,
Merci pour ta réponse rapide ! 🚀
Oui, je désactive bien le cache quand je fais les ajustement sur le site, puis je le réactive quand je suis satisfaite.
URL du site : https://www.atlantid.net/

**Comment by AmauriC** [comment]
Actuellement je vois le CSS classique de tarteaucitron.

Dans le CSS du theme il y a bien une section "tarteaucitron" mais elle est vide : /
https://www.atlantid.net/wp-content/themes/DiviChild2021/style.css?ver=4.14.4

J'ai refait un codepen ; )
https://codepen.io/AmauriC/pen/NWazdbM

**Comment by JulieJAP** [comment]
Euh, oui, c'est pas bête ça ! J'étais tellement stressée de laisser un site cassé aux yeux de la terre entière que j'ai remis "useExternalCss" à false 😅

Je l'ai rebasculé à true et si tu vas sur le site, tu vas voir le problème 💥

**Comment by AmauriC** [comment]
Ou est censé être le css custom? Dans le fichier cité plus haut? Si oui, tout en bas, il y a un commentaire "tarteaucitron" mais aucune règle :/

**Comment by JulieJAP** [comment]
Génial pour le codepen ! Je garde précieusement le lien et je vais apprendre à m'en servir. 💖🥂

**Comment by JulieJAP** [comment]
> Ou est censé être le css custom? Dans le fichier cité plus haut? Si oui, tout en bas, il y a un commentaire "tarteaucitron" mais aucune règle :/

Il est dans le style.css de mon thème enfant.. 
Je suis passé par Editeur de thème > style.css et j'ai copié collé le CSS de tarteaucitron dans sa petite section dédiée après les autres personnalisations du thème enfant.

**Comment by JulieJAP** [comment]
![Divi child](https://user-images.githubusercontent.com/97164592/148211249-cfd14f3e-8499-41f5-ab3f-439fda7b133f.jpg)

**Comment by JulieJAP** [comment]
> Ou est censé être le css custom? Dans le fichier cité plus haut? Si oui, tout en bas, il y a un commentaire "tarteaucitron" mais aucune règle :/

Incompréhensible... Je creuse...

**Comment by JulieJAP** [comment]
VICTOIRE ! 🥂🏆

Un immense merci pour ton aide Amauri. Je n'aurais jamais réussi à débloquer le problème toute seule si tu ne m'avais pas pointée dans la bonne direction !

Je mets la réponse ci-dessous pour mémoire, car elle n'est pas intuitive et spécifique au thème DIVI. Peut-être cette réponse servira-t-elle à d'autres personnes qui rencontreront le même problème que moi ? 😊

Il y a une option dans DIVI que l'on peut activer dans l'onglet performance (options du thème)  et qui s'appelle "Critical CSS" dont voici la définition :

"Critical CSS greatly improves website load times and Google PageSpeed scores by deferring non-critical styles and eliminating render-blocking CSS requests."

Bon ben il semble que cette petite option suffise à mettre le bazar. 😅

Ne me demande pas pourquoi, je ne suis pas assez technique pour ça, mais il semble que le CSS que j'avais ajouté pour tarteaucitron n'était pas jugé critique et mon style.css était sans cesse amputé du code correspondant.

Une fois que je l'ai désactivée, tout a commencé à fonctionner.

Je vais pouvoir commencer à jouer avec le style de tarteaucitron après le déjeuner !! 💖

Superbe journée à toi ! ✨

**Comment by AmauriC** [comment]
Super! Merci pour le retour d'expérience qui aidera surement d'autres utilisateurs 💪

Bonne personnalisation ! 😁
