### ISSUE TITLE
How to push a job in disabled state

### ISSUE THREAD

**Issue by loxK** [AmauriC/tarteaucitron.js#858]
Is there a way to push a service as disabled by default?

Doing this:

```html
<script type="text/javascript">
        (tarteaucitron.job = tarteaucitron.job || []).push('twitter');
</script>
```
pushes it in a "no choice made" state and triggers the popup. I want it to be disabled by default, visitors enabling on demand when a twitter widget should be shown.

**Comment by AmauriC** [comment]
Hey
Your commit looks good, you can push it here if tested and validated on your side ;-)
