### ISSUE TITLE
What is .user.recaptchaapi = 'XXXXX' ?

### ISSUE THREAD

**Issue by titou26140** [AmauriC/tarteaucitron.js#859]
Hello,
I'm trying to use your script with RECaptcha V2 or v3.
But I have to enter the params : user.recaptchaapi.

I don't really know what this parameter refers.
Because when I add a new projet in the Google ReCaptcha admin I only get secretKey and siteKey.

Could you explain to me what I need to write here?

Thank you in advance.

**Comment by AmauriC** [comment]
Try with the siteKey (never use or share the secret) ; )
