### ISSUE TITLE
Random Misses 404

### ISSUE THREAD

**Issue by shirokoweb** [AmauriC/tarteaucitron.js#86]
Hi,

Noticed on page refreshes the script is randomly acting wierd :

> Failed to load resource: the server responded with a status of 404 () /css/tarteaucitron.css?v=323:1
> Failed to load resource: the server responded with a status of 404 () /lang/tarteaucitron.fr.js?v=323:1

It requests wrong URL path.

rgds

**Comment by fsoabsix** [comment]
Hi, i have the same problem...
