### ISSUE TITLE
Possibilité de faire apparaître le bandeau des cookies même si uniquement cookies fonctionnels?

### ISSUE THREAD

**Issue by JulieJAP** [AmauriC/tarteaucitron.js#865]
Bonjour Amauri, 

J'espère que tu vas bien !

Suite à toute la polémique autour de Google Analytics et après mûre réflexion, j'ai fini par enlever le code Google Analytics de mon site vitrine sous Wordpress.

J'ai aussi changé le message du bandeau Tarte Au Citron pour mentionner : "Ce site n'utilise que des cookies fonctionnels" avec un bouton OK et le lien vers la politique de confidentialité.

Le problème, c'est qu'à partir du moment où j'ai enlevé le service Google Analytics le bandeau cookies n'apparaît plus. 

Cela paraît logique, mais en même temps, il est important de le faire apparaître pour prévenir les internautes.

Y-a-t-il un moyen ou une commande à placer dans le code pour faire apparaître le bandeau (et éventuellement le petit widget de gestion des services) même dans le cas où l'on n'a que des cookies fonctionnels?

Un grand merci pour ta réponse et bon week-end à toi !

**Comment by AmauriC** [comment]
Bonjour Julie : )

Si tarteaucitron n'a rien à faire, le bandeau ne s'affiche pas et il n'y a aucune obligation de le faire.
Les cookies fonctionnels n'ont pas besoin d'être présentés à l'utilisateur.

Profites du fait que sur ce site l'utilisateur ne sera pas ennuyé par un bandeau 👍

**Comment by JulieJAP** [comment]
Bonjour Amauri : )

Un grand merci pour ta réponse !

On s'est tellement habitués à voir des bandeaux de cookies partout maintenant, même lorsque le site n'utilise que des cookies fonctionnels, que j'en étais venue à croire que c'était une obligation légale... 😅

Mais si ce n'en est pas une, oui, c'est bien mieux comme ça, car à la longue tous ces bandeaux de cookies ont un côté vraiment repoussoir... surtout quand l'auteur du site rend l'optin / optout des cookies difficilement lisible et compliqué, ce qui donne l'impression (qui n'est pas qu'une impression) de se faire forcer la main.

C'est ce que j'aime beaucoup avec ta solution. Tout est clair, lisible et facile à paramétrer pour le visiteur ! 👍

Superbe dimanche à toi !

**Comment by AmauriC** [comment]
Merci Julie ! Excellent dimanche 😀
