### ISSUE TITLE
Travail sur l'Accessibilité de Tarteaucirton

### ISSUE THREAD

**Issue by EmmanuelDemey** [AmauriC/tarteaucitron.js#868]
Une petite issue pour vous indiquer que je suis disponible pour travailler sur l'accessibilité de votre projet. 
Je viens d'auditer le site d'un client, et nous avons remarquer quelques soucis. 

Avez-vous déjà travailler sur ces problématiques ? Notamment la compatibilité RGAA ?

**Comment by AmauriC** [comment]
Super Emmanuel 🙂

Tac est normalement ok (ou presque ok) avec le premier niveau RGAA.
Il est possible de faire bien mieux, je serai là pour aider si besoin. :)

**Comment by EmmanuelDemey** [comment]
Je ne connais pas encore très bien le produit. Je pose donc les questions d'abord :)

- préconisez.vous une façon de rendre le bouton de gestion des cookies rapidement accessible au clavier ? Car a l'heure actuelle, en tout cas chez mon client, nous sommes obligés de traverser l'ensemble de la page avec le clavier avant d'atteindre ce fameux bouton. 

- il y a t'il une configuration pour insérer l'attribut Lang sur la modale afin d'indiquer la langue utilisée ? Mon navigateur étant en anglais, le site de mon client en français, le changement de langue n'a pas été pris en compte par le synthétiseur vocal.

**Comment by AmauriC** [comment]
- C'est intéressant, quel est la bonne pratique? 
Il y a cette option https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.js#L523 pour mettre le panel en haut. Peut-être que c'est suffisant?

- C'est assez facile à faire. Il suffit d'ajouter lang="en" dans la div principale de tarteaucitron?

**Comment by EmmanuelDemey** [comment]
Pour la langue, ne serait-il pas intéressant de le mettre par défaut en fonction de la langue sélectionnée ?
https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.js#L1792

Pour le premier problème, ta solution permettra de résoudre que lorsque le bouton est en haut. Mais cela n'interdit pas aux utilisateurs de garder le bouton en bas. 
Pourquoi, si le bouton est en bas, ajouter un lien d'échappement qui sera utilisé que par les utilisateurs navigant avec le clavier ? https://css-tricks.com/how-to-create-a-skip-to-content-link/

**Comment by AmauriC** [comment]
Ajouter un attribut `<div id="tarteaucitronRoot" lang="' + tarteaucitron.getLanguage() + '">` règle le problème pour les synthétiseurs ? Si oui je m'en occupe : )

Ok pour la navigation vers le bandeau, je vais regarder tout ça en détails.

**Comment by nicozerr** [comment]
Bonjour,

Logiquement, l'attribut `lang` devrait se trouver sur la balise `<html>` de vos pages web (au pire du pire, sur une balise parent du plus haut niveau possible, genre `<body>`). La définition de la langue par défaut est d'ailleurs une obligation au regard du RGAA.
Lorsque le bandeau de TAC s'insère dans le code, il est inséré soit à l'ouverture de la balise `<body>`, soit avant sa fermeture (option `bodyPosition`). Si l'attribut `lang` est défini sur une des balises parent, alors la langue par défaut de TAC sera celle de votre page.

Après, j'utilise NVDA sur mon navigateur français, avec windows en français. Lorsque, sur un site français, un changement de langue est opéré sur un mot anglais (lang="en"), malheureusement NVDA ne change prend pas d'accent ou de considère pas le changement de langue. Peut-être un problème de paramétrage, je ne sais pas.

@EmmanuelDemey lorsque vous dites "_Mon navigateur étant en anglais, le site de mon client en français, le changement de langue n'a pas été pris en compte par le synthétiseur vocal._", comment votre synthèse vocale lit le reste de la page ? Quelle langue est utilisée par TAC ?

**Comment by AmauriC** [comment]
Merci pour ces détails.

Du coup la bonne pratique serait d'utiliser l'attribut lang de la page si il existe plutôt que d'utiliser la langue du navigateur (qui dans le cas d'op est différente de celle du site et fait un mix fr-en).

**Comment by EmmanuelDemey** [comment]
Par exemple, si nous prenons le code suivant, que je viens de tester : 

```
<!DOCTYPE html>
<html lang="fr">
<body>
<button>Bonjour</button>
	<button lang="en">How are you ?</button>
</body>
</html>
```

Avec mon VoiceOver configuré avec deux langues sur Mac, il y a un changement de voix utilisée. FR pour le premier bouton, et EN pour le deuxième. 

L'attribut lang peut se mettre sur n'importe quelle balise HTML. Cf le critère 8.7 du RGAA : https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode-rgaa/criteres/

**Comment by nicozerr** [comment]
Le code présenté par @EmmanuelDemey est exactement ce qu'il faut faire lorsqu'une page dans une langue par défaut contient un élément dans une autre langue, d'un point de vue HTML et accessibilité (et peut-être même SEO)... Cela vaut aussi lorsque l'on utilise un anglicisme qui n'existe pas dans le [dictionnaire de l'académie française](http://www.dictionnaire-academie.fr/), comme "workflow", "low-cost", "toaster".

Si je comprends bien ce que la [fonction `getLanguage` de TAC](https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.js#L1778) semble indiquer, le choix du fichier de langue pour TAC est déterminé par la langue du navigateur (`navigator.language || navigator.browserLanguage || navigator.userLang`) ou de l'OS (`navigator.systemLanguage`), ou sinon elle est forcée avec l'option `tarteaucitronForceLanguage`.

Selon moi, le choix du fichier de langue de TAC et la valeur de l'attribut `lang` doit plutôt être conditionné de la manière suivante :
1. Par défaut, TAC doit utiliser la langue de la page, comme définie sur la balise `<html>` de la page. Dans ce cas, il n'y a même pas besoin d'attribut `lang` sur le bandeau et la modale de TAC.
2. Ensuite, si cette langue n'est pas définie, l'option `tarteaucitronForceLanguage` peut être utilisée. Il s'agit là en fait d'une solution de contournement puisque l'absence de langue par défaut sur une page constitue une erreur HTML et d'accessibilité.
3. Puis, si aucune langue n'est définie ni sur la page ni dans TAC, on peut envisager que TAC utilise la langue du navigateur ou du système pour son fichier de langue et l'attribut `lang`.
4. Et enfin, si aucune des précédentes options ne fonctionne, TAC pourrait utiliser l'anglais par défaut.

Votre avis ?

**Comment by AmauriC** [comment]
Pour l'ordre de détection je propose:

1. la variable `tarteaucitronForceLanguage`
2. l'attribut `lang` de la balise `html`
3. la langue par défaut du navigateur / os
4. Anglais (en)

Dans les cas 1-3-4, ajouter un attribut `lang` sur la div tarteaucitron pour les synthétiseurs.

**Comment by nicozerr** [comment]
Oui c'est plutôt ça en effet. En fait, `tarteaucitronForceLanguage` est toujours prioritaire.

**Comment by EmmanuelDemey** [comment]
Cette solution me convient.

**Comment by AmauriC** [comment]
Je viens de publier ces changements ; )
https://github.com/AmauriC/tarteaucitron.js/commit/a470a4be591876e1409269930362acd3cc73e92d
https://github.com/AmauriC/tarteaucitron.js/commit/21a271e5ba8036653b7cf580383814949890a8df

**Comment by EmmanuelDemey** [comment]
Dois je crée une seconde issue pour l'autre point ?

**Comment by AmauriC** [comment]
Oui, ce sera plus simple. Merci 😃

**Comment by EmmanuelDemey** [comment]
Done

**Comment by EmmanuelDemey** [comment]
Ce bug est corrigé dans quelle version ?

**Comment by AmauriC** [comment]
Je n'ai pas encore push de nouvelle release. 
Je m'en occupe la semaine prochaine quand j'ai ajouté les services en attente ; )
