### ISSUE TITLE
Intégration de l'API IAB

### ISSUE THREAD

**Issue by Flofr** [AmauriC/tarteaucitron.js#87]
Salut tout le monde,

J'ai besoin d'intégrer l'[API IAB](http://advertisingconsent.eu/) pour deux de mes annonceurs, quelqu'un l'a déjà fait ?

**Comment by paulgreg** [comment]
D’après ce que j’a compris : pour être conforme au RGPD/GDPR, l’IAB impose une solution qui nécessite l’utilisation d’un « CMP » (Consent Management Provider).
Les spécifications sont publiques : https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/CMP%20JS%20API%20v1.1%20Final.md

Chaque implémentation de CMP doit être validé par l’IAB (sur https://register.consensu.org/CMP et moyennant 350 € de frais au passage).

L’intérêt est que, seul les CMP « validés » par l’IAB pourront afficher de la pub ciblée. Sans CMP ou sans CMP validé, pas de publicité ciblé.

J’ai trouvé une implémentation de CMP de démo sur le github d’AppNexus, un acteur dans le monde de la publicité : https://github.com/appnexus/cmp (attention, il n’est pas validé et à priori ne devrait pas l’être, c’est juste une implém de démo).

D’où mes questions : est-ce que tarteaucitron a vocation a évoluer pour être conforme au RGPD/GDPR ? 
Si oui, est-il prévu de modifier tarteaucitron pour « devenir » un CMP et de le faire valider auprès de l’IAB ?

**Comment by Flofr** [comment]
Bonjour paulgreg, merci pour ta réponse.

Nous avons eu l'occasion de tester l'intégration d'un CMP validé par l'IAB, mais nous n'allons pas continuer pour l'instant pour deux raisons : 
 1) Tous les annonceurs déclarés sur l'IAB sont affichés et on a la possibilité de les autoriser ou nous, ce qui peut noyer l'utilisateur et lui faire peur.
 2) l'API de l'IAB n'est pas finalisée, on verra donc ce que ça donne une fois que ce sera stable et utilisé.

En attendant nous restons donc sur tarteaucitron et l'implémentation classique.
A suivre

**Comment by vaandefanel** [comment]
@Flofr Ca fait 1 an, l'information est toujours valable ?

**Comment by Flofr** [comment]
Salut,

Nous n'utilisons plus tarteaucitron depuis quelques mois car en effet il faut une CMP validée par l'IAB. Je n'ai pas suivi si celle-ci a évolué depuis.
On a donc migré vers notre solution groupe avec un vendor enregistré auprès de l'IAB.
