### ISSUE TITLE
La fenêtre du cookie réapparait a "tout refuser" => cookie reste sur Wait

### ISSUE THREAD

**Issue by MyErickson** [AmauriC/tarteaucitron.js#871]
Bonjour,

-Lorsque la popin s'ouvre pour la première fois, on peut choisir "**tout refuser**", Mais cette commande mets la valeurs des services à "wait", la popin réapparait au chargement de page.
-Même soucis  si on refuse tout un par un dans gestion de cookie .
La page se recharge et la popin s'ouvre de nouveau...ainsi de suite

**Tout marche** si on décide "Tout accepter" ou on accepte au moin "un service".

Comportement voulu :   Si la personne dis non à tous, il ne faudrait pas lui reproposer la popin au chargement et mettre les cookies utiliser a false.

j'utilise la méthode manuelle 

site : https://prium-portage.com/
version utilisé : 1.9.5
voici l'init : 
```

function tarteaucitron_init() {
?>
<script type="text/javascript">
        tarteaucitron.init({
          "privacyUrl": "https://prium-portage.com/protection-des-donnees/",
          "hashtag": "#tarteaucitron",
          "cookieName": "tartaucitron",
          "orientation": "bottom",
          "showAlertSmall": true,
          "cookieslist": false,
          "adblocker": false,
          "AcceptAllCta" : true,
          "highPrivacy": true,
          "handleBrowserDNTRequest": false,
          "removeCredit": false,
          "moreInfoLink": false,
          "DenyAllCta" : true,
          "cookieDomain": ".prium-staging.fr",
          "useExternalJs": false,
        });
    </script>
    <?php
}
    add_action('wp_head', 'tarteaucitron_init');
function add_tarteaucitron_services()
{
?><script type="text/javascript">
        tarteaucitron.user.googletagmanagerId = 'GTM-N3PJL4';
        (tarteaucitron.job = tarteaucitron.job || []).push('googletagmanager');
    </script>
    <script type="text/javascript">
        (tarteaucitron.job = tarteaucitron.job || []).push('facebook');
    </script>
<?php
}
    add_action('wp_footer', 'add_tarteaucitron_services');
?>
```

**Comment by MyErickson** [comment]
J'ai changé dans le fichier tartaucitron.js

```
if (nbPending === 0 ) {
                tarteaucitron.userInterface.closeAlert();
            }
```

par 

```
if (nbPending <= 1) {
                console.log("ON A TOUT CHECK HAN INT",nbPending)
                tarteaucitron.userInterface.closeAlert();
            }
```

pour que tout comportement voulu marche (test en local)

**Comment by AmauriC** [comment]
Modifier le fichier js n'est jamais une bonne idée, la solution est plus simple, le cookieDomain est pour le staging `"cookieDomain": ".prium-staging.fr",` donc le cookie ne peux jamais être déposé sur /prium-portage.com/, c'est ça le souci ; )

**Comment by kumatata** [comment]
@AmauriC  sur le site de production, le cookidomain est bien sur ".prium-portage.com" , malgré tout la fenêtre revient. En particulier quand on veut accepter/refuser les services un par un dans la fenêtre" gestion de cookie".

**Comment by AmauriC** [comment]
Je n'avais pas vérifié le site.
C'est une version non à jour et modifié actuellement sur le site en prod donc difficile de trouver le problème.

Mettez à jour tarteaucitron sans vos modifs perso et ce sera plus simple pour aider à chercher le problème ; )

**Comment by MyErickson** [comment]
Autant pour moi j'ai donné le lien de prod . Le bon lien est celui  ci http://prium-staging.fr/

J'ai cru que j'étais déjà a jour avec la version 1.9.5. Apres avoir re télécharger et dézippé , le new version porte le nom de 1.9.2.5. 
Tout marche avec cette version, merci ;)
