### ISSUE TITLE
conflict with recaptcha loaded through contact form 7 in wordpress

### ISSUE THREAD

**Issue by JordanDemartin** [AmauriC/tarteaucitron.js#873]
Hi,
In my wordpress, I have a recaptcha v3 loaded by contact form 7.
When I use tarteaucitron with the automatic mode I have javascript error saying that 'grecaptcha is not defined'.
The problem I have beside the javascript error is that my contact form ends up not being validated by the captcha and any submission is treated as a spam.

What I understand from what I tried is that tarteaucitron seems to hinder the contact form 7 when it tries to load recaptcha.
Any idea on how to solve my issue?

![Capture d’écran 2022-02-02 à 10 56 38](https://user-images.githubusercontent.com/8151969/152131960-e46fdc9d-c7cc-4659-b56c-ab21a8cdf9c0.png)

**Comment by AmauriC** [comment]
Hi

I guess you get this error when the recaptcha service is not allowed on the page?
This is how tarteaucitron work, if the user didnt allow a service, he's not loaded so the function didnt exist.

**Comment by JordanDemartin** [comment]
Well, sadly, this is not the problem, as I test it while having allowed the service

**Comment by AmauriC** [comment]
So this is because CF7 try to access `grecaptcha` before it's loaded by tarteaucitron.

Did you asked their support? 
There is also this https://github.com/jerome-rdlv/cf7-tac-recaptcha (untested)

**Comment by JordanDemartin** [comment]
Tarteaucitron dosen't load recaptcha by itself? As I use the automatic mode, dosen't it just discover the recaptcha used by CF7?

But yes, with the link you gave, if I succeed in having tarteaucitron load recaptcha, everything would be solved.

**Comment by AmauriC** [comment]
The auto mode detect and block the script.

If allowed, it's loaded but after the DOM is ready. CF7 try to get it before so it fail.

**Comment by JordanDemartin** [comment]
I tried switching their loading order but it didn't change anything.

Also tried to use this https://github.com/jerome-rdlv/cf7-tac-recaptcha
But it just ended with no recaptcha loading at all
(usually contact form manage to load recaptcha but not use it, as tarteaucitron somehow prevent it)

**Comment by JordanDemartin** [comment]
I think I found a solution
I disabled the reCaptcha of CF7 and added the plugin 'Invisible reCaptcha',
using this plugin that can also protect CF7, everything seems to work

Tarteaucitron sees the recaptcha and if I refuse it, the form doesn't submit (expected behavior)
