### ISSUE TITLE
Any plan to support webpack bundling ?

### ISSUE THREAD

**Issue by WhereIsLucas** [AmauriC/tarteaucitron.js#877]
Hi,

I'm using tarteaucitron with Laravel Mix (wrapper around webpack) and it's currently not possible to include it in my app.js file, it has to be loaded in parallel, which is not that great.
Do you have any plan on changing that so it would be possible ? 
I'm willing to work on a PR for that if it has chances to get merged.

Thanks for this great script and for making it open-source !

**Comment by AmauriC** [comment]
Hey!

I'm not sure of what have to be changed but if it doesnt break anything, I'm ok to merge any PR that can help the community ; )
