### ISSUE TITLE
Rendre le bouton ouvrant la modale accessible rapidement au clavier

### ISSUE THREAD

**Issue by EmmanuelDemey** [AmauriC/tarteaucitron.js#878]
Pour des raisons d'accessibilité, préconisez.vous une façon de rendre le bouton de gestion des cookies rapidement accessible au clavier ? Car a l'heure actuelle, en tout cas chez mon client, nous sommes obligés de traverser l'ensemble de la page avec le clavier avant d'atteindre ce fameux bouton.

**Comment by EmmanuelDemey** [comment]
https://github.com/AmauriC/tarteaucitron.js/issues/868

**Comment by AmauriC** [comment]
Quelque chose comme ça? 
https://tarteaucitron.io/TEST/878.html

**Comment by nicozerr** [comment]
Si tu utilises l'option `bodyPosition` avec la valeur "top" pour que TAC soit positionné au début du code HTML de ta page, le bouton d'ouverture sera lui aussi positionné au début du code, et donc accessible rapidement au clavier. Pareil avec le bandeau cookie.

**Comment by EmmanuelDemey** [comment]
Pour ce bandeau ne doit pas se trouver en bas, car sinon nous avons un autre problème d'accessibilité : le fait que l'utilisateur doit aller en bas puis revenir en haut de la page si il navigue via le clavier. 
Ce que je préconise, pour que cela soit assez flexible, c'est de vérifier, si le TAC est en bas, est de vérifier qu'il existe une lien avec une ancre pointant vers le TAC. Si ce n'est pas le cas, emettre une erreur dans la console. 
Ensuite libre au développeur de créer cette ancre avec son propre stye et/ou l'intégrer à son système de skipLink existant 

Qu'en pensez vous ?

**Comment by nicozerr** [comment]
Attention, il ne faut pas confondre la position visuelle du bandeau définie en CSS, et la position dans le code source qui a un impact sur l'ordre de lecture/tabulation.

En effet, avec l'option `bodyPosition` à "top" et `orientation` à "bottom", le bandeau est affiché en bas de la page, mais son code source se trouve en haut. Lors de la navigation au clavier, cela provoque un déplacement important du haut de la page vers le bas (puis retour en haut ensuite) et pourrait perturber certains utilisateurs malvoyants qui zooment plus ou moins fortement pour consulter la page.
Certains auditeurs en accessibilité rendent le bandeau cookie (ou le bouton d'ouverture de TAC) non-conforme sur le critère 10.3 (ordre logique des éléments) ou le 12.8 (ordre de tabulation) dans ce cas-là. Moi en tant qu'auditeur en accessibilité (et ancien développeur), je le tolère cela et ne l'impacte pas.

Pour respecter pleinement l'accessibilité, on peut utiliser `bodyPosition` à "top" et `orientation` à "top". L'ordre de lecture/tabulation correspondra alors à l'ordre d'affichage. Cela deviendra alors une question de webdesign. Et même, avec une surcharge CSS, on peut tout à fait le rendre non-flottant, tanqué proprement en haut.

On pourrait aussi utiliser `bodyPosition` à "bottom" et `orientation` à "bottom". Cela respectera aussi l'accessibilité, mais un peu moins le RGPD qui exige que le consentement des cookies soit l'un des premiers éléments à présenter aux utilisateurs.
On peut solutionner cela en remplaçant le bouton d'ouverture natif de TAC (`showIcon` ou `showAlertSmall`) par un bouton custom dans l'entête de la page pour ouvrir le bandeau cookie, du type `<button title="Gestion des cookies - fenêtre modale" onclick="tarteaucitron.userInterface.openPanel(); return false;">Gestion des cookies</button>`. 

En tout cas, selon moi, ce n'est pas à TAC de vérifier que la configuration de TAC respecte l'accessibilité par rapport à son positionnement visuelle et dans le code. TAC fournit assez d'options pour cela, il est possible de le surcharger en CSS, et sa dernière vresion est très très satisfaisante niveau accessibilité.

**Comment by EmmanuelDemey** [comment]
Mais on pourrait au moins mettre quelque part (documentation, warning, ...) cette information pour les utilisateurs. Sinon cela ne sera jamais mis en place. 
Mais je suis d'accord avec toi.

**Comment by nicozerr** [comment]
Quand tu parle de mettre l'information à disposition des utilisateurs, tu parles de quelle information exactement ? Une info qui permette aux utilisateurs naviguant au clavier de se rendre directement au bandeau cookie ou sur le bouton d'ouverture de TAC ?

**Comment by EmmanuelDemey** [comment]
pour indiquer aux développeurs et développeuses qui utilise le TAC, que si ils le placent en bas, un travail supplémentaire est nécessaire pour rendre le TAC accessible. Mais qu'il a été choisi de ne pas le faire au sein du TAC, et laisser les développeurs le faire seuls.

**Comment by nicozerr** [comment]
> On pourrait aussi utiliser `bodyPosition` à "bottom" et `orientation` à "bottom". Cela respectera aussi l'accessibilité, mais un peu moins le RGPD qui exige que le consentement des cookies soit l'un des premiers éléments à présenter aux utilisateurs.

Je viens de m'informer auprès de mon référent RGPD. Je me suis trompé. Le RGPD n'exige pas que le consentement des cookies soit l'un des premiers éléments à présenter aux utilisateurs. Le choix doit juste être présenté explicitement et sans incitation (par ex., Accepter ne doit pas être mis en avant par rapport à Refuser).

**Comment by AmauriC** [comment]
Dans l'exemple de mon premier post le skip link est juste à côté du mini bandeau puise que c'est un endroit ou logiquement il y a de la place. Mettre le skip link en haut sera aléatoire, impossible de savoir si il n'y a pas déjà un element qui sera masqué.

Tarteaucitron l'est déjà sur la navigation dans le panel/bandeau, rendre accessible l'accès à ce panneau n'est pas forcément du ressort de tac et risque au final d'être contre productif. 
Par exemple sur https://www.numerique.gouv.fr/publications/rgaa-accessibilite/, il suffirait d'ajouter un skip link avec ceux déjà existant.

**Comment by EmmanuelDemey** [comment]
@nicozerr ma remarque n'est pas lié à la RGPD mais a l'accessibilité. 
Image quelqu'un qui souhaite en premier lieu refuser les cookies, il doit naviguer sur l'ensemble de la.page avant d'y arriver.

**Comment by EmmanuelDemey** [comment]
@AmauriC je préconise également une documentation quelque part.

**Comment by nicozerr** [comment]
De nombreux utilisateurs utilisent des aides techniques, dont des lecteurs d'écrans, qui proposent plusieurs manières de comprendre la structure d'une page et d'accéder aux différentes sections d'une page. L'une des plus utilisées est la navigation par titres. Le logiciel fournit la liste de tous les titres de la page, avec leur niveau hiérarchique, et l'utilisateur passe de l'un à l'autre.

[La directive 2.4.10 des WCAG](https://www.w3.org/Translations/NOTE-UNDERSTANDING-WCAG20-fr/NOTE-UNDERSTANDING-WCAG20-fr-20110706/navigation-mechanisms-headings.html) ([version anglaise ici](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-headings.html)), de niveau AAA, indique que chaque section d'une page doit avoir un titre (au regard du RGAA, ce n'est pas une non-conformité).

> **Avantages spécifiques du critère de succès 2.4.10 :**
> - Les personnes aveugles sauront qu'elles se déplacent d'une section à l'autre d'une page Web et connaîtront le but de chaque section.
> - Les personnes ayant certaines difficultés d'apprentissage auront la possibilité d'utiliser les en-têtes pour comprendre plus facilement l'organisation générale du contenu de la page.
> - Les personnes qui naviguent à l'aide du clavier pourront déplacer le focus d'en-tête en en-tête, ce qui leur permet de trouver rapidement le contenu qui les intéresse.
> - Dans les pages où une partie du contenu se met à jour, les en-têtes peuvent être utilisés pour accéder rapidement au contenu mis à jour.

Pour améliorer l'accès à TAC, c.-à-d. au bandeau et au bouton d'ouverture, il serait donc intéressant d'ajouter, par exemple, un titre `h2` juste après l'ouverture de la balise `div#tarteaucitronRoot`, associé à un nouveau paramètre pour définir le texte. Si le paramètre est vide, il n'y a pas de titre.

Ensuite, pour la documentation, il pourrait y avoir une page sur tarteaucitron.io avec la configuration recommandée pour respecter l'accessibilité au maximum, et ce qu'il serait conseillé d'ajouter sur le site.
Je vais voir pour vous proposer une config adaptée.

**Comment by AmauriC** [comment]
Merci @nicozerr  👍 

> il serait donc intéressant d'ajouter, par exemple, un titre `h2`

Il peux être en `display:none` ou pour être interpréter pour les logiciels d'aide il faut qu'il soit visible?

**Comment by EmmanuelDemey** [comment]
Je ne me souviens plus qu'on fonctionne le rotor des synthétiseurs vocaux. Est ce qu'ils gèrent les titre caché ? 
Je vais vérifier ce soir si personne ne le fait avant :)

**Comment by EmmanuelDemey** [comment]
Le titre n'est pas récupéré par le rotor quand il est caché. 
Il faut mieux le mettre à l'extérieur du viewport avec une position absolue

**Comment by nicozerr** [comment]
Les lecteurs d'écran ne restituent pas les éléments avec display:none. D'autres propriétés CSS et attributs HTML permettent de cacher un élément aux aides techniques, comme indiqué dans le [glossaire du RGAA](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode-rgaa/glossaire/#contenu-cache).
Il vaut mieux lui mettre une classe lié à du CSS [comme indiqué dans cet exemple](https://gist.github.com/ffoodd/000b59f431e3e64e4ce1a24d5bb36034).

**Comment by AmauriC** [comment]
Merci @EmmanuelDemey et @nicozerr , je m'occupe d'ajouter l'option : )

**Comment by nicozerr** [comment]
@AmauriC 
Je viens ajouter un élément qui peut avoir son importance pour la navigation rapide vers TAC avec les technologies d'assistance.

Précédemment, j'évoquais la navigation par titre.
Une autre manière de naviguer rapidement est aussi très utilisée : la navigation par régions principales de la page, ou "Landmarks".
En HTML5, ces Landmarks sont identifiées avec les balises `<header>`, `<aside>`, `<footer>`, `<form>`, `<main>`, `<nav>`, et `<section>`.
Lorsqu'il n'est pas possible d'utiliser ces balises (pour la rétrocompatibilité par exemple), [WAI-ARIA](https://www.w3.org/TR/wai-aria/) permet d'utiliser l'attribut `role` pour définir les Landmarks (et aussi tout un tas d'autres types d'éléments).
- `<div role="main">` = `<main>`
- `<div role="banner">` = `<header>`
- `<div role="conteninfo">` = `<footer>`
- `<div role="complementary">` = `<aside>`
- `<div role="navigation">` = `<nav>`
- `<div role="form">` = `<form>`
- `<div role="region">` = `<section>`
- `<div role="search">` (pas d'équivalent en HTML5)

[La définition de ces Landmark sur le site WAI-ARIA.](https://www.w3.org/TR/wai-aria/#landmark_roles)

Dans le cas de TAC, j'aurais bien proposer d'utiliser la balise `<section id="tarteaucitronRoot">` au lieu de `<div id="tarteaucitronRoot">` pour le wrapper général. Mais pour respecter la rétrocompatibilité, on peut utiliser `<div id="tarteaucitronRoot" role="region">`.
Si à cela tu ajoutes le titre que nous évoquions précédemment, cela devra donner :
```
<div id="tarteaucitronRoot" role="region" aria-labelledby="tac_title">
 <div role="heading" aria-level="1" id="tac_title" class="tac_visually-hidden">Gestion des cookies</div>
 ...
```

Explications :
- `role="region"` : définition de la région ([plus d'info sur le site de Developer Mozilla](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/region_role) ou du [WAI-ARIA](https://www.w3.org/TR/wai-aria/#region))
- `aria-labelledby="tac_title"` : permet de donner un titre à cette région, en l'associant au titre utilisant `id="tac_title"`
- `<div role="heading" aria-level="1"` : permet de transformer cette <div> en un titre de niveau 1 pour les aides techniques, sans utiliser directement `<h1>` (ça évitera les foudres des spécialistes du SEO)
- class="tac_visually-hidden" : classe CSS à définir pour cacher le titre visuellement mais conserver la lecture avec un lecteur d'écran ([voir `.visually-hidden` sur Orange Accessibilité](https://a11y-guidelines.orange.com/fr/web/exemples-de-composants/masquage-accessible/), ou [`.sr-only` sur Bootstrap](https://getbootstrap.com/docs/4.3/getting-started/accessibility/#visually-hidden-content) et [amélioré sur ce Gist](https://gist.github.com/ffoodd/000b59f431e3e64e4ce1a24d5bb36034))

**Comment by AmauriC** [comment]
Merci pour toutes ces précisions, c'est dispo : )

**Comment by nicozerr** [comment]
Personnellement, je valide !

**Comment by EmmanuelDemey** [comment]
Moi aussi

**Comment by AmauriC** [comment]
Merci encore à tous pour vos précieuses contributions 😊

**Comment by nicozerr** [comment]
De rien :)
Merci à toi pour ta réactivité, ta compréhension et ton ouverture.
