### ISSUE TITLE
Installation via npm/yarn

### ISSUE THREAD

**Issue by iroshiva** [AmauriC/tarteaucitron.js#880]
Bonjour,

J'ai installé tarteaucitron via $ yarn add tarteaucitronjs, mais n'ai pas réussi à l'initialiser.

import tarteaucitron from 'tarteaucitronjs/tarteaucitron'
tarteaucitron.init({maconfig})

J'ai l'erreur suivante en console: "tarteaucitronjs_tarteaucitron__WEBPACK_IMPORTED_MODULE_6___default(...).init is not a function"

Erreur de manip ?
Ou l'extension n'est faite en modules, est-ce pour ça ? Ne marche pas ?

Merci !

**Comment by AmauriC** [comment]
tarteaucitron n'est pas fait en module, si ça peux aider à débugguer le problème.

Je n'ai pas du tout l'habitude de travailler avec yarn donc difficile d'aider plus ; )

**Comment by iroshiva** [comment]
ok !
npm/yarn c'est un peu le même combat ;)

Quelle serait du coup la manière d'utiliser la librairie après son install via npm ?

**Comment by AmauriC** [comment]
Aucune idée de mon côté puise que je n'utilise ni l'un ni l'autre mais le dépôt npm est pas mal utilisé donc je suis sur qu'il y a une solution ☺️

**Comment by hoprikoma** [comment]
Personne n'a trouvé de solutions ? J'en ai besoin 😢

**Comment by pixel-up-13** [comment]
Je suis dans le même cas, installé via NPM (webpack) mais impossible de charger le script avec un import classique...
Par tout hasard @AmauriC aurais tu avancés sur cette problématique ?
En tout cas merci pour ce JS que j'utilise depuis plusieurs année maintenant.
