### ISSUE TITLE
Services à bloquer

### ISSUE THREAD

**Issue by ecosphere-aggelos** [AmauriC/tarteaucitron.js#881]
Salut Amauri,
serait-il possible d’ajouter Weborama à la liste des services bloqués automatiquement, stp ? 

Le site est https://weborama.com/

Le script appelé par ce service est : <script type="text/javascript" src="https://cstatic.weborama.fr/js/advertiserv2/adperf_conversion.js"></script>

Le cookie : https://secure.adnxs.com/

En bloquant l'accès à https://cstatic.weborama.fr/js/advertiserv2/adperf_conversion.js on bloque toutes les requêtes qui s'appuient sur ce service.

Un autre service qui échappe à TAC est ce pixel provenant de [doubleclick.net](http://doubleclick.net/), peux-tu le bloquer de quelques façon ?

L'iframe appelé est : 
<iframe src="https://9677851.fls.doubleclick.net/activityi;src=9677851;type=lpuni;cat=lpuniq;dc_lat=;dc_rdid=;tag_for_child_directed_treatment=;tfua=;npa=;ord=1;num=' + a + '?" width="1" height="1" frameborder="0" style="display:none"></iframe>

Les cookies : https://9677851.fls.doubleclick.net et adservice.google.com

Merci, si tu as besoin d'autres détails n'hésite pas.

**Comment by AmauriC** [comment]
Salut,

## Weborama

Il n'y a que le tag `<script type="text/javascript" src="https://cstatic.weborama.fr/js/advertiserv2/adperf_conversion.js"></script>` à ajouter sur le site?

## Doubleclick

A quoi correspond `9677851` ? C'est l'id unique du compte?
Il n'y a que l'iframe à ajouter, pas de script js?


Merci!

**Comment by ecosphere-aggelos** [comment]
Salut,

Pour Weborama il y a ce script et le cookie https://[ID_COMPTE].solution.weborama.fr : 
![Capture d’écran 2022-02-21 à 10 37 18](https://user-images.githubusercontent.com/86417525/154928867-b71c8dba-bed1-4d10-89c2-72b7bba84f84.png)

Pour Doubleclick oui, il s'agit de l'id unique et je ne vois pas des js liés au domaine (peut être qu'ils sont dans le code executé par l'iframe).

Merci à toi !

**Comment by AmauriC** [comment]
J'ai ouvert 2 issues pour faciliter la mise en place:
https://github.com/AmauriC/tarteaucitron.js/issues/895
https://github.com/AmauriC/tarteaucitron.js/issues/894
