### ISSUE TITLE
Matomo garde des références à piwik dans les services

### ISSUE THREAD

**Issue by xillibit** [AmauriC/tarteaucitron.js#883]
Quand on utilise matomo et que l'on demande le code de suivi on obtient ça :

`<script>
  var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="https://link.com/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '1']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>`

Mais le fichier service il reste des référence à piwik : 

`window._paq.push(["setTrackerUrl", tarteaucitron.user.matomoHost + "piwik.php"]);`
   
`tarteaucitron.addScript(tarteaucitron.user.matomoHost + 'piwik.js', '', '', true, 'defer', true);`

`// waiting for piwik to be ready to check first party cookies`

**Comment by AmauriC** [comment]
C'est le service `matomocloud` qu'il vous faut ; )

**Comment by xillibit** [comment]
Je viens de voir que l'on peut être exempter de consentement en ayant configurer Matomo selon les préconisations de la CNIL : https://www.cnil.fr/fr/cookies-solutions-pour-les-outils-de-mesure-daudience

**Comment by lucmuller** [comment]
J'ai le cas d'un script d'inclusion matomo où le fichier n'est ni piwik.php, ni matomo.php mais m.php (  _paq.push(['setTrackerUrl', u+'m.php']); )
Est-ce une mise à jour de matomo ? Une autre version qui doit être prise en compte dans TAC ?

Je tente d'avoir des précisions et je reviens faire un tour par ici.

> Je viens de voir que l'on peut être exempté de consentement en ayant configurer Matomo selon les préconisations de la CNIL : https://www.cnil.fr/fr/cookies-solutions-pour-les-outils-de-mesure-daudience
=> Quand-bien même, la cnil prévois que l'utilisateur doit pouvoir renoncer et indiquer qu'il ne souhaites pas être suivi.
Matomo fourni une iframe à ce but.
Si vous avez installé cette iframe dans votre site, ALORS il n'est pas requis de déclarer le script matomo (high privacy) dans TAC.
Sinon la meilleure solution reste d'intégrer matomo dans tac et car cela centralise les autorisations/refus de l'utilisateur.

**Comment by lucmuller** [comment]
> J'ai le cas d'un script d'inclusion matomo où le fichier n'est ni piwik.php, ni matomo.php mais m.php ( _paq.push(['setTrackerUrl', u+'m.php']); ) Est-ce une mise à jour de matomo ? Une autre version qui doit être prise en compte dans TAC ?
> 
> Je tente d'avoir des précisions et je reviens faire un tour par ici.

Je confirme que dans l'installation en court, le service matomo ne fonctionne pas avec les serveur matomo qui utilisent m.php

**Comment by AmauriC** [comment]
Ok, une idée, vérifier si `tarteaucitron.user.matomoHost` termine par .php et ajouter comme maintenant `"piwik.php"` si ce n'est pas le cas ?
