### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'toString') at Object.fixSelfXSS (tarteaucitron.js?1638786396:1772:21)

### ISSUE THREAD

**Issue by lucmuller** [AmauriC/tarteaucitron.js#884]
Je rencontre cette erreur sur l'un de mes sites de développement, lors du premier clic sur l'un des boutons de la modalbox.
![image](https://user-images.githubusercontent.com/1927963/154224365-8a044443-5f0a-4a4c-b4f8-d7f9bfaef2c9.png)
Cela semble lié au fait que dans certains cas _html_ ne soit pas défini dans la fonction _fixSelfXSS_
![image](https://user-images.githubusercontent.com/1927963/154224605-60761cad-f5dc-44a5-8f96-67609cfb5315.png)

Une des idées que j'ai pour l'instant est le fait que j'utilise ce script : https://van11y.net/accessible-accordion/ pour lequel la gestion du 'onclick' me semble hasardeux.
Tous les clics sur le body sont trackés et détournés, j'ignore pourquoi il font cela ainsi, mais cela m'a déjà posé souci sur un autre site, mais je n'avais encore jamais constaté de dysfonctionnement avec Tarte au Citron.

Je vais investiguer pour voir si je trouve l'origine de l'anomalie, mais j'imagine que conditionner l'exécution à la présent de HTML ne doit pas être adéquat.

J'ouvre le ticket, des fois que des personnes aient déjà été confrontées à ce souci aussi.

**Comment by AmauriC** [comment]
Tu utilises le service "iframe" ?

Si oui, modifie ligne 14 :

```
            var frame_title = tarteaucitron.fixSelfXSS(x.getAttribute("title") || 'iframe'),
```

Si c'est bien ça je corrige ici aussi ; )

**Comment by lucmuller** [comment]
J'ai proposé un pull request qui corrige l'anomalie.
J'ai conditionné l'appel à la fonction à la présence d'un title. Cela me semble plus correct plutôt que d'impacter un title qui ne soit pas verbeux.
