### ISSUE TITLE
Exemption du consentement pour Matomo

### ISSUE THREAD

**Issue by ecosphere-aggelos** [AmauriC/tarteaucitron.js#889]
Salut Amauri,

Actuellement les utilisateurs des sites où TAC est installés peuvent choisir si refuser les cookies de Matomo, alors que lorsqu'il est auto-hebergé, bien configuré et qu'on informe les utilisateurs de sa présence, Matomo respecte le RGPD et bénéficie de l'exemption du consentement de la CNIL. 

Est-il possible que les solutions de mesure d'audiences éthiques et légales soient exemptées du système de blocage des cookies, ou au moins donner la possibilité de les exclure ?

Plus d'infos et liste des solutions à exempter ici : https://www.cnil.fr/fr/cookies-solutions-pour-les-outils-de-mesure-daudience

Merci !

**Comment by AmauriC** [comment]
Salut,

Si Matomo est correctement configuré pour être exempté de consentement, il n'est pas utile de l'inclure dans tarteaucitron.

Tac est là pour les services qui nécessitent un consentement, dans le cas contraire, inutile d'ennuyer l'utilisateur   ; )

**Comment by pierretux** [comment]
Bonjour,

Matomo va prendre de l’ampleur avec la nouvelle règle pour GA.
Comment savoir si je l'ai bien configurer ?

Merci

**Comment by mythevalentinus** [comment]
Bonjour,

Je me permets d'ouvrir à nouveau ce topic.
Matomo n'a pas besoin de consentement si il est bien configuré, par contre il faut pouvoir le désactiver à la demande utilisateur.
Est-il possible avec tarteaucitron d'activer un service par défaut meme sans action utilisateur, mais de pouvoir venir le bloquer ?

Merci

**Comment by AmauriC** [comment]
C'est le paramètre `needConsent` qui détermine si un service est ok pour être chargé par défaut ou non.
https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.services.js#L4242
