### ISSUE TITLE
Ajout de Revive Adserver

### ISSUE THREAD

**Issue by AmauriC** [AmauriC/tarteaucitron.js#891]
## Marqueur HTML
```
```
## Liste des cookies
?

### Site web
[Site web](https://www.revive-adserver.com/)
### Politique de confidentialité
[Politique de confidentialité](https://www.revive-adserver.com/privacy/)

**Comment by editionslva** [comment]
Voici le code utilisé par le [plugin wordpress](https://fr.wordpress.org/plugins/wp-revive-adserver/) pour afficher les bannières. J'espère que vous pourrez en faire quelque chose mais j'ai des doutes...
Le code est consultable ici: [https://plugins.trac.wordpress.org/browser/wp-revive-adserver/trunk/src/Inc/WPReviveShortcodes.php](https://plugins.trac.wordpress.org/browser/wp-revive-adserver/trunk/src/Inc/WPReviveShortcodes.php)

###  Async Insertion
`  $content = '<ins data-revive-zoneid="' . $zoneid . '" data-revive-id="' . $reviveid . '"></ins>
        <script async src="' . $url . '/asyncjs.php"></script></div>';
`
### Iframe Insertion
`   $content='<iframe id="' . $iframeID . '" name="' . $iframeName . '" src="' . $url . '/afr.php?zoneid=' . $zoneid . '&amp;cb=INSERT_RANDOM_NUMBER_HERE" frameborder="0" scrolling="no" width="' . $width . '"
    height="' . $height . '"><a href="' . $url . '/ck.php?n=a23d0313&amp;cb=INSERT_RANDOM_NUMBER_HERE" target="_blank">
    <img src="' . $url . '/avw.php?zoneid=1&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=a23d0313" border="0" alt="" /></a></iframe>';`


### JS
` $content = '
    <script type=\'text/javascript\'></script><noscript><a href=\'' . $url . '/ck.php?n=a86c7caa&amp;cb=INSERT_RANDOM_NUMBER_HERE\' target=\'_blank\'><img src=\'' . $url . '/avw.php?zoneid=1&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=a86c7caa\' border=\'0\' alt=\'\' /></a></noscript>`
