### ISSUE TITLE
Ajout de Userpilot

### ISSUE THREAD

**Issue by AmauriC** [AmauriC/tarteaucitron.js#892]
## Marqueur HTML
```
<script> window.userpilotSettings = {token: "appToken"}; </script>
<script src = "https://js.userpilot.io/sdk/latest.js"></script>
```
## Liste des cookies
?

### Site web
?
### Politique de confidentialité
https://userpilot.com/security

**Comment by MajdSehwail** [comment]
**HTML markup:**
`<script> window.userpilotSettings = {token: "appToken"}; </script> <script src = "https://js.userpilot.io/sdk/latest.js"></script`

**List of cookies:** None used

**Privacy Policy:** https://userpilot.com/privacy-policy

**Possible Options:**
- Long Polling: `window.userpilotSettings = {token: "appToken", connection: "polling"};`
