### ISSUE TITLE
Register to Bower

### ISSUE THREAD

**Issue by devyg** [AmauriC/tarteaucitron.js#9]
As it's heavily used nowadays, why not register your js to Bower ? I love just having to `bower install` the packages I use, plus it makes it easier for devs to integrate your project.

**Comment by AmauriC** [comment]
I don't use bower, is it possible to sync bower with this github or I must push to bower when a new release is published ?

**Comment by devyg** [comment]
You register your GithHub repo so it only has to be done one time. The package is then linked to the project. When you push, users will have the last version when installing or updating with the bower tool.
Official doc right here : http://bower.io/docs/creating-packages/

**Comment by AmauriC** [comment]
Done :)
`bower install tarteaucitron`

**Comment by guix77** [comment]
It works but there are 2 warnings :
    bower invalid-meta  tarteaucitron is missing "main" entry in bower.json
    bower invalid-meta  tarteaucitron is missing "ignore" entry in bower.json
