### ISSUE TITLE
TypeError: tarteaucitron.lang[b] is undefined

### ISSUE THREAD

**Issue by Sorcim** [AmauriC/tarteaucitron.js#90]
Bonjour, 
lorsque j'essaie d'utiliser le script, je me retrouve avec cette erreur : 

TypeError: tarteaucitron.lang[b] is undefined

Ligne 219 de tarteaucitron.js

J'ai beau chercher je ne trouve pas d’où vient l'erreur.

Merci

**Comment by Nabnab9** [comment]
Salut, 

est ce que vous avez apporté des modifications au fichier de langue ? (dans tarteaucitron/lang)

**Comment by Sorcim** [comment]
Non, j'ai utilisé les fichiers sans modification.

**Comment by Sorcim** [comment]
Je ne comprend pas, j'ai ré-uploadé les fichiers et maintenant ça fonctionne.
Pourtant les fichiers sont les mêmes...

Désolé pour le dérangement.
