### ISSUE TITLE
Utiliser les variables CSS ou SCSS ?

### ISSUE THREAD

**Issue by benjamingrolleau** [AmauriC/tarteaucitron.js#912]
Hello,

Je pense que nous serions un paquet de développeur à adorer utiliser Tarte au citron avec un fichier SCSS de base ou bien encore mieux, en utilisant les variables CSS pour surcharger le style par défaut.

**Comment by benjamingrolleau** [comment]
Et bien si tu veux que je t'aide, je suis ton homme :-)

Dispo sur Twitter pour en discuter : @benjgrolleau

**Comment by AmauriC** [comment]
Le compte Twitter n'existe pas 😅

Le premier gros chantier serait de sortir de tarteaucitron.js tous les styles online pour les mettre dans css/Tarteaucitron.css 

Ensuite mettre au propre le fichier css parce que c'est vraiment le bordel 😬

Ensuite remplacer ce qui doit l'être (couleurs, shadow, radius, ..) en css var.

**Comment by benjamingrolleau** [comment]
Oups ... benj_grolleau c'est mieux !

Allez, go pour le premier chantier, et ensuite go créer une version avec full variables (en base SCSS ou non, à en discuter, je te laisse me contacter). :-)

**Comment by AmauriC** [comment]
Merci !
Si besoin d'info ou d'aide, n'hésites pas 😉

**Comment by raphaelriehl** [comment]
Hello tout le monde,

Désolé, ce ticket est clôturé mais y a t'il du nouveau pour la mise à disposition des variables CSS ?
Ça m'intéresse également ! :)

**Comment by AmauriC** [comment]
Salut,

Pas de changement sur ce point, toujours pas dispo et pas prévu 🙂‍↕️
