### ISSUE TITLE
[SEO] Exclure tarteaucitron

### ISSUE THREAD

**Issue by AmauriC** [AmauriC/tarteaucitron.js#914]
J'ai eu quelques retours où le bandeau tarteaucitron est indexé et affiché dans les résultats de recherche.

Est-ce qu'il existe un attribut ou un moyen de dire aux moteurs de recherche d'ignorer une partie de la page (la div `tarteaucitronRoot`)?

**Comment by benjamingrolleau** [comment]
`data-nosnippet` sur l'élément parent, je pense que ça fonctionnerait.

**Comment by AmauriC** [comment]
Parfait, en effet je pense que ça sera suffisant, merci!
