### ISSUE TITLE
service tawk integration

### ISSUE THREAD

**Issue by yoan34** [AmauriC/tarteaucitron.js#917]
Bonjour,

J'essaye d'intégrer le service **tawk**, j'ai mis:
```
 <script type="text/javascript">
    tarteaucitron.user.tawktoId = 'ID';
    (tarteaucitron.job = tarteaucitron.job || []).push('tawkto');
 </script>
```
et dans le body:
```
<script>tarteaucitron.user.tawktoWidgetId = '1ftpomi2b';</script>
```
Résultat: Je vois bien la demande du consentement du service **tawk** mais une fois accepter, le script n'affiche pas le chatbot.

**Comment by AmauriC** [comment]
Possible d'avoir une url pour que je puisse reproduire le problème?

**Comment by yoan34** [comment]
Si c'est l'URL du site, je fais des tests en local, peut-être que ça marche pas à cause de ça.
