### ISSUE TITLE
Google Analytics 4 - Interdit après acceptation

### ISSUE THREAD

**Issue by FlorientR** [AmauriC/tarteaucitron.js#919]
Bonjour et merci beaucoup pour cette librairie !

J'ai vu dans les issues que le cookie `_ga_XXXX ` était géré via la variable `googleIdentifier` même si on passe via GTM.
Une fois bien configuré tout est ok mais si je change d'avis et que j'interdis GTM, cela supprime bien `_ga` mais pas `_ga_XXXXX`.

Visible sur [https://www.plinedesign.fr](https://www.plinedesign.fr).

La config :

`
tarteaucitron.user.googletagmanagerId = 'GTM-XXXXXXX';
tarteaucitron.user.googleIdentifier = 'VAXXXXXX';
(tarteaucitron.job = tarteaucitron.job || []).push('googletagmanager');
`

Bonne journée !

**Comment by AmauriC** [comment]
Merci! : D

`googleIdentifier` est sur les services GA. Si tu charges GA depuis GTM et que dans les services tac il n'y a pas GA, il est logique que le cookie ne soit pas détruit.

**Comment by FlorientR** [comment]
Ha ok donc impossible d'utiliser TAC avec GTM et GA sans mettre GA dans TAC ?
________________________________

**Comment by AmauriC** [comment]
C'est possible mais pas optimal, tarteaucitron est un tag manager comme GTM, il faut idéalement tout déplacer sur tac et le laisser gérer.

**Comment by FlorientR** [comment]
Ok c'est noté je vais faire comme ça merci !
