### ISSUE TITLE
Analytics : Uncaught ReferenceError: ga is not defined

### ISSUE THREAD

**Issue by ghost** [AmauriC/tarteaucitron.js#92]
Bonjour,

J'ai intégré tarteaucitron avec succès sur plusieurs sites jusqu'à présent sans soucis.

Mais j'ai un site qui envoie des événements à google analytics manuellement, avec un code du genre : 

    $(document).ready(function() {
      ga('send', 'event', 'banner viewed', 'view', 'Banner');
      $('.banner').click(function(e) {
         ga('send', 'event', 'banner clicked', 'view', 'Banner');
      });
    });

Ce code fonctionnait parfaitemement avant l'ajout de tarteaucitron. Voici le service que j'ai chargé :

    <script type="text/javascript">
        tarteaucitron.user.analyticsUa = 'UA-XXXXXXX-X';
        tarteaucitron.user.analyticsMore = function () { /* add here your optionnal ga.push() */ };
        (tarteaucitron.job = tarteaucitron.job || []).push('analytics');
    </script>

Tarteaucitron fonctionne bien, je vois ma popup, tout se passe bien, excepté le message d'erreur sur chaque page : 

    Uncaught ReferenceError: ga is not defined

Et bien entendu, mon événement google analytics qui ne remonte plus....

J'ai tout essayé, chargé mon script avant tarteaucitron, après, mette mon code dans la fonction prévue par tarteaucitron.analyticsMore..... rien n'y fait. 

Je commence a me demander si c'est pas un bug de tarteaucitron qui se verrait incapable d'exécuter des événements google analytics appelés manuellement (ou peut être que si, mais avec un syntaxe propre a tarteaucitron que je ne connais pas).

**Comment by Nabnab9** [comment]
Salut,

ne faut il pas justement appeler les ga(...) dans la fonction analyticsMore ? Comme ceci par exemple : 
``` 
<script type="text/javascript">
    tarteaucitron.user.analyticsUa = 'UA-XXXXXXX-X';
    tarteaucitron.user.analyticsMore = function () { 
        $(document).ready(function() {
             ga('send', 'event', 'banner viewed', 'view', 'Banner');
              $('.banner').click(function(e) {
                       ga('send', 'event', 'banner clicked', 'view', 'Banner');
               });
         });
     };
    (tarteaucitron.job = tarteaucitron.job || []).push('analytics');
</script>
```

**Comment by vincentjpmbb** [comment]
Bonjour !
J'ai l'impression que c'est justement ce que Alex360hd a tenté ("mettre mon code dans la fonction prévue pzr tarteaucitron.analyticsMore").
Je uis arrivé au même constat également hier.
Des pistes ?,

**Comment by Nabnab9** [comment]
Ah oui, j'ai loupé ce bout de phrase, pardon
Hum, il faudrait savoir où l'erreur apparaît, parce que des appels à ga(..) sont également effectués dans le service d'analytics, ça aiguillerai peut-être sur la source du problème

**Comment by GuillaumeKadolis** [comment]
Essaye de remplacer à la ligne 857
`tarteaucitron.addScript('//www.google-analytics.com/analytics.js', '', function () {`
par 
`tarteaucitron.addScript('//www.google-analytics.com/analytics.js', 'ga', function () {`

**Comment by Alex360hd** [comment]
Bonjour à tous,

Tout d'abord merci pour vos nombreux retours.

Effectivement j'avais d'abord essayé de mettre ma fonction dans analyticsMore et ça me ressortait la même erreur.

Je vais essaye de remplacer la ligne 857 par celle suggérée et je vous tiens au courant.

**Comment by Alex360hd** [comment]
Bonjour à tous,

Même problème après avoir remplace la ligne 857 par celle suggérée. J'ai réessayé la totale (script chargé avant, après, dans la fonction analyticsMore), toujours ce ga is not defined....

**Comment by Djullin** [comment]
Salut, j'ai eu un souci similaire avec gtag, du coup j'ai rajouté la fonction de déclaration de ga juste avant le reste du code. Essaye : 

```
tarteaucitron.user.analyticsUa = 'UA-XXXXXXX-X';
    tarteaucitron.user.analyticsMore = function () { 
        $(document).ready(function() {

        window.GoogleAnalyticsObject = 'ga';
        window.ga = window.ga || function () {
            window.ga.q = window.ga.q || [];
            window.ga.q.push(arguments);
        };
        
        ga('send', 'event', 'banner viewed', 'view', 'Banner');
        $('.banner').click(function(e) {
                       ga('send', 'event', 'banner clicked', 'view', 'Banner');
               });
         });
     };
```

**Comment by Europrocurement** [comment]
Bonjour à tous !

@Djullin : quelle est la solution que tu as trouvée pour gtag ?
Je rencontre le même problème : gtag undefined...

Par avance, merci !

**Comment by Djullin** [comment]
Salut @Europrocurement,

j'avais mis la solution juste au dessus, en ajoutant 

window.ga = window.ga || function () {
            window.ga.q = window.ga.q || [];
            window.ga.q.push(arguments);
        };

dans le code ça devrait fonctionner :)

**Comment by Europrocurement** [comment]
@Djullin merci ! 
Je pensais que c'était spécifique à ga.js 😉

**Comment by mfirmignac** [comment]
Bonjour,
apres l'execution de
<script type="text/javascript">
        tarteaucitron.user.analyticsUa = 'XXXXXXX';
        tarteaucitron.user.analyticsMore = function () { /* add here your optionnal ga.push() */ };
        (tarteaucitron.job = tarteaucitron.job || []).push('analytics');
 </script>
j'observe que analytics.js n'est pas chargé
du coup le code suivant sui s'execute au chargement de la page
<script>	
$(document).ready(function() {
  ga(function(tracker) {
  document.getElementById('cid').value = tracker.get('clientId');
  });
});
</script>	
Me declenche un beau :
 ReferenceError: ga is not defined

Quelqu'un a t'il la solution SVP?
Merci de votre aide
Marc

**Comment by Djullin** [comment]
Salut,

ga n'est pas défini au moment où il est appelé dans le script, c'est pour cela qu'il faut rajouter la fonction qui le défini juste avant (solution temporaire mais qui fonctionne) : 

window.GoogleAnalyticsObject = 'ga';
        window.ga = window.ga || function () {
        window.ga.q = window.ga.q || [];
        window.ga.q.push(arguments);
};

Voir ma réponse précédente pour savoir où le mettre :)

**Comment by mfirmignac** [comment]
OK, merci je n'avais pas compris a la premiere lecture
je viens de remplacer ma fonction
<script> $(document).ready(function() { ga(function(tracker) { document.getElementById('cid').value = tracker.get('clientId'); }); }); </script> 
par
<script>
window.GoogleAnalyticsObject = 'ga';
window.ga = window.ga || function () {
window.ga.q = window.ga.q || [];
window.ga.q.push(arguments);
};
	
$(document).ready(function() {
  ga(function(tracker) {
  document.getElementById('cid').value = tracker.get('clientId');
  });
});
</script>	

et effectivement plus d'erreur
Merci Djullin

**Comment by pom421** [comment]
Une solution pour `gtag` qui a l'air de marcher : 

```
tarteaucitron.user.gtagUa = "XX-1234567"
tarteaucitron.user.gtagMore = function () {
  gtag("event", "conversion", {
    allow_custom_scripts: true,
    send_to: "XX-1234567/datadata",
  })
}
;(tarteaucitron.job = tarteaucitron.job || []).push("gtag")

```
