### ISSUE TITLE
Refuser les cookies appelés par GTM

### ISSUE THREAD

**Issue by anhon** [AmauriC/tarteaucitron.js#920]
Bonsoir ! 

J'aimerai savoir si il est possible de refuser des services comme GA ou Facebook Pixel appelés depuis un GTM qui lui même est appelé par TAC ? 
J'ai lu que ce n'était pas optimal d'appelé des services de cette façon car TAC finalement est un gestionnaire comme GTM, hélas je ne peux pas faire autrement car je ne gère pas le compte Google. 

Merci d'avance.

**Comment by AmauriC** [comment]
Non ce ne sera pas possible, tarteaucitron ne pourra pas bloquer les services venant de GTM et le choix de l'utilisateur sera limité à tout accepter/tout refuser.

**Comment by anhon** [comment]
D'accord, merci pour cette réponse claire. Et quelle réactivité, top !

Bonne journée.

**Comment by boulaffasae** [comment]
Hi @AmauriC, au contraire c'est possible de bloquer les services venant de GTM

Il suffit d'utiliser les [data layer](https://developers.google.com/tag-platform/tag-manager/web/datalayer#use_a_data_layer_with_event_handlers), c'est très simple.

https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.js#L913-L927

```js
    "sendEvent" : function(event_key) {
        if(event_key !== undefined) {
            //ie compatibility
            dataLayer.push({'event': event_key});

            //ie compatibility
            var send_event_item;
            if(typeof(Event) === 'function') {
                send_event_item = new Event(event_key);
            }else if (typeof(document.createEvent) === 'function'){
                send_event_item = document.createEvent('Event');
                send_event_item.initEvent(event_key, true, true);
            }
            //end ie compatibility

            document.dispatchEvent(send_event_item);
        }
    },
```

Par la suite, il faut re-configurer le déclencheur sur Google Tag Manager, sélectionnez le type de déclencheur **Événement personnalisé**, Saisissez un nom d'événement _service.key_ _allowed

- youtube_allowed
- facebookpixel_allowed

Axeptio :wink:; https://developers.axeptio.eu/cookies/google-tag-manager/controler-vos-balises-axeptio-avec-google-tag-manager

**Comment by AmauriC** [comment]
Oui mais ce n'est pas dispo si il faut ajouter `dataLayer.push({'event': event_key});` et je n'ai pas envie d'intégrer du Google dans tarteaucitron : /

En utilisant cette technique, il ne faut pas oublier d'ajouter `tarteaucitron.job.push('facebook');` pour ajouter le service au panel tarteaucitron.
