### ISSUE TITLE
Google Maps not loading [WordPress]

### ISSUE THREAD

**Issue by francoisjacquet** [AmauriC/tarteaucitron.js#924]
Hello,

We have tarteaucitron.js v1.6.4 plugin installed at elton-cuisines.com.

We have Google Maps on this page for example:
https://www.elton-cuisines.com/boutiques/elton-lyon-centre

When the plugin is activated, the map is not displayed and the Gmaps JS is not loaded. There is a "Voir la carte" button instead:
![image](https://user-images.githubusercontent.com/4723501/162438126-83b1a622-39c8-4dda-ace3-03e172ddef54.png)

When the plugin is deactivated, the map is displayed:
![image](https://user-images.githubusercontent.com/4723501/162438236-5c5ca17f-0b5c-47b6-b9ce-c285faa04d14.png)

Please note that on tarteaucitron.io, the website is configured to be "automatic".

What has been done for troubleshooting:
- Plugins have been deactivated one by one, the issue still persists.

Thank you.

**Comment by AmauriC** [comment]
Hello

Add this Javascript snippet to force a map reload when tarteaucitron allow google maps:

```
document.addEventListener('googlemaps_loaded', function(){setTimeout(maps_callback, 500);});
```

**Comment by francoisjacquet** [comment]
Thank you @AmauriC , the Javascript code solved the issue :+1:
