### ISSUE TITLE
Support du module Twitter Embeded par Wordpress

### ISSUE THREAD

**Issue by samsam-rolon** [AmauriC/tarteaucitron.js#925]
Hello,

Je voulais savoir s'il est possible (sans le plugin tac) de détecter le module embeded Twitter de Wordpress qui permet de quoter des tweet via tac ?

J'ai essayé en activant tous les module Twitter inclus dans TAC mais il n'est pas détécté.

Merci,
Samuel

**Comment by AmauriC** [comment]
En mode manuel (quand on déclare les services sur la console) tarteaucitron ne bloque pas, il faut supprimer le tag twitter du site et tarteaucitron le remettra après acceptation.

Pour un blocage auto, il faut activer le mode auto sur la console tac ;)

**Comment by samsam-rolon** [comment]
En mode auto ? Je précise que je suis dans le cadre de TAC en mode "Gratuit / Opensource"

Si je comprends le fonctionnement du mode mannuel, si je ne rends plus explicite le module twitter, alors cela fonctionnera ?

**Comment by AmauriC** [comment]
Ce qu'il faut faire en mode manuel c'est retirer du site le widget twitter et utiliser l'intégration tarteaucitron pour le remplacer.
