### ISSUE TITLE
Documenter le paramètre BodyPosition

### ISSUE THREAD

**Issue by lucmuller** [AmauriC/tarteaucitron.js#931]
En travaillant sur un projet, je me suis rendu compte que le paramètre BodyPosition, qui permet de déplacer le HTML de Tac en haut ou bas de page n'était pas documenté sur https://tarteaucitron.io/fr/install/

Cela pourrai être utile le le rendre lisible.

**Comment by AmauriC** [comment]
Merci, c'est fait : )
