### ISSUE TITLE
Firefox / Protection renforcée contre le pistage : pas de bandeau des cookies 

### ISSUE THREAD

**Issue by jblum66** [AmauriC/tarteaucitron.js#938]
Bonjour,

Le bandeau des cookies ne s'affiche pas au chargement sous Firefox si la Protection renforcée contre le pistage est réglée sur "Stricte" au lieu de "Standard". Pourtant Tarte au citron ne semble pas faire appel à une URL sur un domaine tiers. Rencontrez-vous aussi ce problème ?

Merci pour vos avis éclairés !

**Comment by AmauriC** [comment]
Je n'utilise pas Firefox mais je sais que tarteaucitron est sur des listes de blocage utilisées par des adblocker.. c'est sûrement le même principe.

Par exemple la EasyPrivacy: https://easylist.to/

**Comment by loxK** [comment]
En mode renforcé pour moi ça fonctionne sur plusieurs sites.

**Comment by jblum66** [comment]
J'ai constaté cela aussi. Donc le problème n'affecte que mon site et doit venir d'ailleurs. Ce qui est étrange, c'est que Firefox ne liste pas TAC dans les éléments bloqués par le navigateur. Je continue de chercher.

**Comment by CIMEOS** [comment]
Bonjour,

Nous constatons aussi le problème sur Firefox.

Version TAC :  1.14
URL : https://www.reims.fr/#tarteaucitron

Sur Brave, TAC fonctionne en désactivant le Brave Shield.
Sur Chrome, TAC fonctionne en désactivant le blocage des cookies tiers.
Seulement sur Firefox, peu importe le mode de sécurité (Standard,  Stricte, Personnalisé) le bandeau ne s'affiche pas.

Fait notoire : le bandeau est apparu une seule fois en changeant du mode Personnalisé au mode Standard, mais depuis pas moyen de reproduire en changeant le mode (même en supprimant le cookie)

Merci, bonne journée.

**Comment by AmauriC** [comment]
Je viens de tester pleins de sites différents sur Firefox et aucun souci, sauf sur le votre.

Il y a pas mal de modifications sur votre intégration de tarteaucitron.

Commencez par retirer de `$(document).ready(function(){});` l'initialisation de tarteaucitron.
