### ISSUE TITLE
Domain name change on cookie list

### ISSUE THREAD

**Issue by velicuicristian** [AmauriC/tarteaucitron.js#94]
Hello,

The script is great but in that java I can not find one thing. He wants when he lists the cookies where he writes the domain name in my case refurbished-laptop.ro can change with a text like the kind of cookies required.

Can this change be made? If yes, please indicate my line.

Multumessc

**Comment by Nabnab9** [comment]
Hi, 

if I understand it right, you want to add cookies on the list of those which are supposed to be filtered by the script ?

Is it maybe in the service file  `tarteaucitron.services.js` line 879 ? You need to add cookies in the array. 

I'm sorry if I understood it wrong
