### ISSUE TITLE
Usage in ES Module based context

### ISSUE THREAD

**Issue by Blackclaws** [AmauriC/tarteaucitron.js#940]
We're trying to use tarteaucitron in Vue 3 and are hitting a few roadblocks. As is usual for this sort of deployment we want to simply import tarteaucitron like so:

```js
import tarteaucitron from 'tarteaucitronjs'
```

However it seems tarteaucitron does not export itself in any way. Are you planning to release a module based version that exports itself so it can be used in such a way?

**Comment by AmauriC** [comment]
Hey
What will be the best solution to make tac module compatible?

**Comment by hoprikoma** [comment]
I use Svelte and I have the exactly same problem, why release an NPM package if it's just for using cdnjs or alternative.

**Comment by AmauriC** [comment]
What is the solution? I dont use package manager so I dont know how to make it better.

**Comment by hoprikoma** [comment]
I'm a junior dev so I'm not the best person to give advice but I think you need to transform the script to a module with an `export default tarteaucitron`, so peoples can use it with `import tarteaucitron from 'tarteaucitronjs' ` and after use `tarteaucitron.init`.

**Comment by ALTITUDE-DEV-FR** [comment]
> I'm a junior dev so I'm not the best person to give advice but I think you need to transform the script to a module with an `export default tarteaucitron`, so peoples can use it with `import tarteaucitron from 'tarteaucitronjs' ` and after use `tarteaucitron.init`.

Same problem with "Hotwired Turbo" :(
