### ISSUE TITLE
Problème avec le plug-in Wordpress "G-Forms hCaptcha"

### ISSUE THREAD

**Issue by anthodata** [AmauriC/tarteaucitron.js#944]
Bonjour,
Nous avons un petit soucis en essayant d'intégrer un hcaptcha dans un formulaire Gravity Forms avec l'aide du plug-in G-Forms hCaptcha, si nous déclarons le cookie hcaptcha dans tarteaucitron le hcatpcha ne s'affiche plus alors que s'il n'est pas déclaré cela fonctionne bien. Après plusieurs tests de combinaison, nous avons pu observer les choses suivantes :
- si l'on met le paramétrage des services du site en question en **mode automatique** sur l'interface web de tarteaucitron, on se retrouve avec une erreur JS disant : `hcaptcha is not defined`
- si on push le cookie hcaptcha **manuellement** dans le code avec `(tarteaucitron.job = tarteaucitron.job || []).push('hcaptcha');` le hcatpcha s'affiche des fois un peu aléatoirement, ou alors ne s'affiche pas mais aucune erreur ne s'affiche dans la console

Le problème vient visiblement de l'appel du script d'initialisation de hcatpcha avec le `src="https://hcaptcha.com/1/api.js"`, qui est fait automatiquement par le plug-in Wordpress avant la fin du `<body>` puis qui est écrasé et/ou déplacé par tarteaucitron dans le `<head>`. Si cela peut vous donner une piste...
Merci d'avance

**Comment by loxK** [comment]
Pour commencer ce n'est pas un bug de tarteaucitron.js. Il est conçu pour charger les scripts, quand autorisé par le visiteur. Si le plugin WordPress charge lui-même le script, quoiqu'il arrive, ça pose effectivement un problème.

Ceci dit, j'ai jeté un œil au plugin. Je ne vois pas de manière facile de l'empêcher de charger le script de hCaptcha. Regardez avec le développeur. Mais en l'état le plugin n'est pas compatible avec tarteaucitron.js.

**Comment by anthodata** [comment]
Ok, merci pour votre réponse.
