### ISSUE TITLE
script tarteaucitron matomo problème execution

### ISSUE THREAD

**Issue by Romd-s** [AmauriC/tarteaucitron.js#946]
Bonjour, 
Nous avons implémenté matomo il y a peu sur notre site, nous utilisions déjà tarteaucitron pour la gestion des cookies de GA, nous avons donc ajouter matomo de la même manière, en remplissant le script fourni par tarteaucitron pour matomo :    
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="YOUR_MATOMO_URL";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', SITE_ID]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>

Mais il ne semble pas s'executer correctement, si un visiteur refuse tout les cookies la page se reload https://www.smsmode.com/
nous comptions l'ajouter sur des sous-domaines mais lors d'un test en preprod, le même souci (en pire) apparait, la page se reload lors du refus mais la pop up revient également. 

Avez-vous une idée de l'origine du problème ? 
Merci d'avance.

**Comment by Romd-s** [comment]
Désolé, je suis allé un peu vite, c'est bien le code tarteaucitron qui est présent.
<script type="text/javascript">
        tarteaucitron.user.matomoId = X;
        (tarteaucitron.job = tarteaucitron.job || []).push('matomo');
        </script>
        <script>tarteaucitron.user.matomoHost = '//matomo.monsite.fr/';</script>
le tracking fonctionne correctement, comme je le disais le problème est que la page se rafraîchit lorsque un nouveau visiteur choisit de refuser les cookies. et sur un sous domaine testé en preprod, non seulement la page se rafraichit, mais la fenêtre de consentement et toujours là. pour faire simple, il est donc impossible de refuser les cookies 😅. 
Une idée de ce qui peut être à l'origine de ce problème ? 
Merci d'avance

**Comment by AmauriC** [comment]
Le rafraichissement au refus c'est normal, c'est pour supprimer les cookies et retirer le marqueur.

Pour le bandeau qui réapparait en permanence, c'est généralement parce que la valeur `cookieDomain` est invalide.
Pour avoir le même cookie tarteaucitron sur tous les sous domaines il faut mettre comme valeur `.github.com` par exemple pour github.com, xxx.github.com, ... ;)

**Comment by Romd-s** [comment]
merci bcp pour vos réponses, le souci venait bien de la valeur cookieDomain .
