### ISSUE TITLE
GTM et GA4 en mode automatique, GA4 est bloqué

### ISSUE THREAD

**Issue by fmedard** [AmauriC/tarteaucitron.js#948]
Bonjour,
Je fais passer mes propriétés GA3 et GA4 via GTM, avec Tarteaucitron en mode automatique, version pro.
Le mode automatique de Tarteaucitron détecte et **propose uniquement GTM à l'internaute**. 
- Si l'internaute refuse tous les services (donc uniquement GTM) le fonctionnement est normal, aucun cookie ne passe.
- Si l'internaute accepte tous les services, GA3 passe bien dans les Analytics, mais pas GA4.
- Le container GTM a bien été testé en mode preview et fonctionne normalement 
- Si je retire l'appel au script Tarteaucitron, GA3 et GA4 fonctionnent.

Après investigation, en comparant les cookies posés avec et sans le script Tarteaucitron, je constate qu'un cookie manque à l'appel avec Tarteaucitron quand j'autorise tous les services : _ga_EVP8... dans la copie d'écran jointe.
<img width="370" alt="image" src="https://user-images.githubusercontent.com/29124974/169080069-340c752e-036f-488c-bdad-370e9fda6463.png">

J'ai réussi à "régler le problème" en passant ma configuration Tarteaucitron en manuel, avec les services GTM, GA3 et GA4.

Avez-vous rencontré ce problème, et est-il possible de faire fonctionner GTM avec GA4 en mode automatique ? Bizarrement, GA3 fonctionne par défaut

**Comment by AmauriC** [comment]
Je ne pense pas que ce soit lié à GA3 ou GA4 mais ce qui pose problème c’est qu’il y a 2x le même service (GA3 et 4 utilisent le même tag) et tarteaucitron n’en active qu’un.
Pour confirmer vous pouvez supprimer GA3 et voir si GA4 est correctement chargé?

**Comment by fmedard** [comment]
Bonjour,

Je vous remercie pour votre réactivité. J'ai désactivé GA3 dans GTM, le cookie n'est toujours pas posé et je ne trouve pas ma page dans GA. 
Si je passe Tarteaucitron mode manuel en activant les 3 services GTM, GA3 et GA4, ça fonctionne

<img width="767" alt="image" src="https://user-images.githubusercontent.com/29124974/169571751-1c3fa559-6084-4b66-89fb-a90a1100e564.png">

<img width="664" alt="image" src="https://user-images.githubusercontent.com/29124974/169571878-2cf0e0d1-b113-4be0-969a-a303516b540a.png">

<img width="695" alt="image" src="https://user-images.githubusercontent.com/29124974/169572131-53d5e564-09bb-417a-a897-154297473966.png">

**Comment by AmauriC** [comment]
Si vous passez en mode manuel sur tarteaucitron, il faut supprimer les trackers sur le site (code GTM, GA, ..).

En mode auto, charger un second service depuis un premier (dans votre cas GA depuis GTM), le fonctionnement est aléatoire, il est mieux de dissocier les services.

**Comment by pauline-proxilog** [comment]
Bonjour,
Je me permets de reposer une question sur ce ticket car je suis dans le même cas de figure.
Je souhaite conserver le mode automatique de tarteaucitron, cependant je ne comprends pas le sens de "dissocier les services", est-ce que cela veut dire que je dois appeler GA4 en plus de GTM dans le code du site ? Et donc ne plus appeler GA4 via GTM ?
Je vous remercie par avance pour votre aide.

**Comment by pauline-proxilog** [comment]
Merci pour votre réponse très rapide.
Que voulez-vous dire par "tout mettre en direct" ? Voici l'exemple de mon site : https://www.andopack.com/
Je vous remercie par avance pour votre aide.

**Comment by AmauriC** [comment]
Ne pas passer par GTM pour ajouter GA, ads, .. mais les ajouter comme vous avez ajouté GTM.
