### ISSUE TITLE
TAC et le moteur de recherche interne de AT Internet

### ISSUE THREAD

**Issue by thebird5578** [AmauriC/tarteaucitron.js#949]
Bonjour,

nous rencontrons quelques difficultés à récupérer les mots clés saisient dans notre moteur de recherche en passant par la solution décrite dans la doc d'AT Internet, sachant que notre script TAC pour la remonté de l'URL des pages visitées est le suivant ( et fonctionne très bien ) : 

```
<script type="text/javascript">
	    tarteaucitron.user.atMore = function () {
	    	var tag = new ATInternet.Tracker.Tag();
	        setTimeout(function() {
				tag.page.set({
					name: <?php echo oo_TplTools::get_xtpage(); ?>,
					level2: <?php echo oo_TplTools::get_xtn2(); ?> });
 				tag.dispatch();
			}, 1000);
	    }; 
</script>
```

Comment y incorporer le script qui permet l'envoi des mots clés recherchés dans le Tag Manager svp ?

Merci pour votre aide,

TB

**Comment by AmauriC** [comment]
Hello,

Quel est le script a ajouter pour comptabiliser les recherches? En l’incluant dans le `atMore` ça ne fonctionne pas?

**Comment by thebird5578** [comment]
Bonjour,

merci pour votre retour mais nous sommes finalement parvenu à trouver le problème !

Merci,

TB
