### ISSUE TITLE
Utiliser tarteaucitron.getElemAttr dans les services plutôt que elem.getAttribute

### ISSUE THREAD

**Issue by lucmuller** [AmauriC/tarteaucitron.js#955]
Afin d'avoir un code HTML valide, certains attributs comme width et height ne sont pas autorisés.
L'utilisation de elem.getAttribute ne permet pas le fallback vers les attribut data-set.
Cela devient possible si l'on migre les appels à getAttribute dans les services par tarteaucitron.getElemAttr(elem,'attribut').

Il y a actuellement 411 occurence dans le fichier.

Je suis confronte au souci avec le service iframe. Je ne pense pas avoir le temps de tous les convertir.

**Comment by AmauriC** [comment]
En effet c'est un assez gros chantier mais c'est utile. J'essai de m'en occuper quand j'ai un moment.

Merci 👍
