### ISSUE TITLE
Ajout Golden Bees service

### ISSUE THREAD

**Issue by Vanlen1er** [AmauriC/tarteaucitron.js#959]
Salut, 
j'ai ajouté le service de Golden Bees dans tarteaucitron.services.js :

`tarteaucitron.services.goldenbees = {
    "key": "goldenbees",
    "type": "analytic",
    "name": "Golden Bees",
    "uri": "",
    "needConsent": true,
    "cookies": [],
    "js": function () {
      "use strict";
      var gbJsScript = document.createElement("script");
      gbJsScript.src = "https://cdn.goldenbees.fr/proxy?url=http%3A%2F%2Fstatic.goldenbees.fr%2Fcdn%2Fjs%2Fgtag%2Fgoldentag-min.js&attachment=0";
      document.head.appendChild(gbJsScript);
      gbJsScript.addEventListener("load", function() {var gbTag=GbTagBuilder.build("ID");gbTag.fire();})
    },
  };`

Sachant que le code de base qu'on m'a donnée c'est ça :

`<script type="text/javascript">var gbJsScript = document.createElement("script");gbJsScript.src = "https://cdn.goldenbees.fr/proxy?url=http%3A%2F%2Fstatic.goldenbees.fr%2Fcdn%2Fjs%2Fgtag%2Fgoldentag-min.js&attachment=0";document.head.appendChild(gbJsScript);gbJsScript.addEventListener("load", function() {var gbTag=GbTagBuilder.build("ID");gbTag.fire();})</script>`

Et j'ai ajouté ça : `(tarteaucitron.job = tarteaucitron.job || []).push('goldenbees');`

Ca m'a l'air de fonctionner, mais il ajoute le code à la fin du head et on me recommande de le mettre au début de Body, comment je peux faire ?
Merci

**Comment by AmauriC** [comment]
```document.head.appendChild(gbJsScript);``` >> ajout dans le head
```document.body.insertBefore(gbJsScript, document.body.childNodes[0]);``` >> début du body

**Comment by Vanlen1er** [comment]
Nickel merci de ta rapidité :)
