### ISSUE TITLE
Go pro version? but difficult

### ISSUE THREAD

**Issue by Philroque** [AmauriC/tarteaucitron.js#96]
Hello and Thank you for your work.

I tested the script in its free version and now I would like to upgrade to the pro version, the free trial period is run ..
But if I put the custom script for the stats, the sript on the site does not work anymore.

I missed something, but where?

thank you in advance for your advice

**Comment by Fivemy** [comment]
Hello,
Je passerais bien a la version pro direct, mais j'ai un grand doute sur le bon fonctionnement et si j'ai bien lu les CGV les stats doivent fonctionner
