### ISSUE TITLE
Utilisation de plausible comme web analytic

### ISSUE THREAD

**Issue by yoan34** [AmauriC/tarteaucitron.js#960]
Bonjour,

J'ai intégré **[plausible-next](https://www.npmjs.com/package/next-plausible)** comme web analytic. Je sais pas comment le rendre compatible avec Tarteaucitron.
Leur solution principale avec le [script](https://plausible.io/docs/plausible-script)

**Comment by AmauriC** [comment]
Merci! Je viens de l'ajouter : )
