### ISSUE TITLE
New service Snapchat

### ISSUE THREAD

**Issue by AmauriC** [AmauriC/tarteaucitron.js#963]
## Marqueur HTML
```
<!-- Snap Pixel Code --> <script type='text/javascript'> (function(e,t,n){if(e.snaptr)return;var a=e.snaptr=function() {a.handleRequest?a.handleRequest.apply(a,arguments):a.queue.push(arguments)}; a.queue=[];var s='script';r=t.createElement(s);r.async=!0; r.src=n;var u=t.getElementsByTagName(s)[0]; u.parentNode.insertBefore(r,u);})(window,document, 'https://sc-static.net/scevent.min.js'); snaptr('init', 'da4a63cd-b719-49a6-a526-c772fa74a617', { 'user_email': '__INSERT_USER_EMAIL__' }); snaptr('track', 'PAGE_VIEW'); </script> <!-- End Snap Pixel Code -->
```
## Liste des cookies
?

### Site web
https://www.snapchat.com/
### Politique de confidentialité
https://snap.com/fr-FR/privacy/privacy-policy

**Comment by Niels-verbist** [comment]
When I add the Snapchat Pixel Code the Pixel SDK is loaded, but the pixel id itself is not initialized.

Is this a know bug? Or am I doing something wrong while adding the pixel?

`
	<script type="text/javascript">
		tarteaucitron.user.snapchatId = '{{ snapchat_pixel_id }}';
		tarteaucitron.user.snapchatMore = function () { /* add here your optional snapchat function */ };
		(tarteaucitron.job = tarteaucitron.job || []).push('snapchat');
	</script>
	
	<script>
		tarteaucitron.user.snapchatEmail = '{{ snapchat_email }}';
	</script>`
	
If I add the pixel directly to my page without tarteaucitron is does work as expected.

**Comment by AmauriC** [comment]
Do you have a public url where I can reproduce the issue?

**Comment by Niels-verbist** [comment]
Thank you for the quick answer.

I can get you a public url on monday, I was testing it on my local setup so it is not ready to release on our staging server.
GTM, GA, hotjar and facebook all work on my setup by the way.

It’s only the Snapchat Pixel which causes problems, therefore I was wondering whether it works correctly on other websites.


Kind regards,

—
Multimedium steunt "Save Ukrain NOW”
Help jij mee? Klik hier voor meer informatie. <https://www.multimedium.be/save-ukrain-now>
—
Niels Verbist. Web developer.
Multimedium. Digitale doeners, voor digitale durvers.
https://www.multimedium.be
+32 3 297 71 54
—
Minderhoutsestraat 1 - 2320 Hoogstraten (BE)
Multimedium BV - BE 0869.479.888 - RPR Turnhout - IBAN BE49 0014 4062 2071 - BIC GEBABEBB

**Comment by Niels-verbist** [comment]
> Do you have a public url where I can reproduce the issue?

https://channel-6617.staging.tickoweb.be/selection

This staging url contains the Snapchat pixel.

**Comment by Niels-verbist** [comment]
I have fixed the issue myself. It was my own fault. You may ignore my question.
Thank you for the quick response though!

**Comment by AmauriC** [comment]
Thanks for the feedback, I was close to check this ticket : )

**Comment by Niels-verbist** [comment]
One more question:
I've noticed the snapchatEmail is always required.

`if (tarteaucitron.user.snapchatId === undefined || tarteaucitron.user.snapchatEmail === undefined) {
       return;
}`

In the documentation of Snapchat it says it is optional (but highly encouraged):
https://businesshelp.snapchat.com/s/article/pixel-direct-implementation?language=en_US
```
Pass a user parameter.

In order for Snap to potentially match your browser, it’s highly encouraged to pass a user parameter (email or phone number).
```

In my application I only have a user email after the order is finished. Would it be possible to make this value optional so I can also track page views etc. in advance?
