### ISSUE TITLE
how do InfoWindow in google map

### ISSUE THREAD

**Issue by Neodixi** [AmauriC/tarteaucitron.js#969]
Hi,
I use in initialize function
` var infowindow = new google.maps.InfoWindow({ content: '<div id="content"><div id="siteNotice"></div><strong id="firstHeading" class="firstHeading">Hotel Resort Tonicello</strong><div id="bodyContent"><p>My text</p></div></div>' });
        marker.addListener('click', function() { infowindow.open(map, marker); });
        google.maps.event.addListenerOnce(map, 'idle', function(){infowindow.open(map, marker1);});`

How to do in tarteaucitron?
Thank you very much!

**Comment by AmauriC** [comment]
Hi

Try to to embed this code in the following event:

```
document.addEventListener("googlemaps_loaded", function() {
   var infowindow = new google.maps.InfoWindow({ content: '<div id="content"><div id="siteNotice"></div><strong id="firstHeading" class="firstHeading">Hotel Resort Tonicello</strong><div id="bodyContent"><p>My text</p></div></div>' }); marker.addListener('click', function() { infowindow.open(map, marker); }); google.maps.event.addListenerOnce(map, 'idle', function(){infowindow.open(map, marker1);});
}
```


De : Neodixi ***@***.***>
Répondre à : "AmauriC/tarteaucitron.js" ***@***.***>
Date : jeudi 14 juillet 2022 à 08:39
À : "AmauriC/tarteaucitron.js" ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [AmauriC/tarteaucitron.js] how to InfoWindow in google map (Issue #969)


Hi,
I use in initialize function
var infowindow = new google.maps.InfoWindow({ content: '<div id="content"><div id="siteNotice"></div><strong id="firstHeading" class="firstHeading">Hotel Resort Tonicello</strong><div id="bodyContent"><p>My text</p></div></div>' }); marker.addListener('click', function() { infowindow.open(map, marker); }); google.maps.event.addListenerOnce(map, 'idle', function(){infowindow.open(map, marker1);});

How to do in tarteaucitron?
Thank you very much!
