### ISSUE TITLE
Tag Google sur certaines pages

### ISSUE THREAD

**Issue by thierryler** [AmauriC/tarteaucitron.js#972]
Bonjour,

Je voudrais ajouter des tags Google, que j'ai eut dans Google Ads, mais sur certaines pages spécifiquement, et pas sur les autres pages du site, sachant que j'ai déjà un tag global XXXX.

Par exemple, le tag YYYY sur monsite.com/pageY et le tag ZZZZ sur monsite.com/pageZ, en plus du tag Global.

Pour l'instant j'ai juste ça :

```
<script src="/assets/tarteaucitron.js-1.9.7/tarteaucitron.js"></script>

<script>
  tarteaucitron.init({
      "privacyUrl": "/{{ lang }}/cookies", /* Privacy policy url */

      "hashtag": "#tarteaucitron", /* Open the panel with this hashtag */
      "cookieName": "tarteaucitron", /* Cookie name */

      "orientation": "middle", /* Banner position (top - bottom - middle - popup) */

      "groupServices": false, /* Group services by category */

      "showAlertSmall": false, /* Show the small banner on bottom right */
      "cookieslist": true, /* Show the cookie list */
      
      "showIcon": true, /* Show cookie icon to manage cookies */
      // "iconSrc": "", /* Optionnal: URL or base64 encoded image */
      "iconPosition": "BottomLeft", /* Position of the icon between BottomRight, BottomLeft, TopRight and TopLeft */

      "adblocker": false, /* Show a Warning if an adblocker is detected */

      "DenyAllCta" : true, /* Show the deny all button */
      "AcceptAllCta" : true, /* Show the accept all button when highPrivacy on */
      "highPrivacy": true, /* HIGHLY RECOMMANDED Disable auto consent */

      "handleBrowserDNTRequest": false, /* If Do Not Track == 1, disallow all */

      "removeCredit": false, /* Remove credit link */
      "moreInfoLink": true, /* Show more info link */
      "useExternalCss": false, /* If false, the tarteaucitron.css file will be loaded */

      //"cookieDomain": ".my-multisite-domaine.fr", /* Shared cookie for subdomain website */

      "readmoreLink": "", /* Change the default readmore link pointing to tarteaucitron.io */
      
      "mandatory": true, /* Show a message about mandatory cookies */

      "closePopup": false, /* Bouton pour fermer la popup du bas */
  });
</script>
<script type="text/javascript">
  tarteaucitron.user.gtagUa = 'G-XXXX';
  // tarteaucitron.user.gtagCrossdomain = ['example.com', 'example2.com'];
  tarteaucitron.user.gtagMore = function () { /* add here your optionnal gtag() */ };
  (tarteaucitron.job = tarteaucitron.job || []).push('gtag');
</script>
```

Et dans l'interface de Google Ads, j'ai eu ça :

```
<script async src="https://www.googletagmanager.com/gtag/js?id=AW-YYYY"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'AW-YYYYY');
</script>
```

Je voudrais que YYYYY ne soit utilisé que sur la monsite.com/pageY, et qu'il ne soit surtout pas utilisé sur d'autres pages, faute de quoi je ne vais pas pouvoir catcher les objectifs correctement.

Est ce possible de faire ça avec TAC ?

**Comment by AmauriC** [comment]
Il faut utiliser le service Google Ads :

```
        <script type="text/javascript">
        tarteaucitron.user.googleadsId = 'AW-XXXXXXXXX';
        (tarteaucitron.job = tarteaucitron.job || []).push('googleads');
        </script>
```

Ce n'est pas géré par tarteaucitron mais vous pouvez le faire de votre côté en conditionnant l'id en fonction des pages.

**Comment by thierryler** [comment]
Merci pour cette réponse. Mais j'avoue ne pas bien comprendre. J'ai plusieurs tags mais chacun ne doit apparaitre que sur une seule page, cad que même s'il a déjà été affiché, il ne doit pas apparaitre sur les autres pages après.

Est ce qu'il est possible de faire un truc dans ce style ?

```
<?php
if(!isSet(googleadsId)) {
  $googleadsId = null;     // si la variable n'existe pas alors on l'initialise à null pour ne pas planter
}
if($page == 'pageY.html') {     // ici le test sera plus beau au final
  $googleadsId = 'AW-XXXXXXXXX'; 
}
?>

<script type="text/javascript">
tarteaucitron.user.googleadsId = null
(tarteaucitron.job = tarteaucitron.job || []).remove('googleads');  // Necessaire ?

<?php if($googleadsId != null) { ?>
  tarteaucitron.user.googleadsId = '<?= $googleadsId ?>'
<?php } ?>

(tarteaucitron.job = tarteaucitron.job || []).push('googleads');
</script>
```

Est ce que si je fais comme ça, ça va bien vérifier que l'utilisateur a accepté ? Et j'ai peur que, comme on ne propose pas forcément googleads dès la première page, ça ne demande même pas. Ou sinon, il faudrait que j'ai un tag global (pour tout le site), pour bien demander le consentement, et que j'ajoute un second tag sur les pages qui m'intéressent, mais est ce possible d'avoir des pages avec plusieurs tags, vu qu'on fait googleadsId='AW-XXXXXXXXX' ???

**Comment by AmauriC** [comment]
C'est bien ça.

En fonction de la page adaptez l'id Google ads.

L'acceptation n'est pas basé sur l'id, si c'est déjà accepté et que l'id change, ce sera chargé normalement.

**Comment by thierryler** [comment]
Merci pour cette réponse.

Ca veut dire que je dois faire la ligne suivante dans mon template afin que ça demande l'autorisation, même pour les pages non concernées ?
```
(tarteaucitron.job = tarteaucitron.job || []).push('googleads');
```

Ou est ce que je peux le mettre directement dans mon init comme suit et ne plus m'en occuper ensuite ?

```
<script type="text/javascript">
tarteaucitron.user.gtagUa = 'G-XXXX';
tarteaucitron.user.gtagMore = function () { };
(tarteaucitron.job = tarteaucitron.job || []).push('gtag');
(tarteaucitron.job = tarteaucitron.job || []).push('googleads');
</script>
```

et du coup, juste faire ça : 
```
<script type="text/javascript">
tarteaucitron.user.googleadsId = null

<?php if($googleadsId != null) { ?>
  tarteaucitron.user.googleadsId = '<?= $googleadsId ?>'
<?php } ?>
</script>
```

Si tarteaucitron.user.googleadsId est null, il ne va pas essayer de le langer, même si on a googleads dans tarteaucitron.job ?

**Comment by AmauriC** [comment]
Inutile de l'initialiser à vide. Plus simplement :

<script type="text/javascript">
<?php if($googleadsId != null) { ?>
  (tarteaucitron.job = tarteaucitron.job || []).push('googleads');
  tarteaucitron.user.googleadsId = '<?= $googleadsId ?>';
<?php } ?>
</script>

**Comment by thierryler** [comment]
J'ai du manquer une étape. Sur index.php je n'ai pas de tag googlads, donc googleadsid sera null. Donc quand l'utilisateur arrive, on lui affiche la popup de TAC mais sans googleads et il ne va donc pas accepter. Puis l'utilisateur va sur page1.php, et là googleadsid aura une valeur. Mais du coup, il faut lui refaire accepter quelque chose ? ou alors ca ne sera jamais accepté et donc jamais affiché ?...

**Comment by AmauriC** [comment]
Le bandeau réapparaitra au moment ou l'acceptation sera nécessaire.

Pour le faire dès le départ du coup oui, il faut ajouter le service (inutile de définir googleadsId, le push est suffisant pour l'afficher dans le panneau).

**Comment by thierryler** [comment]
OK, je vais l'ajouter dès le départ alors. Ca sera plus simple pour l'utilisateur. 
Merci beaucoup.
