### ISSUE TITLE
Google Adsense / Cadre noir

### ISSUE THREAD

**Issue by vcol** [AmauriC/tarteaucitron.js#975]
Bonjour,
Lorsque les internautes arrivent sur mon site https://www.e-go.fr , les blocs Adsense affichent un cadre noir contenant le message suivant : "Google Adsense est désactivé." .
Si l'internaute accepte tous les cookies, les publicités Adsense apparaissent mais en dessous du fameux cadre noir.
Je ne vois pas de solution pour supprimer ce cadre noir suite au clic sur le bouton "Tout accepter pour poursuivre la navigation".
Merci d'avance @AmauriC pour ton aide.
Vincent

**Comment by AmauriC** [comment]
Merci pour le retour, je viens de publier un correctif : )
https://github.com/AmauriC/tarteaucitron.js/commit/db8924d207398094a11bdbd6effdb89ca44ec199
