### ISSUE TITLE
Soucis sur WordPress

### ISSUE THREAD

**Issue by nbaudine-Sol** [AmauriC/tarteaucitron.js#981]
La liste des cookies sur certaine page est différentes : https://bacasable-siteinternet.soluris.fr/uuuuu/ 
contient le service des vidéos youtube mais https://bacasable-siteinternet.soluris.fr lui ne le contient pas.

Une mauvaise configuration de ma part ?

J'ai déjà désinstaller / réinstaller le plugin etc ...

**Comment by nbaudine-Sol** [comment]
Mais donc à chaque page l'utilisteur devra accepter ou refuser si il y a des services ? 
Il y a pas un mode permettant de pouvoir voir directement tout les cookies du site ?

**Comment by AmauriC** [comment]
Si sur une page un service est présent et n'a pas été accepté/refusé, oui, le bandeau réapparaitra.

Une solution est d'ajouter le js `tarteaucitron.job.push('googlemaps');` par ex pour forcer la demander partout. Voir la doc de l'installation free pour les id:
https://tarteaucitron.io/fr/install/
