### ISSUE TITLE
Problème Wordpress tarteaucitron.user.matomoId

### ISSUE THREAD

**Issue by Samuelk4** [AmauriC/tarteaucitron.js#984]
Bonjour, je rencontre un problème sur 2 sites Wordpress (https://actecil.eu/ & https://rgpd-academy.eu/ - WP v6.0.1 et plugin TaC v1.6.4).
Aléatoirement (mais 4 fois sur 5) le script https://tarteaucitron.io/load.js provoque l'erreur "Uncaught SyntaxError: Unexpected token ':'", ce qui empêche l'exécution de scripts en aval (notamment l'apparition de la pop-in d'acceptation des cookies).

![image](https://user-images.githubusercontent.com/111957159/186351686-e9e683cd-2d0f-4f57-b66b-dede38590eb7.png)

Voici le problème dans le script :
![image](https://user-images.githubusercontent.com/111957159/186349236-604607ff-acd3-4e22-8996-1846eaae961b.png)

Étrangement, tarteaucitron.user.matomoId ne semble pas présent dans le script load.js lorsqu'il n'y a pas d'erreur.

Savez-vous d'où cela peut venir ?

Bien à vous,
Samuel K.

**Comment by AmauriC** [comment]
Modifiez la valeur de MatomoId depuis la console tarteaucitron.
Il faut que ce soit un chiffre. 1 dans votre cas.

Retirez aussi le tag Matomo du site, c'est tarteaucitron qui s'occupe de l'injecter.

**Comment by Samuelk4** [comment]
Bonjour Amauri, merci de votre réponse rapide, cela fonctionne correctement à présent !
