### ISSUE TITLE
Atinternet mode exempt

### ISSUE THREAD

**Issue by pierretux** [AmauriC/tarteaucitron.js#985]
Bonjour,

Sur le site https://solidarites-sante.gouv.fr/ nous sommes toujours en exempt sauf si on change l'option dans la page des gestion des cookie.
Comment corrigé cela ?

Cordialement

**Comment by AmauriC** [comment]
Vous forcez le mode exempt dans le code source du site:

```
tarteaucitron.user.atMore = function () {
  tag.privacy.setVisitorMode('cnil', 'exempt');
  [...]
```

**Comment by pierretux** [comment]
Oui j'ai un test sur le bouton ici https://solidarites-sante.gouv.fr/ministere/article/donnees-personnelles-et-cookies pour savoir si li est in / out 

Comment faire sinon ?

**Comment by AmauriC** [comment]
C'est géré par tarteaucitron.

Ici pour l'option: https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.services.js#L3788
Là pour l'optout/cnil: https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.services.js#L3819

**Comment by pierretux** [comment]
le code de mon bouton http://pastebin.fr/108868 est ok ou pas déjà ?
Si tu peux me dire ce que je dois corrigé car je comprends pas tout la

**Comment by AmauriC** [comment]
A voir avec atinternet, ce n'est pas tarteaucitron cette partie.

Le problème est que c'est toujours en exempt, normal puise que dans le atmore qui est appelé à chaque fois il y a l'instruction pour passer en mode exempt.

Il suffit de la supprimer, voir mon premier message.

**Comment by pierretux** [comment]
Le but est d'arrivé en exempt et si je clic sur un bouton passer dans le in ou le out mais si je vire la ligne indquer j'ai plus rien

**Comment by AmauriC** [comment]
`window.tag.privacy.getVisitorMode()` retourne bien:
- optin quand c'est autorisé sur tarteaucitron (après rechargement de la page)
- Exempt au chargement sans action ou si refus
- Optout si optout depuis la page des cookies

**Comment by pierretux** [comment]
Dc pas besoin que ce soit écrit dans la ligne du hit sur tag inspector

**Comment by pierretux** [comment]
Amauri,

Retour de ATinternet au sujet de mon site

Pierre, 
 
En arrivant sur le site, nous remarquons un hit sans mode visiteur. Sans action de la part du visiteur, aucun cookie "atauthority" n'est envoyé. De ce fait, aucun mode visiteur n'apparaît au sein du hit.
 
Il sera donc nécessaire d'ajuster votre marquage pour que l'exemption CNIL puisse être activée et fonctionnelle dès l'arrivée de votre visiteur sur le site internet.
 
Nous vous invitons donc à déclencher Tarte au citron directement dès le premier événement on-site. Dans notre cas, il aurait fallu que les méthodes Tarte au citron s'activent dès notre premier chargement de page sur votre site. 
 
En ce sens, nous vous invitons donc à modifier votre marquage en ce sens afin de collecter des données en mode exempt dès l'arrivée sur le site. 

Nous restons disponibles pour tout complément d'information.
Bien cordialement,
Mirana Rakotoarivony
AT Internet a Piano company



Que dois je faire dans le code ?

**Comment by AmauriC** [comment]
Ok, compris, c'est corrigé dans le fix ci-dessous.
