### ISSUE TITLE
Cookie en multidomaine

### ISSUE THREAD

**Issue by pierretux** [AmauriC/tarteaucitron.js#986]
Bonjour,

Je ne retrouve pas les infos : j'ai mis en place TAC sur https://dreets.gouv.fr/ mais on me demande que la gestion des cookie soit centralisé.
Un define permet cela ?

Merci

**Comment by AmauriC** [comment]
Il faut ajouter une ligne dans la configuration de tarteaucitron si vous voulez que le consentement tarteaucitron soit le même pour tous les sites .gouv.fr (il faudra faire la manip sur tous les sites):

```
"cookieDomain": ".gouv.fr",
```

**Comment by pierretux** [comment]
Amaury,
On peut géré 2 domaines avec des virgules ? Par exemple des sites en préprod et en prod qui on pas le meme domaine.

**Comment by pierretux** [comment]
Ok donc je ne peux pas le mettre en dur dans le code, je dois le configurer pour géré les 2 cas. Merci

**Comment by AmauriC** [comment]
C'est quoi la valeur de cookiedomain?

Il doit commencer par un point et ne pas y avoir de /

**Comment by pierretux** [comment]
"cookieDomain": ".toto.cloud"

**Comment by AmauriC** [comment]
Quand la bannière reviens c'est que le cookie n'a tarteaucitron n'a pas été créé et j'en reviens à ce que je dis dans le message précédent.

Difficile d'aider plus sans tous les détails de l'installation.

**Comment by pierretux** [comment]
Le code est celui ci 
`tarteaucitron.init({
		"privacyUrl": "", /* Privacy policy url */

		"hashtag": "#tarteaucitron", /* Ouverture automatique du panel avec le hashtag */
		"cookieName": "tarteaucitron", /* Cookie name */

		"orientation": "bottom", /* le bandeau doit être en haut (top) ou en bas (bottom) ? */

		/* Gestion petit bandeau */
		"showAlertSmall": false, /* afficher le petit bandeau en bas à droite ? */
		"cookieslist": false, /* Afficher la liste des cookies installés ? */

		/* Gestion de la petite icone Cookie */
		"showIcon": true, /* Show cookie Icon or not */
		"iconPosition": "BottomRight", /* BottomRight, BottomLeft, TopRight and TopLeft */

		"adblocker": false, /* Afficher un message si un adblocker est détecté */

		/* Gestion grand bandeau */
		"DenyAllCta" : true, /* Show the deny all button */
		"AcceptAllCta" : true, /* Show the accept all button when highPrivacy on */
		"highPrivacy": true, /* Si true, affiche le bandeau de consentement. Sinon, le consentement est implicite. */


		"handleBrowserDNTRequest": false, /* If Do Not Track == 1, disallow all */

		"removeCredit": false, /* supprimer le lien vers la source ? */
		"moreInfoLink": true, /* Show more info link */

		"useExternalCss": false, /* If false, the tarteaucitron.css file will be loaded */
        "useExternalJs": false, /* If false, the tarteaucitron.js file will be loaded */

		"cookieDomain": ".ppreprod.cloud", /* Shared cookie for multisite */

		"readmoreLink": "/article17379", /* Change the default readmore link */
		"mandatory": true, /* Show a message about mandatory cookies */

	});

	var tarteaucitronCustomText = {
		"alertBigPrivacy": 'Ce site utilise des cookies afin de vous proposer des vidéos, des boutons de partage, des remontées de contenus de plateformes sociales et des contenus animés et interactifs.',
		"disclaimer": 'Sur direccte.gouv.fr nous utilisons des outils de mesure d’audience pour comprendre le parcours de navigation des utilisateurs afin d’optimiser l’ergonomie et la mise en avant des contenus les plus pertinents. Certaines fonctionnalités du site (partage de contenus sur les réseaux sociaux, lecteurs vidéos, contenus interactifs) font par ailleurs appel à des services proposés par des tiers. Ces fonctionnalités déposent des cookies permettant aux tiers d’identifier les sites que vous consultez et les contenus auxquels vous vous intéressez. Ces deux types de cookies ne sont déposés que si vous donnez votre accord. Vous pouvez ci-dessous vous informer sur la nature de chacun des cookies déposés, les accepter ou les refuser. Ce choix est possible soit globalement pour l’ensemble du site et l’ensemble des services, soit service par service.',
		"info": 'Gestion de vos préférences sur les cookies',
	}

	var tarteaucitronForceLanguage = 'fr';`
	
Je ne vois pas ce qui le bloque.
Le site n'est pas publique donc pour partagé l'url il me faut un email

**Comment by pierretux** [comment]
oui pas de soucis là

**Comment by AmauriC** [comment]
Ok donc le souci viens d'ailleurs.

La conf semble ok, aucun problème pour que tarteaucitron gère le multi domaine :/

**Comment by pierretux** [comment]
Mais d'où dans ce cas ? dans la lib ?

**Comment by AmauriC** [comment]
Non, sur tarteaucitron il n'y a aucun problème remonté à propos du multidomaine ou de la non prise en compte du consentement.

C'est un problème sur le site mais sans y avoir accès je ne peux pas aider.

**Comment by AmauriC** [comment]
Vu en privée, problème réglé (cache côté navigateur avec un ancien cookie) 👍
