### ISSUE TITLE
Wordpress/contactform7 intégration Google Recaptcha vs tarteaucitron automatique

### ISSUE THREAD

**Issue by theodend** [AmauriC/tarteaucitron.js#988]
Bonjour Amauri,
dans ce cas de figure le recaptcha ne démarre jamais et cela provoque une erreur.
Tarte semble bloquer le script qui ne s'initialise pas même après acceptation utilisateur.

Que faut-il faire ?

**Comment by AmauriC** [comment]
Bonjour,

Le trio tarteaucitron/cf7/recaptcha ne fonctionne pas et je n'ai pas de solution : (

**Comment by theodend** [comment]
Très bien arrêtons d'utiliser Google Recaptcha dans cas ;-)

**Comment by Elimuhub-coder** [comment]
@AmauriC #981
