### ISSUE TITLE
Cookie qui subsiste après le refus

### ISSUE THREAD

**Issue by capetrel** [AmauriC/tarteaucitron.js#992]
Bonjour

J'ai trouvé d'autres issues concernant le problème que je vais évoqué, mais elles sont sans suite.
J'ai installé tarte au citron sur le site de mon client (https://www.les-theatrales.com/), pour gérer Google Tag Manager, Google Analytics 4 et le Pixel Facebook
quand on arrive pour la première fois sur le site il y a bien le cookie tarteaucitron à 'wait' et aucun autres. On accepte tous, les cookies s'installent. Je décide de tous supprimer, les cookie disparaissent, sauf 1 cookie de Google Tag Manager. (capture ci-dessous).

J'ai essayé sur Chrome, Edge, Firefox, depuis une IP différente et j'ai le même comportement.

![tac-theatrale-2](https://user-images.githubusercontent.com/18441194/189697136-0450969a-80ec-45e1-bcfb-67244bffc0b2.png)

![tac-theatrale-3](https://user-images.githubusercontent.com/18441194/189697159-fd486933-4146-4d0c-852a-c9ff6858d49e.png)

**Comment by AmauriC** [comment]
Certains cookies avec des identifiants comme celui-ci ne peuvent pas être supprimé par tac (il faut connaitre le nom complet) mais ce n'est pas un problème, le cookie en soit ne fait rien, le problème c'est quand Google l'utilise.

Quand GTM est désactivé, rien n'est chargé et personne n'utilise le cookie.

**Comment by capetrel** [comment]
Bonjour, merci pour cette réponse claire et rapide, je me permet de fermer l'issue. Merci encore
