### ISSUE TITLE
tag ?

### ISSUE THREAD

**Issue by pierretux** [AmauriC/tarteaucitron.js#998]
Bonjour Amauri,

Le prochain tag est prévu quand ?
Je maintiens à jour un plugins pour le CMS SPIP à partir des tags et le dernier remonte au 15 juillet.

Merci

**Comment by AmauriC** [comment]
Bonjour Pierre,

Je viens d'ajouter plusieurs services, je peux faire un tag maintenant mais dans la semaine je devrais faire des modifs sur l'accessibilité, je pense qu'il faut mieux attendre ces changements ; )

Si lundi pas de nouveau tag, n'hésite pas à me relancer.

**Comment by pierretux** [comment]
Bonsoir Amauri,

Si tu fais l’accessibilité, on attend un peu.
En fait je voulais voir quand tu penses aire des tags, est ce que tu l'on peu envisager un tag par mois par ex ?

**Comment by AmauriC** [comment]
Je viens de créer le nouveau tag 1.9.8

**Comment by AmauriC** [comment]
1.9.9, j'ai une dernière modif.
