### ISSUE TITLE
Personalisation de texte avec du texte en gras

### ISSUE THREAD

**Issue by pierretux** [AmauriC/tarteaucitron.js#999]
On me remonte une possible amélioration https://git.spip.net/spip-contrib-extensions/tarteaucitron/issues/25
Comment géré cela dans le JS ?

**Comment by AmauriC** [comment]
Un saut de ligne ça casse la variable Javascript, il ne faut pas en mettre.

Par contre, vous pouvez utiliser toutes les balises html (<br> pour le saut de ligne, <b>pour mettre en gras</b>, ...) ;)
